### ISSUE TITLE
Inconsistent use of graphicx and color packages in LaTeX preambles

### ISSUE THREAD

**Issue by juliangilbey** [matplotlib/matplotlib#10042]
### Bug report

**Bug summary**

The `backend_ps.py` file imports the graphicx and color packages into the LaTeX preamble after using the custom preamble, whereas `texmanager.py` does not.  I have a context where I am trying to generate both eps and pdf files from the same image (don't ask!), so I've written:

```
plt.savefig('example.pdf', format='pdf')
plt.savefig('example.eps', format='eps')
```

I need the graphicx package for something I'm doing, so I need to include `\usepackage{graphicx}` in `text.latex.preamble`.  But this is unnecessary for generating the eps file, as it's already included in the `backend_ps.py` file, and in fact including it breaks the compilation (inconsistent package options).  On the other hand, the pdf build fails without it.  And it does not seem to be possible to change the options between the two instantiations of savefig.

On the page `https://matplotlib.org/users/customizing.html#customizing-matplotlib`, it says:

```
#text.latex.preamble :  # IMPROPER USE OF THIS FEATURE WILL LEAD TO LATEX FAILURES
                            # AND IS THEREFORE UNSUPPORTED. PLEASE DO NOT ASK FOR HELP
                            # IF THIS FEATURE DOES NOT DO WHAT YOU EXPECT IT TO.
                            # preamble is a comma separated list of LaTeX statements
                            # that are included in the LaTeX document preamble.
                            # An example:
                            # text.latex.preamble : \usepackage{bm},\usepackage{euler}
                            # The following packages are always loaded with usetex, so
                            # beware of package collisions: color, geometry, graphicx,
                            # type1cm, textcomp. Adobe Postscript (PSSNFS) font packages
                            # may also be loaded, depending on your font settings
```
but this is not actually the case, as I've now discovered; there is significant inconsistency between the three files `texmanager.py`, `backend_ps.py` and `backend_pgf.py`.

I don't know whether making the default preamble packages in these three files match each other (and the above description) would be feasible or whether it would be problematic.  Or whether it could maybe become an option (off by default) to prevent existing files breaking?

**Code for reproduction**

```python
import matplotlib.pyplot as plt

plt.rcParams['text.usetex'] = True
plt.rcParams['text.latex.preamble'] = r'\usepackage{graphicx}'

plt.plot([1,2,3,4])

plt.savefig('broken.pdf', format='pdf')
plt.savefig('broken.eps', format='eps')
```

** Actual outcome**

```
~/tempdir $ python3 breakage.py 
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/matplotlib/backends/backend_ps.py", line 1448, in convert_psfrags
    stderr=subprocess.STDOUT)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['latex', '-interaction=nonstopmode', '"/var/folders/13/81nshcj54kn81w0dx5psywz40000gn/T/tmpgaxxmyf5.tex"']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "breakage.py", line 9, in <module>
    plt.savefig('broken.eps', format='eps')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/matplotlib/pyplot.py", line 701, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/matplotlib/figure.py", line 1834, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 2267, in print_figure
    **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/matplotlib/backends/backend_ps.py", line 913, in print_eps
    return self._print_ps(outfile, 'eps', *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/matplotlib/backends/backend_ps.py", line 937, in _print_ps
    **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/matplotlib/backends/backend_ps.py", line 1346, in _print_figure_tex
    orientation)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/matplotlib/backends/backend_ps.py", line 1455, in convert_psfrags
    exc.output.decode("utf-8"))))
RuntimeError: LaTeX was not able to process the following file:
/var/folders/13/81nshcj54kn81w0dx5psywz40000gn/T/tmpgaxxmyf5.tex

Here is the full report generated by LaTeX:
This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017) (preloaded format=latex)
 restricted \write18 enabled.
entering extended mode
(/var/folders/13/81nshcj54kn81w0dx5psywz40000gn/T/tmpgaxxmyf5.tex
LaTeX2e <2017-04-15>
Babel <3.15> and hyphenation patterns for 84 language(s) loaded.
(/usr/local/texlive/2017/texmf-dist/tex/latex/base/article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(/usr/local/texlive/2017/texmf-dist/tex/latex/base/size10.clo))
(/usr/local/texlive/2017/texmf-dist/tex/latex/type1cm/type1cm.sty)
(/usr/local/texlive/2017/texmf-dist/tex/latex/base/textcomp.sty
(/usr/local/texlive/2017/texmf-dist/tex/latex/base/ts1enc.def))
(/usr/local/texlive/2017/texmf-dist/tex/latex/graphics/graphicx.sty
(/usr/local/texlive/2017/texmf-dist/tex/latex/graphics/keyval.sty)
(/usr/local/texlive/2017/texmf-dist/tex/latex/graphics/graphics.sty
(/usr/local/texlive/2017/texmf-dist/tex/latex/graphics/trig.sty)
(/usr/local/texlive/2017/texmf-dist/tex/latex/graphics-cfg/graphics.cfg)
(/usr/local/texlive/2017/texmf-dist/tex/latex/graphics-def/dvips.def)))
(/usr/local/texlive/2017/texmf-dist/tex/latex/geometry/geometry.sty
(/usr/local/texlive/2017/texmf-dist/tex/generic/oberdiek/ifpdf.sty)
(/usr/local/texlive/2017/texmf-dist/tex/generic/oberdiek/ifvtex.sty)
(/usr/local/texlive/2017/texmf-dist/tex/generic/ifxetex/ifxetex.sty)

Package geometry Warning: Over-specification in `h'-direction.
    `width' (462.52756pt) is ignored.


Package geometry Warning: Over-specification in `v'-direction.
    `height' (346.89621pt) is ignored.

) (/usr/local/texlive/2017/texmf-dist/tex/latex/psfrag/psfrag.sty)

! LaTeX Error: Option clash for package graphicx.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.12 \usepackage
                {color}
(/usr/local/texlive/2017/texmf-dist/tex/latex/graphics/color.sty
(/usr/local/texlive/2017/texmf-dist/tex/latex/graphics-cfg/color.cfg)
(/usr/local/texlive/2017/texmf-dist/tex/latex/graphics/dvipsnam.def))
No file tmpgaxxmyf5.aux.
(/usr/local/texlive/2017/texmf-dist/tex/latex/base/ts1cmr.fd)
*geometry* detected driver: dvips
<tmpgaxxmyf5.eps> [1] (./tmpgaxxmyf5.aux) )
(see the transcript file for additional information)
Output written on tmpgaxxmyf5.dvi (1 page, 3092 bytes).
Transcript written on tmpgaxxmyf5.log.
 
```

**Expected outcome**

The expected outcome would be a pair of output files, `broken.pdf` and `broken.eps`.

**Matplotlib version**

  * Operating system: Mac OS 10.13.2; Debian GNU/Linux testing
  * Matplotlib version: 2.1.1 (on Mac OS); 2.0.0 (on Debian)
  * Matplotlib backend (`print(matplotlib.get_backend())`): MacOSX (on Mac OS); TkAgg (on Debian)
  * Python version: 3.6, 2.7 (both versions on both systems tried)
  * Jupyter version (if applicable):
  * Other libraries: 

On Mac OS: matplotlib installed from pip; on Debian, installed as a Debian package.

**Comment by tacaswell** [comment]
We should, at a minimum, make the 3 default pre-ambles match the documentation.   If that proves un-tenable we should update the docs to match what the code does.

Making the all match each other would be good, but I am also not sure what the consequences of that are.

@juliangilbey Can you take a shot at it?

**Comment by juliangilbey** [comment]
Hi @tacaswell I've had a go and created a pull request for the four lines of code which seemed to do the job.  Only I've just discovered that they don't ... so hang on there!

**Comment by juliangilbey** [comment]
Hi @tacaswell - fixed now with second commit.  The following test file works very nicely, even if the files are called broken!

```
import matplotlib
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pgf import FigureCanvasPgf

matplotlib.backend_bases.register_backend('pdf', FigureCanvasPgf)

plt.rcParams['pgf.rcfonts'] = False  # Ignore Matplotlibrc
plt.rcParams['text.usetex'] = True

plt.plot([1,2,3,4])
plt.text(1, 1, r'\textcolor{red}{$y=x$}')

plt.savefig('broken.pdf', format='pdf')
plt.savefig('broken.eps', format='eps')
```

The documentation about which packages are always loaded is a little misleading, and this might be a bit better (albeit longer), especially once this fix is applied:

```
                            # The color and graphicx packages are always loaded with usetex,
                            # so beware of package collisions, and do not try loading these
                            # manually.  The geometry package is also loaded for internal use.
                            # Except in the PGF backend, the font packages type1cm and
                            # textcomp are always loaded, and Adobe Postscript (PSSNFS) font
                            # packages may also be loaded, depending on your font settings.
                            # The PGF backend instead loads fontspec where needed.
```

Best wishes!

**Comment by tacaswell** [comment]
Can you add both of those to your PR?

The tests should go in `tests/test_pgf.py` please.

**Comment by juliangilbey** [comment]
Hi @tacaswell , I'm not quite sure what you mean?  Do you mean to add the test code which now works into the `tests/test_pgf.py` file?  That's one thing; what is the 'both of those'?

Best wishes, 

Julian

**Comment by juliangilbey** [comment]
Test file added to PR!  Seems to work, and have merged in matplotlib/master

**Comment by juliangilbey** [comment]
BTW, the documentation I was referring to is at https://matplotlib.org/tutorials/introductory/customizing.html#sphx-glr-tutorials-introductory-customizing-py
