### ISSUE TITLE
cannot import matplotlib.pyplot

### ISSUE THREAD

**Issue by hproe** [matplotlib/matplotlib#10373]
### Bug report

**Bug summary**

cannot import matplotlib.pyplot

**Code for reproduction**

```python
# Paste your code here
import matplotlib.pyplot as plt
#
```

**Actual outcome**
```
(C:\ProgramData\Anaconda3) C:\Users\hproe_000>python
Python 3.6.3 |Anaconda custom (64-bit)| (default, Oct 15 2017, 03:27:45) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib.pyplot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\hproe_000\AppData\Roaming\Python\Python36\site-packages\matplotlib\pyplot.py", line 116, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "C:\Users\hproe_000\AppData\Roaming\Python\Python36\site-packages\matplotlib\backends\__init__.py", line 60, in pylab_setup
    [backend_name], 0)
  File "C:\Users\hproe_000\AppData\Roaming\Python\Python36\site-packages\matplotlib\backends\backend_tkagg.py", line 15, in <module>
    from matplotlib.backends.backend_agg import FigureCanvasAgg
  File "C:\Users\hproe_000\AppData\Roaming\Python\Python36\site-packages\matplotlib\backends\backend_agg.py", line 409
    GB byte string
          ^
SyntaxError: invalid syntax
>>>

#


**Expected outcome**

no error message

**Matplotlib version**
  * Operating system: Windows 10 Pro 64-bit, version 1709, OS Build 16299.192
  * Matplotlib version: 2.1.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): what command is this?
  * Python version:3.6.3
  * Jupyter version (if applicable): -
  * Other libraries:  none

<!--Please tell us how you installed matplotlib and python e.g., from source, pip, conda--> conda
<!--If you installed from conda, please specify which channel you used if not the default--> conda-forge

cheers, HP

**Comment by timhoffm** [comment]
~~~
File "C:\Users\hproe_000\AppData\Roaming\Python\Python36\site-packages\matplotlib\backends\backend_agg.py", line 409
    GB byte string
~~~

"GB byte string" is not on the given line of 2.1.2 release files. Please check that your backend_agg.py has not been modified accidentally.

**Comment by hproe** [comment]
In fact, my backend_agg.py was corrupted,, i.e. a piece of code was 
missing, which then produced the somewhat cryptic "GB byte string" in 
the error message. No idea how this could have happend but all is well now!
