### ISSUE TITLE
plt.bar() fails on 2D arrays with singleton dimensions.  error message is unhelpful.

### ISSUE THREAD

**Issue by HoniSanders** [matplotlib/matplotlib#10733]
### Bug report

**Bug summary**
plt.bar() only accept 1D arrays, and does not accept 2D arrays with a dimension that has length 1.  E.g., does not accept arrays with shape (3,1).  Unfortunately, the traceback is unhelpful.  

**Code for reproduction**
```python
from matplotlib import pyplot as plt
import numpy as np
plt.bar(np.zeros((2,)),np.zeros((2,1)))
```

**Actual outcome**
```
  File "<stdin>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/pyplot.py", line 2648, in bar
    ret = ax.bar(*args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/__init__.py", line 1717, in inner
    return func(ax, *args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/axes/_axes.py", line 2087, in bar
    label='_nolegend_',
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/patches.py", line 659, in __init__
    Patch.__init__(self, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/patches.py", line 103, in __init__
    self.set_linewidth(linewidth)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/patches.py", line 351, in set_linewidth
    self._linewidth = float(w)
TypeError: only length-1 arrays can be converted to Python scalars
```

**Expected outcome**

plt.bar() should be able to figure out that a 1D vector and a 2D array with a singleton dimension are equivalent.  This can be done by applying squeeze if necessary.  In any case if plt.bar() is going to fail unintuitively on this, it should test to see if the input is a 2D array, and provide an informative error message.  

**Matplotlib version**
  * Operating system: windows, linux, and mac
  * Matplotlib version: most recent 
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version: 2.7 and 3.6
  * Jupyter version (if applicable):
  * Other libraries: 

This code works with matplotlib version 1.4.2 and does not work with 2.1.1.  Other pyplot functions do not exhibit this behavior.  E.g., plt.plot(np.zeros((2,1)),np.zeros((2,1))) works fine.

**Comment by jklymak** [comment]
ping @anntzer You last touched the logic for linewidth here: 

https://github.com/matplotlib/matplotlib/blob/fbcfe76cda4dabe980d7b6abd4cff42f885ddf67/lib/matplotlib/axes/_axes.py#L2221

@bringingheavendown I don't know that we can catch every input and give nice error messages,  but I agree that there is no good reason for `bar` to be more persnickety than `plot`...

**Comment by anntzer** [comment]
Actually I think that came in with @tacaswell's https://github.com/matplotlib/matplotlib/pull/9110 which added broadcasting to linewidths, which is apparently(?) unneeded (it's handled below with itertools.cycle(np.atleast_1d(linewidths))).

**Comment by bringingheavendown** [comment]
More info on comparing behavior of plt.plot() to plt.bar()

```python
>>> import numpy as np
>>> from matplotlib import pyplot as plt
>>> a=np.zeros((2,))
>>> b=np.ones((2,))
>>> c=np.zeros((2,1))
>>> d=np.ones((2,1))
>>> e=np.zeros((1,2))
>>> f=np.ones((1,2))
>>> plt.plot(a,b)
[<matplotlib.lines.Line2D object at 0x1032a5f10>]
>>> plt.figure()
<matplotlib.figure.Figure object at 0x1026f9c90>
>>> plt.plot(c,d)
[<matplotlib.lines.Line2D object at 0x10330a450>]
>>> plt.plot(e,f)
[<matplotlib.lines.Line2D object at 0x1032b7a50>, <matplotlib.lines.Line2D object at 0x10330a9d0>]
>>> plt.bar(a,b)
<Container object of 2 artists>
>>> plt.bar(c,d)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/pyplot.py", line 2648, in bar
    ret = ax.bar(*args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/__init__.py", line 1717, in inner
    return func(ax, *args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/axes/_axes.py", line 2087, in bar
    label='_nolegend_',
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/patches.py", line 659, in __init__
    Patch.__init__(self, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/patches.py", line 103, in __init__
    self.set_linewidth(linewidth)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/patches.py", line 351, in set_linewidth
    self._linewidth = float(w)
TypeError: cannot convert to a float; scalar object is not a number
>>> plt.bar(e,f)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/pyplot.py", line 2648, in bar
    ret = ax.bar(*args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/__init__.py", line 1717, in inner
    return func(ax, *args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/axes/_axes.py", line 2087, in bar
    label='_nolegend_',
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/patches.py", line 659, in __init__
    Patch.__init__(self, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/patches.py", line 103, in __init__
    self.set_linewidth(linewidth)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/patches.py", line 351, in set_linewidth
    self._linewidth = float(w)
TypeError: only length-1 arrays can be converted to Python scalars
```

**Comment by efiring** [comment]
Moving grouped-bar support from hist to bar (#10610) seems like the right way to solve this.  At present, bar specifies 1-D inputs.  I'm leery of putting `squeeze` calls all over the place; I would rather leave it to the user to provide inputs with the appropriate dimensions.

**Comment by bringingheavendown** [comment]
Ok, but there should at least be a reasonable error message if plt.bar() is going to have unintuitive and undocumented requirements on its inputs.

**Comment by jklymak** [comment]
We don't always add strict argument checking.   We added some recently, but that was for a case where the error didn't trigger until `draw()` was called.  

In this case, its pretty clear that a call to `bar` is causing an error in `bar` due to bad argument sizes. So I don't think this is as striong a case, and I'm 50/50 on whether it needs an argument check.  But if someone wanted to put in a PR that did this in a way that didn't break other things and wasn't a lot of extra messy code, I think that would have a decent chance of being accepted.

**Comment by efiring** [comment]
The requirement is documented: "scalar or sequence of scalars" means no more than 1-D.
https://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.bar.html#matplotlib-axes-axes-bar

**Comment by xapple** [comment]
I had this error on a python installation that had `matplotlib` version `3.1.0`

I was able to solve the problem by executing the following command:

    python3 -m pip install --user matplotlib==3.0.3

It seems like this was fixed but then a regression was introduced.
