### ISSUE TITLE
Embedding in Qt example gives AttributeError: 'Figure' object has no attribute 'subplots'

### ISSUE THREAD

**Issue by titusjan** [matplotlib/matplotlib#10855]
### Bug report

**Bug summary**

When I run the example from [Embedding in Qt](https://matplotlib.org/gallery/user_interfaces/embedding_in_qt_sgskip.html) I get an `AttributeError: 'Figure' object has no attribute 'subplots'`, which is strange because according to [the documentation](https://matplotlib.org/api/_as_gen/matplotlib.figure.Figure.html#matplotlib.figure.Figure.subplots) it does.

**Code for reproduction**

The example code is copied below.
```

import sys
import time

import numpy as np

from matplotlib.backends.qt_compat import QtCore, QtWidgets, is_pyqt5
if is_pyqt5():
    from matplotlib.backends.backend_qt5agg import (
        FigureCanvas, NavigationToolbar2QT as NavigationToolbar)
else:
    from matplotlib.backends.backend_qt4agg import (
        FigureCanvas, NavigationToolbar2QT as NavigationToolbar)
from matplotlib.figure import Figure


class ApplicationWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super(ApplicationWindow, self).__init__()
        self._main = QtWidgets.QWidget()
        self.setCentralWidget(self._main)
        layout = QtWidgets.QVBoxLayout(self._main)

        static_canvas = FigureCanvas(Figure(figsize=(5, 3)))
        layout.addWidget(static_canvas)
        self.addToolBar(NavigationToolbar(static_canvas, self))

        dynamic_canvas = FigureCanvas(Figure(figsize=(5, 3)))
        layout.addWidget(dynamic_canvas)
        self.addToolBar(QtCore.Qt.BottomToolBarArea,
                        NavigationToolbar(dynamic_canvas, self))

        self._static_ax = static_canvas.figure.subplots()
        t = np.linspace(0, 10, 501)
        self._static_ax.plot(t, np.tan(t), ".")

        self._dynamic_ax = dynamic_canvas.figure.subplots()
        self._timer = dynamic_canvas.new_timer(
            100, [(self._update_canvas, (), {})])
        self._timer.start()

    def _update_canvas(self):
        self._dynamic_ax.clear()
        t = np.linspace(0, 10, 101)
        # Shift the sinusoid as a function of time.
        self._dynamic_ax.plot(t, np.sin(t + time.time()))
        self._dynamic_ax.figure.canvas.draw()


if __name__ == "__main__":
    qapp = QtWidgets.QApplication(sys.argv)
    app = ApplicationWindow()
    app.show()
    qapp.exec_()

```

**Actual outcome**

My stack strace is:
```
/usr/bin/python3.5 /home/pepijnk/src/egse/python/gssw/quicklook/trials/mpl_test.py
Traceback (most recent call last):
  File "/home/pepijnk/src/egse/python/gssw/quicklook/trials/mpl_test.py", line 52, in <module>
    app = ApplicationWindow()
  File "/home/pepijnk/src/egse/python/gssw/quicklook/trials/mpl_test.py", line 33, in __init__
    self._static_ax = static_canvas.figure.subplots()
AttributeError: 'Figure' object has no attribute 'subplots'

```

**Matplotlib version**

  * Operating system: Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 GNU/Linux
  * Matplotlib version: 2.0.0
  * Matplotlib backend: 'Qt5Agg'
  * Python version: 3.5.3 (installed with debian package manager)

**Comment by tacaswell** [comment]
`Figure.subplots` is a new feature in 2.1.

**Comment by titusjan** [comment]
Ok thanks for the info. I dowloaded the [2.0.0 example](https://matplotlib.org/2.0.0/examples/user_interfaces/embedding_in_qt5.html) and this works for me. 

Case closed :-)
