### ISSUE TITLE
bbox_inches='tight' raises KeyError for JPG and TIF

### ISSUE THREAD

**Issue by astrofrog** [matplotlib/matplotlib#109]
The following script:

```
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

fig = plt.figure()
ax = fig.add_subplot(2,2,1)
ax.scatter([0.5], [0.5])
fig.savefig('test.jpg', bbox_inches='tight')
```

raises the following exception:

```
Traceback (most recent call last):
  File "tif.py", line 8, in <module>
    fig.savefig('test.jpg', bbox_inches='tight')
  File "/Users/tom/Library/Python/2.6/site-packages/matplotlib/figure.py", line 1162, in savefig
    self.canvas.print_figure(*args, **kwargs)
  File "/Users/tom/Library/Python/2.6/site-packages/matplotlib/backend_bases.py", line 1943, in print_figure
    **kwargs)
  File "/Users/tom/Library/Python/2.6/site-packages/matplotlib/backend_bases.py", line 1803, in print_jpg
    return image.save(filename_or_obj, **options)
  File "/Users/tom/Library/Python/2.6/site-packages/PIL/Image.py", line 1423, in save
    raise KeyError(ext) # unknown extension
KeyError: ''
```

and same for TIFF files. If `bbox_inches='tight'` isn't supported, maybe a warning would be better?

I'm using 5df583026510d7bd228c97ddf72964c815fc0493

**Comment by kilojoules** [comment]
I got this error for .jpeg

**Comment by tacaswell** [comment]
@kilojoules What version of mpl are you using?  If it is 1.4.x please create a new issue with a minimal case to reproduce, if it is older, please upgrade and check if you can reproduce on a current version.
