### ISSUE TITLE
BUG: Plot directive fails if its content ends with a normal text line (sphinxext)

### ISSUE THREAD

**Issue by lagru** [matplotlib/matplotlib#11007]
This potential bug concerns the [plot directive](https://matplotlib.org/devel/plot_directive.html) provided by matplotlib to including plots in a Sphinx document.. 
Whether this is actually a bug or just faulty syntax depends on whether you consider the example below to be a valid use case of the plot directive. If that's not the case I want to apologize for taking your time.

I'd be willing to contribute a fix in a PR myself if someone could help me understand the code in question better and find the modifications required to make this work.

### Bug report

**Bug summary**
When using the plot directive in RestructuredText sometimes the plots are not included in the rendered HTML output. This happens when the content of the plot directive ends with a normal text line after invoking the plot. 

It seems like this is happens because the two functions [contains_doctest](https://github.com/matplotlib/matplotlib/blob/v2.2.2/lib/matplotlib/sphinxext/plot_directive.py#L289-L298) and [unescape_doctest](https://github.com/matplotlib/matplotlib/blob/v2.2.2/lib/matplotlib/sphinxext/plot_directive.py#L301-L319) in `plot_directive.py` won't prefix the last line with `#`. As a consequence the last line raises an exception when calling [six.exec_(code, ns)](https://github.com/matplotlib/matplotlib/blob/v2.2.2/lib/matplotlib/sphinxext/plot_directive.py#L524).

Note: I discovered this bug here: https://github.com/scipy/scipy/pull/8627#discussion_r178143548 

**Code for reproduction**
I have created a minimal dummy project to demonstrate the behavior because I couldn't think of a way to invoke this from the REPL: https://github.com/lagru/docstring-plot-bug-demo

As explained in the summary, the bug appears if the indent block of the plot directive ends with "normal" text. Compare the snippet below... 

```rst
# index.rst

.. plot::
   :format: doctest

   If I try to plot something

   >>> import matplotlib.pyplot as plt
   >>> plt.plot([1, 2, 3], [1, 2, 3])
   >>> plt.show()

   Some text.
```

**Actual outcome**
While building the HTML documentation the following error is raised:

```
**/docstring-plot-bug/index.rst:5: WARNING: Exception occurred in plotting index-1 from **s/docstring-plot-bug/index.rst:
Traceback (most recent call last):                                                                                  
  File "**/lib/python3.6/site-packages/matplotlib/sphinxext/plot_directive.py", line 524, in run_code                                                                                                     
    six.exec_(code, ns)                                                                                             
  File "<string>", line 2                                                                                           
    Some text.                                                                                                      
            ^  
SyntaxError: invalid syntax
```

**Expected outcome**
No errors should be raised and the plot should be included in the rendered HTML.

**Versions**
  * Operating system: Manjaro 17.1.7, x86_64 Linux 4.14.30-1-MANJARO
  * Matplotlib version: 2.2.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.6.5 (Anaconda, [GCC 7.2.0] on linux)
  * numpydoc: 0.7.0
  * sphinx: 1.7.2

### Related Links & Discussions

* https://github.com/scipy/scipy/pull/8627#discussion_r178143548
* https://github.com/numpy/numpydoc/issues/162

**Comment by lagru** [comment]
Okay, if I find the time I'll have a look and see if I can figure out an easy fix.
