### ISSUE TITLE
Artists not in Axes can not be animated with blit=True by FuncAnimation

### ISSUE THREAD

**Issue by bersbersbers** [matplotlib/matplotlib#11135]
### Bug report

**Bug summary**

Text cannot be animated with blit=True. Code works fine with blit=False.

**Code for reproduction**

```python
import matplotlib.animation
import matplotlib.pyplot

Animation = matplotlib.animation.FuncAnimation(
    matplotlib.pyplot.figure(),
    lambda x: (matplotlib.pyplot.suptitle(int(x)),),
    frames=1,
    blit=True)
matplotlib.pyplot.show(block=True)
```

**Actual outcome**
This error:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\tkinter\__init__.py", line 1702, in __call__
    return self.func(*args)
  File "C:\Program Files\Python36\lib\tkinter\__init__.py", line 746, in callit
    func(*args)
  File "C:\Program Files\Python36\lib\site-packages\matplotlib\backends\_backend_tk.py", line 88, in _on_timer
    TimerBase._on_timer(self)
  File "C:\Program Files\Python36\lib\site-packages\matplotlib\backend_bases.py", line 1373, in _on_timer
    ret = func(*args, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\matplotlib\animation.py", line 1481, in _step
    still_going = Animation._step(self, *args)
  File "C:\Program Files\Python36\lib\site-packages\matplotlib\animation.py", line 1217, in _step
    self._draw_next_frame(framedata, self._blit)
  File "C:\Program Files\Python36\lib\site-packages\matplotlib\animation.py", line 1237, in _draw_next_frame
    self._post_draw(framedata, blit)
  File "C:\Program Files\Python36\lib\site-packages\matplotlib\animation.py", line 1260, in _post_draw
    self._blit_draw(self._drawn_artists, self._blit_cache)
  File "C:\Program Files\Python36\lib\site-packages\matplotlib\animation.py", line 1274, in _blit_draw
    bg_cache[a.axes] = a.figure.canvas.copy_from_bbox(a.axes.bbox)
AttributeError: 'NoneType' object has no attribute 'bbox'
```

**Expected outcome**

A plot with suptitle 0.

**Matplotlib version**
  * Operating system: Windows 10
  * Matplotlib version: matplotlib==2.2.2
  * Matplotlib backend: TkAgg
  * Python version: 3.6.5
  * Jupyter version (if applicable): none
  * Other libraries: 

Python from https://www.python.org/
Matplotlib using pip

**Comment by ImportanceOfBeingErnest** [comment]
The error above does not actually show any error. But probably it's something like "`Text` has no attribute `axes`" or "`None` has no attribute `bbox`" or so?

Blitting blits the axes, not the complete figure. `plt.suptitle` is not part of any axes. 
But even an axes title, which is part of an axes, would not be visibly updated, simply because it's shown outside of the axes bounding box. 

The least that can be done here is for sure to add a sentence in the docs that figure artists are not supported by blitting. Apart, I'm unsure if blitting should be extended to use the figure instead of the axes. One could probably use the figure bbox instead of the axes to save and restore for blitting; I'm not sure in how far this makes things less efficient (of course a larger image takes longer to restore).

**Comment by bersbersbers** [comment]
@ImportanceOfBeingErnest yes, I had only copied part of the error message by mistake (https://github.com/Microsoft/vscode/issues/18788). I have updated the original post. The error message is indeed `AttributeError: 'NoneType' object has no attribute 'bbox'`.

**Comment by sahmed95** [comment]
Hi, thanks for raising this. I was also trying to blit some text but it didn't work. Any alternative solutions? I am not thinking of making images separately and combining them as a gif.

**Comment by ImportanceOfBeingErnest** [comment]
@sahmed95 The issue here is that text *outside*  of the axes is not updated in the blitting process. You may easily use text within the axes instead. You may also manually blit the text if needed, or write your custom animation to blit the complete figure instead of the axes. If however the aim is to create a gif, blitting is not useful at all (a saved image will always draw each frame in completeness), hence you can simply set `blit=False`.
For help with your issue, you may inquire at Stackoverflow or the mailing list but make sure to detail the use case with a minimal and runnable example code and your attempts to solve the issue.

**Comment by GSh47** [comment]
has there been any fix for the issue ? I have a similar error myself with the _blit_draw's    `cur_view = ax._get_view()`
