### ISSUE TITLE
Errors in the examples for matplotlib.pyplot.streamplot

### ISSUE THREAD

**Issue by xxpittip** [matplotlib/matplotlib#11256]
### Bug report

**Bug summary**

There are multiple errors in the example code of matplotlib.pyplot.streamplot, specifically in the initiation of the meshgrid and the seed_points.

**Code for reproduction**

```python
# Code given in the example
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec

w = 3
Y, X = np.mgrid[-w:w:100j, -w:w:100j]
U = -1 - X**2 + Y
V = 1 + X - Y**2
speed = np.sqrt(U*U + V*V)

fig = plt.figure(figsize=(7, 9))
gs = gridspec.GridSpec(nrows=3, ncols=2, height_ratios=[1, 1, 2])

w = 3
Y, X = np.mgrid[-w:w:100j, -w:w:100j]
U = -1 - X**2 + Y
V = 1 + X - Y**2
speed = np.sqrt(U*U + V*V)

# [more code here (unnecessary to reproduce the errors)]

seed_points = np.array([[-2, -1, 0, 1, 2, -1], [-2, -1,  0, 1, 2, 2]])

ax3 = fig.add_subplot(gs[1, 1])
strm = ax3.streamplot(X, Y, U, V, color=U, linewidth=2,
                     cmap='autumn', start_points=seed_points.T)

# [more code here (unnecessary to reproduce the errors)]
```

**Actual outcome**

```
# If applicable, paste the console output here
Traceback (most recent call last):                                                                                        File "error.py", line 26, in <module>                                                                                     cmap='autumn', start_points=seed_points.T)                                                                            File "C:\Users\Pit\Anaconda3\Anaconda3_ver3\lib\site-packages\matplotlib\__init__.py", line 1818, in inner                return func(ax, *args, **kwargs)                                                                                      File "C:\Users\Pit\Anaconda3\Anaconda3_ver3\lib\site-packages\matplotlib\axes\_axes.py", line 4437, in streamplot         zorder=zorder)                                                                                                        File "C:\Users\Pit\Anaconda3\Anaconda3_ver3\lib\site-packages\matplotlib\streamplot.py", line 140, in streamplot          sp2[:, 0] += np.abs(x[0])                                                                                           ValueError: operands could not be broadcast together with shapes (6,) (100,) (6,) 
```

**Expected outcome**

See images at https://matplotlib.org/gallery/images_contours_and_fields/plot_streamplot.html

**Matplotlib version**

  * Operating system: Windows 10 
  * Matplotlib version: 1.5.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.5.2
  * Jupyter version (if applicable): - 
  * Other libraries: 

Installed via conda

**Working Code**
```python
# This code includes all necessary corrections to produce the images shown in the example

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec

w = 3
y, x = np.linspace(-3,3, 100), np.linspace(-3,3, 100)
X, Y = np.meshgrid(x, y)
U = -1 - X**2 + Y
V = 1 + X - Y**2
speed = np.sqrt(U*U + V*V)

fig = plt.figure(figsize=(7, 9))
gs = gridspec.GridSpec(nrows=3, ncols=2, height_ratios=[1, 1, 2])

#  Varying density along a streamline
ax0 = fig.add_subplot(gs[0, 0])
ax0.streamplot(x, y, U, V, density=[0.5, 1])
ax0.set_title('Varying Density')

# Varying color along a streamline
ax1 = fig.add_subplot(gs[0, 1])
strm = ax1.streamplot(x, y, U, V, color=U, linewidth=2, cmap='autumn')
fig.colorbar(strm.lines)
ax1.set_title('Varying Color')

#  Varying line width along a streamline
ax2 = fig.add_subplot(gs[1, 0])
lw = 5*speed / speed.max()
ax2.streamplot(x, y, U, V, density=0.6, color='k', linewidth=lw)
ax2.set_title('Varying Line Width')

# Controlling the starting points of the streamlines
#seed_points = np.array([[-2, -1, 0, 1, 2, -1], [-2, -1,  0, 1, 2, 2]])
seed_points = np.array([[-2, -2], [-1, -1], [0, 0], [1, 1], [2, 2], [-1, 2]])

ax3 = fig.add_subplot(gs[1, 1])
strm = ax3.streamplot(x, y, U, V, color=U, linewidth=2,
                     cmap='autumn', start_points=seed_points)
#plt.streamplot(x,y, U, V, start_points=start, color="crimson", linewidth=2)
fig.colorbar(strm.lines)
ax3.set_title('Controlling Starting Points')

# Displaying the starting points with blue symbols.
ax3.plot(seed_points[:, 0], seed_points[:, 1], 'bo')
ax3.axis((-w, w, -w, w))

# Create a mask
mask = np.zeros(U.shape, dtype=bool)
mask[40:60, 40:60] = True
U[:20, :20] = np.nan
U = np.ma.array(U, mask=mask)

ax4 = fig.add_subplot(gs[2:, :])
ax4.streamplot(x, y, U, V, color='r')
ax4.set_title('Streamplot with Masking')

ax4.imshow(~mask, extent=(-w, w, -w, w), alpha=0.5,
          interpolation='nearest', cmap='gray', aspect='auto')
ax4.set_aspect('equal')

plt.tight_layout()
plt.show()
```

**Comment by jklymak** [comment]
We generate the example gallery using the code shown, so its unlikely to be broken.

If you want to use 1.5.3, it is best to look at 1.5.3 examples rather than the 2.2.2 ones: https://matplotlib.org/1.5.3/gallery.html

Closing because I don't think there is an error here...

**Comment by xxpittip** [comment]
You are right, i didn't consider the possibility of things like this changing with newer versions of matplotlib. I'm sorry for the trouble.

**Comment by tacaswell** [comment]
Did we document that API change?
