### ISSUE TITLE
savefig and path.py

### ISSUE THREAD

**Issue by Nodd** [matplotlib/matplotlib#11306]
### Bug report

**Bug summary**

Matplotlib now supports Path-like objets like `pathlib.Path`, but it broke the support for `Path` objects from path.py.

**Code for reproduction**

```python
import matplotlib.pyplot as plt

fig = plt.figure()
ax = fig.add_subplot(111)
ax.plot([1, 2, 3])

# Works with a string
fig.savefig("toto.png")

# Works with pathlib
from pathlib import Path
fig.savefig(Path("toto.png"))

# Fails with path.py
from path import Path
fig.savefig(Path("toto.png"))
```

**Actual outcome**

```
Traceback (most recent call last):
  File "mplbug.py", line 20, in <module>
    fig.savefig(Path("toto.png"))
  File "D:\data\Miniconda3\lib\site-packages\matplotlib\figure.py", line 2035, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "D:\data\Miniconda3\lib\site-packages\matplotlib\backends\backend_qt5agg.py", line 94, in print_figure
    super(FigureCanvasQTAgg, self).print_figure(*args, **kwargs)
  File "D:\data\Miniconda3\lib\site-packages\matplotlib\backend_bases.py", line 2263, in print_figure
    **kwargs)
  File "D:\data\Miniconda3\lib\site-packages\matplotlib\backends\backend_agg.py", line 526, in print_png
    with cbook.open_file_cm(filename_or_obj, "wb") as fh:
  File "D:\data\Miniconda3\lib\contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "D:\data\Miniconda3\lib\site-packages\matplotlib\cbook\__init__.py", line 624, in open_file_cm
    fh, opened = to_filehandle(path_or_file, mode, True, encoding)
  File "D:\data\Miniconda3\lib\site-packages\matplotlib\cbook\__init__.py", line 598, in to_filehandle
    flag=flag, return_opened=return_opened, encoding=encoding)
  File "D:\data\Miniconda3\lib\site-packages\matplotlib\cbook\__init__.py", line 598, in to_filehandle
    flag=flag, return_opened=return_opened, encoding=encoding)
  File "D:\data\Miniconda3\lib\site-packages\matplotlib\cbook\__init__.py", line 598, in to_filehandle
    flag=flag, return_opened=return_opened, encoding=encoding)
  [Previous line repeated 972 more times]
  File "D:\data\Miniconda3\lib\site-packages\matplotlib\cbook\__init__.py", line 595, in to_filehandle
    if hasattr(os, "PathLike") and isinstance(fname, os.PathLike):
  File "D:\data\Miniconda3\lib\abc.py", line 184, in __instancecheck__
    if subclass in cls._abc_cache:
  File "D:\data\Miniconda3\lib\_weakrefset.py", line 75, in __contains__
    return wr in self.data
RecursionError: maximum recursion depth exceeded in comparison
```

**Expected outcome**

No traceback.

**Matplotlib version**

  * Operating system: Linux (Ubuntu) and Windows 7
  * Matplotlib version: 2.2.2 from Anaconda
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.6
  * Jupyter version (if applicable):
  * Other libraries: path.py

For information, Path objects from path.py inherit from string and are PathLike objects.

**Comment by Nodd** [comment]
I understand the problem: since `path.Path` is a PathLike, `to_filehandle()` calls itself using `os.fspath()` to get a string. But since `path.Path` is a string, it gets directly returned by `os.fspath()`, not even calling `path.Path.__fspath__`. So the next recursion still gets a PathLike object, and so on...
