### ISSUE TITLE
Travis CI failing on `test_interactive_backend[qt5cairo]`

### ISSUE THREAD

**Issue by jklymak** [matplotlib/matplotlib#11554]
### Bug report

Travis CI tests are all failing on test_interactive_backend[qt5cairo].  i.e. https://travis-ci.org/matplotlib/matplotlib/jobs/399224639

I think...
```
ImportError: Matplotlib qt-based backends require an external PyQt4, PyQt5,
PySide or PySide2 package to be installed, but it was not found.
```

**Comment by anntzer** [comment]
Probably something with the release of pyqt5.11.2 (see also https://github.com/matplotlib/matplotlib/pull/11500#pullrequestreview-131438688, which was re: pyqt5.11.0).

**Comment by jklymak** [comment]
Logs seem to claim that Qt5 is installed OK:

```python
Collecting pyqt5
  Using cached https://files.pythonhosted.org/packages/3a/c7/4a9bec78c864051051b41b4cc76672ecc232e6dc7dbb91a5f8ff6f20ff64/PyQt5-5.11.2-5.11.1-cp35.cp36.cp37.cp38-abi3-manylinux1_x86_64.whl
Collecting PyQt5_sip<4.20,>=4.19.11 (from pyqt5)
  Using cached https://files.pythonhosted.org/packages/c6/b3/04b16d75282a8d8781985dd99955be1eea83f12c48b2605eee3d8a3e97b5/PyQt5_sip-4.19.11-cp36-cp36m-manylinux1_x86_64.whl
Installing collected packages: PyQt5-sip, pyqt5
Successfully installed PyQt5-sip-4.19.11 pyqt5-5.11.2
PyQt5 is available
```

```
   OPTIONAL BACKEND EXTENSIONS
                    macosx: no  [Mac OS-X only]
                    qt5agg: yes [installing, Qt: 5.11.1, PyQt: 5.11.2; PySide2
                            not found]
```

but then it fails later with:

```
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/home/travis/build/matplotlib/matplotlib/lib/matplotlib/pyplot.py", line 113, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/home/travis/build/matplotlib/matplotlib/lib/matplotlib/backends/__init__.py", line 49, in pylab_setup
    backend_mod = importlib.import_module(backend_name)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/travis/build/matplotlib/matplotlib/lib/matplotlib/backends/backend_qt5cairo.py", line 4, in <module>
    from .backend_qt5 import QtCore, QtGui, _BackendQT5, FigureCanvasQT
  File "/home/travis/build/matplotlib/matplotlib/lib/matplotlib/backends/backend_qt5.py", line 15, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "/home/travis/build/matplotlib/matplotlib/lib/matplotlib/backends/qt_editor/figureoptions.py", line 13, in <module>
    import matplotlib.backends.qt_editor.formlayout as formlayout
  File "/home/travis/build/matplotlib/matplotlib/lib/matplotlib/backends/qt_editor/formlayout.py", line 49, in <module>
    from matplotlib.backends.qt_compat import QtGui, QtWidgets, QtCore
  File "/home/travis/build/matplotlib/matplotlib/lib/matplotlib/backends/qt_compat.py", line 200, in <module>
    "Matplotlib qt-based backends require an external PyQt4, PyQt5,\n"
ImportError: Matplotlib qt-based backends require an external PyQt4, PyQt5,
PySide or PySide2 package to be installed, but it was not found.
----------------------------- Captured stderr call -----------------------------
Traceback (most recent call last):
  File "/home/travis/build/matplotlib/matplotlib/lib/matplotlib/backends/qt_compat.py", line 197, in <module>
    from PySide import QtCore, QtGui, __version__, __version_info__
ModuleNotFoundError: No module named 'PySide'
```

**Comment by timhoffm** [comment]
Assuming this is fixed since CI works fine recently.
