### ISSUE TITLE
TkAgg is currently broken (raise an AttributeError when trying to disply a plot)

### ISSUE THREAD

**Issue by NelleV** [matplotlib/matplotlib#11653]
### Bug report

**Bug summary**

The TkAgg backend is currently broken.

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt
plt.stem(np.arange(12))
plt.show()
```

**Actual outcome**

```
In [4]: plt.show()
Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/nelle/.miniconda3/envs/matplotlib/lib/python3.6/tkinter/__init__.py", line 1699, in __call__
    return self.func(*args)
  File "/home/nelle/Projects/matplotlib/lib/matplotlib/backends/_backend_tk.py", line 267, in resize
    self.draw()
  File "/home/nelle/Projects/matplotlib/lib/matplotlib/backends/backend_tkagg.py", line 10, in draw
    _backend_tk.blit(self._tkphoto, self.renderer._renderer, (0, 1, 2, 3))
  File "/home/nelle/Projects/matplotlib/lib/matplotlib/backends/_backend_tk.py", line 90, in blit
    _tkagg.blit(
AttributeError: module 'matplotlib.backends._tkagg' has no attribute 'blit'
Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/nelle/.miniconda3/envs/matplotlib/lib/python3.6/tkinter/__init__.py", line 1699, in __call__
    return self.func(*args)
  File "/home/nelle/.miniconda3/envs/matplotlib/lib/python3.6/tkinter/__init__.py", line 745, in callit
    func(*args)
  File "/home/nelle/Projects/matplotlib/lib/matplotlib/backends/_backend_tk.py", line 346, in idle_draw
    self.draw()
  File "/home/nelle/Projects/matplotlib/lib/matplotlib/backends/backend_tkagg.py", line 10, in draw
    _backend_tk.blit(self._tkphoto, self.renderer._renderer, (0, 1, 2, 3))
  File "/home/nelle/Projects/matplotlib/lib/matplotlib/backends/_backend_tk.py", line 90, in blit
    _tkagg.blit(
AttributeError: module 'matplotlib.backends._tkagg' has no attribute 'blit'

```

**Matplotlib version**

  * Matplotlib version: git hash 7935efcd22a5c47ba0e2cb32856d7c3482401b68
  * Matplotlib backend: TkAgg
  * Python version: 3.6.1
  * Jupyter version (if applicable): NA
  * Other libraries:   tkinter.TkVersion : 8.5

**Comment by ImportanceOfBeingErnest** [comment]
I cannot reproduce this with master (fetched 10 minutes ago, hash 7935efcd2), python 3.6.4, tkinter.TkVersion 8.6 on windows 8. The example code runs fine with this configuration.

**Comment by WeatherGod** [comment]
I can't imagine how this error could happen. hasn't blitting always existed?

**Comment by NelleV** [comment]
I probably just need to rebuild the binaries. I'll double check and will close if that is the caes.

**Comment by ImportanceOfBeingErnest** [comment]
Oh, so I haven't built the binaries for quite some time. If something changed there recently, it could well be that I'm the one who's missing it.

**Comment by jklymak** [comment]
... can't reproduce on a rebuilt master..

**Comment by NelleV** [comment]
Rebuilding didn't help on my end. I'm now trying on a fresh install.

**Comment by NelleV** [comment]
Fresh install fixes the problem, so something is wrong with my old install.

**Comment by WeatherGod** [comment]
yeah, nothing changed for a while now, IIRC. I seriously don't know what
could cause that
