### ISSUE TITLE
can't save as pgf files when calling ax.text with datetime as the xaxis

### ISSUE THREAD

**Issue by marquistj13** [matplotlib/matplotlib#11814]
### Bug report

**Bug summary**

When I use date as tick labels (e.g. [here](https://matplotlib.org/gallery/text_labels_and_annotations/date.html#sphx-glr-download-gallery-text-labels-and-annotations-date-py)), and use `ax.text`,  I can't save the figure as the .pgf file ( I follow the pgf code [here](https://matplotlib.org/users/pgf.html)).

For the above setting, I can save the figure as .pdf, but can't save as .pgf, when using the Qt5Agg backend.
However, when using the pgf backend, I can't save the figure as  .pdf or .pgf files

**Moever, when I comment the `ax.text` line, everything goes well.**
I tried to use numbers as tick labels rather than the datetime, the above  `ax.text`  issue also doesn't exist any more.

**So, it seems that, the `ax.text` can't use datetime for saving as .pgf files?**
(also can't save as pdf files with pgf backend)

For simplicity, I only include the code using date as tick labels, and with the pgf backend.
**Code for reproduction**

```python
# -*- coding: utf-8 -*-
import matplotlib as mpl
mpl.use("pgf")
pgf_with_custom_preamble = {
    "font.family": "serif", # use serif/main font for text elements
    "text.usetex": True,    # use inline math for ticks
    "pgf.rcfonts": False,   # don't setup fonts from rc parameters
    "pgf.preamble": [
         "\\usepackage{units}",         # load additional packages
         "\\usepackage{metalogo}",
         "\\usepackage{unicode-math}",  # unicode math setup
         r"\setmathfont{xits-math.otf}",
         r"\setmainfont{DejaVu Serif}", # serif font via preamble
         ]
}
mpl.rcParams.update(pgf_with_custom_preamble)
import numpy as np
import datetime as dt
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from matplotlib.font_manager import FontProperties
x_date_string= np.array(['2007/1/1', '2007/1/2', '2007/1/3', '2007/1/4', '2007/1/5'])
x=map(lambda x_in:dt.datetime.strptime(x_in, "%Y/%m/%d"),x_date_string)
np.random.seed(0)
y=np.random.random_sample(5)
fig, ax = plt.subplots(figsize=(8,5))
# plot figure
ax.plot(x, y, '.-', markersize= 8)
# set Locator
dayLoc = mdates.DayLocator(interval=1) # every day
ax.xaxis.set_major_locator(dayLoc)
dayFmt = mdates.DateFormatter('%y/%m/%d')
ax.xaxis.set_major_formatter(dayFmt)
# add text
# here is the bug line
ax.text(dt.datetime.strptime("2007/1/1", "%Y/%m/%d"), 0.5, u"Text", fontsize = 20)
ax.set_xlabel(u"€, ü", fontsize = 20)
fig.autofmt_xdate()
plt.savefig("pgf_test.pdf")
plt.savefig("pgf_test.pgf")
```

**Actual outcome**

```
Traceback (most recent call last):
  File "C:/Users/houpe/Documents/GitHub/upcm-npcm/wavelet_fis_example/manual_coed.py", line 39, in <module>
    plt.savefig("pgf_test.pdf")
  File "C:\tools\Anaconda2\lib\site-packages\matplotlib\pyplot.py", line 697, in savefig
    res = fig.savefig(*args, **kwargs)
  File "C:\tools\Anaconda2\lib\site-packages\matplotlib\figure.py", line 1814, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "C:\tools\Anaconda2\lib\site-packages\matplotlib\backend_bases.py", line 2259, in print_figure
    **kwargs)
  File "C:\tools\Anaconda2\lib\site-packages\matplotlib\backends\backend_pgf.py", line 901, in print_pdf
    self._print_pdf_to_fh(fh, *args, **kwargs)
  File "C:\tools\Anaconda2\lib\site-packages\matplotlib\backends\backend_pgf.py", line 855, in _print_pdf_to_fh
    self.print_pgf(fname_pgf, *args, **kwargs)
  File "C:\tools\Anaconda2\lib\site-packages\matplotlib\backends\backend_pgf.py", line 837, in print_pgf
    self._print_pgf_to_fh(fh, *args, **kwargs)
  File "C:\tools\Anaconda2\lib\site-packages\matplotlib\backends\backend_pgf.py", line 818, in _print_pgf_to_fh
    self.figure.draw(renderer)
  File "C:\tools\Anaconda2\lib\site-packages\matplotlib\artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\tools\Anaconda2\lib\site-packages\matplotlib\figure.py", line 1295, in draw
    renderer, self, artists, self.suppressComposite)
  File "C:\tools\Anaconda2\lib\site-packages\matplotlib\image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "C:\tools\Anaconda2\lib\site-packages\matplotlib\artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\tools\Anaconda2\lib\site-packages\matplotlib\axes\_base.py", line 2399, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "C:\tools\Anaconda2\lib\site-packages\matplotlib\image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "C:\tools\Anaconda2\lib\site-packages\matplotlib\artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\tools\Anaconda2\lib\site-packages\matplotlib\text.py", line 799, in draw
    mtext=mtext)
  File "C:\tools\Anaconda2\lib\site-packages\matplotlib\backends\backend_pgf.py", line 662, in draw_tex
    self.draw_text(gc, x, y, s, prop, angle, ismath, mtext)
  File "C:\tools\Anaconda2\lib\site-packages\matplotlib\backends\backend_pgf.py", line 692, in draw_text
    x, y = mtext.get_transform().transform_point(mtext.get_position())
  File "C:\tools\Anaconda2\lib\site-packages\matplotlib\transforms.py", line 1511, in transform_point
    return self.transform(np.asarray([point]))[0]
  File "C:\tools\Anaconda2\lib\site-packages\matplotlib\transforms.py", line 1423, in transform
    res = self.transform_affine(self.transform_non_affine(values))
  File "C:\tools\Anaconda2\lib\site-packages\matplotlib\transforms.py", line 2450, in transform_affine
    return self.get_affine().transform(points)
  File "C:\tools\Anaconda2\lib\site-packages\matplotlib\transforms.py", line 1775, in transform
    return self.transform_affine(values)
  File "C:\tools\Anaconda2\lib\site-packages\matplotlib\transforms.py", line 1859, in transform_affine
    return affine_transform(points, mtx)
ValueError: object too deep for desired array
```

**Matplotlib version**

  * Operating system:  Window 10
  * Matplotlib version:  2.1.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): pgf
  * Python version: 2.7.14 |Anaconda custom (64-bit)| (default, Oct 15 2017, 03:34:40) [MSC v.1500 64 bit (AMD64)]
  * Jupyter version (if applicable):
  * Other libraries: I install the realated libraries by installinig Anaconda

**Comment by ImportanceOfBeingErnest** [comment]
Does it work if you convert to a numerical values first?

    ax.text(mdates.date2num(dt.datetime.strptime("2007/1/1", "%Y/%m/%d")), 0.5, u"Text")

**Comment by marquistj13** [comment]
Yes, it works.
Thanks!
