### ISSUE TITLE
pyplot import fails if filename begins with “inspect”

### ISSUE THREAD

**Issue by Jollywatt** [matplotlib/matplotlib#11893]
### Bug report

**Bug summary**

Import fails if python script is run from file named `inspect.py` or `inspect*.py`.

**Code for reproduction**

In a file named “inspect.py”
```python
from matplotlib import pyplot
```

**Actual outcome**

Running `python inspect.py` produces:
```
Traceback (most recent call last):
  File "Desktop/inspect.py", line 1, in <module>
    from matplotlib import pyplot
  File "/Library/anaconda/lib/python3.6/site-packages/matplotlib/__init__.py", line 111, in <module>
    import inspect
  File "/Users/Joseph/Desktop/inspect.py", line 1, in <module>
    from matplotlib import pyplot
  File "/Library/anaconda/lib/python3.6/site-packages/matplotlib/pyplot.py", line 29, in <module>
    import matplotlib.colorbar
  File "/Library/anaconda/lib/python3.6/site-packages/matplotlib/colorbar.py", line 32, in <module>
    import matplotlib.artist as martist
  File "/Library/anaconda/lib/python3.6/site-packages/matplotlib/artist.py", line 14, in <module>
    from matplotlib import docstring, rcParams
ImportError: cannot import name 'rcParams'
```
Running from `ipython` works as expected.

If file is named `inspectXXX.py` where `XXX` is any string, the error becomes:
```
Traceback (most recent call last):
  File "inspectXXX.py", line 1, in <module>
    from matplotlib import pyplot
  File "/Library/anaconda/lib/python3.6/site-packages/matplotlib/__init__.py", line 111, in <module>
    import inspect
ImportError: bad magic number in 'inspect': b'\x03\xf3\r\n'
```
Again, running from `ipython` works as expected.

**Expected outcome**

Successful import.

**Matplotlib version**

  * Operating system: macOS
  * Matplotlib version: 2.0.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): MacOSX
  * Python version: 3.6.3
  * Jupyter version (if applicable): 4.2.1
  * `which python` gives `/Library/anaconda/bin/python`
  * `which ipython` gives `/Library/anaconda/bin/ipython`

Python installed wiith conda.

**Comment by QuLogic** [comment]
[`inspect` is part of the Python standard library](https://docs.python.org/3/library/inspect.html); you should not name files to clash with it or you will get weird errors like this one. As for your second error, it is possible that you have a cache file `inspect*.pyc` in the directory from the original name that is confusing things.

In any case, this is not a bug in Matplotlib.
