### ISSUE TITLE
Qt binding WLS

### ISSUE THREAD

**Issue by Khalilsqu** [matplotlib/matplotlib#11929]
having problem using qt plotting!

### Bug report

```
Traceback (most recent call last):
  File "/home/khalil/Untitled.py", line 1, in <module>
    import matplotlib.pyplot as plt
  File "/home/khalil/anaconda3/lib/python3.6/site-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/home/khalil/anaconda3/lib/python3.6/site-packages/matplotlib/backends/__init__.py", line 62, in pylab_setup
    [backend_name], 0)
  File "/home/khalil/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_qt5agg.py", line 15, in <module>
    from .backend_qt5 import (
  File "/home/khalil/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_qt5.py", line 19, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "/home/khalil/anaconda3/lib/python3.6/site-packages/matplotlib/backends/qt_editor/figureoptions.py", line 20, in <module>
    import matplotlib.backends.qt_editor.formlayout as formlayout
  File "/home/khalil/anaconda3/lib/python3.6/site-packages/matplotlib/backends/qt_editor/formlayout.py", line 54, in <module>
    from matplotlib.backends.qt_compat import QtGui, QtWidgets, QtCore
  File "/home/khalil/anaconda3/lib/python3.6/site-packages/matplotlib/backends/qt_compat.py", line 158, in <module>
    raise ImportError("Failed to import any qt binding")
ImportError: Failed to import any qt binding
```

**Code for reproduction**

```
import matplotlib.pyplot as plt

plt.plot(range(10))
plt.show()
```

```python
# Paste your code here
#
#
```

**Actual outcome**

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

**Matplotlib version**

  * Operating system: linux ubuntu in windows linux subsystem
  * Matplotlib version: 2.2.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): t5Agg
  * Python version:3.6.5 anaconda 64 for linux
  * Jupyter version (if applicable):
  * Other libraries: 

 Anaconda

**Comment by tacaswell** [comment]
Dose `import PyQt5` work?

**Comment by Khalilsqu** [comment]
no, it is not working too. @tacaswell

**Comment by jklymak** [comment]
You need to install PyQt5 :wink:

**Comment by Khalilsqu** [comment]
I think it is already installed but still I ma getting the same error.  

`>>> import matplotlib.pyplot
````
khalil@khooti:~$ conda list
# packages in environment at /home/khalil/miniconda3:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                   py36_0
blas                      1.0                         mkl
ca-certificates           2018.03.07                    0    anaconda
certifi                   2018.8.13                py36_0    anaconda
cffi                      1.11.5           py36h9745a5d_0
chardet                   3.0.4                    py36_1
conda                     4.5.10                   py36_0    anaconda
conda-env                 2.6.0                         1
cryptography              2.3              py36hb7f436b_0
cryptography-vectors      2.3                      py36_0
cycler                    0.10.0                   py36_0
dbus                      1.13.2               h714fa37_1
expat                     2.2.5                he0dffb1_0
fontconfig                2.13.0               h9420a91_0
freetype                  2.9.1                h8a8886c_0
glib                      2.56.1               h000015b_0
gst-plugins-base          1.14.0               hbbd80ab_1
gstreamer                 1.14.0               hb453b48_1
icu                       58.2                 h9c2bf20_1
idna                      2.7                      py36_0
intel-openmp              2018.0.3                      0
jpeg                      9b                   h024ee3a_2
kiwisolver                1.0.1            py36hf484d3e_0
libedit                   3.1.20170329         h6b74fdf_2
libffi                    3.2.1                hd88cf55_4
libgcc-ng                 8.2.0                hdf63c60_1
libgfortran-ng            7.3.0                hdf63c60_0
libpng                    1.6.34               hb9fc6fc_0
libstdcxx-ng              8.2.0                hdf63c60_1
libuuid                   1.0.3                h1bed415_2
libxcb                    1.13                 h1bed415_1
libxml2                   2.9.8                h26e45fe_1
matplotlib                2.2.3            py36hb69df0a_0
mkl                       2018.0.3                      1
mkl_fft                   1.0.4            py36h4414c95_1
mkl_random                1.0.1            py36h4414c95_1
ncurses                   6.1                  hf484d3e_0
numpy                     1.15.0           py36h1b885b7_0
numpy-base                1.15.0           py36h3dfced4_0
openssl                   1.0.2p               h14c3975_0    anaconda
pcre                      8.42                 h439df22_0
pip                       10.0.1                   py36_0
pycosat                   0.6.3            py36h14c3975_0
pycparser                 2.18                     py36_1
pyopenssl                 18.0.0                   py36_0
pyparsing                 2.2.0                    py36_1
pyqt                      5.9.2            py36h22d08a2_0    anaconda
pysocks                   1.6.8                    py36_0
python                    3.6.6                hc3d631a_0
python-dateutil           2.7.3                    py36_0
pytz                      2018.5                   py36_0
qt                        5.9.6                h52aff34_0
readline                  7.0                  ha6073c6_4
requests                  2.19.1                   py36_0
ruamel_yaml               0.15.46          py36h14c3975_0
setuptools                40.0.0                   py36_0
sip                       4.19.8           py36hf484d3e_0
six                       1.11.0                   py36_1
sqlite                    3.24.0               h84994c4_0
tk                        8.6.7                hc745277_3
tornado                   5.1              py36h14c3975_0
urllib3                   1.23                     py36_0
wheel                     0.31.1                   py36_0
xz                        5.2.4                h14c3975_4
yaml                      0.1.7                had09818_2
zlib                      1.2.11               ha838bed_2
```

**Comment by Khalilsqu** [comment]
sorry 
`import PyQt5` works fine

**Comment by Khalilsqu** [comment]
interestingly, whern running
`>>> import matplotlib.pyplot `
i get this error:
`ImportError: Failed to import any qt binding`

but when running

```
>>> import PyQt5
>>>import matplotlib.pyplot
```

the error is different

`ImportError: libGL.so.1: cannot open shared object file: No such file or directory`

**Comment by pkl728** [comment]
I can confirm I see the same issue as @Khalilsqu.

**Comment by Khalilsqu** [comment]
@pkl728 

I solved the problem by installing nvidia drivers. My machine is using nvidia gtx card and the driver was missing. 

https://askubuntu.com/questions/61396/how-do-i-install-the-nvidia-drivers.

**Comment by Khalilsqu** [comment]
@pkl728 you need also to install qtcreater

https://www.lucidar.me/en/dev-c-cpp/how-to-install-qt-creator-on-ubuntu-18-04/

I am using vcxsrc, 
https://sourceforge.net/projects/vcxsrv/

when launching the server make sure to toggle off the option of Native Opengl, otherwise applications like visual studio code will crash the xserver upon launch.

Here is the steps I followed:

1. toggle on ''Windows Subsystem for linux" from turn windows feature on or off
2. install ubuntu 18 from microsoft store
3. update and upgrade ubuntu. 
sudo apt update
sudo apt upgade
4. sudo apt install build-essential
5. export display=:0.0 you can save it in bash
6. install anaconda, and also accept to install vscode through anaconda
7. sudo apt install qtcreator

start xlaunch and but toggle of Native Opengl. 
code will launch without problem and matplotlib plots graph with qt bindings

**Comment by divenex** [comment]
Thanks @Khalilsqu. I have the same issue under Windows Subsystem for Linux (WSL). Your workaround fixed the error message for me. However, installing both `build-essential` and `qtcreator` requires 260MB of disk space, for an issue which looks like just a wrong path... It would be good to have a proper understanding of the problem and a clean solution for this, but I can live with the workaround.

**Comment by keattang** [comment]
I came across this issue after upgrading from Ubuntu 16.04 to 18.04 and fixed it by installing `python-pyqt5` rather than `python-qt4` which I was previously using. 

Thought I would share in case this helps someone else.

**Comment by keflavich** [comment]
I'm getting the same error on Mac OS X 10.9.5.  Any ideas how to work around it for this OS?  I'm using anaconda, so I wonder if there's a badly-built version of the shared object there?

This is the traceback I get if I import pyqt first; without doing that, my issue is the same as the original.
```
$ ~/anaconda/envs/astropy36mpl3/bin/python -c "import PyQt5; import pylab"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/adam/anaconda/envs/astropy36mpl3/lib/python3.7/site-packages/pylab.py", line 1, in <module>
    from matplotlib.pylab import *
  File "/Users/adam/anaconda/envs/astropy36mpl3/lib/python3.7/site-packages/matplotlib/pylab.py", line 245, in <module>
    from matplotlib import cbook, mlab, pyplot as plt
  File "/Users/adam/anaconda/envs/astropy36mpl3/lib/python3.7/site-packages/matplotlib/pyplot.py", line 2371, in <module>
    switch_backend(rcParams["backend"])
  File "/Users/adam/anaconda/envs/astropy36mpl3/lib/python3.7/site-packages/matplotlib/pyplot.py", line 207, in switch_backend
    backend_mod = importlib.import_module(backend_name)
  File "/Users/adam/anaconda/envs/astropy36mpl3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/adam/anaconda/envs/astropy36mpl3/lib/python3.7/site-packages/matplotlib/backends/backend_qt5agg.py", line 11, in <module>
    from .backend_qt5 import (
  File "/Users/adam/anaconda/envs/astropy36mpl3/lib/python3.7/site-packages/matplotlib/backends/backend_qt5.py", line 15, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "/Users/adam/anaconda/envs/astropy36mpl3/lib/python3.7/site-packages/matplotlib/backends/qt_editor/figureoptions.py", line 13, in <module>
    import matplotlib.backends.qt_editor.formlayout as formlayout
  File "/Users/adam/anaconda/envs/astropy36mpl3/lib/python3.7/site-packages/matplotlib/backends/qt_editor/formlayout.py", line 49, in <module>
    from matplotlib.backends.qt_compat import QtGui, QtWidgets, QtCore
  File "/Users/adam/anaconda/envs/astropy36mpl3/lib/python3.7/site-packages/matplotlib/backends/qt_compat.py", line 142, in <module>
    _setup_pyqt5()
  File "/Users/adam/anaconda/envs/astropy36mpl3/lib/python3.7/site-packages/matplotlib/backends/qt_compat.py", line 76, in _setup_pyqt5
    from PyQt5 import QtCore, QtGui, QtWidgets
ImportError: dlopen(/Users/adam/anaconda/envs/astropy36mpl3/lib/python3.7/site-packages/PyQt5/QtCore.so, 2): Symbol not found: _LSCopyDefaultApplicationURLForURL
  Referenced from: /Users/adam/anaconda/envs/astropy36mpl3/lib/libQt5Core.5.dylib
  Expected in: /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
 in /Users/adam/anaconda/envs/astropy36mpl3/lib/libQt5Core.5.dylib
```

**Comment by ImportanceOfBeingErnest** [comment]
@keflavich Do you get the same error when running

    python -c "from PyQt5 import QtCore, QtGui, QtWidgets"

?

**Comment by keflavich** [comment]
yes:
```
$ ~/anaconda/envs/astropy36mpl3/bin/python -c "from PyQt5 import QtCore, QtGui, QtWidgets"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: dlopen(/Users/adam/anaconda/envs/astropy36mpl3/lib/python3.7/site-packages/PyQt5/QtCore.so, 2): Symbol not found: _LSCopyDefaultApplicationURLForURL
  Referenced from: /Users/adam/anaconda/envs/astropy36mpl3/lib/libQt5Core.5.dylib
  Expected in: /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
 in /Users/adam/anaconda/envs/astropy36mpl3/lib/libQt5Core.5.dylib
```
So I assume this points to a problem with qt, not matplotlib?

**Comment by ImportanceOfBeingErnest** [comment]
Yes, this means it is completely independent of matplotlib. Of course if someone has a solution they can post it here, but I fear from the matplotlib side of things there is little one can do.

**Comment by Ravi-Sage** [comment]
> 
> 
> I got exactly same error. However, my server has no external graphic card.
> 
> My final solution for my CentOS 7.0 server is:
> `yum install mesa-libGL.x86_64`
> 
> It does seem like this issue has something related to graphic card driver.

Thanks a ton...Worked like magic. was stuck with the issue for half day on AWS

**Comment by kawa-marcin** [comment]
> I got exactly same error. However, my server has no external graphic card.
> 
> My final solution for my CentOS 7.0 server is:
> `yum install mesa-libGL.x86_64`
> 
> It does seem like this issue has something related to graphic card driver.

Or for Ubuntu:

```
sudo apt-get install mesa-utils
```

**Comment by RTbecard** [comment]
I had a similar error using pyinstaller in a Ubuntu 20.04 docker container.  With some trial and error checking the pyinstaller logs, my missing PyQt5 dependencies were:
```sh
sudo apt-get install mesa-utils libglib2.0-dev
``` 

which prevented the `Qt5Agg` backend froim being added, throwing the `Failed to import any qt binding` message.
