### ISSUE TITLE
Adding single value scatter plot causes TypeError: Cannot cast array data from dtype('<U1') to dtype('float64') according to the rule 'safe'

### ISSUE THREAD

**Issue by John3-16** [matplotlib/matplotlib#12011]
### Bug report

**Bug summary**

5 scatter plots to plot.  3 work fine (see screen shot) the last 2 are single values to plot and each generate the exception when either or both are added to the plot. If I plot the 2 first the when adding the others the exception is also generated. 

**Code for reproduction**

```python
# Paste your code here
import numpy as np
import sklearn.neighbors as nn
import sklearn.linear_model as lm
import matplotlib.pyplot as plt


# Return density ratio for point x, where each density is a mixture
# of normal with 10 components
def mixnorm(x):
    class1 = np.sum(np.exp(-np.sum((np.sum((m1, -x), axis=0) ** 2), axis=1) * 5.0 / 2.0))
    class0 = np.sum(np.exp(-np.sum((np.sum((m2, -x), axis=0) ** 2), axis=1) * 5.0 / 2.0))
    return class1 / class0
# END mixnorm(x)

csize = 10  # number of centers
p = 2  # dimension for x
s = 1  # standard deviation (sd) for generating x

# centers for 10 Gaussian Distributions
m1 = np.reshape(np.random.normal(size=csize * p), (csize, p)) * s + np.reshape([1, 0] * csize, (csize, p))
m2 = np.reshape(np.random.normal(size=csize * p), (csize, p)) * s + np.reshape([0, 1] * csize, (csize, p))

# Setup training data
n = 200
# Randomly allocate n samples for class 1 and class 0 to the 10 clusters
id1 = np.random.choice(csize, n)
id0 = np.random.choice(csize, n)

s = np.sqrt(float(1) / 5)  # sd for generating x
train_data = np.reshape(np.random.normal(size=2 * n * p), (2 * n, p)) * s \
             + np.concatenate((m1[id1], m2[id0]), axis=0)
Ytrain = np.concatenate(([1] * n, [0] * n))

# Setup testing data
N = 10000
# Randomly allocate n samples for class 1 and class 0 to the 10 clusters
id1 = np.random.choice(csize, N)
id0 = np.random.choice(csize, N)

test_data = np.reshape(np.random.normal(size=2 * N * p), (2 * N, p)) * s + np.concatenate(
    (m1[id1, :], m2[id0, :]), axis=0)
Ytest = np.concatenate(([1] * N, [0] * N))

# Bayes Error
Ytest_pred_Bayes = [mixnorm(x) > 1 for x in test_data]
test_err_Bayes = sum(Ytest != Ytest_pred_Bayes) / float(2 * N)

# Least Square Method
lr = lm.LinearRegression()
lr.fit(train_data, Ytrain)
Ytrain_pred_LSM = (lr.predict(train_data) > 0.5)
Ytest_pred_LSM = (lr.predict(test_data) > 0.5)
train_err_LSM = sum(Ytrain != Ytrain_pred_LSM) / float(2 * n)
test_err_LSM = sum(Ytest != Ytest_pred_LSM) / float(2 * N)

# kNN Method
my_Ks = [151, 101, 69, 45, 31, 21, 11, 7, 5, 3, 1]
m = len(my_Ks)

train_err_kNN = [0] * m
test_err_kNN = [0] * m

for j in range(m):
    kNN = nn.KNeighborsClassifier(n_neighbors=my_Ks[j]).fit(train_data, Ytrain)
    Ytrain_pred = kNN.predict(train_data)
    train_err_kNN[j] = sum(Ytrain != Ytrain_pred) / float(2 * n)
    Ytest_pred = kNN.predict(test_data)
    test_err_kNN[j] = sum(Ytest != Ytest_pred) / float(2 * N)
# END FOR LOOP

# Plot figure
plt.figure(figsize=(10, 6))
pkNN_train = plt.scatter(range(m), train_err_kNN, color="blue", marker="o", alpha=0.5)
pkNN_test = plt.scatter(range(m), test_err_kNN, color="red", marker="o", alpha=0.5)
pbayes = plt.axhline(y=test_err_Bayes, color='green', linestyle='-')
plt.xticks(range(m), my_Ks, rotation=20)
plt.legend((pkNN_train, pkNN_test, pbayes),
           ('train error', 'test error', 'Bayes error'), loc='lower left')
plt.scatter(2, train_err_LSM, s=100, marker='^', facecolor='none', edgecolor='blue', linewidth='2')
# plt.scatter(2, test_err_LSM, s=100, marker='^', facecolor='none', edgecolor='red', linewidth='2')
plt.show()
```

**Actual outcome**

```
# If applicable, paste the console output here
D:\Tools\Anaconda3\envs\UIUC\python.exe "C:\Program Files\JetBrains\PyCharm 2018.2.2\helpers\pydev\pydevd.py" --cmd-line --multiproc --qt-support=auto --client 127.0.0.1 --port 50116 --file D:/GitRepro/UIUC/CS598-PSL/Week1/Assignment_1_5295_rw6.py
pydev debugger: process 7396 is connecting

Connected to pydev debugger (build 182.4129.34)
Backend Qt5Agg is interactive backend. Turning interactive mode on.
Traceback (most recent call last):
  File "D:\Tools\Anaconda3\envs\UIUC\lib\site-packages\matplotlib\backends\backend_qt5.py", line 519, in _draw_idle
    self.draw()
  File "D:\Tools\Anaconda3\envs\UIUC\lib\site-packages\matplotlib\backends\backend_agg.py", line 437, in draw
    self.figure.draw(self.renderer)
  File "D:\Tools\Anaconda3\envs\UIUC\lib\site-packages\matplotlib\artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "D:\Tools\Anaconda3\envs\UIUC\lib\site-packages\matplotlib\figure.py", line 1493, in draw
    renderer, self, artists, self.suppressComposite)
  File "D:\Tools\Anaconda3\envs\UIUC\lib\site-packages\matplotlib\image.py", line 141, in _draw_list_compositing_images
    a.draw(renderer)
  File "D:\Tools\Anaconda3\envs\UIUC\lib\site-packages\matplotlib\artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "D:\Tools\Anaconda3\envs\UIUC\lib\site-packages\matplotlib\axes\_base.py", line 2635, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "D:\Tools\Anaconda3\envs\UIUC\lib\site-packages\matplotlib\image.py", line 141, in _draw_list_compositing_images
    a.draw(renderer)
  File "D:\Tools\Anaconda3\envs\UIUC\lib\site-packages\matplotlib\artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "D:\Tools\Anaconda3\envs\UIUC\lib\site-packages\matplotlib\collections.py", line 911, in draw
    Collection.draw(self, renderer)
  File "D:\Tools\Anaconda3\envs\UIUC\lib\site-packages\matplotlib\artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "D:\Tools\Anaconda3\envs\UIUC\lib\site-packages\matplotlib\collections.py", line 337, in draw
    self._offset_position)
  File "D:\Tools\Anaconda3\envs\UIUC\lib\site-packages\matplotlib\backends\backend_agg.py", line 129, in draw_path_collection
    return self._renderer.draw_path_collection(*kl, **kw)
TypeError: Cannot cast array data from dtype('<U1') to dtype('float64') according to the rule 'safe'
```

**Expected outcome**

  Plot showing the 2 single data points along with the other scatter plots.

Don't know what version it worked before, but it has worked before

**Matplotlib version**

  * Operating system:  Windows 10 1803
  * Matplotlib version: 2.2.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): 'Qt5Agg'
  * Python version:  3.6.5
  * Jupyter version (if applicable):
  * Other libraries: 

 Installed using conda

build channel:  py36hd159220_0

Plot of the 3 scatter plots that works before adding the single value scatter plot.
![working_without_final_2scatterplots_2018-09-03_22-16-55](https://user-images.githubusercontent.com/18647491/45006899-1d51fd80-afc9-11e8-9dda-4bc3c79908d3.png)

**Comment by jklymak** [comment]
This will get more notice if you can make it far more minimal.   As it reads I have no idea what statement is causing the error though I guess it’s the last scatter call.  If so, What is the value and type of train_err_lsm?

**Comment by John3-16** [comment]
This line causes the error:  plt.scatter(2, train_err_LSM, s=100, marker='^', facecolor='none', edgecolor='blue', linewidth='2')

The train_err_LSM has a single float64 value for example 0.115

**Comment by John3-16** [comment]
I managed to rollback to matplotlib=2.0.2, retested and no error is generated using the same code.

**Comment by jklymak** [comment]
Here is a minimal self-contained working example:

```python
import matplotlib.pyplot as plt

fig, ax = plt.subplots()
ax.scatter(2, 1.15, s=100, marker='^', facecolor='none', edgecolor='blue', linewidth='2')
plt.show()
```
Your error is that line width should be a float not a string.  There was some type casting we did for you in 2.x that no longer is being done to keep other things consistent. i.e. this works:

```python
import matplotlib.pyplot as plt

fig, ax = plt.subplots()
ax.scatter(2, 1.15, s=100, marker='^', facecolor='none', edgecolor='blue', linewidth=2)
plt.show()
```

I'm closing because we are not going to go back to casting line width strings to numbers based on previous discussions.

**Comment by John3-16** [comment]
Thanks it works with the new version now.
