### ISSUE TITLE
MacOS: Cannot import name 'format_exc'

### ISSUE THREAD

**Issue by fralau** [matplotlib/matplotlib#12160]
### Bug report

**Bug summary**

When importing matplotlib on Macos (python 3.6 or 3.7), an ImportError occurs with `Cannot import name 'format_exc`

**Code for reproduction**

```python
import matplotlib.pyplot as plt
```

**Actual outcome**

```
Frame 19: File <frozen importlib._bootstrap>:_find_and_load, line: 971
Frame 20: File <frozen importlib._bootstrap>:_call_with_frames_removed, line: 219
Frame 21: File <frozen importlib._bootstrap>:_find_and_load_unlocked, line: 941
Frame 22: File <frozen importlib._bootstrap>:_find_and_load, line: 971
Frame 23: File split_no.py:<module>, line: 95
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 140, in <module>
    import threading
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 7, in <module>
    from traceback import format_exc as _format_exc
ImportError: cannot import name 'format_exc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "split_no.py", line 95, in <module>
    import matplotlib.pyplot as plt
  File "/usr/local/lib/python3.6/site-packages/matplotlib/__init__.py", line 134, in <module>
    import subprocess
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 142, in <module>
    import dummy_threading as threading
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/dummy_threading.py", line 45, in <module>
    import threading
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 7, in <module>
    from traceback import format_exc as _format_exc
ImportError: cannot import name 'format_exc'
```

**Expected outcome**

Import should work

**Matplotlib version**

  * Operating system: MacOS 10.12.6
  * Matplotlib version: 3.0.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): *N/A*
  * Python version: 3.6.5

Matplotlib installed with pip3.

**Comment by dstansby** [comment]
That looks like a python error and not a Matplotlib error; if you start python and just run
```python
from traceback import format_exc as _format_exc
```
Does it give you an error? If so I would suggest re-installing python and seeing if that fixes it.

**Comment by fralau** [comment]
Hi, thanks for your answer

Here is why I get:
```
$ python3
Python 3.6.5 (default, Apr 27 2018, 08:41:22)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from traceback import format_exc as _format_exc
>>>
```
That sounds OK?

**Comment by dstansby** [comment]
No worries, glad you got it sorted!

**Comment by tacaswell** [comment]
> I found the root cause: it's my mistake and it's both silly and instructive. By accident, I had a file called traceback.py in the directory... I changed its name and everything was straightened out.

This is a problem more often than you would think!

**Comment by anjalinagel12** [comment]
from matplotlib import (
ImportError: cannot import name 'get_backend'

getting this error
