### ISSUE TITLE
Can't import matplotlib

### ISSUE THREAD

**Issue by beojan** [matplotlib/matplotlib#12601]
### Bug report

**Bug summary**

Importing matplotlib fails with `ImportError: cannot import name 'get_backend' from 'matplotlib'`.

**Code for reproduction**

```python
import matplotlib
```

**Actual outcome**

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/site-packages/matplotlib/__init__.py", line 1080, in <module>
    rcParamsOrig = RcParams(rcParams.copy())
  File "/usr/lib/python3.7/site-packages/matplotlib/__init__.py", line 870, in __getitem__
    from matplotlib import pyplot as plt
  File "/usr/lib/python3.7/site-packages/matplotlib/pyplot.py", line 33, in <module>
    import matplotlib.image
  File "/usr/lib/python3.7/site-packages/matplotlib/image.py", line 18, in <module>
    from matplotlib.backend_bases import FigureCanvasBase
  File "/usr/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 46, in <module>
    from matplotlib import (
ImportError: cannot import name 'get_backend' from 'matplotlib' (/usr/lib/python3.7/site-packages/matplotlib/__init__.py)
```

**Expected outcome**

Matplotlib is imported

**Matplotlib version**

  * Operating system: GNU/Linux
  * Matplotlib version: 3.0 git master
  * Python version: 3.7.1

Python from Arch repo, matplotlib from git master.

**Comment by anntzer** [comment]
I can repro with 3.7.1 (but not 3.7.0, even though the changelog doesn't say anything about the import system...).

**Comment by ArchangeGabriel** [comment]
I can confirm by building from master branch in a clean chroot, during the tests part:
```
E   _pytest.config.ConftestImportFailure: (local('/build/python-matplotlib-git/src/matplotlib-test/lib/matplotlib/tests/conftest.py'), (<class 'ImportError'>, ImportError("cannot import name 'get_backend' from 'matplotlib' (/build/python-matplotlib-git/src/matplotlib-test/lib/matplotlib/__init__.py)"), <traceback object at 0x7f591217ff08>))
```

**Comment by QuLogic** [comment]
CI is also failing on this same issue.

**Comment by tacaswell** [comment]
I clearly have not been doing enough development work recently as I missed this in my all-the-master-branch enviroment  :disappointed:
