### ISSUE TITLE
auto-ticks do not handle values near bounds gracefully

### ISSUE THREAD

**Issue by UziFTW** [matplotlib/matplotlib#12655]
### Unexpected IndexError

I am having an issue with matplotlib where I am attempting to plot data from a Pandas dataframe. Upon trying to plot the data I get an IndexError. The data I am plotting is from an ajax request on BitcoinCharts. I am fetching the data from: http://bitcoincharts.com/charts/chart.json?m=bitstampUSD#rg360zig12-hourztgSzm1g10zm2g25zv

The shape of my dataframe is (2603, 8)
```
url = 'http://bitcoincharts.com/charts/chart.json?m=bitstampUSD#rg360zig12-hourztgSzm1g10zm2g25zv'
data = np.array(json.loads(requests.get(url).content))

cols=['timestamp', 'open', 'high', 'low', 'close', 'volume_btc', 'volume_curr', 'weighted_price']
df=pd.DataFrame(data, columns=cols)
df.head()

plt.plot(df['close'])

```

**Outcome**

```
Warning (from warnings module):
  File "C:\Users\uzair\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\transforms.py", line 2902
    elif vmax - vmin <= maxabsvalue * tiny:
RuntimeWarning: overflow encountered in double_scalars
Warning (from warnings module):
  File "C:\Users\uzair\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\transforms.py", line 429
    return (x0, y0, x1 - x0, y1 - y0)
RuntimeWarning: overflow encountered in double_scalars
Warning (from warnings module):
  File "C:\Users\uzair\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\axis.py", line 1081
    warnings.warn("Unable to find pixel distance along axis "
UserWarning: Unable to find pixel distance along axis for interval padding of ticks; assuming no interval padding needed.
Warning (from warnings module):
  File "C:\Users\uzair\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\axis.py", line 1091
    warnings.warn("Unable to find pixel distance along axis "
UserWarning: Unable to find pixel distance along axis for interval padding of ticks; assuming no interval padding needed.
Warning (from warnings module):
  File "C:\Users\uzair\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\ticker.py", line 1757
    dv = abs(vmax - vmin)  # > 0 as nonsingular is called before.
RuntimeWarning: overflow encountered in double_scalars
Warning (from warnings module):
  File "C:\Users\uzair\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\ticker.py", line 1942
    raw_step = (_vmax - _vmin) / nbins
RuntimeWarning: overflow encountered in double_scalars
Warning (from warnings module):
  File "C:\Users\uzair\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\ticker.py", line 1949
    istep = np.nonzero(steps >= raw_step)[0][0]
RuntimeWarning: invalid value encountered in greater_equal
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\uzair\AppData\Local\Programs\Python\Python36\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Users\uzair\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\backends\_backend_tk.py", line 267, in resize
    self.draw()
  File "C:\Users\uzair\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\backends\backend_tkagg.py", line 9, in draw
    super(FigureCanvasTkAgg, self).draw()
  File "C:\Users\uzair\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\backends\backend_agg.py", line 402, in draw
    self.figure.draw(self.renderer)
  File "C:\Users\uzair\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\artist.py", line 50, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\Users\uzair\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\figure.py", line 1649, in draw
    renderer, self, artists, self.suppressComposite)
  File "C:\Users\uzair\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "C:\Users\uzair\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\artist.py", line 50, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\Users\uzair\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\axes\_base.py", line 2604, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "C:\Users\uzair\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "C:\Users\uzair\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\artist.py", line 50, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\Users\uzair\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\axis.py", line 1185, in draw
    ticks_to_draw = self._update_ticks(renderer)
  File "C:\Users\uzair\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\axis.py", line 1023, in _update_ticks
    tick_tups = list(self.iter_ticks())  # iter_ticks calls the locator
  File "C:\Users\uzair\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\axis.py", line 967, in iter_ticks
    majorLocs = self.major.locator()
  File "C:\Users\uzair\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\ticker.py", line 1985, in __call__
    return self.tick_values(vmin, vmax)
  File "C:\Users\uzair\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\ticker.py", line 1993, in tick_values
    locs = self._raw_ticks(vmin, vmax)
  File "C:\Users\uzair\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\ticker.py", line 1949, in _raw_ticks
    istep = np.nonzero(steps >= raw_step)[0][0]
IndexError: index 0 is out of bounds for axis 0 with size 0
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\uzair\AppData\Local\Programs\Python\Python36\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Users\uzair\AppData\Local\Programs\Python\Python36\lib\tkinter\__init__.py", line 749, in callit
    func(*args)
  File "C:\Users\uzair\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\backends\_backend_tk.py", line 346, in idle_draw
    self.draw()
  File "C:\Users\uzair\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\backends\backend_tkagg.py", line 9, in draw
    super(FigureCanvasTkAgg, self).draw()
  File "C:\Users\uzair\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\backends\backend_agg.py", line 402, in draw
    self.figure.draw(self.renderer)
  File "C:\Users\uzair\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\artist.py", line 50, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\Users\uzair\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\figure.py", line 1649, in draw
    renderer, self, artists, self.suppressComposite)
  File "C:\Users\uzair\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "C:\Users\uzair\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\artist.py", line 50, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\Users\uzair\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\axes\_base.py", line 2604, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "C:\Users\uzair\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "C:\Users\uzair\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\artist.py", line 50, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\Users\uzair\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\axis.py", line 1185, in draw
    ticks_to_draw = self._update_ticks(renderer)
  File "C:\Users\uzair\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\axis.py", line 1023, in _update_ticks
    tick_tups = list(self.iter_ticks())  # iter_ticks calls the locator
  File "C:\Users\uzair\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\axis.py", line 967, in iter_ticks
    majorLocs = self.major.locator()
  File "C:\Users\uzair\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\ticker.py", line 1985, in __call__
    return self.tick_values(vmin, vmax)
  File "C:\Users\uzair\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\ticker.py", line 1993, in tick_values
    locs = self._raw_ticks(vmin, vmax)
  File "C:\Users\uzair\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\ticker.py", line 1949, in _raw_ticks
    istep = np.nonzero(steps >= raw_step)[0][0]

IndexError: index 0 is out of bounds for axis 0 with size 0
```

**Matplotlib version**
  * Operating system: Windows 10 (64 bit)
  * Matplotlib version: 3.0.0
  * Matplotlib backend: TkAgg
  * Python version: 3.6 (64 bit)
  * Jupyter version: 4.4.0
  * Other libraries: Pandas (0.23.4), Numpy (1.15.3), Json (2.0.9), Requests (2.13.0)

Installed from pip

**Comment by tacaswell** [comment]
@UziFTW Can you please include the full traceback?  Can you reproduce this without hitting an external service?

**Comment by UziFTW** [comment]
> By an "external service" @tacaswell means the maintainers are not going to make a call to whatever URL you provided above.
> 
> Did this ever work? Why do you think this is a Matplotlib problem? My guess would be that your ajax request returned empty data somehow. I'm actually going to close, but if you can isolate a Matplotlib error, please post here and we will be happy to take a look at it.

Try going on the link, there is data and when trying to print the data no error occurs. I am pretty sure it has something to do with matplotlib

**Comment by jklymak** [comment]
Bug reports here should be self-contained and minimal.  If you make it self contained you will help us narrow down the possible error.  Thanks for your understanding.

**Comment by tacaswell** [comment]
Reopened, from the traceback this deferentially coming out of our code.  @UziFTW Can you produce a dataframe that triggers this with out reach out a bitcoin website?

**Comment by anntzer** [comment]
The biggest value in the array is 1.7e308, which is close to the largest value representable as float64, and the codebase is not equipped to handle such values at all (e.g. 2*x/2 is infinite).
Likely we should just call `np.seterr(overflow="error")` around the correct code blocks to hard-fail in such cases instead of just having a warning and then nonsense later.

**Comment by jklymak** [comment]
Reclosing, as I think users should realize they can't plot data out at 10**308.  But feel free to reopen if I'm being too peremptory....

**Comment by ge3088** [comment]
Hello,
I am unable to open matplot when running the command (rqt_plot cmd_vel/linear/x cmd_vel/angular/z).
if any one has any suggestions. Thank you. The error is copied below.

/usr/lib/python2.7/dist-packages/matplotlib/axis.py:1015: UserWarning: Unable to find pixel distance along axis for interval padding of ticks; assuming no interval padding needed.
  warnings.warn("Unable to find pixel distance along axis "
/usr/lib/python2.7/dist-packages/matplotlib/axis.py:1025: UserWarning: Unable to find pixel distance along axis for interval padding of ticks; assuming no interval padding needed.
  warnings.warn("Unable to find pixel distance along axis "
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_plot/data_plot/mat_data_plot.py", line 107, in resizeEvent
    self.figure.tight_layout()
  File "/usr/lib/python2.7/dist-packages/matplotlib/figure.py", line 1754, in tight_layout
    rect=rect)
  File "/usr/lib/python2.7/dist-packages/matplotlib/tight_layout.py", line 349, in get_tight_layout_figure
    pad=pad, h_pad=h_pad, w_pad=w_pad)
  File "/usr/lib/python2.7/dist-packages/matplotlib/tight_layout.py", line 128, in auto_adjust_subplotpars
    fig.transFigure.inverted())
  File "/usr/lib/python2.7/dist-packages/matplotlib/transforms.py", line 1775, in inverted
    self._inverted = Affine2D(inv(mtx), shorthand_name=shorthand_name)
  File "/usr/lib/python2.7/dist-packages/numpy/linalg/linalg.py", line 526, in inv
    ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)
  File "/usr/lib/python2.7/dist-packages/numpy/linalg/linalg.py", line 90, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
numpy.linalg.linalg.LinAlgError: Singular matrix
