### ISSUE TITLE
Unable to import due to font_manager error

### ISSUE THREAD

**Issue by aksh1618** [matplotlib/matplotlib#12840]
### Bug report

Trying to import `matplotlib.pyplot` makes python hang, `Ctrl + C` results in a stacktrace. Reverting to 2.2.3 fixes this.

**Code for reproduction**

```python
import matplotlib.pyplot
```

**Actual outcome**

```
$ python
Python 3.7.1 (default, Oct 22 2018, 10:41:28)
[GCC 8.2.1 20180831] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib.pyplot
^CTraceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/matplotlib/font_manager.py", line 1356, in <module>
    fontManager = json_load(_fmcache)
  File "/usr/lib/python3.7/site-packages/matplotlib/font_manager.py", line 891, in json_load
    with open(filename, 'r') as fh:
FileNotFoundError: [Errno 2] No such file or directory: '/home/aksh/.cache/matplotlib/fontlist-v300.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/site-packages/matplotlib/pyplot.py", line 32, in <module>
    import matplotlib.colorbar
  File "/usr/lib/python3.7/site-packages/matplotlib/colorbar.py", line 32, in <module>
    import matplotlib.contour as contour
  File "/usr/lib/python3.7/site-packages/matplotlib/contour.py", line 18, in <module>
    import matplotlib.font_manager as font_manager
  File "/usr/lib/python3.7/site-packages/matplotlib/font_manager.py", line 1366, in <module>
    _rebuild()
  File "/usr/lib/python3.7/site-packages/matplotlib/font_manager.py", line 1347, in _rebuild
    fontManager = FontManager()
  File "/usr/lib/python3.7/site-packages/matplotlib/font_manager.py", line 986, in __init__
    self.ttflist = createFontList(ttffiles)
  File "/usr/lib/python3.7/site-packages/matplotlib/font_manager.py", line 497, in createFontList
    font = ft2font.FT2Font(fpath)
KeyboardInterrupt
```

**Expected outcome**

Importing `matplotlib.pyplot` works.

**Matplotlib version**
  * Operating system: Arch Linux
  * Matplotlib version: 3.0.2
  * Matplotlib backend: Qt5Agg
  * Python version: 3.7.1

Both python and matplotlib installed using pacman.

**Comment by anntzer** [comment]
Add some print()s to see what's the fpath that causes the deadlock?

**Comment by dstansby** [comment]
Does anyone have some more helpful/specific debugging advice for this issue? @aksh1618 have you tried re-installing Matplotlib?

**Comment by aksh1618** [comment]
Sorry, I kinda forgot about this. Currently I'm on 3.0.3, and this issue seems to be fixed. You may close this if no further clarification is needed.

**Comment by jklymak** [comment]
Ok sorry this was a mystery.  Thanks!
