### ISSUE TITLE
While Running code got an Error : Import Error 

### ISSUE THREAD

**Issue by sam4u3** [matplotlib/matplotlib#12979]
Python Code :
```python
from matplotlib import pyplot as plt
years=[1950,1960,1970,1980,1990,2000]
gdp=[222.50,543.5,2862.6,5979.7,14870,7978.5]
plt.plot(years,gdp,color='green',marker='o',linestyle='solid')
plt.ylabel("Billions of $")
plt.show()
```
**Actual outcome**
```pytb
Traceback (most recent call last):
  File "E:/SAYAR PROJECTS/PYTHON/DATA_SC/Data Visual.py", line 1, in <module>
    from matplotlib import pyplot as plt
  File "C:\ProgramData\Anaconda3\envs\sayar ecube\lib\site-packages\matplotlib\pyplot.py", line 31, in <module>
    import matplotlib.colorbar
  File "C:\ProgramData\Anaconda3\envs\sayar ecube\lib\site-packages\matplotlib\colorbar.py", line 32, in <module>
    import matplotlib.artist as martist
  File "C:\ProgramData\Anaconda3\envs\sayar ecube\lib\site-packages\matplotlib\artist.py", line 16, in <module>
    from .path import Path
  File "C:\ProgramData\Anaconda3\envs\sayar ecube\lib\site-packages\matplotlib\path.py", line 21, in <module>
    from . import _path, rcParams
ImportError: cannot import name '_path'
```

**Matplotlib version**

  * Operating system: Windows server 2012 R2
  * Matplotlib version: 3.0.2
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version:  Python 3.6.6 :: Anaconda, Inc.
![matplolib](https://user-images.githubusercontent.com/17972687/49855603-c5226700-fe13-11e8-90c7-2202a59fba17.png)

**Comment by story645** [comment]
does just this line work:
```python
import matplotlib
```
if so, can you then type:
```python
import matplotlib
print(matplotlib.__version__)
```
and report the version number?
thanks

**Comment by tacaswell** [comment]
This looks like installation issues `_path` is one of our c-extensions.

**Comment by sam4u3** [comment]
i have re-install package but same issue. 
if i'm using anaconda interpreter then only i get this issue.

**Comment by dstansby** [comment]
Have you tried reinstalling `Matplotlib` from *both* pip and conda (and anywhere else), and then installing it fresh?

**Comment by anntzer** [comment]
Closing for lack of activity.  Feel free to request a reopen with more info.
