### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by jzyxbb** [matplotlib/matplotlib#13041]
###  Need Help

```python
import numpy as np
import matplotlib.pyplot as plt
a='x+1'
x=np.linspace(0,10,1000)
plt.plot(x,a)
plt.show()
```

**Actual outcome**

```
Traceback (most recent call last):
  File "D:\python大作业\edit part.py", line 5, in <module>
    plt.plot(x,a)
  File "C:\Users\jzyxbb\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\pyplot.py", line 2813, in plot
    is not None else {}), **kwargs)
  File "C:\Users\jzyxbb\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\__init__.py", line 1810, in inner
    return func(ax, *args, **kwargs)
  File "C:\Users\jzyxbb\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\axes\_axes.py", line 1611, in plot
    for line in self._get_lines(*args, **kwargs):
  File "C:\Users\jzyxbb\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\axes\_base.py", line 393, in _grab_next_args
    yield from self._plot_args(this, kwargs)
  File "C:\Users\jzyxbb\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\axes\_base.py", line 342, in _plot_args
    linestyle, marker, color = _process_plot_format(tup[-1])
  File "C:\Users\jzyxbb\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\axes\_base.py", line 105, in _process_plot_format
    'Illegal format string "%s"; two marker symbols' % fmt)
ValueError: Illegal format string "x+1"; two marker symbols
```

  * Operating system:win 10
  * Matplotlib version: 3.0.2
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version:
  * Jupyter version (if applicable):

**Comment by jzyxbb** [comment]
if I change 'x+1'to'x',it can run sussecssfully!Why? thanks a lot for help

**Comment by timhoffm** [comment]
Please note that this is the bug tracker for matplotlib, not a help forum. We would appreciate if you use one of the recommended ways to ask for help in the future:

- [gitter channel](https://gitter.im/matplotlib/matplotlib)
- [matplotlib-users mailing list](https://mail.python.org/mailman/listinfo/matplotlib-users)
- [stackoverflow](http://stackoverflow.com/questions/tagged/matplotlib)

#### Concerning your question:
The way you call it, `a` is interpreted as format string. 'x' is a valid format, while 'x+1' is not.
And since you provide only one numeric value, your `x`  goes on the vertical axis, while the horizontal axis is implicitly 0, 1, 2, ...

I assume this is not what you are intending. Likely, you are looking for:

```
x = np.linspace(0, 10, 1000)
a = x + 1
plt.plot(x, a)
```

See also the [plot documentation](https://matplotlib.org/api/_as_gen/matplotlib.pyplot.plot.html).

**Comment by jzyxbb** [comment]
sorry，sir，I don’t know the rule here,I will delete it,thank you for your help

蒋子艺
Ziyi Jiang，Student
电子工程学院（School of Electronic Engineering）
电子信息工程（Electronic information Engineering）
Xidian university

________________________________
