### ISSUE TITLE
Got `time data '19-Sep-03' does not match format '%d-%b-%y'` while building 3.0.2-doc

### ISSUE THREAD

**Issue by gepcel** [matplotlib/matplotlib#13056]
I download doc files from branch `3.0.2-doc`, and tried to build it for local use. 

```
D:\download\temp\matplotlib-3.0.2-doc\doc>make htmlhelp
...
generating gallery for gallery\frontpage... [100%] membrane.py
generating gallery for gallery\misc... [ 57%] load_converter.py
Warning, treated as error:
D:\download\temp\matplotlib-3.0.2-doc\examples\misc\load_converter.py failed to execute correctly: Traceback (most recent call last):
  File "D:\download\temp\matplotlib-3.0.2-doc\examples\misc\load_converter.py", line 17, in <module>
    skiprows=1, usecols=(0, 2), unpack=True)
  File "c:\anaconda3\lib\site-packages\numpy\lib\npyio.py", line 1101, in loadtxt
    for x in read_data(_loadtxt_chunksize):
  File "c:\anaconda3\lib\site-packages\numpy\lib\npyio.py", line 1028, in read_data
    items = [conv(val) for (conv, val) in zip(converters, vals)]
  File "c:\anaconda3\lib\site-packages\numpy\lib\npyio.py", line 1028, in <listcomp>
    items = [conv(val) for (conv, val) in zip(converters, vals)]
  File "c:\anaconda3\lib\site-packages\numpy\lib\npyio.py", line 1087, in tobytes_first
    return conv(x.encode("latin1"))
  File "c:\anaconda3\lib\site-packages\matplotlib\dates.py", line 361, in __call__
    return super().__call__(s)
  File "c:\anaconda3\lib\site-packages\matplotlib\dates.py", line 335, in __call__
    return date2num(datetime.datetime(*time.strptime(s, self.fmt)[:6]))
  File "c:\anaconda3\lib\_strptime.py", line 559, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "c:\anaconda3\lib\_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '19-Sep-03' does not match format '%d-%b-%y'
```

But inside the `matplotlib-3.0.2-doc\examples\misc\` folder, I can do `python load_converter.py` without any error. 

**What am I missing?**

Versions:
```
matplotlib: 3.0.2
numpy: 1.15.4
sphinx: 1.8.1
numpydoc: 0.8.0
sphinx-gallery: 0.2.0
Windows 10 with Chinese simplified language
```

**Comment by timhoffm** [comment]
Is this a locale issue of you execution environment? I assume that 'Sep' cannot be parsed using `%b` in Chinese.

**Comment by gepcel** [comment]
But, from my computer:

```
In [1]: from datetime import date

In [2]: date.today().strftime('%d-%b-%y')
Out[2]: '28-Dec-18'
```

Since I can run `python load_converter.py` without any problem, how can I find out the reason? Would you please show me some guidance? I'm new to sphinx.

**Comment by gepcel** [comment]
And also, just copying these codes to ipython, and run it manually:

```python
In [13]: import numpy as np
    ...: import matplotlib.pyplot as plt
    ...: import matplotlib.cbook as cbook
    ...: from matplotlib.dates import bytespdate2num

In [14]: datafile = cbook.get_sample_data('msft.csv', asfileobj=False)
    ...: print('loading', datafile)
loading C:\anaconda3\lib\site-packages\matplotlib\mpl-data\sample_data\msft.csv

In [15]: dates, closes = np.loadtxt(datafile, delimiter=',',
    ...:                            converters={0: bytespdate2num('%d-%b-%y')},
    ...:                            skiprows=1, usecols=(0, 2), unpack=True)

In [16]: closes
Out[16]:
array([29.97, 29.51, 28.95, 28.95, 28.61, 28.4 , 28.11, 28.18, 28.71,
       28.92, 28.75, 28.47, 28.4 , 27.3 , 26.55, 26.58, 26.58, 26.67,
       26.54, 26.95, 26.73, 26.53, 26.65, 25.83, 25.66, 25.71, 25.89,
       25.77, 25.99, 25.98, 25.81, 26.19, 26.54, 26.41, 26.51, 26.99,
       26.57, 26.9 , 27.  , 26.95, 26.92, 26.65, 26.56, 26.91, 27.23,
       27.27, 27.62, 27.53, 27.81, 27.45, 27.42, 27.7 , 27.8 , 27.55,
       26.95, 26.93, 26.2 , 26.12, 26.34, 26.51, 25.99, 26.04, 26.24,
       26.38, 26.39])

In [17]: dates
Out[17]:
array([731477., 731476., 731475., 731474., 731473., 731470., 731469.,
       731468., 731467., 731466., 731463., 731462., 731461., 731460.,
       731456., 731455., 731454., 731453., 731452., 731449., 731448.,
       731447., 731446., 731445., 731442., 731441., 731440., 731439.,
       731438., 731435., 731434., 731433., 731432., 731431., 731428.,
       731427., 731426., 731425., 731424., 731421., 731420., 731419.,
       731418., 731417., 731414., 731413., 731412., 731411., 731410.,
       731407., 731406., 731405., 731404., 731403., 731399., 731398.,
       731397., 731396., 731393., 731392., 731391., 731390., 731389.,
       731386., 731385.])
```

**Comment by anntzer** [comment]
Interestingly, it looks like whether strptime is actually using the locale or not depends on other imports:
```
$ LANG=fr_FR.UTF-8 python -c 'import time, rpy2; print(time.strptime("19-May-03", "%d-%b-%y"))'
time.struct_time(tm_year=2003, tm_mon=5, tm_mday=19, tm_hour=0, tm_min=0, tm_sec=0, tm_wday=0, tm_yday=139, tm_isdst=-1)

$ LANG=fr_FR.UTF-8 python -c 'import time, rpy2.robjects; print(time.strptime("19-May-03", "%d-%b-%y"))'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.7/_strptime.py", line 571, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "/usr/lib/python3.7/_strptime.py", line 359, in _strptime
    (data_string, format))
ValueError: time data '19-May-03' does not match format '%d-%b-%y'
```

**Comment by gepcel** [comment]
Wow, I saw your pull #13061, very impressive, how did you figure that out? Would you share some experience or process if you don't mind?

**Comment by anntzer** [comment]
Not much magic to it: like anything else, spend a lot of time to know the codebase well.

**Comment by tacaswell** [comment]
Closing as #13061 has been merged.
