### ISSUE TITLE
test_backend_qt tests failing

### ISSUE THREAD

**Issue by dstansby** [matplotlib/matplotlib#13201]
Seems to be present in all recent builds, here's a sample error from pytest:

```python
lib/matplotlib/tests/test_backends_interactive.py:117: Failed
----------------------------- Captured stderr call -----------------------------
Failed to connect to Mir: Failed to connect to server socket: No such file or directory
Unable to init server: Could not connect: Connection refused
Failed to connect to Mir: Failed to connect to server socket: No such file or directory
Unable to init server: Could not connect: Connection refused
(-c:14609): Gdk-CRITICAL **: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Traceback (most recent call last):
  File "/home/travis/build/matplotlib/matplotlib/lib/matplotlib/backends/backend_gtk3.py", line 43, in <module>
    cursors.MOVE          : Gdk.Cursor.new(Gdk.CursorType.FLEUR),
TypeError: constructor returned NULL
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<string>", line 7, in <module>
  File "/home/travis/build/matplotlib/matplotlib/lib/matplotlib/pyplot.py", line 2341, in <module>
    switch_backend(rcParams["backend"])
  File "/home/travis/build/matplotlib/matplotlib/lib/matplotlib/pyplot.py", line 207, in switch_backend
    backend_mod = importlib.import_module(backend_name)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/travis/build/matplotlib/matplotlib/lib/matplotlib/backends/backend_gtk3agg.py", line 4, in <module>
    from . import backend_agg, backend_cairo, backend_gtk3
  File "/home/travis/build/matplotlib/matplotlib/lib/matplotlib/backends/backend_gtk3.py", line 52, in <module>
    raise ImportError(exc)
ImportError: constructor returned NULL
```

**Comment by QuLogic** [comment]
Could possibly be fixed by the commits @tacaswell added in #13181 for xvfb?
