### ISSUE TITLE
ImportError: cannot import name 'rcParams'

### ISSUE THREAD

**Issue by RohanJ24** [matplotlib/matplotlib#13407]
Traceback (most recent call last):
  File "/home/ewebcore/Desktop/numpy.py", line 18, in <module>
    from matplotlib import pyplot as plt
  File "/usr/lib/python3/dist-packages/matplotlib/__init__.py", line 123, in <module>
    from . import cbook
  File "/usr/lib/python3/dist-packages/matplotlib/cbook/__init__.py", line 36, in <module>
    import numpy as np
  File "/home/ewebcore/Desktop/numpy.py", line 18, in <module>
    from matplotlib import pyplot as plt
  File "/usr/lib/python3/dist-packages/matplotlib/pyplot.py", line 32, in <module>
    import matplotlib.colorbar
  File "/usr/lib/python3/dist-packages/matplotlib/colorbar.py", line 32, in <module>
    import matplotlib.artist as martist
  File "/usr/lib/python3/dist-packages/matplotlib/artist.py", line 15, in <module>
    from . import cbook, docstring, rcParams
ImportError: cannot import name 'rcParams'

Give me solution for above error

**Comment by ImportanceOfBeingErnest** [comment]
Please don't name any script you want to run by the same name as a package you have installed. That is, don't call your script `numpy.py`.

**Comment by RohanJ24** [comment]
> Please don't name any script you want to run by the same name as a package you have installed. That is, don't call your script `numpy.py`.

Still I got same error:

Traceback (most recent call last):
  File "/home/ewebcore/Desktop/testing.py", line 18, in <module>
    from matplotlib import pyplot as plt
  File "/usr/lib/python3/dist-packages/matplotlib/__init__.py", line 123, in <module>
    from . import cbook
  File "/usr/lib/python3/dist-packages/matplotlib/cbook/__init__.py", line 36, in <module>
    import numpy as np
  File "/home/ewebcore/Desktop/numpy.py", line 18, in <module>
    from matplotlib import pyplot as plt
  File "/usr/lib/python3/dist-packages/matplotlib/pyplot.py", line 32, in <module>
    import matplotlib.colorbar
  File "/usr/lib/python3/dist-packages/matplotlib/colorbar.py", line 32, in <module>
    import matplotlib.artist as martist
  File "/usr/lib/python3/dist-packages/matplotlib/artist.py", line 15, in <module>
    from . import cbook, docstring, rcParams
ImportError: cannot import name 'rcParams'

**Comment by ImportanceOfBeingErnest** [comment]
Yes you have added a different script now, but the initial `numpy.py` is still present. Delete that file.

**Comment by RohanJ24** [comment]
> Yes you have added a different script now, but the initial `numpy.py` is still present. Delete that file.

It works... Thanx !! : )
