### ISSUE TITLE
LaTeX preamble not held outside of rc_context manager

### ISSUE THREAD

**Issue by mattpitkin** [matplotlib/matplotlib#13431]
### Bug report

**Bug summary**

If I set `text.latex.preamble` in the parameters passed to the `rc_context` manager, then create a plot within the context manager and then try to `show` it outside the context manager the `text.latex.preamble` is no longer present. However, if I set something else, like the `axes.edgecolor`, it is still present when showing the plot outside the context manager.

**Code for reproduction**

```python
import matplotlib as mpl 
from matplotlib import pyplot as pl 
import numpy as np

x = np.linspace(0, 1, 100)
y = x**2

# set rcParams
rcparams = {'backend': 'Agg', 
                    'text.usetex': True, 
                    'text.latex.preamble': '\\usepackage{xfrac}',  # set a required package
                    'axes.edgecolor': 'r'}

with mpl.rc_context(rc=rcparams): 
    fig, ax = pl.subplots() 
    ax.plot(x, y) 
    ax.set_xticks([0.5]) 
    ax.set_xticklabels(['$\\sfrac{1}{2}$'])  # use package 

# show the plot
pl.show()
```

**Actual outcome**

The (rather long) output is

```                                                                     
Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/matthew/.conda/envs/cwinpy/lib/python3.7/site-packages/matplotlib/texmanager.py", line 298, in _run_checked_subprocess
    stderr=subprocess.STDOUT)
  File "/home/matthew/.conda/envs/cwinpy/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/home/matthew/.conda/envs/cwinpy/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['latex', '-interaction=nonstopmode', '--halt-on-error', '/home/matthew/.cache/matplotlib/tex.cache/d7fb9dd095f3401adbeced366fb53b6f.tex']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/matthew/.conda/envs/cwinpy/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/matthew/.conda/envs/cwinpy/lib/python3.7/site-packages/matplotlib/backends/_backend_tk.py", line 267, in resize
    self.draw()
  File "/home/matthew/.conda/envs/cwinpy/lib/python3.7/site-packages/matplotlib/backends/backend_tkagg.py", line 9, in draw
    super(FigureCanvasTkAgg, self).draw()
  File "/home/matthew/.conda/envs/cwinpy/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 402, in draw
    self.figure.draw(self.renderer)
  File "/home/matthew/.conda/envs/cwinpy/lib/python3.7/site-packages/matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/matthew/.conda/envs/cwinpy/lib/python3.7/site-packages/matplotlib/figure.py", line 1649, in draw
    renderer, self, artists, self.suppressComposite)
  File "/home/matthew/.conda/envs/cwinpy/lib/python3.7/site-packages/matplotlib/image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/matthew/.conda/envs/cwinpy/lib/python3.7/site-packages/matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/matthew/.conda/envs/cwinpy/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 2628, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/home/matthew/.conda/envs/cwinpy/lib/python3.7/site-packages/matplotlib/image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/matthew/.conda/envs/cwinpy/lib/python3.7/site-packages/matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/matthew/.conda/envs/cwinpy/lib/python3.7/site-packages/matplotlib/axis.py", line 1187, in draw
    renderer)
  File "/home/matthew/.conda/envs/cwinpy/lib/python3.7/site-packages/matplotlib/axis.py", line 1125, in _get_tick_bboxes
    extent = tick.label1.get_window_extent(renderer)
  File "/home/matthew/.conda/envs/cwinpy/lib/python3.7/site-packages/matplotlib/text.py", line 930, in get_window_extent
    bbox, info, descent = self._get_layout(self._renderer)
  File "/home/matthew/.conda/envs/cwinpy/lib/python3.7/site-packages/matplotlib/text.py", line 313, in _get_layout
    ismath=ismath)
  File "/home/matthew/.conda/envs/cwinpy/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 209, in get_text_width_height_descent
    s, fontsize, renderer=self)
  File "/home/matthew/.conda/envs/cwinpy/lib/python3.7/site-packages/matplotlib/texmanager.py", line 464, in get_text_width_height_descent
    dvifile = self.make_dvi(tex, fontsize)
  File "/home/matthew/.conda/envs/cwinpy/lib/python3.7/site-packages/matplotlib/texmanager.py", line 328, in make_dvi
    texfile], tex)
  File "/home/matthew/.conda/envs/cwinpy/lib/python3.7/site-packages/matplotlib/texmanager.py", line 307, in _run_checked_subprocess
    exc=exc.output.decode('utf-8')))
RuntimeError: latex was not able to process the following string:
b'$\\\\sfrac{1}{2}$'

Here is the full report generated by latex:
This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017/Debian) (preloaded format=latex)
 restricted \write18 enabled.
entering extended mode

(/home/matthew/.cache/matplotlib/tex.cache/d7fb9dd095f3401adbeced366fb53b6f.tex
LaTeX2e <2017-04-15>
Babel <3.18> and hyphenation patterns for 84 language(s) loaded.
(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo))
(/usr/share/texlive/texmf-dist/tex/latex/type1cm/type1cm.sty)
(/usr/share/texlive/texmf-dist/tex/latex/base/textcomp.sty
(/usr/share/texlive/texmf-dist/tex/latex/base/ts1enc.def))
(/usr/share/texlive/texmf-dist/tex/latex/base/inputenc.sty
(/usr/share/texlive/texmf-dist/tex/latex/base/utf8.def
(/usr/share/texlive/texmf-dist/tex/latex/base/t1enc.dfu)
(/usr/share/texlive/texmf-dist/tex/latex/base/ot1enc.dfu)
(/usr/share/texlive/texmf-dist/tex/latex/base/omsenc.dfu)
(/usr/share/texlive/texmf-dist/tex/latex/base/ts1enc.dfu)))
(/usr/share/texlive/texmf-dist/tex/latex/geometry/geometry.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty)
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ifpdf.sty)
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ifvtex.sty)
(/usr/share/texlive/texmf-dist/tex/generic/ifxetex/ifxetex.sty)

Package geometry Warning: Over-specification in `h'-direction.
    `width' (5058.9pt) is ignored.


Package geometry Warning: Over-specification in `v'-direction.
    `height' (5058.9pt) is ignored.

) (./d7fb9dd095f3401adbeced366fb53b6f.aux)
(/usr/share/texlive/texmf-dist/tex/latex/base/ts1cmr.fd)
*geometry* driver: auto-detecting
*geometry* detected driver: dvips
! Undefined control sequence.
<recently read> \sfrac 
                       
l.14 ...ze{10.000000}{12.500000}{\sffamily $\sfrac
                                                  {1}{2}$}
No pages of output.
Transcript written on d7fb9dd095f3401adbeced366fb53b6f.log.



Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/matthew/.conda/envs/cwinpy/lib/python3.7/site-packages/matplotlib/texmanager.py", line 298, in _run_checked_subprocess
    stderr=subprocess.STDOUT)
  File "/home/matthew/.conda/envs/cwinpy/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/home/matthew/.conda/envs/cwinpy/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['latex', '-interaction=nonstopmode', '--halt-on-error', '/home/matthew/.cache/matplotlib/tex.cache/d7fb9dd095f3401adbeced366fb53b6f.tex']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/matthew/.conda/envs/cwinpy/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/matthew/.conda/envs/cwinpy/lib/python3.7/tkinter/__init__.py", line 749, in callit
    func(*args)
  File "/home/matthew/.conda/envs/cwinpy/lib/python3.7/site-packages/matplotlib/backends/_backend_tk.py", line 346, in idle_draw
    self.draw()
  File "/home/matthew/.conda/envs/cwinpy/lib/python3.7/site-packages/matplotlib/backends/backend_tkagg.py", line 9, in draw
    super(FigureCanvasTkAgg, self).draw()
  File "/home/matthew/.conda/envs/cwinpy/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 402, in draw
    self.figure.draw(self.renderer)
  File "/home/matthew/.conda/envs/cwinpy/lib/python3.7/site-packages/matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/matthew/.conda/envs/cwinpy/lib/python3.7/site-packages/matplotlib/figure.py", line 1649, in draw
    renderer, self, artists, self.suppressComposite)
  File "/home/matthew/.conda/envs/cwinpy/lib/python3.7/site-packages/matplotlib/image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/matthew/.conda/envs/cwinpy/lib/python3.7/site-packages/matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/matthew/.conda/envs/cwinpy/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 2628, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/home/matthew/.conda/envs/cwinpy/lib/python3.7/site-packages/matplotlib/image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/matthew/.conda/envs/cwinpy/lib/python3.7/site-packages/matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/matthew/.conda/envs/cwinpy/lib/python3.7/site-packages/matplotlib/axis.py", line 1187, in draw
    renderer)
  File "/home/matthew/.conda/envs/cwinpy/lib/python3.7/site-packages/matplotlib/axis.py", line 1125, in _get_tick_bboxes
    extent = tick.label1.get_window_extent(renderer)
  File "/home/matthew/.conda/envs/cwinpy/lib/python3.7/site-packages/matplotlib/text.py", line 930, in get_window_extent
    bbox, info, descent = self._get_layout(self._renderer)
  File "/home/matthew/.conda/envs/cwinpy/lib/python3.7/site-packages/matplotlib/text.py", line 313, in _get_layout
    ismath=ismath)
  File "/home/matthew/.conda/envs/cwinpy/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 209, in get_text_width_height_descent
    s, fontsize, renderer=self)
  File "/home/matthew/.conda/envs/cwinpy/lib/python3.7/site-packages/matplotlib/texmanager.py", line 464, in get_text_width_height_descent
    dvifile = self.make_dvi(tex, fontsize)
  File "/home/matthew/.conda/envs/cwinpy/lib/python3.7/site-packages/matplotlib/texmanager.py", line 328, in make_dvi
    texfile], tex)
  File "/home/matthew/.conda/envs/cwinpy/lib/python3.7/site-packages/matplotlib/texmanager.py", line 307, in _run_checked_subprocess
    exc=exc.output.decode('utf-8')))
RuntimeError: latex was not able to process the following string:
b'$\\\\sfrac{1}{2}$'

Here is the full report generated by latex:
This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017/Debian) (preloaded format=latex)
 restricted \write18 enabled.
entering extended mode

(/home/matthew/.cache/matplotlib/tex.cache/d7fb9dd095f3401adbeced366fb53b6f.tex
LaTeX2e <2017-04-15>
Babel <3.18> and hyphenation patterns for 84 language(s) loaded.
(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo))
(/usr/share/texlive/texmf-dist/tex/latex/type1cm/type1cm.sty)
(/usr/share/texlive/texmf-dist/tex/latex/base/textcomp.sty
(/usr/share/texlive/texmf-dist/tex/latex/base/ts1enc.def))
(/usr/share/texlive/texmf-dist/tex/latex/base/inputenc.sty
(/usr/share/texlive/texmf-dist/tex/latex/base/utf8.def
(/usr/share/texlive/texmf-dist/tex/latex/base/t1enc.dfu)
(/usr/share/texlive/texmf-dist/tex/latex/base/ot1enc.dfu)
(/usr/share/texlive/texmf-dist/tex/latex/base/omsenc.dfu)
(/usr/share/texlive/texmf-dist/tex/latex/base/ts1enc.dfu)))
(/usr/share/texlive/texmf-dist/tex/latex/geometry/geometry.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty)
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ifpdf.sty)
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ifvtex.sty)
(/usr/share/texlive/texmf-dist/tex/generic/ifxetex/ifxetex.sty)

Package geometry Warning: Over-specification in `h'-direction.
    `width' (5058.9pt) is ignored.


Package geometry Warning: Over-specification in `v'-direction.
    `height' (5058.9pt) is ignored.

) (./d7fb9dd095f3401adbeced366fb53b6f.aux)
(/usr/share/texlive/texmf-dist/tex/latex/base/ts1cmr.fd)
*geometry* driver: auto-detecting
*geometry* detected driver: dvips
! Undefined control sequence.
<recently read> \sfrac 
                       
l.14 ...ze{10.000000}{12.500000}{\sffamily $\sfrac
                                                  {1}{2}$}
No pages of output.
Transcript written on d7fb9dd095f3401adbeced366fb53b6f.log.
```

It can be seen in the created LaTeX file that the package `xfrac` has not been included in the preamble.

```latex
\documentclass{article}
\usepackage{type1cm}

\usepackage{textcomp}

\usepackage[utf8]{inputenc}

\usepackage[papersize={72in,72in},body={70in,70in},margin={1in,1in}]{geometry}
\pagestyle{empty}
\begin{document}
\fontsize{10.000000}{12.500000}{\sffamily $\sfrac{1}{2}$}
\end{document}
```

**Expected outcome**

If you do the same thing, but without the LaTeX preamble, and show the plot outside the context manager, the other parameters (e.g., `axes.edgecolor`) that are set still persist, e.g.:

```
import matplotlib as mpl 
from matplotlib import pyplot as pl 
import numpy as np

x = np.linspace(0, 1, 100)
y = x**2

# set rcParams
rcparams = {'axes.edgecolor': 'r'}

with mpl.rc_context(rc=rcparams): 
    fig, ax = pl.subplots() 
    ax.plot(x, y)

# show the plot
pl.show()
```
This still shows a plot with a red border.

The reason that I'd like this to work even with the LaTeX preamble is that I'd like to use the `rc_context` within a function to create a figure and then return that figure from the function.

**Matplotlib version**

  * Operating system: Ubuntu 18.04
  * Matplotlib version: 3.0.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 3.7.2
  * Jupyter version (if applicable):
  * Other libraries: 

Matplotlib installed via pip in a conda environment.

**Comment by ImportanceOfBeingErnest** [comment]
Half the people want to have the rcParams applied more eagerly, the other half more lazily. And currently we're right in the middle. 

Meaning, the current situation is that rcParams are applied in the moment they are needed. In case of the preamble it is still needed when drawing (showing) the figure, because that is when the string `'$\\sfrac{1}{2}$'` needs to be interpreted. It seems as of now the only chance you have is to include `plt.show()` inside the context, or call it within a new context of the same content.

**Comment by mattpitkin** [comment]
Another slight oddity - if I set the `text.latex.preamble` outside of the `rc_context` manager, but set `text.usetex` to `True` in the context manager, e.g.,

```python
import matplotlib as mpl 
from matplotlib import pyplot as pl 
import numpy as np

x = np.linspace(0, 1, 100)
y = x**2

# set rcParams
rcparams = {'backend': 'Agg',
            'text.usetex': True, 
            'axes.edgecolor': 'r'}

mpl.rcParams['text.latex.preamble'] = '\\usepackage{xfrac}'

with mpl.rc_context(rc=rcparams): 
    fig, ax = pl.subplots() 
    ax.plot(x, y) 
    ax.set_xticks([0.5]) 
    ax.set_xticklabels(['$\\sfrac{1}{2}$'])  # use package 

# show the plot
pl.show()
```

then the x-axis labels are rendered using LaTeX, but the y-axis labels aren't _except_ for the first one at 0.0!

![image](https://user-images.githubusercontent.com/1421092/52862182-83bc7980-312c-11e9-9b62-110d13c28aab.png)

**Comment by ImportanceOfBeingErnest** [comment]
That is explainable by the same as the above. The first ticklabel is a kind of "master label"; it is created at instantiation of the axes. At this point the usetex flag is on. All other ticklabels are created at draw time. At this point the usetex flag is off.

**Comment by mattpitkin** [comment]
Ah, yes. That seems to be "fixable" by forcing a `pl.draw()` inside the context manager.

**Comment by anntzer** [comment]
> That is explainable by the same as the above. The first ticklabel is a kind of "master label"; it is created at instantiation of the axes. At this point the usetex flag is on. All other ticklabels are created at draw time. At this point the usetex flag is off.

That specific point should likely be fixed by making the labels also copy the master's usetex flag (just like they copy other attributes).

**Comment by trondbn** [comment]
> Ah, yes. That seems to be "fixable" by forcing a `pl.draw()` inside the context manager.

I tried forcing a show/draw inside the context, but it did not fix the issue for me. Only workaround I have found is to not use `rc_context` and directly assign to `(m)pl.rcParams`
