### ISSUE TITLE
[3.0.3] No such file or directory: '/usr/share/matplotlib/stylelib'

### ISSUE THREAD

**Issue by yopito** [matplotlib/matplotlib#13666]
### Bug report

**Bug summary**

fail to import `matplotlib.pyplot` with python3

**Code for reproduction**

```python
# Paste your code here
import matplotlib.pyplot    
```

**Actual outcome**

```
# If applicable, paste the console output here
$ python3                                                                                    
Python 3.6.8 (default, Feb  1 2019, 07:25:12)                                                                       
[GCC 8.2.0] on linux                                                                                                
Type "help", "copyright", "credits" or "license" for more information.                                              
>>> import matplotlib.pyplot                                                                                        
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/matplotlib/pyplot.py", line 34, in <module>
    from matplotlib import rcsetup, style
  File "/usr/lib/python3.6/site-packages/matplotlib/style/__init__.py", line 1, in <module>
    from .core import use, context, available, library, reload_library
  File "/usr/lib/python3.6/site-packages/matplotlib/style/core.py", line 212, in <module>
    _base_library = load_base_library()
  File "/usr/lib/python3.6/site-packages/matplotlib/style/core.py", line 153, in load_base_library
    library = read_style_directory(BASE_LIBRARY_PATH)
  File "/usr/lib/python3.6/site-packages/matplotlib/style/core.py", line 185, in read_style_directory
    for path, name in iter_style_files(style_dir):
  File "/usr/lib/python3.6/site-packages/matplotlib/style/core.py", line 174, in iter_style_files
    for path in os.listdir(style_dir):
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/matplotlib/mpl-data/stylelib'
```

**Expected outcome**

succeed to import

**Matplotlib version**

  * Operating system: GNU/Linux, VoidLinux distribution, x86_64/glibc plateform
  * Matplotlib version:  3.0.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): !! same traceback
  * Python version: 3.6.8
  * Jupyter version (if applicable): n/r
  * Other libraries: n/r

matplotlib and python3 from binary packages of distribution:
```
$ xbps-query -s '' | grep -E 'python3-matplotlib|python3-3'
[*] python3-3.6.8_3                       Interpreted, interactive, object-oriented programming language (3.6 series)
[*] python3-matplotlib-3.0.3_1            Python3 2D/3D plotting library
[*] python3-matplotlib-data-3.0.3_1       Python3 2D/3D plotting library - data files

```

**Comment by yopito** [comment]
my bad: not related upstream but related to distribution packaging:

files are referenced in package:
```
$ xbps-query -f python3-matplotlib-data-3.0.3_1 | grep /usr/share/matplotlib/mpl-data/stylelib
/usr/share/matplotlib/mpl-data/stylelib/Solarize_Light2.mplstyle
/usr/share/matplotlib/mpl-data/stylelib/_classic_test.mplstyle
/usr/share/matplotlib/mpl-data/stylelib/bmh.mplstyle
/usr/share/matplotlib/mpl-data/stylelib/classic.mplstyle
|...]
```
but folder `stylelib` is missing on disk:
```
$ ls -l /usr/share/matplotlib/mpl-data/
total 12
drwxr-xr-x 2 root root 4096 Mar 13 20:01 fonts
drwxr-xr-x 2 root root 4096 Mar 13 20:01 images
drwxr-xr-x 2 root root 4096 Mar 13 20:01 sample_data
```
