### ISSUE TITLE
PGF Backend : Latex command not found

### ISSUE THREAD

**Issue by azavallina** [matplotlib/matplotlib#13682]
Hello, 

PGF Backend can not find the pdfLaTeX command, I do not know how to solve this problem.

thanks for the help

### Bug report

**Code for reproduction**

```python
import matplotlib.pyplot as plt
import matplotlib as mpl

# remove or set to True (default) to trigger exception
rc_xelatex = {'pgf.rcfonts': False} 
mpl.rcParams.update(rc_xelatex)

plt.plot([1, 2, 3, 4], label="$test$")  # adding latex label
plt.legend(loc='right')  # add to plot
plt.show()  
plt.savefig("latex_pyplot.pdf")  
plt.savefig("latex_pyplot.pgf")  

```

**Actual outcome**

```
Traceback (most recent call last):
  File "<tmp 2>", line 11, in <module>
    plt.savefig("latex_pyplot.pdf")  # works
  File "/Users/***/anaconda3/lib/python3.6/site-packages/matplotlib/pyplot.py", line 697, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/Users/***/anaconda3/lib/python3.6/site-packages/matplotlib/figure.py", line 1814, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/Users/***/anaconda3/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 2259, in print_figure
    **kwargs)
  File "/Users/***/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_pgf.py", line 901, in print_pdf
    self._print_pdf_to_fh(fh, *args, **kwargs)
  File "/Users/***/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_pgf.py", line 855, in _print_pdf_to_fh
    self.print_pgf(fname_pgf, *args, **kwargs)
  File "/Users/***/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_pgf.py", line 837, in print_pgf
    self._print_pgf_to_fh(fh, *args, **kwargs)
  File "/Users/***/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_pgf.py", line 816, in _print_pgf_to_fh
    RendererPgf(self.figure, fh),
  File "/Users/***/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_pgf.py", line 420, in __init__
    self.latexManager = LatexManagerFactory.get_latex_manager()
  File "/Users/***/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_pgf.py", line 232, in get_latex_manager
    new_inst = LatexManager()
  File "/Users/***/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_pgf.py", line 309, in __init__
    % self.texcommand
RuntimeError: Latex command not found. Install 'pdflatex' or change pgf.texsystem to the desired command.
```

**Matplotlib version**

  * Operating system: Mac Os Sierra 10.12.6
  * Matplotlib version: 2.1.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): pgf
  * Python version: 3.6.3

**Comment by anntzer** [comment]
See discussion in https://github.com/matplotlib/matplotlib/issues/11668, especially https://github.com/matplotlib/matplotlib/issues/11668#issuecomment-508541058.
