### ISSUE TITLE
Using TeX throws ValueError in versions >2.0.2

### ISSUE THREAD

**Issue by Octogonapus** [matplotlib/matplotlib#13773]
### Bug report

**Bug summary**

Using TeX in a figure causes a ValueError in versions newer than `2.0.2`.

**Code for reproduction**

This code is not exactly as it is in my program, but it's pretty close:
```python
plt.rc('text', usetex=True)

X, Y = np.meshgrid(np.array(x_data), np.array(y_data))
Z = np.array(z_data)

fig1 = plt.figure(1, figsize=(12, 6))
fig1.suptitle(title)

ax = fig1.add_subplot(1, 2, 1)
contours = ax.contour(X, Y, Z, 9)
fig1.colorbar(contours, ax=ax)
ax.set_xlabel("$P(O_1)$")
ax.set_ylabel("$P(J \\mid O_1)$")

# Another subplot is added (omitted)

fig1.show()
```

**Actual outcome**

With matplotlib version `2.0.2` and lower, no error. Otherwise, I get this error:
```
/home/salmon/Documents/MoralAI/venv/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: invalid value encountered in reduce
  return umr_minimum(a, axis, None, out, keepdims, initial)
/home/salmon/Documents/MoralAI/venv/lib/python3.6/site-packages/numpy/core/_methods.py:28: RuntimeWarning: invalid value encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial)
/home/salmon/Documents/MoralAI/venv/lib/python3.6/site-packages/numpy/core/fromnumeric.py:83: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/home/salmon/Documents/MoralAI/venv/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: invalid value encountered in reduce
  return umr_minimum(a, axis, None, out, keepdims, initial)
/home/salmon/Documents/MoralAI/venv/lib/python3.6/site-packages/numpy/core/_methods.py:28: RuntimeWarning: invalid value encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial)
Traceback (most recent call last):
  File "/home/salmon/Documents/MoralAI/scan_dense_results.py", line 83, in <module>
    "Classification accuracy against " + test_name)
  File "/home/salmon/Documents/MoralAI/scan_dense_results.py", line 71, in generate_plots
    fig1.show()
  File "/home/salmon/Documents/MoralAI/venv/lib/python3.6/site-packages/matplotlib/figure.py", line 437, in show
    manager.show()
  File "/home/salmon/pycharm-2018.3.2/helpers/pycharm_matplotlib_backend/backend_interagg.py", line 107, in show
    self.canvas.show()
  File "/home/salmon/pycharm-2018.3.2/helpers/pycharm_matplotlib_backend/backend_interagg.py", line 63, in show
    FigureCanvasAgg.draw(self)
  File "/home/salmon/Documents/MoralAI/venv/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 402, in draw
    self.figure.draw(self.renderer)
  File "/home/salmon/Documents/MoralAI/venv/lib/python3.6/site-packages/matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/salmon/Documents/MoralAI/venv/lib/python3.6/site-packages/matplotlib/figure.py", line 1649, in draw
    renderer, self, artists, self.suppressComposite)
  File "/home/salmon/Documents/MoralAI/venv/lib/python3.6/site-packages/matplotlib/image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/salmon/Documents/MoralAI/venv/lib/python3.6/site-packages/matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/salmon/Documents/MoralAI/venv/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 2628, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/home/salmon/Documents/MoralAI/venv/lib/python3.6/site-packages/matplotlib/image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/salmon/Documents/MoralAI/venv/lib/python3.6/site-packages/matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/salmon/Documents/MoralAI/venv/lib/python3.6/site-packages/matplotlib/axis.py", line 1185, in draw
    ticks_to_draw = self._update_ticks(renderer)
  File "/home/salmon/Documents/MoralAI/venv/lib/python3.6/site-packages/matplotlib/axis.py", line 1023, in _update_ticks
    tick_tups = list(self.iter_ticks())  # iter_ticks calls the locator
  File "/home/salmon/Documents/MoralAI/venv/lib/python3.6/site-packages/matplotlib/axis.py", line 967, in iter_ticks
    majorLocs = self.major.locator()
  File "/home/salmon/Documents/MoralAI/venv/lib/python3.6/site-packages/matplotlib/ticker.py", line 1985, in __call__
    return self.tick_values(vmin, vmax)
  File "/home/salmon/Documents/MoralAI/venv/lib/python3.6/site-packages/matplotlib/ticker.py", line 1993, in tick_values
    locs = self._raw_ticks(vmin, vmax)
  File "/home/salmon/Documents/MoralAI/venv/lib/python3.6/site-packages/matplotlib/ticker.py", line 1932, in _raw_ticks
    nbins = np.clip(self.axis.get_tick_space(),
  File "/home/salmon/Documents/MoralAI/venv/lib/python3.6/site-packages/matplotlib/axis.py", line 2159, in get_tick_space
    return int(np.floor(length / size))
ValueError: cannot convert float NaN to integer
```

**Expected outcome**

I expect my plot to be generated using TeX for axis labels. The code works for matplotlib verion `2.0.2` and lower, but fails with any more recent version.

**Matplotlib version**

  * Operating system: Ubuntu 18.04
  * Matplotlib version: 2.0.2
  * Matplotlib backend: `module://backend_interagg`
  * Python version: 3.6.7
  * Jupyter version (if applicable): N/A
  * Other libraries: pdfTeX 3.14159265-2.6-1.40.18 (TeX Live 2017/Debian), kpathsea version 6.2.3

I installed matplotlib using pip.

**Comment by jklymak** [comment]
Were you sure to clear the Tex cache?   I think it’s in .matplotlib.

**Comment by Octogonapus** [comment]
I'm not sure where that is. If you know the name of the cache folder then I can try to `find` it.

**Comment by jklymak** [comment]
`~/.matplotlib/tex.cache`

**Comment by Octogonapus** [comment]
It ended up being here `~/.cache/matplotlib/tex.cache` (I don't have a `~/.matplotlib`). I cleared it and ran my code again and got the same error.

**Comment by jklymak** [comment]
Can you reproduce w/o pycharm?  If so, can you make a self-contained minimal working example that we can run to see the problem?

**Comment by Octogonapus** [comment]
Interesting. Good call, the code works fine outside of PyCharm. This is a PyCharm bug then?

**Comment by jklymak** [comment]
Possibly.  They have their own backend (the thing that renders the plot) so it seems possible they have a bug.   I’d make sure you update pycharm to the latest.

**Comment by Octogonapus** [comment]
I am on the latest PyCharm version (`2019.1`).

**Comment by tacaswell** [comment]
Can you sort out which of `length` and `size` is `nan`?

This is an odd one if it only fail using the interagg backend...

**Comment by Octogonapus** [comment]
`length` is `nan`
![image](https://user-images.githubusercontent.com/4064722/55201006-546f4280-5197-11e9-8f8d-127917930641.png)

**Comment by tacaswell** [comment]
What is the transform doing? `ends = self.axes.transAxes.transform([[0, 0], [1, 0]])` is the problematic line, that should not be returning `nan` as we are asking what pixel the lower left and lower right corner of the Axes are at...

**Comment by anntzer** [comment]
Please provide x_data/y_data/z_data so that we can reproduce this issue.

**Comment by anntzer** [comment]
Closing as lacking repro information, but feel free to reopen with more info.
