### ISSUE TITLE
Cannot import matplotlib.animation

### ISSUE THREAD

**Issue by ImportanceOfBeingErnest** [matplotlib/matplotlib#13786]
### Bug report

**Bug summary**

`import matplotlib.animation` fails on master with an Error (see traceback below).
This bisects to #13303 (Unify checking of executable info.)

**Code for reproduction**

    import matplotlib.animation

**Actual outcome**

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "d:\path\to\development\folder\matplotlib\lib\matplotlib\animation.py", line 727, in <module>
    class ImageMagickWriter(ImageMagickBase, MovieWriter):
  File "d:\path\to\development\folder\matplotlib\lib\matplotlib\animation.py", line 120, in wrapper
    if writerClass.isAvailable():
  File "d:\path\to\development\folder\matplotlib\lib\matplotlib\animation.py", line 720, in isAvailable
    return super().isAvailable()
  File "d:\path\to\development\folder\matplotlib\lib\matplotlib\animation.py", line 417, in isAvailable
    return shutil.which(cls.bin_path()) is not None
  File "d:\path\to\development\folder\matplotlib\lib\matplotlib\animation.py", line 714, in bin_path
    binpath = mpl._get_executable_info('magick').executable
  File "d:\path\to\development\folder\matplotlib\lib\matplotlib\__init__.py", line 380, in _get_executable_info
    return impl([path, "--version"], r"^Version: ImageMagick (\S*)")
  File "d:\path\to\development\folder\matplotlib\lib\matplotlib\__init__.py", line 325, in impl
    args, stderr=subprocess.STDOUT, universal_newlines=True)
  File "D:\path\to\conda\envs\mplgit\lib\subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "D:\path\to\conda\envs\mplgit\lib\subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "D:\path\to\conda\envs\mplgit\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "D:\path\to\conda\envs\mplgit\lib\subprocess.py", line 971, in _execute_child
    args = list2cmdline(args)
  File "D:\path\to\conda\envs\mplgit\lib\subprocess.py", line 461, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: argument of type 'WindowsPath' is not iterable
```

**Expected outcome**

No Error

**Matplotlib version**

  * Operating system: Windows 8.1
  * Matplotlib version: master branch (conda environment with matplotlib in dev mode)
  * Matplotlib backend: Qt5Agg
  * Python version: 3.6.4

**Comment by anntzer** [comment]
Can you confirm that
```patch
diff --git i/lib/matplotlib/__init__.py w/lib/matplotlib/__init__.py
index 80588e97a..2d2345cdf 100644
--- i/lib/matplotlib/__init__.py
+++ w/lib/matplotlib/__init__.py
@@ -363,7 +363,7 @@ def _get_executable_info(name):
                 for name in ["convert.exe", "magick.exe"]:
                     candidate = Path(binpath, name)
                     if candidate.exists():
-                        path = candidate
+                        path = str(candidate)
                         break
         else:
             path = "convert"
```
closes this issue?  Looks like https://bugs.python.org/issue31961, basically.

**Comment by ImportanceOfBeingErnest** [comment]
Yes, the suggested change does get rid of the error for me.
