### ISSUE TITLE
ValueError message requests impossible condition

### ISSUE THREAD

**Issue by Keating950** [matplotlib/matplotlib#13872]
### Bug report

The explanatory message accompanying the `ValueError` below requests a mathematical impossibility. `1 <= num <= 0` can never be a true statement.

**Code for reproduction**

```python
def plot_PCAs(train_data_pca, test_data_pca):

    coords_train = [(row[0], row[1], row[2]) for row in train_data_pca]
    coords_test = ([(row[0], row[1], row[2]) for row in test_data_pca])

    fig = plt.figure()
    ax = fig.add_subplot(500, projection='3d')


    Xtrn = [tup[0] for tup in coords_train]
    Ytrn = [tup[1] for tup in coords_train]
    Ztrn = [tup[2] for tup in coords_train]
    ax.scatter(Xtrn, Ytrn, Ztrn, marker='o')

    Xtst = [tup[0] for tup in coords_test]
    Ytst = [tup[1] for tup in coords_test]
    Ztst = [tup[2] for tup in coords_test]
    ax.scatter(Xtst, Ytst, Ztst, marker='x')
```

**Actual outcome**

```
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1741, in <module>
    main()
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/[user]/[path]/assignment5.py", line 166, in <module>
    plot_PCAs(X_train_pca, X_test_pca)
  File "/Users/[user]/[path]/assignment5.py", line 144, in plot_PCAs
    ax = fig.add_subplot(500, projection='3d')
  File "/Users/[user]/anaconda3/envs/Assignment_5/lib/python3.7/site-packages/matplotlib/figure.py", line 1367, in add_subplot
    a = subplot_class_factory(projection_class)(self, *args, **kwargs)
  File "/Users/[user]/anaconda3/envs/Assignment_5/lib/python3.7/site-packages/matplotlib/axes/_subplots.py", line 60, in __init__
    ).format(maxn=rows*cols, num=num))
```
\
**Expected outcome**

A 3D scatterplot of two datasets.

**Matplotlib version**

  * Operating system: MacOS 10.14.4
  * Matplotlib version: 3.0.3
  * Matplotlib backend `module://backend_interagg`
  * Python version: 3.7.3
  * Jupyter version (if applicable):
  * Other libraries: NumPy

 

 Python and matploblib acquired through the default Anaconda Navigator channel.

**Comment by jklymak** [comment]
Can you make this self-contained and minimal?  Can you also say what the error actually is?  Finally, can you try w/o pycharm to make sure the problem doesn't have anything to do w/ their backend.

**Comment by WeatherGod** [comment]
The mistake is that `fig.add_subplot(500, ...)` is erroring at the wrong
spot. It should detect that the number of rows or columns requested is not
greater than 0 and error at that point prior to detecting what is
essentially an index error (which causes the incorrect error message).
