### ISSUE TITLE
In headless mode, matplotlib.use('tkagg') only errors after importing pyplot

### ISSUE THREAD

**Issue by shoyer** [matplotlib/matplotlib#13883]
### Bug report

**Bug summary**

Calling `matplotlib.use('tkagg')` doesn't work in headless mode. That's fine and to be expected.

What is bizarre is that this only results in an error when this is called *after* `matplotlib.pyplot` is imported. This results in a surprising and challenge to debug situation if `matplotlib.use('tkagg')` is called multiple times (e.g., in separate files).

**Code for reproduction**

Here's a script that I'm running with matplotlib 3.0.2:
```python
import os

# pretend to be in "headless" mode
os.environ.pop("DISPLAY", None)

# first module
import matplotlib
matplotlib.use('TkAgg')  # silently fails?
import matplotlib.pyplot

# in another imported module
import matplotlib
matplotlib.use('TkAgg')  # this is when matplotlib crashes!
import matplotlib.pyplot
```

**Actual outcome**

```
Traceback (most recent call last):
  File "/usr/local/google/home/shoyer/Downloads/use_tkagg_test.py", line 13, in <module>
    matplotlib.use('TkAgg')  # this is when matplotlib crashes!
  File "/usr/local/google/home/shoyer/miniconda3/envs/xarray-py37/lib/python3.7/site-packages/matplotlib/__init__.py", line 1391, in use
    switch_backend(name)
  File "/usr/local/google/home/shoyer/miniconda3/envs/xarray-py37/lib/python3.7/site-packages/matplotlib/pyplot.py", line 222, in switch_backend
    newbackend, required_framework, current_framework))
ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'headless' is currently running
```

**Expected outcome**

It would be nice if matplotlib did any of these:
1. Gave a clear error message when `matplotlib.use()` was called the first time.
2. Gave a clear error message when `matplotlib.pyplot` is imported and an invalid backend is selected.
2. Silently allowed setting an invalid backend with `matplotlib.use()` even after pyplot is imported.

**Matplotlib version**

  * Operating system:
  * Matplotlib version: 3.0.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): NA
  * Python version: 3.7
  * Jupyter version (if applicable):
  * Other libraries: 

As far as I can tell, the source of the problem is that matplotlib only actually validates backends if `matplotlib.pyplot` is imported:
https://github.com/matplotlib/matplotlib/blob/d9030efd40fe4300e775db22ba55845399f6668f/lib/matplotlib/__init__.py#L1281=L1283

It seems like one good way to avoid this would be to use a consistent codepath, whether or not `matplotlib.pyplot` has already been imported, e.g., by always calling `matplotlib.pyplot.switch_backend()`. Or maybe `matplotlib.use()` could do some basic validation, e.g., to verify that the backend is a valid choice.

**Comment by tacaswell** [comment]
This is the intersection of a couple of things that are trying to be nice the user.  The first call to `use` is effecitvely being discarded as https://github.com/matplotlib/matplotlib/blob/e4839b7c86605c1850aa57bb3f5a9c44f98469b3/lib/matplotlib/pyplot.py#L2284-L2290 is re-setting the backend to "auto" which does it's best to pick a compatible backend.

If you set `rcParms['backend_fallback']` to False it works as expected:

```python
amilyn@12:55  ➤  ipython
Python 3.7.1 (default, Dec 14 2018, 19:28:38) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.2.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import matplotlib                                                                                                                                                                                                                                                                 

In [2]: matplotlib.rcParams['backend_fallback']                                                                                                                                                                                                                                           
Out[2]: True

In [3]: matplotlib.rcParams['backend_fallback'] = False                                                                                                                                                                                                                                   

In [4]: import os                                                                                                                                                                                                                                                                         

In [5]: os.environ.pop("DISPLAY", None)                                                                                                                                                                                                                                                   
Out[5]: ':0'

In [6]: matplotlib.use('tkagg')                                                                                                                                                                                                                                                           

In [7]: import matplotlib.pyplot                                                                                                                                                                                                                                                          
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-7-864e826dab68> in <module>
----> 1 import matplotlib.pyplot

~/.conda/envs/dd37/lib/python3.7/site-packages/matplotlib/pyplot.py in <module>
   2370     dict.__setitem__(rcParams, "backend", rcsetup._auto_backend_sentinel)
   2371 # Set up the backend.
-> 2372 switch_backend(rcParams["backend"])
   2373 
   2374 # Just to be safe.  Interactive mode can be turned on without

~/.conda/envs/dd37/lib/python3.7/site-packages/matplotlib/pyplot.py in switch_backend(newbackend)
    220                 "Cannot load backend {!r} which requires the {!r} interactive "
    221                 "framework, as {!r} is currently running".format(
--> 222                     newbackend, required_framework, current_framework))
    223 
    224     rcParams['backend'] = rcParamsDefault['backend'] = newbackend

ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'headless' is currently running

In [8]:                                                                                                                                                                                                                                                                                   
```

I suspect the fix is to in `matplolib.use` to set `bacend_fallback` to False to indicate that the user really did want the backend in the rcparams.

**Comment by shoyer** [comment]
I believe this can be considered fixed by https://github.com/matplotlib/matplotlib/pull/13977.

Thanks for the quick follow up!
