### ISSUE TITLE
Impossible to draw long dashed line

### ISSUE THREAD

**Issue by mark-i-m** [matplotlib/matplotlib#13979]
### Bug report

**Bug summary**

`OverflowError` when plotting long dashed line. **Not** solved by setting `agg.path.chucksize`. 
Note that this **only** happens when the line is "dashed".

**Code for reproduction**

```python
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.collections as collect

fig, ax = plt.subplots(figsize=(8, 5))
matplotlib.rcParams['agg.path.chunksize'] = 1000000000000000000000

ax.add_collection(collect.LineCollection([[(0,0), (1E12, 0)]], linestyle="dashed"))

plt.show()

```

**Actual outcome**

Note that this **only** happens when the line is "dashed".

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/u/m/a/markm/.local/lib/python3.6/site-packages/matplotlib/backends/_backend_tk.py", line 267, in resize
    self.draw()
  File "/u/m/a/markm/.local/lib/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 9, in draw
    super(FigureCanvasTkAgg, self).draw()
  File "/u/m/a/markm/.local/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 402, in draw
    self.figure.draw(self.renderer)
  File "/u/m/a/markm/.local/lib/python3.6/site-packages/matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/u/m/a/markm/.local/lib/python3.6/site-packages/matplotlib/figure.py", line 1649, in draw
    renderer, self, artists, self.suppressComposite)
  File "/u/m/a/markm/.local/lib/python3.6/site-packages/matplotlib/image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "/u/m/a/markm/.local/lib/python3.6/site-packages/matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/u/m/a/markm/.local/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 2628, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/u/m/a/markm/.local/lib/python3.6/site-packages/matplotlib/image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "/u/m/a/markm/.local/lib/python3.6/site-packages/matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/u/m/a/markm/.local/lib/python3.6/site-packages/matplotlib/collections.py", line 332, in draw
    self._offset_position)
OverflowError: In draw_path_collection: Exceeded cell block limit
Exception in Tkinter callback
Traceback (most recent call last):
  File "/u/m/a/markm/.local/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 149, in draw_path
    self._renderer.draw_path(gc, path, transform, rgbFace)
OverflowError: In draw_path: Exceeded cell block limit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/usr/lib/python3.6/tkinter/__init__.py", line 749, in callit
    func(*args)
  File "/u/m/a/markm/.local/lib/python3.6/site-packages/matplotlib/backends/_backend_tk.py", line 346, in idle_draw
    self.draw()
  File "/u/m/a/markm/.local/lib/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 9, in draw
    super(FigureCanvasTkAgg, self).draw()
  File "/u/m/a/markm/.local/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 402, in draw
    self.figure.draw(self.renderer)
  File "/u/m/a/markm/.local/lib/python3.6/site-packages/matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/u/m/a/markm/.local/lib/python3.6/site-packages/matplotlib/figure.py", line 1646, in draw
    self.patch.draw(renderer)
  File "/u/m/a/markm/.local/lib/python3.6/site-packages/matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/u/m/a/markm/.local/lib/python3.6/site-packages/matplotlib/patches.py", line 535, in draw
    renderer.draw_path(gc, tpath, affine, rgbFace)
  File "/u/m/a/markm/.local/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 151, in draw_path
    raise OverflowError("Exceeded cell block limit (set "
OverflowError: Exceeded cell block limit (set 'agg.path.chunksize' rcparam)

```

**Expected outcome**

I should see a long dashed line plotted.

**Matplotlib version**

  * Operating system: Ubuntu 18.04
  * Matplotlib version: 3.0.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): `TkAgg`
  * Python version: 3.6.7

At first, I tried this with matplotlib installed from `apt install python3-mathplotlib`. Then, I tried with matplotlib installed via `pip3`.

**Comment by tacaswell** [comment]
Indeed, I can reproduce this.  I suspect that problem is that the dashed line is implicitly drawn as many small lines.  The chunk size lets you split the line up into small sections, but you only have 2 points so splitting does not help...

**Comment by timhoffm** [comment]
Related: #14498

**Comment by timhoffm** [comment]
This has the same cause as #14498. It's enough tracking the issue there.
