### ISSUE TITLE
annotation connectionstyle and width, headwidth compatibility issue

### ISSUE THREAD

**Issue by jiadongdan** [matplotlib/matplotlib#14195]
Some connectionstyle can not work!!!

See code below:

```python
fig, ax = plt.subplots(1, 1, figsize=(7.2, 7.2))
start = (0.1, 0.1)
end = (0.5, 0.5)
connectionstyle='arc3, rad=1'
#connectionstyle='angle,angleA=-90,angleB=10,rad=5' #this not working

ax.annotate("",
            xy=end, xycoords='data',
            xytext=start, textcoords='data',
            arrowprops=dict(#arrowstyle="->, head_length=1, head_width=1",
                            width=10,headwidth=30,
                            color="0.5",
                            shrinkA=5, shrinkB=5,
                            patchA=None,
                            patchB=None,
                            connectionstyle=connectionstyle,
                            ),)
```

This code snipet works fine. However, if I change `connectionstyle` to "angle,angleA=-90,angleB=10,rad=5", it just does not work. Not sure what is wrong. 

matplotlib version: 3.0.3

**Comment by jklymak** [comment]
```
Traceback (most recent call last):
  File "/Users/jklymak/matplotlib/lib/matplotlib/backends/backend_qt5.py", line 501, in _draw_idle
    self.draw()
  File "/Users/jklymak/matplotlib/lib/matplotlib/backends/backend_agg.py", line 388, in draw
    self.figure.draw(self.renderer)
  File "/Users/jklymak/matplotlib/lib/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/Users/jklymak/matplotlib/lib/matplotlib/figure.py", line 1716, in draw
    renderer, self, artists, self.suppressComposite)
  File "/Users/jklymak/matplotlib/lib/matplotlib/image.py", line 135, in _draw_list_compositing_images
    a.draw(renderer)
  File "/Users/jklymak/matplotlib/lib/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/Users/jklymak/matplotlib/lib/matplotlib/axes/_base.py", line 2670, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/Users/jklymak/matplotlib/lib/matplotlib/image.py", line 135, in _draw_list_compositing_images
    a.draw(renderer)
  File "/Users/jklymak/matplotlib/lib/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/Users/jklymak/matplotlib/lib/matplotlib/text.py", line 2369, in draw
    self.arrow_patch.draw(renderer)
  File "/Users/jklymak/matplotlib/lib/matplotlib/patches.py", line 4303, in draw
    path, fillable = self.get_path_in_displaycoord()
  File "/Users/jklymak/matplotlib/lib/matplotlib/patches.py", line 4287, in get_path_in_displaycoord
    self.get_mutation_aspect())
  File "/Users/jklymak/matplotlib/lib/matplotlib/patches.py", line 3250, in __call__
    return self.transmute(path, mutation_size, linewidth)
  File "/Users/jklymak/matplotlib/lib/matplotlib/patches.py", line 3717, in transmute
    x0, y0, x1, y1, x2, y2 = self.ensure_quadratic_bezier(path)
  File "/Users/jklymak/matplotlib/lib/matplotlib/patches.py", line 3202, in ensure_quadratic_bezier
    "'path' is not a valid quadratic Bezier curve")
ValueError: 'path' is not a valid quadratic Bezier curve
```

**Comment by ksunden** [comment]
I think that this is actually correct that it is unable to work and should raise, however I think the work is to make the error message more understandable (and potentially erroring before draw is called, but that is less necessary). While "not a valid quadratic Bezier curve" is at least in some sense accurate and the proximal cause of the incompatibility, it is not useful to a user who asked for an arrow to be drawn. 

The short version is that the default arrow style is `"simple"`, which can only work with a subset of connection styles, such as `arc3` or `angle3`.

Setting the arrow style to e.g. `->` (or pretty much any of the more pictoral keys, i.e. all except "simple", "fancy", or "wedge") will fix it.

The [`annotate` docstring](https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.annotate.html#matplotlib.axes.Axes.annotate) for the *arrowprops* arg gets at this behavior by saying:


> For historical reasons there are two different ways to specify arrows, "simple" and "fancy":
> 
> Simple arrow:
> 
> If arrowprops does not contain the key 'arrowstyle' the allowed keys are:
>
> \<table removed for brevity, but notably "connectionstyle" is absent>
>
> ...
>
> Fancy arrow:
> 
> This is used if 'arrowstyle' is provided in the arrowprops.
> 
> Valid keys are the following [FancyArrowPatch](https://matplotlib.org/stable/api/_as_gen/matplotlib.patches.FancyArrowPatch.html#matplotlib.patches.FancyArrowPatch) parameters:
>
> \<table removed for brevity, but notably "connectionstyle" is present>

Technically, there are some options for "connectionstyle" that _will_ work, and they do still get passed through to `FancyArrowPatch` so not sure disallowing it fully would be advisable.

**Comment by timhoffm** [comment]
The updated docstring that @ksunden mentions has been added in #21743, so after this issue was created. I consider the issue solved through that PR.
