### ISSUE TITLE
Exception importing  pyplot

### ISSUE THREAD

**Issue by dhirschfeld** [matplotlib/matplotlib#14306]
Today, in a docker build on win64/py37 I'm seeing an error when importing pylab:
```
python -c "import matplotlib.pyplot"
```
```
2019-05-24T05:04:57.7175630Z Configuring matplotlib...
2019-05-24T05:04:59.2114991Z Traceback (most recent call last):
2019-05-24T05:04:59.2115844Z 
2019-05-24T05:04:59.2116045Z   File "<string>", line 1, in <module>
2019-05-24T05:04:59.2116346Z 
2019-05-24T05:04:59.2116637Z   File "C:\ProgramData\Miniconda3\envs\py-dev\lib\site-packages\matplotlib\pyplot.py", line 2349, in <module>
2019-05-24T05:04:59.2116956Z 
2019-05-24T05:04:59.2117704Z     switch_backend(rcParams["backend"])
2019-05-24T05:04:59.2118058Z 
2019-05-24T05:04:59.2118302Z   File "C:\ProgramData\Miniconda3\envs\py-dev\lib\site-packages\matplotlib\__init__.py", line 820, in __getitem__
2019-05-24T05:04:59.2118602Z 
2019-05-24T05:04:59.2118837Z     plt.switch_backend(rcsetup._auto_backend_sentinel)
2019-05-24T05:04:59.2119034Z 
2019-05-24T05:04:59.2119280Z   File "C:\ProgramData\Miniconda3\envs\py-dev\lib\site-packages\matplotlib\pyplot.py", line 212, in switch_backend
2019-05-24T05:04:59.2119502Z 
2019-05-24T05:04:59.2119728Z     newbackend[9:] if newbackend.startswith("module://")
2019-05-24T05:04:59.2119918Z 
2019-05-24T05:04:59.2120115Z AttributeError: 'object' object has no attribute 'startswith'
```

I'll try to get some more information to help identify the problem...

**Comment by dhirschfeld** [comment]
This same dockerfile used to work so I'm assuming there was some change in [`3.1.0`](https://github.com/matplotlib/matplotlib/releases/tag/v3.1.0) which has broken our usage.

**Comment by dhirschfeld** [comment]
Seems to be a dup of #14263
