### ISSUE TITLE
hist() fails when all data points are np.nan

### ISSUE THREAD

**Issue by MaozGelbart** [matplotlib/matplotlib#14439]
### Bug report

**Bug summary**

As of #6483 ``plt.hist()`` allows for ``np.nan``-containing input, but raises warnings and fails when *all* data points are ``np.nan``. 

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt

plt.hist([np.nan])
```

**Actual outcome**

```python
C:\ProgramData\Miniconda3\lib\site-packages\matplotlib\axes\_axes.py:6721: RuntimeWarning: All-NaN slice encountered
  xmin = min(xmin, np.nanmin(xi))
C:\ProgramData\Miniconda3\lib\site-packages\matplotlib\axes\_axes.py:6722: RuntimeWarning: All-NaN slice encountered
  xmax = max(xmax, np.nanmax(xi))
Traceback (most recent call last):
  File "D:\nan_hist.py", line 4, in <module>
    plt.hist([np.nan])
  File "C:\ProgramData\Miniconda3\lib\site-packages\matplotlib\pyplot.py", line 2636, in hist
    **({"data": data} if data is not None else {}), **kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\matplotlib\__init__.py", line 1589, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\matplotlib\axes\_axes.py", line 6753, in hist
    m, bins = np.histogram(x[i], bins, weights=w[i], **hist_kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\numpy\lib\histograms.py", line 780, in histogram
    bin_edges, uniform_bins = _get_bin_edges(a, bins, range, weights)
  File "C:\ProgramData\Miniconda3\lib\site-packages\numpy\lib\histograms.py", line 417, in _get_bin_edges
    first_edge, last_edge = _get_outer_edges(a, range)
  File "C:\ProgramData\Miniconda3\lib\site-packages\numpy\lib\histograms.py", line 315, in _get_outer_edges
    "autodetected range of [{}, {}] is not finite".format(first_edge, last_edge))
ValueError: autodetected range of [nan, nan] is not finite
```

**Expected outcome**

An output similar to ``plt.hist([])``

**Matplotlib version**

  * Operating system: Windows
  * Matplotlib version: 3.1.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.7.3
  * Other libraries: numpy 1.16.3

Matplotlib installed through conda-forge.

**Comment by tacaswell** [comment]
That does seem like the correct behavior, but I have concerns about moving away from the behavior of `np.histogram` (as those exceptions are actually originating in numpy).

**Comment by WeatherGod** [comment]
should the behavior be similar to when an empty array is passed in?

**Comment by MaozGelbart** [comment]
The numpy exception are around the automatic range determination of the bins when they were not specified. However, the following code works: ``np.histogram([np.nan], bins=[])`` but this one raises a (different) error in ``Axes.hist()``: ``plt.hist([np.nan], bins=[])``

**Comment by tacaswell** [comment]
Currently on master this warns, but does not raise.

```
In [5]: plt.hist([np.nan], bins=[])                                                                                                                           
/home/tcaswell/src/p/matplotlib/lib/matplotlib/axes/_axes.py:6614: RuntimeWarning: All-NaN slice encountered
  xmin = min(xmin, np.nanmin(xi))
/home/tcaswell/src/p/matplotlib/lib/matplotlib/axes/_axes.py:6615: RuntimeWarning: All-NaN slice encountered
  xmax = max(xmax, np.nanmax(xi))
Out[5]: 
(array([], dtype=float64),
 array([], dtype=float64),
 <a list of 0 Patch objects>)

```

I think this is reasonable behavior so I am going to close this, @MaozGelbart please ping to have this re-opened or open a new issue if you disagree.

Thanks for reporting this!
