### ISSUE TITLE
Multicolor errorbars cannot have caps

### ISSUE THREAD

**Issue by ImportanceOfBeingErnest** [matplotlib/matplotlib#14480]
### Bug report

**Bug summary**

Bringing https://stackoverflow.com/questions/56490293/why-do-i-get-an-invalid-rgba-argument-valueerror-when-defining-capsize-to-my-e to the issue tracker.

Multicolored errorbars cannot have caps. Settings `capsize` for a bar plot with multiple colors results in a ValueError.

**Code for reproduction**

```
import matplotlib.pyplot as plt
plt.rcParams["errorbar.capsize"] = 2

fig, ax = plt.subplots( figsize=(3,3))

colors=['crimson', 'limegreen', 'indigo']

ax.bar( [0,1,2], 
        [5,3,4],
        linewidth=2,
        color="papayawhip",
        edgecolor=colors,
        ecolor=colors,
        yerr=[1.5, 1, 1.5], 
        error_kw = {
            'elinewidth': 2, }
        )

plt.show()
```

**Actual outcome**

```
Traceback (most recent call last):
  File "D:\***\lib\site-packages\matplotlib\backends\backend_qt5.py", line 501, in _draw_idle
    self.draw()
  File "D:\***\lib\site-packages\matplotlib\backends\backend_agg.py", line 388, in draw
    self.figure.draw(self.renderer)
  File "D:\***\lib\site-packages\matplotlib\artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "D:\***\lib\site-packages\matplotlib\figure.py", line 1709, in draw
    renderer, self, artists, self.suppressComposite)
  File "D:\***\lib\site-packages\matplotlib\image.py", line 135, in _draw_list_compositing_images
    a.draw(renderer)
  File "D:\***\lib\site-packages\matplotlib\artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "D:\***\lib\site-packages\matplotlib\axes\_base.py", line 2645, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "D:\***\lib\site-packages\matplotlib\image.py", line 135, in _draw_list_compositing_images
    a.draw(renderer)
  File "D:\***\lib\site-packages\matplotlib\artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "D:\***\lib\site-packages\matplotlib\lines.py", line 812, in draw
    self.get_markeredgecolor(), self._alpha)
  File "D:\***\lib\site-packages\matplotlib\colors.py", line 177, in to_rgba
    rgba = _to_rgba_no_colorcycle(c, alpha)
  File "D:\***\lib\site-packages\matplotlib\colors.py", line 238, in _to_rgba_no_colorcycle
    raise ValueError("Invalid RGBA argument: {!r}".format(orig_c))
ValueError: Invalid RGBA argument: ['crimson', 'limegreen', 'indigo']
```

**Expected outcome**

Expected outcome would be the same as with

    plt.rcParams["errorbar.capsize"] = 0

![image](https://user-images.githubusercontent.com/23121882/59093295-defcbc80-8913-11e9-8d4b-7d77a6032a2a.png)

***but with caps on the errorbars.***

**Matplotlib version**

  * Operating system: Win8
  * Matplotlib version: current
  * Matplotlib backend (`print(matplotlib.get_backend())`): any
  * Python version: 3.6.6

**Comment by jklymak** [comment]
Is this a regression?

**Comment by ImportanceOfBeingErnest** [comment]
No, I don't think so. It's a problem of the API, which allows for arguments which cannot be processed correctly, as the caps (being markers of a `Line2D`) are always single-colored. So I doubt this has ever worked.

**Comment by avk0** [comment]
Have the same issue

plt.errorbar([1,2], [1,2], yerr=[1,3], capsize=None, ecolor=['red','green'])     # works
plt.errorbar([1,2], [1,2], yerr=[1,3], capsize=3, ecolor=['red','green'])            # doesn't work

**Comment by jklymak** [comment]
@edbennett if this is a regression, can you share the code and version that used to work and now does not?  Thanks!

**Comment by edbennett** [comment]
Thanks @jklymak, but the issue was a change elsewhere in the environment the script was being run in meaning that `errorbar.capsize` had changed from 0 to 1; as discussed by the commenters above, I don't think that this has ever worked correctly when error bar caps are used.

For completeness, the minimal script to reproduce I came up with:

```
from matplotlib import pyplot as plt

def test(with_caps):
    if with_caps:
        plt.rc("errorbar", capsize=2)

    fig, ax = plt.subplots()
    ax.errorbar([1, 2], [3, 4],
                yerr=[0.5, 0.6], marker="None", linestyle="None",
                ecolor=[[1, 0, 0, 1], [0, 1, 0, 0]])
    plt.show()

test(with_caps=False) # Works
test(with_caps=True) # Fails with the ValueError mentioned above
```

**Comment by jklymak** [comment]
OK, thanks - we try to deliver faster service for actual regressions ;-), but certainly someone should try and fix this.

**Comment by timhoffm** [comment]
The underlying issue is that the errorbar functionality is just a convenience shortcut to [errorbar()](https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.errorbar.html) and that does not support multiple colors.

Technically, in more detail, errorbars are constructed out of three Artists: markers (Line2D), the vertical line (LineCollection) and the caps (Line2D). Line2D by design does not support multiple colors.

Nowadays we likely would not add errorbar functionality to bar, because it's combines multiple visualizations and increases complexity, it's clearer to do two seprate calls `bar(); errorbar()`. And here we see that in more complex cases we cannot live up to the promised integration.

My proposal here is to close with "won't fix" - we don't support per bar coloring and errorbars at the same time. I'd just document on `xerr, yerr`
> Errorbars are not officially supported when bars are individually colored, because the underlying `~.Axes.errorbar` is not designed for individual coloring per data point. Please use one ``errorbar()`` call per data point in this case.

I'm -1 on any changes to the errorbar() function to support multiple colors. It's not intended for that.

**Comment by timhoffm** [comment]
Closing as not planned. #31579 will document that this is not supported.
