### ISSUE TITLE
AttributeError: 'str' object has no attribute 'N'

### ISSUE THREAD

**Issue by daxinnan** [matplotlib/matplotlib#14517]
### Bug report

I run anaconda python3.6.8, and I wanna to plot some wrf(a meteorological model) domain figures in Lambert Conformal Conic projection and one error occurred.
Actually, I rewrite code from [here](https://github.com/lucas-uw/WRF-tools/blob/master/WRF_input_tools/Visualize_WPS_domain.ipynb).
**Bug summary**

As we can see, this 
```python
cb1 = mpl.colorbar.ColorbarBase(cbar_ax, cmap='terrain', orientation='vertical', ticks=[np.arange(0, 1.01, 0.25)])
```
is the key, but I don't know why.

**Code for reproduction**

```python
import matplotlib.pyplot as plt
import matplotlib as mpl

#some calculations and d01, d02 box settings

fig1 = plt.figure(figsize=(10, 8))
ax1 = plt.axes(projection=wpsproj)
xticks = [70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94]
yticks = [32, 35, 38, 41, 43, 47, 50]
ax1.gridlines(xlocs=xticks, ylocs=yticks)
ax1.xaxis.set_major_formatter(LONGITUDE_FORMATTER)
ax1.yaxis.set_major_formatter(LATITUDE_FORMATTER)
lambert_xticks(ax1, xticks, 14)
lambert_yticks_left(ax1, yticks, 14)
ax1.set_title('WRF test', size=20)

cbar_ax = fig1.add_axes([0.92, 0.2, 0.02, 0.6])
cb1 = mpl.colorbar.ColorbarBase(cbar_ax, cmap='terrain', orientation='vertical', ticks=[np.arange(0, 1.01, 0.25)])
cb1.set_ticklabels(['0', '1000', '2000', '3000', '4000'])
cbar_ax.tick_params(labelsize=12)
cbar_ax.text(1.9, -0.01, 'm', size=12)

plt.show()
```

**Actual outcome**
```
Traceback (most recent call last):
  File "/home/lxc/.vscode/extensions/ms-python.python-2019.5.18875/pythonFiles/ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "/home/lxc/.vscode/extensions/ms-python.python-2019.5.18875/pythonFiles/lib/python/ptvsd/__main__.py", line 434, in main
    run()
  File "/home/lxc/.vscode/extensions/ms-python.python-2019.5.18875/pythonFiles/lib/python/ptvsd/__main__.py", line 312, in run_file
    runpy.run_path(target, run_name='__main__')
  File "/home/lxc/anaconda3/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/home/lxc/anaconda3/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/lxc/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/lxc/Desktop/wpsplot/draw_domain.py", line 342, in <module>
    cb1 = mpl.colorbar.ColorbarBase(cbar_ax, cmap='terrain', orientation='vertical', ticks=[np.arange(0, 1.01, 0.25)])
  File "/home/lxc/anaconda3/lib/python3.6/site-packages/matplotlib/colorbar.py", line 460, in __init__
    self.draw_all()
  File "/home/lxc/anaconda3/lib/python3.6/site-packages/matplotlib/colorbar.py", line 483, in draw_all
    self._process_values()
  File "/home/lxc/anaconda3/lib/python3.6/site-packages/matplotlib/colorbar.py", line 932, in _process_values
    b = self.norm.inverse(self._uniform_y(self.cmap.N + 1))
AttributeError: 'str' object has no attribute 'N'
```

**Expected outcome**
A picture the same like [wrf_domain_python](https://wolfscie.files.wordpress.com/2017/10/wrf_domain_python.png)

**Matplotlib version**
  * Operating system: Ubuntu 18.04.2 LTS, 8G memory
  * Matplotlib version:  3.1.0
  * Matplotlib backend: Qt5Agg
  * Python version: 3.6.8
  * Jupyter version (if applicable):
   jupyter_console           6.0.0
   jupyter_core                4.4.0
  * Other libraries: 

 I installed matplotlib from conda

conda channels:
  - https://repo.continuum.io/pkgs/main/
  - https://repo.continuum.io/pkgs/free/
  - defaults

**Comment by ImportanceOfBeingErnest** [comment]
`ColorbarBase` is the base class for colorbars. It would only accept actual colormaps as input for `cmap`, as opposed to string names of colormaps. 

     ColorbarBase(..., cmap=plt.cm.terrain, ...)

I'm always a big fan of creating the colorbar through `fig.colorbar`, which makes it clearer that you need a `ScalarMappable` for the colormapping. 

Also `ticks` needs to be a list or array, not a list *of* an array.

So here is how I would do it:

```
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl

fig, ax = plt.subplots()
ax.set_title('WRF test', size=20)

cbar_ax = fig.add_axes([0.92, 0.2, 0.02, 0.6])

sm = mpl.cm.ScalarMappable(cmap=plt.cm.terrain, norm=plt.Normalize(0,1))
cb1 = fig.colorbar(sm, cax=cbar_ax, 
                   ticks=np.arange(0, 1.01, 0.25),
                   format=mpl.ticker.FuncFormatter(lambda x,_: x*4000))

cbar_ax.tick_params(labelsize=12)

plt.show()
```

**Comment by daxinnan** [comment]
Wow, thank you, I just now read the docs again and found this low-level mistake, thanks for your code!
