### ISSUE TITLE
Undefined symbol in ft2font.cpython-36m-x86_64-linux-gnu.so upon import of ft2font

### ISSUE THREAD

**Issue by blaiseli** [matplotlib/matplotlib#14684]
### Bug report

**Bug summary**

I updated matplotlib using pip, switching from 3.0.2 to 3.1.1 (`python3.6 -m pip install -U matplotlib`) and now matplotlib cannot be imported. I got the following error:

```
ImportError: /pasteur/homes/bli/.local/lib/python3.6/site-packages/matplotlib/ft2font.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZNSt13runtime_errorC1EPKc
```

Switching back to 3.0.2 (`python3.6 -m pip install matplotlib==3.0.2`) recovers a working matplotlib

**Code for reproduction**

I tested installing from the git repository:
```
git clone https://github.com/matplotlib/matplotlib.git
cd matplotlib
python3.6 -m pip install .
```

This `Successfully installed matplotlib-3.1.0+1299.gce72670` (strangely, this looks like a lower version number than 3.1.1), and importing matpplotlib fails again:

```
$ python3.6 -c "import matplotlib"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/pasteur/homes/bli/.local/lib/python3.6/site-packages/matplotlib/__init__.py", line 206, in <module>
    _check_versions()
  File "/pasteur/homes/bli/.local/lib/python3.6/site-packages/matplotlib/__init__.py", line 191, in _check_versions
    from . import ft2font
ImportError: /pasteur/homes/bli/.local/lib/python3.6/site-packages/matplotlib/ft2font.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZTVNSt7__cxx1115basic_stringbufIcSt11char_traitsIcESaIcEEE

```

**Matplotlib version**

  * Operating system: Linux CentOS on a computing cluster
  * Matplotlib version: 3.1.1, 3.1.0+1299.gce72670
  * Python version: 3.6.0

**Comment by blaiseli** [comment]
I don't have this problem on a Ubuntu 16.04 workstation.
