### ISSUE TITLE
While import matplotlib I'm getting following Error message. How to solve this ?

### ISSUE THREAD

**Issue by imzi** [matplotlib/matplotlib#14685]
### Bug report

**Bug summary**

**Code for reproduction**

```python
import matplotlib.pyplot as plt
```

**Actual outcome**

```
Traceback (most recent call last):
  File "e:\FourthYear\Research\Practice\testi.py", line 1, in <module>
    import matplotlib.pyplot as plt
  File "C:\Python27\lib\site-packages\matplotlib\__init__.py", line 129, in <module>
    from matplotlib.cbook import is_string_like
  File "C:\Python27\lib\site-packages\matplotlib\cbook.py", line 28, in <module>
    import numpy as np
  File "C:\Python27\lib\site-packages\numpy\__init__.py", line 170, in <module>
    from . import add_newdocs
  File "C:\Python27\lib\site-packages\numpy\add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "C:\Python27\lib\site-packages\numpy\lib\__init__.py", line 8, in <module>
    from .type_check import *
  File "C:\Python27\lib\site-packages\numpy\lib\type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "C:\Python27\lib\site-packages\numpy\core\__init__.py", line 6, in <module>
    from . import multiarray
ImportError: DLL load failed: %1 is not a valid Win32 application.
```

**Expected outcome**

**Matplotlib version**

  * Operating system: Windows 10
  * Matplotlib version:  Could not find due to Error
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version: 2.7
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by jklymak** [comment]
@imzi  This is failing on the numpy import, which is another library matplotlib uses.  Please make sure you have properly installed matplotlib and all its dependencies.  If you need to follow up, please be sure to say what you have done to install matplotlib.  Strongly suggest using conda (https://conda.io/en/latest/)

**Comment by imzi** [comment]
> @imzi This is failing on the numpy import, which is another library matplotlib uses. Please make sure you have properly installed matplotlib and all its dependencies. If you need to follow up, please be sure to say what you have done to install matplotlib. Strongly suggest using conda (https://conda.io/en/latest/)

I will try @JackKelly

**Comment by story645** [comment]
@imzi did @jklymak's answer solve your issue? I'm going to close this for now, but can reopen if needed.
