### ISSUE TITLE
hist2d / pcolormesh / colorbar + LogNorm: Unhelpful error when all bins are empty

### ISSUE THREAD

**Issue by larsfu** [matplotlib/matplotlib#14738]
### Bug report

**Bug summary**

When doing `hist2d` while using a `colorbar` and `LogNorm` one gets a rather unhelpful error message, if one by accident chooses a `range` in which no entries are present.

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt
import matplotlib

x = np.random.uniform(size=100)
y = np.random.uniform(size=100)

plt.hist2d(x, y, range=((1, 2), (1, 2)), norm=matplotlib.colors.LogNorm())
plt.colorbar()
plt.show()
plt.close()
```

**Actual outcome**
```
emptyhist2d.py:16: UserWarning: Attempted to set non-positive left xlim on a log-scaled axis.
Invalid limit will be ignored.
  plt.colorbar()
emptyhist2d.py:16: UserWarning: Attempted to set non-positive bottom ylim on a log-scaled axis.
Invalid limit will be ignored.
  plt.colorbar()
Traceback (most recent call last):
  File "emptyhist2d.py", line 17, in <module>
    plt.savefig('test.pdf')
  File "/usr/lib/python3.7/site-packages/matplotlib/pyplot.py", line 722, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/matplotlib/figure.py", line 2180, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/usr/lib/python3.7/site-packages/matplotlib/backends/backend_qt5agg.py", line 88, in print_figure
    super().print_figure(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2082, in print_figure
    **kwargs)
  File "/usr/lib/python3.7/site-packages/matplotlib/backends/backend_pdf.py", line 2503, in print_pdf
    self.figure.draw(renderer)
  File "/usr/lib/python3.7/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/matplotlib/figure.py", line 1709, in draw
    renderer, self, artists, self.suppressComposite)
  File "/usr/lib/python3.7/site-packages/matplotlib/image.py", line 135, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/lib/python3.7/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 2647, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/usr/lib/python3.7/site-packages/matplotlib/image.py", line 135, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/lib/python3.7/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/matplotlib/collections.py", line 2017, in draw
    self.update_scalarmappable()
  File "/usr/lib/python3.7/site-packages/matplotlib/collections.py", line 763, in update_scalarmappable
    self._facecolors = self.to_rgba(self._A, self._alpha)
  File "/usr/lib/python3.7/site-packages/matplotlib/cm.py", line 289, in to_rgba
    x = self.norm(x)
  File "/usr/lib/python3.7/site-packages/matplotlib/colors.py", line 1096, in __call__
    raise ValueError("values must all be positive")
ValueError: values must all be positive
```

**Expected outcome**

I understand that it does not make any sense to construct a colormap for this case, but it would be nice if there was some warning that all bins are empty. Especially, because everything runs fine if only _some_ bins are empty.

**Matplotlib version**
  * Operating system: Arch
  * Matplotlib version: 3.1.1
  * Matplotlib backend: Qt5Agg
  * Python version: 3.7

**Comment by dstansby** [comment]
This is arguable a bit better in the current `master` version of the code:
```python
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    plt.colorbar()
  File "/Users/dstansby/github/matplotlib/lib/matplotlib/pyplot.py", line 2043, in colorbar
    ret = gcf().colorbar(mappable, cax=cax, ax=ax, **kw)
  File "/Users/dstansby/github/matplotlib/lib/matplotlib/figure.py", line 2224, in colorbar
    cb = cbar.colorbar_factory(cax, mappable, **cb_kw)
  File "/Users/dstansby/github/matplotlib/lib/matplotlib/colorbar.py", line 1633, in colorbar_factory
    cb = Colorbar(cax, mappable, **kwargs)
  File "/Users/dstansby/github/matplotlib/lib/matplotlib/colorbar.py", line 1178, in __init__
    ColorbarBase.__init__(self, ax, **kw)
  File "/Users/dstansby/github/matplotlib/lib/matplotlib/colorbar.py", line 456, in __init__
    self.draw_all()
  File "/Users/dstansby/github/matplotlib/lib/matplotlib/colorbar.py", line 479, in draw_all
    self._process_values()
  File "/Users/dstansby/github/matplotlib/lib/matplotlib/colorbar.py", line 921, in _process_values
    b = self.norm.inverse(self._uniform_y(self.cmap.N + 1))
  File "/Users/dstansby/github/matplotlib/lib/matplotlib/colors.py", line 1161, in inverse
    self._check_vmin_vmax()
  File "/Users/dstansby/github/matplotlib/lib/matplotlib/colors.py", line 1122, in _check_vmin_vmax
    raise ValueError("minvalue must be positive")
ValueError: minvalue must be positive
```
with the error coming earlier when a colorbar is constructed and not at draw time. I'm not sure how to make this even clearer though; `axes.pcolormesh()` would have to do some validating of the norm.

**Comment by oscargus** [comment]
In current main the (really long, ending with) error has changed to is:
```
  File "C:\Users\Oscar\matplotlib\lib\matplotlib\colors.py", line 1664, in __call__
    raise ValueError("Invalid vmin or vmax")

ValueError: Invalid vmin or vmax
```
when calling `colorbar`
