### ISSUE TITLE
Segment fault when set dpi too high

### ISSUE THREAD

**Issue by qiankehan** [matplotlib/matplotlib#14842]
### Bug report

**Bug summary**
Set plt.figure(dpi=) too high such as **5000**, then python3 will get a segment fault when saving the graph file.

**Code for reproduction**
```py
import matplotlib.pyplot as plt
import matplotlib as mpl
mpl.use('Agg')

if __name__ == "__main__":
    plt.figure(figsize=[12, 9], dpi=5000)
    print("figure")
    plt.plot(range(0,4), range(0,4))
    print("plot")
    plt.savefig('a.png')
    print("save")
    plt.clf()
    print("clf")
    plt.close()
    print("close")
```

**Actual outcome**
```
# python3 ./test.py
figure
plot
[1]    13736 segmentation fault (core dumped)  ./test.py
```

Backtrace:
```
#0  0x00007fffea5f7810 in RendererAgg::RendererAgg(unsigned int, unsigned int, double) ()
   from /home/hhan/.local/lib/python3.7/site-packages/matplotlib/backends/_backend_agg.cpython-37m-x86_64-linux-gnu.so
#1  0x00007fffea604567 in ?? () from /home/hhan/.local/lib/python3.7/site-packages/matplotlib/backends/_backend_agg.cpython-37m-x86_64-linux-gnu.so
#2  0x00000000005d8ee9 in type_call (kwds=<optimized out>, args=(60000, 45000, 5000), type=<optimized out>) at ../Objects/typeobject.c:949
#3  _PyObject_FastCallKeywords (callable=<type at remote 0x7fffea83eb80>, stack=<optimized out>, nargs=<optimized out>, kwnames=<optimized out>) at ../Objects/call.c:199
#4  0x0000000000552188 in call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>) at ../Python/ceval.c:4619
#5  _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at ../Python/ceval.c:3124
```

**Expected outcome**
No segment fault

**Matplotlib version**
```
matplotlib              3.1.1, installed from pip3
python3                 3.7.3-1
```

**Comment by timhoffm** [comment]
This has to do with the total size of the figure. Happens equally for
~~~
plt.figure(figsize=[1200, 900], dpi=50)
~~~

**Comment by timhoffm** [comment]
I cannot reproduce with current matplotlib (3.7.1) on linux.
