### ISSUE TITLE
Unknown property facecolor

### ISSUE THREAD

**Issue by yangop8** [matplotlib/matplotlib#14956]
When I want to use **facecolor** to change the Boxplot, I got the follow result:
```
Traceback (most recent call last):
  File "plot.py", line 424, in <module>
    box_plot_multiple(hit_ratio_gather_base,hit_ratio_gather_prefetch,qps_gather_base,qps_gather_prefetch,fig_name)
  File "plot.py", line 279, in box_plot_multiple
    widths=0.6, boxprops={'color':'black', 'facecolor':'#0076ae'}, medianprops={'color': 'black'})
  File "/usr/local/lib/python3.7/site-packages/matplotlib/pyplot.py", line 2496, in boxplot
    is not None else {}))
  File "/usr/local/lib/python3.7/site-packages/matplotlib/__init__.py", line 1810, in inner
    return func(ax, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 3615, in boxplot
    manage_xticks=manage_xticks, zorder=zorder)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 3962, in bxp
    boxes.extend(doplot(box_x, box_y, **final_boxprops))
  File "/usr/local/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 3884, in doplot
    return self.plot(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/__init__.py", line 1810, in inner
    return func(ax, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 1611, in plot
    for line in self._get_lines(*args, **kwargs):
  File "/usr/local/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 393, in _grab_next_args
    yield from self._plot_args(this, kwargs)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 383, in _plot_args
    seg = func(x[:, j % ncx], y[:, j % ncy], kw, kwargs)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 288, in _makeline
    seg = mlines.Line2D(x, y, **kw)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/lines.py", line 410, in __init__
    self.update(kwargs)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/artist.py", line 916, in update
    ret = [_update_property(self, k, v) for k, v in props.items()]
  File "/usr/local/lib/python3.7/site-packages/matplotlib/artist.py", line 916, in <listcomp>
    ret = [_update_property(self, k, v) for k, v in props.items()]
  File "/usr/local/lib/python3.7/site-packages/matplotlib/artist.py", line 912, in _update_property
    raise AttributeError('Unknown property %s' % k)
AttributeError: Unknown property facecolor
```

and my matplotlib version is 3.0.3 and python version is 3.7

**Comment by jklymak** [comment]
Can you give us a self contained example?  Did this work before?

**Comment by yangop8** [comment]
@jklymak ok, I used it as follows:
`plt.boxplot(hit_ratio_base_fn, positions=np.array(np.arange(len(hit_ratio_base_fn))) * 2.0 - 0.4,
                widths=0.6, boxprops={'color':'black', 'facecolor':'#0076ae'}, medianprops={'color': 'black'})`

but it gives me **AttributeError: Unknown property facecolor**
I thought it was because my matplotlib was not the latest version, so I upgraded it from 2.2.3 to 3.0.3, but it didn't work either. I didn't use it before, so on my own, it never works.
Thanks!

**Comment by QuLogic** [comment]
You need to specify `patch_artist=True` if you want there to actually be faces; otherwise the boxes are just 4 lines.

**Comment by yangop8** [comment]
@QuLogic thanks, and it has been figured out through setting `patch_artist=True`
But I still wonder why it gives out different error messages since I run the same code?
This time, I was given the error message like `AttributeError: 'Line2D' object has no property 'facecolor'` and I know I need to set `patch_artist=True`, but if it gives me `AttributeError: Unknown property facecolor`, I don't know how to solve it.
Anyway, thanks a lot for helping! :)
Best wishes!

**Comment by timhoffm** [comment]
`AttributeError: Unknown property facecolor` comes from `AbstractPathEffect._update_gc` whereas `AttributeError: 'Line2D' object has no property 'facecolor'` comes from  `Artist.update()`. These are two different levels of abstraction. I don't think we know the artist in the former case, so the error message is a bit more general.

Closing as I don't think we can improve the error message.

**Comment by gmweir** [comment]
extremely unhelpful close of a current issue

**Comment by aakhmetz** [comment]
Indeed, I thought there would be some solution

**Comment by ImportanceOfBeingErnest** [comment]
The solution to the original problem is in [this comment](https://github.com/matplotlib/matplotlib/issues/14956#issuecomment-517548504) above. 
Note that ***constructive*** feedback is always welcome. So if there is anything that still needs to be addressed, please feel free to give a concise problem description.

**Comment by MAJabed** [comment]
I got a similar issue in ax.fill_between, it works in Jupiter notebook but not in the "Agg" backend in Linux system. I figured out that shortened name - 'fc', 'ec' were the source of error, Attribute error resolve when I used full name - 'facecolor' and 'edgecolor'

**Comment by jklymak** [comment]
@MAJabed  that seems unrelated.  Can you please open a new issue with a self-contained minimal example?

**Comment by moritzpoll** [comment]
Old thread, but in case it's useful: I got this error when throwing a Pandas DataFrame into a plotting function that was expecting a GeoPandas GeoDataFrame.
