### ISSUE TITLE
can't import backend  supporting GUI

### ISSUE THREAD

**Issue by AvivSham** [matplotlib/matplotlib#15038]
I'm trying to plot a simple vector but I'm not able to run the following line `matplotlib.use('tkagg')`  - the output is an error related to tkinter which is odd since it natively installed along with python.

### Bug report

**Bug summary**

**Code for reproduction**

```python
import matplotlib
matplotlib.use('TkAgg')
import matplotlib.pyplot as plt
plt.plot([i for i in range(10)])
plt.show()
```

also tried:

```
import matplotlib.pyplot as plt
plt.plot([i for i in range(10)])
plt.show()
```

**Actual outcome**

```
Traceback (most recent call last):
  File "<input>", line 3, in <module>
  File "/snap/pycharm-professional/147/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/aviv/PycharmProjects/Forecast/venv/lib/python3.6/site-packages/matplotlib/pyplot.py", line 2355, in <module>
    switch_backend(rcParams["backend"])
  File "/home/aviv/PycharmProjects/Forecast/venv/lib/python3.6/site-packages/matplotlib/pyplot.py", line 221, in switch_backend
    backend_mod = importlib.import_module(backend_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/aviv/PycharmProjects/Forecast/venv/lib/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 1, in <module>
    from . import _backend_tk
  File "/snap/pycharm-professional/147/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/aviv/PycharmProjects/Forecast/venv/lib/python3.6/site-packages/matplotlib/backends/_backend_tk.py", line 6, in <module>
    import tkinter as tk
  File "/snap/pycharm-professional/147/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'tkinter'
Failed to enable GUI event loop integration for 'tk'
Traceback (most recent call last):
  File "/snap/pycharm-professional/147/helpers/pydev/pydev_ipython/inputhook.py", line 281, in enable_tk
    import Tkinter as _TK
  File "/snap/pycharm-professional/147/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'Tkinter'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/snap/pycharm-professional/147/helpers/pydev/_pydev_bundle/pydev_code_executor.py", line 209, in do_enable_gui
    enable_gui(guiname)
  File "/snap/pycharm-professional/147/helpers/pydev/pydev_ipython/inputhook.py", line 536, in enable_gui
    return gui_hook(app)
  File "/snap/pycharm-professional/147/helpers/pydev/pydev_ipython/inputhook.py", line 284, in enable_tk
    import tkinter as _TK  # @UnresolvedImport
  File "/snap/pycharm-professional/147/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'tkinter'
```

**Expected outcome**
Linear plot of the input in a separate window.

**Matplotlib version**
  * Operating system: Ubuntu 18.04
  * Matplotlib version: 3.1.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): tried AGG TKAGG QTK3AGG
  * Python version: 3.6.8
  * Using Pycharm if that matters (tried to use both the native interpreter and also creating new virtual env)

**Comment by ImportanceOfBeingErnest** [comment]
Does the same problem occur outside of PyCharm? If yes, please post the stacktrace for that. If not, there isn't really anything we can do here (PyCharm is closed-source; but they have a company own support channel.)

**Comment by AvivSham** [comment]
I have created the following test.py file:

```
import matplotlib
matplotlib.use('tkagg')
import matplotlib.pyplot as plt
plt.plot([i for i in range(10)])
```

In terminal went to test.py root and typed python3 test.py it ran without any errors. 
`python -V` => 3.6.8
`matplotlib.__version__` => 3.1.1
`matplotlib.get_backend()` => TkAgg


This is what I run from the terminal as well and the plotting window didn't pop up.

What else do I need to provide?

**Comment by tacaswell** [comment]
Can you please run 

```python
import sys
print(sys.executable)
```

in the context that does not work?  From the tracback it looks like when you run from within the pycharm snap you have a cut-down python without tk installed.

**Comment by AvivSham** [comment]
I ran it and this is the output. 
`"/home/aviv/PycharmProjects/Forecast/venv/bin/python"`
Importing `tkinter` can be done without any errors (I have just checked it)

**Comment by jklymak** [comment]
```python
import matplotlib
matplotlib.use('tkagg')
import matplotlib.pyplot as plt
plt.plot([i for i in range(10)])
plt.show()
```

In `test.py` and then `python3 test.py` from the command line, or the window won't try to be shown.

**Comment by AvivSham** [comment]
I don't remember the setup but on my old computer the GUI pop up window appeared without using `plt.show()` command.  any suggestions on how to get back to that?

**Comment by jklymak** [comment]
Not clear what you are asking.  If the above worked then matplotlib is working as expected and we can close this and you can follow up with pycharm.  If it doesn’t work then please post the stacktrace.  If you had a different behaviour before, we will need more info on your previous setup.

**Comment by AvivSham** [comment]
Which info do you need about my previous setup?

**Comment by jklymak** [comment]
As far as I know plt.show is the only way to get a GUI window unless you are running an IDE with a run button or the web backend (ie jupyter).  But I think your original issue has been solved from our end so I’ll close this.   If you have a different issue please open a new issue with a full description
