### ISSUE TITLE
ax.text fails with positional argument error

### ISSUE THREAD

**Issue by sprajagopal** [matplotlib/matplotlib#15156]
### Bug report

**Bug summary**
Slider component uses ax.text which fails with position argument error.

**Code for reproduction**

```python
from mpl_toolkits import mplot3d
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.widgets import Slider
import matplotlib
import time
import sys
print(sys.version)
print(matplotlib.__version__)

# curve definition
def foo(a, b):
    # set parameters for curve
    x = 1.1
    y = 1.1
    f = 9.1
    k = 2.0
    # print range for convexity
    print(0, x * y/(x + y) - 1, f)
    time.sleep(1)
    return np.minimum(a*x,b*y) - a - b - f * np.maximum(a + b - k, 0)

# calculate x,y,z
x = np.linspace(-6, 6, 30)
y = np.linspace(-6, 6, 30)
X, Y = np.meshgrid(x, y)
Z = foo(X, Y)

# figure plot
fig = plt.figure()
ax = plt.axes(projection='3d')
l = ax.contour3D(X, Y, Z, 50, cmap='binary')
ax.set_xlabel('x')
ax.set_ylabel('y')
ax.set_zlabel('z')

# figure slider for interactive update
def update(val):
    global k
    k = valk.val
    l.set_zdata(foo(x,y))
    fig.canvas.draw_idle()

valk = Slider(ax, 'kparam', 0, 30.0, valinit=1.0)
valk.on_changed(update)


# invoke plot
plt.show()```
```
**Actual outcome**
```
3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0]
3.1.1
Traceback (most recent call last):
  File "plot.py", line 44, in <module>
    valk = Slider(ax, 'kparam', 0, 30.0, valinit=1.0)
  File "/home/prasanna/Documents/python/3dplots/local/lib/python3.6/site-packages/matplotlib/widgets.py", line 381, in __init__
    horizontalalignment='right')
TypeError: text() missing 1 required positional argument: 's'

```

**Expected outcome**
ax.text should not fail as per the API. There is no 's' keyword positional argument.

**Comment by tacaswell** [comment]
The issue is that you are trying to put the slider into a 3D axes where `ax.text(x, y, z, s)` is the expected signature.  A minimal example to reproduce this is

```
fig = plt.figure()
ax = plt.axes(projection='3d')
valk = Slider(ax, 'kparam', 0, 30.0, valinit=1.0)
```

I do not expect the `Sliders` to work correctly in non-linear non-2D projections, I think you want to make a second Axes to hold the slider.
