### ISSUE TITLE
Error at save animation with pillow

### ISSUE THREAD

**Issue by Zachary4biz** [matplotlib/matplotlib#15678]
### Bug report

**Bug summary**

line 575 of `animation.py` use `Image.frombytes` to load a `BytesIO`, this will lead to an exception -- `not enough image data`.  
seems we can't feed bytes of `.png` to `frombytes` from the first question-comment of [this SO question](https://stackoverflow.com/questions/32908639/open-pil-image-from-byte-file)

**Code for reproduction**

```python
import numpy as np
from matplotlib import animation
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

emb = np.random.random_sample((1000,3))

fig = plt.figure("bug_report")
ax = Axes3D(fig)
ax.set_xlabel('x')
ax.set_ylabel('y')
ax.set_zlabel('z')
ax.set_xlim3d(left=-1,right=1)
ax.set_ylim3d(bottom=-1,top=1)
ax.set_zlim3d(bottom=-1,top=1)

batch=50
def animate(i):
    emb_part = emb[i*batch:(i+1)*batch]
    ax.scatter(xs=emb_part[:, 0], ys=emb_part[:, 1], zs=emb_part[:, 2])
    return ax

ani = animation.FuncAnimation(fig=fig, func=animate, frames=len(emb)//batch + 1, interval=0.01*1000, blit=False, repeat=False)

ani.save("/Users/zac/Downloads/ani.gif", fps=30, writer='pillow')
```

**Actual outcome**

```
# ....
ValueError: not enough image data

During handling of the above exception, another exception occurred:
# ....
```
actually, if we use `plt.show()` before `ani.save`, this exception wont appear, but we will get only some last parts of the animation, [example as this](https://raw.githubusercontent.com/Zachary4biz/Tahiti_any_data/master/pics/err_ani.gif)

**Expected outcome**

normally saved gif pic
[example as this](https://raw.githubusercontent.com/Zachary4biz/Tahiti_any_data/master/pics/normal_ani.gif)

**Matplotlib version**

  * Operating system: MacOSX
  * Matplotlib version: 3.0.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.7.3
  * Jupyter version (if applicable):
  * Other libraries: numpy

**Comment by anntzer** [comment]
I cannot repro with either 3.0.3 or master, and in any case the frombytes call was removed in https://github.com/matplotlib/matplotlib/pull/14242.

**Comment by dopplershift** [comment]
It works if I don't specify the backend, but it fails for me if I do: `MPLBACKEND="Qt5Agg" python test_anim.py`:
```pytb
Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.
Traceback (most recent call last):
  File "/Users/rmay/miniconda3/envs/py37/lib/python3.7/site-packages/matplotlib/animation.py", line 230, in saving
    yield self
  File "/Users/rmay/miniconda3/envs/py37/lib/python3.7/site-packages/matplotlib/animation.py", line 1156, in save
    writer.grab_frame(**savefig_kwargs)
  File "/Users/rmay/miniconda3/envs/py37/lib/python3.7/site-packages/matplotlib/animation.py", line 572, in grab_frame
    buf.getvalue()))
  File "/Users/rmay/miniconda3/envs/py37/lib/python3.7/site-packages/PIL/Image.py", line 2542, in frombytes
    im.frombytes(data, decoder_name, args)
  File "/Users/rmay/miniconda3/envs/py37/lib/python3.7/site-packages/PIL/Image.py", line 829, in frombytes
    raise ValueError("not enough image data")
ValueError: not enough image data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_anim.py", line 25, in <module>
    ani.save("/Users/rmay/Downloads/ani.gif", fps=30, writer='pillow')
  File "/Users/rmay/miniconda3/envs/py37/lib/python3.7/site-packages/matplotlib/animation.py", line 1156, in save
    writer.grab_frame(**savefig_kwargs)
  File "/Users/rmay/miniconda3/envs/py37/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/rmay/miniconda3/envs/py37/lib/python3.7/site-packages/matplotlib/animation.py", line 232, in saving
    self.finish()
  File "/Users/rmay/miniconda3/envs/py37/lib/python3.7/site-packages/matplotlib/animation.py", line 575, in finish
    self._frames[0].save(
IndexError: list index out of range
Exception ignored in: <function TimerBase.__del__ at 0x11c218950>
Traceback (most recent call last):
  File "/Users/rmay/miniconda3/envs/py37/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 1100, in __del__
  File "/Users/rmay/miniconda3/envs/py37/lib/python3.7/site-packages/matplotlib/backends/backend_qt5.py", line 210, in _timer_stop
RuntimeError: Internal C++ object (PySide2.QtCore.QTimer) already deleted.
```

I should note that this is using PySide2.

**Comment by dopplershift** [comment]
On master with python 3.7.3 I get a slightly different error:
```pytb
Traceback (most recent call last):
  File "/Users/rmay/repos/matplotlib/lib/matplotlib/animation.py", line 230, in saving
    yield self
  File "/Users/rmay/repos/matplotlib/lib/matplotlib/animation.py", line 1148, in save
    writer.grab_frame(**savefig_kwargs)
  File "/Users/rmay/repos/matplotlib/lib/matplotlib/animation.py", line 567, in grab_frame
    "raw", "RGBA", 0, 1))
  File "/Users/rmay/miniconda3/envs/test-mpl/lib/python3.7/site-packages/PIL/Image.py", line 2605, in frombuffer
    im = im._new(core.map_buffer(data, size, decoder_name, None, 0, args))
ValueError: buffer is not large enough

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_anim.py", line 25, in <module>
    ani.save("/Users/rmay/Downloads/ani.gif", fps=30, writer='pillow')
  File "/Users/rmay/repos/matplotlib/lib/matplotlib/animation.py", line 1148, in save
    writer.grab_frame(**savefig_kwargs)
  File "/Users/rmay/miniconda3/envs/test-mpl/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/rmay/repos/matplotlib/lib/matplotlib/animation.py", line 232, in saving
    self.finish()
  File "/Users/rmay/repos/matplotlib/lib/matplotlib/animation.py", line 570, in finish
    self._frames[0].save(
IndexError: list index out of range
Exception ignored in: <function TimerBase.__del__ at 0x113a83d08>
Traceback (most recent call last):
  File "/Users/rmay/repos/matplotlib/lib/matplotlib/backend_bases.py", line 1094, in __del__
  File "/Users/rmay/repos/matplotlib/lib/matplotlib/backends/backend_qt5.py", line 213, in _timer_stop
RuntimeError: Internal C++ object (PySide2.QtCore.QTimer) already deleted.
```

**Comment by anntzer** [comment]
Still can't repro (pyside2+qt5agg+master), except the "Internal C++ object already deleted" error which I do repro but that doesn't affect the correct creation of the gif.

**Comment by dopplershift** [comment]
Oh fun, probably mac-specific.

**Comment by dopplershift** [comment]
I think it's a DPI scaling issue. If I print out the renderer height, width, and length of the image buffer (`BytesIO`), I get:

Without Qt5Agg:
```
640.0 480.0 1228800
```

With Qt5Agg:
```
1280.0 960.0 1228800
```

**Comment by Zachary4biz** [comment]
I see, maybe this is just some occasional error. 
**in matplotlib 3.1.3, it works fine for my case.**
thx!

**Comment by Zachary4biz** [comment]
btw, maybe you guys have some idea about generating [this kind of pic](https://raw.githubusercontent.com/Zachary4biz/Tahiti_any_data/master/pics/sunset_meitu.png)?

I was tackling some image-cluster-visualization stuff, and got stuck at controlling the position of `plt.imshow`

**Comment by dopplershift** [comment]
@anntzer Can you reproduce with this, even without specifying backend?
```python
import numpy as np
from matplotlib import animation
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

emb = np.random.random_sample((1000,3))

fig = plt.figure("bug_report")
ax = Axes3D(fig)
ax.set_xlabel('x')
ax.set_ylabel('y')
ax.set_zlabel('z')
ax.set_xlim3d(left=-1,right=1)
ax.set_ylim3d(bottom=-1,top=1)
ax.set_zlim3d(bottom=-1,top=1)

batch=50
def animate(i):
    emb_part = emb[i*batch:(i+1)*batch]
    ax.scatter(xs=emb_part[:, 0], ys=emb_part[:, 1], zs=emb_part[:, 2])
    return ax

ani = animation.FuncAnimation(fig=fig, func=animate, frames=len(emb)//batch + 1, interval=0.01*1000, blit=False, repeat=False)

ani.save("/Users/zac/Downloads/ani.gif", fps=30, writer='pillow', savefig_kwargs={'dpi':50})
```

I think there's a fundamental problem in the Pillow writer (and who knows where else) that assumes the number of pixels written in `savefig()` matches that found by querying `renderer` afterwards. Empirically, that's not the case--but I'm not sure what the right way to get that information is.

**Comment by dopplershift** [comment]
https://github.com/matplotlib/matplotlib/blob/fc413b3b60c875ddb7c4a19e3292ed31be163e26/lib/matplotlib/animation.py#L558-L568

**Comment by anntzer** [comment]
OK, I can repro by faking high-dpi with QT_SCALE_FACTOR; can you check whether #15691 fixes this?

**Comment by Svito-zar** [comment]
This issue is still there for me on Mac using Matplotlib v 3.3.4

**Comment by jklymak** [comment]
Please open a new issue

**Comment by Svito-zar** [comment]
I realized it was a bug in my code :)
