### ISSUE TITLE
Can't Import matplotlib.pyplot in ipython, spyder (also can't run anaconda-navigator or jupyter-notebook))

### ISSUE THREAD

**Issue by biocmann** [matplotlib/matplotlib#16026]
### Bug report

**Bug summary**

I recently installed anaconda and pycharm and am using the anaconda python env in my projects.  matplotlib.pyplot can't be imported and returns an error message.

**Code for reproduction**

```python
import matplotlib.pyplot as plt
```

**Actual outcome**

```
Traceback (most recent call last):
  File "/Users/marcoperezcaceres/opt/anaconda3/lib/python3.7/site-packages/matplotlib/font_manager.py", line 1353, in <module>
    fontManager = json_load(_fmcache)
  File "/Users/marcoperezcaceres/opt/anaconda3/lib/python3.7/site-packages/matplotlib/font_manager.py", line 924, in json_load
    with open(filename, 'r') as fh:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/marcoperezcaceres/.matplotlib/fontlist-v310.json'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/marcoperezcaceres/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-a0d2faabd9e9>", line 1, in <module>
    import matplotlib.pyplot as plt
  File "/Applications/PyCharm CE with Anaconda plugin.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/marcoperezcaceres/opt/anaconda3/lib/python3.7/site-packages/matplotlib/pyplot.py", line 32, in <module>
    import matplotlib.colorbar
  File "/Applications/PyCharm CE with Anaconda plugin.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/marcoperezcaceres/opt/anaconda3/lib/python3.7/site-packages/matplotlib/colorbar.py", line 31, in <module>
    import matplotlib.contour as contour
  File "/Applications/PyCharm CE with Anaconda plugin.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/marcoperezcaceres/opt/anaconda3/lib/python3.7/site-packages/matplotlib/contour.py", line 16, in <module>
    import matplotlib.font_manager as font_manager
  File "/Applications/PyCharm CE with Anaconda plugin.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/marcoperezcaceres/opt/anaconda3/lib/python3.7/site-packages/matplotlib/font_manager.py", line 1355, in <module>
    _rebuild()
  File "/Users/marcoperezcaceres/opt/anaconda3/lib/python3.7/site-packages/matplotlib/font_manager.py", line 1346, in _rebuild
    fontManager = FontManager()
  File "/Users/marcoperezcaceres/opt/anaconda3/lib/python3.7/site-packages/matplotlib/font_manager.py", line 1013, in __init__
    ttffiles = findSystemFonts(paths) + findSystemFonts()
  File "/Users/marcoperezcaceres/opt/anaconda3/lib/python3.7/site-packages/matplotlib/font_manager.py", line 311, in findSystemFonts
    fontfiles.update(get_fontconfig_fonts(fontext))
  File "/Users/marcoperezcaceres/opt/anaconda3/lib/python3.7/site-packages/matplotlib/font_manager.py", line 287, in get_fontconfig_fonts
    return [fname for fname in _call_fc_list()
  File "/Users/marcoperezcaceres/opt/anaconda3/lib/python3.7/site-packages/matplotlib/font_manager.py", line 275, in _call_fc_list
    out = subprocess.check_output(['fc-list', '--format=%{file}\\n'])
  File "/Users/marcoperezcaceres/opt/anaconda3/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/Users/marcoperezcaceres/opt/anaconda3/lib/python3.7/site-packages/run/__init__.py", line 145, in __new__
    process = cls.create_process(command, stdin, cwd=cwd, env=env, shell=shell)
  File "/Users/marcoperezcaceres/opt/anaconda3/lib/python3.7/site-packages/run/__init__.py", line 121, in create_process
    shlex.split(command),
  File "/Users/marcoperezcaceres/opt/anaconda3/lib/python3.7/shlex.py", line 305, in split
    return list(lex)
  File "/Users/marcoperezcaceres/opt/anaconda3/lib/python3.7/shlex.py", line 295, in __next__
    token = self.get_token()
  File "/Users/marcoperezcaceres/opt/anaconda3/lib/python3.7/shlex.py", line 105, in get_token
    raw = self.read_token()
  File "/Users/marcoperezcaceres/opt/anaconda3/lib/python3.7/shlex.py", line 136, in read_token
    nextchar = self.instream.read(1)
AttributeError: 'list' object has no attribute 'read'

```

**Expected outcome**
Expected the module to load normally

**Matplotlib version**

  * Operating system:
  * Matplotlib version: 
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version:
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by anntzer** [comment]
It looks like(?) you have https://github.com/xando/subprocess.run installed, which makes a mess of the stdlib subprocess and is thus incompatible with matplotlib.

**Comment by QuLogic** [comment]
Yes, see xando/subprocess.run#5. You should just uninstall that package; it doesn't provide anything that's not already in Python 3.7.
