### ISSUE TITLE
Unable to build from source on windows due to unspecified freetype issue

### ISSUE THREAD

**Issue by eric-wieser** [matplotlib/matplotlib#16241]
I'm trying to build from source so I can try out the latest features in master. However, when I do, I get the error:
```
    Building freetype in build\freetype-2.6.1
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\devenv.exe build\freetype-2.6.1\builds\windows\vc2010\freetype.sln /upgrade
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Common7\\IDE\\devenv.exe' failed with exit status 1
```
I can't seem to find any more details about why this command is failing - it pops open a GUI if I run it from a terminal, and presents an upgrade GUI.

<details>

<summary>Full  output:</summary>

```
PS C:\Users\wiese> py -3.8 -m pip install -e .\Repos\numeric-python\matplotlib --user -vv
Created temporary directory: C:\Users\wiese\AppData\Local\Temp\pip-ephem-wheel-cache-0jq_79r4
Created temporary directory: C:\Users\wiese\AppData\Local\Temp\pip-req-tracker-3udf9g4t
Created requirements tracker 'C:\\Users\\wiese\\AppData\\Local\\Temp\\pip-req-tracker-3udf9g4t'
Created temporary directory: C:\Users\wiese\AppData\Local\Temp\pip-install-cs5lcln7
Obtaining file:///C:/Users/wiese/Repos/numeric-python/matplotlib
  Added file:///C:/Users/wiese/Repos/numeric-python/matplotlib to build tracker 'C:\\Users\\wiese\\AppData\\Local\\Temp\\pip-req-tracker-3udf9g4t'
    Running setup.py (path:C:\Users\wiese\Repos\numeric-python\matplotlib\setup.py) egg_info for package from file:///C:/Users/wiese/Repos/numeric-python/matplotlib
    Running command python setup.py egg_info

    Edit setup.cfg to change the build options; suppress output with --quiet.

    BUILDING MATPLOTLIB
      matplotlib: yes [3.2.0rc2+1203.g081a6398e]
          python: yes [3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC
                      v.1916 64 bit (AMD64)]]
        platform: yes [win32]
     sample_data: yes [installing]
           tests: yes [installing]
           tkagg: yes [installing; run-time loading from Python Tcl/Tk]
          macosx: no  [Mac OS-X only]

    running egg_info
    writing lib\matplotlib.egg-info\PKG-INFO
    writing dependency_links to lib\matplotlib.egg-info\dependency_links.txt
    writing namespace_packages to lib\matplotlib.egg-info\namespace_packages.txt
    writing requirements to lib\matplotlib.egg-info\requires.txt
    writing top-level names to lib\matplotlib.egg-info\top_level.txt
    reading manifest file 'lib\matplotlib.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'lib\matplotlib.egg-info\SOURCES.txt'
  Source in c:\users\wiese\repos\numeric-python\matplotlib has version 3.2.0rc2+1203.g081a6398e, which satisfies requirement matplotlib==3.2.0rc2+1203.g081a6398e from file:///C:/Users/wiese/Repos/numeric-python/matplotlib
  Removed matplotlib==3.2.0rc2+1203.g081a6398e from file:///C:/Users/wiese/Repos/numeric-python/matplotlib from build tracker 'C:\\Users\\wiese\\AppData\\Local\\Temp\\pip-req-tracker-3udf9g4t'
Requirement already satisfied: cycler>=0.10 in c:\users\wiese\appdata\local\programs\python\python38\lib\site-packages (from matplotlib==3.2.0rc2+1203.g081a6398e) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\wiese\appdata\local\programs\python\python38\lib\site-packages (from matplotlib==3.2.0rc2+1203.g081a6398e) (1.1.0)
Requirement already satisfied: numpy>=1.15 in c:\users\wiese\appdata\local\programs\python\python38\lib\site-packages (from matplotlib==3.2.0rc2+1203.g081a6398e) (1.17.4)
Requirement already satisfied: pillow>=6.2.0 in c:\users\wiese\appdata\local\programs\python\python38\lib\site-packages (from matplotlib==3.2.0rc2+1203.g081a6398e) (7.0.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\users\wiese\appdata\local\programs\python\python38\lib\site-packages (from matplotlib==3.2.0rc2+1203.g081a6398e) (2.4.6)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\wiese\appdata\local\programs\python\python38\lib\site-packages (from matplotlib==3.2.0rc2+1203.g081a6398e) (2.8.1)
Requirement already satisfied: six in c:\users\wiese\appdata\local\programs\python\python38\lib\site-packages (from cycler>=0.10->matplotlib==3.2.0rc2+1203.g081a6398e) (1.13.0)
Requirement already satisfied: setuptools in c:\users\wiese\appdata\local\programs\python\python38\lib\site-packages (from kiwisolver>=1.0.1->matplotlib==3.2.0rc2+1203.g081a6398e) (41.2.0)
Installing collected packages: matplotlib
  Running setup.py develop for matplotlib
    Running command 'C:\Users\wiese\AppData\Local\Programs\Python\Python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\wiese\\Repos\\numeric-python\\matplotlib\\setup.py'"'"'; __file__='"'"'C:\\Users\\wiese\\Repos\\numeric-python\\matplotlib\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps --user --prefix=

    Edit setup.cfg to change the build options; suppress output with --quiet.

    BUILDING MATPLOTLIB
      matplotlib: yes [3.2.0rc2+1203.g081a6398e]
          python: yes [3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC
                      v.1916 64 bit (AMD64)]]
        platform: yes [win32]
     sample_data: yes [installing]
           tests: yes [installing]
           tkagg: yes [installing; run-time loading from Python Tcl/Tk]
          macosx: no  [Mac OS-X only]

    running develop
    running egg_info
    writing lib\matplotlib.egg-info\PKG-INFO
    writing dependency_links to lib\matplotlib.egg-info\dependency_links.txt
    writing namespace_packages to lib\matplotlib.egg-info\namespace_packages.txt
    writing requirements to lib\matplotlib.egg-info\requires.txt
    writing top-level names to lib\matplotlib.egg-info\top_level.txt
    reading manifest file 'lib\matplotlib.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'lib\matplotlib.egg-info\SOURCES.txt'
    running build_ext
    Building freetype in build\freetype-2.6.1
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\devenv.exe build\freetype-2.6.1\builds\windows\vc2010\freetype.sln /upgrade
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Common7\\IDE\\devenv.exe' failed with exit status 1
Cleaning up...
Removed build tracker 'C:\\Users\\wiese\\AppData\\Local\\Temp\\pip-req-tracker-3udf9g4t'
ERROR: Command errored out with exit status 1: 'C:\Users\wiese\AppData\Local\Programs\Python\Python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\wiese\\Repos\\numeric-python\\matplotlib\\setup.py'"'"'; __file__='"'"'C:\\Users\\wiese\\Repos\\numeric-python\\matplotlib\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps --user --prefix= Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "C:\Users\wiese\AppData\Local\Programs\Python\Python38\lib\site-packages\pip\_internal\cli\base_command.py", line 188, in main
    status = self.run(options, args)
  File "C:\Users\wiese\AppData\Local\Programs\Python\Python38\lib\site-packages\pip\_internal\commands\install.py", line 398, in run
    installed = install_given_reqs(
  File "C:\Users\wiese\AppData\Local\Programs\Python\Python38\lib\site-packages\pip\_internal\req\__init__.py", line 54, in install_given_reqs
    requirement.install(
  File "C:\Users\wiese\AppData\Local\Programs\Python\Python38\lib\site-packages\pip\_internal\req\req_install.py", line 917, in install
    self.install_editable(
  File "C:\Users\wiese\AppData\Local\Programs\Python\Python38\lib\site-packages\pip\_internal\req\req_install.py", line 768, in install_editable
    call_subprocess(
  File "C:\Users\wiese\AppData\Local\Programs\Python\Python38\lib\site-packages\pip\_internal\utils\misc.py", line 931, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: 'C:\Users\wiese\AppData\Local\Programs\Python\Python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\wiese\\Repos\\numeric-python\\matplotlib\\setup.py'"'"'; __file__='"'"'C:\\Users\\wiese\\Repos\\numeric-python\\matplotlib\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps --user --prefix= Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 19.3.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```

</details>

**Comment by eric-wieser** [comment]
Further debugging shows that `devenv` is interacting badly with python:

```python
# py -3.8 -m IPython
In [1]: import subprocess

In [2]: subprocess.check_call(['C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Common7\\IDE\\devenv.exe', 'build/freetype-2.6.1/builds/windows/vc2010/freetype.sln', "/upgrade"])
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
<ipython-input-3-643d8c6da4e7> in <module>
----> 1 subprocess.check_call([e, 'build/freetype-2.6.1/builds/windows/vc2010/freetype.sln', "/upgrade"])

~\AppData\Local\Programs\Python\Python38\lib\subprocess.py in check_call(*popenargs, **kwargs)
    362         if cmd is None:
    363             cmd = popenargs[0]
--> 364         raise CalledProcessError(retcode, cmd)
    365     return 0
    366

CalledProcessError: Command '['C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Common7\\IDE\\devenv.exe', 'build/freetype-2.6.1/builds/windows/vc2010/freetype.sln', '/upgrade']' returned non-zero exit status 1.
```

yet called directly from a shell causes no issues:

```
PS C:\Users\...\matplotlib> &"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\devenv.exe" build/freetype-2.6.1/builds/windows/vc2010/freetype.sln /upgrade
PS C:\Users\...\matplotlib> echo $?
True
```

**Comment by eric-wieser** [comment]
Replacing `devenv.exe` with `devenv.com` gave a useful error message:
```
Microsoft Visual Studio 2017 Version 15.0.27004.2009.
Copyright (C) Microsoft Corp. All rights reserved.

The license for Visual Studio has expired.

Your license for this product is expired and could not be refreshed. Please connect to the internet to continue to use this product.
```

**Comment by eric-wieser** [comment]
Starting the gui and re-entering my password was enough to solve this issue, will open a new one with the next error.
