### ISSUE TITLE
ValueError: zero-size array to reduction operation minimum which has no identity

### ISSUE THREAD

**Issue by Khalilsqu** [matplotlib/matplotlib#16284]
### Bug report

Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\matplotlib\backends\backend_qt5agg.py", line 58, in paintEvent
    memoryview(reg))
  File "C:\Program Files\Python37\lib\site-packages\matplotlib\cbook\__init__.py", line 2116, in _unmultiplied_rgba8888_to_premultiplied_argb32
    if alpha8.min() != 0xff:
  File "C:\Program Files\Python37\lib\site-packages\numpy\core\_methods.py", line 34, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial, where)
ValueError: zero-size array to reduction operation minimum which has no identity

I created some matplotlib images and impeded them in pyqt5 application. when scrolling up and down with the mouse my app crashes and I do not know which line of code causing the crash.

**Code for reproduction**

```python
# Paste your code here
#
#
```

**Actual outcome**

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

**Matplotlib version**

  * Operating system: Windows 10 64bit
  * Matplotlib version:  3.1.2
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version: '3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)]'
  * Jupyter version (if applicable): No jupyter or ipython
  * Other libraries: 
C:\Users\asalh>pip list
Package         Version
--------------- ---------
altgraph        0.17
cycler          0.10.0
future          0.18.2
kiwisolver      1.1.0
matplotlib      3.1.2
numpy           1.18.1
pandas          0.25.3
pefile          2019.4.18
pip             19.3.1
PyInstaller     3.6
pyparsing       2.4.6
PyQt5           5.14.1
PyQt5-sip       12.7.0
python-dateutil 2.8.1
pytz            2019.3
pywin32-ctypes  0.2.0
setuptools      41.2.0
six             1.14.0
xlrd            1.2.0
 pip

**Comment by Khalilsqu** [comment]
I noticed when installing python through anaconda the app never crashes and the traceback does not appear. However, the exe file generated by Pyinstaller is really huge compared with the installation of python from the official website and Matplotlib from PyPi through pip (50 MB pip, 800 Anaconda).

My imports are as follows:

```
from numpy import round
from pandas import Series, DataFrame, concat
from PyQt5.QtWidgets import (QWidget, QSizePolicy, QMessageBox)
from matplotlib.backends.backend_qt5agg import (FigureCanvasQTAgg as
                                                FigureCanvas)
from matplotlib.figure import Figure
from matplotlib.backends.backend_qt5agg import (NavigationToolbar2QT as
                                                NavigationToolbar)
import matplotlib.ticker as ticker
```

is there something I need to change in the imports to avoid the crash when using the offical python installation?

**Comment by tacaswell** [comment]
> when scrolling up and down with the mouse at the window where the images

Can you explain a bit more what you mean by this?  My guess is that somehow we are getting a figure rendered which is 0 in one or both of the dimensions and are not gracefully handling that.

Can you check the Qt and PyQt versions in both cases? That is probably the difference.

You should also look at using a conda env based on miniconda which will let you only install the packages you need rather than the full data science (and friends) stack.

**Comment by Khalilsqu** [comment]
I update tomorrow, it is 1 am here right now,

**Comment by Khalilsqu** [comment]
Here is a gif showing how the crash happens. sometimes it happens when just scrolling slightly up and down. while with anaconda or conda environment installation, it never happens.

![crash](https://user-images.githubusercontent.com/22060413/72898920-70535e80-3d3e-11ea-83da-a100d97532e1.gif)


I tried this [solution](https://stackoverflow.com/a/22903196/6814154) but it did not help. 

```
    try:
        ax.set_ylim([0, counts.max() + counts.max() * 0.1])
        ax1.set_ylim(ax.get_ylim())
        ax1.get_yaxis().set_visible(False)
    except ValueError:
        pass
```

conda list

```
altgraph                  0.16.1                     py_0
blas                      1.0                         mkl
ca-certificates           2019.11.27                    0
certifi                   2019.11.28               py37_0
cycler                    0.10.0                   py37_0
freetype                  2.9.1                ha9979f8_1
future                    0.18.2                   py37_0
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha66f8fd_1
intel-openmp              2019.4                      245
jpeg                      9b                   hb83a4c4_2
kiwisolver                1.1.0            py37ha925a31_0
libpng                    1.6.37               h2a8f88b_0
macholib                  1.11                       py_0
matplotlib                3.1.1            py37hc8f65d3_0
mkl                       2019.4                      245
mkl-service               2.3.0            py37hb782905_0
mkl_fft                   1.0.15           py37h14836fe_0
mkl_random                1.1.0            py37h675688f_0
numpy                     1.18.1           py37h93ca92e_0
numpy-base                1.18.1           py37hc3f5095_0
openssl                   1.1.1d               he774522_3
pandas                    0.25.3           py37ha925a31_0
pefile                    2019.4.18                  py_0
pip                       19.3.1                   py37_0
pycrypto                  2.6.1            py37hfa6e2cd_9
pyinstaller               3.5              py37h2a8f88b_0
pyparsing                 2.4.6                      py_0
pyqt                      5.9.2            py37h6538335_2
python                    3.7.6                h60c2a47_2
python-dateutil           2.8.1                      py_0
pytz                      2019.3                     py_0
pywin32                   227              py37he774522_1
pywin32-ctypes            0.2.0                    py37_0
qt                        5.9.7            vc14h73c81de_0
setuptools                44.0.0                   py37_0
sip                       4.19.8           py37h6538335_0
six                       1.13.0                   py37_0
sqlite                    3.30.1               he774522_0
tornado                   6.0.3            py37he774522_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_1
wheel                     0.33.6                   py37_0
wincertstore              0.2                      py37_0
xlrd                      1.2.0                    py37_0
zlib                      1.2.11               h62dcd97_3
```

Python installation from the official site

pip list
Package         Version
```
--------------- ---------
altgraph        0.17
cycler          0.10.0
future          0.18.2
kiwisolver      1.1.0
matplotlib      3.1.2
numpy           1.18.1
pandas          0.25.3
pefile          2019.4.18
pip             20.0.1
PyInstaller     3.6
pyparsing       2.4.6
PyQt5           5.14.1
PyQt5-sip       12.7.0
python-dateutil 2.8.1
pytz            2019.3
pywin32-ctypes  0.2.0
setuptools      41.2.0
six             1.14.0
xlrd            1.2.0
```

still, the size of the app generated by Pyinstaller is really huge when using conda virtual environment. mkl alone is about 120 MB

**Comment by jklymak** [comment]
The Qt and PyQt versions are different, so I'd suspect there is a problem there?

**Comment by Khalilsqu** [comment]
Okay I will try to make them the same. Thanks. by the way, I experience the crash when creating a conda environment but installing all dependencies using pip instead of conda

**Comment by Khalilsqu** [comment]
Okay, @jklymak  that was indeed the solution. the problem solved. Thank you so much. I posted the same question in SO and some expert in PyQt removed pyqt5 tag stating that your question has no relation to pyqt

**Comment by jklymak** [comment]
Well its hard to tell sometimes, but if it works in one version of PyQt and not the other, that tends to point to either pyqt being broken or matplotlib using pyqt in a way that changed.
