### ISSUE TITLE
Problem with eventplot - error message claims events & lineoffsets are unequal sizes

### ISSUE THREAD

**Issue by oscr104** [matplotlib/matplotlib#16546]
### Bug report

**Matplotlib.pyplot eventplot function is raising an error when i try to generate a raster plot. Given a sequence of event timings, and an equally sized sequence of lineoffsets, the error message  'ValueError: lineoffsets and positions are unequal sized sequences' is returned. Changing the dtype to np.array for both variables does not help.**

Reproducible with:

import matplotlib.pyplot as plt

events=[197, 2175, 4153]   # event timings for a single subject
lineoffsets = [1, 1, 1]
plt.eventplot(events, lineoffsets=lineoffsets)

**Actual outcome**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nd17878/anaconda3/lib/python3.7/site-packages/matplotlib/pyplot.py", line 2567, in eventplot
    else {}), **kwargs)
  File "/home/nd17878/anaconda3/lib/python3.7/site-packages/matplotlib/__init__.py", line 1589, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/home/nd17878/anaconda3/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 1376, in eventplot
    raise ValueError('lineoffsets and positions are unequal sized '
ValueError: lineoffsets and positions are unequal sized sequences
>>> lineoffsets = [1,3]
>>> plt.eventplot(events, lineoffsets=lineoffsets)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nd17878/anaconda3/lib/python3.7/site-packages/matplotlib/pyplot.py", line 2567, in eventplot
    else {}), **kwargs)
  File "/home/nd17878/anaconda3/lib/python3.7/site-packages/matplotlib/__init__.py", line 1589, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/home/nd17878/anaconda3/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 1376, in eventplot
    raise ValueError('lineoffsets and positions are unequal sized '
ValueError: lineoffsets and positions are unequal sized sequences

**Comment by ImportanceOfBeingErnest** [comment]
You can either create a single event series, like

```
events=[197, 2175, 4153]
lineoffsets = [1]
plt.eventplot(events, lineoffsets=lineoffsets)
```

or 3 series like
```
events=np.array([[197, 2175, 4153]]).T
lineoffsets = [1, 1, 1]
plt.eventplot(events, lineoffsets=lineoffsets)
```

but creating a single series with 3 offsets won't work. Possibly the documentation needs to be improved? Please feel free to make a suggestion.
