### ISSUE TITLE
BLD: ascii codec decode on 3.2.0 in non-UTF8 locales

### ISSUE THREAD

**Issue by tylerjereddy** [matplotlib/matplotlib#16670]
I've noticed in the SciPy Azure CI that the recent `3.2.0` release is having some install issues in a 32-bit Docker container with Python 3.6.

Invocation line:
`pip3 install setuptools wheel numpy cython==0.29.14 pybind11 pytest pytest-timeout pytest-xdist pytest-env pytest-cov Pillow mpmath matplotlib --user`

Traceback is below the fold:

<details>

```
2020-03-05T04:45:27.4491113Z Collecting matplotlib
2020-03-05T04:45:27.4532879Z   Downloading matplotlib-3.2.0.tar.gz (40.5 MB)
2020-03-05T04:45:31.2009727Z     ERROR: Command errored out with exit status 1:
2020-03-05T04:45:31.2011736Z      command: /usr/bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-9ku0am4u/matplotlib/setup.py'"'"'; __file__='"'"'/tmp/pip-install-9ku0am4u/matplotlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-9ku0am4u/matplotlib/pip-egg-info
2020-03-05T04:45:31.2012969Z          cwd: /tmp/pip-install-9ku0am4u/matplotlib/
2020-03-05T04:45:31.2013529Z     Complete output (20 lines):
2020-03-05T04:45:31.2013825Z     Traceback (most recent call last):
2020-03-05T04:45:31.2014131Z       File "<string>", line 1, in <module>
2020-03-05T04:45:31.2015115Z       File "/tmp/pip-install-9ku0am4u/matplotlib/setup.py", line 229, in <module>
2020-03-05T04:45:31.2015558Z         long_description = fd.read()
2020-03-05T04:45:31.2015957Z       File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
2020-03-05T04:45:31.2016366Z         return codecs.ascii_decode(input, self.errors)[0]
2020-03-05T04:45:31.2017125Z     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2619: ordinal not in range(128)
2020-03-05T04:45:31.2017575Z     
2020-03-05T04:45:31.2018675Z     Edit setup.cfg to change the build options; suppress output with --quiet.
2020-03-05T04:45:31.2019005Z     
2020-03-05T04:45:31.2019223Z     BUILDING MATPLOTLIB
2020-03-05T04:45:31.2019700Z       matplotlib: yes [3.2.0]
2020-03-05T04:45:31.2020246Z           python: yes [3.6.9 (default, Nov  7 2019, 10:44:02)  [GCC 8.3.0]]
2020-03-05T04:45:31.2020638Z         platform: yes [linux]
2020-03-05T04:45:31.2021203Z      sample_data: yes [installing]
2020-03-05T04:45:31.2021743Z            tests: no  [skipping due to configuration]
2020-03-05T04:45:31.2022100Z              agg: yes [installing]
2020-03-05T04:45:31.2022899Z            tkagg: yes [installing; run-time loading from Python Tcl/Tk]
2020-03-05T04:45:31.2023532Z           macosx: no  [Mac OS-X only]
2020-03-05T04:45:31.2024068Z     
2020-03-05T04:45:31.2024938Z     ----------------------------------------
2020-03-05T04:45:31.3508502Z ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
2020-03-05T04:45:31.9675862Z 
2020-03-05T04:45:31.9750941Z ##[error]Bash exited with code '1'.
2020-03-05T04:45:31.9781234Z ##[section]Finishing: Run 32-bit Ubuntu Docker Build / Tests
```

</details>

Two recent SciPy PR examples:

https://github.com/scipy/scipy/pull/11628
https://github.com/scipy/scipy/pull/11627

Any ideas?

**Comment by QuLogic** [comment]
The `README.rst` now includes non-ASCII `–`, and `setup.py` doesn't open the file as utf-8. A workaround would be to set a Unicode locale: `LANG=C.utf-8 pip install matplotlib`.

**Comment by QuLogic** [comment]
Can be reproduced by `LANG=C python3.6 setup.py egg_info`; note this doesn't affect 3.7+ because it coerces locale back to UTF-8.

**Comment by QuLogic** [comment]
Maybe could be fixed for the existing release if there were 32-bit wheels, too?

**Comment by tylerjereddy** [comment]
Thanks @QuLogic that's helpful info
