### ISSUE TITLE
Jupyter interactive display inside output order dependant

### ISSUE THREAD

**Issue by shaielc** [matplotlib/matplotlib#17576]
### Bug report

**Bug summary**

Plot not being displayed using notebook toolkit on the output widget depending on order of output.

**Code for reproduction**

cell 1:
```python
%matplotlib notebook
from matplotlib import pyplot as plt
import ipywidgets as wg
```

cell 2:
```python
test_out = wg.Output()
display(test_out)
with test_out:
    plt.figure()
    plt.plot([1,2,3])
```

cell 3:
```python
test_out = wg.Output()
with test_out:
    plt.figure()
    plt.plot([1,2,3])
display(test_out)

```
**Actual outcome**

![mpl_bug](https://user-images.githubusercontent.com/33698726/83866191-1de46e80-a730-11ea-8bf3-5d6bf3926b04.png)

**Expected outcome**

same output for cell 3  as cell 2:

![mpl_bug](https://user-images.githubusercontent.com/33698726/83866398-6bf97200-a730-11ea-859d-9d1e805c317b.png)

**Matplotlib version**

  * Operating system: win
  * Matplotlib version:  3.0.2
  * Matplotlib backend : nbAgg
  * Python version: Python 3.7.1
  * Jupyter version (if applicable): 5.7.4
  * Other libraries: ipywidgets 7.5.1

**Comment by tacaswell** [comment]
Can you try using https://github.com/matplotlib/ipympl instead?  It is a backend that uses the widget framework. 

nbAgg works by reaching into the front end and injecting a whole bunch of js.  My knee-jerk guess is that if you don't display the output first, the logic that sorts out what element of the DOM to inject into is broken (or concludes it is not visible and closes's its self).  Either way, by the time you show the output widget it is gone.

Also interestingly, running the broken cell breaks the mouse events on the shown figure.  If you get another figure on the screen the mouse over on all of the existing figures is fixed.

```
[IPKernelApp] ERROR | Exception in comm_msg for e85025d6413b4911a878e99fbcf66cb9
Traceback (most recent call last):
  File "/home/tcaswell/.virtualenvs/bleeding/lib/python3.10/site-packages/ipykernel/comm/manager.py", line 111, in comm_msg
    comm.handle_msg(msg)
  File "/home/tcaswell/.virtualenvs/bleeding/lib/python3.10/site-packages/ipykernel/comm/comm.py", line 161, in handle_msg
    self._msg_callback(msg)
  File "/home/tcaswell/source/p/matplotlib/lib/matplotlib/backends/backend_nbagg.py", line 219, in on_message
    self.manager.handle_json(message)
  File "/home/tcaswell/source/p/matplotlib/lib/matplotlib/backends/backend_webagg_core.py", line 452, in handle_json
    self.canvas.handle_event(content)
  File "/home/tcaswell/source/p/matplotlib/lib/matplotlib/backends/backend_webagg_core.py", line 236, in handle_event
    return handler(event)
  File "/home/tcaswell/source/p/matplotlib/lib/matplotlib/backends/backend_webagg_core.py", line 257, in _handle_mouse
    y = self.get_renderer().height - y
TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'
```

which is coming out of https://github.com/matplotlib/matplotlib/blob/879d1cfd5e8d90f645e243c7ff4628e9564cf81a/lib/matplotlib/backends/backend_webagg_core.py#L254-L257 which suggests that somehow there are bad messages going back to the kernel?

Attn @SylvainCorlay , something is going on here with the way output is captured that I don't understand.  That showing a new figure un-breaks the other figures is very strange to me...

**Comment by shaielc** [comment]
> Can you try using https://github.com/matplotlib/ipympl instead? It is a backend that uses the widget framework.

Just tried using the ipympl and I can verify that it works

**Comment by tacaswell** [comment]
I don't think this should be closed.  Using ipympl is a workaround, but nbagg is still broken.

**Comment by jklymak** [comment]
Oh sorry I didn't realize widgets were also supposed to work in nbagg

**Comment by QuLogic** [comment]
When the JavaScript eventually loads, it looks for the output cell in which to paste in the canvas:
https://github.com/matplotlib/matplotlib/blob/421d7b362123f00b9040311bca710f56da90d198/lib/matplotlib/backends/web_backend/js/nbagg_mpl.js#L217-L240
This likely is not going to work when capturing. I don't know what sort of alternate display options Jupyter might have to insert things like this.

As for the broken first figure, that's because the DPI ratio is stored on the `window.mpl` object, and since the second figure has not inserted a canvas, that gets set to `undefined`, breaking the positioning of events.
