### ISSUE TITLE
RuntimeError: Failed to process string with tex because latex could not be found  <Figure size 1800x1200 with 1 Axes>

### ISSUE THREAD

**Issue by hafez-ahmad** [matplotlib/matplotlib#17683]
### Bug report

**Bug summary**

**Code for reproduction**

```python
# Paste your code here
ax1=plt.subplot(2,1,1)
Traceback (most recent call last):

  File "C:\Users\hafez\anaconda3\lib\site-packages\matplotlib\texmanager.py", line 305, in _run_checked_subprocess
    stderr=subprocess.STDOUT)

  File "C:\Users\hafez\anaconda3\lib\subprocess.py", line 411, in check_output
    **kwargs).stdout

  File "C:\Users\hafez\anaconda3\lib\subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:

  File "C:\Users\hafez\anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 105, in __init__
    super(SubprocessPopen, self).__init__(*args, **kwargs)

  File "C:\Users\hafez\anaconda3\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)

  File "C:\Users\hafez\anaconda3\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)

FileNotFoundError: [WinError 2] The system cannot find the file specified


The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "C:\Users\hafez\anaconda3\lib\site-packages\IPython\core\formatters.py", line 341, in __call__
    return printer(obj)

  File "C:\Users\hafez\anaconda3\lib\site-packages\IPython\core\pylabtools.py", line 248, in <lambda>
    png_formatter.for_type(Figure, lambda fig: print_figure(fig, 'png', **kwargs))

  File "C:\Users\hafez\anaconda3\lib\site-packages\IPython\core\pylabtools.py", line 132, in print_figure
    fig.canvas.print_figure(bytes_io, **kw)

  File "C:\Users\hafez\anaconda3\lib\site-packages\matplotlib\backend_bases.py", line 2079, in print_figure
    self.figure.draw(renderer)

  File "C:\Users\hafez\anaconda3\lib\site-packages\matplotlib\artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)

  File "C:\Users\hafez\anaconda3\lib\site-packages\matplotlib\figure.py", line 1736, in draw
    renderer, self, artists, self.suppressComposite)

  File "C:\Users\hafez\anaconda3\lib\site-packages\matplotlib\image.py", line 137, in _draw_list_compositing_images
    a.draw(renderer)

  File "C:\Users\hafez\anaconda3\lib\site-packages\matplotlib\artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)

  File "C:\Users\hafez\anaconda3\lib\site-packages\matplotlib\axes\_base.py", line 2630, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)

  File "C:\Users\hafez\anaconda3\lib\site-packages\matplotlib\image.py", line 137, in _draw_list_compositing_images
    a.draw(renderer)

  File "C:\Users\hafez\anaconda3\lib\site-packages\matplotlib\artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)

  File "C:\Users\hafez\anaconda3\lib\site-packages\matplotlib\axis.py", line 1229, in draw
    renderer)

  File "C:\Users\hafez\anaconda3\lib\site-packages\matplotlib\axis.py", line 1174, in _get_tick_bboxes
    for tick in ticks if tick.label1.get_visible()],

  File "C:\Users\hafez\anaconda3\lib\site-packages\matplotlib\axis.py", line 1174, in <listcomp>
    for tick in ticks if tick.label1.get_visible()],

  File "C:\Users\hafez\anaconda3\lib\site-packages\matplotlib\text.py", line 905, in get_window_extent
    bbox, info, descent = self._get_layout(self._renderer)

  File "C:\Users\hafez\anaconda3\lib\site-packages\matplotlib\text.py", line 293, in _get_layout
    ismath="TeX" if self.get_usetex() else False)

  File "C:\Users\hafez\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py", line 204, in get_text_width_height_descent
    s, fontsize, renderer=self)

  File "C:\Users\hafez\anaconda3\lib\site-packages\matplotlib\texmanager.py", line 450, in get_text_width_height_descent
    dvifile = self.make_dvi(tex, fontsize)

  File "C:\Users\hafez\anaconda3\lib\site-packages\matplotlib\texmanager.py", line 339, in make_dvi
    texfile], tex)

  File "C:\Users\hafez\anaconda3\lib\site-packages\matplotlib\texmanager.py", line 309, in _run_checked_subprocess
    'found'.format(command[0])) from exc

RuntimeError: Failed to process string with tex because latex could not be found

<Figure size 1800x1200 with 1 Axes>
#
```

**Actual outcome**

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

**Matplotlib version**

  * Operating system:
  * Matplotlib version: 
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version:
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by jklymak** [comment]
You need to either install latex or set usetex to false. I’m going to close as I don’t think there is a bug here or if there is then there is not enough info to go by.  OTOH feel free to comment if you still can’t figure this out.
