### ISSUE TITLE
Cannot run Matplotlib 3.2.2 on Python 3.8.1

### ISSUE THREAD

**Issue by zosob** [matplotlib/matplotlib#17695]
I installed matplotlib on my environment, but it doesn't work with python3. It DOES work with python2 though, which is odd. 

### Bug report

**Bug summary**

**Code for reproduction**

```python
import matplotlib
#All dependednceis have been installed
```

**Actual outcome**

```
>>> import matplotlib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Bhaskar/opt/anaconda3/envs/Vision/lib/python3.8/site-packages/matplotlib/__init__.py", line 124, in <module>
    import inspect
  File "/Users/Bhaskar/opt/anaconda3/envs/Vision/lib/python3.8/inspect.py", line 40, in <module>
    import linecache
  File "/Users/Bhaskar/opt/anaconda3/envs/Vision/lib/python3.8/linecache.py", line 11, in <module>
    import tokenize
  File "/Users/Bhaskar/opt/anaconda3/envs/Vision/lib/python3.8/tokenize.py", line 34, in <module>
    from token import *
  File "/Users/Bhaskar/token.py", line 1, in <module>
    from nltk.tokenize import sent_tokenize, word_tokenize
  File "/Users/Bhaskar/opt/anaconda3/envs/Vision/lib/python3.8/site-packages/nltk/__init__.py", line 129, in <module>
    from nltk.decorators import decorator, memoize
  File "/Users/Bhaskar/opt/anaconda3/envs/Vision/lib/python3.8/site-packages/nltk/decorators.py", line 221, in <module>
    def memoize(func, *args):
  File "/Users/Bhaskar/opt/anaconda3/envs/Vision/lib/python3.8/site-packages/nltk/decorators.py", line 193, in decorator
    if inspect.isclass(caller):
AttributeError: partially initialized module 'inspect' has no attribute 'isclass' (most likely due to a circular import)
#
```

**Expected outcome**

**Matplotlib version**

  * Operating system: MacOS 10.15.5
  * Matplotlib version: 3.2.2
  * Matplotlib backend (`print(matplotlib.get_backend())`):MacOSX
  * Python version:3.8.1
  * Jupyter version (if applicable):
  * Other libraries: 

I used conda install -c conda-forge matplotlib to install it.

**Comment by jklymak** [comment]
Try uninstall  nltk?

**Comment by QuLogic** [comment]
The file `/Users/Bhaskar/token.py` is shadowing the file with the same name from the standard library. Delete or rename it so it doesn't do that.

**Comment by zosob** [comment]
Thank you! :) Worked like a charm!
