### ISSUE TITLE
PGF xelatex can't find fonts in special-character paths

### ISSUE THREAD

**Issue by QuLogic** [matplotlib/matplotlib#17765]
### Bug report

**Bug summary**

On Fedora, the latest guidelines put `~` in the version for release candidates. This translates to everything being in a directory with `~` in the name. This breaks the PGF tests using xelatex, but also can be reproduced by placing custom fonts in a similar path.

**Code for reproduction**

I used Josefin Slab from Google Fonts, as I didn't have it installed already, so I knew if it'd be working. I then placed those in a `foo~bar` directory, and ran the following.

```python
import os

import matplotlib.pyplot as plt
import matplotlib.font_manager

matplotlib.font_manager.fontManager.addfont(
    os.path.abspath('foo~bar/JosefinSlab-Regular.ttf'))
plt.rcParams['font.sans-serif'] = ['Josefin Slab']
plt.rcParams['pgf.texsystem'] = 'xelatex'

fig, ax = plt.subplots()
fig.savefig('test.pdf', backend='pgf')
```

**Actual outcome**

```
kpathsea:make_tex: Invalid filename `[/home/elliott/code/matplotlib/foo', contains '['
Traceback (most recent call last):
  File "../mpl-tests/pgf-font-fail.py", line 12, in <module>
    fig.savefig('test.pdf', backend='pgf')
  File "/home/elliott/code/matplotlib/lib/matplotlib/figure.py", line 2309, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/elliott/code/matplotlib/lib/matplotlib/backends/backend_qt5agg.py", line 81, in print_figure
    super().print_figure(*args, **kwargs)
  File "/home/elliott/code/matplotlib/lib/matplotlib/backend_bases.py", line 2217, in print_figure
    **kwargs)
  File "/home/elliott/code/matplotlib/lib/matplotlib/backends/backend_pgf.py", line 940, in print_pdf
    self._print_pdf_to_fh(file, *args, **kwargs)
  File "/home/elliott/code/matplotlib/lib/matplotlib/backends/backend_pgf.py", line 901, in _print_pdf_to_fh
    self.print_pgf(fname_pgf, *args, **kwargs)
  File "/home/elliott/code/matplotlib/lib/matplotlib/backends/backend_pgf.py", line 884, in print_pgf
    self._print_pgf_to_fh(file, *args, **kwargs)
  File "/home/elliott/code/matplotlib/lib/matplotlib/backend_bases.py", line 1639, in wrapper
    return func(*args, **kwargs)
  File "/home/elliott/code/matplotlib/lib/matplotlib/cbook/deprecation.py", line 410, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/home/elliott/code/matplotlib/lib/matplotlib/backends/backend_pgf.py", line 864, in _print_pgf_to_fh
    RendererPgf(self.figure, fh),
  File "/home/elliott/code/matplotlib/lib/matplotlib/cbook/deprecation.py", line 410, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/home/elliott/code/matplotlib/lib/matplotlib/backends/backend_pgf.py", line 429, in __init__
    self._latexManager = LatexManager._get_cached_or_new()  # deprecated
  File "/home/elliott/code/matplotlib/lib/matplotlib/backends/backend_pgf.py", line 241, in _get_cached_or_new
    return cls._get_cached_or_new_impl(cls._build_latex_header())
  File "/home/elliott/code/matplotlib/lib/matplotlib/backends/backend_pgf.py", line 246, in _get_cached_or_new_impl
    return cls()
  File "/home/elliott/code/matplotlib/lib/matplotlib/backends/backend_pgf.py", line 308, in __init__
    "or error in preamble:\n%s" % stdout)
matplotlib.backends.backend_pgf.LatexError: LaTeX returned an error, probably missing font or error in preamble:
This is XeTeX, Version 3.14159265-2.6-0.999991 (TeX Live 2019) (preloaded format=xelatex)
 restricted \write18 enabled.
**entering extended mode
LaTeX2e <2018-12-01>

*
*(/usr/share/texlive/texmf-dist/tex/latex/base/minimal.cls
Document Class: minimal 2001/05/25 Standard LaTeX minimal class
)
*(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphicx.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty)
(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphics.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics/trig.sty)
(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/graphics.cfg)
(/usr/share/texlive/texmf-dist/tex/latex/graphics-def/xetex.def)))
(Please type a command or say `\end')
*
*(/usr/share/texlive/texmf-dist/tex/latex/fontspec/fontspec.sty
(/usr/share/texlive/texmf-dist/tex/latex/l3packages/xparse/xparse.sty
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/expl3.sty
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/expl3-code.tex)
(/usr/share/texlive/texmf-dist/tex/latex/l3backend/l3backend-xdvipdfmx.def)))
(/usr/share/texlive/texmf-dist/tex/latex/fontspec/fontspec-xetex.sty
(/usr/share/texlive/texmf-dist/tex/latex/base/fontenc.sty
(/usr/share/texlive/texmf-dist/tex/latex/base/tuenc.def))
(/usr/share/texlive/texmf-dist/tex/latex/fontspec/fontspec.cfg)))
*
! LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
<*> ...ath=/home/elliott/code/matplotlib/foo~bar/]
                                                  
No pages of output.
Transcript written on texput.log.
```

**Expected outcome**

PDF is produced, like it is in 3.2.2, using Josefin Slab font.

**Matplotlib version**
  * Operating system: Fedora 31
  * Matplotlib version: 4a143b9a77390fda6ae29de0fd97bfeca54cd7f7
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.6.10

**Comment by QuLogic** [comment]
Huh, so bisect says this came from 154a3126344d36cdab77d96d48b5a7447722c745, i.e., adding the `backend` parameter to `savefig`. Obviously that's not right, so adding `mpl.use('pgf')` does use the right backend in 3.2.2, and shows it never worked there either.

**Comment by QuLogic** [comment]
Also fails in 3.1.x; I guess the test is just new?

For the Fedora package, this would only affect the release candidates, so I can work around that easily.

**Comment by anntzer** [comment]
I doubt this ever worked.  Looks like
```
diff --git i/lib/matplotlib/backends/backend_pgf.py w/lib/matplotlib/backends/backend_pgf.py
index 8da4abca6..7e112e136 100644
--- i/lib/matplotlib/backends/backend_pgf.py
+++ w/lib/matplotlib/backends/backend_pgf.py
@@ -50,7 +50,7 @@ def get_fontspec():
             # 1) Forward slashes also work on Windows, so don't mess with
             # backslashes.  2) The dirname needs to include a separator.
             path = pathlib.Path(fm.findfont(family))
-            latex_fontspec.append(r"\%s{%s}[Path=%s]" % (
+            latex_fontspec.append(r"\%s{%s}[Path=\detokenize{%s}]" % (
                 command, path.name, path.parent.as_posix() + "/"))
 
     return "\n".join(latex_fontspec)
```
will get you through at least some more special TeX characters (in particular ~) (see https://www.overleaf.com/learn/latex/Articles/An_Introduction_to_LuaTeX_(Part_2):_Understanding_%5Cdirectlua#Other_commands.2Ftechniques_used_in_expansion) but this still breaks if your path contains backslashes or braces.

**Comment by QuLogic** [comment]
Indeed that does fix it. Would calling `_replace_escapetext` on the path fix the other special characters?

**Comment by anntzer** [comment]
Perhaps? I'll let you try it :)

**Comment by QuLogic** [comment]
For me, this is only really important for RCs, and since we aren't doing another one, we can bump this to 3.4.
