### ISSUE TITLE
TypeError: alpha must be a float or None

### ISSUE THREAD

**Issue by joaquim7** [matplotlib/matplotlib#17805]
### Bug report
TypeError: alpha must be a float or None
**Bug summary**
Noting is plotted and the above error message is displayed

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt
import scaleogram as scg 
import pywt

scg.set_default_wavelet('cmor1-1.5')

ns   = 1024
time = np.arange(ns)

# and a range of scales to perform the transform
scales = scg.periods2scales( np.arange(1, 40) )

# and a periodic signal with varying amplitude
p1=10; periodic1 = np.cos(2*np.pi/p1*time) * np.exp(-((time-ns/2)/200)**2)

# plot the signal
fig1, ax1 = plt.subplots(1, 1, figsize=(6.2,2));
lines = ax1.plot(periodic1);
ax1.set_xlim(0, len(time))
ax1.set_title("cos wave with gaussian envelope")
fig1.tight_layout()

# and the scaleogram
ax2 = scg.cws(periodic1, scales=scales, figsize=(6.9,2.3));
txt = ax2.annotate("p1=10s", xy=(100, 10), bbox=dict(boxstyle="round4", fc="w"))
plt.tight_layout()

print("Default wavelet function used to compute the transform:", scg.get_default_wavelet(), "(",
      pywt.ContinuousWavelet(scg.get_default_wavelet()).family_name, ")")
plt.show()
```

**Actual outcome**

```pytb
Traceback (most recent call last):
  File "wavelet3.py", line 33, in <module>
    ax2 = scg.cws(periodic1, scales=scales, figsize=(6.9,2.3));
  File "/media/joaquim/audio/anaconda3/envs/envssl/lib/python3.8/site-packages/scaleogram/cws.py", line 264, in cws
    ax.fill_between(xmesh, yborder, ymask, **coikw )
  File "/media/joaquim/audio/anaconda3/envs/envssl/lib/python3.8/site-packages/matplotlib/__init__.py", line 1565, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/media/joaquim/audio/anaconda3/envs/envssl/lib/python3.8/site-packages/matplotlib/axes/_axes.py", line 5229, in fill_between
    collection = mcoll.PolyCollection(polys, **kwargs)
  File "/media/joaquim/audio/anaconda3/envs/envssl/lib/python3.8/site-packages/matplotlib/collections.py", line 1072, in __init__
    Collection.__init__(self, **kwargs)
  File "/media/joaquim/audio/anaconda3/envs/envssl/lib/python3.8/site-packages/matplotlib/collections.py", line 164, in __init__
    self.update(kwargs)
  File "/media/joaquim/audio/anaconda3/envs/envssl/lib/python3.8/site-packages/matplotlib/artist.py", line 1006, in update
    ret = [_update_property(self, k, v) for k, v in props.items()]
  File "/media/joaquim/audio/anaconda3/envs/envssl/lib/python3.8/site-packages/matplotlib/artist.py", line 1006, in <listcomp>
    ret = [_update_property(self, k, v) for k, v in props.items()]
  File "/media/joaquim/audio/anaconda3/envs/envssl/lib/python3.8/site-packages/matplotlib/artist.py", line 1003, in _update_property
    return func(v)
  File "/media/joaquim/audio/anaconda3/envs/envssl/lib/python3.8/site-packages/matplotlib/collections.py", line 771, in set_alpha
    super().set_alpha(alpha)
  File "/media/joaquim/audio/anaconda3/envs/envssl/lib/python3.8/site-packages/matplotlib/artist.py", line 932, in set_alpha
    raise TypeError('alpha must be a float or None')
TypeError: alpha must be a float or None
```

**Expected outcome**
scalogram of the signal is plotted 

Not applicable

**Matplotlib version**

  * Operating system:Ubuntu 18.04 LTS
  * Matplotlib version: 3.2.2
  * Matplotlib backend (`print(matplotlib.get_backend())`):TkAgg

  * Python version:3.8.3
  * Jupyter version (if applicable):
  * Other libraries: 
```
_libgcc_mutex             0.1                        main  
absl-py                   0.9.0                    pypi_0    pypi
asciitree                 0.3.3                    pypi_0    pypi
attrs                     19.3.0                   pypi_0    pypi
audioread                 2.1.8                    pypi_0    pypi
blas                      1.0                         mkl  
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2020.6.24                     0  
cachetools                4.1.0                    pypi_0    pypi
certifi                   2020.6.20                py38_0  
cffi                      1.14.0                   pypi_0    pypi
chardet                   3.0.4                    pypi_0    pypi
cycler                    0.10.0                   pypi_0    pypi
dbus                      1.13.16              hb2f20db_0  
decorator                 4.4.2                    pypi_0    pypi
expat                     2.2.9                he6710b0_2  
fasteners                 0.15                     pypi_0    pypi
ffmpeg                    4.2.2                h20bf706_0  
ffmpy                     0.2.3                    pypi_0    pypi
fontconfig                2.13.0               h9420a91_0  
freetype                  2.10.2               h5ab3b9f_0  
future                    0.18.2                   pypi_0    pypi
glib                      2.65.0               h3eb4bd4_0  
gmp                       6.1.2                h6c8ec71_1  
gnutls                    3.6.5             h71b1129_1002  
google-auth               1.16.0                   pypi_0    pypi
google-auth-oauthlib      0.4.1                    pypi_0    pypi
gpytorch                  1.1.1                    pypi_0    pypi
grpcio                    1.29.0                   pypi_0    pypi
gst-plugins-base          1.14.0               hbbd80ab_1  
gstreamer                 1.14.0               hb31296c_0  
icu                       58.2                 he6710b0_3  
idna                      2.9                      pypi_0    pypi
importlib-metadata        1.6.0                    pypi_0    pypi
intel-openmp              2020.1                      217  
jams                      0.3.4                    pypi_0    pypi
joblib                    0.15.1                   pypi_0    pypi
jpeg                      9b                   h024ee3a_2  
jsonschema                3.2.0                    pypi_0    pypi
kiwisolver                1.2.0            py38hfd86e86_0  
lame                      3.100                h7b6447c_0  
ld_impl_linux-64          2.33.1               h53a641e_7  
libedit                   3.1.20191231         h7b6447c_0  
libffi                    3.3                  he6710b0_1  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libllvm9                  9.0.1                h4a3c616_0  
libopus                   1.3.1                h7b6447c_0  
libpng                    1.6.37               hbc83047_0  
librosa                   0.7.2                    pypi_0    pypi
libstdcxx-ng              9.1.0                hdf63c60_0  
libuuid                   1.0.3                h1bed415_2  
libvpx                    1.7.0                h439df22_0  
libxcb                    1.13                 h1bed415_1  
libxml2                   2.9.10               he19cac6_1  
llvmlite                  0.32.1                   pypi_0    pypi
mad                       0.15.1b              he1b5a44_0    conda-forge
markdown                  3.2.2                    pypi_0    pypi
matplotlib                0+unknown                pypi_0    pypi
matplotlib-base           3.2.2            py38hef1b27d_0  
mir-eval                  0.6                      pypi_0    pypi
mkl                       2020.1                      217  
mkl-service               2.3.0            py38he904b0f_0  
mkl_fft                   1.1.0            py38h23d657b_0  
mkl_random                1.1.1            py38h0573a6f_0  
monotonic                 1.5                      pypi_0    pypi
musdb                     0.3.1                    pypi_0    pypi
museval                   0.3.0                    pypi_0    pypi
ncurses                   6.2                  he6710b0_1  
nettle                    3.4.1                hbb512f6_0  
norbert                   0.2.1                    pypi_0    pypi
numba                     0.50.1           py38h0573a6f_0  
numcodecs                 0.6.2                    pypi_0    pypi
numpy                     1.18.5           py38ha1c710e_0  
numpy-base                1.18.5           py38hde5b4d6_0  
nussl                     1.1.0                    pypi_0    pypi
oauthlib                  3.1.0                    pypi_0    pypi
openh264                  2.1.0                hd408876_0  
openssl                   1.1.1g               h7b6447c_0  
pandas                    1.0.4                    pypi_0    pypi
pcre                      8.44                 he6710b0_0  
pillow                    7.1.2                    pypi_0    pypi
pip                       20.1.1                   py38_1  
protobuf                  3.12.2                   pypi_0    pypi
pyaml                     20.4.0                   pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycparser                 2.20                     pypi_0    pypi
pyparsing                 2.4.7                      py_0  
pyqt                      5.9.2            py38h05f1152_4  
pyrsistent                0.16.0                   pypi_0    pypi
python                    3.8.3                hcff3b4d_0  
python-dateutil           2.8.1                      py_0  
pytorch-ignite            0.3.0                    pypi_0    pypi
pytz                      2020.1                     py_0  
pywavelets                1.1.1            py38h7b6447c_0  
pyyaml                    5.3.1                    pypi_0    pypi
qt                        5.9.7                h5867ecd_1  
readline                  8.0                  h7b6447c_0  
requests                  2.23.0                   pypi_0    pypi
requests-oauthlib         1.3.0                    pypi_0    pypi
resampy                   0.2.2                    pypi_0    pypi
rsa                       4.0                      pypi_0    pypi
scaleogram                0.9.5                    pypi_0    pypi
scikit-learn              0.23.1                   pypi_0    pypi
scipy                     1.5.0            py38h0b6359f_0  
seaborn                   0.10.1                     py_0  
setuptools                47.3.1                   py38_0  
simplejson                3.17.0                   pypi_0    pypi
sip                       4.19.13          py38he6710b0_0  
six                       1.15.0                     py_0  
sortedcontainers          2.1.0                    pypi_0    pypi
soundfile                 0.10.3.post1             pypi_0    pypi
sox                       14.4.2            h27f72bc_1013    conda-forge
sqlite                    3.32.3               h62c20be_0  
stempeg                   0.1.8                    pypi_0    pypi
tbb                       2020.0               hfd86e86_0  
tensorboard               2.2.2                    pypi_0    pypi
tensorboard-plugin-wit    1.6.0.post3              pypi_0    pypi
termtables                0.2.1                    pypi_0    pypi
threadpoolctl             2.1.0                    pypi_0    pypi
tk                        8.6.10               hbc83047_0  
torch                     1.5.0                    pypi_0    pypi
tornado                   6.0.4            py38h7b6447c_1  
tqdm                      4.46.0                   pypi_0    pypi
urllib3                   1.25.9                   pypi_0    pypi
werkzeug                  1.0.1                    pypi_0    pypi
wheel                     0.34.2                   py38_0  
x264                      1!157.20191217       h7b6447c_0  
xz                        5.2.5                h7b6447c_0  
zarr                      2.3.0                    pypi_0    pypi
zipp                      3.1.0                    pypi_0    pypi
zlib                      1.2.11               h7b6447c_3 
```

default channel

**Comment by jklymak** [comment]
This error is coming from `scaleogram`.  Can you either reproduce what they are doing, or submit the issue to that project?

**Comment by joaquim7** [comment]
The same code runs in this kaggle notebook
https://www.kaggle.com/asauve/a-gentle-introduction-to-wavelet-for-data-analysis/notebook

**Comment by dstansby** [comment]
Yes, it looks like this is an error in the https://github.com/alsauve/scaleogram package - could you open an issue there? If you still think it's a maplotlib issue feel free to re-open this or comment.

**Comment by kinokoberuji** [comment]
Correcting this error is easy, we can access to the cws.py in the package, and find this dictionary  : `COI_DEFAULTS = {
        'alpha': '0.5',
        'hatch':'/',
}` , then change '0.5' to 0.5, now the problem is resolved

**Comment by mfarhansohail** [comment]
Incase you are on a cloud environment and cant have access to the python file just add one more input to the scg.cws function called coikw with the value as given 

COI_DEFAULTS = {'alpha':0.5,'hatch':'/',}

scg.cws(periodic1, scales=scales, figsize=(6.9,2.3), coikw=COI_DEFAULTS)
