### ISSUE TITLE
Cannot savefig to stdout: TypeError: write() argument must be str, not bytes

### ISSUE THREAD

**Issue by iljah** [matplotlib/matplotlib#18049]
As far as I can tell from documentation (matplotlib.org/3.2.2/api/_as_gen/matplotlib.pyplot.savefig.html), following should work:
```
#! /usr/bin/env python3
from sys import stdout
import matplotlib.pyplot as plot
plot.savefig(stdout, format = 'png')
```
but produces:
```
Traceback (most recent call last):
  File "./bug.py", line 4, in <module>
    plot.savefig(stdout, format = 'png')
  File "/usr/lib64/python3.8/site-packages/matplotlib/pyplot.py", line 723, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/usr/lib64/python3.8/site-packages/matplotlib/figure.py", line 2203, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/usr/lib64/python3.8/site-packages/matplotlib/backend_bases.py", line 2119, in print_figure
    result = print_method(
  File "/usr/lib64/python3.8/site-packages/matplotlib/backends/backend_agg.py", line 536, in print_png
    _png.write_png(renderer._renderer, fh, self.figure.dpi,
TypeError: write() argument must be str, not bytes
```
I'm using /usr/lib64/python3.8/site-packages/matplotlib-3.2.2-py3.8.egg-info from fedora 32. Same thing with at least format=pdf.

**Comment by iljah** [comment]
format=eps works

**Comment by iljah** [comment]
format=svg works

**Comment by QuLogic** [comment]
PNG is a binary format; `sys.stdout` is a textual interface. Use `sys.stdout.buffer` instead. https://docs.python.org/3/library/sys.html#sys.stdout

**Comment by iljah** [comment]
Thanks, matplotlib documentation could probably use a note about this...
