### ISSUE TITLE
AttributeError: module 'matplotlib' has no attribute 'projections'

### ISSUE THREAD

**Issue by mydlgit** [matplotlib/matplotlib#18074]
Traceback (most recent call last):
  File "/home/hsy/wh/license_plate/datasets/ccpd.py", line 6, in <module>
    import pycocotools.coco as coco
  File "/home/hsy/.local/lib/python3.6/site-packages/pycocotools-2.0-py3.6-linux-x86_64.egg/pycocotools/coco.py", line 49, in <module>
    import matplotlib.pyplot as plt
  File "/home/hsy/.local/lib/python3.6/site-packages/matplotlib-3.3.0-py3.6-linux-x86_64.egg/matplotlib/pyplot.py", line 43, in <module>
    from matplotlib.figure import Figure, figaspect
  File "/home/hsy/.local/lib/python3.6/site-packages/matplotlib-3.3.0-py3.6-linux-x86_64.egg/matplotlib/figure.py", line 18, in <module>
    from matplotlib import docstring, projections
  File "/home/hsy/.local/lib/python3.6/site-packages/matplotlib-3.3.0-py3.6-linux-x86_64.egg/matplotlib/projections/__init__.py", line 4, in <module>
    from mpl_toolkits.mplot3d import Axes3D
  File "/home/hsy/anaconda3/envs/tf15_gpu/lib/python3.6/site-packages/mpl_toolkits/mplot3d/__init__.py", line 1, in <module>
    from .axes3d import Axes3D
  File "/home/hsy/anaconda3/envs/tf15_gpu/lib/python3.6/site-packages/mpl_toolkits/mplot3d/axes3d.py", line 24, in <module>
    import matplotlib.projections as proj
**AttributeError: module 'matplotlib' has no attribute 'projections'**
What does this question mean？(My matplotlib version is 3.3.0)

**Comment by dstansby** [comment]
It looks like you have matplotlib installed in two places, and python is picking some files from each installation. How did you install matplotlib?

Uninstalling all versions of matplotlib (it looks like you have one in `/home/hsy/.local/lib/python3.6/site-packages/` and one in `/home/hsy/anaconda3/envs/tf15_gpu/lib/python3.6/site-packages/`) and reinstalling might work.

**Comment by mydlgit** [comment]
> It looks like you have matplotlib installed in two places, and python is picking some files from each installation. How did you install matplotlib?
> 
> Uninstalling all versions of matplotlib (it looks like you have one in `/home/hsy/.local/lib/python3.6/site-packages/` and one in `/home/hsy/anaconda3/envs/tf15_gpu/lib/python3.6/site-packages/`) and reinstalling might work.

Thx, I have solved this problem by uninstalling the matplotlib in first place.

**Comment by fenugrec** [comment]
Hijacking this since I have nearly the same symptoms, although no clear sign of duplicate matplotlib installs :

```
$ PySetWacom
Traceback (most recent call last):
  File "/home/p/.local/bin/PySetWacom", line 5, in <module>
    from PySetWacom.__main__ import main
  File "/home/p/.local/lib/python3.10/site-packages/PySetWacom/__init__.py", line 29, in <module>
    from PySetWacom.gui import GUI, CaptureKeystrokeDialog, EditMappingDialog, NewProfileValidator, app
  File "/home/p/.local/lib/python3.10/site-packages/PySetWacom/gui.py", line 35, in <module>
    from domdf_wxpython_tools.validators import ValidatorBase  # type: ignore
  File "/home/p/.local/lib/python3.10/site-packages/domdf_wxpython_tools/__init__.py", line 26, in <module>
    from domdf_wxpython_tools.chartpanel import ChartPanelBase
  File "/home/p/.local/lib/python3.10/site-packages/domdf_wxpython_tools/chartpanel.py", line 54, in <module>
    matplotlib.projections.register_projection(XPanAxes)
  File "/home/p/.local/lib/python3.10/site-packages/matplotlib/_api/__init__.py", line 226, in __getattr__
    raise AttributeError(
AttributeError: module 'matplotlib' has no attribute 'projections'. Did you mean: 'collections'?
```

Any ideas ?

**Comment by rcomer** [comment]
@fenugrec we have a section in discourse for help with installation problems.  That is the best place to ask this.
https://discourse.matplotlib.org/c/community/install/13
