### ISSUE TITLE
different behaviour between 3.3.0 and 3.2.2 (and earlier) for ploting in a Tk canvas

### ISSUE THREAD

**Issue by yevgenyr** [matplotlib/matplotlib#18232]
### Bug report
I am trying to plot graphs in a Tk canvas, and I find different behavior for mpl 3.3.0 and 3.2.2.
I am running the same code: 

The code I am reusing it from here: https://github.com/SuperMechaDeathChrist/Widgets/blob/master/plt_figure_w_controls.py 

it runs well for 3.2.2 and bellow but get the following error for 3.3.0:
```python
Traceback (most recent call last):
  File "/home/yr2369/dev/mosydb/_personal/tests/plt_sg.py", line 90, in <module>
    'fig_cv').TKCanvas, fig, window.FindElement('controls_cv').TKCanvas)
  File "/home/yr2369/dev/mosydb/_personal/tests/plt_sg.py", line 17, in draw_figure_w_toolbar
    toolbar = Toolbar(figure_canvas_agg, canvas_toolbar)
  File "/home/yr2369/dev/mosydb/_personal/tests/plt_sg.py", line 34, in __init__
    super(Toolbar, self).__init__(*args, **kwargs)
  File "/home/yr2369/anaconda3/envs/mosydb/lib/python3.7/site-packages/matplotlib/backends/_backend_tk.py", line 525, in __init__
    NavigationToolbar2.__init__(self, canvas)
  File "/home/yr2369/anaconda3/envs/mosydb/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2866, in __init__
    self.set_history_buttons()
  File "/home/yr2369/anaconda3/envs/mosydb/lib/python3.7/site-packages/matplotlib/backends/_backend_tk.py", line 640, in set_history_buttons
    self._buttons['Back']['state'] = tk.DISABLED
KeyError: 'Back'

Process finished with exit code 1
```
It looks like an easy fix, but maybe I am wrong - let me know what additional details you need from me. 
I use python 3.7.8
ps - to test the code -` pip install pysimplegui`

Thank you

**Comment by tacaswell** [comment]
It looks like in 56504fae81c97fe04bfd378c0dad2dc94d221ca3 we made sure that we updated the active/inactive state of the history buttons in Tk, but that sub-class is removing them all together so they are not there to update.

**Comment by QuLogic** [comment]
Should be a simple fix to handle this like Qt does:
https://github.com/matplotlib/matplotlib/blob/4ac49b9c342cf3f3a7d9a2c079b848fa41956b2f/lib/matplotlib/backends/backend_qt5.py#L822-L828

**Comment by tacaswell** [comment]
I'll have a PR shortly.
