### ISSUE TITLE
Importing backend_qt5agg before pyplot causes error on some systems

### ISSUE THREAD

**Issue by blue-fish** [matplotlib/matplotlib#18326]
### Bug report

For some systems, importing `matplotlib.backends.backend_qt5agg` before `matplotlib.pyplot` results in an error.

**Code for reproduction**

```
import matplotlib.backends.backend_qt5agg
import matplotlib.pyplot as plt

plt.plot()
```

**Actual outcome**

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/venv/lib/python3.8/site-packages/matplotlib/pyplot.py", line 2824, in plot
    return gca().plot(
  File "/tmp/venv/lib/python3.8/site-packages/matplotlib/pyplot.py", line 2352, in gca
    return gcf().gca(**kwargs)
  File "/tmp/venv/lib/python3.8/site-packages/matplotlib/pyplot.py", line 731, in gcf
    return figure()
  File "/tmp/venv/lib/python3.8/site-packages/matplotlib/pyplot.py", line 671, in figure
    figManager = new_figure_manager(num, figsize=figsize,
  File "/tmp/venv/lib/python3.8/site-packages/matplotlib/pyplot.py", line 299, in newfigure_manager
    return _backend_mod.new_figure_manager(*args, **kwargs)
  File "/tmp/venv/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 3494, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/tmp/venv/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 3499, in new_figure_manager_given_figure
    canvas = cls.FigureCanvas(figure)
TypeError: 'NoneType' object is not callable
```

**Expected outcome**

plt.plot() should return `[]`, and it does on most systems I've tried it on. But for whatever reason it has this error with some configurations. However, when this occurs I can get the expected outcome by changing the order of the imports:

```
import matplotlib.pyplot as plt
import matplotlib.backends.backend_qt5agg

plt.plot()
```

**Matplotlib version**
  * Operating system: Ubuntu 20.04
  * Matplotlib version: 3.3.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.8.2
  * Jupyter version (if applicable): N/A
  * Other libraries: N/A

Matplotlib installed from pip. Python is the default version shipped with Ubuntu 20.04.

**Comment by blue-fish** [comment]
### Procedure for reproducing error message

1. Download [Ubuntu Desktop 20.04](https://ubuntu.com/download/desktop) (x86_64) and [make a bootable USB drive](https://ubuntu.com/tutorials/create-a-usb-stick-on-windows#1-overview) with the downloaded .iso file
2. Boot from the USB drive and select "Try Ubuntu" to start it without affecting the computer's configuration.
3. Connect to a wifi network
4. Open a terminal and install matplotlib and PyQt5 by running the following commands
```
sudo apt update
sudo apt install curl python3-distutils
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python3 get-pip.py
python3 -m pip install matplotlib PyQt5
```
5. Reproduce the error
```
python3
>>> import matplotlib.backends.backend_qt5agg
>>> import matplotlib.pyplot as plt
>>> plt.plot()
```

**Comment by blue-fish** [comment]
@anntzer I've applied your #18352 changes locally and confirmed that it resolves the issue I am experiencing. Thank you for troubleshooting it!
