### ISSUE TITLE
update_datalim in matplotlib/axes/_base.py cannot handle None

### ISSUE THREAD

**Issue by FRidh** [matplotlib/matplotlib#18524]
### Bug report

**Bug summary**

Passing in `None` will cause `np.isfinite` to raise. This function should handle `None`. Not handling it will result in the following trace when creating a spectrogram with holoviews/hvplot.

**Code for reproduction**
```py
import datetime
import holoviews as hv
import hvplot.xarray
import numpy as np
import pandas as pd
import xarray as xr

hv.extension('matplotlib')

arr = xr.DataArray(np.ones((5, 4)), dims=["a","b"], coords={
    "a": pd.date_range(start=datetime.date(2020, 9, 1), end=datetime.date(2020, 10, 1), periods=5), # works fine without date range
    "b": np.arange(4),
})

arr.hvplot("a", "b")
```

**Actual outcome**

```
Traceback (most recent call last):

  File "/nix/store/42yh96csb0wn65xcbkldvlnrjkrk5sxf-python3-3.8.5-env/lib/python3.8/site-packages/holoviews/plotting/mpl/element.py", line 513, in initialize_plot
    handles = self.init_artists(ax, plot_data, plot_kwargs)

  File "/nix/store/42yh96csb0wn65xcbkldvlnrjkrk5sxf-python3-3.8.5-env/lib/python3.8/site-packages/holoviews/plotting/mpl/element.py", line 531, in init_artists
    artist = plot_fn(*plot_args, **plot_kwargs)

  File "/nix/store/42yh96csb0wn65xcbkldvlnrjkrk5sxf-python3-3.8.5-env/lib/python3.8/site-packages/matplotlib/__init__.py", line 1438, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)

  File "/nix/store/42yh96csb0wn65xcbkldvlnrjkrk5sxf-python3-3.8.5-env/lib/python3.8/site-packages/matplotlib/axes/_axes.py", line 5533, in imshow
    im.set_extent(im.get_extent())

  File "/nix/store/42yh96csb0wn65xcbkldvlnrjkrk5sxf-python3-3.8.5-env/lib/python3.8/site-packages/matplotlib/image.py", line 948, in set_extent
    self.axes.update_datalim(corners)

  File "/nix/store/42yh96csb0wn65xcbkldvlnrjkrk5sxf-python3-3.8.5-env/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 2147, in update_datalim
    if not np.any(np.isfinite(xys)):

TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

**Expected outcome**
No trace.

See the following holoviews solution. I think simply using that function here as well would resolve the issue.
https://github.com/holoviz/holoviews/pull/2715. Note that function has been updated since then.

**Matplotlib version**
Matplotlib 3.3.1
Python 3.8.5
NixOS 20.09.20200831.707bed5

**Comment by QuLogic** [comment]
What code are you running?

**Comment by jklymak** [comment]
Looking at the case above, are you somehow initializing an empty image so that `im.get_extent()` is returning `None`?  I guess one could argue that `get_extent` should return something better?

**Comment by FRidh** [comment]
I've updated the issue with a minimum example. Seems using a date range on an axis triggers the issue.

**Comment by jklymak** [comment]
Can you open this with holoviz?  If there is something we should be fixing, happy to look at it, but we need an example that doesn't use a downstream library's code.  I'll close for now, but we can always re-open.
