### ISSUE TITLE
Conversion cache cleaning is broken with xdist

### ISSUE THREAD

**Issue by QuLogic** [matplotlib/matplotlib#18641]
### Bug report

On `master`, when running tests in parallel (i.e., with pytest-xdist, `pytest -n4`), the conversion cache cleaning that happens at exit trample over each other process. This is likely non-fatal, but a bit suspect looking to people unfamiliar with it.

**Actual outcome**

```pytb
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File ".../lib/matplotlib/testing/compare.py", line 328, in _clean_conversion_cache
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
Error in atexit._run_exitfuncs:
  File ".../lib/matplotlib/testing/compare.py", line 328, in _clean_conversion_cache
Traceback (most recent call last):
  File ".../lib/matplotlib/testing/compare.py", line 328, in _clean_conversion_cache
    path.unlink()
  File ".../conda/envs/mpl37/lib/python3.7/pathlib.py", line 1304, in unlink
    path.unlink()
  File ".../conda/envs/mpl37/lib/python3.7/pathlib.py", line 1304, in unlink
    path.unlink()
  File ".../conda/envs/mpl37/lib/python3.7/pathlib.py", line 1304, in unlink
        self._accessor.unlink(self)self._accessor.unlink(self)    
self._accessor.unlink(self)
FileNotFoundError
FileNotFoundErrorFileNotFoundError: : [Errno 2] No such file or directory: '~/.cache/matplotlib/test_cache/894075a190479001a466df499c487a5a.png'[Errno 2] No such file or directory: '~/.cache/matplotlib/test_cache/894075a190479001a466df499c487a5a.png'

: [Errno 2] No such file or directory: '~/.cache/matplotlib/test_cache/894075a190479001a466df499c487a5a.png'
```

**Comment by anntzer** [comment]
Easiest may be to just `cbook._lock_path(cachedir() / "test_cache")`?

**Comment by QuLogic** [comment]
Seems to work.
