### ISSUE TITLE
Installation error on Python 3.9 in Mac OS.

### ISSUE THREAD

**Issue by AtsushiSakai** [matplotlib/matplotlib#18678]
### Describe the issue

Hi. When I try to install matplotlib 3.3.2 on Python 3.9 for Mac OS Catalina (V10.16.7) using pip, I encountered an error.

This is error message:
```
$ pip3 install matplotlib
Collecting matplotlib
  Using cached matplotlib-3.3.2.tar.gz (37.9 MB)
    ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/fh/qhnlbtlj47x7l932htdbk6jc0000gn/T/pip-install-qvuf9s5n/matplotlib/setup.py'"'"'; __file__='"'"'/private/var/folders/fh/qhnlbtlj47x7l932htdbk6jc0000gn/T/pip-install-qvuf9s5n/matplotlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/fh/qhnlbtlj47x7l932htdbk6jc0000gn/T/pip-pip-egg-info-qce8hdul
         cwd: /private/var/folders/fh/qhnlbtlj47x7l932htdbk6jc0000gn/T/pip-install-qvuf9s5n/matplotlib/
    Complete output (64 lines):
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.

    Edit setup.cfg to change the build options; suppress output with --quiet.

    BUILDING MATPLOTLIB
      matplotlib: yes [3.3.2]
          python: yes [3.9.0 (v3.9.0:9cf6752276, Oct  5 2020, 11:29:23)  [Clang 6.0
                      (clang-600.0.57)]]
        platform: yes [darwin]
     sample_data: yes [installing]
           tests: no  [skipping due to configuration]
          macosx: yes [installing]

    running egg_info
    creating /private/var/folders/fh/qhnlbtlj47x7l932htdbk6jc0000gn/T/pip-pip-egg-info-qce8hdul/matplotlib.egg-info
    writing /private/var/folders/fh/qhnlbtlj47x7l932htdbk6jc0000gn/T/pip-pip-egg-info-qce8hdul/matplotlib.egg-info/PKG-INFO
    writing dependency_links to /private/var/folders/fh/qhnlbtlj47x7l932htdbk6jc0000gn/T/pip-pip-egg-info-qce8hdul/matplotlib.egg-info/dependency_links.txt
    writing namespace_packages to /private/var/folders/fh/qhnlbtlj47x7l932htdbk6jc0000gn/T/pip-pip-egg-info-qce8hdul/matplotlib.egg-info/namespace_packages.txt
    writing requirements to /private/var/folders/fh/qhnlbtlj47x7l932htdbk6jc0000gn/T/pip-pip-egg-info-qce8hdul/matplotlib.egg-info/requires.txt
    writing top-level names to /private/var/folders/fh/qhnlbtlj47x7l932htdbk6jc0000gn/T/pip-pip-egg-info-qce8hdul/matplotlib.egg-info/top_level.txt
    writing manifest file '/private/var/folders/fh/qhnlbtlj47x7l932htdbk6jc0000gn/T/pip-pip-egg-info-qce8hdul/matplotlib.egg-info/SOURCES.txt'
    init_dgelsd failed init
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/fh/qhnlbtlj47x7l932htdbk6jc0000gn/T/pip-install-qvuf9s5n/matplotlib/setup.py", line 242, in <module>
        setup(  # Finally, pass this all along to distutils to do the heavy lifting.
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/__init__.py", line 165, in setup
        return distutils.core.setup(**attrs)
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 297, in run
        self.find_sources()
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 304, in find_sources
        mm.run()
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 535, in run
        self.add_defaults()
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 571, in add_defaults
        sdist.add_defaults(self)
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/sdist.py", line 228, in add_defaults
        self._add_defaults_ext()
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/sdist.py", line 311, in _add_defaults_ext
        build_ext = self.get_finalized_command('build_ext')
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/cmd.py", line 299, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/private/var/folders/fh/qhnlbtlj47x7l932htdbk6jc0000gn/T/pip-install-qvuf9s5n/matplotlib/setup.py", line 88, in finalize_options
        self.distribution.ext_modules[:] = [
      File "/private/var/folders/fh/qhnlbtlj47x7l932htdbk6jc0000gn/T/pip-install-qvuf9s5n/matplotlib/setup.py", line 91, in <listcomp>
        for ext in package.get_extensions()
      File "/private/var/folders/fh/qhnlbtlj47x7l932htdbk6jc0000gn/T/pip-install-qvuf9s5n/matplotlib/setupext.py", line 345, in get_extensions
        add_numpy_flags(ext)
      File "/private/var/folders/fh/qhnlbtlj47x7l932htdbk6jc0000gn/T/pip-install-qvuf9s5n/matplotlib/setupext.py", line 469, in add_numpy_flags
        import numpy as np
      File "/private/var/folders/fh/qhnlbtlj47x7l932htdbk6jc0000gn/T/pip-install-qvuf9s5n/matplotlib/.eggs/numpy-1.19.2-py3.9-macosx-10.9-x86_64.egg/numpy/__init__.py", line 286, in <module>
        raise RuntimeError(msg)
    RuntimeError: Polyfit sanity test emitted a warning, most likely due to using a buggy Accelerate backend. If you compiled yourself, see site.cfg.example for information. Otherwise report this to the vendor that provided NumPy.
    RankWarning: Polyfit may be poorly conditioned

    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

### Proposed fix

To install it successfully.

**Comment by QuLogic** [comment]
This is because NumPy has no 3.9 wheels. numpy/numpy#17482 and #18677

**Comment by WeatherGod** [comment]
Could this be a variation on https://github.com/matplotlib/matplotlib/issues/17980

**Comment by Ammad53** [comment]
@AtsushiSakai  Hi  did you get the  fix for this error?

**Comment by mattip** [comment]
It seems python3.9 no longer accepts `macosx_10_9_x86_64` as a valid platform tag. So pip will not download the binary wheels and will compile from source, pulling in the buggy Accelerate library.

**Comment by tacaswell** [comment]
@mattip Any sense if this a bug in pip / python / wheel / packaging scripts / our configuration?

**Comment by mattip** [comment]
When building python with macOS 11, the `packaging` package, that underneath pip provides the set of valid platform tags, will not accept 10_9. There is an open PR to change that pypa/packaging#319, even if it is accepted today it will take time to percolate through the system. The python you can download [from python.org](https://www.python.org/downloads/mac-osx/) are not compiled with macOS 11, the ones from HomeBrew are compiled via macOS 11. In that case, [homebrew recommends]() using them to install NumPy, i.e, `brew install numpy`.
