### ISSUE TITLE
installation error: Polyfit sanity test emitted a warning, most likely due to using a buggy Accelerate backend.

### ISSUE THREAD

**Issue by vic-lee** [matplotlib/matplotlib#18698]
### Bug report

**Bug summary**

When installing matplotlib, I'm seeing the error as attached below.

I understand that the same error message has been referenced in the following issues: 

- https://github.com/matplotlib/matplotlib/issues/18678
- https://github.com/ReagentX/purple_air_api/issues/63

But the source of the issue in both of these cases are python 3.9. I'm using python 3.7, yet I'm still seeing this error.

**Actual outcome**

```
ERROR:pip.subprocessor:Command errored out with exit status 1:
 command: /Users/shihangli/.local/share/virtualenvs/api-h1FiSvSM/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/qh/cv_ygbw9399d7b37k1p5bzvh0000gn/T/pip-resolver-assc3fcv/matplotlib/setup.py'"'"'; __file__='"'"'/private/var/folders/qh/cv_ygbw9399d7b37k1p5bzvh0000gn/T/pip-resolver-assc3fcv/matplotlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/qh/cv_ygbw9399d7b37k1p5bzvh0000gn/T/pip-resolver-assc3fcv/matplotlib/pip-egg-info
     cwd: /private/var/folders/qh/cv_ygbw9399d7b37k1p5bzvh0000gn/T/pip-resolver-assc3fcv/matplotlib/
Complete output (62 lines):

Edit setup.cfg to change the build options; suppress output with --quiet.

BUILDING MATPLOTLIB
  matplotlib: yes [3.3.2]
      python: yes [3.7.8 (default, Oct  8 2020, 15:45:41)  [Clang 12.0.0
                  (clang-1200.0.28.3)]]
    platform: yes [darwin]
 sample_data: yes [installing]
       tests: no  [skipping due to configuration]
      macosx: yes [installing]

running egg_info
creating /private/var/folders/qh/cv_ygbw9399d7b37k1p5bzvh0000gn/T/pip-resolver-assc3fcv/matplotlib/pip-egg-info/matplotlib.egg-info
writing /private/var/folders/qh/cv_ygbw9399d7b37k1p5bzvh0000gn/T/pip-resolver-assc3fcv/matplotlib/pip-egg-info/matplotlib.egg-info/PKG-INFO
writing dependency_links to /private/var/folders/qh/cv_ygbw9399d7b37k1p5bzvh0000gn/T/pip-resolver-assc3fcv/matplotlib/pip-egg-info/matplotlib.egg-info/dependency_links.txt
writing namespace_packages to /private/var/folders/qh/cv_ygbw9399d7b37k1p5bzvh0000gn/T/pip-resolver-assc3fcv/matplotlib/pip-egg-info/matplotlib.egg-info/namespace_packages.txt
writing requirements to /private/var/folders/qh/cv_ygbw9399d7b37k1p5bzvh0000gn/T/pip-resolver-assc3fcv/matplotlib/pip-egg-info/matplotlib.egg-info/requires.txt
writing top-level names to /private/var/folders/qh/cv_ygbw9399d7b37k1p5bzvh0000gn/T/pip-resolver-assc3fcv/matplotlib/pip-egg-info/matplotlib.egg-info/top_level.txt
writing manifest file '/private/var/folders/qh/cv_ygbw9399d7b37k1p5bzvh0000gn/T/pip-resolver-assc3fcv/matplotlib/pip-egg-info/matplotlib.egg-info/SOURCES.txt'
init_dgelsd failed init
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/private/var/folders/qh/cv_ygbw9399d7b37k1p5bzvh0000gn/T/pip-resolver-assc3fcv/matplotlib/setup.py", line 299, in <module>
    cmdclass=cmdclass,
  File "/Users/shihangli/.local/share/virtualenvs/api-h1FiSvSM/lib/python3.7/site-packages/setuptools/__init__.py", line 165, in setup
    return distutils.core.setup(**attrs)
  File "/Users/shihangli/.pyenv/versions/3.7.8/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/shihangli/.pyenv/versions/3.7.8/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/Users/shihangli/.pyenv/versions/3.7.8/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/shihangli/.local/share/virtualenvs/api-h1FiSvSM/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 297, in run
    self.find_sources()
  File "/Users/shihangli/.local/share/virtualenvs/api-h1FiSvSM/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 304, in find_sources
    mm.run()
  File "/Users/shihangli/.local/share/virtualenvs/api-h1FiSvSM/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 535, in run
    self.add_defaults()
  File "/Users/shihangli/.local/share/virtualenvs/api-h1FiSvSM/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 571, in add_defaults
    sdist.add_defaults(self)
  File "/Users/shihangli/.pyenv/versions/3.7.8/lib/python3.7/distutils/command/sdist.py", line 228, in add_defaults
    self._add_defaults_ext()
  File "/Users/shihangli/.pyenv/versions/3.7.8/lib/python3.7/distutils/command/sdist.py", line 311, in _add_defaults_ext
    build_ext = self.get_finalized_command('build_ext')
  File "/Users/shihangli/.pyenv/versions/3.7.8/lib/python3.7/distutils/cmd.py", line 299, in get_finalized_command
    cmd_obj.ensure_finalized()
  File "/Users/shihangli/.pyenv/versions/3.7.8/lib/python3.7/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "/private/var/folders/qh/cv_ygbw9399d7b37k1p5bzvh0000gn/T/pip-resolver-assc3fcv/matplotlib/setup.py", line 90, in finalize_options
    for package in good_packages
  File "/private/var/folders/qh/cv_ygbw9399d7b37k1p5bzvh0000gn/T/pip-resolver-assc3fcv/matplotlib/setup.py", line 91, in <listcomp>
    for ext in package.get_extensions()
  File "/private/var/folders/qh/cv_ygbw9399d7b37k1p5bzvh0000gn/T/pip-resolver-assc3fcv/matplotlib/setupext.py", line 345, in get_extensions
    add_numpy_flags(ext)
  File "/private/var/folders/qh/cv_ygbw9399d7b37k1p5bzvh0000gn/T/pip-resolver-assc3fcv/matplotlib/setupext.py", line 469, in add_numpy_flags
    import numpy as np
  File "/Users/shihangli/.local/share/virtualenvs/api-h1FiSvSM/lib/python3.7/site-packages/numpy/__init__.py", line 286, in <module>
    raise RuntimeError(msg)
RuntimeError: Polyfit sanity test emitted a warning, most likely due to using a buggy Accelerate backend. If you compiled yourself, see site.cfg.example for information. Otherwise report this to the vendor that provided NumPy.
RankWarning: Polyfit may be poorly conditioned
```

**Expected outcome**

To be installed successfully.

**Matplotlib version**

  * Matplotlib version: latest
  * Matplotlib backend (`print(matplotlib.get_backend())`): latest
  * Python version: 3.7.8

**Comment by jklymak** [comment]
Do you have 3.9 installed in a different env? Looks like you may have crossed installations of numpy.  Make sure you install numpy in this py3.7 env first and then try matplotlib again.

**Comment by vic-lee** [comment]
> Do you have 3.9 installed in a different env? Looks like you may have crossed installations of numpy. Make sure you install numpy in this py3.7 env first and then try matplotlib again.

Thanks for your reply. Here's what have:

```
$ pip3 install numpy
Requirement already satisfied: numpy in /Users/shihangli/.local/share/virtualenvs/api-h1FiSvSM/lib/python3.7/site-packages (1.19.2)
$ pip3 install matplotlib
// error linked above
```

As the output from `pip3 install numpy` shows, numpy was installed under python 3.7.

I also double checked that I don't have python 3.9 installed on my system.

**Comment by jklymak** [comment]
Sure; can you do `import numpy` from a script or ipython?  

It just seems that numpy is not importable, in which case we can't really help from our end.

**Comment by tacaswell** [comment]
I think these are the key lines in the traceback

```
  File "/private/var/folders/qh/cv_ygbw9399d7b37k1p5bzvh0000gn/T/pip-resolver-assc3fcv/matplotlib/setupext.py", line 469, in add_numpy_flags
    import numpy as np
  File "/Users/shihangli/.local/share/virtualenvs/api-h1FiSvSM/lib/python3.7/site-packages/numpy/__init__.py", line 286, in <module>
    raise RuntimeError(msg)
RuntimeError: Polyfit sanity test emitted a warning, most likely due to using a buggy Accelerate backend. If you compiled yourself, see site.cfg.example for information. Otherwise report this to the vendor that provided NumPy.

```

We are failing to import numpy, I don't think there is anything we can do to help with this on the Matplotlib side.
