### ISSUE TITLE
Error while installing matplotlib in python 3.9 using pip in command prompt

### ISSUE THREAD

**Issue by KushalSharma19** [matplotlib/matplotlib#18718]
Hello everyone, this is  @KushalSharma19,
 I am facing an error while installing matplotlib in python 3.9 using pip in command prompt.
First, I got an issue while installing NumPy, so I installed windows visual studio builds. 
Then it got resolved. 
I tried installing matplotlib but it shows error. 

Here is the code

```
**C:\Users\kushal>pip install matplotlib
Collecting matplotlib
  Using cached matplotlib-3.3.2.tar.gz (37.9 MB)
Collecting certifi>=2020.06.20
  Using cached certifi-2020.6.20-py2.py3-none-any.whl (156 kB)
Collecting cycler>=0.10
  Using cached cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Collecting kiwisolver>=1.0.1
  Using cached kiwisolver-1.2.0.tar.gz (52 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\kushal\appdata\local\programs\python\python39\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\kushal\\AppData\\Local\\Temp\\pip-install-jmzoie_d\\kiwisolver\\setup.py'"'"'; __file__='"'"'C:\\Users\\kushal\\AppData\\Local\\Temp\\pip-install-jmzoie_d\\kiwisolver\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\kushal\AppData\Local\Temp\pip-pip-egg-info-m1yxnht9'
         cwd: C:\Users\kushal\AppData\Local\Temp\pip-install-jmzoie_d\kiwisolver\
    Complete output (44 lines):
    WARNING: The wheel package is not available.
      ERROR: Command errored out with exit status 1:
       command: 'c:\users\kushal\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\kushal\\AppData\\Local\\Temp\\pip-wheel-elo_dqlf\\cppy\\setup.py'"'"'; __file__='"'"'C:\\Users\\kushal\\AppData\\Local\\Temp\\pip-wheel-elo_dqlf\\cppy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\kushal\AppData\Local\Temp\pip-wheel-bsj8jkb9'
           cwd: C:\Users\kushal\AppData\Local\Temp\pip-wheel-elo_dqlf\cppy\
      Complete output (6 lines):
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help

      error: invalid command 'bdist_wheel'
      ----------------------------------------
      ERROR: Failed building wheel for cppy
    ERROR: Failed to build one or more wheels
    Traceback (most recent call last):
      File "c:\users\kushal\appdata\local\programs\python\python39\lib\site-packages\setuptools\installer.py", line 126, in fetch_build_egg
        subprocess.check_call(cmd)
      File "c:\users\kushal\appdata\local\programs\python\python39\lib\subprocess.py", line 373, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['c:\\users\\kushal\\appdata\\local\\programs\\python\\python39\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\kushal\\AppData\\Local\\Temp\\tmp2h8ysndg', '--quiet', 'cppy>=1.1.0']' returned non-zero exit status 1.

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\kushal\AppData\Local\Temp\pip-install-jmzoie_d\kiwisolver\setup.py", line 59, in <module>
        setup(
      File "c:\users\kushal\appdata\local\programs\python\python39\lib\site-packages\setuptools\__init__.py", line 152, in setup
        _install_setup_requires(attrs)
      File "c:\users\kushal\appdata\local\programs\python\python39\lib\site-packages\setuptools\__init__.py", line 147, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "c:\users\kushal\appdata\local\programs\python\python39\lib\site-packages\setuptools\dist.py", line 673, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "c:\users\kushal\appdata\local\programs\python\python39\lib\site-packages\pkg_resources\__init__.py", line 764, in resolve
        dist = best[req.key] = env.best_match(
      File "c:\users\kushal\appdata\local\programs\python\python39\lib\site-packages\pkg_resources\__init__.py", line 1049, in best_match
        return self.obtain(req, installer)
      File "c:\users\kushal\appdata\local\programs\python\python39\lib\site-packages\pkg_resources\__init__.py", line 1061, in obtain
        return installer(requirement)
      File "c:\users\kushal\appdata\local\programs\python\python39\lib\site-packages\setuptools\dist.py", line 732, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "c:\users\kushal\appdata\local\programs\python\python39\lib\site-packages\setuptools\installer.py", line 128, in fetch_build_egg
        raise DistutilsError(str(e)) from e
    distutils.errors.DistutilsError: Command '['c:\\users\\kushal\\appdata\\local\\programs\\python\\python39\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\kushal\\AppData\\Local\\Temp\\tmp2h8ysndg', '--quiet', 'cppy>=1.1.0']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.**
```

please tell me the solution

**Comment by CofeDrink68** [comment]
I have the same problem, My hypothesis is that he can't install a package called zlib ... Do anyone have an idea about that ?

**Comment by KushalSharma19** [comment]
Brother, I am new to the world of programming. I am just 14years old. So, I don't have any idea.

**Comment by CofeDrink68** [comment]
Yours is failing on "cppy". Maybe try to report to the corresponding github repo if any ...

**Comment by KushalSharma19** [comment]
Yes you are right Still there are no packages available for python 3.9. So i will install 3.8 and when packages will be available i will upgrade to 3.9

**Comment by jklymak** [comment]
I'll close this here as we are already tracking 3.9 issues.  Thanks!

**Comment by schneiderfelipe** [comment]
Same problem here, this time while running a GitHub action:

```
Collecting matplotlib
  Downloading matplotlib-3.3.2.tar.gz (37.9 MB)
Collecting certifi>=2020.06.20
  Using cached certifi-2020.6.20-py2.py3-none-any.whl (156 kB)
Collecting cycler>=0.10
  Downloading cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Collecting kiwisolver>=1.0.1
  Downloading kiwisolver-1.2.0.tar.gz (52 kB)
    ERROR: Command errored out with exit status 1:
     command: /opt/hostedtoolcache/Python/3.9.0/x64/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-91z5_k5g/kiwisolver/setup.py'"'"'; __file__='"'"'/tmp/pip-install-91z5_k5g/kiwisolver/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-t_3t8ow1
         cwd: /tmp/pip-install-91z5_k5g/kiwisolver/
    Complete output (44 lines):
    WARNING: The wheel package is not available.
      ERROR: Command errored out with exit status 1:
       command: /opt/hostedtoolcache/Python/3.9.0/x64/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-6j_6i1gl/cppy/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-6j_6i1gl/cppy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-yfrkhbn6
           cwd: /tmp/pip-wheel-6j_6i1gl/cppy/
      Complete output (6 lines):
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help
    
      error: invalid command 'bdist_wheel'
      ----------------------------------------
      ERROR: Failed building wheel for cppy
    ERROR: Failed to build one or more wheels
    Traceback (most recent call last):
      File "/opt/hostedtoolcache/Python/3.9.0/x64/lib/python3.9/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/opt/hostedtoolcache/Python/3.9.0/x64/lib/python3.9/subprocess.py", line 373, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/opt/hostedtoolcache/Python/3.9.0/x64/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpe2n95now', '--quiet', 'cppy>=1.1.0']' returned non-zero exit status 1.
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-91z5_k5g/kiwisolver/setup.py", line 59, in <module>
        setup(
      File "/opt/hostedtoolcache/Python/3.9.0/x64/lib/python3.9/site-packages/setuptools/__init__.py", line 164, in setup
        _install_setup_requires(attrs)
      File "/opt/hostedtoolcache/Python/3.9.0/x64/lib/python3.9/site-packages/setuptools/__init__.py", line 159, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/opt/hostedtoolcache/Python/3.9.0/x64/lib/python3.9/site-packages/setuptools/dist.py", line 699, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "/opt/hostedtoolcache/Python/3.9.0/x64/lib/python3.9/site-packages/pkg_resources/__init__.py", line 779, in resolve
        dist = best[req.key] = env.best_match(
      File "/opt/hostedtoolcache/Python/3.9.0/x64/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1064, in best_match
        return self.obtain(req, installer)
      File "/opt/hostedtoolcache/Python/3.9.0/x64/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1076, in obtain
        return installer(requirement)
      File "/opt/hostedtoolcache/Python/3.9.0/x64/lib/python3.9/site-packages/setuptools/dist.py", line 758, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/opt/hostedtoolcache/Python/3.9.0/x64/lib/python3.9/site-packages/setuptools/installer.py", line 130, in fetch_build_egg
        raise DistutilsError(str(e)) from e
    distutils.errors.DistutilsError: Command '['/opt/hostedtoolcache/Python/3.9.0/x64/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpe2n95now', '--quiet', 'cppy>=1.1.0']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Error: Process completed with exit code 1.
```

**Comment by schneiderfelipe** [comment]
> Yes you are right Still there are no packages available for python 3.9. So i will install 3.8 and when packages will be available i will upgrade to 3.9

I can confirm that by downgrading Python to 3.8.6, I could solve the issue.

**Comment by tacaswell** [comment]
@schneiderfelipe You may need to install `pip install wheel` as you are failing on building kiwisolver (one of our deps) not on Matplotlib itsself.

**Comment by schneiderfelipe** [comment]
> @schneiderfelipe You may need to install `pip install wheel` as you are failing on building kiwisolver (one of our deps) not on Matplotlib itsself.

You are absolutely right, but there are [reports about Pillow failing after that](https://github.com/matplotlib/matplotlib/issues/18718#issuecomment-707589303) ([see also this SO question](https://stackoverflow.com/a/64285448/4039050)). Is it possible that some of those packages are not ready for 3.9 yet? ([As pointed out by @KushalSharma19](https://github.com/matplotlib/matplotlib/issues/18718#issuecomment-707876270)).

**Comment by schneiderfelipe** [comment]
Thanks for the thorogh explanation, @tacaswell, that was really useful!

I decided to stay with 3.8.x as I don't actually need 3.9. The issue for me was really using [GitHub's actions/setup-python](https://github.com/actions/setup-python) without specifying a complete version,

```
- uses: actions/setup-python@v2
  with:
    python-version: '3.x'
```

Chaging `3.x` to `3.8.x` solved the issue (in case anyone in the future sees this). Now I know *why*.

**Comment by hugovk** [comment]
> @tacaswell You are absolutely right, but there are [reports about Pillow failing after that](https://github.com/matplotlib/matplotlib/issues/18718#issuecomment-707589303) ([see also this SO question](https://stackoverflow.com/a/64285448/4039050)). Is it possible that some of those packages are not ready for 3.9 yet? ([As pointed out by @KushalSharma19](https://github.com/matplotlib/matplotlib/issues/18718#issuecomment-707876270)).

Pillow 8.0.0 now supports Python 3.9 with wheels: https://pillow.readthedocs.io/en/stable/releasenotes/8.0.0.html

**Comment by Shadrach-characteristic7** [comment]
@tacaswell https://lnkr.fun/e8c0081
