### ISSUE TITLE
Some plot formats (-- and :) break future scipy.optimize.curve_fit fits

### ISSUE THREAD

**Issue by jtc42** [matplotlib/matplotlib#18775]
### Bug report

Plotting line data with certain formats causes future scipy.optimize.curve_fit fits to fail. Feeding the exact same data and parameters into the fit function works first time, and then again **if no plot is created with the specific formats in between the two**.

It seems to be that plot formats requiring some level of interpolation (dashed lines, dashed dots) cause the issue, but others such as lines, dots etc don't.

**Code for reproduction**

https://gist.github.com/jtc42/b2c895f4abd3704d9efe445015dd2d62

**Actual outcome**

```
[1.00000000e+00 1.00000000e+01 2.69119407e-01 1.24560000e+03]
Traceback (most recent call last):
  File ".\main.py", line 12, in <module>
    L_popt, L_pcov = curve_fit(
  File "C:\Users\jtc92\scoop\apps\python\current\lib\site-packages\scipy\optimize\minpack.py", line 795, in curve_fit
    res = least_squares(func, p0, jac=jac, bounds=bounds, method=method,
  File "C:\Users\jtc92\scoop\apps\python\current\lib\site-packages\scipy\optimize\_lsq\least_squares.py", line 915, in least_squares
    result = trf(fun_wrapped, jac_wrapped, x0, f0, J0, lb, ub, ftol, xtol,
  File "C:\Users\jtc92\scoop\apps\python\current\lib\site-packages\scipy\optimize\_lsq\trf.py", line 123, in trf
    return trf_bounds(
  File "C:\Users\jtc92\scoop\apps\python\current\lib\site-packages\scipy\optimize\_lsq\trf.py", line 301, in trf_bounds
    U, s, V = svd(J_augmented, full_matrices=False)
  File "C:\Users\jtc92\scoop\apps\python\current\lib\site-packages\scipy\linalg\decomp_svd.py", line 129, in svd
    raise LinAlgError("SVD did not converge")
numpy.linalg.LinAlgError: SVD did not converge
```

**Expected outcome**

```
[1.00000000e+00 1.00000000e+01 2.69119407e-01 1.24560000e+03]
[1.00000000e+00 1.00000000e+01 2.69119407e-01 1.24560000e+03]
```

**Matplotlib version**
  * Operating system: Windows 10
  * Matplotlib version: 3.3.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 3.8.5
  * Other libraries: scipy 1.5.3, numpy 1.19.2

Installed from pip

**Comment by jklymak** [comment]
Please provide a self contained matplotlib example that causes this problem.  We don't use scipy so it's hard to see how we are causing the problem.

**Comment by richardsheridan** [comment]
Possibly this is related to the windows/openblas bug that was recently fixed in 1.19.3?
 numpy/numpy#16744  
There's some weird x87 state that can get corrupted anywhere and hang around for an arbitrary amount of time. It has not been fixed in the script wheels yet afaik

**Comment by jtc42** [comment]
That definitely looks relevant. Still really odd that it only becomes a problem here depending on the formatting of a plot though...

**Comment by dopplershift** [comment]
Closing because I don't think there is anything for us to do here. Feel free to re-open if you feel there's something wrong with matplotlib here.
