### ISSUE TITLE
Problem with newest kiwisolver

### ISSUE THREAD

**Issue by krzysiekmwk** [matplotlib/matplotlib#18846]
### Bug report

**Bug summary**

When installing matplotlib and trying to import pyplot there is problem with some ImportError: DLL load failed.

**Steps for reproduction**

create new clear environment and activate it:
virtualenv env_new ; source env_new/Scripts/activate
install newest matplotlib:
python -m pip install -U pip
python -m pip install -U matplotlib

Open python and try to import something from matplotlib, e.g.: import matplotlib.pyplot as plt
There will be problem with some ImportError: DLL load failed

```
(env_new) C:\git\test>python
Python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib.pyplot as plt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\git\dapdTest\env_new\lib\site-packages\matplotlib\__init__.py", line 174, in <module>
    _check_versions()
  File "C:\git\dapdTest\env_new\lib\site-packages\matplotlib\__init__.py", line 168, in _check_versions
    module = importlib.import_module(modname)
  File "c:\users\nowakows\appdata\local\programs\python\python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed: The specified module could not be found.
```

**Analyze**
After some digging deeper I found out there is a problem with newest kiwisolver library.

Problem: "Collecting kiwisolver>=1.0.1"
Newest kiwisolver==1.3.0 has some problems. After downgrading it to 1.2.0, everything is okay. (python -m pip install kiwisolver==1.2.0)

```
(env_new) C:\git\test>python
Python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib.pyplot as plt
>>>
```

**Matplotlib version**
certifi==2020.6.20
cycler==0.10.0
kiwisolver==1.3.0
matplotlib==3.3.2
numpy==1.19.3
Pillow==8.0.1
pyparsing==2.4.7
python-dateutil==2.8.1
six==1.15.0

**Comment by MatthieuDartiailh** [comment]
As mentioned in the linked issue I deleted the offending wheels for windows (and figured out the issue). Fixing it will likely require a bugfix release since I will need to update setup.py. While I am at it I would like guidance from the matplotlib people regarding manylinux1 support. Due to an apparent bug in the GCC available on manylinux1 I upgraded to manylinux2010 for the most recent build. Is that fine with matplotlib developers or should I try to produce again manylinux1 wheels ?

**Comment by MatthieuDartiailh** [comment]
I actually yanked the release this way pip will just avoid it.

**Comment by MatthieuDartiailh** [comment]
Ping @tacaswell @QuLogic  maybe (sorry you the only matplotlib developers I can remember)

**Comment by tacaswell** [comment]
As we do not pin to a newer version of kiwisolver, I think it is OK if the newest wheels are manylinux2010.  

I think we are still using manylinux1 to build the Matplotlib wheels and don't see any pressure to move (particularly given the issues with recent-ish pip versions not seeing them yet).

**Comment by MatthieuDartiailh** [comment]
I ask because people using old pip won't be able to install matplotlib because of kiwi if I distribute only 2010 manylinux wheels. Since those tend to bubble both to me and to you guys adding noise to matplotlib which is why I asked.

**Comment by QuLogic** [comment]
If it won't install current kiwi, then it'll install older kiwi and Matplotlib will still work?

**Comment by MatthieuDartiailh** [comment]
The problem is that old pip will still find the source tarball and try to build it (which will often fail on Windows for example). I do not fancy not having a source release on PyPI.

**Comment by tacaswell** [comment]
ah, right :sheep: , is what pip does not what I wished it does in this one case :-p

In that case I think it is up to you if you want to field the "I can't compile" bug reports or get the manylinux1 wheels building.

I agree that it is very important to have the source on pypi!

**Comment by MatthieuDartiailh** [comment]
The manylinux1 bug is fixable (it appears to mostly be a stupid bug in the old GCC of the manylinux1 image, and involve modifying only 2 lines). I will probably go that route for one last release and then switch. Hopefully by then people will stop using pip 9.

**Comment by MatthieuDartiailh** [comment]
Kiwisolver v1.3.1 is now online for Python 3.6 to 3.9. Windows wheels link against VC2014 and not VC2014_1 and manylinux1 wheels which works with all version of pip are provided. Wheels for ARM, PPC64le and PyPy3.6 are also provided. Hopefully this fixes all the issues reported in the past week. Once again sorry for the inconvenience.

**Comment by jklymak** [comment]
Thanks a lot @MatthieuDartiailh.  It's probably a bit of a pain that we depend on you, so your efforts keeping kiwisolver maintained are very much appreciated!

**Comment by MatthieuDartiailh** [comment]
No problem. It is just that when I do make a mistake it is much more visible than I am used to. Also I noticed that the windows linking issue was noticed earlier by the matplotlib team. Would there be a way I could be looped in on build matter that may affect kiwisolver to avoid going through that kind of embarrassing moments again ?
