### ISSUE TITLE
Animation module errors out when using Python3

### ISSUE THREAD

**Issue by aignas** [matplotlib/matplotlib#1891]
I used the double pendulum example and it did not work with the latest version of Matplotlib and Py3k on Arch Linux. However, it worked with Python2.7. I was using

```
#! /usr/bin/env python3
```

as my shebang in the script.

The exact script which I used is here: https://gist.github.com/gns-ank/5347084#file-double_pendulum-py

The error log:

```
Traceback (most recent call last):
  File "./double_pendulum_animated.py", line 88, in <module>
    ani.save('double_pendulum.mp4', fps=15)
  File "/usr/lib/python3.3/site-packages/matplotlib/animation.py", line 616, in save
    writer.grab_frame()
  File "/usr/lib/python3.3/site-packages/matplotlib/animation.py", line 200, in grab_frame
    dpi=self.dpi)
  File "/usr/lib/python3.3/site-packages/matplotlib/figure.py", line 1371, in savefig
    self.canvas.print_figure(*args, **kwargs)
  File "/usr/lib/python3.3/site-packages/matplotlib/backend_bases.py", line 2101, in print_figure
    self.figure.dpi = origDPI
  File "/usr/lib/python3.3/site-packages/matplotlib/figure.py", line 375, in _set_dpi
    self.dpi_scale_trans.clear().scale(dpi, dpi)
  File "/usr/lib/python3.3/site-packages/matplotlib/transforms.py", line 1751, in clear
    self._mtx = np.identity(3)
  File "/usr/lib/python3.3/site-packages/numpy/core/numeric.py", line 1913, in identity
    from numpy import eye
  File "<frozen importlib._bootstrap>", line 1609, in _handle_fromlist
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

Press ENTER or type command to continue
```

**Comment by wrkyle** [comment]
I'm using python 3.4.0, with matplotlib 1.3.1 and am just trying to save my animation but get the errors described above. I see that this appears to be solved on your end but on my end I have no idea what to do to get this to function properly. Can anyone help me out?

**Comment by tacaswell** [comment]
The simplest solution is to update to mpl 1.4.x.
