### ISSUE TITLE
Installation Errors 

### ISSUE THREAD

**Issue by yezz123** [matplotlib/matplotlib#18935]
## Installation Error report

**summary**

- I try to start using a new project using Matplotlib and i have some requirement to download it but during the installation using ` pip install -r requirements.txt ` i get some errors and i think they are based on build :
``` 
requirements that i wanna download : 
beautifulsoup4
black
fake_useragent
flake8
keras
matplotlib
mypy
numpy>=1.17.4
opencv-python
pandas
pillow
pytest
pytest-cov
requests
scikit-fuzzy
sklearn
sympy
tensorflow
xgboost
```
**pip install result**
```bash
Collecting black
  Downloading black-20.8b1.tar.gz (1.1 MB)
     |████████████████████████████████| 1.1 MB 504 kB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting fake_useragent
  Downloading fake-useragent-0.1.11.tar.gz (13 kB)
Requirement already satisfied: flake8 in c:\users\yasse\appdata\local\programs\python\python39\lib\site-packages (from -r requirements.txt (line 4)) (3.8.4)
Collecting keras
  Downloading Keras-2.4.3-py2.py3-none-any.whl (36 kB)
Collecting matplotlib
  Downloading matplotlib-3.3.2.tar.gz (37.9 MB)
     |████████████████████████████████| 37.9 MB 327 kB/s
 ** On entry to DGEBAL parameter number  3 had an illegal value
 ** On entry to DGEHRD  parameter number  2 had an illegal value
 ** On entry to DORGHR DORGQR parameter number  2 had an illegal value
 ** On entry to DHSEQR parameter number  4 had an illegal value
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\yasse\appdata\local\programs\python\python39\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\yasse\\AppData\\Local\\Temp\\pip-install-orrm3uci\\matplotlib\\setup.py'"'"'; __file__='"'"'C:\\Users\\yasse\\AppData\\Local\\Temp\\pip-install-orrm3uci\\matplotlib\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\yasse\AppData\Local\Temp\pip-pip-egg-info-4lqrlvce'
         cwd: C:\Users\yasse\AppData\Local\Temp\pip-install-orrm3uci\matplotlib\
    Complete output (62 lines):
    WARNING: The wheel package is not available.

    Edit setup.cfg to change the build options; suppress output with --quiet.

    BUILDING MATPLOTLIB
      matplotlib: yes [3.3.2]
          python: yes [3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC
                      v.1927 64 bit (AMD64)]]
        platform: yes [win32]
     sample_data: yes [installing]
           tests: no  [skipping due to configuration]
          macosx: no  [Mac OS-X only]

    running egg_info
    creating C:\Users\yasse\AppData\Local\Temp\pip-pip-egg-info-4lqrlvce\matplotlib.egg-info
    writing C:\Users\yasse\AppData\Local\Temp\pip-pip-egg-info-4lqrlvce\matplotlib.egg-info\PKG-INFO
    writing dependency_links to C:\Users\yasse\AppData\Local\Temp\pip-pip-egg-info-4lqrlvce\matplotlib.egg-info\dependency_links.txt
    writing namespace_packages to C:\Users\yasse\AppData\Local\Temp\pip-pip-egg-info-4lqrlvce\matplotlib.egg-info\namespace_packages.txt
    writing requirements to C:\Users\yasse\AppData\Local\Temp\pip-pip-egg-info-4lqrlvce\matplotlib.egg-info\requires.txt
    writing top-level names to C:\Users\yasse\AppData\Local\Temp\pip-pip-egg-info-4lqrlvce\matplotlib.egg-info\top_level.txt
    writing manifest file 'C:\Users\yasse\AppData\Local\Temp\pip-pip-egg-info-4lqrlvce\matplotlib.egg-info\SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\yasse\AppData\Local\Temp\pip-install-orrm3uci\matplotlib\setup.py", line 242, in <module>
        setup(  # Finally, pass this all along to distutils to do the heavy lifting.
      File "c:\users\yasse\appdata\local\programs\python\python39\lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\yasse\appdata\local\programs\python\python39\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\yasse\appdata\local\programs\python\python39\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\users\yasse\appdata\local\programs\python\python39\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\yasse\appdata\local\programs\python\python39\lib\site-packages\setuptools\command\egg_info.py", line 298, in run
        self.find_sources()
      File "c:\users\yasse\appdata\local\programs\python\python39\lib\site-packages\setuptools\command\egg_info.py", line 305, in find_sources
        mm.run()
      File "c:\users\yasse\appdata\local\programs\python\python39\lib\site-packages\setuptools\command\egg_info.py", line 536, in run
        self.add_defaults()
      File "c:\users\yasse\appdata\local\programs\python\python39\lib\site-packages\setuptools\command\egg_info.py", line 572, in add_defaults
        sdist.add_defaults(self)
      File "c:\users\yasse\appdata\local\programs\python\python39\lib\distutils\command\sdist.py", line 228, in add_defaults
        self._add_defaults_ext()
      File "c:\users\yasse\appdata\local\programs\python\python39\lib\distutils\command\sdist.py", line 311, in _add_defaults_ext
        build_ext = self.get_finalized_command('build_ext')
      File "c:\users\yasse\appdata\local\programs\python\python39\lib\distutils\cmd.py", line 299, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "c:\users\yasse\appdata\local\programs\python\python39\lib\distutils\cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "C:\Users\yasse\AppData\Local\Temp\pip-install-orrm3uci\matplotlib\setup.py", line 88, in finalize_options
        self.distribution.ext_modules[:] = [
      File "C:\Users\yasse\AppData\Local\Temp\pip-install-orrm3uci\matplotlib\setup.py", line 91, in <listcomp>
        for ext in package.get_extensions()
      File "C:\Users\yasse\AppData\Local\Temp\pip-install-orrm3uci\matplotlib\setupext.py", line 345, in get_extensions
        add_numpy_flags(ext)
      File "C:\Users\yasse\AppData\Local\Temp\pip-install-orrm3uci\matplotlib\setupext.py", line 469, in add_numpy_flags
        import numpy as np
      File "c:\users\yasse\appdata\local\temp\pip-install-orrm3uci\matplotlib\.eggs\numpy-1.19.4-py3.9-win-amd64.egg\numpy\__init__.py", line 305, in <module>
        _win_os_check()
      File "c:\users\yasse\appdata\local\temp\pip-install-orrm3uci\matplotlib\.eggs\numpy-1.19.4-py3.9-win-amd64.egg\numpy\__init__.py", line 302, in _win_os_check
        raise RuntimeError(msg.format(__file__)) from None
    RuntimeError: The current Numpy installation ('c:\\users\\yasse\\appdata\\local\\temp\\pip-install-orrm3uci\\matplotlib\\.eggs\\numpy-1.19.4-py3.9-win-amd64.egg\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Configuration**

- Operating System: Windows 10 Pro 64-bit (10.0, Build 19041) (19041.vb_release.191206-1406)

- Processor: Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz (4 CPUs), ~2.3GHz

- Memory: 16384MB RAM

- Python version : Python 3.9.0

- Jupyter Notebook version : 6.1.4

**Comment by jklymak** [comment]
Unless you have a burning need to use python 3.9, suggest you use 3.8 for which the wheels have had time to be made...  I'm going to close this as your issue is with the numpy install and you need to get a numpy wheel for your machine.
