### ISSUE TITLE
Defining number of levels in cmap for scatter plot doesn't work

### ISSUE THREAD

**Issue by pl992** [matplotlib/matplotlib#18951]
### Bug report

**Bug summary**
I want to plot a set of points with different colors using Colormaps with a discretized specific discretized number of colors but the following code doesn't work

**Code for reproduction**
```python
import matplotlib.pyplot as plt
import matplotlib.colors as mcolor
import numpy as np
x = np.random.random(100)
y = np.random.random(100)
colors = np.random.randint(0,5,100)
plt.scatter(x,y,c=colors,cmap=mcolor.Colormap('jet',6))
plt.show()
```

**Actual outcome**

```
Traceback (most recent call last):
  File "/home/piersilvio/miniconda3/lib/python3.7/site-packages/matplotlib/backends/backend_qt5.py", line 480, in _draw_idle
    self.draw()
  File "/home/piersilvio/miniconda3/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 407, in draw
    self.figure.draw(self.renderer)
  File "/home/piersilvio/miniconda3/lib/python3.7/site-packages/matplotlib/artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/piersilvio/miniconda3/lib/python3.7/site-packages/matplotlib/figure.py", line 1864, in draw
    renderer, self, artists, self.suppressComposite)
  File "/home/piersilvio/miniconda3/lib/python3.7/site-packages/matplotlib/image.py", line 131, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/piersilvio/miniconda3/lib/python3.7/site-packages/matplotlib/artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/piersilvio/miniconda3/lib/python3.7/site-packages/matplotlib/cbook/deprecation.py", line 411, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/home/piersilvio/miniconda3/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 2747, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/home/piersilvio/miniconda3/lib/python3.7/site-packages/matplotlib/image.py", line 131, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/piersilvio/miniconda3/lib/python3.7/site-packages/matplotlib/artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/piersilvio/miniconda3/lib/python3.7/site-packages/matplotlib/collections.py", line 931, in draw
    Collection.draw(self, renderer)
  File "/home/piersilvio/miniconda3/lib/python3.7/site-packages/matplotlib/artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/piersilvio/miniconda3/lib/python3.7/site-packages/matplotlib/collections.py", line 346, in draw
    self.update_scalarmappable()
  File "/home/piersilvio/miniconda3/lib/python3.7/site-packages/matplotlib/collections.py", line 855, in update_scalarmappable
    self._facecolors = self.to_rgba(self._A, self._alpha)
  File "/home/piersilvio/miniconda3/lib/python3.7/site-packages/matplotlib/cm.py", line 333, in to_rgba
    rgba = self.cmap(x, alpha=alpha, bytes=bytes)
  File "/home/piersilvio/miniconda3/lib/python3.7/site-packages/matplotlib/colors.py", line 568, in __call__
    self._init()
  File "/home/piersilvio/miniconda3/lib/python3.7/site-packages/matplotlib/colors.py", line 663, in _init
    raise NotImplementedError("Abstract class only")
NotImplementedError: Abstract class only
```

**Matplotlib version**

  * Operating system: test on arch linux and debian
  * Matplotlib version: test on 3.3.2 and 3.3.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): test on Qt5Agg and module://ipykernel.pylab.backend_inline
  * Python version: test on 3.7.6 and 3.7.7 
  * Jupyter version (if applicable): 6.1.4
  * Other libraries: 

I installed it either from conda and pip.

N.B.
In the notebook no error comes out it just doesn't print anything. If I include the line `%matplotlib notebook` then it colors everything with the default color

**Comment by jklymak** [comment]
You want to use get_cmap method.  What you are doing here is incompletely instantiating a new colormap.  

Did you see this in our docs somewhere?

**Comment by pl992** [comment]
Thank you! That works. No I've seen it in no docs just tried to stick together different parts
