### ISSUE TITLE
Frequent crashes when used from the command line in debugging

### ISSUE THREAD

**Issue by HenrikJStromberg** [matplotlib/matplotlib#18952]
### Bug report

**Bug summary**

I have my main program run up to a break point in PyCharm. Then I do various 3d line plots from the command line to understand my issues. After displaying the line plot for some while the whole process randomly crashes.

**Code for reproduction**

Sadly I cannot provide a real minimum example since the crashes become more frequent if I am working on a large project. In small scenarios I was unable to reproduce the issue. What I generally do is the following:
```python
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
fig = plt.figure()
ax = Axes3D(fig)
ax.plot(x, y, z)
```

**Actual outcome**

```Exception ignored in: <function Image.__del__ at 0x000001A09EA0A5E8>
Traceback (most recent call last):
  File "C:\Users\Henrik\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x000001A09EA0A5E8>
Traceback (most recent call last):
  File "C:\Users\Henrik\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Tcl_AsyncDelete: async handler deleted by the wrong thread
```

**Matplotlib version**

  * Operating system: Windows 10 (10.0.19041)
  * Matplotlib version: 3.2.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 3.7.7
  * Other libraries: numpy 1.18.2
  * PyCharm 2020 2.3

Matplotlib was installed via pip.

**Comment by QuLogic** [comment]
Please try with 3.3.3.

**Comment by anntzer** [comment]
Closing for lack of activity, and because newer versions likely handle the threading problem better as well.
