### ISSUE TITLE
_tkinter.TclError: unknown color name "white"

### ISSUE THREAD

**Issue by liubamboo** [matplotlib/matplotlib#18999]
### Bug report
Traceback (most recent call last):
  File "/home/lwt/projects/SC-SfMLearner-Release/kitti_eval/eval_odom.py", line 31, in <module>
    seqs=args.seqs,
  File "/home/lwt/projects/SC-SfMLearner-Release/kitti_eval/kitti_odometry.py", line 603, in eval
    self.plot_trajectory(poses_gt, poses_result, i)
  File "/home/lwt/projects/SC-SfMLearner-Release/kitti_eval/kitti_odometry.py", line 280, in plot_trajectory
    fig = plt.figure()
  File "/home/lwt/anaconda3/envs/py36-for-sc-sfmlearner/lib/python3.6/site-packages/matplotlib/pyplot.py", line 693, in figure
    **kwargs)
  File "/home/lwt/anaconda3/envs/py36-for-sc-sfmlearner/lib/python3.6/site-packages/matplotlib/pyplot.py", line 315, in new_figure_manager
    return _backend_mod.new_figure_manager(*args, **kwargs)
  File "/home/lwt/anaconda3/envs/py36-for-sc-sfmlearner/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 3494, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/home/lwt/anaconda3/envs/py36-for-sc-sfmlearner/lib/python3.6/site-packages/matplotlib/backends/_backend_tk.py", line 901, in new_figure_manager_given_figure
    canvas = cls.FigureCanvas(figure, master=window)
  File "/home/lwt/anaconda3/envs/py36-for-sc-sfmlearner/lib/python3.6/site-packages/matplotlib/backends/_backend_tk.py", line 184, in __init__
    width=w, height=h, borderwidth=0, highlightthickness=0)
  File "/home/lwt/anaconda3/envs/py36-for-sc-sfmlearner/lib/python3.6/tkinter/__init__.py", line 2405, in __init__
    Widget.__init__(self, master, 'canvas', cnf, kw)
  File "/home/lwt/anaconda3/envs/py36-for-sc-sfmlearner/lib/python3.6/tkinter/__init__.py", line 2299, in __init__
    (widgetName, self._w) + extra + self._options(cnf))
_tkinter.TclError: unknown color name "white"

**Bug summary**
_tkinter.TclError: unknown color name "white"

when I use matplotlib.pyplot to plot some experiment results. The bug appear. I use ubuntu 18.04, python 3.6 and use ssh and xmanager to connect the server computer. and I use pycharm.
**Code for reproduction**
I run the clone code from https://github.com/JiawangBian/SC-SfMLearner-Release and run the eval_odom.py
        fig = plt.figure()
        ax = plt.gca()
        ax.set_aspect('equal')

**Expected outcome**

**Matplotlib version**

  * Operating system: ubuntu 18.04
  * Matplotlib version: 3.3.3
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version:3.6
  * Jupyter version (if applicable):
  * Other libraries: 

 pip

**Comment by richardsheridan** [comment]
It seems like your tkinter is corrupted. Can you try this code at an interactive prompt:

```python
import tkinter as tk
f = tk.Toplevel(background='white')
```

it should fail with the same error. Then, make a new python 3.6 conda environment and try it again and there should be no error, just two windows to close, one with a white background.

**Comment by anntzer** [comment]
Closing both for lack of activity, and because this likely has a similar cause as https://github.com/matplotlib/matplotlib/issues/8960.
