### ISSUE TITLE
Can't install matplotlib on MacOS Big Sur, Python 3.8

### ISSUE THREAD

**Issue by apacha** [matplotlib/matplotlib#19000]
### Bug report

**Bug summary**

I tried to install matplotlib in a fresh venv on a MacOS Big Sur machine, but got an error instead.

**Code for reproduction**

pip install matplotlib

**Actual outcome**

```
(venv) (base) alex@Alexanders-MacBook-Pro MusicObjectDetector % pip install matplotlib
Collecting matplotlib
  Using cached matplotlib-3.3.3.tar.gz (37.9 MB)
    ERROR: Command errored out with exit status 1:
     command: /Users/alex/Repositories/MusicObjectDetector-TF/MusicObjectDetector/venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/bs/1t82d5697dn_nd32ngbq_9bh0000gn/T/pip-install-ql96_g36/matplotlib/setup.py'"'"'; __file__='"'"'/private/var/folders/bs/1t82d5697dn_nd32ngbq_9bh0000gn/T/pip-install-ql96_g36/matplotlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/bs/1t82d5697dn_nd32ngbq_9bh0000gn/T/pip-pip-egg-info-x_xqvx8g
         cwd: /private/var/folders/bs/1t82d5697dn_nd32ngbq_9bh0000gn/T/pip-install-ql96_g36/matplotlib/
    Complete output (63 lines):
    WARNING: The wheel package is not available.
    
    Edit setup.cfg to change the build options; suppress output with --quiet.
    
    BUILDING MATPLOTLIB
      matplotlib: yes [3.3.3]
          python: yes [3.8.2 (default, Oct  2 2020, 10:45:42)  [Clang 12.0.0
                      (clang-1200.0.32.27)]]
        platform: yes [darwin]
     sample_data: yes [installing]
           tests: no  [skipping due to configuration]
          macosx: yes [installing]
    
    running egg_info
    creating /private/var/folders/bs/1t82d5697dn_nd32ngbq_9bh0000gn/T/pip-pip-egg-info-x_xqvx8g/matplotlib.egg-info
    writing /private/var/folders/bs/1t82d5697dn_nd32ngbq_9bh0000gn/T/pip-pip-egg-info-x_xqvx8g/matplotlib.egg-info/PKG-INFO
    writing dependency_links to /private/var/folders/bs/1t82d5697dn_nd32ngbq_9bh0000gn/T/pip-pip-egg-info-x_xqvx8g/matplotlib.egg-info/dependency_links.txt
    writing namespace_packages to /private/var/folders/bs/1t82d5697dn_nd32ngbq_9bh0000gn/T/pip-pip-egg-info-x_xqvx8g/matplotlib.egg-info/namespace_packages.txt
    writing requirements to /private/var/folders/bs/1t82d5697dn_nd32ngbq_9bh0000gn/T/pip-pip-egg-info-x_xqvx8g/matplotlib.egg-info/requires.txt
    writing top-level names to /private/var/folders/bs/1t82d5697dn_nd32ngbq_9bh0000gn/T/pip-pip-egg-info-x_xqvx8g/matplotlib.egg-info/top_level.txt
    writing manifest file '/private/var/folders/bs/1t82d5697dn_nd32ngbq_9bh0000gn/T/pip-pip-egg-info-x_xqvx8g/matplotlib.egg-info/SOURCES.txt'
    init_dgelsd failed init
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/bs/1t82d5697dn_nd32ngbq_9bh0000gn/T/pip-install-ql96_g36/matplotlib/setup.py", line 242, in <module>
        setup(  # Finally, pass this all along to distutils to do the heavy lifting.
      File "/Users/alex/Repositories/MusicObjectDetector-TF/MusicObjectDetector/venv/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Users/alex/Repositories/MusicObjectDetector-TF/MusicObjectDetector/venv/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 298, in run
        self.find_sources()
      File "/Users/alex/Repositories/MusicObjectDetector-TF/MusicObjectDetector/venv/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 305, in find_sources
        mm.run()
      File "/Users/alex/Repositories/MusicObjectDetector-TF/MusicObjectDetector/venv/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 536, in run
        self.add_defaults()
      File "/Users/alex/Repositories/MusicObjectDetector-TF/MusicObjectDetector/venv/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 572, in add_defaults
        sdist.add_defaults(self)
      File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/command/sdist.py", line 228, in add_defaults
        self._add_defaults_ext()
      File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/command/sdist.py", line 311, in _add_defaults_ext
        build_ext = self.get_finalized_command('build_ext')
      File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/cmd.py", line 299, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/private/var/folders/bs/1t82d5697dn_nd32ngbq_9bh0000gn/T/pip-install-ql96_g36/matplotlib/setup.py", line 88, in finalize_options
        self.distribution.ext_modules[:] = [
      File "/private/var/folders/bs/1t82d5697dn_nd32ngbq_9bh0000gn/T/pip-install-ql96_g36/matplotlib/setup.py", line 91, in <listcomp>
        for ext in package.get_extensions()
      File "/private/var/folders/bs/1t82d5697dn_nd32ngbq_9bh0000gn/T/pip-install-ql96_g36/matplotlib/setupext.py", line 345, in get_extensions
        add_numpy_flags(ext)
      File "/private/var/folders/bs/1t82d5697dn_nd32ngbq_9bh0000gn/T/pip-install-ql96_g36/matplotlib/setupext.py", line 469, in add_numpy_flags
        import numpy as np
      File "/Users/alex/Repositories/MusicObjectDetector-TF/MusicObjectDetector/venv/lib/python3.8/site-packages/numpy/__init__.py", line 286, in <module>
        raise RuntimeError(msg)
    RuntimeError: Polyfit sanity test emitted a warning, most likely due to using a buggy Accelerate backend. If you compiled yourself, see site.cfg.example for information. Otherwise report this to the vendor that provided NumPy.
    RankWarning: Polyfit may be poorly conditioned
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```

**Expected outcome**

Installed version of matplotlib

**Matplotlib version**

  * Operating system: MacOS Big Sur 11.0.1
  * Matplotlib version: 3.3.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): N/A
  * Python version: 3.8

**Comment by QuLogic** [comment]
>     RuntimeError: Polyfit sanity test emitted a warning, most likely due to using a buggy Accelerate backend. If you compiled yourself, see site.cfg.example for information. Otherwise report this to the vendor that provided NumPy.

This is a problem in NumPy; you will have to ask them for ARM wheels, or figure out how to compile it properly yourself.

**Comment by clawfire** [comment]
Same error for me on an upgraded version of Big Sur on an Intel arch :/

**Comment by Cydia5530** [comment]
> Same error for me on an upgraded version of Big Sur on an Intel arch :/

hi guy, have you resolve this problem?  brew install numpy?

**Comment by apacha** [comment]
I think I downgraded to Python 3.7 to fix this.
