### ISSUE TITLE
Calling animation from a function

### ISSUE THREAD

**Issue by vp1981** [matplotlib/matplotlib#19043]
### Bug report

**Bug summary**

Animation defined in a function doesn't do anything.

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as anim

def func1(x,t):
    return np.sin(x+t)

def anim_me(x0,x1):
    xx = np.linspace(x0,x1,500)

    fig, ax = plt.subplots()
    line, = ax.plot([], [])

    f = lambda t: func1(xx,t)

    def init():
        ax.set_xlim(x0,x1)
        ax.set_ylim(-1,1)
        return line,

    def animate(t):
        line.set_ydata(f(t))
        return line,

    ani = anim.FuncAnimation(fig, animate, frames=np.linspace(0,10,100), init_func=init, interval=10, blit=True)
    plt.show()
    return ani
```

(Actually I could do something fishy with python, I not very fluent with it.)

**Actual outcome**

Just empty figure with correctly set x and y axes.

I'm using Archlinux x86_64 and python 3.9, I run code in `jupyter qtconsole` and do inside `qtconsole`
```
%matplotlib qt5
%load test2.py
```
but in console I see many
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 1194, in _on_timer
    ret = func(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/matplotlib/animation.py", line 1426, in _step
    still_going = Animation._step(self, *args)
  File "/usr/lib/python3.9/site-packages/matplotlib/animation.py", line 1157, in _step
    self._draw_next_frame(framedata, self._blit)
  File "/usr/lib/python3.9/site-packages/matplotlib/animation.py", line 1177, in _draw_next_frame
    self._post_draw(framedata, blit)
  File "/usr/lib/python3.9/site-packages/matplotlib/animation.py", line 1200, in _post_draw
    self._blit_draw(self._drawn_artists)
  File "/usr/lib/python3.9/site-packages/matplotlib/animation.py", line 1222, in _blit_draw
    a.axes.draw_artist(a)
  File "/usr/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 2762, in draw_artist
    a.draw(self.figure._cachedRenderer)
  File "/usr/lib/python3.9/site-packages/matplotlib/artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/matplotlib/lines.py", line 742, in draw
    self.recache()
  File "/usr/lib/python3.9/site-packages/matplotlib/lines.py", line 662, in recache
    self._xy = np.column_stack(np.broadcast_arrays(x, y)).astype(float)
  File "<__array_function__ internals>", line 5, in broadcast_arrays
  File "/usr/lib/python3.9/site-packages/numpy/lib/stride_tricks.py", line 258, in broadcast_arrays
    shape = _broadcast_shape(*args)
  File "/usr/lib/python3.9/site-packages/numpy/lib/stride_tricks.py", line 189, in _broadcast_shape
    b = np.broadcast(*args[:32])
ValueError: shape mismatch: objects cannot be broadcast to a single shape
```

**Expected outcome**

I would expect to see animated graphics in separate window.

**Matplotlib version**
  * Operating system: Archlinux x86_64
  * Matplotlib version: 3.3.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): qt5 (`print(plt.get_backend())`: Qt5Agg)
  * Python version: 3.9
  * Jupyter version (if applicable): 4.6.3
  * Other libraries: qtconsole: 4.7.3, qt5: 5.15.2

All packages are come from my distribution.

**Comment by dopplershift** [comment]
So this is a frequent issue where we don't store references to animations, so you need to or else Python will delete it for you (just like if you open a file and don't save it to a variable). So when you call your function (which already returns the animation), you need to do:

```python
anim = anim_me(x0, x1)
```

The error messages are due to a bug in your code--you never set the x values for the line:

```python
    xx = np.linspace(x0,x1,500)

    fig, ax = plt.subplots()

    #
    # Empty plot, no x values
    #
    line, = ax.plot([], [])

    f = lambda t: func1(xx,t)

    def init():
        ax.set_xlim(x0,x1)
        ax.set_ylim(-1,1)
        return line,

    def animate(t):
        #
        # Only setting y values, no x values
        #
        line.set_ydata(f(t))
        return line,
```

**Comment by vp1981** [comment]
Hello, thank you!

I tried to learn how to make animation using examples from gallery but they didn't work within function. I found question on Stackoverflow (didn't save a link) and the suggestion to return animation object, that's why the function do return it. Seems the only error on my side was the empty 'x' plot, after I fixed this I see the animation.

**Comment by jungerm2** [comment]
Please let me know if this should be its own issue but it seems related, hence my commenting here. 

When animating using the following snippet:

```python
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation
from IPython.display import HTML

plt.rcParams['animation.frame_format'] = 'png'

def update_line(num, data, line):
    line.set_data(range(num+1), data[:num])
    return line,
fig1 = plt.figure()

# Fixing random state for reproducibility
np.random.seed(19680801)

size = 25
data = np.random.rand(size)
l, = plt.plot([], [], 'r-')
plt.xlim(0, size)
plt.ylim(0, 1)

line_ani = animation.FuncAnimation(fig1, update_line, size, fargs=(data, l),
                                   interval=50, blit=True)
anim = line_ani.to_jshtml()
plt.close(fig1)

HTML(anim)
```

This error gets thrown: 

```
ValueError                                Traceback (most recent call last)
<ipython-input-7-6fb730cf6bdf> in <module>
     22 line_ani = animation.FuncAnimation(fig1, update_line, size, fargs=(data, l),
     23                                    interval=50, blit=True)
---> 24 anim = line_ani.to_jshtml()
     25 plt.close(fig1)
     26 

~/.ml-venv/lib/python3.8/site-packages/matplotlib/animation.py in to_jshtml(self, fps, embed_frames, default_mode)
   1400                                     embed_frames=embed_frames,
   1401                                     default_mode=default_mode)
-> 1402                 self.save(str(path), writer=writer)
   1403                 self._html_representation = path.read_text()
   1404 

~/.ml-venv/lib/python3.8/site-packages/matplotlib/animation.py in save(self, filename, writer, fps, dpi, codec, bitrate, extra_args, metadata, extra_anim, savefig_kwargs, progress_callback)
   1171                 for anim, d in zip(all_anim, data):
   1172                     # TODO: See if turning off blit is really necessary
-> 1173                     anim._draw_next_frame(d, blit=False)
   1174                     if progress_callback is not None:
   1175                         progress_callback(frame_number, total_frames)

~/.ml-venv/lib/python3.8/site-packages/matplotlib/animation.py in _draw_next_frame(self, framedata, blit)
   1207         self._pre_draw(framedata, blit)
   1208         self._draw_frame(framedata)
-> 1209         self._post_draw(framedata, blit)
   1210 
   1211     def _init_draw(self):

~/.ml-venv/lib/python3.8/site-packages/matplotlib/animation.py in _post_draw(self, framedata, blit)
   1232             self._blit_draw(self._drawn_artists)
   1233         else:
-> 1234             self._fig.canvas.draw_idle()
   1235 
   1236     # The rest of the code in this class is to facilitate easy blitting

~/.ml-venv/lib/python3.8/site-packages/matplotlib/backend_bases.py in draw_idle(self, *args, **kwargs)
   2053         if not self._is_idle_drawing:
   2054             with self._idle_draw_cntx():
-> 2055                 self.draw(*args, **kwargs)
   2056 
   2057     def get_width_height(self):

~/.ml-venv/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py in draw(self)
    404              (self.toolbar._wait_cursor_for_draw_cm() if self.toolbar
    405               else nullcontext()):
--> 406             self.figure.draw(self.renderer)
    407             # A GUI class may be need to update a window using this draw, so
    408             # don't forget to call the superclass.

~/.ml-venv/lib/python3.8/site-packages/matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     72     @wraps(draw)
     73     def draw_wrapper(artist, renderer, *args, **kwargs):
---> 74         result = draw(artist, renderer, *args, **kwargs)
     75         if renderer._rasterizing:
     76             renderer.stop_rasterizing()

~/.ml-venv/lib/python3.8/site-packages/matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     49                 renderer.start_filter()
     50 
---> 51             return draw(artist, renderer, *args, **kwargs)
     52         finally:
     53             if artist.get_agg_filter() is not None:

~/.ml-venv/lib/python3.8/site-packages/matplotlib/figure.py in draw(self, renderer)
   2723 
   2724             self.patch.draw(renderer)
-> 2725             mimage._draw_list_compositing_images(
   2726                 renderer, self, artists, self.suppressComposite)
   2727 

~/.ml-venv/lib/python3.8/site-packages/matplotlib/image.py in _draw_list_compositing_images(renderer, parent, artists, suppress_composite)
    130     if not_composite or not has_images:
    131         for a in artists:
--> 132             a.draw(renderer)
    133     else:
    134         # Composite any adjacent images together

~/.ml-venv/lib/python3.8/site-packages/matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     49                 renderer.start_filter()
     50 
---> 51             return draw(artist, renderer, *args, **kwargs)
     52         finally:
     53             if artist.get_agg_filter() is not None:

~/.ml-venv/lib/python3.8/site-packages/matplotlib/_api/deprecation.py in wrapper(*inner_args, **inner_kwargs)
    429                          else deprecation_addendum,
    430                 **kwargs)
--> 431         return func(*inner_args, **inner_kwargs)
    432 
    433     return wrapper

~/.ml-venv/lib/python3.8/site-packages/matplotlib/axes/_base.py in draw(self, renderer, inframe)
   2923             renderer.stop_rasterizing()
   2924 
-> 2925         mimage._draw_list_compositing_images(renderer, self, artists)
   2926 
   2927         renderer.close_group('axes')

~/.ml-venv/lib/python3.8/site-packages/matplotlib/image.py in _draw_list_compositing_images(renderer, parent, artists, suppress_composite)
    130     if not_composite or not has_images:
    131         for a in artists:
--> 132             a.draw(renderer)
    133     else:
    134         # Composite any adjacent images together

~/.ml-venv/lib/python3.8/site-packages/matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     49                 renderer.start_filter()
     50 
---> 51             return draw(artist, renderer, *args, **kwargs)
     52         finally:
     53             if artist.get_agg_filter() is not None:

~/.ml-venv/lib/python3.8/site-packages/matplotlib/lines.py in draw(self, renderer)
    749 
    750         if self._invalidy or self._invalidx:
--> 751             self.recache()
    752         self.ind_offset = 0  # Needed for contains() method.
    753         if self._subslice and self.axes:

~/.ml-venv/lib/python3.8/site-packages/matplotlib/lines.py in recache(self, always)
    669             y = self._y
    670 
--> 671         self._xy = np.column_stack(np.broadcast_arrays(x, y)).astype(float)
    672         self._x, self._y = self._xy.T  # views
    673 

<__array_function__ internals> in broadcast_arrays(*args, **kwargs)

~/.ml-venv/lib/python3.8/site-packages/numpy/lib/stride_tricks.py in broadcast_arrays(*args, **kwargs)
    262     args = [np.array(_m, copy=False, subok=subok) for _m in args]
    263 
--> 264     shape = _broadcast_shape(*args)
    265 
    266     if all(array.shape == shape for array in args):

~/.ml-venv/lib/python3.8/site-packages/numpy/lib/stride_tricks.py in _broadcast_shape(*args)
    189     # use the old-iterator because np.nditer does not handle size 0 arrays
    190     # consistently
--> 191     b = np.broadcast(*args[:32])
    192     # unfortunately, it cannot handle 32 or more arguments directly
    193     for pos in range(32, len(args), 31):

ValueError: shape mismatch: objects cannot be broadcast to a single shape
```

Now, this error is not at all informative and it's quite hard to figure out what went wrong. In fact, the issue is is simply a type mismatch. The line `line.set_data(range(num+1), data[:num])` should actually say `line.set_data(range(num), data[:num])`. 

I was wondering if it would be possible to improve this error message and make it more like the one we get if we try running `plt.plot([1,2,3], [1, 2])`:

```
~/.ml-venv/lib/python3.8/site-packages/matplotlib/axes/_base.py in _plot_args(self, tup, kwargs, return_kwargs)
    499 
    500         if x.shape[0] != y.shape[0]:
--> 501             raise ValueError(f"x and y must have same first dimension, but "
    502                              f"have shapes {x.shape} and {y.shape}")
    503         if x.ndim > 2 or y.ndim > 2:

ValueError: x and y must have same first dimension, but have shapes (3,) and (2,)
``` 

So how can this error be caught better? I wouldn't mind contributing to this small "quality of life" improvement, I'm just not sure where to start or if this is in fact an issue.  

For reference, I'm using matplotlib-3.3.4+2545.gbd7df7847 which I've built from source, and py3.8.

**Comment by jklymak** [comment]
This is a very separate issue. Please open a new issue.
