### ISSUE TITLE
3D Axes don't work in SubFigures

### ISSUE THREAD

**Issue by QuLogic** [matplotlib/matplotlib#19091]
### Bug report

**Bug summary**

3D Axes fail in SubFigures, with a traceback in `draw`.

**Code for reproduction**

```python
import matplotlib.pyplot as plt
fig = plt.figure()
sf = fig.subfigures()
ax = sf.add_subplot(1, 1, 1, projection='3d')
plt.show()
```

**Actual outcome**

```pytb
Exception in Tkinter callback
Traceback (most recent call last):
  File "/var/container/conda/envs/mpl37/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/var/container/conda/envs/mpl37/lib/python3.7/tkinter/__init__.py", line 749, in callit
    func(*args)
  File "/home/elliott/code/matplotlib/lib/matplotlib/backends/_backend_tk.py", line 239, in idle_draw
    self.draw()
  File "/home/elliott/code/matplotlib/lib/matplotlib/backends/backend_tkagg.py", line 9, in draw
    super().draw()
  File "/home/elliott/code/matplotlib/lib/matplotlib/backends/backend_agg.py", line 406, in draw
    self.figure.draw(self.renderer)
  File "/home/elliott/code/matplotlib/lib/matplotlib/artist.py", line 74, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/home/elliott/code/matplotlib/lib/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/elliott/code/matplotlib/lib/matplotlib/figure.py", line 2885, in draw
    sfig.draw(renderer)
  File "/home/elliott/code/matplotlib/lib/matplotlib/figure.py", line 2231, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/home/elliott/code/matplotlib/lib/matplotlib/image.py", line 133, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/elliott/code/matplotlib/lib/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/elliott/code/matplotlib/lib/mpl_toolkits/mplot3d/axes3d.py", line 463, in draw
    axis.draw(renderer)
  File "/home/elliott/code/matplotlib/lib/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/elliott/code/matplotlib/lib/mpl_toolkits/mplot3d/axis3d.py", line 264, in draw
    ax_inches = np.multiply(ax_scale, self.figure.get_size_inches())
AttributeError: 'SubFigure' object has no attribute 'get_size_inches'
```

**Expected outcome**

**Matplotlib version**
  * Operating system: Fedora 32
  * Matplotlib version: 593033aeef
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version: 3.7

**Comment by jklymak** [comment]
Oh, hmmm.  I thought `get_size_inches` passed through.  Thats an easy fix!
