### ISSUE TITLE
ImportError: cannot import name '_api' from 'matplotlib'

### ISSUE THREAD

**Issue by mengxuanjia** [matplotlib/matplotlib#19113]
```Spyder 4.1.5
Python 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 7.19.0 -- An enhanced Interactive Python.

=========================================================================
NOTE: The following error appeared when setting your Matplotlib backend!!
=========================================================================

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\console\kernel.py", line 580, in _set_mpl_backend
    get_ipython().run_line_magic(magic, backend)
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2327, in run_line_magic
    result = fn(*args, **kwargs)
  File "<decorator-gen-102>", line 2, in matplotlib
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\magic.py", line 187, in <lambda>
    call = lambda f, *a, **k: f(*a, **k)
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\magics\pylab.py", line 99, in matplotlib
    gui, backend = self.shell.enable_matplotlib(args.gui.lower() if isinstance(args.gui, str) else args.gui)
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3506, in enable_matplotlib
    pt.activate_matplotlib(backend)
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\pylabtools.py", line 320, in activate_matplotlib
    from matplotlib import pyplot as plt
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\pyplot.py", line 43, in <module>
    from matplotlib.figure import Figure, figaspect
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\figure.py", line 18, in <module>
    from matplotlib import docstring, projections
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\projections\__init__.py", line 1, in <module>
    from .. import axes, docstring
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\axes\__init__.py", line 1, in <module>
    from ._subplots import *
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\axes\_subplots.py", line 6, in <module>
    from matplotlib.axes._axes import Axes
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\axes\_axes.py", line 21, in <module>
    import matplotlib.mlab as mlab
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\mlab.py", line 41, in <module>
    from matplotlib import _api
ImportError: cannot import name '_api' from 'matplotlib' (C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\__init__.py)
```

**Comment by jklymak** [comment]
Suggest you re-install matplotlib, as your install looks to be crossed somehow.  We can't really deal with bad installs, feel free to take to discourse.matplotlib.org for more user help.  Thanks!
