### ISSUE TITLE
plot_directive errantly tries to run code

### ISSUE THREAD

**Issue by larsoner** [matplotlib/matplotlib#19111]
### Bug report

**Bug summary**

The `.. plot::` directive using doctest syntax can throw a cryptic error by accidentally trying to execute code it shouldn't.

**Code for reproduction**

In a sphinx build:
```
.. plot::

    A:
    
    >>> import matplotlib.pyplot as plt
    >>> plt.plot(0, 0)
    >>> plt.show()
    
    B.
```
and then this happens
```
/home/larsoner/python/numpydoc/numpydoc/tests/tinybuild/numpydoc_test_module.py:docstring of numpydoc_test_module.my_function:37: WARNING: Exception occurred in plotting numpydoc_test_module-my_function-1
 from /home/larsoner/python/numpydoc/numpydoc/tests/tinybuild/generated/numpydoc_test_module.my_function.rst:
Traceback (most recent call last):
  File "/home/larsoner/python/matplotlib/lib/matplotlib/sphinxext/plot_directive.py", line 472, in run_code
    exec(code, ns)
  File "<string>", line 2
    B.
     ^
SyntaxError: invalid syntax
```
If there is another example code block after the `B.`, there is no error. If there is no `plt.show()` in the `A:` block, there is no error. This is especially odd because you can have multi-block plots (even though this isn't documented?):
```
.. plot::

    aoeuaoeuaoeu:
    
    >>> import matplotlib.pyplot as plt
    >>> plt.plot(0, 0)
    >>> plt.show()
    
    B.
    
    >>> plt.plot(1, 1)
    >>> plt.show()
```
This produces two plots.

To try locally, you can check out https://github.com/larsoner/numpydoc/tree/minimal/numpydoc, navigate to the `tests/tinybuild` directory, and do `make` and you should see the error (plus a `print` of how `numpydoc` is actually constructing the `plot` directive).

**Expected outcome**

Doc build completes without error.

**Matplotlib version**

  * Operating system: Linux
  * Matplotlib version: master
  * Matplotlib backend (`print(matplotlib.get_backend())`): 
  * Python version: 3.8

**Comment by anntzer** [comment]
Looks ike the patch below fixes the problem.  Basically we need to decide from the beginning whether the whole block is python (no escape needed) or doctest (escape needed), because after splitting, some doctest chunks may look like python instead...

Back-compatibility is left as an exercise to the reader (I would suggest just deprecating all the public API here, I doubt anyone is setting up the right objects to manually pass them as arguments somewhere in the middle of the sphinx call stack...).

```patch
diff --git i/lib/matplotlib/sphinxext/plot_directive.py w/lib/matplotlib/sphinxext/plot_directive.py
index 2f29dc00b..898d8c7b3 100644
--- i/lib/matplotlib/sphinxext/plot_directive.py
+++ w/lib/matplotlib/sphinxext/plot_directive.py
@@ -295,13 +295,7 @@ def contains_doctest(text):
 
 
 def unescape_doctest(text):
-    """
-    Extract code from a piece of text, which contains either Python code
-    or doctests.
-    """
-    if not contains_doctest(text):
-        return text
-
+    """Extract code from a piece of doctest."""
     code = ""
     for line in text.split("\n"):
         m = re.match(r'^\s*(>>>|\.\.\.) (.*)$', line)
@@ -314,11 +308,9 @@ def unescape_doctest(text):
     return code
 
 
-def split_code_at_show(text):
+def split_code_at_show(text, is_doctest):
     """Split code at plt.show()."""
     parts = []
-    is_doctest = contains_doctest(text)
-
     part = []
     for line in text.split("\n"):
         if (not is_doctest and line.strip() == 'plt.show()') or \
@@ -431,7 +423,7 @@ class PlotError(RuntimeError):
     pass
 
 
-def run_code(code, code_path, ns=None, function_name=None):
+def run_code(code, is_doctest, code_path, ns=None, function_name=None):
     """
     Import a Python module from a path, and run the function given by
     name, if function_name is not None.
@@ -460,7 +452,8 @@ def run_code(code, code_path, ns=None, function_name=None):
             sys, argv=[code_path], path=[os.getcwd(), *sys.path]), \
             contextlib.redirect_stdout(StringIO()):
         try:
-            code = unescape_doctest(code)
+            if is_doctest:
+                code = unescape_doctest(code)
             if ns is None:
                 ns = {}
             if not ns:
@@ -510,9 +503,10 @@ def get_plot_formats(config):
     return formats
 
 
-def render_figures(code, code_path, output_dir, output_base, context,
-                   function_name, config, context_reset=False,
-                   close_figs=False):
+def render_figures(
+    code, is_doctest, code_path, output_dir, output_base, context,
+    function_name, config, context_reset=False, close_figs=False,
+):
     """
     Run a pyplot script and save the images in *output_dir*.
 
@@ -523,7 +517,7 @@ def render_figures(code, code_path, output_dir, output_base, context,
 
     # -- Try to determine if all images already exist
 
-    code_pieces = split_code_at_show(code)
+    code_pieces = split_code_at_show(code, is_doctest)
 
     # Look for single-figure output files first
     all_exists = True
@@ -587,7 +581,7 @@ def render_figures(code, code_path, output_dir, output_base, context,
         elif close_figs:
             plt.close('all')
 
-        run_code(code_piece, code_path, ns, function_name)
+        run_code(code_piece, is_doctest, code_path, ns, function_name)
 
         images = []
         fig_managers = _pylab_helpers.Gcf.get_all_fig_managers()
@@ -679,12 +673,8 @@ def run(arguments, content, options, state_machine, state, lineno):
     output_base = output_base.replace('.', '-')
 
     # is it in doctest format?
-    is_doctest = contains_doctest(code)
-    if 'format' in options:
-        if options['format'] == 'python':
-            is_doctest = False
-        else:
-            is_doctest = True
+    is_doctest = (options['format'] != 'doctest' if 'format' in options
+                  else contains_doctest(code))
 
     # determine output directory name fragment
     source_rel_name = relpath(source_file_name, setup.confdir)
@@ -724,6 +714,7 @@ def run(arguments, content, options, state_machine, state, lineno):
     # make figures
     try:
         results = render_figures(code,
+                                 is_doctest,
                                  source_file_name,
                                  build_dir,
                                  output_base,
@@ -803,7 +794,8 @@ def run(arguments, content, options, state_machine, state, lineno):
 
     # copy script (if necessary)
     Path(dest_dir, output_base + source_ext).write_text(
-        unescape_doctest(code) if source_file_name == rst_file else code,
+        unescape_doctest(code) if source_file_name == rst_file and is_doctest
+        else code,
         encoding='utf-8')
 
     return errors
```
