### ISSUE TITLE
BUG: Axes3D.quiver does not actually accept scalars

### ISSUE THREAD

**Issue by madphysicist** [matplotlib/matplotlib#19148]
### Bug report

**Bug summary**

Plotting on a quiver on 3D axes using a scalar for the endpoint coordinates and lengths is a documented feature: https://matplotlib.org/mpl_toolkits/mplot3d/tutorial.html#quiver:

> The arguments could be array-like or scalars, so long as they they can be broadcast together.

In practice, it raises an error.

**Code for reproduction**

```
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
fig, ax = plt.subplots(subplot_kw={'projection': '3d'})
ax.plot(0, 0, 0, 1, 0, 0)
```

**Actual outcome**

```
Traceback (most recent call last):

  File "C:\test.py", line 4, in <module>
    ax.plot(0, 0, 0, 1, 0, 0)

  File "C:\anaconda3\lib\site-packages\mpl_toolkits\mplot3d\axes3d.py", line 1421, in plot
    zs = np.broadcast_to(zs, len(xs))

TypeError: object of type 'int' has no len()
```

**Expected outcome**

3D plot with a single quiver on it.

**Matplotlib version**
  * Operating system: Windows 10
  * Matplotlib version: 3.2.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.8.3
  * Jupyter version (if applicable): N/A
  * Other libraries: N/A

matplotlib installed via conda (default channel)

**Comment by madphysicist** [comment]
Wow. Sorry about the typo
