### ISSUE TITLE
_make_norm_from_scale needs to process values

### ISSUE THREAD

**Issue by jklymak** [matplotlib/matplotlib#19239]
As noted in #18653, norms created via `colors._make_norm_from_scale` do not process values that are passed to `inverse` so `norm.inverse([0.2, 5, 10])` fails, whereas `norm.inverse(np.array([0.2, 5, 10]))` works fine.  

@QuLogic noticed this: 

Probably because `inverse` doesn't pass `value` through `process_value` like `__call__` does. Something like:
```diff
diff --git a/lib/matplotlib/colors.py b/lib/matplotlib/colors.py
index e417b8178d..b37ec947fa 100644
--- a/lib/matplotlib/colors.py
+++ b/lib/matplotlib/colors.py
@@ -1449,12 +1449,14 @@ def _make_norm_from_scale(scale_cls, base_norm_cls=None, *, init=None):
             t_vmin, t_vmax = self._trf.transform([self.vmin, self.vmax])
             if not np.isfinite([t_vmin, t_vmax]).all():
                 raise ValueError("Invalid vmin or vmax")
+            value, is_scalar = self.process_value(value)
             rescaled = value * (t_vmax - t_vmin)
             rescaled += t_vmin
-            return (self._trf
-                    .inverted()
-                    .transform(rescaled)
-                    .reshape(np.shape(value)))
+            t_value = (self._trf
+                       .inverted()
+                       .transform(rescaled)
+                       .reshape(np.shape(value)))
+            return t_value[0] if is_scalar else t_value
 
     Norm.__name__ = base_norm_cls.__name__
     Norm.__qualname__ = base_norm_cls.__qualname__
```
Maybe it also needs the masking?

_Originally posted by @QuLogic in https://github.com/matplotlib/matplotlib/pull/18653#discussion_r551657752_

**Comment by jklymak** [comment]
### Test: 

```python
import matplotlib.colors as mcolors
import numpy as np

norm = mcolors.LogNorm(vmin=0.1, vmax=10)
print(norm([0.5, 0.4]))
print(norm.inverse([0.5, 0.4]))
```

The second call fails:

```
Traceback (most recent call last):
  File "testbadnorm.py", line 6, in <module>
    print(norm.inverse([0.5, 0.4]))
  File "/Users/jklymak/matplotlib/lib/matplotlib/colors.py", line 1452, in inverse
    rescaled = value * (t_vmax - t_vmin)
TypeError: can't multiply sequence by non-int of type 'numpy.float64'
```
