### ISSUE TITLE
matplotlib.dates file problem

### ISSUE THREAD

**Issue by yueqianhaobo** [matplotlib/matplotlib#19403]
### Bug report
when i run django,it reported
**Bug summary**
D:\software\Anaconda\envs\pytorch_gpu\python.exe E:/python-project/web/Web(2)111/manage.py runserver 127.0.0.1:8000
Performing system checks...

Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "D:\software\Anaconda\envs\pytorch_gpu\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "D:\software\Anaconda\envs\pytorch_gpu\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "D:\software\Anaconda\envs\pytorch_gpu\lib\site-packages\django\utils\autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "D:\software\Anaconda\envs\pytorch_gpu\lib\site-packages\django\core\management\commands\runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "D:\software\Anaconda\envs\pytorch_gpu\lib\site-packages\django\core\management\base.py", line 395, in check
    include_deployment_checks=include_deployment_checks,
  File "D:\software\Anaconda\envs\pytorch_gpu\lib\site-packages\django\core\management\base.py", line 382, in _run_checks
    return checks.run_checks(**kwargs)
  File "D:\software\Anaconda\envs\pytorch_gpu\lib\site-packages\django\core\checks\registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "D:\software\Anaconda\envs\pytorch_gpu\lib\site-packages\django\core\checks\urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "D:\software\Anaconda\envs\pytorch_gpu\lib\site-packages\django\core\checks\urls.py", line 23, in check_resolver
    return check_method()
  File "D:\software\Anaconda\envs\pytorch_gpu\lib\site-packages\django\urls\resolvers.py", line 407, in check
    for pattern in self.url_patterns:
  File "D:\software\Anaconda\envs\pytorch_gpu\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "D:\software\Anaconda\envs\pytorch_gpu\lib\site-packages\django\urls\resolvers.py", line 588, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "D:\software\Anaconda\envs\pytorch_gpu\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "D:\software\Anaconda\envs\pytorch_gpu\lib\site-packages\django\urls\resolvers.py", line 581, in urlconf_module
    return import_module(self.urlconf_name)
  File "D:\software\Anaconda\envs\pytorch_gpu\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "E:\python-project\web\Web(2)111\Web\urls.py", line 34, in <module>
    url(r"^houtai/", include("apps.houtai.urls")),
  File "D:\software\Anaconda\envs\pytorch_gpu\lib\site-packages\django\urls\conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "D:\software\Anaconda\envs\pytorch_gpu\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "E:\python-project\web\Web(2)111\apps\houtai\urls.py", line 16, in <module>
    from apps.houtai.views import *
  File "E:\python-project\web\Web(2)111\apps\houtai\views.py", line 7, in <module>
    from cells_cut.image_cut import *
  File "E:\python-project\web\Web(2)111\cells_cut\image_cut.py", line 2, in <module>
    from pylab import *
  File "C:\Users\ASUS\AppData\Roaming\Python\Python37\site-packages\pylab.py", line 1, in <module>
    from matplotlib.pylab import *
  File "C:\Users\ASUS\AppData\Roaming\Python\Python37\site-packages\matplotlib\pylab.py", line 218, in <module>
    from matplotlib.dates import (
ImportError: cannot import name 'strpdate2num' from 'matplotlib.dates' (C:\Users\ASUS\AppData\Roaming\Python\Python37\site-packages\matplotlib\dates.py)

**Code for reproduction**

perhaps it because environment

```python
# Paste your code here
#
#
```

**Actual outcome**

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

**Matplotlib version**

  * Operating system: 
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): 
  * Matplotlib backend (`print(matplotlib.get_backend())`): 
  * Python version: 
  * Jupyter version (if applicable): 
  * Other libraries:

**Comment by jklymak** [comment]
Your version of django has not been updated to modern matplotlib. Check your versions and/or discuss with them.
