### ISSUE TITLE
OSError on import when cairosvg is installed.

### ISSUE THREAD

**Issue by spalato** [matplotlib/matplotlib#19547]
### Bug report

**Bug summary**

Installing `cairosvg` and `matplotlib` using `pip` causes an `OSError` when trying to `import matplotlib.pyplot`.
The error is not present when `cairosvg` is not installed.

I ran into this issue when running the test suite of `lmfit`. You can see the discussion here: https://github.com/lmfit/lmfit-py/issues/712

I narrowed the issue down to the example below. I encounter this issue on windows, it doesn't seem to happen on linux (lmfit's Azure pipelines don't catch it).

Compounding the issue, the import raises an `OSError` instead of an `ImportError`. It is therefore not caught by `pytest.importorskip`.

**Code for reproduction**

```
conda create -n mpl_cairo python pip
conda activate mpl_cairo
pip install cairosvg matplotlib
python -c "import matplotlib.pyplot"
```

**Actual outcome**

Output of the last command:
```
Traceback (most recent call last):
  File "C:\Users\samue\Anaconda3\envs\mpl_cairo\lib\site-packages\matplotlib\backends\backend_cairo.py", line 15, in <module>
    import cairo
ModuleNotFoundError: No module named 'cairo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\samue\Anaconda3\envs\mpl_cairo\lib\site-packages\matplotlib\pyplot.py", line 2336, in <module>
    switch_backend(rcParams["backend"])
  File "C:\Users\samue\Anaconda3\envs\mpl_cairo\lib\site-packages\matplotlib\__init__.py", line 703, in __getitem__
    plt.switch_backend(rcsetup._auto_backend_sentinel)
  File "C:\Users\samue\Anaconda3\envs\mpl_cairo\lib\site-packages\matplotlib\pyplot.py", line 256, in switch_backend
    switch_backend(candidate)
  File "C:\Users\samue\Anaconda3\envs\mpl_cairo\lib\site-packages\matplotlib\pyplot.py", line 276, in switch_backend
    class backend_mod(matplotlib.backend_bases._Backend):
  File "C:\Users\samue\Anaconda3\envs\mpl_cairo\lib\site-packages\matplotlib\pyplot.py", line 277, in backend_mod
    locals().update(vars(importlib.import_module(backend_name)))
  File "C:\Users\samue\Anaconda3\envs\mpl_cairo\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\samue\Anaconda3\envs\mpl_cairo\lib\site-packages\matplotlib\backends\backend_gtk3agg.py", line 5, in <module>
    from . import backend_cairo
  File "C:\Users\samue\Anaconda3\envs\mpl_cairo\lib\site-packages\matplotlib\backends\backend_cairo.py", line 21, in <module>
    import cairocffi as cairo
  File "C:\Users\samue\Anaconda3\envs\mpl_cairo\lib\site-packages\cairocffi\__init__.py", line 48, in <module>
    cairo = dlopen(
  File "C:\Users\samue\Anaconda3\envs\mpl_cairo\lib\site-packages\cairocffi\__init__.py", line 45, in dlopen
    raise OSError(error_message)  # pragma: no cover
OSError: no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7e
```

**Working example**

Somehow this works without `cairosvg`:
```
conda create -n mpl python pip
conda activate mpl
pip install matplotlib
python -c "import matplotlib.pyplot"
```

**Matplotlib version**

  * Operating system: Windows 10
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): 3.3.4
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg, only in working case. When using `cairosvg`, this raises the same error as above.
  * Python version: Python 3.9.1 | packaged by conda-forge | (default, Jan 26 2021, 01:29:07) [MSC v.1916 64 bit (AMD64)] on win32
  * Jupyter version (if applicable): 
  * Other libraries: cairocffi 1.2.0, CairoSVG 2.5.1, cffi 1.14.5

**Comment by jklymak** [comment]
I can only assume that installing cairosvg is uninstalling `libcairo-2` for some reason. I don't see that matplotlib can help, so I'll close this, but if there is something we can do, please feel free to re-comment, or discuss further at https://discourse.matplotlib.org
