### ISSUE TITLE
Allow legend_elements func parameter to return strings.

### ISSUE THREAD

**Issue by Illviljan** [matplotlib/matplotlib#19555]
### Bug report

**Bug summary**
`PatchCollection.legend_elements` allows mapping values to another using `func`. 
I want to convert numerically values back to categorical strings. But `legend_elements `assumes the converted value is **numerical**.

**Code for reproduction**

```python
import matplotlib.pyplot as plt
import pandas as pd

# Create date:
a = np.arange(0, 15)
x = 2 + a
y = x**2
categorical = pd.Series(a.astype(str), index=a) + " Celcius"

# Convert categorical to numerical:
normed = np.arange(0, len(categorical))
categorical_to_numerical = pd.Series(normed, index=categorical)
color_to_label = pd.Series(categorical_to_numerical.index, index=categorical_to_numerical)

# Plot:
fig, ax = plt.subplots(1, 1)
pc = ax.scatter(x, y, c=categorical_to_numerical)
ax.legend(*pc.legend_elements(fmt="{x}", func=lambda x: color_to_label[x]))
```

**Actual outcome**

```
Traceback (most recent call last):

  File "<ipython-input-114-ab835483b758>", line 1, in <module>
    ax.legend(*pc.legend_elements(func=lambda x: color_to_label[x]))

  File "C:\Users\J.W\anaconda3\lib\site-packages\matplotlib\collections.py", line 1104, in legend_elements
    fmt.set_bounds(func(u).min(), func(u).max())

  File "C:\Users\J.W\anaconda3\lib\site-packages\matplotlib\ticker.py", line 228, in set_bounds
    self.set_view_interval(vmin, vmax)

  File "C:\Users\J.W\anaconda3\lib\site-packages\matplotlib\ticker.py", line 222, in set_view_interval
    self.axis.set_view_interval(vmin, vmax)

  File "C:\Users\J.W\anaconda3\lib\site-packages\matplotlib\ticker.py", line 195, in set_view_interval
    self.viewLim.intervalx = vmin, vmax

  File "C:\Users\J.W\anaconda3\lib\site-packages\matplotlib\transforms.py", line 943, in intervalx
    self._points[:, 0] = interval

ValueError: could not convert string to float: '0 Celcius'
```

**Expected outcome**

![image](https://user-images.githubusercontent.com/14371165/108635709-16f9b980-7481-11eb-8711-6f387e800812.png)

**Suggested solution**
Check what dtype func values are, bypass all numerical checks if it's non-numeric.
When there are more than 9 values, just choose evenly distributed values until the length is 9.

Example implementation:
```python
def legend_elements(
    self, prop="colors", num="auto", fmt=None, func=lambda x: x, **kwargs
):
    """
    Create legend handles and labels for a PathCollection.

    Each legend handle is a `.Line2D` representing the Path that was drawn,
    and each label is a string what each Path represents.

    This is useful for obtaining a legend for a `~.Axes.scatter` plot;
    e.g.::

        scatter = plt.scatter([1, 2, 3],  [4, 5, 6],  c=[7, 2, 3])
        plt.legend(*scatter.legend_elements())

    creates three legend elements, one for each color with the numerical
    values passed to *c* as the labels.

    Also see the :ref:`automatedlegendcreation` example.

    Parameters
    ----------
    prop : {"colors", "sizes"}, default: "colors"
        If "colors", the legend handles will show the different colors of
        the collection. If "sizes", the legend will show the different
        sizes. To set both, use *kwargs* to directly edit the `.Line2D`
        properties.
    num : int, None, "auto" (default), array-like, or `~.ticker.Locator`,
        Target number of elements to create.
        If None, use all unique elements of the mappable array. If an
        integer, target to use *num* elements in the normed range.
        If *"auto"*, try to determine which option better suits the nature
        of the data.
        The number of created elements may slightly deviate from *num* due
        to a `~.ticker.Locator` being used to find useful locations.
        If a list or array, use exactly those elements for the legend.
        Finally, a `~.ticker.Locator` can be provided.
    fmt : str, `~matplotlib.ticker.Formatter`, or None (default)
        The format or formatter to use for the labels. If a string must be
        a valid input for a `~.StrMethodFormatter`. If None (the default),
        use a `~.ScalarFormatter`.
    func : function, default *lambda x: x*
        Function to calculate the labels.  Often the size (or color)
        argument to `~.Axes.scatter` will have been pre-processed by the
        user using a function ``s = f(x)`` to make the markers visible;
        e.g. ``size = np.log10(x)``.  Providing the inverse of this
        function here allows that pre-processing to be inverted, so that
        the legend labels have the correct values; e.g. ``func = lambda
        x: 10**x``.
    **kwargs
        Allowed keyword arguments are *color* and *size*. E.g. it may be
        useful to set the color of the markers if *prop="sizes"* is used;
        similarly to set the size of the markers if *prop="colors"* is
        used. Any further parameters are passed onto the `.Line2D`
        instance. This may be useful to e.g. specify a different
        *markeredgecolor* or *alpha* for the legend handles.

    Returns
    -------
    handles : list of `.Line2D`
        Visual representation of each element of the legend.
    labels : list of str
        The string labels for elements of the legend.
    """
    handles = []
    labels = []
    hasarray = self.get_array() is not None
    if fmt is None:
        fmt = mpl.ticker.ScalarFormatter(useOffset=False, useMathText=True)
    elif isinstance(fmt, str):
        fmt = mpl.ticker.StrMethodFormatter(fmt)
    fmt.create_dummy_axis()

    if prop == "colors":
        if not hasarray:
            warnings.warn(
                "Collection without array used. Make sure to "
                "specify the values to be colormapped via the "
                "`c` argument."
            )
            return handles, labels
        u = np.unique(self.get_array())
        size = kwargs.pop("size", mpl.rcParams["lines.markersize"])
    elif prop == "sizes":
        u = np.unique(self.get_sizes())
        color = kwargs.pop("color", "k")
    else:
        raise ValueError(
            "Valid values for `prop` are 'colors' or "
            f"'sizes'. You supplied '{prop}' instead."
        )

    func_is_numeric = True
    try:
        fmt.set_bounds(func(u).min(), func(u).max())
    except ValueError:
        func_is_numeric = False

    if num == "auto":
        num = 9
        if len(u) <= num:
            num = None
    if num is None:
        values = u
        label_values = func(values)
    elif not func_is_numeric:
        # Values are not numerical so instead of interpolating just
        # choose evenly distributed indexes instead:
        label_values = func(u)
        which_idxs = lambda m, n: np.rint(np.linspace(1, n, min(m, n)) - 1).astype(int)
        cond = which_idxs(num, len(label_values))
        values = u[cond]
        label_values = label_values[cond]
    else:
        if prop == "colors":
            arr = self.get_array()
        elif prop == "sizes":
            arr = self.get_sizes()
        if isinstance(num, mpl.ticker.Locator):
            loc = num
        elif np.iterable(num):
            loc = mpl.ticker.FixedLocator(num)
        else:
            num = int(num)
            loc = mpl.ticker.MaxNLocator(
                nbins=num, min_n_ticks=num - 1, steps=[1, 2, 2.5, 3, 5, 6, 8, 10]
            )
        label_values = loc.tick_values(func(arr).min(), func(arr).max())
        cond = (label_values >= func(arr).min()) & (label_values <= func(arr).max())
        label_values = label_values[cond]
        xarr = np.linspace(arr.min(), arr.max(), 256)
        values = np.interp(label_values, func(xarr), xarr)

    kw = dict(markeredgewidth=self.get_linewidths()[0], alpha=self.get_alpha())
    kw.update(kwargs)

    for val, lab in zip(values, label_values):
        if prop == "colors":
            color = self.cmap(self.norm(val))
        elif prop == "sizes":
            size = np.sqrt(val)
            if np.isclose(size, 0.0):
                continue
        h = mlines.Line2D(
            [0], [0], ls="", color=color, ms=size, marker=self.get_paths()[0], **kw
        )
        handles.append(h)
        if hasattr(fmt, "set_locs"):
            fmt.set_locs(label_values)
        l = fmt(lab)
        labels.append(l)

    return handles, labels
```

**Matplotlib version**

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
byteorder: little
LC_ALL: None
LANG: en
libhdf5: 1.10.4
libnetcdf: None

xarray: 0.16.2
pandas: 1.2.1
numpy: 1.19.2
scipy: 1.6.0
netCDF4: None
pydap: None
h5netcdf: None
h5py: 2.10.0
Nio: None
zarr: None
cftime: None
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: 1.3.2
dask: 2021.01.1
distributed: 2021.02.0
matplotlib: 3.3.2
cartopy: None
seaborn: 0.11.1
numbagg: None
pint: None
setuptools: 52.0.0.post20210125
pip: 20.3.3
conda: 4.9.2
pytest: 6.2.2
IPython: 7.20.0
sphinx: 3.4.3
</details>

**Comment by rcomer** [comment]
See discussion on the linked PR #19556 for why this didn’t go in.
