### ISSUE TITLE
bisect very hard with rcParam changes

### ISSUE THREAD

**Issue by jklymak** [matplotlib/matplotlib#19578]
At some point recently we changed rcParam handling so that it makes `git bisect` require that matplotlib be rebuilt every time a bisect step crosses a change in the rcParam list.  This seems a needless pain, and we should just warn.  

```
  import matplotlib as mpl
Traceback (most recent call last):
  File "/Users/jklymak/matplotlib/testlisted.py", line 1, in <module>
    import matplotlib as mpl
  File "/Users/jklymak/matplotlib/lib/matplotlib/__init__.py", line 833, in <module>
    defaultParams = rcsetup.defaultParams = {
  File "/Users/jklymak/matplotlib/lib/matplotlib/__init__.py", line 836, in <dictcomp>
    rcParamsDefault[key]),
  File "/Users/jklymak/matplotlib/lib/matplotlib/__init__.py", line 621, in __getitem__
    return dict.__getitem__(self, key)
KeyError: 'axes.zmargin'
```

**Comment by tacaswell** [comment]
or at least have  `MPLBISECT_MODE=1` env?

**Comment by anntzer** [comment]
fixed by https://github.com/matplotlib/matplotlib/pull/19603, I believe.
