### ISSUE TITLE
matplotlib thread-safety vs core-dump/segfault

### ISSUE THREAD

**Issue by pelson** [matplotlib/matplotlib#19608]
**Bug summary**

The matplotlib docs clearly state that it is not thread-safe (this is nice clear messaging :+1:). I wanted to give an example of just how bad it can get if you are unlucky (or trying to break things).

In this example I get matplotlib to core dump since it seems that ``tight_layout`` is taking a little while to do its thing, and in the meantime other calls are being made to the underlying backend. This core dump occurs on both ``tkagg`` and ``qt5agg`` backends (didn't try testing others).

I plan to close this issue immediately, as there isn't anything to be done here, other than for me (the user) to fix my code with appropriate locks.

**Code for reproduction**

```python

import datetime
import threading
import time

import matplotlib
matplotlib.use('tkagg')
import matplotlib.pyplot as plt

fig = plt.figure()
plt.plot(range(10))


def update_text(thread_n: int):
    while True:
        fig.axes[0].xaxis.set_ticks(range(10))
        fig.axes[0].xaxis.set_ticklabels([f'foo {i} {thread_n}' for i in range(10)])
        plt.tight_layout()  # Note: I mostly get away with the threaded behaviour without this call.
        fig.canvas.draw()
        time.sleep(1)

threads = []
n = 20
for i in range(n):
    t = threading.Thread(target=update_text, kwargs={'thread_n': i})
    threads.append(t)

for t in threads:
    t.start()

plt.show()

```

**Actual outcome**

Looks like a crash in font handling

```
DEBUG:matplotlib.font_manager:findfont: score(<Font 'Rasa' (Rasa-Bold.ttf) normal normal 700 normal>) = 10.335
DEBUG:matplotlib.font_manager:findfont: score(<Font 'Tlwg Mono' (TlwgMono-Oblique.ttf) oblique normal 400 normal>) = 11.05
DEBUG:matplotlib.font_manager:findfont: score(<Font 'Nimbus Sans' (NimbusSans-Regular.otf) normal normal 400 normal>) = 10.05
DEBUG:matplotlib.font_manager:findfont: score(<Font 'Pagul' (Pagul.ttf) normal normal 400 normal>) = 10.05
DEBUG:matplotlib.font_manager:findfont: score(<Font 'Noto Serif CJK JP' (NotoSerifCJK-Regular.ttc) normal normal 400 normal>) = 10.05
DEBUG:matplotlib.font_manager:findfont: score(<Font 'Tlwg Typewriter' (TlwgTypewriter.ttf) normal normal 400 normal>) = 10.05
DEBUG:matplotlib.font_manager:findfont: score(<Font 'Waree' (Waree.ttf) normal normal 400 normal>) = 10.05

Thread 20 "python" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffb6ffd700 (LWP 126809)]
0x00007fffdd520e47 in TT_Load_Glyph_Header () from /media/important/github/jpype/jpype/env-acc-py-2020.11/lib/python3.7/site-packages/matplotlib/ft2font.cpython-37m-x86_64-linux-gnu.so
(gdb) bt
#0  0x00007fffdd520e47 in TT_Load_Glyph_Header () from /media/important/github/jpype/jpype/env-acc-py-2020.11/lib/python3.7/site-packages/matplotlib/ft2font.cpython-37m-x86_64-linux-gnu.so
#1  0x00007fffdd52302d in load_truetype_glyph () from /media/important/github/jpype/jpype/env-acc-py-2020.11/lib/python3.7/site-packages/matplotlib/ft2font.cpython-37m-x86_64-linux-gnu.so
#2  0x00007fffdd524f9e in TT_Load_Glyph () from /media/important/github/jpype/jpype/env-acc-py-2020.11/lib/python3.7/site-packages/matplotlib/ft2font.cpython-37m-x86_64-linux-gnu.so
#3  0x00007fffdd51fcc1 in tt_glyph_load () from /media/important/github/jpype/jpype/env-acc-py-2020.11/lib/python3.7/site-packages/matplotlib/ft2font.cpython-37m-x86_64-linux-gnu.so
#4  0x00007fffdd513b26 in FT_Load_Glyph () from /media/important/github/jpype/jpype/env-acc-py-2020.11/lib/python3.7/site-packages/matplotlib/ft2font.cpython-37m-x86_64-linux-gnu.so
#5  0x00007fffdd575f82 in af_latin_metrics_init_blues () from /media/important/github/jpype/jpype/env-acc-py-2020.11/lib/python3.7/site-packages/matplotlib/ft2font.cpython-37m-x86_64-linux-gnu.so
#6  0x00007fffdd576d9a in af_latin_metrics_init () from /media/important/github/jpype/jpype/env-acc-py-2020.11/lib/python3.7/site-packages/matplotlib/ft2font.cpython-37m-x86_64-linux-gnu.so
#7  0x00007fffdd5734bc in af_face_globals_get_metrics () from /media/important/github/jpype/jpype/env-acc-py-2020.11/lib/python3.7/site-packages/matplotlib/ft2font.cpython-37m-x86_64-linux-gnu.so
#8  0x00007fffdd57e1f5 in af_loader_load_glyph () from /media/important/github/jpype/jpype/env-acc-py-2020.11/lib/python3.7/site-packages/matplotlib/ft2font.cpython-37m-x86_64-linux-gnu.so
#9  0x00007fffdd57e7e2 in af_autofitter_load_glyph () from /media/important/github/jpype/jpype/env-acc-py-2020.11/lib/python3.7/site-packages/matplotlib/ft2font.cpython-37m-x86_64-linux-gnu.so
#10 0x00007fffdd513aee in FT_Load_Glyph () from /media/important/github/jpype/jpype/env-acc-py-2020.11/lib/python3.7/site-packages/matplotlib/ft2font.cpython-37m-x86_64-linux-gnu.so
#11 0x00007fffdd507a0f in FT2Font::set_text (this=0x7fffac004800, N=N@entry=2, codepoints=0x7fffac012130, angle=<optimised out>, flags=32, xys=...) at src/ft2font.cpp:653
#12 0x00007fffdd50dd8f in PyFT2Font_set_text (self=0x7fffd461b240, args=<optimised out>, kwds=<optimised out>) at src/ft2font_wrapper.cpp:666
#13 0x00005555556b99b6 in _PyMethodDef_RawFastCallKeywords (method=<optimised out>, self=0x7fffd461b240, args=0x7fffac003300, nargs=<optimised out>, kwnames=<optimised out>)
    at /tmp/build/80754af9/python_1598874792229/work/Objects/call.c:693
#14 0x00005555556b9a31 in _PyCFunction_FastCallKeywords (func=0x7fffd464a960, args=<optimised out>, nargs=<optimised out>, kwnames=<optimised out>)
    at /tmp/build/80754af9/python_1598874792229/work/Objects/call.c:732
#15 0x0000555555726483 in call_function (kwnames=0x7fffda90c390, oparg=<optimised out>, pp_stack=<synthetic pointer>) at /tmp/build/80754af9/python_1598874792229/work/Python/ceval.c:4568
#16 _PyEval_EvalFrameDefault (f=<optimised out>, throwflag=<optimised out>) at /tmp/build/80754af9/python_1598874792229/work/Python/ceval.c:3139
#17 0x0000555555668829 in _PyEval_EvalCodeWithName (_co=0x7fffdae9a540, globals=<optimised out>, locals=<optimised out>, args=<optimised out>, argcount=<optimised out>, kwnames=0x7fffdcbc0a28, 
    kwargs=0x7fffac0030b0, kwcount=1, kwstep=1, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0, name=0x7fffdccc2a80, qualname=0x7fffda9028d0) at /tmp/build/80754af9/python_1598874792229/work/Python/ceval.c:3930
#18 0x00005555556b9107 in _PyFunction_FastCallKeywords (func=<optimised out>, stack=0x7fffac003098, nargs=3, kwnames=<optimised out>) at /tmp/build/80754af9/python_1598874792229/work/Objects/call.c:433
#19 0x0000555555722585 in call_function (kwnames=0x7fffdcbc0a10, oparg=<optimised out>, pp_stack=<synthetic pointer>) at /tmp/build/80754af9/python_1598874792229/work/Python/ceval.c:4616
#20 _PyEval_EvalFrameDefault (f=<optimised out>, throwflag=<optimised out>) at /tmp/build/80754af9/python_1598874792229/work/Python/ceval.c:3139
#21 0x0000555555669160 in _PyEval_EvalCodeWithName (_co=0x7fffdcbc1300, globals=<optimised out>, locals=<optimised out>, args=<optimised out>, argcount=<optimised out>, kwnames=0x0, kwargs=0x7fffac002b38, 
    kwcount=0, kwstep=1, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0, name=0x7fffdcc4bb30, qualname=0x7fffdcbbec60) at /tmp/build/80754af9/python_1598874792229/work/Python/ceval.c:3930
#22 0x00005555556b9107 in _PyFunction_FastCallKeywords (func=<optimised out>, stack=0x7fffac002b28, nargs=2, kwnames=<optimised out>) at /tmp/build/80754af9/python_1598874792229/work/Objects/call.c:433
#23 0x0000555555721740 in call_function (kwnames=0x0, oparg=<optimised out>, pp_stack=<synthetic pointer>) at /tmp/build/80754af9/python_1598874792229/work/Python/ceval.c:4616
#24 _PyEval_EvalFrameDefault (f=<optimised out>, throwflag=<optimised out>) at /tmp/build/80754af9/python_1598874792229/work/Python/ceval.c:3110
#25 0x0000555555668829 in _PyEval_EvalCodeWithName (_co=0x7fffdcbc7780, globals=<optimised out>, locals=<optimised out>, args=<optimised out>, argcount=<optimised out>, kwnames=0x0, kwargs=0x7fffd4618b08, 
    kwcount=0, kwstep=1, defs=0x7fffdcbcb9c8, defcount=2, kwdefs=0x0, closure=0x0, name=0x7fffdd0cbc60, qualname=0x7fffdcbca300) at /tmp/build/80754af9/python_1598874792229/work/Python/ceval.c:3930
#26 0x00005555556b90a5 in _PyFunction_FastCallKeywords (func=<optimised out>, stack=0x7fffd4618af8, nargs=2, kwnames=<optimised out>) at /tmp/build/80754af9/python_1598874792229/work/Objects/call.c:433
#27 0x0000555555721740 in call_function (kwnames=0x0, oparg=<optimised out>, pp_stack=<synthetic pointer>) at /tmp/build/80754af9/python_1598874792229/work/Python/ceval.c:4616
#28 _PyEval_EvalFrameDefault (f=<optimised out>, throwflag=<optimised out>) at /tmp/build/80754af9/python_1598874792229/work/Python/ceval.c:3110
#29 0x0000555555668b0a in _PyEval_EvalCodeWithName (_co=0x7fffdafe4300, globals=<optimised out>, locals=<optimised out>, args=<optimised out>, argcount=<optimised out>, kwnames=0x0, kwargs=0x7fffdb484928, 
    kwcount=0, kwstep=1, defs=0x0, defcount=0, kwdefs=0x0, closure=0x7fffda01a890, name=0x7fffdafd20f0, qualname=0x7fffdafe1750) at /tmp/build/80754af9/python_1598874792229/work/Python/ceval.c:3930
#30 0x00005555556b9107 in _PyFunction_FastCallKeywords (func=<optimised out>, stack=0x7fffdb484920, nargs=1, kwnames=<optimised out>) at /tmp/build/80754af9/python_1598874792229/work/Objects/call.c:433
#31 0x00005555557214b6 in call_function (kwnames=0x0, oparg=<optimised out>, pp_stack=<synthetic pointer>) at /tmp/build/80754af9/python_1598874792229/work/Python/ceval.c:4616
#32 _PyEval_EvalFrameDefault (f=<optimised out>, throwflag=<optimised out>) at /tmp/build/80754af9/python_1598874792229/work/Python/ceval.c:3124
#33 0x0000555555669160 in _PyEval_EvalCodeWithName (_co=0x7fffdafe4420, globals=<optimised out>, locals=<optimised out>, args=<optimised out>, argcount=<optimised out>, kwnames=0x0, kwargs=0x7fffac002930, 
    kwcount=0, kwstep=1, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0, name=0x7fffdafe34e0, qualname=0x7fffdafe3cb0) at /tmp/build/80754af9/python_1598874792229/work/Python/ceval.c:3930
#34 0x00005555556b9107 in _PyFunction_FastCallKeywords (func=<optimised out>, stack=0x7fffac002918, nargs=3, kwnames=<optimised out>) at /tmp/build/80754af9/python_1598874792229/work/Objects/call.c:433
#35 0x0000555555721740 in call_function (kwnames=0x0, oparg=<optimised out>, pp_stack=<synthetic pointer>) at /tmp/build/80754af9/python_1598874792229/work/Python/ceval.c:4616
#36 _PyEval_EvalFrameDefault (f=<optimised out>, throwflag=<optimised out>) at /tmp/build/80754af9/python_1598874792229/work/Python/ceval.c:3110
#37 0x0000555555668829 in _PyEval_EvalCodeWithName (_co=0x7fffdaff3a50, globals=<optimised out>, locals=<optimised out>, args=<optimised out>, argcount=<optimised out>, kwnames=0x7fffdaff80e8, 
    kwargs=0x7fffac001ae8, kwcount=1, kwstep=1, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0, name=0x7fffdaff18f0, qualname=0x7fffdaff58a0) at /tmp/build/80754af9/python_1598874792229/work/Python/ceval.c:3930
#38 0x00005555556b9107 in _PyFunction_FastCallKeywords (func=<optimised out>, stack=0x7fffac001ae0, nargs=1, kwnames=<optimised out>) at /tmp/build/80754af9/python_1598874792229/work/Objects/call.c:433
#39 0x0000555555722585 in call_function (kwnames=0x7fffdaff80d0, oparg=<optimised out>, pp_stack=<synthetic pointer>) at /tmp/build/80754af9/python_1598874792229/work/Python/ceval.c:4616
#40 _PyEval_EvalFrameDefault (f=<optimised out>, throwflag=<optimised out>) at /tmp/build/80754af9/python_1598874792229/work/Python/ceval.c:3139
#41 0x00005555556b8e7b in function_code_fastcall (globals=<optimised out>, nargs=2, args=<optimised out>, co=<optimised out>) at /tmp/build/80754af9/python_1598874792229/work/Objects/call.c:283
#42 _PyFunction_FastCallKeywords (func=<optimised out>, stack=0x7fffda007208, nargs=2, kwnames=<optimised out>) at /tmp/build/80754af9/python_1598874792229/work/Objects/call.c:408
#43 0x0000555555721740 in call_function (kwnames=0x0, oparg=<optimised out>, pp_stack=<synthetic pointer>) at /tmp/build/80754af9/python_1598874792229/work/Python/ceval.c:4616
#44 _PyEval_EvalFrameDefault (f=<optimised out>, throwflag=<optimised out>) at /tmp/build/80754af9/python_1598874792229/work/Python/ceval.c:3110
#45 0x0000555555669160 in _PyEval_EvalCodeWithName (_co=0x7fffdafe45d0, globals=<optimised out>, locals=<optimised out>, args=<optimised out>, argcount=<optimised out>, kwnames=0x7fffdafcd568, 
    kwargs=0x7fffac002660, kwcount=1, kwstep=1, defs=0x0, defcount=0, kwdefs=0x7fffdaf9e5f0, closure=0x0, name=0x7fffdd0d0bb0, qualname=0x7fffdafe3ee0)
    at /tmp/build/80754af9/python_1598874792229/work/Python/ceval.c:3930
#46 0x00005555556b9107 in _PyFunction_FastCallKeywords (func=<optimised out>, stack=0x7fffac002650, nargs=2, kwnames=<optimised out>) at /tmp/build/80754af9/python_1598874792229/work/Objects/call.c:433

```

For the record, I saw a different core dump that I was trying to slim down. That dump camp from JPype I think, rather than matplotlib, but was being caused by the error:

```
Traceback (most recent call last):
  File "/tmp/bq_venv/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 224, in process
    func(*args, **kwargs)
  File "/tmp/bqtrig_viewer/gui.py", line 155, in on_resize
    self.fig.tight_layout()
  File "/tmp/bq_venv/lib/python3.7/site-packages/matplotlib/cbook/deprecation.py", line 411, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/tmp/bq_venv/lib/python3.7/site-packages/matplotlib/figure.py", line 2615, in tight_layout
    pad=pad, h_pad=h_pad, w_pad=w_pad, rect=rect)
  File "/tmp/bq_venv/lib/python3.7/site-packages/matplotlib/tight_layout.py", line 308, in get_tight_layout_figure
    pad=pad, h_pad=h_pad, w_pad=w_pad)
  File "/tmp/bq_venv/lib/python3.7/site-packages/matplotlib/tight_layout.py", line 84, in auto_adjust_subplotpars
    bb += [ax.get_tightbbox(renderer, for_layout_only=True)]
  File "/tmp/bq_venv/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 4163, in get_tightbbox
    renderer, for_layout_only=for_layout_only)
  File "/tmp/bq_venv/lib/python3.7/site-packages/matplotlib/axis.py", line 1125, in get_tightbbox
    *ticklabelBoxes2,
  File "/tmp/bq_venv/lib/python3.7/site-packages/matplotlib/axis.py", line 1123, in <genexpr>
    if a.get_visible()),
  File "/tmp/bq_venv/lib/python3.7/site-packages/matplotlib/text.py", line 902, in get_window_extent
    bbox, info, descent = self._get_layout(self._renderer)
  File "/tmp/bq_venv/lib/python3.7/site-packages/matplotlib/text.py", line 296, in _get_layout
    clean_line, self._fontproperties, ismath=ismath)
  File "/tmp/bq_venv/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 238, in get_text_width_height_descent
    font.set_text(s, 0.0, flags=flags)
RuntimeError: In set_text: Could not load glyph (error code 0x14)
```

This error was the same as that reported in https://github.com/spacetelescope/PASTIS/issues/48. I think it was triggered inside a Java managed thread (through JPype) and was resulting in a core-dump. That has nothing to do with matplotlib though (I'm just trying to write this all down so that it can be googled easily). The JPype core dump looked like:

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f9d003e4ed7, pid=26963, tid=26963
#
# JRE version: OpenJDK Runtime Environment 18.9 (11.0.8+10) (build 11.0.8+10-LTS)
# Java VM: OpenJDK 64-Bit Server VM 18.9 (11.0.8+10-LTS, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [ft2font.cpython-37m-x86_64-linux-gnu.so+0x25ed7]
[error occurred during error reporting (printing problematic frame), id 0xb, SIGSEGV (0xb) at pc=0x00007f9d1c95f1e2]

# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /tmp/bqtrig-viewer/hs_err_pid26963.log
[thread 27042 also had an error]
Killed
```

In all cases we are taking about font issues in a multi-threaded context though.

**Expected outcome**

**Nothing different!** This is a consequence of not following the documented recommendations regarding thread-safety. In user code we need to acquire a ``threading.Lock`` (or some other form of synchronisation). *If wanted*, it is believable that matplotlib could do something slightly more sophisticated here with regards to locking for a single figure.

**Comment by pelson** [comment]
Closing, nothing to do here.

**Comment by pelson** [comment]
For completeness, the other core dump I got had more detail about what was happening at the time (TT_Load_Glyph_Header):

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f038e068e47, pid=2626, tid=2626
#
# JRE version: OpenJDK Runtime Environment 18.9 (11.0.8+10) (build 11.0.8+10-LTS)
# Java VM: OpenJDK 64-Bit Server VM 18.9 (11.0.8+10-LTS, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [ft2font.cpython-37m-x86_64-linux-gnu.so+0x25e47]  TT_Load_Glyph_Header+0x4b
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /tmp/hs_err_pid2626.log
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

**Comment by jklymak** [comment]
@tacaswell was noting that thread safeness got worse recently as well.
