### ISSUE TITLE
Errorbars with yerr fail when fillstyle is specified

### ISSUE THREAD

**Issue by rtobar** [matplotlib/matplotlib#19776]
### Bug report

**Bug summary**

Errorbar plots don't accept the `fillstyle` keyword argument anymore when using `yerr`.

**Code for reproduction**

```python
import matplotlib.pyplot as plt
plt.errorbar([1, 2, 3, 4, 5], [5, 6, 7, 8, 9], yerr=[[1, 1, 1, 1, 1], [1, 1, 1,1, 1]], ls='None', mfc='r', fillstyle='full', ecolor = 'r', mec='r',marker='s',markersize=7)
```

**Actual outcome**

```
>>> import matplotlib.pyplot as plt
>>> plt.errorbar([1, 2, 3, 4, 5], [5, 6, 7, 8, 9], yerr=[[1, 1, 1, 1, 1], [1, 1, 1,1, 1]], ls='None', mfc='r', fillstyle='full', ecolor = 'r', mec='r',marker='s',markersize=7)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/python_environments/shark/lib/python3.8/site-packages/matplotlib/pyplot.py", line 2741, in errorbar
    return gca().errorbar(
  File "/opt/python_environments/shark/lib/python3.8/site-packages/matplotlib/__init__.py", line 1352, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/opt/python_environments/shark/lib/python3.8/site-packages/matplotlib/axes/_axes.py", line 3497, in errorbar
    barcols.append(self.vlines(
  File "/opt/python_environments/shark/lib/python3.8/site-packages/matplotlib/__init__.py", line 1352, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/opt/python_environments/shark/lib/python3.8/site-packages/matplotlib/axes/_axes.py", line 1120, in vlines
    lines.update(kwargs)
  File "/opt/python_environments/shark/lib/python3.8/site-packages/matplotlib/artist.py", line 1062, in update
    raise AttributeError(f"{type(self).__name__!r} object "
AttributeError: 'LineCollection' object has no property 'fillstyle'
```

**Expected outcome**

The code to work as before.

**Matplotlib version**

Installed on a virtual environment via `pip install -U matplotlib`:
```
$ pip freeze | grep matplotlib
matplotlib==3.4.0
```

Downgrading to `matplotlib!=3.4` (==3.3.4) works.

**Comment by smartlixx** [comment]
This is caused by `errorbar` used `fillstyle` to plot the error bars, which should only be used to plot markers. However, I don't know why this was introduced from v3.3.4 to v3.4.0. 

I will add a PR to fix this shortly.
