### ISSUE TITLE
FloatingPointError (underflow) during violinplot

### ISSUE THREAD

**Issue by mgroth0** [matplotlib/matplotlib#19837]
Matplotlib: 3.3.4
Matplotlib backend: Agg
Numpy: 1.20.1
OS: linux-gnu
Python: 3.9.2
[Data file download link](https://drive.google.com/file/d/1DY5n13N_mlJmruU5xxiL4xssmRBmg2VV/view?usp=sharing) 

I have a pipeline that involves generating violin plots and am commonly getting this exception thrown when the number of data points in one violin exceeds around 1000. For example, with array lengths of 2500 or 3500. 

Stack trace:
```
>>> plt.violinplot([problem_array])
Traceback (most recent call last):
  File "/om2/user/mjgroth/miniconda3/envs/dnn39/lib/python3.9/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/om2/user/mjgroth/miniconda3/envs/dnn39/lib/python3.9/site-packages/matplotlib/pyplot.py", line 3069, in violinplot
    return gca().violinplot(
  File "/om2/user/mjgroth/miniconda3/envs/dnn39/lib/python3.9/site-packages/matplotlib/__init__.py", line 1447, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/om2/user/mjgroth/miniconda3/envs/dnn39/lib/python3.9/site-packages/matplotlib/axes/_axes.py", line 7858, in violinplot
    vpstats = cbook.violin_stats(dataset, _kde_method, points=points,
  File "/om2/user/mjgroth/miniconda3/envs/dnn39/lib/python3.9/site-packages/matplotlib/cbook/__init__.py", line 1482, in violin_stats
    stats['vals'] = method(x, coords)
  File "/om2/user/mjgroth/miniconda3/envs/dnn39/lib/python3.9/site-packages/matplotlib/axes/_axes.py", line 7856, in _kde_method
    return kde.evaluate(coords)
  File "/om2/user/mjgroth/miniconda3/envs/dnn39/lib/python3.9/site-packages/matplotlib/mlab.py", line 1108, in evaluate
    result[i] = np.sum(np.exp(-energy), axis=0)
FloatingPointError: underflow encountered in exp
```

I've set a breakpoint in the `except` clause to play around with this, and discovered that it occurs 100% of the time if I retry with the same data at the breakpoint. On the other hand, most other arrays work fine (including other arrays that are larger).

The next thing I tried to do was make this problem reproducible, but I've been having so much trouble here. First I saved the problem array to a pickle file, which I've attached at the top.  Next, I downloaded the pickle to my local machine and ran the following: 
```python
import matplotlib.pyplot as plt
import pickle
import numpy as np
import matplotlib
matplotlib.rcParams["backend"] = 'Agg'
if __name__ == '__main__':
    with open('problem_array.pkl', 'rb') as f:
        problem_array = pickle.load(f)
    print(f'len:{len(problem_array)}')
    print(f'min:{min(problem_array)}')
    print(f'max:{max(problem_array)}')
    print(f'num NaNs:{len([n for n in problem_array if np.isnan(n)])}')
    print(f'num floats:{len([n for n in problem_array if isinstance(n,float)])}')
    print(f'backend:{matplotlib.rcParams["backend"]}')
    plt.violinplot([problem_array])
    plt.show()
```

And unfortunately, there was no exception. Output:
```
len:3600
min:0.5916151710066876
max:1.3002891240514034
num NaNs:0
num floats:3600
backend:agg
```

Next, thinking this would have to work, I uploaded this script to the machine where the problem is occurring. I ran it there with the same exact pickle file, and to my frustration the exception still did not occur again. So reproducibility is by far the biggest issue here. Clearly something in my pipeline is causing this bug to occur, but tearing it apart will be a huge process and I wouldn't know where to start. I've even set the breakpoint where the bug is occurring, downloaded the data file attached here, and tried to use `plt.violinplot(data)` right at that spot, and interestingly, **the error does occur here!**. The analysis pipeline is somewhat randomized and so the error doesn't occur every time. But since I have a breakpoint in the `except` clause of my `try` statement I can at least play around with it whenever it happens again. 

Any further troubleshooting tips would be great.

**Comment by mgroth0** [comment]
Another observation with slices:

This works: `plt.violinplot([problem_array[:3497]])`
This causes the exception: `plt.violinplot([problem_array[:3498]])`

`problem_array[3497]` is `0.5916151710066876`

But the number at that point isn't the problem anyway. When I chop parts off the beginning eventually it stops throwing the exception.

`plt.violinplot([problem_array[100:3498]])` still throws the exception
`plt.violinplot([problem_array[1000:3498]])` does not

**Comment by mgroth0** [comment]
Found it!
`np.seterr(all='raise')`
With this line, I can easily reproduce the exception.

**Comment by mgroth0** [comment]
And removing that line from my code avoids the error and the plot works normally.
