### ISSUE TITLE
plt.legend() crashes scatter plot with color map

### ISSUE THREAD

**Issue by jpmvferreira** [matplotlib/matplotlib#19933]
**Bug summary**

Using `plt.legend()` when using `plt.scatter()` while specifying a label for the scatter plot results in Python crashing. For the code below removing `plt.legend()` shows the scatter plot with color map as expected.

**Code for reproduction**

```python
import matplotlib.pyplot as plt

x = [1,2,3]
y = [2,4,6]
z = [-1,0,1]

plt.scatter(x, y, c=z, cmap="gist_rainbow", label="test")
plt.colorbar()
plt.legend()
plt.show()
```

**Actual outcome**

```
Traceback (most recent call last):
  File "/home/undercover/ze/Cadeiras/Astrofísica Complementar/TP/2/fuckthis.py", line 10, in <module>
    plt.show()
  File "/usr/lib/python3.9/site-packages/matplotlib/pyplot.py", line 354, in show
    return _backend_mod.show(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 3575, in show
    manager.show()  # Emits a warning for non-interactive backend.
  File "/usr/lib/python3.9/site-packages/matplotlib/backends/backend_gtk3.py", line 393, in show
    self.canvas.draw()
  File "/usr/lib/python3.9/site-packages/matplotlib/backends/backend_gtk3agg.py", line 70, in draw
    backend_agg.FigureCanvasAgg.draw(self)
  File "/usr/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 406, in draw
    self.figure.draw(self.renderer)
  File "/usr/lib/python3.9/site-packages/matplotlib/artist.py", line 74, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/matplotlib/figure.py", line 2734, in draw
    mimage._draw_list_compositing_images(
  File "/usr/lib/python3.9/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/lib/python3.9/site-packages/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/matplotlib/_api/deprecation.py", line 431, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/usr/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 2925, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/usr/lib/python3.9/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/lib/python3.9/site-packages/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/matplotlib/legend.py", line 614, in draw
    self._legend_box.draw(renderer)
  File "/usr/lib/python3.9/site-packages/matplotlib/offsetbox.py", line 368, in draw
    c.draw(renderer)
  File "/usr/lib/python3.9/site-packages/matplotlib/offsetbox.py", line 368, in draw
    c.draw(renderer)
  File "/usr/lib/python3.9/site-packages/matplotlib/offsetbox.py", line 368, in draw
    c.draw(renderer)
  [Previous line repeated 1 more time]
  File "/usr/lib/python3.9/site-packages/matplotlib/offsetbox.py", line 694, in draw
    c.draw(renderer)
  File "/usr/lib/python3.9/site-packages/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/matplotlib/collections.py", line 1009, in draw
    super().draw(renderer)
  File "/usr/lib/python3.9/site-packages/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/matplotlib/collections.py", line 380, in draw
    len(facecolors) == 1 and len(edgecolors) == 1 and
TypeError: object of type 'NoneType' has no len()
```

**Expected outcome**

The scatter plot with the color map specified and a legend.

**Matplotlib version**
- Operating system: Manjaro
- Matplotlib version: 3.4.0
- Matplotlib backend: GTK3Agg
- Python version: 3.9.2

Both Python and Matplotlib were using pacman in the official repositories.

**Additional comments**
I gave this small script to a friend of mine, running Python version 3.8.5 and Matplotlib 3.4.1, and she said she was able to run the script.

Also running this script on [Trinket](https://trinket.io/embed/python3/a5bd54189b) worked and it show the plot, however I'm unsure what version of Python or Matplotlib they are using.

**Comment by jklymak** [comment]
Yes that is why we released 3.4.1.  Please upgrade.
