### ISSUE TITLE
Passing an array to `valstep` in `Slider` throws a ValueError.

### ISSUE THREAD

**Issue by Tioz90** [matplotlib/matplotlib#20089]
### Bug report

**Bug summary**

Passing an array to `valstep` in `Slider` throws a ValueError.

**Code for reproduction**

```
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.widgets import Slider, Button

t = np.arange(0.0, 1.0, 0.001)
a0 = 5
f0 = 3
s = a0 * np.sin(2 * np.pi * f0 * t)

fig, ax = plt.subplots()
plt.subplots_adjust(bottom=0.25)
l, = plt.plot(t, s, lw=2)

slider_bkd_color = 'lightgoldenrodyellow'
ax_freq = plt.axes([0.25, 0.1, 0.65, 0.03], facecolor=slider_bkd_color)
ax_amp = plt.axes([0.25, 0.15, 0.65, 0.03], facecolor=slider_bkd_color)

# define the values to use for snapping
allowed_amplitudes = np.concatenate([np.linspace(.1, 5, 100), [6, 7, 8, 9]])

# create the sliders
samp = Slider(
    ax_amp, "Amp", 0.1, 9.0,
    valinit=a0, valstep=allowed_amplitudes,
    color="green"
)

sfreq = Slider(
    ax_freq, "Freq", 0, 10*np.pi,
    valinit=2*np.pi, valstep=np.pi,
    initcolor='none'  # Remove the line marking the valinit position.
)


def update(val):
    amp = samp.val
    freq = sfreq.val
    l.set_ydata(amp*np.sin(2*np.pi*freq*t))
    fig.canvas.draw_idle()


sfreq.on_changed(update)
samp.on_changed(update)

ax_reset = plt.axes([0.8, 0.025, 0.1, 0.04])
button = Button(ax_reset, 'Reset', color=slider_bkd_color, hovercolor='0.975')


def reset(event):
    sfreq.reset()
    samp.reset()
button.on_clicked(reset)


plt.show()
```

**Actual outcome**

```
Traceback (most recent call last):
  File "/Users/**/Desktop/interactive_test.py", line 22, in <module>
    samp = Slider(
  File "/Users/**/miniforge3/envs/scientific/lib/python3.8/site-packages/matplotlib/widgets.py", line 332, in __init__
    valinit = self._value_in_bounds(valinit)
  File "/Users/**/miniforge3/envs/scientific/lib/python3.8/site-packages/matplotlib/widgets.py", line 393, in _value_in_bounds
    if self.valstep:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Matplotlib version**

  * Operating system: 
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): 3.3.4 (from conda)
  * Matplotlib backend (`print(matplotlib.get_backend())`): MacOSX
  * Python version: 3.8.8
  * Other libraries: numpy 1.20.1

**Comment by jklymak** [comment]
There have been quite a few recent improvements in the widgets.  Its possible upgrading to 3.4.x will help.  If not, maybe @ianhi has an idea what is going on here?
