### ISSUE TITLE
Error on import. Illegal instruction

### ISSUE THREAD

**Issue by arteze** [matplotlib/matplotlib#20580]
I have an error in importing:

```sh
python3 -c "import matplotlib"
Illegal instruction
```

With gdb:

```sh
gdb -ex r --args python3 -c "import matplotlib"
GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python3...(no debugging symbols found)...done.
Starting program: /usr/bin/python3 -c import\ matplotlib
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".

Program received signal SIGILL, Illegal instruction.
0x00007ffff2bca48f in sdot_k_CORE2 ()
   from /usr/lib64/python3.6/site-packages/numpy/core/../../numpy.libs/libopenblasp-r0-09e95953.3.13.so

(gdb) bt
#0  0x00007ffff2bca48f in sdot_k_CORE2 ()
   from /usr/lib64/python3.6/site-packages/numpy/core/../../numpy.libs/libopenblasp-r0-09e95953.3.13.so
#1  0x00007ffff467b5e1 in FLOAT_dot ()
   from /usr/lib64/python3.6/site-packages/numpy/core/_multiarray_umath.cpython-36m-x86_64-linux-gnu.so
#2  0x00007ffff48c6156 in cblas_matrixproduct ()
   from /usr/lib64/python3.6/site-packages/numpy/core/_multiarray_umath.cpython-36m-x86_64-linux-gnu.so
#3  0x00007ffff4744928 in PyArray_MatrixProduct2 ()
   from /usr/lib64/python3.6/site-packages/numpy/core/_multiarray_umath.cpython-36m-x86_64-linux-gnu.so
#4  0x00007ffff473f307 in array_dot ()
   from /usr/lib64/python3.6/site-packages/numpy/core/_multiarray_umath.cpython-36m-x86_64-linux-gnu.so
#5  0x00007ffff7b740da in _PyCFunction_FastCallDict () from /usr/lib64/libpython3.6m.so.1.0
#6  0x00007ffff7c001cf in ?? () from /usr/lib64/libpython3.6m.so.1.0
#7  0x00007ffff7c02c97 in _PyEval_EvalFrameDefault () from /usr/lib64/libpython3.6m.so.1.0
#8  0x00007ffff7c003c9 in ?? () from /usr/lib64/libpython3.6m.so.1.0
#9  0x00007ffff7c02c97 in _PyEval_EvalFrameDefault () from /usr/lib64/libpython3.6m.so.1.0
#10 0x00007ffff7bffdca in ?? () from /usr/lib64/libpython3.6m.so.1.0
#11 0x00007ffff7c0041f in PyEval_EvalCodeEx () from /usr/lib64/libpython3.6m.so.1.0
#12 0x00007ffff7c0044b in PyEval_EvalCode () from /usr/lib64/libpython3.6m.so.1.0
#13 0x00007ffff7bfd42d in ?? () from /usr/lib64/libpython3.6m.so.1.0
#14 0x00007ffff7b741f5 in PyCFunction_Call () from /usr/lib64/libpython3.6m.so.1.0
#15 0x00007ffff7c06f78 in _PyEval_EvalFrameDefault () from /usr/lib64/libpython3.6m.so.1.0
#16 0x00007ffff7bffdca in ?? () from /usr/lib64/libpython3.6m.so.1.0
#17 0x00007ffff7c00062 in ?? () from /usr/lib64/libpython3.6m.so.1.0
#18 0x00007ffff7c02c97 in _PyEval_EvalFrameDefault () from /usr/lib64/libpython3.6m.so.1.0
#19 0x00007ffff7c003c9 in ?? () from /usr/lib64/libpython3.6m.so.1.0
#20 0x00007ffff7c02c97 in _PyEval_EvalFrameDefault () from /usr/lib64/libpython3.6m.so.1.0
#21 0x00007ffff7c003c9 in ?? () from /usr/lib64/libpython3.6m.so.1.0
#22 0x00007ffff7c02c97 in _PyEval_EvalFrameDefault () from /usr/lib64/libpython3.6m.so.1.0
#23 0x00007ffff7c003c9 in ?? () from /usr/lib64/libpython3.6m.so.1.0
#24 0x00007ffff7c02c97 in _PyEval_EvalFrameDefault () from /usr/lib64/libpython3.6m.so.1.0
#25 0x00007ffff7c08a0f in _PyFunction_FastCallDict () from /usr/lib64/libpython3.6m.so.1.0
#26 0x00007ffff7b0c5ce in _PyObject_FastCallDict () from /usr/lib64/libpython3.6m.so.1.0
#27 0x00007ffff7b0d6c4 in _PyObject_CallMethodIdObjArgs () from /usr/lib64/libpython3.6m.so.1.0
#28 0x00007ffff7c22a81 in PyImport_ImportModuleLevelObject () from /usr/lib64/libpython3.6m.so.1.0
#29 0x00007ffff7c076f4 in _PyEval_EvalFrameDefault () from /usr/lib64/libpython3.6m.so.1.0
#30 0x00007ffff7bffdca in ?? () from /usr/lib64/libpython3.6m.so.1.0
#31 0x00007ffff7c0041f in PyEval_EvalCodeEx () from /usr/lib64/libpython3.6m.so.1.0
#32 0x00007ffff7c0044b in PyEval_EvalCode () from /usr/lib64/libpython3.6m.so.1.0
#33 0x00007ffff7bfd42d in ?? () from /usr/lib64/libpython3.6m.so.1.0
#34 0x00007ffff7b741f5 in PyCFunction_Call () from /usr/lib64/libpython3.6m.so.1.0
#35 0x00007ffff7c06f78 in _PyEval_EvalFrameDefault () from /usr/lib64/libpython3.6m.so.1.0
#36 0x00007ffff7bffdca in ?? () from /usr/lib64/libpython3.6m.so.1.0
#37 0x00007ffff7c00062 in ?? () from /usr/lib64/libpython3.6m.so.1.0
---Type <return> to continue, or q <return> to quit---
#38 0x00007ffff7c02c97 in _PyEval_EvalFrameDefault () from /usr/lib64/libpython3.6m.so.1.0
#39 0x00007ffff7c003c9 in ?? () from /usr/lib64/libpython3.6m.so.1.0
#40 0x00007ffff7c02c97 in _PyEval_EvalFrameDefault () from /usr/lib64/libpython3.6m.so.1.0
#41 0x00007ffff7c003c9 in ?? () from /usr/lib64/libpython3.6m.so.1.0
#42 0x00007ffff7c02c97 in _PyEval_EvalFrameDefault () from /usr/lib64/libpython3.6m.so.1.0
#43 0x00007ffff7c003c9 in ?? () from /usr/lib64/libpython3.6m.so.1.0
#44 0x00007ffff7c02c97 in _PyEval_EvalFrameDefault () from /usr/lib64/libpython3.6m.so.1.0
#45 0x00007ffff7c08a0f in _PyFunction_FastCallDict () from /usr/lib64/libpython3.6m.so.1.0
#46 0x00007ffff7b0c5ce in _PyObject_FastCallDict () from /usr/lib64/libpython3.6m.so.1.0
#47 0x00007ffff7b0d6c4 in _PyObject_CallMethodIdObjArgs () from /usr/lib64/libpython3.6m.so.1.0
#48 0x00007ffff7c22a81 in PyImport_ImportModuleLevelObject () from /usr/lib64/libpython3.6m.so.1.0
#49 0x00007ffff7bfbe34 in ?? () from /usr/lib64/libpython3.6m.so.1.0
#50 0x00007ffff7b74163 in PyCFunction_Call () from /usr/lib64/libpython3.6m.so.1.0
#51 0x00007ffff7c06f78 in _PyEval_EvalFrameDefault () from /usr/lib64/libpython3.6m.so.1.0
#52 0x00007ffff7bffdca in ?? () from /usr/lib64/libpython3.6m.so.1.0
#53 0x00007ffff7c00062 in ?? () from /usr/lib64/libpython3.6m.so.1.0
#54 0x00007ffff7c02c97 in _PyEval_EvalFrameDefault () from /usr/lib64/libpython3.6m.so.1.0
#55 0x00007ffff7c08a0f in _PyFunction_FastCallDict () from /usr/lib64/libpython3.6m.so.1.0
#56 0x00007ffff7b0c5ce in _PyObject_FastCallDict () from /usr/lib64/libpython3.6m.so.1.0
#57 0x00007ffff7b0d6c4 in _PyObject_CallMethodIdObjArgs () from /usr/lib64/libpython3.6m.so.1.0
#58 0x00007ffff7c22b41 in PyImport_ImportModuleLevelObject () from /usr/lib64/libpython3.6m.so.1.0
#59 0x00007ffff7c076f4 in _PyEval_EvalFrameDefault () from /usr/lib64/libpython3.6m.so.1.0
#60 0x00007ffff7bffdca in ?? () from /usr/lib64/libpython3.6m.so.1.0
#61 0x00007ffff7c0041f in PyEval_EvalCodeEx () from /usr/lib64/libpython3.6m.so.1.0
#62 0x00007ffff7c0044b in PyEval_EvalCode () from /usr/lib64/libpython3.6m.so.1.0
#63 0x00007ffff7bfd42d in ?? () from /usr/lib64/libpython3.6m.so.1.0
#64 0x00007ffff7b741f5 in PyCFunction_Call () from /usr/lib64/libpython3.6m.so.1.0
#65 0x00007ffff7c06f78 in _PyEval_EvalFrameDefault () from /usr/lib64/libpython3.6m.so.1.0
#66 0x00007ffff7bffdca in ?? () from /usr/lib64/libpython3.6m.so.1.0
#67 0x00007ffff7c00062 in ?? () from /usr/lib64/libpython3.6m.so.1.0
#68 0x00007ffff7c02c97 in _PyEval_EvalFrameDefault () from /usr/lib64/libpython3.6m.so.1.0
#69 0x00007ffff7c003c9 in ?? () from /usr/lib64/libpython3.6m.so.1.0
#70 0x00007ffff7c02c97 in _PyEval_EvalFrameDefault () from /usr/lib64/libpython3.6m.so.1.0
#71 0x00007ffff7c003c9 in ?? () from /usr/lib64/libpython3.6m.so.1.0
#72 0x00007ffff7c02c97 in _PyEval_EvalFrameDefault () from /usr/lib64/libpython3.6m.so.1.0
#73 0x00007ffff7c003c9 in ?? () from /usr/lib64/libpython3.6m.so.1.0
#74 0x00007ffff7c02c97 in _PyEval_EvalFrameDefault () from /usr/lib64/libpython3.6m.so.1.0
#75 0x00007ffff7c08a0f in _PyFunction_FastCallDict () from /usr/lib64/libpython3.6m.so.1.0
#76 0x00007ffff7b0c5ce in _PyObject_FastCallDict () from /usr/lib64/libpython3.6m.so.1.0
#77 0x00007ffff7b0d6c4 in _PyObject_CallMethodIdObjArgs () from /usr/lib64/libpython3.6m.so.1.0
#78 0x00007ffff7c22a81 in PyImport_ImportModuleLevelObject () from /usr/lib64/libpython3.6m.so.1.0
#79 0x00007ffff7c076f4 in _PyEval_EvalFrameDefault () from /usr/lib64/libpython3.6m.so.1.0
#80 0x00007ffff7bffdca in ?? () from /usr/lib64/libpython3.6m.so.1.0
---Type <return> to continue, or q <return> to quit---
#81 0x00007ffff7c0041f in PyEval_EvalCodeEx () from /usr/lib64/libpython3.6m.so.1.0
#82 0x00007ffff7c0044b in PyEval_EvalCode () from /usr/lib64/libpython3.6m.so.1.0
#83 0x00007ffff7c33b8f in PyRun_StringFlags () from /usr/lib64/libpython3.6m.so.1.0
#84 0x00007ffff7c33c0b in PyRun_SimpleStringFlags () from /usr/lib64/libpython3.6m.so.1.0
#85 0x00007ffff7c52266 in Py_Main () from /usr/lib64/libpython3.6m.so.1.0
#86 0x0000000000400b1e in main ()
```

**Comment by arteze** [comment]
I already fixed that part, now I have another error:

```sh
gd2 python3 -c "import matplotlib"
GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python3...(no debugging symbols found)...done.
Starting program: /usr/bin/python3 -c import\ matplotlib
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xa
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib64/python3.6/site-packages/matplotlib/__init__.py", line 174, in <module>
    _check_versions()
  File "/usr/lib64/python3.6/site-packages/matplotlib/__init__.py", line 159, in _check_versions
    from . import ft2font
ImportError: numpy.core.multiarray failed to import
[Inferior 1 (process 23581) exited with code 01]
(gdb) bt
No stack.
```

**Comment by jklymak** [comment]
Please take this discussion to discourse.Matplotlib.org.  You are not installing all the dependencies, which is not a bug to report here.  Thanks for your understanding.

**Comment by tacaswell** [comment]
xref: https://github.com/matplotlib/matplotlib/issues/20158

I suspect you either have a (numpy?) wheel built with extensions that your system does not support (many linux is not all linux), or have an otherwise broken numpy install.  Try building everything from source?

https://discourse.matplotlib.org/c/community/install/13 is probably the best topic target.

**Comment by arteze** [comment]
@tacaswell Now yes, I have seen the xref and it was solved with this command, I do not need to publish in the forum.

```sh
pip install numpy==1.19.4
```
Thanks.
