### ISSUE TITLE
Build error on M1 Macbook (while building freetype): "Invalid configuration `arm64-apple-darwin20.5.0': machine `arm64-apple' not recognized"

### ISSUE THREAD

**Issue by ryan-williams** [matplotlib/matplotlib#20661]
### Bug summary
On my M1 Macbook, running `pip install matplotlib` (or `pip install -e .` from a clone at `v3.4.2`) fails due to a failure while building freetype:

```bash
git clone https://github.com/matplotlib/matplotlib.git \
 && cd matplotlib \
 && git checkout v3.4.2

pip install -e .  # ❌ fails 
```
<details><summary>Full output</summary>

```
Obtaining file:///Users/ryan/c/matplotlib
Requirement already satisfied: cycler>=0.10 in /Users/ryan/.pyenv/versions/3.9.5/lib/python3.9/site-packages (from matplotlib==3.4.2) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /Users/ryan/.pyenv/versions/3.9.5/lib/python3.9/site-packages (from matplotlib==3.4.2) (1.1.0)
Requirement already satisfied: numpy>=1.16 in /Users/ryan/.pyenv/versions/3.9.5/lib/python3.9/site-packages (from matplotlib==3.4.2) (1.21.0)
Requirement already satisfied: pillow>=6.2.0 in /Users/ryan/.pyenv/versions/3.9.5/lib/python3.9/site-packages (from matplotlib==3.4.2) (8.3.1)
Requirement already satisfied: pyparsing>=2.2.1 in /Users/ryan/.pyenv/versions/3.9.5/lib/python3.9/site-packages (from matplotlib==3.4.2) (2.4.7)
Requirement already satisfied: python-dateutil>=2.7 in /Users/ryan/.pyenv/versions/3.9.5/lib/python3.9/site-packages (from matplotlib==3.4.2) (2.8.1)
Requirement already satisfied: six in /Users/ryan/.pyenv/versions/3.9.5/lib/python3.9/site-packages (from cycler>=0.10->matplotlib==3.4.2) (1.16.0)
Requirement already satisfied: setuptools in /Users/ryan/.pyenv/versions/3.9.5/lib/python3.9/site-packages (from kiwisolver>=1.0.1->matplotlib==3.4.2) (56.0.0)
Installing collected packages: matplotlib
  Running setup.py develop for matplotlib
    ERROR: Command errored out with exit status 1:
     command: /Users/ryan/.pyenv/versions/3.9.5/bin/python3.9 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/ryan/c/matplotlib/setup.py'"'"'; __file__='"'"'/Users/ryan/c/matplotlib/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /Users/ryan/c/matplotlib/
    Complete output (107 lines):

    Edit setup.cfg to change the build options; suppress output with --quiet.

    BUILDING MATPLOTLIB
      matplotlib: yes [3.4.2]
          python: yes [3.9.5 (default, Jun 24 2021, 18:26:31)  [Clang 12.0.5
                      (clang-1205.0.22.9)]]
        platform: yes [darwin]
           tests: no  [skipping due to configuration]
          macosx: yes [installing]

    running develop
    running egg_info
    creating lib/matplotlib.egg-info
    writing lib/matplotlib.egg-info/PKG-INFO
    writing dependency_links to lib/matplotlib.egg-info/dependency_links.txt
    writing namespace_packages to lib/matplotlib.egg-info/namespace_packages.txt
    writing requirements to lib/matplotlib.egg-info/requires.txt
    writing top-level names to lib/matplotlib.egg-info/top_level.txt
    writing manifest file 'lib/matplotlib.egg-info/SOURCES.txt'
    reading manifest file 'lib/matplotlib.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '*' found under directory 'lib/matplotlib/backends/web_backend/node_modules'
    writing manifest file 'lib/matplotlib.egg-info/SOURCES.txt'
    running build_ext
    creating var
    creating var/folders
    creating var/folders/dc
    creating var/folders/dc/gqj_cd8d0d9c1nppd5_yl7bc0000gn
    creating var/folders/dc/gqj_cd8d0d9c1nppd5_yl7bc0000gn/T
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Users/ryan/.pyenv/versions/3.9.5/include/python3.9 -c /var/folders/dc/gqj_cd8d0d9c1nppd5_yl7bc0000gn/T/tmpa86yidw7.cpp -o var/folders/dc/gqj_cd8d0d9c1nppd5_yl7bc0000gn/T/tmpa86yidw7.o -fvisibility=hidden
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Users/ryan/.pyenv/versions/3.9.5/include/python3.9 -c /var/folders/dc/gqj_cd8d0d9c1nppd5_yl7bc0000gn/T/tmpbf7gp55v.cpp -o var/folders/dc/gqj_cd8d0d9c1nppd5_yl7bc0000gn/T/tmpbf7gp55v.o -fvisibility-inlines-hidden
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Users/ryan/.pyenv/versions/3.9.5/include/python3.9 -c /var/folders/dc/gqj_cd8d0d9c1nppd5_yl7bc0000gn/T/tmpjhbnhqxk.cpp -o var/folders/dc/gqj_cd8d0d9c1nppd5_yl7bc0000gn/T/tmpjhbnhqxk.o -flto

    FreeType build system -- automatic system detection

    The following settings are used:

      platform                    unix
      compiler                    cc
      configuration directory     ./builds/unix
      configuration rules         ./builds/unix/unix.mk

    If this does not correspond to your system or settings please remove the file
    `config.mk' from this directory then read the INSTALL file for help.

    Otherwise, simply type `/Library/Developer/CommandLineTools/usr/bin/make' again to build the library,
    or `/Library/Developer/CommandLineTools/usr/bin/make refdoc' to build the API reference (this needs python >= 2.6).

    Generating modules list in ./objs/ftmodule.h...
    * module: truetype  (Windows/Mac font files with extension *.ttf or *.ttc)
    * module: type1     (Postscript font files with extension *.pfa or *.pfb)
    * module: cff       (OpenType fonts with extension *.otf)
    * module: cid       (Postscript CID-keyed fonts, no known extension)
    * module: pfr       (PFR/TrueDoc font files with extension *.pfr)
    * module: type42    (Type 42 font files with no known extension)
    * module: winfnt    (Windows bitmap fonts with extension *.fnt or *.fon)
    * module: pcf       (pcf bitmap fonts)
    * module: bdf       (bdf bitmap fonts)
    * module: sfnt      (helper module for TrueType & OpenType formats)
    * module: autofit   (automatic hinting module)
    * module: pshinter  (Postscript hinter module)
    * module: raster    (monochrome bitmap renderer)
    * module: smooth    (anti-aliased bitmap renderer)
    * module: smooth    (anti-aliased bitmap renderer for LCDs)
    * module: smooth    (anti-aliased bitmap renderer for vertical LCDs)
    * module: psaux     (Postscript Type 1 & Type 2 helper module)
    * module: psnames   (Postscript & Unicode Glyph name handling)
    done.
    cd builds/unix; \
    	        ./configure  '--with-zlib=no' '--with-bzip2=no' '--with-png=no' '--with-harfbuzz=no' '--enable-static' '--disable-shared'
    checking build system type... Invalid configuration `arm64-apple-darwin20.5.0': machine `arm64-apple' not recognized
    configure: error: /bin/sh ./config.sub arm64-apple-darwin20.5.0 failed
    make: *** [setup] Error 1
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/ryan/c/matplotlib/setup.py", line 258, in <module>
        setup(  # Finally, pass this all along to distutils to do the heavy lifting.
      File "/Users/ryan/.pyenv/versions/3.9.5/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/Users/ryan/.pyenv/versions/3.9.5/lib/python3.9/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Users/ryan/.pyenv/versions/3.9.5/lib/python3.9/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/Users/ryan/.pyenv/versions/3.9.5/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Users/ryan/.pyenv/versions/3.9.5/lib/python3.9/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/Users/ryan/.pyenv/versions/3.9.5/lib/python3.9/site-packages/setuptools/command/develop.py", line 136, in install_for_development
        self.run_command('build_ext')
      File "/Users/ryan/.pyenv/versions/3.9.5/lib/python3.9/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Users/ryan/.pyenv/versions/3.9.5/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Users/ryan/.pyenv/versions/3.9.5/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/Users/ryan/.pyenv/versions/3.9.5/lib/python3.9/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/Users/ryan/c/matplotlib/setup.py", line 199, in build_extensions
        package.do_custom_build(env)
      File "/Users/ryan/c/matplotlib/setupext.py", line 596, in do_custom_build
        subprocess.check_call(
      File "/Users/ryan/.pyenv/versions/3.9.5/lib/python3.9/subprocess.py", line 373, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['./configure', '--with-zlib=no', '--with-bzip2=no', '--with-png=no', '--with-harfbuzz=no', '--enable-static', '--disable-shared']' returned non-zero exit status 2.
    Extracting /project/freetype/freetype2/2.6.1/freetype-2.6.1.tar.gz
    Building freetype in build/freetype-2.6.1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/ryan/.pyenv/versions/3.9.5/bin/python3.9 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/ryan/c/matplotlib/setup.py'"'"'; __file__='"'"'/Users/ryan/c/matplotlib/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
```
</details>

This appears to be the salient bit (run inside `build/freetype-2.6.1/`):
```
cd builds/unix; \
    	        ./configure  '--with-zlib=no' '--with-bzip2=no' '--with-png=no' '--with-harfbuzz=no' '--enable-static' '--disable-shared'
    checking build system type... Invalid configuration `arm64-apple-darwin20.5.0': machine `arm64-apple' not recognized
    configure: error: /bin/sh ./config.sub arm64-apple-darwin20.5.0 failed
    make: *** [setup] Error 1
```

I see the same thing on Python 3.7.10, 3.8.10, and 3.9.5.

### Workaround: `system_freetype = True`
I already have Freetype installed on my system (via `brew install freetype`), so this fixes it:
```bash
# In MPL root directory
echo '[libs]
system_freetype = True
' > setup.cfg

pip install -e .  # ✅ works
```

#### Setting `system_freetype = True` via an environment variable?
I originally ran into this while trying to install a different library, which depends on matplotlib. Is there a way to e.g. export an environment variable so that when I `pip install -e .` in a library that depends on MPL, `system_freetype = True` is passed to the MPL build?

For now, in the other library, I can just do:
```bash
pip install -e <path to my MPL clone, with custom setup.cfg as above>
pip install -e .  # library that depends on MPL
```

but it would be nice to not have to jump through that hoop.

#### Automatically set (or fall back to?) `system_freetype = True`
If the freetype build fails, and freetype is detected on the system, maybe MPL could automatically infer `system_freetype = True`.

#### Debug why freetype build fails
If anyone knows why freetype is failing with `Invalid configuration `arm64-apple-darwin20.5.0': machine `arm64-apple' not recognized`, that would also be good to understand and try to fix. Thanks.

**Comment by anntzer** [comment]
> Setting system_freetype = True via an environment variable?

You can set MPLSETUPCFG to point to the path of a setup.cfg file that will be used by setup.py (in your case, it would have contents like
```cfg
[libs]
system_freetype = true
```
)
Note that this file can be anywhere in your filesystem.

**Comment by ryan-williams** [comment]
To summarize, since I've had to do this a few times now in different virtualenvs:
```bash
# Write setup.cfg
echo '[libs]
system_freetype = True
' > setup.cfg

# Let matplotlib's install process find it
export MPLSETUPCFG=$PWD/setup.cfg

# pip install now works
pip install matplotlib
```

Open questions:
1. Can MPL detect and do this automatically (on M1 Mac's specifically, or in the case that it tries to install freetype, fails, and notices it's on an M1 with system freetype)?
2. Can/should freetype build properly (even if it is redundant since system freetype exists)? This is presumably out of scope for MPL (unless MPL's invocation of the freetype build can be tweaked to work around or fix the issue), just mentioning for completeness.

**Comment by dopplershift** [comment]
👍 from me on making our `setup.py` detect M1 and set using the system freetype. Right now a major platform is guaranteed to fail to build with the default settings.

I'm not particularly hopeful about us making our pinned copy compile on M1.

**Comment by QuLogic** [comment]
But we need to build wheels so that people don't need to compile at all, so we need to get it working anyway.

**Comment by dopplershift** [comment]
I think it's 50-50 whether the end solution to that is getting freetype 2.6.1 to build or moving to >=2.10. But I've not looked in detail at the current problem with freetype 2.6 building on M1.

**Comment by dstansby** [comment]
On a recent commit on the `main` branch, I can run `python setup.py develop` on a M1 chip fine, and with the output confirming that freetype is compiled fine. @ryan-williams is this still an issue for you? If so perhaps we can try and pin down what's making it work for me and not for you.

**Comment by tacaswell** [comment]
I wonder if this is autotools updating under us?

**Comment by QuLogic** [comment]
We already produce arm64 and universal2 wheels for 3.5.0+, so this should definitely be working now. Please re-open if you still have issues on the latest version.
