### ISSUE TITLE
[Bug]: Colorbar creation from pcolormesh with cell specific alpha values

### ISSUE THREAD

**Issue by kfbz9246** [matplotlib/matplotlib#20785]
### Bug summary

When I try to take advantage of the new ability to set cell specific alpha values in pcolormesh -
 
https://matplotlib.org/stable/users/whats_new.html#transparency-alpha-can-be-set-as-an-array-in-collections

and then use the resulting QuadMesh object to create a colorbar it generates an error detailed below.

### Code for reproduction

```python
from numpy import arange, ones_like, newaxis, linspace
import matplotlib.pyplot as plt
from matplotlib.pyplot import figure, close
from seaborn import heatmap

x = arange(5, dtype=float)
y = arange(5, dtype=float)
# z and zalpha for demo pcolormesh
z = x[1:, newaxis] + y[newaxis, 1:]


zalpha = ones_like(z)
zalpha[::2, ::2] = 0.3  # alternate patches are partly transparent


fig = figure(figsize=(11, 7), dpi=300, frameon=True, tight_layout=True)
fig_ax = fig.add_subplot(111)


mesh = fig_ax.pcolormesh(x, y, z, alpha=zalpha)
fig.colorbar(mesh)

fig.savefig('foo.png')
```

### Actual outcome

```
Singularity> python3 scratch.py 
Traceback (most recent call last):
  File "scratch.py", line 28, in <module>
    fig.savefig('foo.png')
  File "/home/kz245/.local/lib/python3.8/site-packages/matplotlib/figure.py", line 3005, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/kz245/.local/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 2255, in print_figure
    result = print_method(
  File "/home/kz245/.local/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 1669, in wrapper
    return func(*args, **kwargs)
  File "/home/kz245/.local/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py", line 508, in print_png
    FigureCanvasAgg.draw(self)
  File "/home/kz245/.local/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py", line 406, in draw
    self.figure.draw(self.renderer)
  File "/home/kz245/.local/lib/python3.8/site-packages/matplotlib/artist.py", line 74, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/home/kz245/.local/lib/python3.8/site-packages/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/kz245/.local/lib/python3.8/site-packages/matplotlib/figure.py", line 2780, in draw
    mimage._draw_list_compositing_images(
  File "/home/kz245/.local/lib/python3.8/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/kz245/.local/lib/python3.8/site-packages/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/kz245/.local/lib/python3.8/site-packages/matplotlib/_api/deprecation.py", line 431, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/home/kz245/.local/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 2921, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/home/kz245/.local/lib/python3.8/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/kz245/.local/lib/python3.8/site-packages/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/kz245/.local/lib/python3.8/site-packages/matplotlib/collections.py", line 2101, in draw
    self.update_scalarmappable()
  File "/home/kz245/.local/lib/python3.8/site-packages/matplotlib/collections.py", line 916, in update_scalarmappable
    raise ValueError(
ValueError: Data array shape, (256,) is incompatible with alpha array shape, (4, 4). This can occur with the deprecated behavior of the "flat" shading option, in which a row and/or column of the data array is dropped.
```

### Expected outcome

A heat-map with a color bar beside it.

### Operating system

Ubuntu inside singularity container

### Matplotlib Version

3.4.2

### Matplotlib Backend

agg

### Python version

3.8.5

### Jupyter version

not used

### Other libraries

none

### Installation

pip

**Comment by greglucas** [comment]
xref: #19843, but from a different collection object.

**Comment by jklymak** [comment]
Colorbars do a 1d mapping.  This is a 2d mapping.  What do we want the colorbar to look like?

**Comment by kfbz9246** [comment]
The use case I have in mind is using the color to encode the estimated value and the alpha to encode pvlaue so the colorbar can just display the colors as it would have before.

**Comment by kfbz9246** [comment]
How do I install that commit to test out the fix?  I downloaded the code in the commit from  - 
https://github.com/greglucas/matplotlib/archive/refs/heads/cbar-2d-alpha.zip

and then try to install it with python -m pip install -e . as suggested in the installing from source link -
https://matplotlib.org/stable/users/installing_source.html#install-from-source

but it complains:
packaging.version.InvalidVersion: Invalid version: '2d-alpha'

What am I mission?  Sorry

**Comment by jklymak** [comment]
clone the matplotlib repository (all of it), and then use the gh command line tool to checkout #20788.  Then `pip install -e .`.  I'm not sure what the zip downloads for you.

**Comment by kfbz9246** [comment]
Ok that all checks out on my end and works the way I was expecting it to!  I'm not that familiar with matplotlib's release schedule, when will this show up in a main release?  Thanks so much for your help on this and for fixing the issue so quickly!

**Comment by jklymak** [comment]
Thanks for checking.   Expect 3.5 before end of Sept. we hope

**Comment by kfbz9246** [comment]
Awesome, thanks again, and this can be closed out as far as I'm concerned!
