### ISSUE TITLE
[Bug]: Second call to .use() causes recursion error

### ISSUE THREAD

**Issue by oliversheridanmethven** [matplotlib/matplotlib#20808]
### Bug summary

Repeated calls to mpl.use() causes a recursion error. 

### Code for reproduction

```python
import matplotlib as mpl
mpl.use("TkAgg")
import matplotlib.pylab as plt
mpl.use("TkAgg")
```

### Actual outcome

Using Python 3.9.6 and matplotlib version 3.4.2 on Mac OSX, this:
```
import matplotlib as mpl
mpl.use("TkAgg")
import matplotlib.pylab as plt
mpl.use("TkAgg")
```
gives:
```
Backend TkAgg is interactive backend. Turning interactive mode on.
Traceback (most recent call last):
  File "<input>", line 4, in <module>
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydev_ipython/matplotlibtools.py", line 70, in patched_use
    matplotlib.real_use(*args, **kwargs)
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydev_ipython/matplotlibtools.py", line 70, in patched_use
    matplotlib.real_use(*args, **kwargs)
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydev_ipython/matplotlibtools.py", line 70, in patched_use
    matplotlib.real_use(*args, **kwargs)
  [Previous line repeated 987 more times]
RecursionError: maximum recursion depth exceeded
```

### Expected outcome

No error. 

### Operating system

OSX

### Matplotlib Version

3.4.2

### Installation

pip

**Comment by jklymak** [comment]
Can you try this without pycharm?

**Comment by jklymak** [comment]
I believe this is a pycharm issue: https://github.com/fabioz/PyDev.Debugger/issues/148 and will close here.  They patch our `matplotlib.use`.
