### ISSUE TITLE
[Bug]: ImportError: cannot import name 'animation' from partially initialized module 'matplotlib' (most likely due to a circular import)

### ISSUE THREAD

**Issue by hugoabreu1002** [matplotlib/matplotlib#20824]
### Bug summary

Error in importing matplotlib,

I saw that this error was fixed before...

### Code for reproduction

```python
import matplotlib.pyplot as plt
```

### Actual outcome

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\hugow\AppData\Roaming\Python\Python38\site-packages\matplotlib\__init__.py", line 107, in <module>
    from . import _api, cbook, docstring, rcsetup
  File "C:\Users\hugow\AppData\Roaming\Python\Python38\site-packages\matplotlib\rcsetup.py", line 24, in <module>
    from matplotlib import _api, animation, cbook
ImportError: cannot import name 'animation' from partially initialized module 'matplotlib' (most likely due to a circular import)

### Expected outcome

import correctly

### Operating system

Windows 10

### Matplotlib Version

3.4.2

### Python version

3.8.7

### Jupyter version

6.4.0

**Comment by hugoabreu1002** [comment]
Worked by removing completely all files related to matplotlib and reinstalling with pip
