### ISSUE TITLE
[Bug]: when respond about 20 times of key_press_event under interactive pyplot, will crash and can't respond.

### ISSUE THREAD

**Issue by TheGreatGalaxy** [matplotlib/matplotlib#21344]
### Bug summary

 when respond about 20 times of key_press_event under interactive pyplot, will appear 'RecursionError: maximum recursion depth exceeded while calling a Python object' and can't respond. what action triggered by key press event is to draw the last or new figure after calling "fig.clf(keep_observers=True)"

### Code for reproduction

```python
def PressKeyUpdate(self, event):
        if event.key not in ["left", "right"]:
            return
        if event.key == "left":
            if self.percep_idx <= 1:
                return
            self.percep_idx -= 1
            self.PlotPercepFrame(
                self.percep_res[self.percep_idx], self.percep_res[self.percep_idx - 1])
        else:
            if self.percep_idx < len(self.percep_res) - 1:
                self.percep_idx += 1
                self.PlotPercepFrame(
                    self.percep_res[self.percep_idx], self.percep_res[self.percep_idx - 1])


    def PlotPercepFrame(self, percep_frame, last_percep_frame, is_key_event=True):
        if not percep_frame:
            logging.error("Input percep_frame is None!")
            return
        if len(percep_frame.objs) == 0:
            logging.info("This frame has zero perception tracking! Will skip frame "
                         + str(percep_frame.header.lidar_timestamp))
            return
        last_xlimit = self.ax.get_xlim()
        last_ylimit = self.ax.get_ylim()
        if is_key_event:
            self.fig.clf(keep_observers=True)
            self.ax = self.fig.add_subplot()
         '''draw somthing'''
        self.fig.canvas.set_window_title('Perception Debug')
        self.fig.canvas.draw()
```

### Actual outcome

Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/backends/_backend_tk.py", line 378, in key_press
    FigureCanvasBase.key_press_event(self, key, guiEvent=event)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/backend_bases.py", line 1794, in key_press_event
    self.callbacks.process(s, event)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/cbook/__init__.py", line 229, in process
    self.exception_handler(exc)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/cbook/__init__.py", line 81, in _exception_printer
    raise exc
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/cbook/__init__.py", line 224, in process
    func(*args, **kwargs)
  File "/apollo/bazel-bin/yw_core/perception/debug/analyzer.runfiles/apollo/yw_core/perception/debug/analyzer.py", line 291, in PressKeyUpdate
    self.percep_res[self.percep_idx], self.percep_res[self.percep_idx - 1])
  File "/apollo/bazel-bin/yw_core/perception/debug/analyzer.runfiles/apollo/yw_core/perception/debug/analyzer.py", line 304, in PlotPercepFrame
    self.fig.clf(keep_observers=True)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/figure.py", line 1795, in clf
    ax.cla()
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/axes/_base.py", line 1055, in cla
    spine.cla()
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/spines.py", line 238, in cla
    self.axis.cla()
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/axis.py", line 788, in cla
    self.reset_ticks()
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/axis.py", line 811, in reset_ticks
    self.set_clip_path(self.axes.patch)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/axis.py", line 901, in set_clip_path
    for child in self.majorTicks + self.minorTicks:
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/axis.py", line 618, in __get__
    tick = instance._get_tick(major=True)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/axis.py", line 2306, in _get_tick
    return YTick(self.axes, 0, major=major, **tick_kw)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/axis.py", line 494, in __init__
    transform=self.axes.get_yaxis_transform(which="tick1"),
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/axes/_base.py", line 793, in get_yaxis_transform
    return self.spines['left'].get_spine_transform()
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/spines.py", line 393, in get_spine_transform
    self._ensure_position_is_set()
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/spines.py", line 219, in _ensure_position_is_set
    self.set_position(self._position)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/spines.py", line 383, in set_position
    self.axis.reset_ticks()
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/axis.py", line 811, in reset_ticks
    self.set_clip_path(self.axes.patch)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/axis.py", line 901, in set_clip_path
    for child in self.majorTicks + self.minorTicks:
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/axis.py", line 618, in __get__
    tick = instance._get_tick(major=True)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/axis.py", line 2306, in _get_tick
    return YTick(self.axes, 0, major=major, **tick_kw)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/axis.py", line 490, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/cbook/deprecation.py", line 411, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/axis.py", line 147, in __init__
    self.apply_tickdir(tickdir)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/axis.py", line 536, in apply_tickdir
    self.stale = True
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/artist.py", line 224, in stale
    self.stale_callback(self, val)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/artist.py", line 54, in _stale_axes_callback
    self.axes.stale = val
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/artist.py", line 224, in stale
    self.stale_callback(self, val)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/figure.py", line 44, in _stale_figure_callback
    self.figure.stale = val
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/artist.py", line 224, in stale
    self.stale_callback(self, val)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/pyplot.py", line 725, in _auto_draw_if_interactive
    if (val and matplotlib.is_interactive()
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/__init__.py", line 1209, in is_interactive
    return rcParams['interactive']
RecursionError: maximum recursion depth exceeded while calling a Python object
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/backends/_backend_tk.py", line 378, in key_press
    FigureCanvasBase.key_press_event(self, key, guiEvent=event)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/backend_bases.py", line 1794, in key_press_event
    self.callbacks.process(s, event)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/cbook/__init__.py", line 229, in process
    self.exception_handler(exc)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/cbook/__init__.py", line 81, in _exception_printer
    raise exc
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/cbook/__init__.py", line 224, in process
    func(*args, **kwargs)
  File "/apollo/bazel-bin/yw_core/perception/debug/analyzer.runfiles/apollo/yw_core/perception/debug/analyzer.py", line 291, in PressKeyUpdate
    self.percep_res[self.percep_idx], self.percep_res[self.percep_idx - 1])
  File "/apollo/bazel-bin/yw_core/perception/debug/analyzer.runfiles/apollo/yw_core/perception/debug/analyzer.py", line 304, in PlotPercepFrame
    self.fig.clf(keep_observers=True)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/figure.py", line 1795, in clf
    ax.cla()
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/axes/_base.py", line 1055, in cla
    spine.cla()
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/spines.py", line 238, in cla
    self.axis.cla()
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/axis.py", line 788, in cla
    self.reset_ticks()
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/axis.py", line 811, in reset_ticks
    self.set_clip_path(self.axes.patch)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/axis.py", line 901, in set_clip_path
    for child in self.majorTicks + self.minorTicks:
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/axis.py", line 618, in __get__
    tick = instance._get_tick(major=True)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/axis.py", line 2306, in _get_tick
    return YTick(self.axes, 0, major=major, **tick_kw)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/axis.py", line 494, in __init__
    transform=self.axes.get_yaxis_transform(which="tick1"),
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/axes/_base.py", line 793, in get_yaxis_transform
    return self.spines['left'].get_spine_transform()
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/spines.py", line 393, in get_spine_transform
    self._ensure_position_is_set()
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/spines.py", line 219, in _ensure_position_is_set
    self.set_position(self._position)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/spines.py", line 383, in set_position
    self.axis.reset_ticks()
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/axis.py", line 811, in reset_ticks
    self.set_clip_path(self.axes.patch)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/axis.py", line 901, in set_clip_path
    for child in self.majorTicks + self.minorTicks:
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/axis.py", line 618, in __get__
    tick = instance._get_tick(major=True)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/axis.py", line 2306, in _get_tick
    return YTick(self.axes, 0, major=major, **tick_kw)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/axis.py", line 490, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/cbook/deprecation.py", line 411, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/axis.py", line 147, in __init__
    self.apply_tickdir(tickdir)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/axis.py", line 536, in apply_tickdir
    self.stale = True
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/artist.py", line 224, in stale
    self.stale_callback(self, val)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/artist.py", line 54, in _stale_axes_callback
    self.axes.stale = val
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/artist.py", line 224, in stale
    self.stale_callback(self, val)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/figure.py", line 44, in _stale_figure_callback
    self.figure.stale = val
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/artist.py", line 224, in stale
    self.stale_callback(self, val)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/pyplot.py", line 725, in _auto_draw_if_interactive
    if (val and matplotlib.is_interactive()
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/__init__.py", line 1209, in is_interactive
    return rcParams['interactive']
RecursionError: maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):
  File "/apollo/bazel-bin/yw_core/perception/debug/analyzer.runfiles/apollo/yw_core/perception/debug/analyzer.py", line 469, in <module>
    reader.PlotPerceptionFrameFromTrackId(args)
  File "/apollo/bazel-bin/yw_core/perception/debug/analyzer.runfiles/apollo/yw_core/perception/debug/analyzer.py", line 251, in PlotPerceptionFrameFromTrackId
    self.PlotPerceptionFrameFromFrameIdx(args)
  File "/apollo/bazel-bin/yw_core/perception/debug/analyzer.runfiles/apollo/yw_core/perception/debug/analyzer.py", line 276, in PlotPerceptionFrameFromFrameIdx
    self.percep_res[self.percep_idx], self.percep_res[self.percep_idx - 1], False)
  File "/apollo/bazel-bin/yw_core/perception/debug/analyzer.runfiles/apollo/yw_core/perception/debug/analyzer.py", line 424, in PlotPercepFrame
    self.fig.canvas.set_window_title('Perception Debug')
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/backend_bases.py", line 2252, in set_window_title
    self.manager.set_window_title(title)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/backends/_backend_tk.py", line 477, in set_window_title
    self.window.wm_title(title)
AttributeError: 'NoneType' object has no attribute 'wm_title'

### Expected outcome

should draw normally after any times of key press event.

### Operating system

Ubuntu 18.04

### Matplotlib Version

3.3.4

### Matplotlib Backend

'TkAgg'

### Python version

3.6.9

### Installation

pip

**Comment by jklymak** [comment]
Please concoct something minimal and self-contained, otherwise it is really hard for us to guess what the problem may be.

**Comment by TheGreatGalaxy** [comment]
> Please concoct something minimal and self-contained, otherwise it is really hard for us to guess what the problem may be.

Sorry， i didn't understand you. The actual come is the whole trace back.
The core code is what i pasted. Just plot and clear and plot. The new draw is triggered by left and right key.

**Comment by jklymak** [comment]
We cannot run your code as-is.  Please see http://sscce.org.  For all we know your error arises due to other parts of your code that you have not shown us.

**Comment by TheGreatGalaxy** [comment]
@jklymak @tacaswell I am running the attaching code in Apollo docker "https://github.com/ApolloAuto/apollo", and can reproduce the issue every single time. But i can't reproduce the issue by running the scripts outside of docker. Can you try it? Thanks.
The command: `python3 analyzer_debug.py `
The action: press Left or Right key in keyboard for many times
[analyzer_debug.txt](https://github.com/matplotlib/matplotlib/files/7361594/analyzer_debug.txt)
..

**Comment by jklymak** [comment]
That file is 155 lines, most of which seems extraneous to the problem, though maybe I am mistaken.

**Comment by TheGreatGalaxy** [comment]
Sorry for not understanding you well. I have extracted the script from a very large project. I thought the script is small, but actually not for you. Well, now i have minimized it:
`
#!/usr/bin/env python3

import matplotlib.pyplot as plt
import matplotlib
import numpy as np
matplotlib.use('TkAgg')


fig = plt.figure()
ax = fig.add_subplot()

def PressKeyUpdate(event):
        if event.key not in ["left", "right"]:
            return
        if event.key == "left":
            PlotPercepFrame()
        else:
            PlotPercepFrame()

def PlotPercepFrame(is_key_event=True):
    global ax
    global fig
    if is_key_event:
        fig.clf(keep_observers=True)
        ax = fig.add_subplot()
    ax.plot(np.random.rand(4), np.random.rand(4))
    ax.grid()
    fig.canvas.draw()
    plt.show()

fig.canvas.mpl_connect('key_press_event', PressKeyUpdate)
PlotPercepFrame(False)
`
I can reproduce it by python3.6.9. But can't reproduce by python3.8. So i think it maybe a bug.

**Comment by jklymak** [comment]
On my mac, python 3.9.7 this works as expected.  My guess would be this was a Tk bug that has subsequently been fixed.  Given that this works on more modern python/tK, is there an action item for us?
