### ISSUE TITLE
[Bug]: 3.4.3 can't be installed on Python 3.10

### ISSUE THREAD

**Issue by PerchunPak** [matplotlib/matplotlib#21347]
### Bug summary

Title

### Code for reproduction

```python
pip install matplotlib==3.4.3
```

### Actual outcome

```
Collecting matplotlib==3.4.3
  Using cached matplotlib-3.4.3.tar.gz (37.9 MB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\perch\Desktop\programming\PingerBot\venv\Scripts\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\perch\\AppData\\Local\\Temp\\pip-install-suadel9_\\matplotlib_4425044c99d5442ab5133bc5ee3d22aa\\setup.py'"'"'; __file__='"'"'C:\\Users\\perch\\AppData\\Local\\Temp\\pip-install-suadel9_\\matplotlib_4425044c99d5442ab5133bc5ee3d22aa\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\perch\AppData\Local\Temp\pip-pip-egg-info-pz459q62'
       cwd: C:\Users\perch\AppData\Local\Temp\pip-install-suadel9_\matplotlib_4425044c99d5442ab5133bc5ee3d22aa\
  Complete output (248 lines):
  
  Edit setup.cfg to change the build options; suppress output with --quiet.
  
  BUILDING MATPLOTLIB
    matplotlib: yes [3.4.3]
        python: yes [3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC
                    v.1929 64 bit (AMD64)]]
      platform: yes [win32]
         tests: no  [skipping due to configuration]
        macosx: no  [Mac OS-X only]
  
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\perch\Desktop\programming\PingerBot\venv\Scripts\python.exe' 'C:\Users\perch\Desktop\programming\PingerBot\venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' build_wheel 'C:\Users\perch\AppData\Local\Temp\tmpjt4buajd'
         cwd: C:\Users\perch\AppData\Local\Temp\pip-wheel-5rgbkagq\numpy_7b4d8026a8794fbba06577e80a90fab8
    Complete output (200 lines):
    setup.py:63: RuntimeWarning: NumPy 1.21.2 may not yet support Python 3.10.
      warnings.warn(
    Running from numpy source directory.
    Cythonizing sources
    Processing numpy/random\_bounded_integers.pxd.in
    Processing numpy/random\bit_generator.pyx
    C:\Users\perch\AppData\Local\Temp\pip-wheel-5rgbkagq\numpy_7b4d8026a8794fbba06577e80a90fab8\tools\cythonize.py:69: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
      from distutils.version import LooseVersion
    Processing numpy/random\mtrand.pyx
    Processing numpy/random\_bounded_integers.pyx.in
    Processing numpy/random\_common.pyx
    Processing numpy/random\_generator.pyx
    Processing numpy/random\_mt19937.pyx
    Processing numpy/random\_pcg64.pyx
    Processing numpy/random\_philox.pyx
    Processing numpy/random\_sfc64.pyx
    blas_opt_info:
    blas_mkl_info:
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries mkl_rt not found in ['C:\\Users\\perch\\Desktop\\programming\\PingerBot\\venv\\lib', 'C:\\']
      NOT AVAILABLE
  
    blis_info:
      libraries blis not found in ['C:\\Users\\perch\\Desktop\\programming\\PingerBot\\venv\\lib', 'C:\\']
      NOT AVAILABLE
  
    openblas_info:
      libraries openblas not found in ['C:\\Users\\perch\\Desktop\\programming\\PingerBot\\venv\\lib', 'C:\\']
    get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
    customize GnuFCompiler
    Could not locate executable g77
    Could not locate executable f77
    customize IntelVisualFCompiler
    Could not locate executable ifort
    Could not locate executable ifl
    customize AbsoftFCompiler
    Could not locate executable f90
    customize CompaqVisualFCompiler
    Could not locate executable DF
    customize IntelItaniumVisualFCompiler
    Could not locate executable efl
    customize Gnu95FCompiler
    Could not locate executable gfortran
    Could not locate executable f95
    customize G95FCompiler
    Could not locate executable g95
    customize IntelEM64VisualFCompiler
    customize IntelEM64TFCompiler
    Could not locate executable efort
    Could not locate executable efc
    customize PGroupFlangCompiler
    Could not locate executable flang
    don't know how to compile Fortran code on platform 'nt'
      NOT AVAILABLE
  
    accelerate_info:
      NOT AVAILABLE
  
    atlas_3_10_blas_threads_info:
    Setting PTATLAS=ATLAS
      libraries tatlas not found in ['C:\\Users\\perch\\Desktop\\programming\\PingerBot\\venv\\lib', 'C:\\']
      NOT AVAILABLE
  
    atlas_3_10_blas_info:
      libraries satlas not found in ['C:\\Users\\perch\\Desktop\\programming\\PingerBot\\venv\\lib', 'C:\\']
      NOT AVAILABLE
  
    atlas_blas_threads_info:
    Setting PTATLAS=ATLAS
      libraries ptf77blas,ptcblas,atlas not found in ['C:\\Users\\perch\\Desktop\\programming\\PingerBot\\venv\\lib', 'C:\\']
      NOT AVAILABLE
  
    atlas_blas_info:
      libraries f77blas,cblas,atlas not found in ['C:\\Users\\perch\\Desktop\\programming\\PingerBot\\venv\\lib', 'C:\\']
      NOT AVAILABLE
  
    C:\Users\perch\AppData\Local\Temp\pip-wheel-5rgbkagq\numpy_7b4d8026a8794fbba06577e80a90fab8\numpy\distutils\system_info.py:2026: UserWarning:
        Optimized (vendor) Blas libraries are not found.
        Falls back to netlib Blas library which has worse performance.
        A better performance should be easily gained by switching
        Blas library.
      if self._calc_info(blas):
    blas_info:
      libraries blas not found in ['C:\\Users\\perch\\Desktop\\programming\\PingerBot\\venv\\lib', 'C:\\']
      NOT AVAILABLE
  
    C:\Users\perch\AppData\Local\Temp\pip-wheel-5rgbkagq\numpy_7b4d8026a8794fbba06577e80a90fab8\numpy\distutils\system_info.py:2026: UserWarning:
        Blas (http://www.netlib.org/blas/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [blas]) or by setting
        the BLAS environment variable.
      if self._calc_info(blas):
    blas_src_info:
      NOT AVAILABLE
  
    C:\Users\perch\AppData\Local\Temp\pip-wheel-5rgbkagq\numpy_7b4d8026a8794fbba06577e80a90fab8\numpy\distutils\system_info.py:2026: UserWarning:
        Blas (http://www.netlib.org/blas/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [blas_src]) or by setting
        the BLAS_SRC environment variable.
      if self._calc_info(blas):
      NOT AVAILABLE
  
    non-existing path in 'numpy\\distutils': 'site.cfg'
    lapack_opt_info:
    lapack_mkl_info:
      libraries mkl_rt not found in ['C:\\Users\\perch\\Desktop\\programming\\PingerBot\\venv\\lib', 'C:\\']
      NOT AVAILABLE
  
    openblas_lapack_info:
      libraries openblas not found in ['C:\\Users\\perch\\Desktop\\programming\\PingerBot\\venv\\lib', 'C:\\']
      NOT AVAILABLE
  
    openblas_clapack_info:
      libraries openblas,lapack not found in ['C:\\Users\\perch\\Desktop\\programming\\PingerBot\\venv\\lib', 'C:\\']
      NOT AVAILABLE
  
    flame_info:
      libraries flame not found in ['C:\\Users\\perch\\Desktop\\programming\\PingerBot\\venv\\lib', 'C:\\']
      NOT AVAILABLE
  
    atlas_3_10_threads_info:
    Setting PTATLAS=ATLAS
      libraries lapack_atlas not found in C:\Users\perch\Desktop\programming\PingerBot\venv\lib
      libraries tatlas,tatlas not found in C:\Users\perch\Desktop\programming\PingerBot\venv\lib
      libraries lapack_atlas not found in C:\
      libraries tatlas,tatlas not found in C:\
    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      NOT AVAILABLE
  
    atlas_3_10_info:
      libraries lapack_atlas not found in C:\Users\perch\Desktop\programming\PingerBot\venv\lib
      libraries satlas,satlas not found in C:\Users\perch\Desktop\programming\PingerBot\venv\lib
      libraries lapack_atlas not found in C:\
      libraries satlas,satlas not found in C:\
    <class 'numpy.distutils.system_info.atlas_3_10_info'>
      NOT AVAILABLE
  
    atlas_threads_info:
    Setting PTATLAS=ATLAS
      libraries lapack_atlas not found in C:\Users\perch\Desktop\programming\PingerBot\venv\lib
      libraries ptf77blas,ptcblas,atlas not found in C:\Users\perch\Desktop\programming\PingerBot\venv\lib
      libraries lapack_atlas not found in C:\
      libraries ptf77blas,ptcblas,atlas not found in C:\
    <class 'numpy.distutils.system_info.atlas_threads_info'>
      NOT AVAILABLE
  
    atlas_info:
      libraries lapack_atlas not found in C:\Users\perch\Desktop\programming\PingerBot\venv\lib
      libraries f77blas,cblas,atlas not found in C:\Users\perch\Desktop\programming\PingerBot\venv\lib
      libraries lapack_atlas not found in C:\
      libraries f77blas,cblas,atlas not found in C:\
    <class 'numpy.distutils.system_info.atlas_info'>
      NOT AVAILABLE
  
    lapack_info:
      libraries lapack not found in ['C:\\Users\\perch\\Desktop\\programming\\PingerBot\\venv\\lib', 'C:\\']
      NOT AVAILABLE
  
    C:\Users\perch\AppData\Local\Temp\pip-wheel-5rgbkagq\numpy_7b4d8026a8794fbba06577e80a90fab8\numpy\distutils\system_info.py:1858: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      return getattr(self, '_calc_info_{}'.format(name))()
    lapack_src_info:
      NOT AVAILABLE
  
    C:\Users\perch\AppData\Local\Temp\pip-wheel-5rgbkagq\numpy_7b4d8026a8794fbba06577e80a90fab8\numpy\distutils\system_info.py:1858: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      return getattr(self, '_calc_info_{}'.format(name))()
      NOT AVAILABLE
  
    numpy_linalg_lapack_lite:
      FOUND:
        language = c
        define_macros = [('HAVE_BLAS_ILP64', None), ('BLAS_SYMBOL_SUFFIX', '64_')]
  
    Warning: attempted relative import with no known parent package
    C:\Users\perch\AppData\Local\Programs\Python\Python310\lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'define_macros'
      warnings.warn(msg)
    running bdist_wheel
    running build
    running config_cc
    unifing config_cc, config, build_clib, build_ext, build commands --compiler options
    running config_fc
    unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
    running build_src
    build_src
    building py_modules sources
    creating build
    creating build\src.win-amd64-3.10
    creating build\src.win-amd64-3.10\numpy
    creating build\src.win-amd64-3.10\numpy\distutils
    building library "npymath" sources
    error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
    ERROR: Failed building wheel for numpy
  ERROR: Failed to build one or more wheels
  Traceback (most recent call last):
    File "C:\Users\perch\Desktop\programming\PingerBot\venv\lib\site-packages\setuptools\installer.py", line 75, in fetch_build_egg
      subprocess.check_call(cmd)
    File "C:\Users\perch\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 369, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['C:\\Users\\perch\\Desktop\\programming\\PingerBot\\venv\\Scripts\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\perch\\AppData\\Local\\Temp\\tmp13ni4sae', '--quiet', 'numpy>=1.16']' returned non-zero exit status 1.
  
  The above exception was the direct cause of the following exception:
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\perch\AppData\Local\Temp\pip-install-suadel9_\matplotlib_4425044c99d5442ab5133bc5ee3d22aa\setup.py", line 258, in <module>
      setup(  # Finally, pass this all along to distutils to do the heavy lifting.
    File "C:\Users\perch\Desktop\programming\PingerBot\venv\lib\site-packages\setuptools\__init__.py", line 152, in setup
      _install_setup_requires(attrs)
    File "C:\Users\perch\Desktop\programming\PingerBot\venv\lib\site-packages\setuptools\__init__.py", line 147, in _install_setup_requires
      dist.fetch_build_eggs(dist.setup_requires)
    File "C:\Users\perch\Desktop\programming\PingerBot\venv\lib\site-packages\setuptools\dist.py", line 779, in fetch_build_eggs
      resolved_dists = pkg_resources.working_set.resolve(
    File "C:\Users\perch\Desktop\programming\PingerBot\venv\lib\site-packages\pkg_resources\__init__.py", line 766, in resolve
      dist = best[req.key] = env.best_match(
    File "C:\Users\perch\Desktop\programming\PingerBot\venv\lib\site-packages\pkg_resources\__init__.py", line 1051, in best_match
      return self.obtain(req, installer)
    File "C:\Users\perch\Desktop\programming\PingerBot\venv\lib\site-packages\pkg_resources\__init__.py", line 1063, in obtain
      return installer(requirement)
    File "C:\Users\perch\Desktop\programming\PingerBot\venv\lib\site-packages\setuptools\dist.py", line 838, in fetch_build_egg
      return fetch_build_egg(self, req)
    File "C:\Users\perch\Desktop\programming\PingerBot\venv\lib\site-packages\setuptools\installer.py", line 77, in fetch_build_egg
      raise DistutilsError(str(e)) from e
  distutils.errors.DistutilsError: Command '['C:\\Users\\perch\\Desktop\\programming\\PingerBot\\venv\\Scripts\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\perch\\AppData\\Local\\Temp\\tmp13ni4sae', '--quiet', 'numpy>=1.16']' returned non-zero exit status 1.
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/21/37/197e68df384ff694f78d687a49ad39f96c67b8d75718bc61503e1676b617/matplotlib-3.4.3.tar.gz#sha256=fc4f526dfdb31c9bd6b8ca06bf9fab663ca12f3ec9cdf4496fb44bc680140318 (from https://pypi.org/simple/matplotlib/) (requires-python:>=3.7). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement matplotlib==3.4.3 (from versions: 0.86, 0.86.1, 0.86.2, 0.91.0, 0.91.1, 1.0.1, 1.1.0, 1.1.1, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1rc1, 1.4.1, 1.4.2, 1.4.3, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 2.0.0b1, 2.0.0b2, 2.0.0b3, 2.0.0b4, 2.0.0rc1, 2.0.0rc2, 2.0.0, 2.0.1, 2.0.2, 2.1.0rc1, 2.1.0, 2.1.1, 2.1.2, 2.2.0rc1, 2.2.0, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 3.0.0rc2, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.1.0rc1, 3.1.0rc2, 3.1.0, 3.1.1, 3.1.2, 3.1.3, 3.2.0rc1, 3.2.0rc3, 3.2.0, 3.2.1, 3.2.2, 3.3.0rc1, 3.3.0, 3.3.1, 3.3.2, 3.3.3, 3.3.4, 3.4.0rc1, 3.4.0rc2, 3.4.0rc3, 3.4.0, 3.4.1, 3.4.2, 3.4.3, 3.5.0b1, 3.5.0rc1)
ERROR: No matching distribution found for matplotlib==3.4.3
```

### Expected outcome

I doesn't want install Python 3.9 back

### Operating system

Windows 11

### Matplotlib Version

3.4.3

### Python version

Python 3.10.0

### Installation

pip

**Comment by tacaswell** [comment]
>     error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/

This is the key line.  You do not have a c/c++ compiler installed with is required to build both numpy and Matplotlib from source.  You either need to install a complier or wait for pre-built binaries to be available.
