### ISSUE TITLE
[Bug]: Failing install on Python 3.11-alpha.1

### ISSUE THREAD

**Issue by PerchunPak** [matplotlib/matplotlib#21384]
### Bug summary

    File "/tmp/pip-install-q18u2rkj/matplotlib_9ab8a7bf488a4d09a940453e757acaca/versioneer.py", line 401, in get_config_from_root
      parser = configparser.SafeConfigParser()
  AttributeError: module 'configparser' has no attribute 'SafeConfigParser'.

### Code for reproduction

```python
pip install matplotlib==3.4.3



# Workflow file
name: Reproduce issue

on: [push,pull_request,release]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11-dev
    - run: pip install -U pip
    - name: Install dependencies
      run: pip install matplotlib==3.4.3
```

### Actual outcome

```
Collecting matplotlib==3.4.3
  Downloading matplotlib-3.4.3.tar.gz (37.9 MB)
  Preparing metadata (setup.py): started
  ERROR: Command errored out with exit status 1:
  Preparing metadata (setup.py): finished with status 'error'
   command: /opt/hostedtoolcache/Python/3.11.0-alpha.1/x64/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-q18u2rkj/matplotlib_9ab8a7bf488a4d09a940453e757acaca/setup.py'"'"'; __file__='"'"'/tmp/pip-install-q18u2rkj/matplotlib_9ab8a7bf488a4d09a940453e757acaca/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-cvim6va3
       cwd: /tmp/pip-install-q18u2rkj/matplotlib_9ab8a7bf488a4d09a940453e757acaca/
  Complete output (15 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-q18u2rkj/matplotlib_9ab8a7bf488a4d09a940453e757acaca/setup.py", line 54, in <module>
      __version__ = versioneer.get_version()
                    ^^^^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/pip-install-q18u2rkj/matplotlib_9ab8a7bf488a4d09a940453e757acaca/versioneer.py", line 1410, in get_version
      return get_versions()["version"]
             ^^^^^^^^^^^^^^
    File "/tmp/pip-install-q18u2rkj/matplotlib_9ab8a7bf488a4d09a940453e757acaca/versioneer.py", line 1344, in get_versions
      cfg = get_config_from_root(root)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/pip-install-q18u2rkj/matplotlib_9ab8a7bf488a4d09a940453e757acaca/versioneer.py", line 401, in get_config_from_root
      parser = configparser.SafeConfigParser()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/21/37/197e68df384ff694f78d687a49ad39f96c67b8d75718bc61503e1676b617/matplotlib-3.4.3.tar.gz#sha256=fc4f526dfdb31c9bd6b8ca06bf9fab663ca12f3ec9cdf4496fb44bc680140318 (from https://pypi.org/simple/matplotlib/) (requires-python:>=3.7). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement matplotlib==3.4.3 (from versions: 0.86, 0.86.1, 0.86.2, 0.91.0, 0.91.1, 1.0.1, 1.1.0, 1.1.1, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1rc1, 1.4.1, 1.4.2, 1.4.3, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 2.0.0b1, 2.0.0b2, 2.0.0b3, 2.0.0b4, 2.0.0rc1, 2.0.0rc2, 2.0.0, 2.0.1, 2.0.2, 2.1.0rc1, 2.1.0, 2.1.1, 2.1.2, 2.2.0rc1, 2.2.0, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 3.0.0rc2, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.1.0rc1, 3.1.0rc2, 3.1.0, 3.1.1, 3.1.2, 3.1.3, 3.2.0rc1, 3.2.0rc3, 3.2.0, 3.2.1, 3.2.2, 3.3.0rc1, 3.3.0, 3.3.1, 3.3.2, 3.3.3, 3.3.4, 3.4.0rc1, 3.4.0rc2, 3.4.0rc3, 3.4.0, 3.4.1, 3.4.2, 3.4.3, 3.5.0b1, 3.5.0rc1)
ERROR: No matching distribution found for matplotlib==3.4.3
```

### Expected outcome

Why you think this really need

### Operating system

Github Actions, ubuntu-latest

### Matplotlib Version

3.4.3

### Python version

https://github.com/actions/python-versions/releases/tag/3.11.0-alpha.1-117932

### Installation

pip

**Comment by QuLogic** [comment]
There's not going to be much chance that 3.4.x supports 3.11 alphas. `versioneer` is gone in main and (to-be) 3.5, so you should use that.
