### ISSUE TITLE
Zoom/Pan not working properly [Bug]: 

### ISSUE THREAD

**Issue by inxp** [matplotlib/matplotlib#21575]
### Bug summary

Zoom/Pan not working properly in the following PyQt5 example with new version of Matplotlib. (I checked with 3.4.0 and 3.4.3)

Everything works properly with matplotlib 3.3.4 (Check gifs)

Problem occurs only when multiple plots are embedded.

After sometime of switching between figures and zooming/panning following error is shown.

```
Traceback (most recent call last):
  File "\lib\site-packages\matplotlib\cbook\__init__.py", line 270, in process
    func(*args, **kwargs)
  File "\lib\site-packages\matplotlib\backend_bases.py", line 3074, in _zoom_pan_handler
    self.release_pan(event)
  File "\lib\site-packages\matplotlib\backend_bases.py", line 3147, in release_pan
    ax.end_pan()
  File "\lib\site-packages\matplotlib\axes\_base.py", line 4239, in end_pan
    del self._pan_start
AttributeError: _pan_start
```
Thanks

### Code for reproduction

```python
import sys
import os

	
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QAbstractItemView, QAction, QApplication, QFileDialog, QInputDialog
from PyQt5.uic import loadUiType

from matplotlib.figure import Figure
from matplotlib.backends.backend_qt5agg import (
	FigureCanvasQTAgg as FigureCanvas,
	NavigationToolbar2QT as NavigationToolbar)
	
Ui_MainWindow, QMainWindow = loadUiType('window.ui')

class Main(QMainWindow, Ui_MainWindow):
	def __init__(self, ):
		super(Main, self).__init__()
		self.setupUi(self)
		self.fig_dict = {}
		self.figdata_dict = {}
		
		self.mplfigs.itemClicked.connect(self.changefig)
		
		fig = Figure()
		self.addmpl(fig)
		
	
	def changefig(self, item):
		text = item.text()
		text = str(text)
		self.rmmpl()
		self.addmpl(self.fig_dict[text])
	
		
	def addfig(self, name, fig):
		self.fig_dict[name] = fig
		self.mplfigs.addItem(name)
		
	def addmpl(self,fig):
		self.canvas = FigureCanvas(fig)
		self.mplvl.addWidget(self.canvas)
		self.canvas.draw()
		self.toolbar = NavigationToolbar(self.canvas,self.mplwindow, coordinates=2)
		self.toolbar.zoom()
		self.mplvl.addWidget(self.toolbar)
		
	def rmmpl(self,):
		self.mplvl.removeWidget(self.canvas)
		self.canvas.close()
		self.mplvl.removeWidget(self.toolbar)
		self.toolbar.close()
 
 
if __name__ == '__main__':

	fig1 = Figure()
	ax1f1 = fig1.add_subplot(111)
	ax1f1.plot([1,2,3,1,2,3])
	
	fig2 = Figure()
	ax1f2 = fig2.add_subplot(111)
	ax1f2.plot([100,200,300,400,100,200,300])
	ax1f2.plot([200,300,400,200,300,400])
	
	app = QApplication(sys.argv)
	main = Main()
	main.addfig('Oneplot', fig1)
	main.addfig('Twoplots', fig2)
	main.show()
	sys.exit(app.exec_())
```

### Actual outcome

![](https://i.imgur.com/0QKF3DH.gif)

### Expected outcome

![](https://i.imgur.com/DLPW9Hw.gif)

### Operating system

Windows 10 64-bit

### Matplotlib Version

3.4.3

### Matplotlib Backend

pyqt5

### Python version

3.9.7

### Other libraries - window.ui
```
<?xml version="1.0" encoding="UTF-8"?>
<ui version="4.0">
 <class>MainWindow</class>
 <widget class="QMainWindow" name="MainWindow">
  <property name="geometry">
   <rect>
    <x>0</x>
    <y>0</y>
    <width>1280</width>
    <height>768</height>
   </rect>
  </property>
  <property name="windowTitle">
   <string>MainWindow</string>
  </property>
  <widget class="QWidget" name="centralwidget">
   <layout class="QHBoxLayout" name="horizontalLayout">
    <item>
     <widget class="QWidget" name="mplwindow" native="true">
      <property name="sizePolicy">
       <sizepolicy hsizetype="Expanding" vsizetype="Preferred">
        <horstretch>0</horstretch>
        <verstretch>0</verstretch>
       </sizepolicy>
      </property>
      <property name="mouseTracking">
       <bool>false</bool>
      </property>
      <property name="focusPolicy">
       <enum>Qt::ClickFocus</enum>
      </property>
      <layout class="QVBoxLayout" name="mplvl"/>
     </widget>
    </item>
    <item>
     <widget class="QListWidget" name="mplfigs">
      <property name="sizePolicy">
       <sizepolicy hsizetype="Fixed" vsizetype="Expanding">
        <horstretch>0</horstretch>
        <verstretch>0</verstretch>
       </sizepolicy>
      </property>
      <property name="minimumSize">
       <size>
        <width>200</width>
        <height>0</height>
       </size>
      </property>
      <property name="maximumSize">
       <size>
        <width>200</width>
        <height>16777215</height>
       </size>
      </property>
      <property name="focusPolicy">
       <enum>Qt::NoFocus</enum>
      </property>
     </widget>
    </item>
   </layout>
  </widget>
  <widget class="QMenuBar" name="menubar">
   <property name="geometry">
    <rect>
     <x>0</x>
     <y>0</y>
     <width>1280</width>
     <height>21</height>
    </rect>
   </property>
  </widget>
  <widget class="QStatusBar" name="statusbar"/>
 </widget>
 <resources/>
 <connections/>
</ui>
```

### Installation

pip

**Comment by tacaswell** [comment]
That is a fun bug!  I can not reproduce this on the ~current main or the 3.5 rc (`pip install --pre --upgrade matplotlib`).  My guess is that something was getting out of sync with the state of the toolbar when you created new ones (the code it is in is trying to end a PAN not a ZOOM).

As a side note, you may want to actually stash the canvas and toolbar objects and show/hide them rather than recreating them from scratch every time you switch.  If nothing else, it will preserve the view history (which lives in the toolbar).

**Comment by inxp** [comment]
I am getting the same problem with 3.5 rc also.

I tried doing a fresh python + matplotlib install. Still same problem.

pip install matplotlib==3.3.4 fixes the problem for me in the new setup also.

**Comment by inxp** [comment]
![](https://i.imgur.com/1uXCJXV.gif)

It worked for first two zooms then problems started.

**Comment by tacaswell** [comment]
Can you try to modify your code to not re-create the toolbar when you switch figures (toggle the visibility or swap the layout instead) ?  I suspect the the problem is that there is some state on the Axes and some state on the toolbar that is being driven to an inconsistent state when you swap out the toolbars.

This is not something that is done via the pyplot code and we definitely do not test this.  If you could use git bisect to sort out what commit caused this to start breaking for you that would be a very good clue as to where the crossed state is.

**Comment by inxp** [comment]
Yes. You are right. I modified the code to switch the figure/toolbar instead of recreating and the problem is fixed.

Here is the updated code

```
import sys
import os

	
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QAbstractItemView, QAction, QApplication, QFileDialog, QInputDialog
from PyQt5.uic import loadUiType

from matplotlib.figure import Figure
from matplotlib.backends.backend_qt5agg import (
	FigureCanvasQTAgg as FigureCanvas,
	NavigationToolbar2QT as NavigationToolbar)
	
Ui_MainWindow, QMainWindow = loadUiType('window.ui')

class Main(QMainWindow, Ui_MainWindow):
	def __init__(self, ):
		super(Main, self).__init__()
		self.setupUi(self)
		self.canvas_dict = {}
		self.toolbar_dict = {}
		
		self.mplfigs.itemClicked.connect(self.changefig)
		
	def addfig(self,name,fig):
		canvas=FigureCanvas(fig)
		canvas.setVisible(False)
		self.canvas_dict[name]=canvas
		toolbar=NavigationToolbar(canvas,self.mplwindow, coordinates=2)
		toolbar.setVisible(False)
		toolbar.zoom()
		self.toolbar_dict[name]=toolbar
		self.mplvl.addWidget(canvas)
		self.mplvl.addWidget(toolbar)
		self.mplfigs.addItem(name)

	def changefig(self, item):
		for i in range(4):
			self.mplvl.itemAt(i).widget().setVisible(False)
		text = item.text()
		text = str(text)
		canvas=self.canvas_dict[text]
		toolbar=self.toolbar_dict[text]
		canvas.setVisible(True)
		toolbar.setVisible(True)
 
if __name__ == '__main__':

	fig1 = Figure()
	ax1f1 = fig1.add_subplot(111)
	ax1f1.plot([1,2,3,1,2,3])
	
	fig2 = Figure()
	ax1f2 = fig2.add_subplot(111)
	ax1f2.plot([100,200,300,400,100,200,300])
	ax1f2.plot([200,300,400,200,300,400])
	
	app = QApplication(sys.argv)
	main = Main()
	main.addfig('Oneplot', fig1)
	main.addfig('Twoplots', fig2)
	main.show()
	sys.exit(app.exec_())
```

I will try to use git bisect to find out what commit caused this.

Should I close this issue?

Thanks :)

**Comment by jklymak** [comment]
@inxp it seems unlikely this is really a bug, as a reference being dropped as the toolbar is added, and pulled down successively; I think you were probably pushing the system beyond what it could handle.  If you have a good solution now, my vote would be to close this.

**Comment by inxp** [comment]
@jklymak It used to work with older versions of matplotlib (<=3.3.4). A recent change caused it to break. That's why i raised it as a bug.

I think I have a better solution now hence I'm closing this. I will still try to find out what commit caused this.

Again Thanks to @tacaswell  for helping :)

**Comment by anntzer** [comment]
I can consistently repro the issue (you need to pan on one of the plots, then switch to the other and switch back to the first one, and pan).
This occurs because the callbacks registered by the first toolbar on the first plot don't get disconnected, and thus get called twice during the second pan.  It turns out that start_pan and drag_pan can be called twice with no problems (the second call effectively has no effect), but two calls to end_pan try to delete twice the same attribute.

I agree that the design is a bit problematic (I'm not sure how to handle toolbar removal), but at least this seems actionable (try to disconnect callbacks in that case).

**Comment by greglucas** [comment]
I'll add that when testing this out on a retina display, in the first example the plot is constantly zooming in every time I switch figures due to the dpi scaling the figure for me. When I move to a second monitor with standard dpi, the plots appear fine. So something also seems a little wonky with the hidpi initialization here.

With the updated example, all plots seem to work as expected with the dpi scaling.
