### ISSUE TITLE
[Bug]: 3.5.0 colorbar ValueError: minvalue must be less than or equal to maxvalue

### ISSUE THREAD

**Issue by akrherz** [matplotlib/matplotlib#21671]
### Bug summary

ValueError is raised on colorbar code that worked with previous matplotlib releases.

### Code for reproduction

```python
import matplotlib.pyplot as plt
import matplotlib.cm as mpcm
import matplotlib.colors as mpcolors

cmap = plt.get_cmap("viridis")
clevs = list(range(-94, -85))
norm = mpcolors.BoundaryNorm(clevs, cmap.N)
plt.colorbar(
    mpcm.ScalarMappable(cmap=cmap, norm=norm),
)
```

### Actual outcome

```
Traceback (most recent call last):
  File "colorbar.py", line 8, in <module>
    plt.colorbar(
  File "/opt/miniconda3/envs/prod/lib/python3.8/site-packages/matplotlib/pyplot.py", line 2088, in colorbar
    ret = gcf().colorbar(mappable, cax=cax, ax=ax, **kw)
  File "/opt/miniconda3/envs/prod/lib/python3.8/site-packages/matplotlib/figure.py", line 1158, in colorbar
    cb = cbar.Colorbar(cax, mappable, **cb_kw)
  File "/opt/miniconda3/envs/prod/lib/python3.8/site-packages/matplotlib/colorbar.py", line 493, in __init__
    self.draw_all()
  File "/opt/miniconda3/envs/prod/lib/python3.8/site-packages/matplotlib/colorbar.py", line 577, in draw_all
    X, Y, extendlen = self._mesh()
  File "/opt/miniconda3/envs/prod/lib/python3.8/site-packages/matplotlib/colorbar.py", line 1132, in _mesh
    y, extendlen = self._proportional_y()
  File "/opt/miniconda3/envs/prod/lib/python3.8/site-packages/matplotlib/colorbar.py", line 1249, in _proportional_y
    yscaled = np.ma.filled(norm(yscaled), np.nan)
  File "/opt/miniconda3/envs/prod/lib/python3.8/site-packages/matplotlib/colors.py", line 1245, in __call__
    raise ValueError("minvalue must be less than or equal to maxvalue")
ValueError: minvalue must be less than or equal to maxvalue
```

### Expected outcome

No traceback and colorbar added to the plot.

### Additional information

This code has worked for numerous previous matplotlib releases.

### Operating system

Centos 8 Stream

### Matplotlib Version

3.5.0

### Matplotlib Backend

QtAgg or agg

### Python version

3.8.12

### Jupyter version

n/a

### Installation

conda

**Comment by jklymak** [comment]
Thanks, sorry we broke this.  I'll try and fix this in the next few days and hopefully ti will be in a point release soonish...

**Comment by jklymak** [comment]
I have a fix for this, but hopefully ti doesn't break anything else, and I'll need to add a test
