### ISSUE TITLE
[Bug]: add_lines broken for horizontal colorbars

### ISSUE THREAD

**Issue by antonio-rojas** [matplotlib/matplotlib#21683]
### Bug summary

Calling add_lines on a horizontal colorbar is broken since commit 146856b03e85aa4b1becdd89fe1628f98fed2a05

### Code for reproduction

```python
import matplotlib.pyplot as plt
from matplotlib import colorbar
fig, ax = plt.subplots()
CS = ax.contour([[0.0, 1.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0.0]])
cb = colorbar.Colorbar(ax, CS, orientation='horizontal')
cb.add_lines(CS)
```

### Actual outcome

Traceback (most recent call last):
  File "test.sage", line 5, in <module>
    cb = colorbar.Colorbar(ax, CS, orientation='horizontal')
  File "/usr/lib/python3.9/site-packages/matplotlib/colorbar.py", line 496, in __init__
    self.add_lines(mappable)
  File "/usr/lib/python3.9/site-packages/matplotlib/colorbar.py", line 746, in add_lines
    return self.add_lines(
  File "/usr/lib/python3.9/site-packages/matplotlib/colorbar.py", line 788, in add_lines
    col.set_clip_path(mpath.Path(xy, closed=True),
  File "/usr/lib/python3.9/site-packages/matplotlib/path.py", line 130, in __init__
    _api.check_shape((None, 2), vertices=vertices)
  File "/usr/lib/python3.9/site-packages/matplotlib/_api/__init__.py", line 164, in check_shape
    raise ValueError(
ValueError: 'vertices' must be 2D with shape (M, 2). Your input has shape (2, 5).

### Expected outcome

No error

### Operating system

Arch Linux

### Matplotlib Version

3.5.0

### Matplotlib Backend

QtAgg

### Python version

3.9.7

### Installation

from source (.tar.gz)

**Comment by jklymak** [comment]
Thanks for the clear bug report and bisect,  and sorry we broke this.  Should be pretty straightforward to fix...
