### ISSUE TITLE
[Bug]: imshow() doesn't work with np.ndarray as an alpha channel

### ISSUE THREAD

**Issue by jameshclegg** [matplotlib/matplotlib#21747]
### Bug summary

When I supply a 2D array as an alpha channel, I get a numpy broadcasting error.  Looking in the code, it looks like matplotlib tries to multiply an upsampled array (in image pixel space) together with my input array.

### Code for reproduction

```python
import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(0, 1, 10)
x2D = np.tile(x, [x.size, 1])

plt.figure()
plt.imshow(x2D, alpha=x2D)
plt.savefig('u')
```

### Actual outcome

Traceback (most recent call last):
  File "alpha.py", line 9, in <module>
    plt.savefig('u')
  File "C:\WPy64-3870\python-3.8.7.amd64\lib\site-packages\matplotlib\pyplot.py", line 729, in savefig
    res = fig.savefig(*args, **kwargs)
  File "C:\WPy64-3870\python-3.8.7.amd64\lib\site-packages\matplotlib\figure.py", line 2180, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "C:\WPy64-3870\python-3.8.7.amd64\lib\site-packages\matplotlib\backend_bases.py", line 2084, in print_figure
    result = print_method(
  File "C:\WPy64-3870\python-3.8.7.amd64\lib\site-packages\matplotlib\backends\backend_agg.py", line 527, in print_png
    FigureCanvasAgg.draw(self)
  File "C:\WPy64-3870\python-3.8.7.amd64\lib\site-packages\matplotlib\backends\backend_agg.py", line 388, in draw
    self.figure.draw(self.renderer)
  File "C:\WPy64-3870\python-3.8.7.amd64\lib\site-packages\matplotlib\artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\WPy64-3870\python-3.8.7.amd64\lib\site-packages\matplotlib\figure.py", line 1708, in draw
    mimage._draw_list_compositing_images(
  File "C:\WPy64-3870\python-3.8.7.amd64\lib\site-packages\matplotlib\image.py", line 135, in _draw_list_compositing_images
    a.draw(renderer)
  File "C:\WPy64-3870\python-3.8.7.amd64\lib\site-packages\matplotlib\artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\WPy64-3870\python-3.8.7.amd64\lib\site-packages\matplotlib\axes\_base.py", line 2647, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "C:\WPy64-3870\python-3.8.7.amd64\lib\site-packages\matplotlib\image.py", line 135, in _draw_list_compositing_images
    a.draw(renderer)
  File "C:\WPy64-3870\python-3.8.7.amd64\lib\site-packages\matplotlib\artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\WPy64-3870\python-3.8.7.amd64\lib\site-packages\matplotlib\image.py", line 618, in draw
    im, l, b, trans = self.make_image(
  File "C:\WPy64-3870\python-3.8.7.amd64\lib\site-packages\matplotlib\image.py", line 879, in make_image
    return self._make_image(
  File "C:\WPy64-3870\python-3.8.7.amd64\lib\site-packages\matplotlib\image.py", line 530, in _make_image
    np.asarray(alpha_channel, np.float32) * out_alpha * alpha,
ValueError: operands could not be broadcast together with shapes (370,370) (10,10)

### Expected outcome

Expected a plot to be saved, with no exception thrown.

### Operating system

Windows 11

### Matplotlib Version

3.1.3

### Matplotlib Backend

TkAgg

### Python version

3.8.7

### Installation

pip

**Comment by jklymak** [comment]
This works fine in 3.5.0, and I suspect for quite a while.  Please upgrade Matplotlib if you need this to work.
