### ISSUE TITLE
[Bug]: TypeError: isinstance() arg 2 must be a type or tuple of types

### ISSUE THREAD

**Issue by phildurand** [matplotlib/matplotlib#21844]
### Bug summary

I can't generate a simple plot with pyplot

TypeError: isinstance() arg 2 must be a type or tuple of types

<Figure size 432x288 with 0 Axes>

### Code for reproduction

```python
# -*- coding: utf-8 -*-
"""
Spyder Editor

This is a temporary script file.
"""

import numpy as np 
from datetime import datetime
import matplotlib.pyplot as plt

if __name__ == "__main__":
    
    
    
    #Afficher une courbe avec plot
    x = np.arange(0,4*np.pi,0.1)   # start,stop,step
    y = np.sin(x)
    plt.plot(x,y)
    plt.show()
```

### Actual outcome

runfile('D:/Dropbox/2021-2022/1A-R107-Algo-SAE15/SAE15/PRJ/Sujet3/temp.py', wdir='D:/Dropbox/2021-2022/1A-R107-Algo-SAE15/SAE15/PRJ/Sujet3')
Traceback (most recent call last):

  File "D:\Dropbox\2021-2022\1A-R107-Algo-SAE15\SAE15\PRJ\Sujet3\temp.py", line 19, in <module>
    plt.plot(x,y)

  File "C:\Users\Philippe\AppData\Local\Programs\Spyder\pkgs\matplotlib\pyplot.py", line 2757, in plot
    return gca().plot(

  File "C:\Users\Philippe\AppData\Local\Programs\Spyder\pkgs\matplotlib\pyplot.py", line 2262, in gca
    return gcf().gca(**kwargs)

  File "C:\Users\Philippe\AppData\Local\Programs\Spyder\pkgs\matplotlib\figure.py", line 1511, in gca
    return self.add_subplot(1, 1, 1, **kwargs)

  File "C:\Users\Philippe\AppData\Local\Programs\Spyder\pkgs\matplotlib\figure.py", line 772, in add_subplot
    ax = subplot_class_factory(projection_class)(self, *args, **pkw)

  File "C:\Users\Philippe\AppData\Local\Programs\Spyder\pkgs\matplotlib\axes\_subplots.py", line 34, in __init__
    self._axes_class.__init__(self, fig, [0, 0, 1, 1], **kwargs)

  File "C:\Users\Philippe\AppData\Local\Programs\Spyder\pkgs\matplotlib\_api\deprecation.py", line 456, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\Philippe\AppData\Local\Programs\Spyder\pkgs\matplotlib\axes\_base.py", line 632, in __init__
    self.cla()

  File "C:\Users\Philippe\AppData\Local\Programs\Spyder\pkgs\matplotlib\axes\_base.py", line 1249, in cla
    self.grid(False)  # Disable grid on init to use rcParameter

  File "C:\Users\Philippe\AppData\Local\Programs\Spyder\pkgs\matplotlib\_api\deprecation.py", line 299, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\Philippe\AppData\Local\Programs\Spyder\pkgs\matplotlib\axes\_base.py", line 3226, in grid
    self.xaxis.grid(visible, which=which, **kwargs)

  File "C:\Users\Philippe\AppData\Local\Programs\Spyder\pkgs\matplotlib\_api\deprecation.py", line 299, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\Philippe\AppData\Local\Programs\Spyder\pkgs\matplotlib\axis.py", line 1434, in grid
    self.set_tick_params(which='major', **gridkw)

  File "C:\Users\Philippe\AppData\Local\Programs\Spyder\pkgs\matplotlib\axis.py", line 873, in set_tick_params
    for tick in self.majorTicks:

  File "C:\Users\Philippe\AppData\Local\Programs\Spyder\pkgs\matplotlib\axis.py", line 592, in __get__
    tick = instance._get_tick(major=True)

  File "C:\Users\Philippe\AppData\Local\Programs\Spyder\pkgs\matplotlib\axis.py", line 2057, in _get_tick
    return XTick(self.axes, 0, major=major, **tick_kw)

  File "C:\Users\Philippe\AppData\Local\Programs\Spyder\pkgs\matplotlib\axis.py", line 415, in __init__
    super().__init__(*args, **kwargs)

  File "C:\Users\Philippe\AppData\Local\Programs\Spyder\pkgs\matplotlib\axis.py", line 153, in __init__
    markeredgecolor=color, markersize=size, markeredgewidth=width,

  File "C:\Users\Philippe\AppData\Local\Programs\Spyder\pkgs\matplotlib\lines.py", line 371, in __init__
    self._marker = MarkerStyle(marker, fillstyle)

  File "C:\Users\Philippe\AppData\Local\Programs\Spyder\pkgs\matplotlib\markers.py", line 235, in __init__
    self._set_marker(marker)

  File "C:\Users\Philippe\AppData\Local\Programs\Spyder\pkgs\matplotlib\markers.py", line 308, in _set_marker
    if (isinstance(marker, np.ndarray) and marker.ndim == 2 and

TypeError: isinstance() arg 2 must be a type or tuple of types

<Figure size 432x288 with 0 Axes>

### Expected outcome

I would expect to get a plot

### Operating system

W10 

### Matplotlib Version

3.5.0

### Matplotlib Backend

import matplotlib; print(matplotlib.get_backend()) module://matplotlib_inline.backend_inline

### Python version

Python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]

**Comment by jklymak** [comment]
Such a simple plot works fine on a normal Matplotlib install, so the assumption would be your Spyder install is broken somehow.  It would be best if you took this up with the spyder folks.  Thanks for your understanding.

**Comment by tacaswell** [comment]
Can you get into a debugger and sort out what the value of `marker` is in this frame?

```pytb
File "C:\Users\Philippe\AppData\Local\Programs\Spyder\pkgs\matplotlib\lines.py", line 371, in init
self._marker = MarkerStyle(marker, fillstyle)
```

The traceback is coming from attempting to instantiate an Axes (`plt.gca()` will be enough to reproduce this).  I doubt that this is actually a spyder issues (the traceback is entirely in Matplotlib).

My guess as to what is going on here is that `rcParams['line.marker']` has ended up set to in invalid value which is being picked up the first time a `Line2D` is created (which happens to be in making the first tick in the first axis of the first Axes).

**Comment by phildurand** [comment]
Thank you very much for your answer. 
I think I have identified the problem. 
I am confused that I asked you for this. 
It is difficult to solve problems that seem random. I did a lot of tests and some of them knocked out the python kernel.
This is neither the myplot problem, nor the Spyder problem.
You can close the topic.
Regards
Philippe Durand

**Comment by WeatherGod** [comment]
Any hint on what happened? My only guess is that somehow np.ndarray got
redefined.

**Comment by phildurand** [comment]
Yes, that's exactly it!
Sorry for inconvenience.
