### ISSUE TITLE
[Bug]: Tool Manager example broken

### ISSUE THREAD

**Issue by StefRe** [matplotlib/matplotlib#22088]
### Bug summary

The [Tool Manager example](https://matplotlib.org/devdocs/gallery/user_interfaces/toolmanager_sgskip.html) doesn't work.

### Code for reproduction

```python
python toolmanager_sgskip.py
```

### Actual outcome

- Tools are not added:
https://github.com/matplotlib/matplotlib/blob/0c1aa86575126d5659bf885c7f283bbf2744fc4b/examples/user_interfaces/toolmanager_sgskip.py#L77-L78
![grafik](https://user-images.githubusercontent.com/19879328/147918695-8902c162-94fa-406c-bc7f-dbd9e16648f0.png)

- Clicking on "Configure subplots" icon ![grafik](https://user-images.githubusercontent.com/19879328/147918724-1c336544-5e65-4d31-b522-06de1c011893.png) crashes the program:
```
Traceback (most recent call last):
  File "C:\Programs\Python38\lib\site-packages\matplotlib\backends\backend_qt.py", line 930, in handler
    self.trigger_tool(name)
  File "C:\Programs\Python38\lib\site-packages\matplotlib\backend_bases.py", line 3391, in trigger_tool
    self.toolmanager.trigger_tool(name, sender=self)
  File "C:\Programs\Python38\lib\site-packages\matplotlib\backend_managers.py", line 379, in trigger_tool
    self._trigger_tool(name, sender, canvasevent, data)
  File "C:\Programs\Python38\lib\site-packages\matplotlib\backend_managers.py", line 394, in _trigger_tool
    tool.trigger(sender, canvasevent, data)
  File "C:\Programs\Python38\lib\site-packages\matplotlib\backends\backend_qt.py", line 970, in trigger
    NavigationToolbar2QT.configure_subplots(
  File "C:\Programs\Python38\lib\site-packages\matplotlib\backends\backend_qt.py", line 753, in configure_subplots
    if self._subplot_dialog is None:
AttributeError: 'types.SimpleNamespace' object has no attribute '_subplot_dialog'
```

### Expected outcome

- tools being added
- no crash

### Matplotlib Version

3.5.1

**Comment by anntzer** [comment]
Good catch, something like
```patch
diff --git i/lib/matplotlib/backends/backend_qt.py w/lib/matplotlib/backends/backend_qt.py
index c55937a019..1e0856adec 100644
--- i/lib/matplotlib/backends/backend_qt.py
+++ w/lib/matplotlib/backends/backend_qt.py
@@ -3,6 +3,7 @@ import operator
 import os
 import sys
 import traceback
+from weakref import WeakKeyDictionary
 
 import matplotlib as mpl
 from matplotlib import _api, backend_tools, cbook
@@ -646,7 +647,6 @@ class NavigationToolbar2QT(NavigationToolbar2, QtWidgets.QToolBar):
 
         self.coordinates = coordinates
         self._actions = {}  # mapping of toolitem method names to QActions.
-        self._subplot_dialog = None
 
         for text, tooltip_text, image_file, callback in self.toolitems:
             if text is None:
@@ -755,14 +755,11 @@ class NavigationToolbar2QT(NavigationToolbar2, QtWidgets.QToolBar):
         self.canvas.drawRectangle(None)
 
     def configure_subplots(self):
-        if self._subplot_dialog is None:
-            self._subplot_dialog = SubplotToolQt(
-                self.canvas.figure, self.canvas.parent())
-            self.canvas.mpl_connect(
-                "close_event", lambda e: self._subplot_dialog.reject())
-        self._subplot_dialog.update_from_current_subplotpars()
-        self._subplot_dialog.show()
-        return self._subplot_dialog
+        subplot_dialog = SubplotToolQt(
+            self.canvas.figure, self.canvas.parent())
+        subplot_dialog.update_from_current_subplotpars()
+        subplot_dialog.show()
+        return subplot_dialog
 
     def save_figure(self, *args):
         filetypes = self.canvas.get_supported_filetypes_grouped()
@@ -805,8 +802,13 @@ class NavigationToolbar2QT(NavigationToolbar2, QtWidgets.QToolBar):
 
 
 class SubplotToolQt(QtWidgets.QDialog):
-    def __init__(self, targetfig, parent):
-        super().__init__()
+    _keep_alive = WeakKeyDictionary()
+
+    def __new__(cls, targetfig, parent):
+        if targetfig in cls._keep_alive:
+            return cls._keep_alive[targetfig]
+        self = cls._keep_alive[targetfig] = super().__new__(cls, parent)
+        QtWidgets.QDialog.__init__(self)
         self.setWindowIcon(QtGui.QIcon(
             str(cbook._get_data_path("images/matplotlib.png"))))
         self.setObjectName("SubplotTool")
@@ -848,6 +850,11 @@ class SubplotToolQt(QtWidgets.QDialog):
         self._defaults = {}
         self._export_values_dialog = None
         self.update_from_current_subplotpars()
+        targetfig.canvas.mpl_connect("close_event", lambda e: self.reject())
+        return self
+
+    def __init__(self, targetfig, parent):
+        pass
 
     def update_from_current_subplotpars(self):
         self._defaults = {spinbox: getattr(self._figure.subplotpars, name)
```
(moving instance tracking to SubplotToolQt itself) would be one way to fix this.

**Comment by StefRe** [comment]
@anntzer Thanks for the super fast reply 👍 .

When using the Tk backend (added `plt.matplotlib.use('tkagg')`) there's another issue: the "Configure subplots" dialog works at first but then freezes: open the dialog and move some sliders - after a short while the dialog freezes (python 3.8.2 64bit Windows). I guess I should open a separate issue for this, shouldn't I?

**Comment by anntzer** [comment]
Please do (I don't have a solution for that off the top of my head).

**Comment by TheRikke** [comment]
I have the same issue and can confirm that the patch fixed it.
