### ISSUE TITLE
[Bug]: Cannot install on Debian (via mu-editor) - ERROR: ResolutionImpossible

### ISSUE THREAD

**Issue by Sciss** [matplotlib/matplotlib#22113]
### Bug summary

I'm trying to install mu-editor to write some code for a Pi Pico; mu-editor is based on Python, and apparently mathplotlib is a dependency. I cannot install mathplotlib on Debian 11 stable. It says dependencies `freetype` and `png` are not met. Please advise.

### Code for reproduction

```python
Debian 11; Python 3.9.2; `sudo apt install python3-pip`; `pip3 install mu-editor`
```

### Actual outcome

```
...
Collecting matplotlib==2.2.2
  Downloading matplotlib-2.2.2.tar.gz (37.3 MB)
     |████████████████████████████████| 37.3 MB 1.9 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-wjosel1n/matplotlib_68b8d4a2fe554f09ab7aeb951168bcc1/setup.py'"'"'; __file__='"'"'/tmp/pip-install-wjosel1n/matplotlib_68b8d4a2fe554f09ab7aeb951168bcc1/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-fg_514_s
         cwd: /tmp/pip-install-wjosel1n/matplotlib_68b8d4a2fe554f09ab7aeb951168bcc1/
    Complete output (62 lines):
    ============================================================================
    Edit setup.cfg to change the build options
    
    BUILDING MATPLOTLIB
                matplotlib: yes [2.2.2]
                    python: yes [3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC
                            10.2.1 20210110]]
                  platform: yes [linux]
    
    REQUIRED DEPENDENCIES AND EXTENSIONS
                     numpy: yes [version 1.19.5]
          install_requires: yes [handled by setuptools]
                    libagg: yes [pkg-config information for 'libagg' could not
                            be found. Using local copy.]
                  freetype: no  [The C/C++ header for freetype2 (ft2build.h)
                            could not be found.  You may need to install the
                            development package.]
                       png: no  [pkg-config information for 'libpng' could not
                            be found.]
                     qhull: yes [pkg-config information for 'libqhull' could not
                            be found. Using local copy.]
    
    OPTIONAL SUBPACKAGES
               sample_data: yes [installing]
                  toolkits: yes [installing]
                     tests: no  [skipping due to configuration]
            toolkits_tests: no  [skipping due to configuration]
    
    OPTIONAL BACKEND EXTENSIONS
                    macosx: no  [Mac OS-X only]
                    qt5agg: no  [PySide2 not found; PyQt5 not found]
                    qt4agg: no  [PySide not found; PyQt4 not found]
                   gtk3agg: yes [installing, version 3.24.24]
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-wjosel1n/matplotlib_68b8d4a2fe554f09ab7aeb951168bcc1/setup.py", line 197, in <module>
        msg = pkg.install_help_msg()
      File "/tmp/pip-install-wjosel1n/matplotlib_68b8d4a2fe554f09ab7aeb951168bcc1/setupext.py", line 592, in install_help_msg
        release = platform.linux_distribution()[0].lower()
    AttributeError: module 'platform' has no attribute 'linux_distribution'
                 gtk3cairo: yes [installing, version 3.24.24]
                    gtkagg: no  [Requires pygtk]
                     tkagg: yes [installing; run-time loading from Python Tcl /
                            Tk]
                     wxagg: no  [requires wxPython]
                       gtk: no  [Requires pygtk]
                       agg: yes [installing]
                     cairo: yes [installing, pycairo version 1.16.2]
                 windowing: no  [Microsoft Windows only]
    
    OPTIONAL LATEX DEPENDENCIES
                    dvipng: no
               ghostscript: yes [version 9.53.3]
                     latex: yes [version 3.14159265]
                   pdftops: yes [version 20.09.0]
    
    OPTIONAL PACKAGE DATA
                      dlls: no  [skipping due to configuration]
    
    ============================================================================
                            * The following required packages can not be built:
                            * freetype, png
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/ec/ed/46b835da53b7ed05bd4c6cae293f13ec26e877d2e490a53a709915a9dcb7/matplotlib-2.2.2.tar.gz#sha256=4dc7ef528aad21f22be85e95725234c5178c0f938e2228ca76640e5e84d8cde8 (from https://pypi.org/simple/matplotlib/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Collecting mu-editor
  Downloading mu_editor-1.0.2-py3-none-any.whl (2.0 MB)
     |████████████████████████████████| 2.0 MB 513 kB/s 
Collecting pyqt5==5.11.3
  Downloading PyQt5-5.11.3-5.11.2-cp35.cp36.cp37.cp38-abi3-manylinux1_x86_64.whl (117.8 MB)
     |████████████████████████████████| 117.8 MB 727 kB/s 
Collecting PyQtChart==5.11.3
  Downloading PyQtChart-5.11.3-5.11.2-cp35.cp36.cp37.cp38-abi3-manylinux1_x86_64.whl (1.1 MB)
     |████████████████████████████████| 1.1 MB 11.0 MB/s 
Collecting qscintilla==2.10.8
  Downloading QScintilla-2.10.8-5.11.2-cp35.cp36.cp37.cp38-abi3-manylinux1_x86_64.whl (2.6 MB)
     |████████████████████████████████| 2.6 MB 553 kB/s 
Collecting mu-editor
  Downloading mu_editor-1.0.1-py3-none-any.whl (1.9 MB)
     |████████████████████████████████| 1.9 MB 860 kB/s 
Collecting pyqt5==5.11.2
  Downloading PyQt5-5.11.2-5.11.1-cp35.cp36.cp37.cp38-abi3-manylinux1_x86_64.whl (117.9 MB)
     |████████████████████████████████| 117.9 MB 2.1 MB/s 
Collecting PyQtChart==5.11.2
  Downloading PyQtChart-5.11.2-5.11.1-cp35.cp36.cp37.cp38-abi3-manylinux1_x86_64.whl (1.1 MB)
     |████████████████████████████████| 1.1 MB 190.3 MB/s 
Collecting qscintilla==2.10.7
  Downloading QScintilla-2.10.7-5.11.1-cp35.cp36.cp37.cp38-abi3-manylinux1_x86_64.whl (2.6 MB)
     |████████████████████████████████| 2.6 MB 3.3 MB/s 
Collecting mu-editor
  Downloading mu_editor-1.0.0-py3-none-any.whl (1.7 MB)
     |████████████████████████████████| 1.7 MB 1.9 MB/s 
ERROR: Cannot install mu-editor==1.0.0, mu-editor==1.0.1, mu-editor==1.0.2 and mu-editor==1.0.3 because these package versions have conflicting dependencies.

The conflict is caused by:
    mu-editor 1.0.3 depends on matplotlib==2.2.2
    mu-editor 1.0.2 depends on matplotlib==2.2.2
    mu-editor 1.0.1 depends on matplotlib==2.2.2
    mu-editor 1.0.0 depends on matplotlib==2.2.2

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
```

### Expected outcome

should install all dependencies as specified

### Operating system

Debian 11 (bullseye) ; Linux aleph 5.10.0-10-amd64 #1 SMP Debian 5.10.84-1 (2021-12-08) x86_64 GNU/Linux

### Matplotlib Version

2.2.2

### Python version

3.9.2

### Installation

pip

**Comment by Sciss** [comment]
After running `sudo apt install libfreetype-dev`, it works (crashes at other point, but not related to mathplotlib)
