### ISSUE TITLE
[Bug]: fill_between() and numpy array with float instead of numpy.float64 elements

### ISSUE THREAD

**Issue by rbrijder** [matplotlib/matplotlib#22142]
### Bug summary

fill_between() crashes for numpy arrays where the elements are float instead of numpy.float64 elements.

### Code for reproduction

```python
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

d = {'t': [0,1], 'y1': [1.2, 2.3], 'y2': [2.2, 3.3]}
df = pd.DataFrame(data=d)
A = df.to_numpy()
print(type(A[0,1])) # 'numpy.float64'
plt.fill_between(A[:,1], A[:,2]) # works

times = [pd.Timestamp('2020-01-01'), pd.Timestamp('2021-01-01')]
d = {'t': times, 'y1': [1.2, 2.3], 'y2': [2.2, 3.3]}
df = pd.DataFrame(data=d)
B = df.to_numpy()
print(type(B[0,1])) # 'float' instead of 'numpy.float64'

plt.fill_between(np.float64(B[:,1]), np.float64(B[:,2])) # works

plt.fill_between(B[:,1], B[:,2]) # crashes
```

### Actual outcome

<class 'numpy.float64'>
<class 'float'>
Traceback (most recent call last):
  File ".\test_timestamp_inbetween.py", line 19, in <module>
    plt.fill_between(B[:,1], B[:,2]) # crashes
  File "C:\Users\robert.brijder\AppData\Roaming\Python\Python37\site-packages\matplotlib\pyplot.py", line 2545, in fill_between
    **({"data": data} if data is not None else {}), **kwargs)
  File "C:\Users\robert.brijder\AppData\Roaming\Python\Python37\site-packages\matplotlib\__init__.py", line 1412, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "C:\Users\robert.brijder\AppData\Roaming\Python\Python37\site-packages\matplotlib\axes\_axes.py", line 5254, in fill_between
    where=where, interpolate=interpolate, step=step, **kwargs)
  File "C:\Users\robert.brijder\AppData\Roaming\Python\Python37\site-packages\matplotlib\axes\_axes.py", line 5159, in _fill_between_x_or_y
    [(ind_dir, ind), (dep_dir, dep1), (dep_dir, dep2)], kwargs))
  File "C:\Users\robert.brijder\AppData\Roaming\Python\Python37\site-packages\numpy\ma\core.py", line 2371, in masked_invalid
    condition = ~(np.isfinite(a))
TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

### Expected outcome

<class 'numpy.float64'>
<class 'float'>

### Operating system

Windows 10 Pro

### Matplotlib Version

3.5.1

### Matplotlib Backend

QtAgg

### Python version

3.7.3

### Installation

pip

**Comment by jklymak** [comment]
We don't support pandas `Timestamp` objects, and if they don't support reasonable to_numpy behaviour we can't support that either.  I'd vote for won't-fix here.

**Comment by rbrijder** [comment]
Timestamps are not needed: `times = ["a", "b"]` instead of `times = [pd.Timestamp('2020-01-01'), pd.Timestamp('2021-01-01')]` will also crash. Mixing numbers with non-numbers seems to obtain numpy arrays with float instead of numpy.float64 elements.

**Comment by jklymak** [comment]
Yes, we cannot plot arbitrary object arrays.  B[:,1].dtype is `object`, and you can't do normal numpy operations on that.  pandas outputs objects because the data array is mixed.  In this case if you did `y=d['y'].to_numpy()` etc then you would be in much better shape.

**Comment by rbrijder** [comment]
> you can't do normal numpy operations on that

Actually, you can. In fact, I have been happily working with the `to_numpy()` output of a mixed type pandas dataframe. Only `fill_between()` seems to give trouble.

**Comment by dstansby** [comment]
Event though individual elements of the array are floats, the array as a whole has `B[:, 1].dtype == object`. This means `np.isfinite(B[:, 1]` does not work. We could try casting the array to floats internally though - do any other plotting methods in Matplotlib work with `B[:, 1]`?

**Comment by rbrijder** [comment]
> do any other plotting methods in Matplotlib work with B[:, 1]?

Yes, see code below. In fact, not just matplotlib; I have processed such arrays using various python packages. 

```
import matplotlib.pyplot as plt
import numpy as np

A = np.array([1.0, 2.0], dtype = 'object')

plt.plot(A)
plt.show() # output as expected

plt.hist(A)
plt.show() # output as expected

plt.fill_between(A, A) # crash
```

While the label "third-party integration: pandas" was added to this issue by someone, I don't think it has much to do with pandas. There are probably other natural ways to obtain such an array (not only by using pandas).

In case matplotlib doesn't want to support such arrays for `fill_between`, then I feel a better error message would be helpful. For example: `Type error: numpy arrays with dtype 'object' are not supported.`.

**Comment by dstansby** [comment]
Yes, it seems like this is independent of pandas. Given other methods work it seems like a reasonable request for `fill_between` to work too 👍

**Comment by timhoffm** [comment]
Even if other methods work accidentally, I'm hesitant to jump through extra hoops to support object-dtyped arrays.

If there is a trivial change to make this case work, fine let's do it. But we should not generally guarantee to work with object-dtype arrays.

**Comment by jklymak** [comment]
We should sit down at some point and define exactly what we will accept in terms of duck typing and units so that our expectations are clear.  If we break something that used to work unintentionally, we get people mad at us, but if we document what is allowed, we would have a solid set of expectations downstream folks could work with (as well as people who contribute to our methods).  I think this is on the agenda as a [Medium sized project](https://hackmd.io/GgtrcXTlTfuoyHO76_LMLg).

**Comment by timhoffm** [comment]
Rightfully closed, we neither do or plan to systematically support object-dtype data.

**Comment by rbrijder** [comment]
> Rightfully closed, we neither do or plan to systematically support object-dtype data.

Shouldn't that then be reflected in the documentation and an error with helpful message thrown when object-dtype data is used? Crashing is not an ideal user experience.

**Comment by timhoffm** [comment]
object-dtype arrays with floats are quite rare as one typically wants to avoid them for performance, memory efficiency and clarity.

We just call numpy functions, so any array type (or rather even any type) that works there will work with matplotlib. This is duck-typing. In the end, this is a numpy topic. We're out of the business as we are only passing the ndarray through to a numpy function. You could try to get numpy folks support this, but I'd assume they do not give guarantees on object-dtype arrays with floats as they are a rare edge-case.

We won't put special checks in to catch that edge case for a nicer error message.

Documentation wise, I wouldn't know where to put that or how to write so that it does not sound weirdly specific as the case is so obscure.
