### ISSUE TITLE
Unable to type latex \lVert symbol with matplotlib

### ISSUE THREAD

**Issue by Pepo80** [matplotlib/matplotlib#22166]
### Bug summary

Using LaTeX with Matplotlib I am able to use several LaTeX commands. However, when using the command `\lVert` an error is raised.

### Code for reproduction

```python
# Code that works:
import numpy as np
import matplotlib.pyplot as plt
plt.rc('text', usetex=True)
plt.rc('font', family='serif')
    
fig = plt.figure()
ax = fig.add_subplot()
foo = np.arange(8)
ax.plot(foo, foo, label=r"$\omega$")
ax.legend()

# Code that does not work:
import numpy as np
import matplotlib.pyplot as plt
plt.rc('text', usetex=True)
plt.rc('font', family='serif')
    
fig = plt.figure()
ax = fig.add_subplot()
foo = np.arange(8)
ax.plot(foo, foo, label=r"$\lVert\omega\lVert$")
ax.legend()
```

### Actual outcome

```
Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\texmanager.py", line 275, in _run_checked_subprocess
    report = subprocess.check_output(command,
  File "C:\Users\admin\anaconda3\lib\subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\admin\anaconda3\lib\subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['latex', '-interaction=nonstopmode', '--halt-on-error', 'C:\\Users\\admin\\.matplotlib\\tex.cache\\3704073e0ce42657e8ea9e4b0e5d5ff1.tex']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\backends\backend_qt5.py", line 480, in _draw_idle
    self.draw()
  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py", line 407, in draw
    self.figure.draw(self.renderer)
  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\figure.py", line 1863, in draw
    mimage._draw_list_compositing_images(
  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\image.py", line 131, in _draw_list_compositing_images
    a.draw(renderer)
  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\cbook\deprecation.py", line 411, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\axes\_base.py", line 2747, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\image.py", line 131, in _draw_list_compositing_images
    a.draw(renderer)
  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\legend.py", line 606, in draw
    bbox = self._legend_box.get_window_extent(renderer)
  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\offsetbox.py", line 346, in get_window_extent
    w, h, xd, yd, offsets = self.get_extent_offsets(renderer)
  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\offsetbox.py", line 471, in get_extent_offsets
    whd_list = [c.get_extent(renderer)
  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\offsetbox.py", line 471, in <listcomp>
    whd_list = [c.get_extent(renderer)
  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\offsetbox.py", line 341, in get_extent
    w, h, xd, yd, offsets = self.get_extent_offsets(renderer)
  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\offsetbox.py", line 544, in get_extent_offsets
    whd_list = [c.get_extent(renderer)
  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\offsetbox.py", line 544, in <listcomp>
    whd_list = [c.get_extent(renderer)
  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\offsetbox.py", line 341, in get_extent
    w, h, xd, yd, offsets = self.get_extent_offsets(renderer)
  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\offsetbox.py", line 471, in get_extent_offsets
    whd_list = [c.get_extent(renderer)
  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\offsetbox.py", line 471, in <listcomp>
    whd_list = [c.get_extent(renderer)
  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\offsetbox.py", line 341, in get_extent
    w, h, xd, yd, offsets = self.get_extent_offsets(renderer)
  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\offsetbox.py", line 544, in get_extent_offsets
    whd_list = [c.get_extent(renderer)
  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\offsetbox.py", line 544, in <listcomp>
    whd_list = [c.get_extent(renderer)
  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\offsetbox.py", line 886, in get_extent
    bbox, info, d = self._text._get_layout(renderer)
  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\text.py", line 295, in _get_layout
    w, h, d = renderer.get_text_width_height_descent(
  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py", line 227, in get_text_width_height_descent
    w, h, d = texmanager.get_text_width_height_descent(
  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\texmanager.py", line 423, in get_text_width_height_descent
    dvifile = self.make_dvi(tex, fontsize)
  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\texmanager.py", line 309, in make_dvi
    self._run_checked_subprocess(
  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\texmanager.py", line 283, in _run_checked_subprocess
    raise RuntimeError(
RuntimeError: latex was not able to process the following string:
b'$\\\\lVert\\\\omega\\\\lVert$'

Here is the full report generated by latex:
latex: security risk: running with elevated privileges
This is pdfTeX, Version 3.141592653-2.6-1.40.24 (MiKTeX 21.12.10) (preloaded format=latex.fmt)
 restricted \write18 enabled.
entering extended mode
(C:/Users/admin/.matplotlib/tex.cache/3704073e0ce42657e8ea9e4b0e5d5ff1.tex
LaTeX2e <2021-11-15> patch level 1
L3 programming layer <2021-11-22>
(C:\Users\admin\AppData\Local\Programs\MiKTeX\tex/latex/base\article.cls
Document Class: article 2021/10/04 v1.4n Standard LaTeX document class
(C:\Users\admin\AppData\Local\Programs\MiKTeX\tex/latex/base\size10.clo))
(C:\Users\admin\AppData\Local\Programs\MiKTeX\tex/latex/type1cm\type1cm.sty)
(C:\Users\admin\AppData\Local\Programs\MiKTeX\tex/latex/cm-super\type1ec.sty
(C:\Users\admin\AppData\Local\Programs\MiKTeX\tex/latex/base\t1cmr.fd))
(C:\Users\admin\AppData\Local\Programs\MiKTeX\tex/latex/base\inputenc.sty)
(C:\Users\admin\AppData\Local\Programs\MiKTeX\tex/latex/geometry\geometry.sty
(C:\Users\admin\AppData\Local\Programs\MiKTeX\tex/latex/graphics\keyval.sty)
(C:\Users\admin\AppData\Local\Programs\MiKTeX\tex/generic/iftex\ifvtex.sty
(C:\Users\admin\AppData\Local\Programs\MiKTeX\tex/generic/iftex\iftex.sty))
(C:\Users\admin\AppData\Local\Programs\MiKTeX\tex/latex/geometry\geometry.cfg)

Package geometry Warning: Over-specification in `h'-direction.
    `width' (5058.9pt) is ignored.


Package geometry Warning: Over-specification in `v'-direction.
    `height' (5058.9pt) is ignored.

) (C:\Users\admin\AppData\Local\Programs\MiKTeX\tex/latex/base\textcomp.sty)
(C:\Users\admin\AppData\Local\Programs\MiKTeX\tex/latex/l3backend\l3backend-dvi
ps.def)
No file 3704073e0ce42657e8ea9e4b0e5d5ff1.aux.
*geometry* driver: auto-detecting
*geometry* detected driver: dvips
! Undefined control sequence.
<recently read> \lVert 
                       
l.19 {\rmfamily $\lVert
                       \omega\lVert$}
No pages of output.
Transcript written on 3704073e0ce42657e8ea9e4b0e5d5ff1.log.



Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\texmanager.py", line 275, in _run_checked_subprocess
    report = subprocess.check_output(command,
  File "C:\Users\admin\anaconda3\lib\subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\admin\anaconda3\lib\subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['latex', '-interaction=nonstopmode', '--halt-on-error', 'C:\\Users\\admin\\.matplotlib\\tex.cache\\3704073e0ce42657e8ea9e4b0e5d5ff1.tex']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\backends\backend_qt5.py", line 480, in _draw_idle
    self.draw()
  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py", line 407, in draw
    self.figure.draw(self.renderer)
  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\figure.py", line 1863, in draw
    mimage._draw_list_compositing_images(
  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\image.py", line 131, in _draw_list_compositing_images
    a.draw(renderer)
  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\cbook\deprecation.py", line 411, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\axes\_base.py", line 2747, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\image.py", line 131, in _draw_list_compositing_images
    a.draw(renderer)
  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\legend.py", line 606, in draw
    bbox = self._legend_box.get_window_extent(renderer)
  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\offsetbox.py", line 346, in get_window_extent
    w, h, xd, yd, offsets = self.get_extent_offsets(renderer)
  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\offsetbox.py", line 471, in get_extent_offsets
    whd_list = [c.get_extent(renderer)
  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\offsetbox.py", line 471, in <listcomp>
    whd_list = [c.get_extent(renderer)
  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\offsetbox.py", line 341, in get_extent
    w, h, xd, yd, offsets = self.get_extent_offsets(renderer)
  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\offsetbox.py", line 544, in get_extent_offsets
    whd_list = [c.get_extent(renderer)
  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\offsetbox.py", line 544, in <listcomp>
    whd_list = [c.get_extent(renderer)
  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\offsetbox.py", line 341, in get_extent
    w, h, xd, yd, offsets = self.get_extent_offsets(renderer)
  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\offsetbox.py", line 471, in get_extent_offsets
    whd_list = [c.get_extent(renderer)
  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\offsetbox.py", line 471, in <listcomp>
    whd_list = [c.get_extent(renderer)
  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\offsetbox.py", line 341, in get_extent
    w, h, xd, yd, offsets = self.get_extent_offsets(renderer)
  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\offsetbox.py", line 544, in get_extent_offsets
    whd_list = [c.get_extent(renderer)
  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\offsetbox.py", line 544, in <listcomp>
    whd_list = [c.get_extent(renderer)
  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\offsetbox.py", line 886, in get_extent
    bbox, info, d = self._text._get_layout(renderer)
  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\text.py", line 295, in _get_layout
    w, h, d = renderer.get_text_width_height_descent(
  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py", line 227, in get_text_width_height_descent
    w, h, d = texmanager.get_text_width_height_descent(
  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\texmanager.py", line 423, in get_text_width_height_descent
    dvifile = self.make_dvi(tex, fontsize)
  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\texmanager.py", line 309, in make_dvi
    self._run_checked_subprocess(
  File "C:\Users\admin\anaconda3\lib\site-packages\matplotlib\texmanager.py", line 283, in _run_checked_subprocess
    raise RuntimeError(
RuntimeError: latex was not able to process the following string:
b'$\\\\lVert\\\\omega\\\\lVert$'

Here is the full report generated by latex:
latex: security risk: running with elevated privileges
This is pdfTeX, Version 3.141592653-2.6-1.40.24 (MiKTeX 21.12.10) (preloaded format=latex.fmt)
 restricted \write18 enabled.
entering extended mode
(C:/Users/admin/.matplotlib/tex.cache/3704073e0ce42657e8ea9e4b0e5d5ff1.tex
LaTeX2e <2021-11-15> patch level 1
L3 programming layer <2021-11-22>
(C:\Users\admin\AppData\Local\Programs\MiKTeX\tex/latex/base\article.cls
Document Class: article 2021/10/04 v1.4n Standard LaTeX document class
(C:\Users\admin\AppData\Local\Programs\MiKTeX\tex/latex/base\size10.clo))
(C:\Users\admin\AppData\Local\Programs\MiKTeX\tex/latex/type1cm\type1cm.sty)
(C:\Users\admin\AppData\Local\Programs\MiKTeX\tex/latex/cm-super\type1ec.sty
(C:\Users\admin\AppData\Local\Programs\MiKTeX\tex/latex/base\t1cmr.fd))
(C:\Users\admin\AppData\Local\Programs\MiKTeX\tex/latex/base\inputenc.sty)
(C:\Users\admin\AppData\Local\Programs\MiKTeX\tex/latex/geometry\geometry.sty
(C:\Users\admin\AppData\Local\Programs\MiKTeX\tex/latex/graphics\keyval.sty)
(C:\Users\admin\AppData\Local\Programs\MiKTeX\tex/generic/iftex\ifvtex.sty
(C:\Users\admin\AppData\Local\Programs\MiKTeX\tex/generic/iftex\iftex.sty))
(C:\Users\admin\AppData\Local\Programs\MiKTeX\tex/latex/geometry\geometry.cfg)

Package geometry Warning: Over-specification in `h'-direction.
    `width' (5058.9pt) is ignored.


Package geometry Warning: Over-specification in `v'-direction.
    `height' (5058.9pt) is ignored.

) (C:\Users\admin\AppData\Local\Programs\MiKTeX\tex/latex/base\textcomp.sty)
(C:\Users\admin\AppData\Local\Programs\MiKTeX\tex/latex/l3backend\l3backend-dvi
ps.def) (3704073e0ce42657e8ea9e4b0e5d5ff1.aux)
*geometry* driver: auto-detecting
*geometry* detected driver: dvips
! Undefined control sequence.
<recently read> \lVert 
                       
l.19 {\rmfamily $\lVert
                       \omega\lVert$}
No pages of output.
Transcript written on 3704073e0ce42657e8ea9e4b0e5d5ff1.log.
```

### Expected outcome

I would expect that the norm symbol `\lVert` got displayed in the figure.

### Additional information

Following the [docs](https://matplotlib.org/stable/tutorials/text/usetex.html) and some answers, I deleted my `.matplotlib/tex.cache` but it didn't solve the issue. I also checked Miktex (my LaTeX distribution) is in my Windows PATH.

### Operating system

Windows

### Matplotlib Version

3.3.4

### Matplotlib Backend

Qt5Agg

### Python version

3.8

### Installation

conda

**Comment by jklymak** [comment]
Isn't `\lvert` only available with `amsmath`?  In which case you need to include amsmath in   your latex preamble https://stackoverflow.com/questions/46259617/how-does-one-use-latex-amsmath-with-matplotlib, though note this is not officially supported.

**Comment by Pepo80** [comment]
Thanks for the feedback :). That worked!
