### ISSUE TITLE
[Bug]: Data with units not supported on 3d plots

### ISSUE THREAD

**Issue by TD22057** [matplotlib/matplotlib#22207]
### Bug summary

Attempting to make a basic x,y,z plot on a 3d axes with units doesn't work because the conversion to numpy array fails.  I assume this is because the data is never passed through the unit conversion API.

### Code for reproduction

```python
import matplotlib.pyplot as plt
import mpl_toolkits.mplot3d
import matplotlib.testing.jpl_units as units
units.register()

x = [i * units.km for i in range(10)]
y = [2 * i * units.km for i in range(10)]
z = [3 * i * units.km for i in range(10)]

fig = plt.figure()
ax = fig.add_subplot(projection="3d")
ax.plot(x, y, z)
plt.show()
```

### Actual outcome

```Traceback (most recent call last):
  File "/home/trd/t.py", line 12, in <module>
    ax.plot(x, y, z)
  File "/group/monte/tools/rhel7_64/core-12/lib/python3.9/site-packages/mpl_toolkits/mplot3d/axes3d.py", line 1500, in plot
    self.auto_scale_xyz(xs, ys, zs, had_data)
  File "/group/monte/tools/rhel7_64/core-12/lib/python3.9/site-packages/mpl_toolkits/mplot3d/axes3d.py", line 648, in auto_scale_xyz
    self.xy_dataLim.update_from_data_xy(
  File "/group/monte/tools/rhel7_64/core-12/lib/python3.9/site-packages/matplotlib/transforms.py", line 967, in update_from_data_xy
    path = Path(xy)
  File "/group/monte/tools/rhel7_64/core-12/lib/python3.9/site-packages/matplotlib/path.py", line 129, in __init__
    vertices = _to_unmasked_float_array(vertices)
  File "/group/monte/tools/rhel7_64/core-12/lib/python3.9/site-packages/matplotlib/cbook/__init__.py", line 1298, in _to_unmasked_float_array
    return np.asarray(x, float)
  File "/group/monte/tools/rhel7_64/core-12/lib/python3.9/site-packages/numpy/core/_asarray.py", line 102, in asarray
    return array(a, dtype, copy=False, order=order)
TypeError: float() argument must be a string or a number, not 'UnitDbl'
```

### Expected outcome

A 3d plot.

### Matplotlib Version

3.5.0

### Matplotlib Backend

QtAgg

### Python version

3.9.7

**Comment by oscargus** [comment]
Duplicate of #8762

**Comment by TD22057** [comment]
Is there so reason this is "not planned"?  This is more general than bug #8762 as that bug just says dates while this is explicit about it being units.  I'd be worried that someone will add date support without adding the correct unit conversion calls which are what's required for general unit support which this bug tries to indicate.

**Comment by jklymak** [comment]
I think it's true this is a duplicate, but I also think this version of the report is a lot more clear as to original problem.   If @oscargus doesn't mind, I'll re-open, and close the other one.

**Comment by oscargus** [comment]
I'm OK with that, just want to clarify that "not planned" includes "Won't fix, can't repro, duplicate, stale" and selecting the other available option means that it will look as it has been fixed...

**Comment by oscargus** [comment]
As there is work to test date handling (as part of general unit handling), I came back to this and just wanted to add a date test case here as well:

```python
import matplotlib.pyplot as plt        
N = 6
fig, ax = plt.subplots(subplot_kw={'projection': '3d'})
x = np.array([datetime.datetime(2023, 9, n) for n in range(1, N)])
z = np.array([datetime.datetime(2023, 10, n) for n in range(1, N)])
ax.plot(x, z, range(1, N))
```

This gives (the rather long)
```
Traceback (most recent call last):

  Cell In[20], line 6
    ax.plot(x, z, range(1, N))

  File /local/data1/miniconda3/lib/python3.10/site-packages/mpl_toolkits/mplot3d/axes3d.py:1918 in plot
    self.auto_scale_xyz(xs, ys, zs, had_data)

  File /local/data1/miniconda3/lib/python3.10/site-packages/mpl_toolkits/mplot3d/axes3d.py:619 in auto_scale_xyz
    self.xy_dataLim.update_from_data_xy(

  File /local/data1/miniconda3/lib/python3.10/site-packages/matplotlib/transforms.py:952 in update_from_data_xy
    path = Path(xy)

  File /local/data1/miniconda3/lib/python3.10/site-packages/matplotlib/path.py:129 in __init__
    vertices = _to_unmasked_float_array(vertices)

  File /local/data1/miniconda3/lib/python3.10/site-packages/matplotlib/cbook.py:1383 in _to_unmasked_float_array
    return np.asarray(x, float)

TypeError: float() argument must be a string or a real number, not 'datetime.datetime'

Error in callback <function _draw_all_if_interactive at 0x7f21b3b64310> (for post_execute), with arguments args (),kwargs {}:
Traceback (most recent call last):

  File /local/data1/miniconda3/lib/python3.10/site-packages/matplotlib/pyplot.py:196 in _draw_all_if_interactive
    draw_all()

  File /local/data1/miniconda3/lib/python3.10/site-packages/matplotlib/_pylab_helpers.py:132 in draw_all
    manager.canvas.draw_idle()

  File /local/data1/miniconda3/lib/python3.10/site-packages/matplotlib/backend_bases.py:1936 in draw_idle
    self.draw(*args, **kwargs)

  File /local/data1/miniconda3/lib/python3.10/site-packages/matplotlib/backends/backend_agg.py:387 in draw
    self.figure.draw(self.renderer)

  File /local/data1/miniconda3/lib/python3.10/site-packages/matplotlib/artist.py:95 in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)

  File /local/data1/miniconda3/lib/python3.10/site-packages/matplotlib/artist.py:72 in draw_wrapper
    return draw(artist, renderer)

  File /local/data1/miniconda3/lib/python3.10/site-packages/matplotlib/figure.py:3104 in draw
    mimage._draw_list_compositing_images(

  File /local/data1/miniconda3/lib/python3.10/site-packages/matplotlib/image.py:132 in _draw_list_compositing_images
    a.draw(renderer)

  File /local/data1/miniconda3/lib/python3.10/site-packages/matplotlib/artist.py:72 in draw_wrapper
    return draw(artist, renderer)

  File /local/data1/miniconda3/lib/python3.10/site-packages/mpl_toolkits/mplot3d/axes3d.py:487 in draw
    super().draw(renderer)

  File /local/data1/miniconda3/lib/python3.10/site-packages/matplotlib/artist.py:72 in draw_wrapper
    return draw(artist, renderer)

  File /local/data1/miniconda3/lib/python3.10/site-packages/matplotlib/axes/_base.py:3095 in draw
    mimage._draw_list_compositing_images(

  File /local/data1/miniconda3/lib/python3.10/site-packages/matplotlib/image.py:132 in _draw_list_compositing_images
    a.draw(renderer)

  File /local/data1/miniconda3/lib/python3.10/site-packages/matplotlib/artist.py:72 in draw_wrapper
    return draw(artist, renderer)

  File /local/data1/miniconda3/lib/python3.10/site-packages/mpl_toolkits/mplot3d/art3d.py:270 in draw
    xs, ys, zs = proj3d.proj_transform(xs3d, ys3d, zs3d, self.axes.M)

  File /local/data1/miniconda3/lib/python3.10/site-packages/mpl_toolkits/mplot3d/proj3d.py:215 in proj_transform
    return _proj_transform_vec(vec, M)

  File /local/data1/miniconda3/lib/python3.10/site-packages/mpl_toolkits/mplot3d/proj3d.py:174 in _proj_transform_vec
    vecw = np.dot(M, vec)

TypeError: unsupported operand type(s) for *: 'float' and 'datetime.datetime'

Traceback (most recent call last):

  File /local/data1/miniconda3/lib/python3.10/site-packages/IPython/core/formatters.py:340 in __call__
    return printer(obj)

  File /local/data1/miniconda3/lib/python3.10/site-packages/IPython/core/pylabtools.py:152 in print_figure
    fig.canvas.print_figure(bytes_io, **kw)

  File /local/data1/miniconda3/lib/python3.10/site-packages/matplotlib/backend_bases.py:2207 in print_figure
    self.figure.draw(renderer)

  File /local/data1/miniconda3/lib/python3.10/site-packages/matplotlib/artist.py:95 in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)

  File /local/data1/miniconda3/lib/python3.10/site-packages/matplotlib/artist.py:72 in draw_wrapper
    return draw(artist, renderer)

  File /local/data1/miniconda3/lib/python3.10/site-packages/matplotlib/figure.py:3104 in draw
    mimage._draw_list_compositing_images(

  File /local/data1/miniconda3/lib/python3.10/site-packages/matplotlib/image.py:132 in _draw_list_compositing_images
    a.draw(renderer)

  File /local/data1/miniconda3/lib/python3.10/site-packages/matplotlib/artist.py:72 in draw_wrapper
    return draw(artist, renderer)

  File /local/data1/miniconda3/lib/python3.10/site-packages/mpl_toolkits/mplot3d/axes3d.py:487 in draw
    super().draw(renderer)

  File /local/data1/miniconda3/lib/python3.10/site-packages/matplotlib/artist.py:72 in draw_wrapper
    return draw(artist, renderer)

  File /local/data1/miniconda3/lib/python3.10/site-packages/matplotlib/axes/_base.py:3095 in draw
    mimage._draw_list_compositing_images(

  File /local/data1/miniconda3/lib/python3.10/site-packages/matplotlib/image.py:132 in _draw_list_compositing_images
    a.draw(renderer)

  File /local/data1/miniconda3/lib/python3.10/site-packages/matplotlib/artist.py:72 in draw_wrapper
    return draw(artist, renderer)

  File /local/data1/miniconda3/lib/python3.10/site-packages/mpl_toolkits/mplot3d/art3d.py:270 in draw
    xs, ys, zs = proj3d.proj_transform(xs3d, ys3d, zs3d, self.axes.M)

  File /local/data1/miniconda3/lib/python3.10/site-packages/mpl_toolkits/mplot3d/proj3d.py:215 in proj_transform
    return _proj_transform_vec(vec, M)

  File /local/data1/miniconda3/lib/python3.10/site-packages/mpl_toolkits/mplot3d/proj3d.py:174 in _proj_transform_vec
    vecw = np.dot(M, vec)

TypeError: unsupported operand type(s) for *: 'float' and 'datetime.datetime'
```

**Comment by oscargus** [comment]
Also, the original code now has a slightly different (initial) path to the exception message:
```
Traceback (most recent call last):

  Cell In[21], line 12
    ax.plot(x, y, z)

  File /local/data1/miniconda3/lib/python3.10/site-packages/mpl_toolkits/mplot3d/axes3d.py:1915 in plot
    art3d.line_2d_to_3d(line, zs=zs, zdir=zdir)

  File /local/data1/miniconda3/lib/python3.10/site-packages/mpl_toolkits/mplot3d/art3d.py:290 in line_2d_to_3d
    line.set_3d_properties(zs, zdir)

  File /local/data1/miniconda3/lib/python3.10/site-packages/mpl_toolkits/mplot3d/art3d.py:226 in set_3d_properties
    zs = cbook._to_unmasked_float_array(zs).ravel()

  File /local/data1/miniconda3/lib/python3.10/site-packages/matplotlib/cbook.py:1383 in _to_unmasked_float_array
    return np.asarray(x, float)

TypeError: float() argument must be a string or a real number, not 'UnitDbl'
```
