### ISSUE TITLE
[Bug]: Unable to twinx an axis with sharex=True

### ISSUE THREAD

**Issue by madphysicist** [matplotlib/matplotlib#22335]
### Bug summary

If I create subplot axes with `sharex=True` and `sharey=True`, I can not `twinx` one of them later to set a different formatter on the y-axis.

### Code for reproduction

```python
from matplotlib import pyplot as plt
from matplotlib.ticker import FuncFormatter
import numpy as np

fig, ax = plt.subplots(1, 2, sharex=True, sharey=True)
ax[0].imshow(np.arange(100).reshape(10, 10))
ax[1].imshow(np.arange(0, -100, -1).reshape(10, 10))
ax[0].set_ylabel('Left')
ax[0].yaxis.set_major_formatter(FuncFormatter(lambda x, pos: f'{x + 1}'))

# So far so good

ax1b = ax[1].twinx()
ax1b.set_ylabel('Right')
ax1b.yaxis.set_major_formatter(FuncFormatter(lambda x, pos: f'{1 - x}'))
```

### Actual outcome

Up to `# So far so good`, the output looks normal:

![image](https://user-images.githubusercontent.com/4617010/151402167-a4e84412-eba6-44c1-8f4d-b01f56338f40.png)

The next line (`twinx`) raises errors and the figure does not render correctly any more:

![image](https://user-images.githubusercontent.com/4617010/151402460-93504ba6-a8ef-43e9-ae29-748e51ed50bf.png)

```
Traceback (most recent call last):
  File "C:\Users\madphysicist\Anaconda3\lib\site-packages\matplotlib\backends\backend_qt5.py", line 480, in _draw_idle
    self.draw()
  File "C:\Users\madphysicist\Anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py", line 407, in draw
    self.figure.draw(self.renderer)
  File "C:\Users\madphysicist\Anaconda3\lib\site-packages\matplotlib\artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\Users\madphysicist\Anaconda3\lib\site-packages\matplotlib\figure.py", line 1840, in draw
    ax.apply_aspect()
  File "C:\Users\madphysicist\Anaconda3\lib\site-packages\matplotlib\axes\_base.py", line 1661, in apply_aspect
    raise RuntimeError("adjustable='datalim' is not allowed when both "
RuntimeError: adjustable='datalim' is not allowed when both axes are shared
```

### Expected outcome

Something like this:

![image](https://user-images.githubusercontent.com/4617010/151404251-e9b4d4c6-2d4e-4af2-9382-d07e654f9523.png)

### Additional information

Probably something to do with autoscaling and the fact that twinned axes share a Ticker object.

I can hack around to get the desired functionality thusly (based on #10911, among others):

```
ax[1].yaxis.set_label_position('right')
ax[1].yaxis.tick_right()
ax[1].yaxis.set_tick_params(which='both', labelright=True)
ax[1].yaxis.major = Ticker()
ax[1].yaxis.set_major_locator(ax[0].yaxis.get_major_locator())
ax[1].yaxis.set_major_formatter(FuncFormatter(lambda x, pos: f'{1 - x}'))
ax[1].set_ylabel('Sampling Frequency (Hz)')
```

The axis label shows up correctly, and the axes behave, but I can't get the tick labels to show up at all.

### Operating system

Windows

### Matplotlib Version

3.3.4

### Matplotlib Backend

Qt5Agg

### Python version

3.8.8

### Jupyter version

N/A

### Installation

conda

**Comment by jklymak** [comment]
Do you need the second axis to be a twin?  We have secondary_yaxis if all you want is a secondary y axis...

**Comment by madphysicist** [comment]
@jklymak I don't need it to be a twin, but I do need it to share the same x and y as all the other subplots I've set up. I'll experiment with `secondary_yaxis` it likely does exactly what I actually want. Would you say that this issue is a non-issue?

**Comment by tacaswell** [comment]
The source of the issue is that `imshow` impliticly sets the aspect.  If you remove the `imshow` calls it works.

I think the underlying problem is that we have (in a possibly clumsy and overly cautious way) identified that the system is over-constrained and are giving up.  The constraints we have are:

 - ax1 is equal aspect (that 1 data x unit = 1 data y unit)
 - ax2 is equal aspect (ditto)
 - ax1 xlimits equal ax2 xlimits
 - ax1 y limits equal ax1 ylimits
 - ax2b xlimits match ax2 xlimits
 - the screen size of ax2b exactly match the screen size of ax2

I think there is always a consistent way to this, but something about how we encode this is tripping us up.  

We also had a class of bugs a while ago with fixed aspect, shared axes, and twin axes where the iterative process we used to size everything got in an infinite loop (set the screen size of ax1/ax2 -> change data limits of ax2b -> change screen size of ax2 -> change ax2b -> ...).  I suspect that this exception is one of the circuit breakers from fixing those bugs.

**Comment by madphysicist** [comment]
@tacaswell. Thanks. I'll leave this open for now as a very low priority. If I have time to look at it myself, or someone else does in the meantime, maybe we can find a fix. It seems like there is at least one reasonable workaround available in the meantime.
