### ISSUE TITLE
I want to plot winds on precipitation but i got the errors

### ISSUE THREAD

**Issue by sujathasujji** [matplotlib/matplotlib#22404]
### Bug summary

I have model output data from that I had extracted u,v and precipitation by using CDO,now I want to plot the winds and precipitation in one plot but when I am trying to run my script it shows some errors regarding quiver.kindly help me.

### Code for reproduction

```python
import xarray as xr
import cartopy.crs as ccrs
from cartopy import feature as cf
import matplotlib.pyplot as plt
import numpy as np
data=xr.open_dataset("uvrainregcm2014.nc")
print(data)
x=data.xlon[::5];
y=data.xlat[::5]
pr=data.pr[::5]
ua=data.ua[0,0,::5,::5];
va=data.va[0,0,::5,::5]
time=data.time[0]

east = 100
west = 60
north = 38
south = 0

ax = plt.axes(projection=ccrs.PlateCarree())
pr.isel(time=1).plot.pcolormesh(cmap="viridis", ax = ax)
ax.set_extent([west, east, south, north])
ax.coastlines()

ax.quiver(x,y,ua,va, angles='xy', scale_units='xy', scale=4)

plt.savefig("winds.jpg")
plt.show()
```

### Actual outcome

Traceback (most recent call last):
  File "pythonscript.py", line 40, in <module>
    ax.quiver(x,y,ua,va, angles='xy', scale_units='xy', scale=4)
  File "/home/user/.local/lib/python3.8/site-packages/cartopy/mpl/geoaxes.py", line 321, in wrapper
    return func(self, *args, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/cartopy/mpl/geoaxes.py", line 1966, in quiver
    return matplotlib.axes.Axes.quiver(self, x, y, u, v, *args, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/matplotlib/__init__.py", line 1412, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/matplotlib/axes/_axes.py", line 4942, in quiver
    q = mquiver.Quiver(self, *args, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/matplotlib/quiver.py", line 510, in __init__
    self.set_UVC(U, V, C)
  File "/home/user/.local/lib/python3.8/site-packages/matplotlib/quiver.py", line 579, in set_UVC
    raise ValueError(f'Argument {name} has a size {var.size}'
ValueError: Argument U has a size 1920 which does not match 6048, the number of arrow positions

### Expected outcome

winds over the precipitation

### Matplotlib Version

3.4.3

### Python version

python3

**Comment by jklymak** [comment]
Please take user help to discourse.matplotlib.org.  Thanks!
