### ISSUE TITLE
[Bug]: SIGSEGV segfault when plotting multiple subplots

### ISSUE THREAD

**Issue by JackKelly** [matplotlib/matplotlib#22478]
## 🐛 Bug

I'm using matplotlib to create plots whilst training neural networks using [PyTorch](https://pytorch.org/) and [pytorch-lightning](https://www.pytorchlightning.ai/).

If I create specific, simple `matplotlib` plots during `training_step` then I get a segfault after training for several iterations.

I originally raised [this issue on the pytorch-lightning issue queue](https://github.com/PyTorchLightning/pytorch-lightning/issues/11925) but it was concluded that this error is likely coming from `matplotlib` rather than from `pytorch-lighting`.

Specifically, if I call `plot_data()` from within `training_step`, then I get a segfault:

```python
def plot_data():
    """Plot random data."""
    fig, axes = plt.subplots(ncols=4)  # See note 1 below.
    N_PERIODS = 16
    x = pd.date_range(START_DATE, periods=N_PERIODS, freq="30 min")  # See note 2 below.
    y = np.ones(N_PERIODS)
    for ax in axes:
        ax.plot(x, y)
    plt.close(fig)
```

Interestingly, I've found two ways to stop the segfaults. You can do one or the other (or both) of these actions to stop the segfaults:

1. Change `ncols` to one of `{2, 3, 5, 6, 7, 9, 10}`.  segfaults only seem to appear if `ncols` is one of `{4, 8, 16, 32}`
2. Convert `x` from a `pd.DatetimeIndex` to a numpy array of matplotlib dates by doing `x = matplotlib.dates.date2num(x)` after line 1.

If I run `gdb --args python script.py` I get this:

```
Epoch 0:   1%|█▏| 7/1024 [00:01<02:52,  5.90it/s, loss=0.281, v_num=34]
Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0x000055555568bb4b in _PyObject_GC_UNTRACK_impl (filename=0x55555587fef0 
"/home/conda/feedstock_root/build_artifacts/python-split_1643749964416/work/Modules/gcmodule.c", lineno=2236, 
op=0x7fffd05f5e00) at /home/conda/feedstock_root/build_artifacts/python-
split_1643749964416/work/Include/internal/pycore_object.h:76
76  /home/conda/feedstock_root/build_artifacts/python-split_1643749964416/work/Include/internal/pycore_object.h:
 No such file or directory.
```

The minimal code example below seems to always crash whilst training on epoch 7.

In my "real" code, the crash was intermittent.

If `ncols` is large (e.g. 32) then the crash changes randomly between:

* `SIGSEGV` segfault
* `AttributeError: 'weakref' object has no attribute 'grad_fn'`
* `AttributeError: 'builtin_function_or_method' object has no attribute 'grad_fn'`

The two `AttributeErrors` originate from the same bit of code: line 213 of `torch/optim/optimizer.py`: `if p.grad.grad_fn is not None:`.  My guess is that the `SIGSEGV` is the root problem, and the `AttributeErrors` are _symptoms_ of the underlying `SIGSEGV` error. I have (once) seen the code compain, at the same time, about a `SIGSEGV` and an `AttributeError`.

Please see [this comment](https://github.com/PyTorchLightning/pytorch-lightning/issues/11925#issuecomment-1041331457) for some debugging that @justusschock did this morning.

### Code for reproduction

```python
These scripts are in a tiny GitHub repo for this bug report: https://github.com/JackKelly/pytorch-lighting-segfault


import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import pandas as pd
import numpy as np
import torch
from torch import nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
import pytorch_lightning as pl


START_DATE = pd.Timestamp("2020-01-01")
N_EXAMPLES_PER_BATCH = 32
N_FEATURES = 1


class MyDataset(Dataset):
    def __init__(self, n_batches_per_epoch: int):
        self.n_batches_per_epoch = n_batches_per_epoch

    def __len__(self):
        return self.n_batches_per_epoch

    def __getitem__(self, idx: int) -> tuple[torch.Tensor, torch.Tensor]:
        x = torch.rand(N_EXAMPLES_PER_BATCH, N_FEATURES, 1)
        y = torch.rand(N_EXAMPLES_PER_BATCH, 1)
        return x, y


class LitNeuralNetwork(pl.LightningModule):
    def __init__(self):
        super().__init__()
        self.flatten = nn.Flatten()
        self.nn = nn.Linear(in_features=N_FEATURES, out_features=1)

    def forward(self, x):
        x = self.flatten(x)
        return self.nn(x)

    def training_step(self, batch, batch_idx):
        x, y = batch
        y_hat = self(x)
        loss = F.mse_loss(y_hat, y)
        plot_data()
        return loss

    def configure_optimizers(self):
        return torch.optim.Adam(self.parameters(), lr=0.001)


def plot_data():
    """Plot random data."""
    # ncols needs to be 4 or higher to trigger a segfault.
    fig, axes = plt.subplots(ncols=4)
    N_PERIODS = 16
    x = pd.date_range(START_DATE, periods=N_PERIODS, freq="30 min")
    # The segfaults go away if I do:
    # x = mdates.date2num(x)
    y = np.ones(N_PERIODS)
    for ax in axes:
        ax.plot(x, y)
    plt.close(fig)


dataloader = DataLoader(
    MyDataset(n_batches_per_epoch=1024),
    batch_size=None,
    num_workers=2,
)

model = LitNeuralNetwork()
trainer = pl.Trainer()
trainer.fit(model=model, train_dataloader=dataloader)



Here's my `environment.yml` file:

```yaml
name: segfault
channels:
  - conda-forge
  - pytorch
dependencies:
  - matplotlib
  - pandas
  - pytorch
  - cpuonly 
  - pytorch-lightning
```
```


### Actual outcome

If `ncols` is large (e.g. 32) then the crash changes randomly between:

* `SIGSEGV` segfault
* `AttributeError: 'weakref' object has no attribute 'grad_fn'`
* `AttributeError: 'builtin_function_or_method' object has no attribute 'grad_fn'`

### Expected outcome

No segfault :slightly_smiling_face: 

### Additional information

I have tried and failed to reproduce this problem in two simpler scripts:

* A script which _just_ uses matplotlib and pandas (no pytorch.  no pytorch-lightning)
* A script which _just_ uses matplotlib, pandas and pytorch (no pytorch-lightning).


### Operating system

Ubuntu 21.10

### Matplotlib Version

3.5.1

### Matplotlib Backend

QtAgg

### Python version

3.9.10

### Jupyter version

_No response_

### Installation

conda

**Comment by tacaswell** [comment]
Can you run this with https://docs.python.org/3/library/faulthandler.html ?

**Comment by JackKelly** [comment]
Ooh, that's clever! Here's the output when using `faulthandler`:

```
(segfault) jack@jack-NUC:~/dev/ocf/segfault$ python -X faulthandler pytorch-lightning.py
GPU available: False, used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py:735: LightningDeprecationWarning: `trainer.fit(train_dataloader)` is deprecated in v1.4 and will be removed in v1.6. Use `trainer.fit(train_dataloaders)` instead. HINT: added 's'
  rank_zero_deprecation(

  | Name    | Type    | Params
------------------------------------
0 | flatten | Flatten | 0     
1 | nn      | Linear  | 2     
------------------------------------
2         Trainable params
0         Non-trainable params
2         Total params
0.000     Total estimated model params size (MB)
/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/pytorch_lightning/trainer/data_loading.py:132: UserWarning: The dataloader, train_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 8 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
Epoch 0:   0%|                                                                                                                                                                                                       | 0/1024 [00:00<?, ?it/s]Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Epoch 0:   1%|█▏                                                                                                                                                                        | 7/1024 [00:01<04:14,  4.00it/s, loss=1.65, v_num=68]Fatal Python error: Segmentation fault

Thread 0x00007fc977fff640 (most recent call first):
<no Python frame>

Thread 0x00007fc98eabd640 (most recent call first):
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/threading.py", line 312 in wait
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/multiprocessing/queues.py", line 233 in _feed
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/threading.py", line 910 in run
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc98f2be640 (most recent call first):
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/threading.py", line 312 in wait
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/multiprocessing/queues.py", line 233 in _feed
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/threading.py", line 910 in run
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/threading.py", line 930 in _bootstrap

Thread 0x00007fc98fac5640 (most recent call first):
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/threading.py", line 316 in wait
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/threading.py", line 574 in wait
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/tqdm/_monitor.py", line 60 in run
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/threading.py", line 973 in _bootstrap_inner
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/threading.py", line 930 in _bootstrap

Current thread 0x00007fc9b690e740 (most recent call first):
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/torch/optim/optimizer.py", line 213 in zero_grad
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/pytorch_lightning/core/lightning.py", line 1675 in optimizer_zero_grad
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py", line 344 in optimizer_zero_grad
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 409 in _optimizer_zero_grad
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 313 in zero_grad_fn
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 151 in closure
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 160 in __call__
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 148 in _wrap_closure
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/torch/optim/adam.py", line 92 in step
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 28 in decorate_context
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/torch/optim/optimizer.py", line 88 in wrapper
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 163 in optimizer_step
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py", line 339 in optimizer_step
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/pytorch_lightning/core/optimizer.py", line 164 in step
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/pytorch_lightning/core/lightning.py", line 1652 in optimizer_step
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 378 in _optimizer_step
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 266 in _run_optimization
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 215 in advance
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 145 in run
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 88 in advance
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 145 in run
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 193 in advance
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 145 in run
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/pytorch_lightning/loops/fit_loop.py", line 234 in advance
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 145 in run
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1319 in _run_train
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1289 in run_stage
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 202 in start_training
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1279 in _dispatch
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1199 in _run
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 777 in _fit_impl
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 685 in _call_and_handle_interrupt
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 740 in fit
  File "/home/jack/dev/ocf/segfault/pytorch-lightning.py", line 77 in <module>
Segmentation fault (core dumped)
```

**Comment by JackKelly** [comment]
And here's the stack trace with when the code doesn't segfault, but instead fails with an `AttributeError`:

```
(segfault) jack@jack-NUC:~/dev/ocf/segfault$ python -X faulthandler pytorch-lightning.py
GPU available: False, used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py:735: LightningDeprecationWarning: `trainer.fit(train_dataloader)` is deprecated in v1.4 and will be removed in v1.6. Use `trainer.fit(train_dataloaders)` instead. HINT: added 's'
  rank_zero_deprecation(

  | Name    | Type    | Params
------------------------------------
0 | flatten | Flatten | 0     
1 | nn      | Linear  | 2     
------------------------------------
2         Trainable params
0         Non-trainable params
2         Total params
0.000     Total estimated model params size (MB)
/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/pytorch_lightning/trainer/data_loading.py:132: UserWarning: The dataloader, train_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 8 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
Epoch 0:   0%|                                                                                                                                                                                                       | 0/1024 [00:00<?, ?it/s]Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Epoch 0:   1%|█▏                                                                                                                                                                        | 7/1024 [00:01<03:52,  4.37it/s, loss=1.71, v_num=69]Traceback (most recent call last):
  File "/home/jack/dev/ocf/segfault/pytorch-lightning.py", line 77, in <module>
    trainer.fit(model=model, train_dataloader=dataloader)
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 740, in fit
    self._call_and_handle_interrupt(
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 685, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 777, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1199, in _run
    self._dispatch()
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1279, in _dispatch
    self.training_type_plugin.start_training(self)
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 202, in start_training
    self._results = trainer.run_stage()
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1289, in run_stage
    return self._run_train()
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1319, in _run_train
    self.fit_loop.run()
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/pytorch_lightning/loops/fit_loop.py", line 234, in advance
    self.epoch_loop.run(data_fetcher)
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 193, in advance
    batch_output = self.batch_loop.run(batch, batch_idx)
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 88, in advance
    outputs = self.optimizer_loop.run(split_batch, optimizers, batch_idx)
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 215, in advance
    result = self._run_optimization(
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 266, in _run_optimization
    self._optimizer_step(optimizer, opt_idx, batch_idx, closure)
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 378, in _optimizer_step
    lightning_module.optimizer_step(
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/pytorch_lightning/core/lightning.py", line 1652, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/pytorch_lightning/core/optimizer.py", line 164, in step
    trainer.accelerator.optimizer_step(self._optimizer, self._optimizer_idx, closure, **kwargs)
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py", line 339, in optimizer_step
    self.precision_plugin.optimizer_step(model, optimizer, opt_idx, closure, **kwargs)
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 163, in optimizer_step
    optimizer.step(closure=closure, **kwargs)
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/torch/optim/optimizer.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/torch/optim/adam.py", line 92, in step
    loss = closure()
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 148, in _wrap_closure
    closure_result = closure()
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 160, in __call__
    self._result = self.closure(*args, **kwargs)
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 151, in closure
    self._zero_grad_fn()
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 313, in zero_grad_fn
    self._optimizer_zero_grad(batch_idx, optimizer, opt_idx)
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 409, in _optimizer_zero_grad
    self.trainer.accelerator.optimizer_zero_grad(self.trainer.current_epoch, batch_idx, optimizer, opt_idx)
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py", line 344, in optimizer_zero_grad
    model_ref.optimizer_zero_grad(current_epoch, batch_idx, optimizer, opt_idx)
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/pytorch_lightning/core/lightning.py", line 1675, in optimizer_zero_grad
    optimizer.zero_grad()
  File "/home/jack/miniconda3/envs/segfault/lib/python3.9/site-packages/torch/optim/optimizer.py", line 213, in zero_grad
    if p.grad.grad_fn is not None:
AttributeError: 'weakref' object has no attribute 'grad_fn'
```

**Comment by jklymak** [comment]
What happens if you don't use pandas to create the dates?

**Comment by JackKelly** [comment]
Great question!

I haven't explicitly tested _creating_ the dates without pandas. But if we first _convert_ the dates then the code works fine (no segfault):

```python
x = pd.date_range(START_DATE, periods=N_PERIODS, freq="30 min")
# The segfaults go away if we include the following line:
x = mdates.date2num(x)
```

**Comment by tacaswell** [comment]
There is nothing from Matplotlib in any of those traces, I am skeptical that we are directly involved.  My knee-jerk guess is that with the plotting involved the garbage collector is being fired more often or changing the timing so you are now losing some race in pytorch / lightning that without plotting you were winning.

It is also possible that when you pass in the series we hold a reference to the original (I think) so that may be keeping somethings alive longer.

On balance, the fact that different numbers of columns affect if it crashes or not makes be lean more towards there being some sort of race-condition.

In a game of open-source hot-potato, I think this should be kicked back to pytorch-lightning.  Looking at https://github.com/PyTorchLightning/pytorch-lightning/issues/11925#issuecomment-1041331457 I am very worried about

```python
>> for p in old_params:
>>     print(p.grad)
None
None
>> for p in self.parameters():
>>     print(p.grad)
<built-in method pop of dict object at 0x7f44eca02540>
<weakref at 0x7f44d5510f90; to 'CompositeGenericTransform' at 0x7f44ec9e6cd0>
```

from @justusschock 's debugging.  As near as I can tell 'grad' never shows up as a name in the Matplotlib code base so I do not think we are setting the grad.   I'm also _super_ confused how `pop` would show up as grad, but `CompositeGenericTransform` is definitely one of our classes.  

This is weird enough that my guess is that under the hood pytorch/pytoch-lightning is keeping pointers to python objects without properly reference counting them, the objects are getting cleaned up, and then because Python uses an object pool that object is getting resurrected as a new object.  I do not have a clear explanation of how the  `grad` is getting miss-mapped to some other attribute (but my guess is that `Paramaters` is slotted so there is a index-based jump-table in there someplace). This would certainly explain the segfaults in the case when the object did not get resurrected and now instead of grabbing the wrong attribute it is looking at a null pointer.

**Comment by jklymak** [comment]
Instead of the plot can he insert some other expensive calculation that doesn't involve matplotlib?   Or is the problem that we also need to grab a bunch of pointers from memory?

**Comment by tacaswell** [comment]
I suggested `gc.collect()` calls to force the issue.  Lets try to keep the discussion over in the pytoch-lightning issue.

**Comment by tacaswell** [comment]
In pytorch/pytorch#74188 it is reported that it does not segfault with main but does segfault with 3.5.1 both built from source.

That strongly suggests that this is on us, but I do not have the faintest idea as to how (unless it really is just getting (un)lucky with gc cycles and we changed enough to go from bad to good?).

**Comment by benjaminrwilson** [comment]
@JackKelly, were you able to resolve this? I'm seeing this on my end now too.

**Comment by JackKelly** [comment]
I'm afraid this is way above my abilities to resolve :slightly_smiling_face: I think that fixing this requires someone who knows the innards of matplotlib much better than me.

I'm just working around the issue using the tricks described in the top post

**Comment by jklymak** [comment]
> What happens if you don't use pandas to create the dates?

This seems to have been lost in the debugging - if converting pandas dates to floats or numpy dates stops the problem, then its hard to implicate Matplotlib here.  If folks can confirm that dropping pandas from the equation stops the segfaults, then I think we can hot potato to pandas?

**Comment by JackKelly** [comment]
Yes, in my original exploration of this issue, I found that I could stop the segfault by converting `x` from a `pd.DatetimeIndex` to a numpy array of matplotlib dates by doing `x = matplotlib.dates.date2num(x)` after line 1.

**Comment by jklymak** [comment]
Unless you disable them, pandas registers their own converters to go from pandas dates to numpy floats when we plot. Eg they don't use date2num. 

Can you deregister the pandas converters and see if you still have the memory leak?  If not, can you just convert from pandas to float using their converters without using matplotlib at all and trigger a leak?  If so, this would implicate pandas datetime converters somehow.  I have no idea if those are impoimented in c at all, or why that might cause a segfault, but if we can narrow this down more, it would be helpful.

**Comment by tacaswell** [comment]
I suspect that if we bisect this on our side it is going to land on a commit where we get lazier (or less lazy!) and changed the timing / contents of a garbage collection cycle.....

**Comment by tacaswell** [comment]
I can not reproduce installing stable everything from pypi using https://github.com/JackKelly/pytorch-lighting-segfault/blob/main/pytorch.py


https://github.com/JackKelly/pytorch-lighting-segfault/blob/main/pytorch-lightning.py fails due to a changed API on `trainer.fit`.

```
$ pip list
Package                 Version
----------------------- ---------
absl-py                 1.0.0
aiohttp                 3.8.1
aiosignal               1.2.0
async-timeout           4.0.2
attrs                   21.4.0
cachetools              5.0.0
certifi                 2021.10.8
charset-normalizer      2.0.12
cycler                  0.11.0
fonttools               4.32.0
frozenlist              1.3.0
fsspec                  2022.3.0
google-auth             2.6.3
google-auth-oauthlib    0.4.6
grpcio                  1.44.0
idna                    3.3
kiwisolver              1.4.2
Markdown                3.3.6
matplotlib              3.5.1
multidict               6.0.2
numpy                   1.22.3
oauthlib                3.2.0
packaging               21.3
pandas                  1.4.2
Pillow                  9.1.0
pip                     22.0.4
protobuf                3.20.0
pyasn1                  0.4.8
pyasn1-modules          0.2.8
pyDeprecate             0.3.2
pyparsing               3.0.7
python-dateutil         2.8.2
pytorch-lightning       1.6.0
pytz                    2022.1
PyYAML                  6.0
requests                2.27.1
requests-oauthlib       1.3.1
rsa                     4.8
setuptools              58.1.0
six                     1.16.0
tensorboard             2.8.0
tensorboard-data-server 0.6.1
tensorboard-plugin-wit  1.8.1
torch                   1.11.0
torchmetrics            0.7.3
tqdm                    4.64.0
typing_extensions       4.1.1
urllib3                 1.26.9
Werkzeug                2.1.1
wheel                   0.37.1
yarl                    1.7.2

```

**Comment by justusschock** [comment]
@tacaswell to reproduce and avoid API changes, stick to `pytorch-lightning<1.6.0`

**Comment by JackKelly** [comment]
> to reproduce and avoid API changes, stick to pytorch-lightning<1.6.0

Ah, good catch! I've just edited my [pytorch-lightning.py](https://github.com/JackKelly/pytorch-lighting-segfault/blob/main/pytorch-lightning.py) file, which will hopefully make it compatible with any recent version of pytorch lightning! (although I haven't tested it!)

**Comment by tacaswell** [comment]
Given that this has gone quiet and I still think that this is an upstream (or build) issue (and upstream closed their issue https://github.com/pytorch/pytorch/issues/74188) that just happens to be hitting mpl I'm going to close this.

If this still reproduces please ping to have re-opened or open a new issue.
