### ISSUE TITLE
[Bug]: Passing vmin, vmax to LogNorm raises ValueError: Passing parameters norm and vmin/vmax simultaneously is not supported

### ISSUE THREAD

**Issue by RylanSchaeffer** [matplotlib/matplotlib#22518]
### Bug summary

Passing `vmin` & `vmax` to `LogNorm` raises "ValueError: Passing parameters norm and vmin/vmax simultaneously is not supported. Please pass vmin/vmax directly to the norm when creating it."

### Code for reproduction

```python
sns.heatmap(avg_sampled_customer_assignments_by_customer,
                ax=ax,
                mask=np.isnan(avg_sampled_customer_assignments_by_customer),
                cmap='Spectral',
                norm=LogNorm(vmin=cutoff, vmax=1.),
                )
```

### Actual outcome

```
Traceback (most recent call last):
  File "00_prior/run_one.py", line 317, in <module>
    run_one(args)
  File "00_prior/run_one.py", line 66, in run_one
    dynamics_latex_str=dynamics_latex_str)
  File "/net/vast-storage.ib.cluster/scratch/vast/fiete/rylansch/FieteLab-Recursive-Nonstationary-CRP/00_prior/plot.py", line 47, in plot_customer_assignments_analytical_vs_monte_carlo
    norm=LogNorm(cutoff, 1.),
  File "/rdma/vast-rdma/vast/fiete/rylansch/FieteLab-Recursive-Nonstationary-CRP/rncrp_venv/lib/python3.7/site-packages/seaborn/matrix.py", line 525, in heatmap
    plotter.plot(ax, cbar_ax, kwargs)
  File "/rdma/vast-rdma/vast/fiete/rylansch/FieteLab-Recursive-Nonstationary-CRP/rncrp_venv/lib/python3.7/site-packages/seaborn/matrix.py", line 279, in plot
    cmap=self.cmap, **kws)
  File "/rdma/vast-rdma/vast/fiete/rylansch/FieteLab-Recursive-Nonstationary-CRP/rncrp_venv/lib/python3.7/site-packages/matplotlib/__init__.py", line 1412, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/rdma/vast-rdma/vast/fiete/rylansch/FieteLab-Recursive-Nonstationary-CRP/rncrp_venv/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 6073, in pcolormesh
    collection._scale_norm(norm, vmin, vmax)
  File "/rdma/vast-rdma/vast/fiete/rylansch/FieteLab-Recursive-Nonstationary-CRP/rncrp_venv/lib/python3.7/site-packages/matplotlib/cm.py", line 381, in _scale_norm
    "Passing parameters norm and vmin/vmax simultaneously is "
ValueError: Passing parameters norm and vmin/vmax simultaneously is not supported. Please pass vmin/vmax directly to the norm when creating it.
```

### Expected outcome

No error is raised.

### Operating system

CentOS Linux release 7.7.1908 (Core)

### Matplotlib Version

3.5.1

### Matplotlib Backend

agg

### Python version

3.7.4

### Installation

pip

**Comment by RylanSchaeffer** [comment]
The problem persists even if I create the norm separately first e.g.

```
norm = LogNorm(vmin=cutoff, vmax=1.)

sns.heatmap(avg_sampled_customer_assignments_by_customer,
                ax=ax,
                mask=np.isnan(avg_sampled_customer_assignments_by_customer),
                cmap='Spectral',
                norm=norm,
                )
```

**Comment by RylanSchaeffer** [comment]
This bug was caused by my failing to update seaborn. My apologies!
