### ISSUE TITLE
[Bug]: module 'matplotlib.pyplot' has no attribute 'ticker'

### ISSUE THREAD

**Issue by MacauleyLockeml** [matplotlib/matplotlib#22530]
### Bug summary

Matplotlib will not recognise ticker even though it appears to be still available according to documentation. I have recently updated to the latest version of matplotlib. The code is not fully my own and is taken from the matplotlib online documentation.

### Code for reproduction

```python
import numpy as np
import matplotlib.pyplot as plt

#Reads in all of the data
S1 = np.loadtxt("S1.txt")
S1_conf = np.loadtxt("S1_conf.txt")
S1_upper = S1 + S1_conf
S1_lower = S1 - S1_conf

S2=np.loadtxt("S2.txt")
St = np.loadtxt("ST.txt")
St_conf = np.loadtxt("ST_conf.txt")
St_upper = St + St_conf
St_lower = St - St_conf

#Timecourse to plot over
t = np.linspace(1,72,72)

#Labels for the parameters
_labels = ([r'$\beta$', '$k$', r'$\delta$', r'$\rho$','$c$','$V_{0}$'])

#Plotting the first order sobol indices with confidence intervals
f = plt.figure(figsize=(9,7), dpi=300)
ax = f.add_subplot(111)
for i in range(6):
    if i<10:
        ax.plot(t, S1[:,i], label=_labels[i])
        ax.fill_between(t, S1_lower[:,i], S1_upper[:,i], alpha=0.3)
    else:
        ax.plot(t, S1[:,i], label=_labels[i],linestyle='dashed')
        ax.fill_between(t, S1_lower[:,i], S1_upper[:,i], alpha=0.3)
ax.grid('on')
handles, labels = ax.get_legend_handles_labels()
lgd = ax.legend(handles, labels,ncol=6,loc='upper center', bbox_to_anchor=(0.5, -0.10),fancybox=True, shadow=True, title='Parameter',prop={'size': 14})
plt.ylabel('First Order Sobol index')
plt.yticks(fontsize=13)
plt.xlabel('Time (hours)',fontsize=14)
plt.xticks(fontsize=13)
plt.show()
f.savefig('S1_all', bbox_extra_artists=(lgd,), bbox_inches='tight')

#Plotting the total order sobol indices with confidence intervals
f2 = plt.figure(figsize=(9,7), dpi=300) #dpi increases the quality and size of the image
ax2 = f2.add_subplot(111)
for i in range(6):
    if i<10:
        ax2.plot(t, St[:,i], label=labels[i])
        ax2.fill_between(t, St_lower[:,i], St_upper[:,i], alpha=0.3)
    else:
        ax2.plot(t, St[:,i], label=labels[i],linestyle='dashed')
        ax2.fill_between(t, St_lower[:,i], St_upper[:,i], alpha=0.3)
        
ax2.grid('on')
handles2, labels2 = ax2.get_legend_handles_labels()
lgd = ax2.legend(handles2, labels2,ncol=6,loc='upper center', bbox_to_anchor=(0.5, -0.10),fancybox=True, shadow=True, title='Parameter',prop={'size': 14})
#plt.title('Total order Sobol indicies for timecourse of activated TBK-1 for model 1')
plt.ylabel('Total Order Sobol index',fontsize=14)
plt.yticks(fontsize=13)
plt.xlabel('Time (hours)',fontsize=14)
plt.xticks(fontsize=13)
plt.show()
f2.savefig('ST_all', bbox_extra_artists=(lgd,), bbox_inches='tight')

def heatmap(data, row_labels, col_labels, ax=None,
            cbar_kw={}, cbarlabel="", **kwargs):
    """
    Create a heatmap from a numpy array and two lists of labels.

    Parameters
    ----------
    data
        A 2D numpy array of shape (M, N).
    row_labels
        A list or array of length M with the labels for the rows.
    col_labels
        A list or array of length N with the labels for the columns.
    ax
        A `matplotlib.axes.Axes` instance to which the heatmap is plotted.  If
        not provided, use current axes or create a new one.  Optional.
    cbar_kw
        A dictionary with arguments to `matplotlib.Figure.colorbar`.  Optional.
    cbarlabel
        The label for the colorbar.  Optional.
    **kwargs
        All other arguments are forwarded to `imshow`.
    """

    if not ax:
        ax = plt.gca()

    # Plot the heatmap
    im = ax.imshow(data, **kwargs)

    # Create colorbar
    cbar = ax.figure.colorbar(im, ax=ax, **cbar_kw)
    cbar.ax.set_ylabel(cbarlabel, rotation=-90, va="bottom")

    # Show all ticks and label them with the respective list entries.
    ax.set_xticks(np.arange(data.shape[1]), labels=col_labels)
    ax.set_yticks(np.arange(data.shape[0]), labels=row_labels)

    # Let the horizontal axes labeling appear on top.
    ax.tick_params(top=True, bottom=False,
                   labeltop=True, labelbottom=False)

    # Rotate the tick labels and set their alignment.
    plt.setp(ax.get_xticklabels(), rotation=-30, ha="right",
             rotation_mode="anchor")

    # Turn spines off and create white grid.
    ax.spines[:].set_visible(False)

    ax.set_xticks(np.arange(data.shape[1]+1)-.5, minor=True)
    ax.set_yticks(np.arange(data.shape[0]+1)-.5, minor=True)
    ax.grid(which="minor", color="w", linestyle='-', linewidth=3)
    ax.tick_params(which="minor", bottom=False, left=False)

    return im, cbar


def annotate_heatmap(im, data=None, valfmt="{x:.2f}",
                     textcolors=("black", "white"),
                     threshold=None, **textkw):
    """
    A function to annotate a heatmap.

    Parameters
    ----------
    im
        The AxesImage to be labeled.
    data
        Data used to annotate.  If None, the image's data is used.  Optional.
    valfmt
        The format of the annotations inside the heatmap.  This should either
        use the string format method, e.g. "$ {x:.2f}", or be a
        `matplotlib.ticker.Formatter`.  Optional.
    textcolors
        A pair of colors.  The first is used for values below a threshold,
        the second for those above.  Optional.
    threshold
        Value in data units according to which the colors from textcolors are
        applied.  If None (the default) uses the middle of the colormap as
        separation.  Optional.
    **kwargs
        All other arguments are forwarded to each call to `text` used to create
        the text labels.
    """

    if not isinstance(data, (list, np.ndarray)):
        data = im.get_array()

    # Normalize the threshold to the images color range.
    if threshold is not None:
        threshold = im.norm(threshold)
    else:
        threshold = im.norm(data.max())/2.

    # Set default alignment to center, but allow it to be
    # overwritten by textkw.
    kw = dict(horizontalalignment="center",
              verticalalignment="center")
    kw.update(textkw)

    # Get the formatter in case a string is supplied
    if isinstance(valfmt, str):
        valfmt = plt.ticker.StrMethodFormatter(valfmt)

    # Loop over the data and create a `Text` for each "pixel".
    # Change the text's color depending on the data.
    texts = []
    for i in range(data.shape[0]):
        for j in range(data.shape[1]):
            kw.update(color=textcolors[int(im.norm(data[i, j]) > threshold)])
            text = im.axes.text(j, i, valfmt(data[i, j], None), **kw)
            texts.append(text)

    return texts


fig, ax = plt.subplots(dpi=300)

im, cbar = heatmap(S2, _labels, _labels, ax=ax,
                   cmap="YlGn", cbarlabel="Sobol Index")
texts = annotate_heatmap(im, valfmt="{x:.1f} t")

fig.tight_layout()
plt.show()
```

### Actual outcome

Traceback (most recent call last):

  File "C:\Users\macau\Documents\Python Code\FMDV\Eva Perez Data\Sensitivity Analysis\plot.py", line 184, in <module>
    texts = annotate_heatmap(im, valfmt="{x:.1f} t")

  File "C:\Users\macau\Documents\Python Code\FMDV\Eva Perez Data\Sensitivity Analysis\plot.py", line 166, in annotate_heatmap
    valfmt = plt.ticker.StrMethodFormatter(valfmt)

AttributeError: module 'matplotlib.pyplot' has no attribute 'ticker'

Files attached for code to run.
[S1.txt](https://github.com/matplotlib/matplotlib/files/8116778/S1.txt)
[S1_conf.txt](https://github.com/matplotlib/matplotlib/files/8116779/S1_conf.txt)
[S2.txt](https://github.com/matplotlib/matplotlib/files/8116780/S2.txt)
[ST.txt](https://github.com/matplotlib/matplotlib/files/8116781/ST.txt)
[ST_conf.txt](https://github.com/matplotlib/matplotlib/files/8116782/ST_conf.txt)

### Expected outcome

The code should generate an annotated heatmap.

### Operating system

Windows

### Matplotlib Version

3.5.1

**Comment by jklymak** [comment]
Pyplot does not have a ticker method in 3.5.1.  Also please minimize your code and make self contained if at all possible.  You can discuss further at discourse.matplotlib.org.  Thanks!

**Comment by tacaswell** [comment]
@MacauleyLockeml Where in the docs do we use `plt.ticker` and what version did this last work?

The `ticker` here is very likly a re-import of `matplotlib.ticker`, you should adapt your code to directly use that (as it will definitely work with _all_ versions of Matplotlib past and future).
