### ISSUE TITLE
[Bug]: No module named _tkinter when i have it installed tkinter using pip3 install tk

### ISSUE THREAD

**Issue by ayush-india** [matplotlib/matplotlib#22583]
### Bug summary

When i try to run a piece of code which will just basicilly animate the chaos equation(i know it sounds a lot mathhy ) it gives  me this error 

Traceback (most recent call last):
  File "/home/ayu/b.py", line 4, in <module>
    import matplotlib.pyplot as plt
  File "/usr/local/lib/python3.10/site-packages/matplotlib/pyplot.py", line 2230, in <module>
    switch_backend(rcParams["backend"])
  File "/usr/local/lib/python3.10/site-packages/matplotlib/pyplot.py", line 267, in switch_backend
    class backend_mod(matplotlib.backend_bases._Backend):
  File "/usr/local/lib/python3.10/site-packages/matplotlib/pyplot.py", line 268, in backend_mod
    locals().update(vars(importlib.import_module(backend_name)))
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.10/site-packages/matplotlib/backends/backend_tkagg.py", line 1, in <module>
    from . import _backend_tk
  File "/usr/local/lib/python3.10/site-packages/matplotlib/backends/_backend_tk.py", line 7, in <module>
    import tkinter as tk
  File "/usr/local/lib/python3.10/tkinter/__init__.py", line 37, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'

### Code for reproduction

```python
import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import odeint
from mpl_toolkits.mplot3d import Axes3D

rho = 28.0
sigma = 10.0
beta = 8.0 / 3.0

def f(state, t):
    x, y, z = state  # Unpack the state vector
    return sigma * (y - x), x * (rho - z) - y, x * y - beta * z  # Derivatives

state0 = [1.0, 1.0, 1.0]
t = np.arange(0.0, 40.0, 0.01)

states = odeint(f, state0, t)

fig = plt.figure()
ax = fig.gca(projection="3d")
ax.plot(states[:, 0], states[:, 1], states[:, 2])
plt.draw()
plt.show()
```

### Actual outcome

it gives me this error 

Traceback (most recent call last):
  File "/home/ayu/b.py", line 4, in <module>
    import matplotlib.pyplot as plt
  File "/usr/local/lib/python3.10/site-packages/matplotlib/pyplot.py", line 2230, in <module>
    switch_backend(rcParams["backend"])
  File "/usr/local/lib/python3.10/site-packages/matplotlib/pyplot.py", line 267, in switch_backend
    class backend_mod(matplotlib.backend_bases._Backend):
  File "/usr/local/lib/python3.10/site-packages/matplotlib/pyplot.py", line 268, in backend_mod
    locals().update(vars(importlib.import_module(backend_name)))
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.10/site-packages/matplotlib/backends/backend_tkagg.py", line 1, in <module>
    from . import _backend_tk
  File "/usr/local/lib/python3.10/site-packages/matplotlib/backends/_backend_tk.py", line 7, in <module>
    import tkinter as tk
  File "/usr/local/lib/python3.10/tkinter/__init__.py", line 37, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'

### Expected outcome

it should animate the chaos equation 

https://upload.wikimedia.org/wikipedia/commons/1/13/A_Trajectory_Through_Phase_Space_in_a_Lorenz_Attractor.gif

### Operating system

lubuntu20.04 (a fork of ubuntu20.04)

### Matplotlib Version

3.5.1

### Matplotlib Backend

agg

### Python version

3.10.0

### Jupyter version

i do not have install jupyter notebook

### Installation

pip

**Comment by oscargus** [comment]
It says here: `# If this fails your Python may not be configured for Tk`. So this is not a Matplotlib issue. You should be able to trigger it just by doing
``` Python
import tkinter
``` 
in a Python prompt, which rules out Matplotlib.

See e.g. https://stackoverflow.com/questions/59987762/python-tkinter-modulenotfounderror-no-module-named-tkinter for further advice, but it may be that you need to install python-tk though lubuntu as `sudo apt-get install python3-tk`.

Closing this.

**Comment by grmculmfuer9** [comment]
> It says here: `# If this fails your Python may not be configured for Tk`. So this is not a Matplotlib issue. You should be able to trigger it just by doing
> 
> ```python
> import tkinter
> ```
> 
> in a Python prompt, which rules out Matplotlib.
> 
> See e.g. https://stackoverflow.com/questions/59987762/python-tkinter-modulenotfounderror-no-module-named-tkinter for further advice, but it may be that you need to install python-tk though lubuntu as `sudo apt-get install python3-tk`.
> 
> Closing this.

Same issue is with me, it is not working either way, it is the issue with tkinter

**Comment by manuh-L** [comment]
Python 3.7 was giving error something wrong with my venv, the workaround for me was switch versions, you can try other versions on a python venv or change the interpreter on vs code did work...
on vs code:
open Command Palette -> Python: Select Interpreter -> "my case python 3.10.9"

reference: https://code.visualstudio.com/docs/python/environments

Also make sure to have the library installed
pip3 install tk
#check if tk is installed
python3 -m tkinter
