### ISSUE TITLE
Cannot plot in aarch64

### ISSUE THREAD

**Issue by raquelhortab** [matplotlib/matplotlib#22811]
Hi, I got an aarch64 tablet with an OS based on ubuntu (jingos). I can't find the way to make matplotlib work. The problem seems to be the graphical interface but I am not sure. 
With this minimal code:
```
import matplotlib.pyplot as plt
if __name__ == "__main__":
    plt.plot([1,2,3,],[3,4,5])
    plt.show()
```

I got this error:

```
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    plt.plot([1,2,3,],[3,4,5])
  File "/home/raquel/Projects/uned/CE/venv/lib/python3.8/site-packages/matplotlib/pyplot.py", line 2757, in plot
    return gca().plot(
  File "/home/raquel/Projects/uned/CE/venv/lib/python3.8/site-packages/matplotlib/pyplot.py", line 2262, in gca
    return gcf().gca(**kwargs)
  File "/home/raquel/Projects/uned/CE/venv/lib/python3.8/site-packages/matplotlib/pyplot.py", line 846, in gcf
    return figure()
  File "/home/raquel/Projects/uned/CE/venv/lib/python3.8/site-packages/matplotlib/pyplot.py", line 787, in figure
    manager = new_figure_manager(
  File "/home/raquel/Projects/uned/CE/venv/lib/python3.8/site-packages/matplotlib/pyplot.py", line 306, in new_figure_manager
    return _backend_mod.new_figure_manager(*args, **kwargs)
  File "/home/raquel/Projects/uned/CE/venv/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 3494, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/home/raquel/Projects/uned/CE/venv/lib/python3.8/site-packages/matplotlib/backends/_backend_tk.py", line 942, in new_figure_manager_given_figure
    manager = cls.FigureManager(canvas, num, window)
  File "/home/raquel/Projects/uned/CE/venv/lib/python3.8/site-packages/matplotlib/backends/_backend_tk.py", line 413, in __init__
    self.toolbar = self._get_toolbar()
  File "/home/raquel/Projects/uned/CE/venv/lib/python3.8/site-packages/matplotlib/backends/_backend_tk.py", line 435, in _get_toolbar
    toolbar = NavigationToolbar2Tk(self.canvas, self.window)
  File "/home/raquel/Projects/uned/CE/venv/lib/python3.8/site-packages/matplotlib/backends/_backend_tk.py", line 536, in __init__
    self._buttons[text] = button = self._Button(
  File "/home/raquel/Projects/uned/CE/venv/lib/python3.8/site-packages/matplotlib/backends/_backend_tk.py", line 663, in _Button
    NavigationToolbar2Tk._set_image_for_button(self, b)
  File "/home/raquel/Projects/uned/CE/venv/lib/python3.8/site-packages/matplotlib/backends/_backend_tk.py", line 642, in _set_image_for_button
    image = ImageTk.PhotoImage(im.resize((size, size)), master=self)
  File "/home/raquel/Projects/uned/CE/venv/lib/python3.8/site-packages/PIL/Image.py", line 1958, in resize
    im = im.resize(size, resample, box)
  File "/home/raquel/Projects/uned/CE/venv/lib/python3.8/site-packages/PIL/Image.py", line 1980, in resize
    return self._new(self.im.resize(size, resample, box))
ValueError: height and width must be > 0
```

Has someone got an idea what it could be?

**Comment by jklymak** [comment]
does tk work at all (google "basic tk example")?

**Comment by tacaswell** [comment]
Does

```python
import matplotlib.pyplot as plt
plt.switch_backend('agg')
fig, ax = plt.subplots()
ax.plot(range(5))
fig.savefig('/tmp/test.png')
``` 
work?  This will help sort out if this is an issue with the graphical UI or with Matplotilb's rendering pipeline.

Reading the traceback, it looks like this is failing to set the icon on a button (?) which suggests that we are somehow failing to read the button asset from disk (either because it is not installed or in a format that tk on this system can not read).

**Comment by raquelhortab** [comment]
> does tk work at all (google "basic tk example")?

I've tried a basic example and yes, Tk does work

**Comment by raquelhortab** [comment]
> Does
> 
> ```python
> import matplotlib.pyplot as plt
> plt.switch_backend('agg')
> fig, ax = plt.subplots()
> ax.plot(range(5))
> fig.savefig('/tmp/test.png')
> ```
> 
> work? This will help sort out if this is an issue with the graphical UI or with Matplotilb's rendering pipeline.
> 
> Reading the traceback, it looks like this is failing to set the icon on a button (?) which suggests that we are somehow failing to read the button asset from disk (either because it is not installed or in a format that tk on this system can not read).

It does work! Although it is not ideal it is a good enough solution for me for now, at least i can get the plots. Thank you very much! If you want to debug the problem and need me to run something just let me know and I'll post the outcome/results.

**Comment by tacaswell** [comment]
How did you install Matplotlib?  Given that both Tk works on its own, saving a image works, and the error message points to loading an icon failing (!!), I suspect that the underlying issue is that your installation is broken.

Can you please try fully uninstalling and then re-installing Matplotlib?

**Comment by raquelhortab** [comment]
I reinstalled and I still get the same error. I installed it using pip: `pip install matplotlib`

**Comment by daniilS** [comment]
To see if it's an issue with the Tk installation, what does the following code print?
```python
import tkinter as tk
root = tk.Tk()
print(root.winfo_pixels("18p"))

**Comment by jklymak** [comment]
I'll close for lack of response, but feel free to request a re-open.
