### ISSUE TITLE
[Bug]: Latex fonts fail to embed when saving pdf figures

### ISSUE THREAD

**Issue by tranqui** [matplotlib/matplotlib#23123]
### Bug summary

I've just done a fresh OS install (Fedora 36) and matplotlib (3.5.1) fails upon saving figures as pdf with latex-rendered texts (text.usetex=True). The errors seem to suggest a problem embedding the latex fonts. The latex-rendered fonts render correctly on-screen; the errors only occur when attempting to save to pdf.

### Code for reproduction

```python
import numpy as np, matplotlib.pyplot as plt
plt.rc('text', usetex=True)

x = np.random.random(10)
y = x + 0.1*np.random.random(len(x))
plt.plot(x, y, 'o')
plt.xlabel('x')
plt.ylabel('y')

plt.savefig('test.pdf')
```

### Actual outcome

Traceback (most recent call last):
  File "/home/joshua/Documents/CylinderFlow/falsetto/test-pdf.py", line 13, in <module>
    plt.savefig('test.pdf')
  File "/home/joshua/.local/lib/python3.10/site-packages/matplotlib/pyplot.py", line 958, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/home/joshua/.local/lib/python3.10/site-packages/matplotlib/figure.py", line 3019, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/joshua/.local/lib/python3.10/site-packages/matplotlib/backend_bases.py", line 2319, in print_figure
    result = print_method(
  File "/home/joshua/.local/lib/python3.10/site-packages/matplotlib/backend_bases.py", line 1648, in wrapper
    return func(*args, **kwargs)
  File "/home/joshua/.local/lib/python3.10/site-packages/matplotlib/_api/deprecation.py", line 386, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/home/joshua/.local/lib/python3.10/site-packages/matplotlib/backends/backend_pdf.py", line 2788, in print_pdf
    file.finalize()
  File "/home/joshua/.local/lib/python3.10/site-packages/matplotlib/backends/backend_pdf.py", line 794, in finalize
    self.writeFonts()
  File "/home/joshua/.local/lib/python3.10/site-packages/matplotlib/backends/backend_pdf.py", line 914, in writeFonts
    fonts[Fx] = self._embedTeXFont(info)
  File "/home/joshua/.local/lib/python3.10/site-packages/matplotlib/backends/backend_pdf.py", line 981, in _embedTeXFont
    t1font = type1font.Type1Font(fontinfo.fontfile)
  File "/home/joshua/.local/lib/python3.10/site-packages/matplotlib/type1font.py", line 72, in __init__
    with open(input, 'rb') as file:
FileNotFoundError: [Errno 2] No such file or directory: ''

### Expected outcome

A pdf of the plot with latex-rendered text.

### Additional information

Saving in rasterised formats works okay, which is not surprising because there is no font embedding. The figure renders correctly with latex fonts when calling plt.show(), so the problem seems to just be embedding the fonts in the pdf.

### Operating system

Fedora 36

### Matplotlib Version

3.5.1

### Matplotlib Backend

Have tried both TkAgg and Qt

### Python version

3.10.4

### Installation

Linux package manager

**Comment by anntzer** [comment]
Can you please run `matplotlib.dviread._find_tex_file("pdftex.map")` and provide the contents of the file whose path is printed?

**Comment by tranqui** [comment]
It doesn't seem to like me...

`AttributeError: module 'matplotlib.dviread' has no attribute '_find_tex_file'`

**Comment by anntzer** [comment]
`matplotlib.dviread.find_tex_file`, then?

**Comment by tranqui** [comment]
Yes I was just looking into that before you commented. Running the second command led me to some bogus config files I'd accidentally ported over to my new home directory. Font embedding now functions correctly after deleting these.
