### ISSUE TITLE
fail to import matplotlib.pyplot

### ISSUE THREAD

**Issue by matthiasdresden** [matplotlib/matplotlib#2320]
I have found the following problem:

I tried a new Installation of Python 3.3.2 64-bit with WinPython-64bit-3.3.2.2 on a Windows 7 64 bit machine.

Ever when I try to import matplotlib.pyplot (with some of my user accounts i use on this Windows-7 machine) I get tthe following error message:

Traceback (most recent call last):
  File "D:\WinPython_3.3.2.2\python-3.3.2.amd64\lib\site-packages\matplotlib\font_manager.py", line 1348, in <module>
    fontManager = pickle_load(_fmcache)
  File "D:\WinPython_3.3.2.2\python-3.3.2.amd64\lib\site-packages\matplotlib\font_manager.py", line 947, in pickle_load
    with open(filename, 'rb') as fh:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\Jobst3\.matplotlib\fontList.py3k.cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\WinPython_3.3.2.2\python-3.3.2.amd64\lib\site-packages\matplotlib\pyplot.py", line 24, in <module>
    import matplotlib.colorbar
  File "D:\WinPython_3.3.2.2\python-3.3.2.amd64\lib\site-packages\matplotlib\colorbar.py", line 29, in <module>
    import matplotlib.collections as collections
  File "D:\WinPython_3.3.2.2\python-3.3.2.amd64\lib\site-packages\matplotlib\collections.py", line 23, in <module>
    import matplotlib.backend_bases as backend_bases
  File "D:\WinPython_3.3.2.2\python-3.3.2.amd64\lib\site-packages\matplotlib\backend_bases.py", line 50, in <module>
    import matplotlib.textpath as textpath
  File "D:\WinPython_3.3.2.2\python-3.3.2.amd64\lib\site-packages\matplotlib\textpath.py", line 11, in <module>
    import matplotlib.font_manager as font_manager
  File "D:\WinPython_3.3.2.2\python-3.3.2.amd64\lib\site-packages\matplotlib\font_manager.py", line 1356, in <module>
    _rebuild()
  File "D:\WinPython_3.3.2.2\python-3.3.2.amd64\lib\site-packages\matplotlib\font_manager.py", line 1341, in _rebuild
    fontManager = FontManager()
  File "D:\WinPython_3.3.2.2\python-3.3.2.amd64\lib\site-packages\matplotlib\font_manager.py", line 1004, in __init__
    self.ttflist = createFontList(self.ttffiles)
  File "D:\WinPython_3.3.2.2\python-3.3.2.amd64\lib\site-packages\matplotlib\font_manager.py", line 584, in createFontList
    prop = ttfFontProperty(font)
  File "D:\WinPython_3.3.2.2\python-3.3.2.amd64\lib\site-packages\matplotlib\font_manager.py", line 398, in ttfFontProperty
    sfnt4 = sfnt4.decode('ascii').lower()
UnicodeDecodeError: 'ascii' codec can't decode byte 0x82 in position 0: ordinal not in range(128)

The same issue happens with other python version (3.2.3 64 bit, as I installed matplotlib 1.3. with easy install).

I found out that this happens only with newly created user accounts, but not with older accounts. As I found out, python is looking for a file located in the user folder: C:\Users\Jobst3\.matplotlib\fontList.py3k.cache' which is not there in the newly created user account.

But the file is available in older user accounts. The file was created by an older version of matplotlib (matplotlib-1.2.0rc2.win-amd64-py3.2), and everything goes fine, if i use these accounts.

I am not able to test the issue on a complete new and clean Windows-7 machine at the moment

Matthias

**Comment by drcrook1** [comment]
Just gonna put out there I ran into this just recently with conda 4.3.29 and python 3.6 on windows 10.

**Comment by tacaswell** [comment]
@drcrook1 please open a new issue.
