### ISSUE TITLE
[Bug]: Error when trying to save video in .mp4 format

### ISSUE THREAD

**Issue by DarthMalloc** [matplotlib/matplotlib#23362]
### Bug summary

I suspect this is an issue with my ffmpeg software and not with matplotlib. I am trying to test out the function to create a video in .mp4 format, and it is unable to save.

### Code for reproduction

```python
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation

fig, ax = plt.subplots()


def f(x, y):
    return np.sin(x) + np.cos(y)

x = np.linspace(0, 2 * np.pi, 120)
y = np.linspace(0, 2 * np.pi, 100).reshape(-1, 1)

# ims is a list of lists, each row is a list of artists to draw in the
# current frame; here we are just animating one artist, the image, in
# each frame
ims = []
for i in range(60):
    x += np.pi / 15.
    y += np.pi / 20.
    im = ax.imshow(f(x, y), animated=True)
    if i == 0:
        ax.imshow(f(x, y))  # show an initial one first
    ims.append([im])

ani = animation.ArtistAnimation(fig, ims, interval=50, blit=True,
                                repeat_delay=1000)

# To save the animation, use e.g.
#
# ani.save("movie.mp4")
#
# or
#
writer = animation.FFMpegWriter(fps=15, metadata=dict(artist='Me'), bitrate=1800)
ani.save("movie.mp4", writer=writer)
```
```


### Actual outcome

```
MovieWriter stderr:
Unknown encoder 'h264'

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/animation.py", line 234, in saving
    yield self
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/animation.py", line 1093, in save
    writer.grab_frame(**savefig_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/animation.py", line 351, in grab_frame
    self.fig.savefig(self._proc.stdin, format=self.frame_format,
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/figure.py", line 3046, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/backend_bases.py", line 2319, in print_figure
    result = print_method(
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/backend_bases.py", line 1648, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/_api/deprecation.py", line 415, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/backends/backend_agg.py", line 486, in print_raw
    fh.write(renderer.buffer_rgba())
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/justin/animation_test.py", line 36, in <module>
    ani.save("movie.mp4", writer=writer)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/animation.py", line 1093, in save
    writer.grab_frame(**savefig_kwargs)
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/animation.py", line 236, in saving
    self.finish()
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/animation.py", line 342, in finish
    self._cleanup()  # Inline _cleanup() once cleanup() is removed.
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/animation.py", line 373, in _cleanup
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command '['ffmpeg', '-f', 'rawvideo', '-vcodec', 'rawvideo', '-s', '640x480', '-pix_fmt', 'rgba', '-r', '15', '-loglevel', 'error', '-i', 'pipe:', '-vcodec', 'h264', '-pix_fmt', 'yuv420p', '-b', '1800k', '-metadata', 'artist=Me', '-y', 'movie.mp4']' returned non-zero exit status 1.
```

### Expected outcome

Should produce an .mp4 video file.

### Additional information

_No response_

### Operating system

Linux Mint 19.3

### Matplotlib Version

3.5.2

### Matplotlib Backend

TkAgg

### Python version

python 3.8

### Jupyter version

_No response_

### Installation

pip

**Comment by tacaswell** [comment]
```
MovieWriter stderr:
Unknown encoder 'h264'
```

You do not appear to have the right codecs installed.  You will either need to install the h264 codec or switch to a codec you do have installed.   You can control this by passing the `codec` kwarg when you create `FFMpgeWriter` or via

```
mpl.rcParams['animation.codec'] = "..."
```

which will set the default (and by used by the implicit `anim.save('foo.mp4')`.  You can get a list of your installed codecs via 

```bash
$ ffmpeg -codecs
```

Docs: https://matplotlib.org/stable/api/_as_gen/matplotlib.animation.FFMpegWriter.html#matplotlib.animation.FFMpegWriter

I am going to close this because I do not think there is anything that we can do on the Matplotlib side to fix this.  If you have further questions I suggest you start a thread at https://discourse.matplotlib.org where we prefer to do user support and keep github for bugs in Matplotlib.

If you think I am wrong and this is a bug in Matplotlib please ping to have this re-opened!
