### ISSUE TITLE
[Bug]: AttributeError: type object 'Qt' has no attribute 'KeyboardModifier'

### ISSUE THREAD

**Issue by CalinGeo** [matplotlib/matplotlib#23547]
### Bug summary

It happens with ax.scatter or plt.subplots

### Code for reproduction

```python
plt.style.use('_mpl-gallery')

# make the data
np.random.seed(3)
x = 4 + np.random.normal(0, 2, 24)
y = 4 + np.random.normal(0, 2, len(x))
# size and color:
sizes = np.random.uniform(15, 80, len(x))
colors = np.random.uniform(15, 80, len(x))

# plot
fig, ax = plt.subplots()

ax.scatter(x, y, s=sizes, c=colors, vmin=0, vmax=100)

ax.set(xlim=(0, 8), xticks=np.arange(1, 8),
       ylim=(0, 8), yticks=np.arange(1, 8))

plt.show()
```

### Actual outcome

```
raceback (most recent call last):
  File ".py", line 366, in <module>
    fig, ax = plt.subplots()
  File "C:\Python\Python39\lib\site-packages\matplotlib\pyplot.py", line 1455, in subplots
    fig = figure(**fig_kw)
  File "C:\Python\Python39\lib\site-packages\matplotlib\pyplot.py", line 808, in figure
    manager = new_figure_manager(
  File "C:\Python\Python39\lib\site-packages\matplotlib\pyplot.py", line 326, in new_figure_manager
    _warn_if_gui_out_of_main_thread()
  File "C:\Python\Python39\lib\site-packages\matplotlib\pyplot.py", line 316, in _warn_if_gui_out_of_main_thread
    if (_get_required_interactive_framework(_get_backend_mod())
  File "C:\Python\Python39\lib\site-packages\matplotlib\pyplot.py", line 217, in _get_backend_mod
    switch_backend(dict.__getitem__(rcParams, "backend"))
  File "C:\Python\Python39\lib\site-packages\matplotlib\pyplot.py", line 268, in switch_backend
    switch_backend(candidate)
  File "C:\Python\Python39\lib\site-packages\matplotlib\pyplot.py", line 288, in switch_backend
    class backend_mod(matplotlib.backend_bases._Backend):
  File "C:\Python\Python39\lib\site-packages\matplotlib\pyplot.py", line 289, in backend_mod
    locals().update(vars(importlib.import_module(backend_name)))
  File "C:\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Python\Python39\lib\site-packages\matplotlib\backends\backend_qtagg.py", line 12, in <module>
    from .backend_qt import (
  File "C:\Python\Python39\lib\site-packages\matplotlib\backends\backend_qt.py", line 73, in <module>
    _MODIFIER_KEYS = [
  File "C:\Python\Python39\lib\site-packages\matplotlib\backends\backend_qt.py", line 74, in <listcomp>
    (_to_int(getattr(_enum("QtCore.Qt.KeyboardModifier"), mod)),
  File "C:\Python\Python39\lib\site-packages\matplotlib\backends\qt_compat.py", line 165, in _enum
    return operator.attrgetter(
AttributeError: type object 'Qt' has no attribute 'KeyboardModifier'
```

### Expected outcome

The expected outcome would be able to execute and save the plotted scatterplot.

### Operating system

Windows 10

### Matplotlib Version

3.5.2

### Matplotlib Backend

```
Traceback (most recent call last):   File "C:\.py", line 31, in <module>     print(matplotlib.get_backend())   File "C:\Python\Python39\lib\site-packages\matplotlib\__init__.py", line 1170, in get_backend     return rcParams['backend']   File "C:\Python\Python39\lib\site-packages\matplotlib\__init__.py", line 672, in __getitem__     plt.switch_backend(rcsetup._auto_backend_sentinel)   File "C:\Python\Python39\lib\site-packages\matplotlib\pyplot.py", line 268, in switch_backend     switch_backend(candidate)   File "C:\Python\Python39\lib\site-packages\matplotlib\pyplot.py", line 288, in switch_backend     class backend_mod(matplotlib.backend_bases._Backend):   File "C:\Python\Python39\lib\site-packages\matplotlib\pyplot.py", line 289, in backend_mod     locals().update(vars(importlib.import_module(backend_name)))   File "C:\Python\Python39\lib\importlib\__init__.py", line 127, in import_module     return _bootstrap._gcd_import(name[level:], package, level)   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked   File "<frozen importlib._bootstrap_external>", line 790, in exec_module   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed   File "C:\Python\Python39\lib\site-packages\matplotlib\backends\backend_qtagg.py", line 12, in <module>     from .backend_qt import (   File "C:\Python\Python39\lib\site-packages\matplotlib\backends\backend_qt.py", line 73, in <module>     _MODIFIER_KEYS = [   File "C:\Python\Python39\lib\site-packages\matplotlib\backends\backend_qt.py", line 74, in <listcomp>     (_to_int(getattr(_enum("QtCore.Qt.KeyboardModifier"), mod)),   File "C:\Python\Python39\lib\site-packages\matplotlib\backends\qt_compat.py", line 165, in _enum     return operator.attrgetter( AttributeError: type object 'Qt' has no attribute 'KeyboardModifier'
```

### Python version

Python 3.9.2

### Installation

pip

**Comment by tacaswell** [comment]
@CalinGeo This looks like a compatibility issue with PyQt (or PySide).  Which version do you have installed (what does `pip list` say)?

**Comment by CalinGeo** [comment]
Thanks for the feedback! I have Qt6 installed.

I figured it out in the meantime (I think) : from pyqtgraph import PlotWidget

**Comment by tacaswell** [comment]
We only support PyQt >= 6.1 ( https://matplotlib.org/stable/devel/dependencies.html?highlight=dependency#backends )

`pyqtgraph` is an entirely different library, but I am glad you found a tool that fit your needs!
