### ISSUE TITLE
[Bug]: Pie chart with 0 array crashes

### ISSUE THREAD

**Issue by discover59** [matplotlib/matplotlib#23630]
### Bug summary

After upgrading version from 3.3.4 to 3.5.2, pie chart generation crashes with [0,0] data.

With v3.3.4, pie chart shows empty chart.
![image](https://user-images.githubusercontent.com/16558427/184709236-6cf5de45-140b-4bf5-918f-205544f46d57.png)

But on 3.5.2, it crashes with error `cannot convert float NaN to integer`.

### Code for reproduction

```python
import matplotlib.pyplot as plt
fig1, ax1 = plt.subplots()
fig1.set_size_inches(2.8, 2.8)
patches, texts, autotexts = ax1.pie([0, 0])
```

### Actual outcome

cannot convert float NaN to integer

### Expected outcome

Chart with 0% in center

### Operating system

Windows, Ubuntu

### Matplotlib Version

3.5.2

### Matplotlib Backend

TkAgg

### Python version

3.8.10

### Installation

pip

**Comment by tacaswell** [comment]
Can you please provide the full traceback?

**Comment by discover59** [comment]
```
Traceback (most recent call last):
  File "test.py", line 190, in <module>
    patches, texts, autotexts = ax1.pie([0, 0])
  File "venv\lib\site-packages\matplotlib\__init__.py", line 1412, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "venv\lib\site-packages\matplotlib\axes\_axes.py", line 3092, in pie
    w = mpatches.Wedge((x, y), radius, 360. * min(theta1, theta2),
  File "venv\lib\site-packages\matplotlib\patches.py", line 1164, in __init__
    self._recompute_path()
  File "venv\lib\site-packages\matplotlib\patches.py", line 1176, in _recompute_path
    arc = Path.arc(theta1, theta2)
  File "venv\lib\site-packages\matplotlib\path.py", line 947, in arc
    n = int(2 ** np.ceil((eta2 - eta1) / halfpi))
ValueError: cannot convert float NaN to integer
```

**Comment by tacaswell** [comment]
I miss read this the first time, I thought the behavior changes was between 3.5.2 and 3.5.3, but I now see that the behavior changes was in 3.3.4.

The following works on the current main branch:

```python
patches, texts, autotexts = ax1.pie([0, 0], normalize=False, autopct='%f%%')
```

The first change is to disable normalization (which is the source of the error, because `[0, 0]` -> `[nan, nan]` once normalized), the second change ensures that the percentage is shown (without which you get a different failure due to only 2 things being returned).

I am not actually sure what the "right" behavior in this case would be.  In the un-normalized case I think the behavior of showing 0 width slices is correct.  In the normalized case I think we have two options:

1. special case if the sum of the input == 0 than the normalized values are still 0 (we know there are no negative values as we have a check for than already) which is not unreasonable, but it does violate "all sum to 1" of the normalization
2. raise a better exception in `pie` that we can not normalize all 0s


I think both options are reasonable.  The first is a bit easier for people running things in bulk (because it is less likely that their code will explode), but on the other hand I'm not fully convinced that no pie is actually better (just quieter).  The second option is more "in the face of uncertainty resist the tempation to guess'.

I could also see a (weak) case for "If all are 0 normalize to 1/N!" which will always draw a pie and does correctly communicate "there were an equal number of all of them" and does maintain the normalization invariant, but that seems too surprising / hard to explain.

This is a case where the actual change is like 2 lines + a test, but it is not a good first issue because I think there is going to be some consensus building involved in sorting out what it _should_ do.

**Comment by oscargus** [comment]
What about 1 with a warning?

**Comment by oscargus** [comment]
But the way to suppress is it passing `normalize=False`? The warning basically saying, "Hey, we ignored normalization since we cannot divide by zero, if you do not want to see this, make sure you do not normalize." Probably slightly better formulated. (Plus the `autopct` stuff...)

If I was running things in bulk, I can either live with the warning or modify my script to do something more sensible. With 2, you are forced to do something more sensible.

**Comment by rcomer** [comment]
Since #30019 we are throwing an error for the all-zero case regardless of the *normalize* parameter, which is contrary to discussion here.  #30019 is not yet in a release.  Should we revert it?

**Comment by timhoffm** [comment]
I'm +0 on leaving the error.

One could argue that for `normalize=False` it's reasonable to draw an empty pie. However, I see the practical problem that this plots nothing at all (as opposed e.g. bars with height 0, where we at least have the Axes spine and usually a tick label), so it's hard for a reader to interpret.
For now, I'd say that an author should special-case the all-zero case and come up with an appropriate way of visually communicating the missing data. The problem with us doing this by default is that there is no canonical way to do this. Drawing a greyed out full pie, or just a line at 0 angle, or adding a text "no data" are all assumptions that we shouldn't do.
