### ISSUE TITLE
[Bug]: Installing from source fails during Freetype compilation with spaces in working directory filepath

### ISSUE THREAD

**Issue by scottshambaugh** [matplotlib/matplotlib#23718]
### Bug summary

When attempting to install the latest pull of the main branch from source, the build errors out during freetype compilation. I am running this on Ubuntu as installed on Windows WSL. I have very similar setups on my work and home laptops, and this is only happening on the work laptop, I believe because that one has spaces in the filepath. But I can't track down where exactly to escape the spaces in the filename.

Working directory:
```
/home/scottshambaugh/repos/matplotlib
which symlinks to:
/mnt/c/Users/scott.shambaugh/OneDrive - MyDrive/Documents/repos/matplotlib
```

### Code for reproduction

Try putting spaces in your file path? I can do tests on my machine if unable to reproduce.

### Actual outcome

```
(py39) ~/repos/matplotlib$ pip install -e .
Obtaining file:///mnt/c/Users/scott.shambaugh/OneDrive%20-%20MyDrive/Documents/repos/matplotlib
Requirement already satisfied: contourpy>=1.0.1 in /home/scottshambaugh/anaconda3/envs/py39/lib/python3.9/site-packages (from matplotlib==3.6.0.dev3066+gee2f68bdc9.d20220823) (1.0.4)
Requirement already satisfied: cycler>=0.10 in /home/scottshambaugh/anaconda3/envs/py39/lib/python3.9/site-packages (from matplotlib==3.6.0.dev3066+gee2f68bdc9.d20220823) (0.10.0)
Requirement already satisfied: fonttools>=4.22.0 in /home/scottshambaugh/anaconda3/envs/py39/lib/python3.9/site-packages (from matplotlib==3.6.0.dev3066+gee2f68bdc9.d20220823) (4.33.2)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/scottshambaugh/anaconda3/envs/py39/lib/python3.9/site-packages (from matplotlib==3.6.0.dev3066+gee2f68bdc9.d20220823) (1.3.2)
Requirement already satisfied: numpy>=1.19 in /home/scottshambaugh/anaconda3/envs/py39/lib/python3.9/site-packages (from matplotlib==3.6.0.dev3066+gee2f68bdc9.d20220823) (1.22.3)
Requirement already satisfied: packaging>=20.0 in /home/scottshambaugh/anaconda3/envs/py39/lib/python3.9/site-packages (from matplotlib==3.6.0.dev3066+gee2f68bdc9.d20220823) (21.3)
Requirement already satisfied: pillow>=6.2.0 in /home/scottshambaugh/anaconda3/envs/py39/lib/python3.9/site-packages (from matplotlib==3.6.0.dev3066+gee2f68bdc9.d20220823) (8.3.2)
Requirement already satisfied: pyparsing>=2.2.1 in /home/scottshambaugh/anaconda3/envs/py39/lib/python3.9/site-packages (from matplotlib==3.6.0.dev3066+gee2f68bdc9.d20220823) (2.4.7)
Requirement already satisfied: python-dateutil>=2.7 in /home/scottshambaugh/anaconda3/envs/py39/lib/python3.9/site-packages (from matplotlib==3.6.0.dev3066+gee2f68bdc9.d20220823) (2.8.2)
Requirement already satisfied: setuptools_scm>=7 in /home/scottshambaugh/anaconda3/envs/py39/lib/python3.9/site-packages (from matplotlib==3.6.0.dev3066+gee2f68bdc9.d20220823) (7.0.5)
Requirement already satisfied: six in /home/scottshambaugh/anaconda3/envs/py39/lib/python3.9/site-packages (from cycler>=0.10->matplotlib==3.6.0.dev3066+gee2f68bdc9.d20220823) (1.16.0)
Requirement already satisfied: typing-extensions in /home/scottshambaugh/anaconda3/envs/py39/lib/python3.9/site-packages (from setuptools_scm>=7->matplotlib==3.6.0.dev3066+gee2f68bdc9.d20220823) (4.3.0)
Requirement already satisfied: setuptools in /home/scottshambaugh/anaconda3/envs/py39/lib/python3.9/site-packages (from setuptools_scm>=7->matplotlib==3.6.0.dev3066+gee2f68bdc9.d20220823) (58.0.4)
Requirement already satisfied: tomli>=1.0.0 in /home/scottshambaugh/anaconda3/envs/py39/lib/python3.9/site-packages (from setuptools_scm>=7->matplotlib==3.6.0.dev3066+gee2f68bdc9.d20220823) (2.0.1)
Installing collected packages: matplotlib
  Attempting uninstall: matplotlib
    Found existing installation: matplotlib 3.5.1
    Uninstalling matplotlib-3.5.1:
      Successfully uninstalled matplotlib-3.5.1
  Running setup.py develop for matplotlib
    ERROR: Command errored out with exit status 1:
     command: /home/scottshambaugh/anaconda3/envs/py39/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/mnt/c/Users/scott.shambaugh/OneDrive - MyDrive/Documents/repos/matplotlib/setup.py'"'"'; __file__='"'"'/mnt/c/Users/scott.shambaugh/OneDrive - MyDrive/Documents/repos/matplotlib/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /mnt/c/Users/scott.shambaugh/OneDrive - MyDrive/Documents/repos/matplotlib/
    Complete output (205 lines):
    
    Edit mplsetup.cfg to change the build options; suppress output with --quiet.
    
    BUILDING MATPLOTLIB
          python: yes [3.9.7 (default, Sep 16 2021, 13:09:58)  [GCC 7.5.0]]
        platform: yes [linux]
           tests: no  [skipping due to configuration]
          macosx: no  [Mac OS-X only]
    
    running develop
    running egg_info
    writing lib/matplotlib.egg-info/PKG-INFO
    writing dependency_links to lib/matplotlib.egg-info/dependency_links.txt
    writing namespace_packages to lib/matplotlib.egg-info/namespace_packages.txt
    writing requirements to lib/matplotlib.egg-info/requires.txt
    writing top-level names to lib/matplotlib.egg-info/top_level.txt
    adding license file 'LICENSE/LICENSE'
    adding license file 'LICENSE/LICENSE_AMSFONTS'
    adding license file 'LICENSE/LICENSE_BAKOMA'
    adding license file 'LICENSE/LICENSE_CARLOGO'
    adding license file 'LICENSE/LICENSE_COLORBREWER'
    adding license file 'LICENSE/LICENSE_COURIERTEN'
    adding license file 'LICENSE/LICENSE_JSXTOOLS_RESIZE_OBSERVER'
    adding license file 'LICENSE/LICENSE_QT4_EDITOR'
    adding license file 'LICENSE/LICENSE_SOLARIZED'
    adding license file 'LICENSE/LICENSE_STIX'
    adding license file 'LICENSE/LICENSE_YORICK'
    writing manifest file 'lib/matplotlib.egg-info/SOURCES.txt'
    running build_ext
    gcc -pthread -B /home/scottshambaugh/anaconda3/envs/py39/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/scottshambaugh/anaconda3/envs/py39/include -I/home/scottshambaugh/anaconda3/envs/py39/include -fPIC -O2 -isystem /home/scottshambaugh/anaconda3/envs/py39/include -fPIC -I/home/scottshambaugh/anaconda3/envs/py39/include/python3.9 -c /tmp/tmpaevbltws.cpp -o tmp/tmpaevbltws.o -fvisibility=hidden
    gcc -pthread -B /home/scottshambaugh/anaconda3/envs/py39/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/scottshambaugh/anaconda3/envs/py39/include -I/home/scottshambaugh/anaconda3/envs/py39/include -fPIC -O2 -isystem /home/scottshambaugh/anaconda3/envs/py39/include -fPIC -I/home/scottshambaugh/anaconda3/envs/py39/include/python3.9 -c /tmp/tmp2f41_efk.cpp -o tmp/tmp2f41_efk.o -fvisibility-inlines-hidden
    gcc -pthread -B /home/scottshambaugh/anaconda3/envs/py39/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/scottshambaugh/anaconda3/envs/py39/include -I/home/scottshambaugh/anaconda3/envs/py39/include -fPIC -O2 -isystem /home/scottshambaugh/anaconda3/envs/py39/include -fPIC -I/home/scottshambaugh/anaconda3/envs/py39/include/python3.9 -c /tmp/tmpoccmtj50.cpp -o tmp/tmpoccmtj50.o -flto
    ls: cannot access '-': No such file or directory
    ls: cannot access 'MyDrive/Documents/repos/matplotlib/build/freetype-2.6.1': No such file or directory
    ls: cannot access '-': No such file or directory
    ls: cannot access 'MyDrive/Documents/repos/matplotlib/build/freetype-2.6.1': No such file or directory
    
    FreeType build system -- automatic system detection
    
    The following settings are used:
    
      platform                    unix
      compiler                    gcc -pthread -B /home/scottshambaugh/anaconda3/envs/py39/compiler_compat
      configuration directory     ./builds/unix
      configuration rules         ./builds/unix/unix.mk
    
    If this does not correspond to your system or settings please remove the file
    `config.mk' from this directory then read the INSTALL file for help.
    
    Otherwise, simply type `make' again to build the library,
    or `make refdoc' to build the API reference (this needs python >= 2.6).
    
    cd builds/unix; \
            ./configure  '--with-zlib=no' '--with-bzip2=no' '--with-png=no' '--with-harfbuzz=no' '--enable-static' '--disable-shared' '--host=x86_64-conda_cos6-linux-gnu'
    checking build system type... x86_64-pc-linux-gnu
    checking host system type... x86_64-conda_cos6-linux-gnu
    checking for x86_64-conda_cos6-linux-gnu-gcc... gcc -pthread -B /home/scottshambaugh/anaconda3/envs/py39/compiler_compat
    checking whether the C compiler works... yes
    checking for C compiler default output file name... a.out
    checking for suffix of executables...
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
    checking whether gcc -pthread -B /home/scottshambaugh/anaconda3/envs/py39/compiler_compat accepts -g... yes
    checking for gcc -pthread -B /home/scottshambaugh/anaconda3/envs/py39/compiler_compat option to accept ISO C89... none needed
    checking how to run the C preprocessor... gcc -pthread -B /home/scottshambaugh/anaconda3/envs/py39/compiler_compat -E
    checking for x86_64-conda_cos6-linux-gnu-pkg-config... no
    checking for pkg-config... no
    configure: WARNING: Libtool does not cope well with whitespace in `pwd`
    checking how to print strings... printf
    checking for a sed that does not truncate output... /usr/bin/sed
    checking for grep that handles long lines and -e... /usr/bin/grep
    checking for egrep... /usr/bin/grep -E
    checking for fgrep... /usr/bin/grep -F
    checking for ld used by gcc -pthread -B /home/scottshambaugh/anaconda3/envs/py39/compiler_compat... /home/scottshambaugh/anaconda3/envs/py39/compiler_compat/ld
    checking if the linker (/home/scottshambaugh/anaconda3/envs/py39/compiler_compat/ld) is GNU ld... yes
    checking for BSD- or MS-compatible name lister (nm)... no
    checking for x86_64-conda_cos6-linux-gnu-dumpbin... no
    checking for x86_64-conda_cos6-linux-gnu-link... no
    checking for dumpbin... no
    checking for link... link -dump
    checking the name lister (nm) interface... BSD nm
    checking whether ln -s works... yes
    checking the maximum length of command line arguments... 1572864
    checking how to convert x86_64-pc-linux-gnu file names to x86_64-conda_cos6-linux-gnu format... func_convert_file_noop
    checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
    checking for /home/scottshambaugh/anaconda3/envs/py39/compiler_compat/ld option to reload object files... -r
    checking for x86_64-conda_cos6-linux-gnu-objdump... no
    checking for objdump... objdump
    checking how to recognize dependent libraries... pass_all
    checking for x86_64-conda_cos6-linux-gnu-dlltool... no
    checking for dlltool... no
    checking how to associate runtime and link libraries... printf %s\n
    checking for x86_64-conda_cos6-linux-gnu-ar... no
    checking for ar... ar
    checking for archiver @FILE support... @
    checking for x86_64-conda_cos6-linux-gnu-strip... no
    checking for strip... strip
    checking for x86_64-conda_cos6-linux-gnu-ranlib... /usr/bin/gcc-ranlib
    checking for gawk... gawk
    checking command to parse nm output from gcc -pthread -B /home/scottshambaugh/anaconda3/envs/py39/compiler_compat object... ok
    checking for sysroot... no
    checking for a working dd... /usr/bin/dd
    checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
    checking for x86_64-conda_cos6-linux-gnu-mt... no
    checking for mt... mt
    checking if mt is a manifest tool... no
    checking for ANSI C header files... yes
    checking for sys/types.h... yes
    checking for sys/stat.h... yes
    checking for stdlib.h... yes
    checking for string.h... yes
    checking for memory.h... yes
    checking for strings.h... yes
    checking for inttypes.h... yes
    checking for stdint.h... yes
    checking for unistd.h... yes
    checking for dlfcn.h... yes
    checking for objdir... .libs
    checking if gcc -pthread -B /home/scottshambaugh/anaconda3/envs/py39/compiler_compat supports -fno-rtti -fno-exceptions... no
    checking for gcc -pthread -B /home/scottshambaugh/anaconda3/envs/py39/compiler_compat option to produce PIC... -fPIC -DPIC
    checking if gcc -pthread -B /home/scottshambaugh/anaconda3/envs/py39/compiler_compat PIC flag -fPIC -DPIC works... yes
    checking if gcc -pthread -B /home/scottshambaugh/anaconda3/envs/py39/compiler_compat static flag -static works... yes
    checking if gcc -pthread -B /home/scottshambaugh/anaconda3/envs/py39/compiler_compat supports -c -o file.o... yes
    checking if gcc -pthread -B /home/scottshambaugh/anaconda3/envs/py39/compiler_compat supports -c -o file.o... (cached) yes
    checking whether the gcc -pthread -B /home/scottshambaugh/anaconda3/envs/py39/compiler_compat linker (/home/scottshambaugh/anaconda3/envs/py39/compiler_compat/ld -m elf_x86_64) supports shared libraries... yes
    checking dynamic linker characteristics... GNU/Linux ld.so
    checking how to hardcode library paths into programs... immediate
    checking whether stripping libraries is possible... yes
    checking if libtool supports shared libraries... yes
    checking whether to build shared libraries... no
    checking whether to build static libraries... yes
    checking for a BSD-compatible install... /usr/bin/install -c
    checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
    checking for ANSI C header files... (cached) yes
    checking fcntl.h usability... yes
    checking fcntl.h presence... yes
    checking for fcntl.h... yes
    checking for unistd.h... (cached) yes
    checking for an ANSI C-conforming const... yes
    checking size of int... 4
    checking size of long... 8
    checking whether cpp computation of bit length in ftconfig.in works... yes
    checking for stdlib.h... (cached) yes
    checking for unistd.h... (cached) yes
    checking for sys/param.h... yes
    checking for getpagesize... yes
    checking for working mmap... yes
    checking whether munmap is declared... yes
    checking for munmap's first parameter type... void *
    checking for memcpy... yes
    checking for memmove... yes
    checking gcc compiler flag -pedantic to assure ANSI C works correctly... ok, add it to XX_ANSIFLAGS
    checking gcc compiler flag -ansi to assure ANSI C works correctly... ok, add it to XX_ANSIFLAGS
    configure: creating ./config.status
    config.status: creating unix-cc.mk
    config.status: creating unix-def.mk
    config.status: creating ftconfig.h
    config.status: executing libtool commands
    configure:
    
    Library configuration:
      external zlib: no
      bzip2:         no
      libpng:        no
      harfbuzz:      no
    
    make: Nothing to be done for 'unix'.
    make: *** /mnt/c/Users/scott.shambaugh/OneDrive: Is a directory.  Stop.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/mnt/c/Users/scott.shambaugh/OneDrive - MyDrive/Documents/repos/matplotlib/setup.py", line 260, in <module>
        setup(  # Finally, pass this all along to setuptools to do the heavy lifting.
      File "/home/scottshambaugh/anaconda3/envs/py39/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/home/scottshambaugh/anaconda3/envs/py39/lib/python3.9/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/scottshambaugh/anaconda3/envs/py39/lib/python3.9/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/home/scottshambaugh/anaconda3/envs/py39/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/scottshambaugh/anaconda3/envs/py39/lib/python3.9/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/home/scottshambaugh/anaconda3/envs/py39/lib/python3.9/site-packages/setuptools/command/develop.py", line 114, in install_for_development
        self.run_command('build_ext')
      File "/home/scottshambaugh/anaconda3/envs/py39/lib/python3.9/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/scottshambaugh/anaconda3/envs/py39/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/scottshambaugh/anaconda3/envs/py39/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/home/scottshambaugh/anaconda3/envs/py39/lib/python3.9/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/mnt/c/Users/scott.shambaugh/OneDrive - MyDrive/Documents/repos/matplotlib/setup.py", line 174, in build_extensions
        package.do_custom_build(env)
      File "/mnt/c/Users/scott.shambaugh/OneDrive - MyDrive/Documents/repos/matplotlib/setupext.py", line 656, in do_custom_build
        subprocess.check_call([make], env=env, cwd=src_path)
      File "/home/scottshambaugh/anaconda3/envs/py39/lib/python3.9/subprocess.py", line 373, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['make']' returned non-zero exit status 2.
    Building freetype in build/freetype-2.6.1
    ----------------------------------------
  Rolling back uninstall of matplotlib
  Moving to /home/scottshambaugh/anaconda3/envs/py39/lib/python3.9/site-packages/__pycache__/pylab.cpython-39.pyc
   from /tmp/pip-uninstall-ztmou20u/pylab.cpython-39.pyc
  Moving to /home/scottshambaugh/anaconda3/envs/py39/lib/python3.9/site-packages/matplotlib-3.5.1-py3.9-nspkg.pth
   from /tmp/pip-uninstall-ibvp5ekm/matplotlib-3.5.1-py3.9-nspkg.pth
  Moving to /home/scottshambaugh/anaconda3/envs/py39/lib/python3.9/site-packages/matplotlib-3.5.1.dist-info/
   from /home/scottshambaugh/anaconda3/envs/py39/lib/python3.9/site-packages/~atplotlib-3.5.1.dist-info
  Moving to /home/scottshambaugh/anaconda3/envs/py39/lib/python3.9/site-packages/matplotlib/
   from /home/scottshambaugh/anaconda3/envs/py39/lib/python3.9/site-packages/~atplotlib
  Moving to /home/scottshambaugh/anaconda3/envs/py39/lib/python3.9/site-packages/mpl_toolkits/axes_grid/
   from /home/scottshambaugh/anaconda3/envs/py39/lib/python3.9/site-packages/mpl_toolkits/~xes_grid
  Moving to /home/scottshambaugh/anaconda3/envs/py39/lib/python3.9/site-packages/mpl_toolkits/axes_grid1/
   from /home/scottshambaugh/anaconda3/envs/py39/lib/python3.9/site-packages/mpl_toolkits/~xes_grid1
  Moving to /home/scottshambaugh/anaconda3/envs/py39/lib/python3.9/site-packages/mpl_toolkits/axisartist/
   from /home/scottshambaugh/anaconda3/envs/py39/lib/python3.9/site-packages/mpl_toolkits/~xisartist
  Moving to /home/scottshambaugh/anaconda3/envs/py39/lib/python3.9/site-packages/mpl_toolkits/mplot3d/
   from /home/scottshambaugh/anaconda3/envs/py39/lib/python3.9/site-packages/mpl_toolkits/~plot3d
  Moving to /home/scottshambaugh/anaconda3/envs/py39/lib/python3.9/site-packages/mpl_toolkits/tests/
   from /home/scottshambaugh/anaconda3/envs/py39/lib/python3.9/site-packages/mpl_toolkits/~ests
  Moving to /home/scottshambaugh/anaconda3/envs/py39/lib/python3.9/site-packages/pylab.py
   from /tmp/pip-uninstall-ibvp5ekm/pylab.py
ERROR: Command errored out with exit status 1: /home/scottshambaugh/anaconda3/envs/py39/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/mnt/c/Users/scott.shambaugh/OneDrive - MyDrive/Documents/repos/matplotlib/setup.py'"'"'; __file__='"'"'/mnt/c/Users/scott.shambaugh/OneDrive - MyDrive/Documents/repos/matplotlib/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
```

### Expected outcome

Installs successfully.

### Operating system

Ubuntu running on WSL

### Matplotlib Version

3.6.0rc1

### Python version

Python 3.9.7

### Installation

git checkout

**Comment by tacaswell** [comment]
Labeling this as a good first issue because there is no API design or discussion here and a clear target (we should compile in any directory).

**Comment by QuLogic** [comment]
I'm not sure there is anything we can fix. The error is in FreeType's build system.

**Comment by scottshambaugh** [comment]
The issue seems to be [here](https://github.com/matplotlib/matplotlib/blob/main/setupext.py#L641) (and a few other lines right there) in passing `src_path` to subprocess, as [this stackoverflow answer](https://stackoverflow.com/questions/18136706/escape-space-in-filepath) talks about.
 > In fact, there are only a handful of functions in Python that need spaces escaped, either because they're passing a string to the shell (like os.system) or because they're trying to do shell-like parsing on your behalf (like subprocess.foo with an arg string instead of an arg list).
 
I think we need to manually escape any spaces in a filepath passed to subprocess here, lemme try to take a swing at doing that in an os-agnostic way.

**Comment by scottshambaugh** [comment]
Ok, I tried escaping the spaces by converting the path to a string and leaving bare, replacing them with single backslash + space or double backslash+space, or enclosing in single, double, or triple quotes. No dice on any. 

I think this is due to some WSL weirdness. I'm having trouble recreating the conditions, but I ended up in a branch of code in [the subprocess module](https://github.com/python/cpython/blob/main/Lib/subprocess.py) that was gated by a `_mswindows` flag. 

Going to close since I don't think there is anything we can do here.

**Comment by QuLogic** [comment]
It's not WSL-specific, just shell. Non-Windows (that includes WSL) uses the `configure` script, which does not quote the source and/or build path sufficiently in several places:
```
    ls: cannot access '-': No such file or directory
    ls: cannot access 'MyDrive/Documents/repos/matplotlib/build/freetype-2.6.1': No such file or directory
    ls: cannot access '-': No such file or directory
    ls: cannot access 'MyDrive/Documents/repos/matplotlib/build/freetype-2.6.1': No such file or directory
```
