### ISSUE TITLE
[Bug]: Installation causes module 'platform' has no attribute 'linux_distribution'

### ISSUE THREAD

**Issue by chanansh** [matplotlib/matplotlib#23780]
### Bug summary

pip install 3.0.3 causes error `AttributeError: module 'platform' has no attribute 'linux_distribution'`

### Code for reproduction

```python
`pip install matplotlib==3.0.3`
```

### Actual outcome

```
Collecting matplotlib==3.0.3
  Using cached matplotlib-3.0.3.tar.gz (36.6 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [49 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-go5lss7q/matplotlib_1a199b31dccd43148bdafcc7f122c4bb/setup.py", line 225, in <module>
          msg = pkg.install_help_msg()
        File "/tmp/pip-install-go5lss7q/matplotlib_1a199b31dccd43148bdafcc7f122c4bb/setupext.py", line 650, in install_help_msg
          release = platform.linux_distribution()[0].lower()
      AttributeError: module 'platform' has no attribute 'linux_distribution'
      ============================================================================
      Edit setup.cfg to change the build options
      
      BUILDING MATPLOTLIB
                  matplotlib: yes [3.0.3]
                      python: yes [3.8.10 (default, Jun 22 2022, 20:18:18)  [GCC
                              9.4.0]]
                    platform: yes [linux]
      
      REQUIRED DEPENDENCIES AND EXTENSIONS
                       numpy: yes [version 1.23.2]
            install_requires: yes [handled by setuptools]
                      libagg: yes [pkg-config information for 'libagg' could not
                              be found. Using local copy.]
                    freetype: no  [The C/C++ header for freetype2 (ft2build.h)
                              could not be found.  You may need to install the
                              development package.]
                         png: no  [pkg-config information for 'libpng' could not
                              be found.]
                       qhull: yes [pkg-config information for 'libqhull' could not
                              be found. Using local copy.]
      
      OPTIONAL SUBPACKAGES
                 sample_data: yes [installing]
                    toolkits: yes [installing]
                       tests: no  [skipping due to configuration]
              toolkits_tests: no  [skipping due to configuration]
      
      OPTIONAL BACKEND EXTENSIONS
                         agg: yes [installing]
                       tkagg: yes [installing; run-time loading from Python Tcl /
                              Tk]
                      macosx: no  [Mac OS-X only]
                   windowing: no  [Microsoft Windows only]
      
      OPTIONAL PACKAGE DATA
                        dlls: no  [skipping due to configuration]
      
      ============================================================================
                              * The following required packages can not be built:
                              * freetype, png
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

### Expected outcome

install successful 

### Operating system

Ubuntu

### Matplotlib Version

3.0.3

### Python version

Python 3.8.10

### Installation

pip

**Comment by QuLogic** [comment]
`platform.linux_distribution` was removed in Python 3.8. Matplotlib 3.0.3 does not support Python 3.8. Please use a newer version.
