### ISSUE TITLE
streamplot raises ValueError when the input is zeros

### ISSUE THREAD

**Issue by dizcza** [matplotlib/matplotlib#23807]
https://github.com/matplotlib/matplotlib/blob/9b1fcf67c4228c4a2788af5bcaf0c6fde09a55bf/lib/matplotlib/streamplot.py#L229

```python
import matplotlib.pyplot as plt
import numpy as np

n = 100

fig, ax = plt.subplots()

ts = np.linspace(-1, 1, n)
grid = np.stack(np.meshgrid(ts, ts), axis=2)

B = np.zeros_like(grid)

sp = ax.streamplot(
    grid[:, :, 0], grid[:, :, 1], B[:, :, 0], B[:, :, 1],
    cmap='coolwarm',
    color=np.random.uniform(size=(n, n))
)

plt.show()
```

```
Traceback (most recent call last):
  File "/home/dizcza/PycharmProjects/other/magpylib/examples/rrr.py", line 13, in <module>
    sp = ax.streamplot(
  File "/home/dizcza/miniconda3/envs/magpylib/lib/python3.10/site-packages/matplotlib/__init__.py", line 1412, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/home/dizcza/miniconda3/envs/magpylib/lib/python3.10/site-packages/matplotlib/streamplot.py", line 227, in streamplot
    lc.set_array(np.ma.hstack(line_colors))
  File "/home/dizcza/miniconda3/envs/magpylib/lib/python3.10/site-packages/numpy/ma/extras.py", line 291, in __call__
    _d = func(tuple([np.asarray(a) for a in x]), *args, **params)
  File "<__array_function__ internals>", line 5, in hstack
  File "/home/dizcza/miniconda3/envs/magpylib/lib/python3.10/site-packages/numpy/core/shape_base.py", line 345, in hstack
    return _nx.concatenate(arrs, 1)
  File "<__array_function__ internals>", line 5, in concatenate
ValueError: need at least one array to concatenate
```

Even if you do not permit zero values as the input, you need to throw a reasonable exception.

The fix I suggest is

```python
    if use_multicolor_lines and len(line_colors) > 0:
        lc.set_array(np.ma.hstack(line_colors))
```

**Comment by tacaswell** [comment]
@dizcza Can you try with the rc?  `pip install --pre --upgrade matplotlib`?  I can reproduce this on 3.5.2 but not on 3.6.0rc2 (or main).
