### ISSUE TITLE
[ENH]: support PySide6's `snake_case`

### ISSUE THREAD

**Issue by bersbersbers** [matplotlib/matplotlib#23816]
### Problem

I use `PySide6` with `snake_case`:
https://doc.qt.io/qtforpython/feature-why.html#the-snake-case-feature

When debugging code in VS Code, I often get this:
> AttributeError: type object 'PySide6.QtWidgets.QFileDialog' has no attribute 'getSaveFileName'

### Proposed solution

In https://github.com/matplotlib/matplotlib/blob/0371cf971ff5c81a963683e3e1c2d48002929e21/lib/matplotlib/backends/qt_compat.py#L100, check if you need to use `QtWidgets.QFileDialog.get_save_file_name`

**Comment by tacaswell** [comment]
Is there a way to query `PySide6` as to which version of the names it is using?  I guess we could just try to access one name and then go from there.  I am surprised that this is the only place that we break.

I think this is a good first issue because the only changes will need to be in `qt_compat`, but medium as it will require understanding what `PySides6` is doing here and why.

From the linked page, it says the naming should only be in effect within a given module which I'm a bit confused how that works. If you create an object in a method in one module and then use it in a function in another, what names do you expect to be able to use based on all the combinations of which module used this feature or not.  Naively I am unclear how this does not end in chaos where you have to know where an object came from to know what methods it will have!

Steps:
 - understand the full impact of PySide coming in two flavours / if this actually requires any action
 - add the shims we need to in `qt_compat.py` to map the names back to the standard names
 - add a test of the backend working under these conditions (will need to be a subprocess test)

I think documenting that Matplotlib is incompatible with this feature is an unfortunate but acceptable outcome.

**Comment by timhoffm** [comment]
> From the linked page, it says the naming should only be in effect within a given module which I'm a bit confused how that works. If you create an object in a method in one module and then use it in a function in another, what names do you expect to be able to use based on all the combinations of which module used this feature or not. Naively I am unclear how this does not end in chaos where you have to know where an object came from to know what methods it will have!

I suppose there's potential for chaos, but it's not that bad in practice. You do not pass around Qt objects a lot. You don't for widgets, and you don't use all the basic types like QString, because they are mapped to Python types.

From https://doc.qt.io/qtforpython/feature-why.html#the-feature-import I understand that `from __feature__ import ...` monkey-patches the import system. Without checking, I assume that an import statement then provides other classes with the same class name but changed function names.

Questions/observations I have in this context:

- In theory, we should not bothered by this because each module uses its own namespace and thus the respective class versions. `qt_compat.py` should be happy to work with CamelCase no matter what another user does.
- We do the import inside a function and make it public via `global`:
  https://github.com/matplotlib/matplotlib/blob/0371cf971ff5c81a963683e3e1c2d48002929e21/lib/matplotlib/backends/qt_compat.py#L72
  AFAICT this should also not break the namespace, but is a non-standard pecularity to note in our code.

In particular @bersbersbers 

- can you please post the full traceback of the exception?
- does this only happen during debugging or also during regular execution? - I would exclude the possibility that both a debugger and pyside try to patch the import system and somehow get into each others way.

**Comment by bersbersbers** [comment]
Brief update (will post a stack trace and if I can, a MWE tomorrow):

> I am surprised that this is the only place that we break.

I am not saying that ;) it's the only crash with a stack trace I saw, though, and I could work around it by selecting a different backend (Agg) before initializing the Qt app. Nonetheless, debugging this app is still a nightmare, as the app/the debugger closes frequently during debugging. Not sure that is related to matplotlib at all, but it may. Using VS Code with pydevd as far as I can tell.

> does this only happen during debugging or also during regular execution? - I wouldn't exclude the possibility that both a debugger and pyside try to patch the import system and somehow get into each others way

Fortunately, only during debugging so far! The app is rock stable otherwise.

**Comment by bersbersbers** [comment]
Here we go!

MWE:

```python
import sys

import matplotlib
from PySide6.QtWidgets import QApplication, QMainWindow

from __feature__ import snake_case  # isort: skip


class Viewer(QMainWindow):
    def __init__(self):
        super().__init__()

        breakpoint()

        print("Hello, world!")


application = QApplication(sys.argv)
viewer = Viewer()
```

Stack trace:
```
Traceback (most recent call last):
  File "c:\Users\bers\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_frame.py", line 987, in trace_dispatch
    self.do_wait_suspend(thread, frame, event, arg)
  File "c:\Users\bers\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_frame.py", line 164, in do_wait_suspend
    self._args[0].do_wait_suspend(*args, **kwargs)
  File "c:\Users\bers\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd.py", line 2062, in do_wait_suspend
    keep_suspended = self._do_wait_suspend(thread, frame, event, arg, suspend_type, from_this_thread, frames_tracker)
  File "c:\Users\bers\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd.py", line 2085, in _do_wait_suspend
    self._activate_gui_if_needed()
  File "c:\Users\bers\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd.py", line 1581, in _activate_gui_if_needed
    activate_function()
  File "c:\Users\bers\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd.py", line 1565, in <lambda>
    self.mpl_modules_for_patching = {"matplotlib": lambda: activate_matplotlib(do_enable_gui),
  File "c:\Users\bers\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydev_ipython\matplotlibtools.py", line 93, in activate_matplotlib
    gui, backend = find_gui_and_backend()
  File "c:\Users\bers\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydev_ipython\matplotlibtools.py", line 45, in find_gui_and_backend
    backend = matplotlib.rcParams['backend']
  File "C:\Users\bers\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\__init__.py", line 674, in __getitem__
    plt.switch_backend(rcsetup._auto_backend_sentinel)
  File "C:\Users\bers\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\pyplot.py", line 262, in switch_backend
    switch_backend(candidate)
  File "C:\Users\bers\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\pyplot.py", line 282, in switch_backend
    class backend_mod(matplotlib.backend_bases._Backend):
  File "C:\Users\bers\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\pyplot.py", line 283, in backend_mod
    locals().update(vars(importlib.import_module(backend_name)))
  File "C:\Users\bers\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\bers\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\backends\backend_qtagg.py", line 9, in <module>
    from .qt_compat import QT_API, _enum, _setDevicePixelRatio
  File "C:\Users\bers\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\backends\qt_compat.py", line 120, in <module>
    _setup_pyqt5plus()
  File "C:\Users\bers\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\backends\qt_compat.py", line 116, in _setup_pyqt5plus
    _getSaveFileName = QtWidgets.QFileDialog.getSaveFileName
AttributeError: type object 'PySide6.QtWidgets.QFileDialog' has no attribute 'getSaveFileName'
Traceback (most recent call last):
  File "C:\Users\bers\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\bers\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\Users\bers\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy\__main__.py", line 39, in <module>
    cli.main()
  File "c:\Users\bers\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
  File "c:\Users\bers\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "c:\Users\bers\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "c:\Users\bers\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "c:\Users\bers\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "c:\Git\project\bug.py", line 19, in <module>
    viewer = Viewer()
  File "c:\Git\project\bug.py", line 13, in __init__
    breakpoint()
  File "c:\Git\project\bug.py", line 13, in __init__
    breakpoint()
  File "c:\Users\bers\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_frame.py", line 987, in trace_dispatch
    self.do_wait_suspend(thread, frame, event, arg)
  File "c:\Users\bers\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_frame.py", line 164, in do_wait_suspend
    self._args[0].do_wait_suspend(*args, **kwargs)
  File "c:\Users\bers\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd.py", line 2062, in do_wait_suspend
    keep_suspended = self._do_wait_suspend(thread, frame, event, arg, suspend_type, from_this_thread, frames_tracker)
  File "c:\Users\bers\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd.py", line 2085, in _do_wait_suspend
    self._activate_gui_if_needed()
  File "c:\Users\bers\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd.py", line 1581, in _activate_gui_if_needed
    activate_function()
  File "c:\Users\bers\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd.py", line 1565, in <lambda>
    self.mpl_modules_for_patching = {"matplotlib": lambda: activate_matplotlib(do_enable_gui),
  File "c:\Users\bers\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydev_ipython\matplotlibtools.py", line 93, in activate_matplotlib
    gui, backend = find_gui_and_backend()
  File "c:\Users\bers\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydev_ipython\matplotlibtools.py", line 45, in find_gui_and_backend
    backend = matplotlib.rcParams['backend']
  File "C:\Users\bers\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\__init__.py", line 674, in __getitem__
    plt.switch_backend(rcsetup._auto_backend_sentinel)
  File "C:\Users\bers\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\pyplot.py", line 262, in switch_backend
    switch_backend(candidate)
  File "C:\Users\bers\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\pyplot.py", line 282, in switch_backend
    class backend_mod(matplotlib.backend_bases._Backend):
  File "C:\Users\bers\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\pyplot.py", line 283, in backend_mod
    locals().update(vars(importlib.import_module(backend_name)))
  File "C:\Users\bers\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\bers\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\backends\backend_qtagg.py", line 9, in <module>
    from .qt_compat import QT_API, _enum, _setDevicePixelRatio
  File "C:\Users\bers\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\backends\qt_compat.py", line 120, in <module>
    _setup_pyqt5plus()
  File "C:\Users\bers\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\backends\qt_compat.py", line 116, in _setup_pyqt5plus
    _getSaveFileName = QtWidgets.QFileDialog.getSaveFileName
AttributeError: type object 'PySide6.QtWidgets.QFileDialog' has no attribute 'getSaveFileName'. Did you mean: 'get_save_file_name'?
```

`pip list`:
```
Package            Version Editable project location
------------------ ------- -------------------------
astroid            2.12.9
colorama           0.4.5
cycler             0.11.0
dill               0.3.5.1
fonttools          4.37.1
humanize           4.3.0
isort              5.10.1
kiwisolver         1.4.4
lazy-object-proxy  1.7.1
matplotlib         3.5.3
mccabe             0.7.0
numpy              1.23.2
packaging          21.3
Pillow             9.2.0
pip                22.2.2
platformdirs       2.5.2
pylint             2.15.0
pyparsing          3.0.9
PyQt6              6.3.1
PyQt6-Qt6          6.3.1
PyQt6-sip          13.4.0
PySide6            6.3.1
PySide6-Addons     6.3.1
PySide6-Essentials 6.3.1
python-dateutil    2.8.2
shiboken6          6.3.1
six                1.16.0
tomli              2.0.1
tomlkit            0.11.4
wrapt              1.14.1
```

**Comment by tacaswell** [comment]
If you order the imports as:

```python
from __feature__ import snake_case  # isort: skip

import sys
from PySide6.QtWidgets import QApplication, QMainWindow

import matplotlib
import matplotlib.backends.qt_compat


class Viewer(QMainWindow):
    def __init__(self):
        super().__init__()

        breakpoint()

        print("Hello, world!")


application = QApplication(sys.argv)
viewer = Viewer()
```

does it not crash?  From the trace back it looks like the debugger has some support for spinning the GUI event loop while in the debugger so is going through making sure there is an event hook available.  It looks like we may need to talk with the pdevd maintainers to see if it is possible to simplify how they interact with us.

**Comment by bersbersbers** [comment]
> If you order the imports as:
> 
> ```python
> from __feature__ import snake_case  # isort: skip
> ...
> ```
> 
> does it not crash? 

It doesn't even run then:

> Exception has occurred: ModuleNotFoundError       (note: full exception trace is shown but execution is paused at: <module>)
> No module named '__feature__'

I came across some discussion related to this at https://bugreports.qt.io/browse/PYSIDE-1754?focusedCommentId=638930&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-638930
For now, it seems one has to import `__feature__` after `PySide6`.

Fixing that, there is some freedom as to when to import `matplotlib`. I experimented with that a bit: This code

```python
import sys

from PySide6.QtWidgets import QApplication, QMainWindow  # isort: skip
from __feature__ import snake_case  # isort: skip

import matplotlib  # isort: skip
import matplotlib.backends.qt_compat  # isort: skip


class Viewer(QMainWindow):
    def __init__(self):
        super().__init__()

        breakpoint()

        print("Hello, world!")


application = QApplication(sys.argv)
viewer = Viewer()
```

gives

```
Failed to enable GUI event loop integration for 'qt'
Traceback (most recent call last):
  File "c:\Users\bers\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydev_ipython\matplotlibtools.py", line 30, in do_enable_gui
    enable_gui(guiname)
  File "c:\Users\bers\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydev_ipython\inputhook.py", line 540, in enable_gui
    return gui_hook(app)
  File "c:\Users\bers\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydev_ipython\inputhook.py", line 176, in enable_qt
    from pydev_ipython.qt_for_kernel import QT_API, QT_API_PYQT5
  File "c:\Users\bers\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydev_ipython\qt_for_kernel.py", line 116, in <module>
    QtCore, QtGui, QtSvg, QT_API = load_qt(api_opts)
  File "c:\Users\bers\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydev_ipython\qt_loaders.py", line 285, in load_qt
    raise ImportError("""
ImportError: 
    Could not load requested Qt binding. Please ensure that
    PyQt4 >= 4.7 or PySide >= 1.0.3 is available,
    and only one is imported per session.

    Currently-imported Qt library:   None
    PyQt4 installed:                 False
    PyQt5 installed:                 False
    PySide >= 1.0.3 installed:       False
    PySide2 installed:               False
    Tried to load:                   ['pyqtdefault', 'pyside', 'pyside2', 'pyqt5']
    
Backend QtAgg is interactive backend. Turning interactive mode on.
```

In addition, I saw this a few times without being able to reproduce this again:

```
Traceback (most recent call last):
  File "c:\Users\bers\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_frame.py", line 987, in trace_dispatch
    self.do_wait_suspend(thread, frame, event, arg)
  File "c:\Users\bers\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_frame.py", line 164, in do_wait_suspend
    self._args[0].do_wait_suspend(*args, **kwargs)
  File "c:\Users\bers\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd.py", line 2062, in do_wait_suspend
    keep_suspended = self._do_wait_suspend(thread, frame, event, arg, suspend_type, from_this_thread, frames_tracker)
  File "c:\Users\bers\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd.py", line 2085, in _do_wait_suspend
    self._activate_gui_if_needed()
  File "c:\Users\bers\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd.py", line 1581, in _activate_gui_if_needed
    activate_function()
  File "c:\Users\bers\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd.py", line 1565, in <lambda>
    self.mpl_modules_for_patching = {"matplotlib": lambda: activate_matplotlib(do_enable_gui),
  File "c:\Users\bers\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydev_ipython\matplotlibtools.py", line 93, in activate_matplotlib
    gui, backend = find_gui_and_backend()
  File "c:\Users\bers\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydev_ipython\matplotlibtools.py", line 45, in find_gui_and_backend
    backend = matplotlib.rcParams['backend']
  File "C:\Users\bers\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\__init__.py", line 673, in __getitem__
    from matplotlib import pyplot as plt
  File "C:\Users\bers\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\pyplot.py", line 49, in <module>
    import matplotlib.colorbar
  File "C:\Users\bers\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\colorbar.py", line 21, in <module>
    from matplotlib import _api, collections, cm, colors, contour, ticker
  File "C:\Users\bers\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\contour.py", line 13, in <module>
    from matplotlib.backend_bases import MouseButton
  File "C:\Users\bers\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\backend_bases.py", line 46, in <module>
    from matplotlib import (
  File "C:\Users\bers\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\textpath.py", line 8, in <module>
    from matplotlib import _text_helpers, dviread, font_manager
  File "C:\Users\bers\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\dviread.py", line 177, in <module>
    class Dvi:
  File "C:\Users\bers\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\dviread.py", line 209, in Dvi
    baseline = _api.deprecated("3.5")(property(lambda self: None))
  File "C:\Users\bers\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\_api\deprecation.py", line 207, in deprecate
    old_doc = inspect.cleandoc(old_doc or '').strip('\n')
  File "C:\Users\bers\AppData\Local\Programs\Python\Python310\lib\inspect.py", line 750, in cleandoc
    lines = doc.expandtabs().split('\n')
AttributeError: 'dict' object has no attribute 'expandtabs'
Traceback (most recent call last):
  File "C:\Users\bers\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\bers\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\Users\bers\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy\__main__.py", line 39, in <module>
    cli.main()
  File "c:\Users\bers\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
  File "c:\Users\bers\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "c:\Users\bers\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "c:\Users\bers\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "c:\Users\bers\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "c:\Git\Project\bug.py", line 20, in <module>
    viewer = Viewer()
  File "c:\Git\Project\bug.py", line 14, in __init__
    breakpoint()
  File "c:\Git\Project\bug.py", line 14, in __init__
    breakpoint()
  File "c:\Users\bers\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_frame.py", line 987, in trace_dispatch
    self.do_wait_suspend(thread, frame, event, arg)
  File "c:\Users\bers\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_frame.py", line 164, in do_wait_suspend
    self._args[0].do_wait_suspend(*args, **kwargs)
  File "c:\Users\bers\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd.py", line 2062, in do_wait_suspend
    keep_suspended = self._do_wait_suspend(thread, frame, event, arg, suspend_type, from_this_thread, frames_tracker)
  File "c:\Users\bers\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd.py", line 2085, in _do_wait_suspend
    self._activate_gui_if_needed()
  File "c:\Users\bers\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd.py", line 1581, in _activate_gui_if_needed
    activate_function()
  File "c:\Users\bers\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd.py", line 1565, in <lambda>
    self.mpl_modules_for_patching = {"matplotlib": lambda: activate_matplotlib(do_enable_gui),
  File "c:\Users\bers\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydev_ipython\matplotlibtools.py", line 93, in activate_matplotlib
    gui, backend = find_gui_and_backend()
  File "c:\Users\bers\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydev_ipython\matplotlibtools.py", line 45, in find_gui_and_backend
    backend = matplotlib.rcParams['backend']
  File "C:\Users\bers\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\__init__.py", line 673, in __getitem__
    from matplotlib import pyplot as plt
  File "C:\Users\bers\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\pyplot.py", line 49, in <module>
    import matplotlib.colorbar
  File "C:\Users\bers\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\colorbar.py", line 21, in <module>
    from matplotlib import _api, collections, cm, colors, contour, ticker
  File "C:\Users\bers\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\contour.py", line 13, in <module>
    from matplotlib.backend_bases import MouseButton
  File "C:\Users\bers\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\backend_bases.py", line 46, in <module>
    from matplotlib import (
  File "C:\Users\bers\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\textpath.py", line 8, in <module>
    from matplotlib import _text_helpers, dviread, font_manager
  File "C:\Users\bers\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\dviread.py", line 177, in <module>
    class Dvi:
  File "C:\Users\bers\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\dviread.py", line 209, in Dvi
    baseline = _api.deprecated("3.5")(property(lambda self: None))
  File "C:\Users\bers\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\_api\deprecation.py", line 207, in deprecate
    old_doc = inspect.cleandoc(old_doc or '').strip('\n')
  File "C:\Users\bers\AppData\Local\Programs\Python\Python310\lib\inspect.py", line 750, in cleandoc
    lines = doc.expandtabs().split('\n')
AttributeError: 'dict' object has no attribute 'expandtabs'
```

**Comment by tacaswell** [comment]
That makes sense as then Matplotlib does not try to import any sort of Qt (which given you are working on a large application (and I assume embedding)) this may be a good thing to do anyway (or to do `sys.modules['matplotlib.pyplot'] = None` to make sure pyplot _never_ gets imported).

**Comment by bersbersbers** [comment]
> do `sys.modules['matplotlib.pyplot'] = None` to make sure pyplot _never_ gets imported

By the way, have you tried that? Surely `pyplot` cannot be imported anymore, then, but I am getting all kinds of errors doing that, such as

> Fatal Python error: failed to create a new feature set!
Python runtime state: initialized
Traceback (most recent call last):
  File "shibokensupport/signature/loader.py", line 70, in pyside_type_init
  File "shibokensupport/signature/parser.py", line 562, in pyside_type_init
  File "shibokensupport/signature/mapping.py", line 196, in update
  File "shibokensupport/signature/mapping.py", line 197, in <genexpr>
  File "shibokensupport/signature/mapping.py", line 182, in module_valid
AttributeError: 'NoneType' object has no attribute '__name__'. Did you mean: '__ne__'?

I think I might just look for a more light-weight replacement of `matplotlib.cm` after all ;)
