### ISSUE TITLE
[Bug]: ValueError: cannot convert float NaN to integer error when saving a plot as a figure in png via plt.savefig

### ISSUE THREAD

**Issue by techGIAN** [matplotlib/matplotlib#23923]
### Bug summary

I am getting this error whenever I try to save a plot as a figure through `plt.savefig('filename.png')`:
```
ValueError: cannot convert float NaN to integer 
```
I am not sure why this is happening because all other plots that I have seems to be working fine whenever I try saving it.

### Code for reproduction

```python
import osmnx as ox
import matplotlib.pyplot as plt

'''
   Plots map given gdf and configs
   Params:
   ------
   gdf: geodataframe with columns ['id', 'geometry', 'color']
   configs: a dictionary of parameters
'''
def plot_map(gdf, configs):

    city = ox.geocode_to_gdf(configs['city'])
    ax = city.plot(color=configs['map_color'], edgecolor=str(configs['map_edge_color']))
    gdf.plot(ax=ax, color=gdf['color'], edgecolor=str(configs['segment_edge_color']))
    plt.axis([configs['min_lon'], configs['max_lon'], configs['min_lat'], configs['max_lat']])

    title = 'Road Map of ' + configs['city']
    plt.title(title)

    if configs['save_map']:
        save_name = configs['save_name']
        plt.savefig('../visualizations/' + save_name)

    plt.show()
```

### Actual outcome

```
Traceback (most recent call last):
  File "/project/util/visualization.py", line 242, in <module>
    plot_map(gdf, configs)
  File "/project/util/visualization.py", line 134, in plot_map
    plt.savefig('../visualizations/' + save_name)
  File "/opt/homebrew/lib/python3.10/site-packages/matplotlib/pyplot.py", line 942, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/matplotlib/figure.py", line 3272, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/matplotlib/backend_bases.py", line 2338, in print_figure
    result = print_method(
  File "/opt/homebrew/lib/python3.10/site-packages/matplotlib/backend_bases.py", line 2204, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/opt/homebrew/lib/python3.10/site-packages/matplotlib/_api/deprecation.py", line 410, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/matplotlib/backends/backend_agg.py", line 520, in print_png
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/opt/homebrew/lib/python3.10/site-packages/matplotlib/backends/backend_agg.py", line 466, in _print_pil
    FigureCanvasAgg.draw(self)
  File "/opt/homebrew/lib/python3.10/site-packages/matplotlib/backends/backend_agg.py", line 408, in draw
    self.figure.draw(self.renderer)
  File "/opt/homebrew/lib/python3.10/site-packages/matplotlib/artist.py", line 74, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/homebrew/lib/python3.10/site-packages/matplotlib/figure.py", line 3069, in draw
    mimage._draw_list_compositing_images(
  File "/opt/homebrew/lib/python3.10/site-packages/matplotlib/image.py", line 131, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/homebrew/lib/python3.10/site-packages/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/homebrew/lib/python3.10/site-packages/matplotlib/axes/_base.py", line 3070, in draw
    self._update_title_position(renderer)
  File "/opt/homebrew/lib/python3.10/site-packages/matplotlib/axes/_base.py", line 3014, in _update_title_position
    ax.yaxis.get_tightbbox(renderer)  # update offsetText
  File "/opt/homebrew/lib/python3.10/site-packages/matplotlib/axis.py", line 1251, in get_tightbbox
    ticks_to_draw = self._update_ticks()
  File "/opt/homebrew/lib/python3.10/site-packages/matplotlib/axis.py", line 1190, in _update_ticks
    major_locs = self.get_majorticklocs()
  File "/opt/homebrew/lib/python3.10/site-packages/matplotlib/axis.py", line 1416, in get_majorticklocs
    return self.major.locator()
  File "/opt/homebrew/lib/python3.10/site-packages/matplotlib/ticker.py", line 2143, in __call__
    return self.tick_values(vmin, vmax)
  File "/opt/homebrew/lib/python3.10/site-packages/matplotlib/ticker.py", line 2151, in tick_values
    locs = self._raw_ticks(vmin, vmax)
  File "/opt/homebrew/lib/python3.10/site-packages/matplotlib/ticker.py", line 2090, in _raw_ticks
    nbins = np.clip(self.axis.get_tick_space(),
  File "/opt/homebrew/lib/python3.10/site-packages/matplotlib/axis.py", line 2681, in get_tick_space
    return int(np.floor(length / size))
ValueError: cannot convert float NaN to integer
```

### Expected outcome

I am expecting it to do two things:
1. to be able to save the plot in the specified directory with the specified filename.
2. to be able to display the plot using `plt.show()`

### Operating system

Mac OS 12.2.1

### Matplotlib Version

3.6.0

### Matplotlib Backend

MacOSX

### Python version

3.10.6

### Installation

pip

**Comment by jklymak** [comment]
Sorry this broke for your.  However, please provide a self-contained example, preferably using just matplotlib and numpy.  We don't know what a geodataframe might be, nor do we provide its `plot` method.  If you can't reproduce with just matplotlib, please ask whoever provides `gdf.plot` it to investigate and report a new issue.  

3.6 is also a new version, so perhaps you will have better luck rolling back to 3.5.3.

**Comment by tacaswell** [comment]
Probably is this method https://github.com/matplotlib/matplotlib/blob/4a5d09cba5f4a20e14553cebd8f70c1f34d20d35/lib/matplotlib/axis.py#L2692-L2701

We already have some checking to make sure that `size` is positive (so we do not generate a divide by 0) but apparently not enough.  Without the ability to reproduce this, I am guessing, but I suspect that something about the transform is taking the unit box in Axes space to invalid values (which is not something I would have expected).

The pragmatic fix is to the return is `try...except ValueError: return 2**31-1`, but we should try to understand why this is invalid which will require help from (I think) geopandas.  I also have a concern that this bug is dependent on the lat/long specified as the limits.  @techGIAN Do you have a minimal copy-paste-run example that shows this problem?

**Comment by jklymak** [comment]
I'm going to close this for lack of response.  However, feel free to request a re-open if reproducible example is possible.  Thanks!

**Comment by DavidHuber-NOAA** [comment]
May be a duplicate of #28762.
