### ISSUE TITLE
[Bug]: plotnine broken with matplotlib 3.6

### ISSUE THREAD

**Issue by HaoranYi** [matplotlib/matplotlib#23970]
### Bug summary

plotnine==0.9
matplotlib==3.6
Here is the call stack.
```
Traceback (most recent call last):
  File "D:\mydoc\git\kin_scripts\nb\plotnine_ex.py", line 1, in <module>
    from plotnine import ggplot, geom_point, aes, stat_smooth, facet_wrap
  File "D:\Python\Python310\lib\site-packages\plotnine\__init__.py", line 1, in <module>
    from .qplot import qplot            # noqa: F401
  File "D:\Python\Python310\lib\site-packages\plotnine\qplot.py", line 9, in <module>
    from .ggplot import ggplot
  File "D:\Python\Python310\lib\site-packages\plotnine\ggplot.py", line 18, in <module>
    from .facets import facet_null
  File "D:\Python\Python310\lib\site-packages\plotnine\facets\__init__.py", line 1, in <module>
    from .facet_grid import facet_grid
  File "D:\Python\Python310\lib\site-packages\plotnine\facets\facet_grid.py", line 6, in <module>
    from .facet import facet, layout_null, combine_vars, add_missing_facets
  File "D:\Python\Python310\lib\site-packages\plotnine\facets\facet.py", line 14, in <module>
    from ..scales.scales import Scales
  File "D:\Python\Python310\lib\site-packages\plotnine\scales\__init__.py", line 83, in <module>
    from .limits import xlim, ylim, lims, expand_limits
  File "D:\Python\Python310\lib\site-packages\plotnine\scales\limits.py", line 8, in <module>
    from ..geoms import geom_blank
  File "D:\Python\Python310\lib\site-packages\plotnine\geoms\__init__.py", line 6, in <module>
    from .geom_abline import geom_abline
  File "D:\Python\Python310\lib\site-packages\plotnine\geoms\geom_abline.py", line 9, in <module>
    from .geom import geom
  File "D:\Python\Python310\lib\site-packages\plotnine\geoms\geom.py", line 3, in <module>
    from ..stats.stat import stat
  File "D:\Python\Python310\lib\site-packages\plotnine\stats\__init__.py", line 7, in <module>
    from .stat_density_2d import stat_density_2d
  File "D:\Python\Python310\lib\site-packages\plotnine\stats\stat_density_2d.py", line 3, in <module>
    import matplotlib._contour as _contour
ModuleNotFoundError: No module named 'matplotlib._contour'
```

### Code for reproduction

```python
from plotnine.data import economics
from plotnine import ggplot, aes, geom_line

(
    ggplot(economics)  # What data to use
    + aes(x="date", y="pop")  # What variable to use
    + geom_line()  # Geometric object to use for drawing
)
```

### Actual outcome

Traceback (most recent call last):
  File "D:\mydoc\git\kin_scripts\nb\plotnine_ex.py", line 1, in <module>
    from plotnine import ggplot, geom_point, aes, stat_smooth, facet_wrap
  File "D:\Python\Python310\lib\site-packages\plotnine\__init__.py", line 1, in <module>
    from .qplot import qplot            # noqa: F401
  File "D:\Python\Python310\lib\site-packages\plotnine\qplot.py", line 9, in <module>
    from .ggplot import ggplot
  File "D:\Python\Python310\lib\site-packages\plotnine\ggplot.py", line 18, in <module>
    from .facets import facet_null
  File "D:\Python\Python310\lib\site-packages\plotnine\facets\__init__.py", line 1, in <module>
    from .facet_grid import facet_grid
  File "D:\Python\Python310\lib\site-packages\plotnine\facets\facet_grid.py", line 6, in <module>
    from .facet import facet, layout_null, combine_vars, add_missing_facets
  File "D:\Python\Python310\lib\site-packages\plotnine\facets\facet.py", line 14, in <module>
    from ..scales.scales import Scales
  File "D:\Python\Python310\lib\site-packages\plotnine\scales\__init__.py", line 83, in <module>
    from .limits import xlim, ylim, lims, expand_limits
  File "D:\Python\Python310\lib\site-packages\plotnine\scales\limits.py", line 8, in <module>
    from ..geoms import geom_blank
  File "D:\Python\Python310\lib\site-packages\plotnine\geoms\__init__.py", line 6, in <module>
    from .geom_abline import geom_abline
  File "D:\Python\Python310\lib\site-packages\plotnine\geoms\geom_abline.py", line 9, in <module>
    from .geom import geom
  File "D:\Python\Python310\lib\site-packages\plotnine\geoms\geom.py", line 3, in <module>
    from ..stats.stat import stat
  File "D:\Python\Python310\lib\site-packages\plotnine\stats\__init__.py", line 7, in <module>
    from .stat_density_2d import stat_density_2d
  File "D:\Python\Python310\lib\site-packages\plotnine\stats\stat_density_2d.py", line 3, in <module>
    import matplotlib._contour as _contour
ModuleNotFoundError: No module named 'matplotlib._contour'

### Expected outcome

None.

### Matplotlib Version

3.6

**Comment by jklymak** [comment]
plotnine will have to update to not use our private methods.  You can report at https://github.com/has2k1/plotnine but I don't think we have an action item here.

**Comment by HaoranYi** [comment]
ah. looks like it is already fixed in plotnine
https://github.com/has2k1/plotnine/commit/c48d5a26ab0d0a54ed47bbefc6a83b5fcb2af616
