### ISSUE TITLE
[Bug]: 3.6.0 source build fails due to extraneous egg

### ISSUE THREAD

**Issue by adamjstewart** [matplotlib/matplotlib#23997]
### Bug summary

I'm trying to update matplotlib's build recipe in the [Spack](https://spack.io) package manager: https://github.com/spack/spack/pull/32697. However, I'm seeing a build issue relating to setuptools_scm eggs with matplotlib 3.6.0.

### Code for reproduction

```console
$ git clone https://github.com/adamjstewart/spack.git
$ cd spack
$ git switch packages/py-matplotlib
$ . share/spack/setup-env.sh
$ spack install -v py-matplotlib
```

### Actual outcome

When Spack tries to build matplotlib 3.6.0 from source, it encounters the following build error:
```
  Running command python setup.py egg_info
  /Users/ajstewart/spack/opt/spack/darwin-monterey-m1/apple-clang-14.0.0/py-setuptools-59.4.0-dqzwkpn6u6adsjaq6bsekgzw3uycrjed/lib/python3.9/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
    warnings.warn(
  /Users/ajstewart/spack/opt/spack/darwin-monterey-m1/apple-clang-14.0.0/py-setuptools-59.4.0-dqzwkpn6u6adsjaq6bsekgzw3uycrjed/lib/python3.9/site-packages/setuptools/dist.py:812: UserWarning: Module setuptools_scm was already imported from /Users/ajstewart/spack/opt/spack/darwin-monterey-m1/apple-clang-14.0.0/py-setuptools-scm-6.3.2-4tfhn74oz5h2pslhsj46qdatho4wzqzv/lib/python3.9/site-packages/setuptools_scm/__init__.py, but /private/var/folders/j1/68dlgpr91vlgs26vty2c8xk80000gn/T/ajstewart/spack-stage/spack-stage-py-matplotlib-3.6.0-6zhze6nbympybh4pi72na2fceeonseco/spack-src/.eggs/setuptools_scm-7.0.5-py3.9.egg is being added to sys.path
    pkg_resources.working_set.add(dist, replace=True)
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "/private/var/folders/j1/68dlgpr91vlgs26vty2c8xk80000gn/T/ajstewart/spack-stage/spack-stage-py-matplotlib-3.6.0-6zhze6nbympybh4pi72na2fceeonseco/spack-src/setup.py", line 260, in <module>
      setup(  # Finally, pass this all along to setuptools to do the heavy lifting.
    File "/Users/ajstewart/spack/opt/spack/darwin-monterey-m1/apple-clang-14.0.0/py-setuptools-59.4.0-dqzwkpn6u6adsjaq6bsekgzw3uycrjed/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/Users/ajstewart/spack/opt/spack/darwin-monterey-m1/apple-clang-14.0.0/python-3.9.13-j5uwi4faknh6e6wukglkq7djfq5wbo4j/lib/python3.9/distutils/core.py", line 108, in setup
      _setup_distribution = dist = klass(attrs)
    File "/Users/ajstewart/spack/opt/spack/darwin-monterey-m1/apple-clang-14.0.0/py-setuptools-59.4.0-dqzwkpn6u6adsjaq6bsekgzw3uycrjed/lib/python3.9/site-packages/setuptools/dist.py", line 453, in __init__
      _Distribution.__init__(
    File "/Users/ajstewart/spack/opt/spack/darwin-monterey-m1/apple-clang-14.0.0/python-3.9.13-j5uwi4faknh6e6wukglkq7djfq5wbo4j/lib/python3.9/distutils/dist.py", line 292, in __init__
      self.finalize_options()
    File "/Users/ajstewart/spack/opt/spack/darwin-monterey-m1/apple-clang-14.0.0/py-setuptools-59.4.0-dqzwkpn6u6adsjaq6bsekgzw3uycrjed/lib/python3.9/site-packages/setuptools/dist.py", line 831, in finalize_options
      ep(self)
    File "/Users/ajstewart/spack/opt/spack/darwin-monterey-m1/apple-clang-14.0.0/py-setuptools-59.4.0-dqzwkpn6u6adsjaq6bsekgzw3uycrjed/lib/python3.9/site-packages/setuptools/dist.py", line 852, in _finalize_setup_keywords
      ep.load()(self, ep.name, value)
    File "/Users/ajstewart/spack/opt/spack/darwin-monterey-m1/apple-clang-14.0.0/py-setuptools-scm-6.3.2-4tfhn74oz5h2pslhsj46qdatho4wzqzv/lib/python3.9/site-packages/setuptools_scm/integration.py", line 65, in version_keyword
      dist.metadata.version = _get_version(config)
    File "/Users/ajstewart/spack/opt/spack/darwin-monterey-m1/apple-clang-14.0.0/py-setuptools-scm-6.3.2-4tfhn74oz5h2pslhsj46qdatho4wzqzv/lib/python3.9/site-packages/setuptools_scm/__init__.py", line 177, in _get_version
      parsed_version = _do_parse(config)
    File "/Users/ajstewart/spack/opt/spack/darwin-monterey-m1/apple-clang-14.0.0/py-setuptools-scm-6.3.2-4tfhn74oz5h2pslhsj46qdatho4wzqzv/lib/python3.9/site-packages/setuptools_scm/__init__.py", line 128, in _do_parse
      version = _version_from_entrypoints(config) or _version_from_entrypoints(
    File "/Users/ajstewart/spack/opt/spack/darwin-monterey-m1/apple-clang-14.0.0/py-setuptools-scm-6.3.2-4tfhn74oz5h2pslhsj46qdatho4wzqzv/lib/python3.9/site-packages/setuptools_scm/__init__.py", line 69, in _version_from_entrypoints
      version = _call_entrypoint_fn(root, config, ep.load())
    File "/Users/ajstewart/spack/opt/spack/darwin-monterey-m1/apple-clang-14.0.0/python-3.9.13-j5uwi4faknh6e6wukglkq7djfq5wbo4j/lib/python3.9/importlib/metadata.py", line 88, in load
      return functools.reduce(getattr, attrs, module)
  AttributeError: module 'setuptools_scm.git' has no attribute 'parse_archival'
```
I'm guessing what's happening here is that the setuptools_scm version we have installed is incompatible with the setuptools_scm egg in the source directory, but I have no idea where that egg would be coming from. Matplotlib 3.5.3 builds fine, did anything change in 3.6.0 w.r.t. setuptools_scm/eggs?

### Expected outcome

I would expect matplotlib 3.6.0 to build fine, just like 3.5.3.

### Additional information

Build log: 
* [spack-build-out.txt](https://github.com/matplotlib/matplotlib/files/9639630/spack-build-out.txt)

`mplsetup.cfg`:
```ini
[rc_options]
backend = macosx
[libs]
system_freetype = True
system_qhull = True
```

### Operating system

macOS 12.6

### Matplotlib Version

3.6.0

### Matplotlib Backend

macosx

### Python version

3.9.13

### Jupyter version

N/A

### Installation

from source (.tar.gz)

**Comment by oscargus** [comment]
I cannot say that I fully know the subject, but we do require setuptools_scm >= 7 in some situations (and this may be one of them). For various reasons we tried to solve it dynamically:
https://github.com/matplotlib/matplotlib/blob/cada8fb565b1e1cfeb076f1f6ab791b1640d387d/setup.py#L319-L323
but it may be that this doesn't trigger as a requirement in your situation.

**Comment by adamjstewart** [comment]
Thanks for the hint, my version of setuptools-scm turned out to be outdated. After updating that, I'm able to successfully build!
