### ISSUE TITLE
[Bug]: stairs is broken on 3D Axes

### ISSUE THREAD

**Issue by QuLogic** [matplotlib/matplotlib#24222]
### Bug summary

For example, if you modify the `stairs_demo.py` example as below, it will cause an exception at runtime.

### Code for reproduction

```python
diff --git a/examples/lines_bars_and_markers/stairs_demo.py b/examples/lines_bars_and_markers/stairs_demo.py
index 79f63975b3..44f2527ae4 100644
--- a/examples/lines_bars_and_markers/stairs_demo.py
+++ b/examples/lines_bars_and_markers/stairs_demo.py
@@ -17,7 +17,8 @@ np.random.seed(0)
 h, edges = np.histogram(np.random.normal(5, 3, 5000),
                         bins=np.linspace(0, 10, 20))
 
-fig, axs = plt.subplots(3, 1, figsize=(7, 15))
+fig, axs = plt.subplots(3, 1, figsize=(7, 15),
+                        subplot_kw=dict(projection='3d'))
 axs[0].stairs(h, edges, label='Simple histogram')
 axs[0].stairs(h, edges + 5, baseline=50, label='Modified baseline')
 axs[0].stairs(h, edges + 10, baseline=None, label='No edges')
```

### Actual outcome

```pytb
Traceback (most recent call last):
  File "/home/elliott/code/matplotlib/lib/matplotlib/backends/backend_qt.py", line 456, in _draw_idle
    self.draw()
  File "/home/elliott/code/matplotlib/lib/matplotlib/backends/backend_agg.py", line 408, in draw
    self.figure.draw(self.renderer)
  File "/home/elliott/code/matplotlib/lib/matplotlib/artist.py", line 74, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/home/elliott/code/matplotlib/lib/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer)
  File "/home/elliott/code/matplotlib/lib/matplotlib/figure.py", line 3072, in draw
    mimage._draw_list_compositing_images(
  File "/home/elliott/code/matplotlib/lib/matplotlib/image.py", line 131, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/elliott/code/matplotlib/lib/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer)
  File "/home/elliott/code/matplotlib/lib/mpl_toolkits/mplot3d/axes3d.py", line 469, in draw
    for artist in sorted(collections_and_patches,
  File "/home/elliott/code/matplotlib/lib/mpl_toolkits/mplot3d/axes3d.py", line 470, in <lambda>
    key=lambda artist: artist.do_3d_projection(),
AttributeError: 'StepPatch' object has no attribute 'do_3d_projection'
```

### Expected outcome

If we know what `stairs` should look like in 3D, then we should implement it with the proper upgrade from 2D to 3D.

If `stairs` is unsupported in 3D, then it should raise when called, instead of at draw time.

### Matplotlib Version

14c96b510ebeba40f573e512299b1976f35b620e

### Installation

git checkout

**Comment by timhoffm** [comment]
It is a major design flaw that `Axes3D` inherits from `Axes`. This brings in lots of functions that were never considered to work for 3D. 

To make any Artist-creating function work, you have to overwite it's API (for adding the information on the additional dimension) and you have to create 3D versions of the Artists.

I bet we have many more functions that are broken in 3D.

--

Things that could be done here:
a) implement stairs for 3d (if there are volunteers)
b) Overwrite the the function to raise - should probably be done in a systematic way for a lot of functions.
c) Long-term: Do not inherit from Axes. This would be a major effort.

I suggest b) for now.

**Comment by QuLogic** [comment]
This also affects `streamplot`; later I will go through and see if there are others.

**Comment by AlbertoPdRF** [comment]
Hi @timhoffm,

Could you help me figure out how option a) would look like? I am interested in implementing `stairs` for 3D, but some guidance would be needed.

**Comment by timhoffm** [comment]
`stairs` for 3D would basically be analogous to `plot` in 3D. You need to

- create a 3D version of the underlying Artist, i.e. a `StepPatch3D` deriving from `StepPatch`. Compare the `Line3D` derived from `Line2D`: https://github.com/matplotlib/matplotlib/blob/d239b3620fba0002e46d216c6ab3165f5f79ec11/lib/mpl_toolkits/mplot3d/art3d.py#L183
- reimplement `stairs` in `Axes3D` to accept suitable 3D inputs and return a `StepPatch3D`. Compare the reimplementation of `plot` in `Axes3D`: https://github.com/matplotlib/matplotlib/blob/d239b3620fba0002e46d216c6ab3165f5f79ec11/lib/mpl_toolkits/mplot3d/axes3d.py#L1918

**Comment by AlbertoPdRF** [comment]
Thank you! I was playing around yesterday and ended up doing something similar to what you said, although probably the implementation needs some adjustements: https://github.com/matplotlib/matplotlib/compare/main...AlbertoPdRF:matplotlib:stairs3d
