### ISSUE TITLE
[Bug]: pyplot.subplots raises error when passing 'width_ratios' argument

### ISSUE THREAD

**Issue by afonsocrg** [matplotlib/matplotlib#24285]
### Bug summary

When I try to create a plot grid with different column sizes using the 'width_ratios' argument, Python raises an Attribute Error, indicating that `'Figure' object has no property 'width_ratios'`

### Code for reproduction

```python
from matplotlib import pyplot as plt

fig, axs = plt.subplots(2, 2, width_ratio = [5, 3])
```

### Actual outcome

```
Traceback (most recent call last):
  File "~/self_contained.py", line 4, in <module>
    fig, axs = plt.subplots(2, 2, width_ratio = [5, 3])
  File "/home/user/.local/lib/python3.10/site-packages/matplotlib/pyplot.py", line 1455, in subplots
    fig = figure(**fig_kw)
  File "/home/user/.local/lib/python3.10/site-packages/matplotlib/pyplot.py", line 808, in figure
    manager = new_figure_manager(
  File "/home/user/.local/lib/python3.10/site-packages/matplotlib/pyplot.py", line 327, in new_figure_manager
    return _get_backend_mod().new_figure_manager(*args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/matplotlib/backend_bases.py", line 3493, in new_figure_manager
    fig = fig_cls(*args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/matplotlib/figure.py", line 2292, in __init__
    super().__init__(**kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/matplotlib/figure.py", line 216, in __init__
    self.set(**kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/matplotlib/artist.py", line 116, in <lambda>
    cls.set = lambda self, **kwargs: Artist.set(self, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/matplotlib/artist.py", line 1164, in set
    return self.update(kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/matplotlib/artist.py", line 1064, in update
    raise AttributeError(f"{type(self).__name__!r} object "
AttributeError: 'Figure' object has no property 'width_ratio'
```

### Expected outcome

I expected the code to create subplots with the given width ratio

### Additional information

When I call `plt.subplots(nrows=2, ncols=2, gridspec_kw={'width_ratios': [5, 3]})`, it works perfectly

### Operating system

Arch

### Matplotlib Version

3.5.2

### Matplotlib Backend

agg

### Python version

3.10.8

**Comment by QuLogic** [comment]
That is new in 3.6; also you wrote `width_ratio` instead of `width_ratios`.
