### ISSUE TITLE
[Bug]:  TypeError: '>' not supported between instances of 'NoneType' and 'NoneType'

### ISSUE THREAD

**Issue by ahcm** [matplotlib/matplotlib#24316]
### Bug summary

longread_plots (https://github.com/ahcm/longread_plots) produces:
$ ./bin/lrplot t.fastq
[...]
TypeError: '>' not supported between instances of 'NoneType' and 'NoneType'

### Code for reproduction

```python
Use on a FastQ file: https://github.com/ahcm/longread_plots

$ python
Python 3.9.15 (main, Oct 11 2022, 21:39:54)
[Clang 14.0.0 (clang-1400.0.29.102)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib
>>> matplotlib.__version__
'3.6.1'
```
### Actual outcome

```
Traceback (most recent call last):
  File "/Users/andy/github/ahcm/longread_plots/bin/lrplot", line 423, in <module>
    plt.savefig(basename + "-lrplots.png")
  File "/opt/homebrew/lib/python3.9/site-packages/matplotlib/pyplot.py", line 979, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/matplotlib/figure.py", line 3046, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2319, in print_figure
    result = print_method(
  File "/opt/homebrew/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 1648, in wrapper
    return func(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/matplotlib/_api/deprecation.py", line 415, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 540, in print_png
    FigureCanvasAgg.draw(self)
  File "/opt/homebrew/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 436, in draw
    self.figure.draw(self.renderer)
  File "/opt/homebrew/lib/python3.9/site-packages/matplotlib/artist.py", line 73, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/homebrew/lib/python3.9/site-packages/matplotlib/figure.py", line 2837, in draw
    mimage._draw_list_compositing_images(
  File "/opt/homebrew/lib/python3.9/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/homebrew/lib/python3.9/site-packages/matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/homebrew/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 3091, in draw
    mimage._draw_list_compositing_images(
  File "/opt/homebrew/lib/python3.9/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/homebrew/lib/python3.9/site-packages/matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/homebrew/lib/python3.9/site-packages/matplotlib/collections.py", line 2175, in draw
    self.update_scalarmappable()
  File "/opt/homebrew/lib/python3.9/site-packages/matplotlib/collections.py", line 905, in update_scalarmappable
    self._mapped_colors = self.to_rgba(self._A, self._alpha)
  File "/opt/homebrew/lib/python3.9/site-packages/matplotlib/cm.py", line 455, in to_rgba
    x = self.norm(x)
  File "/opt/homebrew/lib/python3.9/site-packages/matplotlib/colors.py", line 1530, in __call__
    if self.vmin > self.vmax:
TypeError: '>' not supported between instances of 'NoneType' and 'NoneType'
```

### Expected outcome

Do not throw exception and save figure.

### Operating system

MacOS, Archlinux, Ubuntu

### Matplotlib Version

3.6.1

**Comment by ahcm** [comment]
Example fastq file:
```
@1 runid=bd8c2bdcba8fbc35803a5c9164bc981e1544a581 sampleid=20221026_C12 read=180 ch=150 start_time=2022-10-26T10:34:57Z model_version_id=2021-05-05_dna_r9.4.1_promethion_384_dd219f32
AGTC
+
@@@@
@2 runid=bd8c2bdcba8fbc35803a5c9164bc981e1544a581 sampleid=20221026_C12 read=181 ch=150 start_time=2022-10-26T10:35:57Z model_version_id=2021-05-05_dna_r9.4.1_promethion_384_dd219f32
GATC
+
@@@@
```

**Comment by jklymak** [comment]
Please work with the longread_plots maintainers to come up with a Matplotlib+numpy-only self-contained reproducible example.  We generally don't debug downstream libraries.

**Comment by ahcm** [comment]
I maintain longread_plots. It builds some plots, it tries to save them.
Saving fails with in matplotlib.
I rather spend my time rewriting in Rust.
Thanks.

**Comment by tacaswell** [comment]
Looks like an autoscale on a norm somehow got missed, from a quick glance, probably in your `pcolormesh`.    

Did this ever work? If so, in what version?

Can you please isolate this down to a Matplotlib only example to be sure that this is actually a bug in Matplotlib not a bug in your code.


-------


@ahcm Almost everyone who works on Matplotlib is a volunteer and we expect everyone (both project members and users) to follow our code of conduct (https://github.com/matplotlib/matplotlib/blob/main/CODE_OF_CONDUCT.md ).  

While I appreciate you may be frustrated, your response to a reasonable request for clarification to your issue was not productive and verging on inappropriate in a professional setting.

**Comment by ahcm** [comment]
Yes, this worked, for a long time. No idea when it broke. I fixed some nonposy to nonpositive, because someone thought that change is important enough as to break API.

Now for this one, I reported it but I'm not interested in spending time on it.

The data parsing is already rewritten in Rust and I rather spend time to rewrite the plotting part too.

Again. Thanks.

**Comment by ahcm** [comment]
I assume it was:
https://github.com/matplotlib/matplotlib/issues/24127
