### ISSUE TITLE
DLL load failed

### ISSUE THREAD

**Issue by ddale** [matplotlib/matplotlib#247]
[Original report at SourceForge, opened Thu Aug  7 16:32:25 2008](https://sourceforge.net/tracker/?func=detail&aid=2042138&group_id=80706&atid=560721)

Hey, I get this error:

```
Traceback (most recent call last):
  File "C:/Python25/scipytest.py", line 3, in <module>
    import pylab as p
  File "C:\Python25\pylab.py", line 1, in <module>
    from matplotlib.pylab import *
  File "C:\Python25\matplotlib\pylab.py", line 206, in <module>
    from matplotlib import mpl  # pulls in most modules
  File "C:\Python25\matplotlib\mpl.py", line 1, in <module>
    from matplotlib import artist
  File "C:\Python25\matplotlib\artist.py", line 4, in <module>
    from transforms import Bbox, IdentityTransform, TransformedBbox, TransformedPath
  File "C:\Python25\matplotlib\transforms.py", line 34, in <module>
    from matplotlib._path import affine_transform
ImportError: DLL load failed: The specified module could not be found.

```

when i run this program:

```
from matplotlib.mlab import normpdf
import matplotlib.numerix as nx
import pylab as p

x = nx.arange(-4, 4, 1, 0,01)
y = normpdf(x, 0 , 1)
p.plot(x, y, color = 'red', lw=2)
show()
```

thanks for the help

**Comment by Arnie97** [comment]
Hello, I'm encountering similar problems on Windows.
Latest `matplotlib` installed by `pip`.
```py
Python 3.4.2 (v3.4.2:ab2c023a9432, Oct  6 2014, 22:15:05) [MSC v.1600 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.

>>> import matplotlib
>>> matplotlib.__version__
'1.5.1'
>>> from matplotlib import _path
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: DLL load failed: The specified procedure could not be found.
```

Any ideas?

**Comment by WeatherGod** [comment]
Please open a new issue, as this issue has been closed for close to 4 years now.

**Comment by pelson** [comment]
> Please open a new issue, as this issue has been closed for close to 4 years now.

To be fair, in my closing comment, I stated that this issue could be re-opened with some more details. They certainly look the same issue.


@Arnie97 - could you provide any more details about your system. How have you installed, what is on your PATH etc. (http://matplotlib.org/faq/troubleshooting_faq.html#getting-help).
