### ISSUE TITLE
[Bug]: ImportError: DLL load failed while importing _path: The specified module could not be found.

### ISSUE THREAD

**Issue by irishismyname** [matplotlib/matplotlib#24704]
### Bug summary

`import`ing matplotlib on a fresh Windows machine or container fails with the following traceback:
```
>>> import matplotlib 
Traceback (most recent call last): 
  File "<stdin>", line 1, in <module>
  File "C:\Python\lib\site-packages\matplotlib\__init__.py", line 113, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File "C:\Python\lib\site-packages\matplotlib\rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "C:\Python\lib\site-packages\matplotlib\colors.py", line 56, in <module>
    from matplotlib import _api, _cm, cbook, scale
  File "C:\Python\lib\site-packages\matplotlib\scale.py", line 22, in <module>
    from matplotlib.ticker import (
  File "C:\Python\lib\site-packages\matplotlib\ticker.py", line 138, in <module>
    from matplotlib import transforms as mtransforms
  File "C:\Python\lib\site-packages\matplotlib\transforms.py", line 49, in <module>
    from matplotlib._path import (
ImportError: DLL load failed while importing _path: The specified module could not be found.
```

AFAIK, the DLL that's being called for isn't displayed here but I suspect this is something from the MSVC runtime.

### Code for reproduction

```python
docker run -it python:3.11.1-windowsservercore-1809 powershell
pip install matplotlib
python
import matplotlib
```

### Actual outcome

```
Traceback (most recent call last): 
  File "<stdin>", line 1, in <module>
  File "C:\Python\lib\site-packages\matplotlib\__init__.py", line 113, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File "C:\Python\lib\site-packages\matplotlib\rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "C:\Python\lib\site-packages\matplotlib\colors.py", line 56, in <module>
    from matplotlib import _api, _cm, cbook, scale
  File "C:\Python\lib\site-packages\matplotlib\scale.py", line 22, in <module>
    from matplotlib.ticker import (
  File "C:\Python\lib\site-packages\matplotlib\ticker.py", line 138, in <module>
    from matplotlib import transforms as mtransforms
  File "C:\Python\lib\site-packages\matplotlib\transforms.py", line 49, in <module>
    from matplotlib._path import (
ImportError: DLL load failed while importing _path: The specified module could not be found.
```

### Expected outcome

matplotlib imports without errors.

### Additional information

I _think_ the MSVC runtime is currently a dependency of matplotlib and the required DLL should be distributed with the wheel.

### Operating system

Windows 10

### Matplotlib Version

Import fails (3.6.2, 3.6.1, 3.6.0)

### Matplotlib Backend

Unknown, import fails

### Python version

3.11.1

### Jupyter version

N/A

### Installation

pip

**Comment by QuLogic** [comment]
Can you run Dependency Walker on the DLL to find out which MSVC runtime DLL is missing? We are only supposed to depend on the ones that Python already depends on.

**Comment by irishismyname** [comment]
I'm not sure which DLL to run Dependency walker on, but I watched `import matplotlib` using Process Monitor and here's what `python.exe` tried to access on my machine with the **MSVC runtime installed** (using a virtual environment):

Search Order | MSVC Installed | Path | Found? | 
| --- | --- | --- | --- |
| 1 | ✔ | `.\env\Lib\site-packages\matplotlib\MSVCP140.dll` | ❌ |
| 2 | ✔ | `%LocalAppData%\Programs\Python\Python311\MSVCP140.dll` | ❌ |
| 3 | ✔ | `.\env\Lib\site-packages\numpy\.libs\MSVCP140.dll` | ❌ |
| 4 | ✔ | `%System32%\msvcp140.dll` | ✔ |
| 5 | ✔ | `%LocalAppData%\Programs\Python\Python311\vcruntime140_1.dlll` | ✔ |

And again on a sandboxed machine **without MSVC** and no virtual environment:
Search Order | MSVC Installed | Path | Found? | 
| --- | --- | --- | --- |
| 1 | ❌ | `%ProgramFiles%\Python311\Lib\site-packages\matplotlib\MSVCP140.dll` | ❌ |
| 2 | ❌ | `%ProgramFiles%\Python311\MSVCP140.dll` | ❌ |
| 3 | ❌ | `%ProgramFiles%\Python311\Lib\site-packages\numpy\.libs\MSVCP140.dll` | ❌ |
| 4 | ❌ | `%System32%\MSVCP140.dll` | ❌ |

## Python 3.10 & matplotlib 3.5.3
I tried this again with Python 3.10 and matplotlib 3.5.3 and got the same dll search as above.

**Comment by QuLogic** [comment]
OK, I think that's the expected runtime. We explicitly pass flags to not require a new version (`VCRUNTIME140_1.dll`). Perhaps some dependency started using the new version and dropped the older one. Or perhaps Python 3.11 did instead?

Can you check if something is loading `VCRUNTIME140.dll` or `VCRUNTIME140_1.dll`?

**Comment by irishismyname** [comment]
I'm having a hard time figuring out exactly what is calling any of these DLLs, I need some clues on how to do that. I tried stepping through this with the IDLE debugger but that didn't provide much more insight than the traceback.

Let me qualify these next statements by saying: _I'm not a C/C++ programmer_.

AFAIK, you're entitled to `vcruntime140_1.dll` and `vcruntime140.dll` as they're distributed with Python. `MSVCP140.dll` becomes a dependency when you use functions/headers from the C++ Standard Library (STL).

For example, I _think_ including [stdint.h in ft2font.h](https://github.com/matplotlib/matplotlib/blob/666c7e3ea593eaede9894e3b0afb46e94e852618/src/ft2font.h) might cause the resulting binary to call for `MSVCP140.dll` unless there's something fancy going on with the build system.

**Comment by QuLogic** [comment]
Can you check if the wheels built on #24724 work? They are available in the artifacts [on this page](https://github.com/matplotlib/matplotlib/pull/24724/checks) (unfortunately, it doesn't appear that GitHub splits them apart by job, so you'll have to download a lot of unnecessary Linux/macOS wheels as well, sorry.) I have confirmed that they contain `msvcp140.dll`, but I do not know if they are in the correct location.

**Comment by irishismyname** [comment]
I ran
```
pip install ./matplotlib-3.7.0.dev973+g8e136b2c70-cp311-cp311-win_amd64.whl
python
import matplotlib
```
On a sandboxed machine **without MSVC** and no virtual environment:
Search Order | MSVC Installed | Path | Found? | 
| --- | --- | --- | --- |
| 1 | ❌ | `%ProgramFiles%\Python311\Lib\site-packages\matplotlib\MSVCP140.dll` | ❌ |
| 2 | ❌ | `%ProgramFiles%\Python311\MSVCP140.dll` | ❌ |
| 3 | ❌ | `%ProgramFiles%\Python311\Lib\site-packages\numpy\.libs\MSVCP140.dll` | ❌ |
| 4 | ❌ | `%ProgramFiles%\Python311\Lib\site-packages\matplotlib.libs\msvcp140.dll` | ✔ |
| 4 | ❌ | `%ProgramFiles%\Python311\vcruntime140_1.dll` | ✔ |

Seems to work!

**Comment by QuLogic** [comment]
Also, would just like to confirm that nothing bad happens if the MSVC runtime is already installed?

**Comment by irishismyname** [comment]
Tried the same as [above](https://github.com/matplotlib/matplotlib/issues/24704#issuecomment-1355550168) on a machine with the MSVC runtime installed, MSCVP140 search order/results were the same.

**Comment by RaffaelWalther** [comment]
Same issue here.

Traceback (most recent call last):
  File "C:/Users/raffa/Dropbox/Computer/Softwareentwicklung/Sourcecode/Python/ImageProcessing/RgbChannels.py", line 3, in <module>
    import matplotlib.pyplot as plt
  File "C:\Users\raffa\AppData\Local\Programs\Python\Python311\Lib\site-packages\matplotlib\__init__.py", line 113, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File "C:\Users\raffa\AppData\Local\Programs\Python\Python311\Lib\site-packages\matplotlib\rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "C:\Users\raffa\AppData\Local\Programs\Python\Python311\Lib\site-packages\matplotlib\colors.py", line 56, in <module>
    from matplotlib import _api, _cm, cbook, scale
  File "C:\Users\raffa\AppData\Local\Programs\Python\Python311\Lib\site-packages\matplotlib\scale.py", line 22, in <module>
    from matplotlib.ticker import (
  File "C:\Users\raffa\AppData\Local\Programs\Python\Python311\Lib\site-packages\matplotlib\ticker.py", line 138, in <module>
    from matplotlib import transforms as mtransforms
  File "C:\Users\raffa\AppData\Local\Programs\Python\Python311\Lib\site-packages\matplotlib\transforms.py", line 49, in <module>
    from matplotlib._path import (
ImportError: DLL load failed while importing _path: Das angegebene Modul wurde nicht gefunden.

Edition	Windows 10 Pro
Version	21H2
Installiert am	‎06.‎02.‎2021
Betriebssystembuild	19044.2364
Leistung	Windows Feature Experience Pack 120.2212.4190.0

**Comment by oscargus** [comment]
@RaffaelWalther this will be fixed in 3.7 and for now it should be enough to do
`pip install msvc-runtime`

**Comment by TharunParthiban** [comment]
Hello there!

While working with matplotlib library file I have encountered a new error which I cant understand!
It seems like the same issue. 
Here it is... 

"Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\matplotlib\__init__.py", line 246, in <module>
    _check_versions()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\matplotlib\__init__.py", line 240, in _check_versions
    module = importlib.import_module(modname)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\kiwisolver\__init__.py", line 8, in <module>
    from ._cext import (
ImportError: DLL load failed while importing _cext: The specified module could not be found."

If anyone knows how to fix it pls SHARE IT!

Thanks

**Comment by QuLogic** [comment]
You've already posted this as #25680, and an answer was given there.

**Comment by DeeeTeeee** [comment]
I am running a web app for gradio, but this error keeps coming;
  File "C:\Users\acer\AppData\Local\Programs\Python\Python311\Lib\site-packages\kiwisolver\__init__.py", line 8, in <module>    
    from ._cext import (
ImportError: DLL load failed while importing _cext: The specified module could not be found.

**Comment by irishismyname** [comment]
That's the same issue but with kiwisolver now 🙄. I haven't tested it recently, but we had the same problem.

**Comment by MousumiBehera** [comment]
ImportError: DLL load failed while importing _path: The specified module could not be found.
please resolve this error...i am unable to resolve this

**Comment by tacaswell** [comment]
@MousumiBehera That is likely due to issues with installation.  I suggest uninstalling and reinstalling Matplotlib using which ever method you used to install it.  If that does not work please post at https://discourse.matplotlib.org with the full tracback, where you got Python from, and how you nistalled Matplotlib.

**Comment by nithesh10** [comment]
pip install msvc-runtime fixed it

**Comment by tkoyama010** [comment]
The same error occurred in PyVista's CI (https://github.com/pyvista/pyvista/pull/6458). Adding the `--only-binary "matplotlib"` option to pip command solved the problem.
