### ISSUE TITLE
[Bug]: ImportError with Pillow 9.4.0 + matplotlib 3.6.2 on mac os x with Python 3.10.9

### ISSUE THREAD

**Issue by jfbu** [matplotlib/matplotlib#24871]
### Bug summary

I can not import matplotlib in my Python 3.10 virtual environment, due to a reported dynamic library loading problem on my mac os x.  After some longish quest I finally managed to realize that the problem did not arise with Pillow 9.3.0 but its triggered by Pillow 9.4.0.
Perhaps this is more a Pillow issue, but it is not triggered from doing only `import PIL`.

### Code for reproduction

```python
import PIL
import matplotlib
```

### Actual outcome

```
$ python
Python 3.10.9 (v3.10.9:1dd9be6584, Dec  6 2022, 14:37:36) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import PIL
>>> import matplotlib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/path/to/.venv310/lib/python3.10/site-packages/matplotlib/__init__.py", line 113, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File "/Users/path/to/.venv310/lib/python3.10/site-packages/matplotlib/rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "/Users/path/to/.venv310/lib/python3.10/site-packages/matplotlib/colors.py", line 51, in <module>
    from PIL import Image
  File "/Users/path/to/.venv310/lib/python3.10/site-packages/PIL/Image.py", line 103, in <module>
    from . import _imaging as core
ImportError: dlopen(/Users/path/to/.venv310/lib/python3.10/site-packages/PIL/_imaging.cpython-310-darwin.so, 2): Library not loaded: @loader_path/libXdmcp.6.dylib
  Referenced from: /Users/path/to/.venv310/lib/python3.10/site-packages/PIL/.dylibs/libxcb.1.1.0.dylib
  Reason: no suitable image found.  Did find:
	/Users/path/to/.venv310/lib/python3.10/site-packages/PIL/.dylibs/libXdmcp.6.dylib: cannot load 'libXdmcp.6.dylib' (load command 0x80000034 is unknown)
	/Users/path/to/.venv310/lib/python3.10/site-packages/PIL/.dylibs/libXdmcp.6.dylib: cannot load 'libXdmcp.6.dylib' (load command 0x80000034 is unknown)
>>> ^D
```

### Expected outcome

The above was with `Pillow 9.4.0`.  Here is after

```
$ pip install Pillow==9.3
Collecting Pillow==9.3
  Using cached Pillow-9.3.0-cp310-cp310-macosx_10_10_x86_64.whl (3.3 MB)
Installing collected packages: Pillow
  Attempting uninstall: Pillow
    Found existing installation: Pillow 9.4.0
    Uninstalling Pillow-9.4.0:
      Successfully uninstalled Pillow-9.4.0
Successfully installed Pillow-9.3.0
```

```
$ python
Python 3.10.9 (v3.10.9:1dd9be6584, Dec  6 2022, 14:37:36) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib
>>> print(matplotlib.__version__)
3.6.2
>>> import PIL
>>> print(PIL.__version__)
9.3.0
>>> ^D
```

### Operating system

mac osx high sierra

### Matplotlib Version

3.6.2

### Matplotlib Backend

MacOSX

### Python version

Python 3.10.9

### Jupyter version

```
Selected Jupyter core packages...
IPython          : 8.6.0
ipykernel        : 6.19.4
ipywidgets       : 8.0.4
jupyter_client   : 7.4.8
jupyter_core     : 5.1.2
jupyter_server   : not installed
jupyterlab       : not installed
nbclient         : 0.7.2
nbconvert        : 7.2.7
nbformat         : 5.7.1
notebook         : not installed
qtconsole        : not installed
traitlets        : 5.8.0
```

### Installation

pip

**Comment by jfbu** [comment]
It is most probably a Pillow packaging thing as I see it happened in the past with 9.1.0 (https://github.com/python-pillow/Pillow/issues/6217). Sorry for noise of reporting it here.

**Comment by radarhere** [comment]
Pillow has now uploaded new wheels, so this problem should be fixed.
