### ISSUE TITLE
[Bug]: Matplotlib doesn't work with Pillow 9.4.0

### ISSUE THREAD

**Issue by Djost43** [matplotlib/matplotlib#24883]
### Bug summary

Matplotlib doesn't work with Pillow 9.4.0

### Code for reproduction

```python
Installing matplotlib with pip in a new virtual environment

pip install matplotlib


Then trying to import it in a shell or in a file

>>> import matplotlib

Raise an ImportError
```

### Actual outcome

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/private/var/folders/nt/zk5g3pjx7_v7xt1s7_wbthjh0000gs/T/AppTranslocation/A6C9CE38-8079-48B4-9388-B4E419DA8C76/d/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/joris/PycharmProjects/pythonProject1/venv/lib/python3.10/site-packages/matplotlib/__init__.py", line 113, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File "/private/var/folders/nt/zk5g3pjx7_v7xt1s7_wbthjh0000gs/T/AppTranslocation/A6C9CE38-8079-48B4-9388-B4E419DA8C76/d/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/joris/PycharmProjects/pythonProject1/venv/lib/python3.10/site-packages/matplotlib/rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "/private/var/folders/nt/zk5g3pjx7_v7xt1s7_wbthjh0000gs/T/AppTranslocation/A6C9CE38-8079-48B4-9388-B4E419DA8C76/d/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/joris/PycharmProjects/pythonProject1/venv/lib/python3.10/site-packages/matplotlib/colors.py", line 51, in <module>
    from PIL import Image
  File "/private/var/folders/nt/zk5g3pjx7_v7xt1s7_wbthjh0000gs/T/AppTranslocation/A6C9CE38-8079-48B4-9388-B4E419DA8C76/d/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/joris/PycharmProjects/pythonProject1/venv/lib/python3.10/site-packages/PIL/Image.py", line 103, in <module>
    from . import _imaging as core
  File "/private/var/folders/nt/zk5g3pjx7_v7xt1s7_wbthjh0000gs/T/AppTranslocation/A6C9CE38-8079-48B4-9388-B4E419DA8C76/d/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ImportError: dlopen(/Users/joris/PycharmProjects/pythonProject1/venv/lib/python3.10/site-packages/PIL/_imaging.cpython-310-darwin.so, 2): Library not loaded: @loader_path/libXdmcp.6.dylib
  Referenced from: /Users/joris/PycharmProjects/pythonProject1/venv/lib/python3.10/site-packages/PIL/.dylibs/libxcb.1.1.0.dylib
  Reason: no suitable image found.  Did find:
	/Users/joris/PycharmProjects/pythonProject1/venv/lib/python3.10/site-packages/PIL/.dylibs/libXdmcp.6.dylib: cannot load 'libXdmcp.6.dylib' (load command 0x80000034 is unknown)
	/Users/joris/PycharmProjects/pythonProject1/venv/lib/python3.10/site-packages/PIL/.dylibs/libXdmcp.6.dylib: cannot load 'libXdmcp.6.dylib' (load command 0x80000034 is unknown)

### Expected outcome

No error when importing matplotlib

### Additional information

The same procedure where I force the version of Pillow as 9.3.0 works without rasing any error 

### Operating system

MacOS 10.14

### Matplotlib Version

3.6.2

### Python version

3.10

### Installation

pip

**Comment by oscargus** [comment]
I cannot seem to reproduce it (on Windows). It seems like you use PyCharm? What happens if you create a virtual environment from the shell?

**Comment by Djost43** [comment]
I use PyCharm Community Edition.
I try to create the virtual environment from shell and I get the same error when importing matplotlib

**Comment by ksunden** [comment]
What happens if you directly import pillow? It seems unlikely that matplotlib is doing anything to the PIL specific dlls that are indicated in the error message. If it produces the same error without importing mpl then this is a Pillow problem and not a matplotlib one.

**Comment by tacaswell** [comment]
xref: https://github.com/matplotlib/matplotlib/issues/24871

@Djost43 Please test

```
from PIL import Image
```


which I expect to fail and indicates that this is likely a packaging problem with Pillow.  There is nothing that we can do on the Matplotlib side to help with this so I am going to close this.  If I am incorrect, please ping to have this re-opened!

**Comment by Djost43** [comment]
This import fail as well
Yes I down-grade pillow since I see it work with 9.3.0
Thank you for the time you took to look through this report

**Comment by wiredfool** [comment]
This looks to be the same issue as here: https://github.com/python-pillow/Pillow/issues/3068#issuecomment-1368856679

Essentially, Homebrew libraries no longer support < 10.15, and that's what's shipping with pillow.

**Comment by radarhere** [comment]
Pillow has now uploaded new wheels, so this problem should be fixed.
