### ISSUE TITLE
[Bug]: LogitLocator runs into OverflowError on line 2815 after nonsingular() is called.

### ISSUE THREAD

**Issue by Gerald-Meyers** [matplotlib/matplotlib#25577]
### Bug summary

Nonsingular passes into the final else block with (vmin, vmax) = (0.35481338923357547, 2818382931.264449). After the test for vmax>1, vmax is set to 0.0. This appears to be due to the block of code

`
minpos = (  self.axis.get_minpos()
                     if self.axis is not None
                     else standard_minpos )
`

which sets minpos to 1. This explains why vmax is 0 (1-1=0... duh).

A simple workaround is to use a range for the axes that does not begin at 1, e.g. range(-1,10).

This prints as output figure:
![image](https://user-images.githubusercontent.com/5313641/228746224-a2daf02a-71e0-4e31-8248-6dabff0110fd.png)

### Code for reproduction

```python
import matplotlib.pyplot as plt
from matplotlib.ticker import LogFormatter, LogLocator, MaxNLocator, NullFormatter, LogitLocator
from numpy import geomspace, linspace

# generate some data
x = [10**i for i in range(10)]
y = [10**i for i in range(10)]

# create a figure and axis object
fig, ax = plt.subplots()

# set the x-axis to log scale
ax.set_xscale('log')

# plot the data
ax.plot(x, y)


# locmin = LogLocator(subs=linspace(.1,1,5), numticks=999)
locmin = LogitLocator(minor=True, nbins=999)
# locmaj = LogLocator(subs=(1,), numticks=5)
ax.xaxis.set_minor_locator(locmin)
# ax.yaxis.set_minor_locator(locmin)
# ax.xaxis.set_major_locator(locmaj)
# ax.yaxis.set_major_locator(locmaj)
ax.xaxis.set_minor_formatter(NullFormatter())
# ax.xaxis.set_major_formatter(NullFormatter())

# add labels and a title
ax.set_xlabel('x')
ax.set_ylabel('y')

plt.show()
```

### Actual outcome
Note: minor line # changes because of added print statements for testing.

Traceback (most recent call last):
  File "C:\Python\lib\site-packages\IPython\core\interactiveshell.py", line 3442, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-b1e4c65612de>", line 32, in <module>
    plt.show()
  File "C:\Python\lib\site-packages\matplotlib\pyplot.py", line 421, in show
    return _get_backend_mod().show(*args, **kwargs)
  File "C:\Program Files\JetBrains\PyCharm 2022.3\plugins\python\helpers\pycharm_matplotlib_backend\backend_interagg.py", line 29, in __call__
    manager.show(**kwargs)
  File "C:\Program Files\JetBrains\PyCharm 2022.3\plugins\python\helpers\pycharm_matplotlib_backend\backend_interagg.py", line 112, in show
    self.canvas.show()
  File "C:\Program Files\JetBrains\PyCharm 2022.3\plugins\python\helpers\pycharm_matplotlib_backend\backend_interagg.py", line 68, in show
    FigureCanvasAgg.draw(self)
  File "C:\Python\lib\site-packages\matplotlib\backends\backend_agg.py", line 405, in draw
    self.figure.draw(self.renderer)
  File "C:\Python\lib\site-packages\matplotlib\artist.py", line 74, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "C:\Python\lib\site-packages\matplotlib\artist.py", line 51, in draw_wrapper
    return draw(artist, renderer)
  File "C:\Python\lib\site-packages\matplotlib\figure.py", line 3082, in draw
    mimage._draw_list_compositing_images(
  File "C:\Python\lib\site-packages\matplotlib\image.py", line 131, in _draw_list_compositing_images
    a.draw(renderer)
  File "C:\Python\lib\site-packages\matplotlib\artist.py", line 51, in draw_wrapper
    return draw(artist, renderer)
  File "C:\Python\lib\site-packages\matplotlib\axes\_base.py", line 3100, in draw
    mimage._draw_list_compositing_images(
  File "C:\Python\lib\site-packages\matplotlib\image.py", line 131, in _draw_list_compositing_images
    a.draw(renderer)
  File "C:\Python\lib\site-packages\matplotlib\artist.py", line 51, in draw_wrapper
    return draw(artist, renderer)
  File "C:\Python\lib\site-packages\matplotlib\axis.py", line 1304, in draw
    ticks_to_draw = self._update_ticks()
  File "C:\Python\lib\site-packages\matplotlib\axis.py", line 1198, in _update_ticks
    minor_locs = self.get_minorticklocs()
  File "C:\Python\lib\site-packages\matplotlib\axis.py", line 1421, in get_minorticklocs
    minor_locs = np.asarray(self.minor.locator())
  File "C:\Python\lib\site-packages\matplotlib\ticker.py", line 2143, in __call__
    return self.tick_values(vmin, vmax)
  File "C:\Python\lib\site-packages\matplotlib\ticker.py", line 2816, in tick_values
    bsup = int(
OverflowError: cannot convert float infinity to integer

### Expected outcome

The plot should have been generated with log scale minor ticks.

### Operating system

win10

### Matplotlib Version

3.6.3

### Matplotlib Backend

module://backend_interagg

### Python version

3.10.9

### Installation

pip

**Comment by ksunden** [comment]
I will state that the `LogitLocator` is primarily intended for use with the `LogitScale` (`set_xscale("logit")`) rather than the `LogScale` (`set_xscale("log")`)

Despite the similar name and the fact that a log is to compute it, Logit is a different scale that is intended only for the domain of 0-1. This is why the ticks only appear below 10^0.

More info:

- https://en.wikipedia.org/wiki/Logit
- https://matplotlib.org/stable/gallery/scales/scales.html
- https://matplotlib.org/stable/gallery/scales/logit_demo.html

I'm not too surprised there are incompatibilities with scales and locators not optimized for each other, nor really sure there is any action to take.

**Comment by Gerald-Meyers** [comment]
My mistake then.
