### ISSUE TITLE
Unable to plot some data

### ISSUE THREAD

**Issue by PhantomLel** [matplotlib/matplotlib#25703]
### Bug summary

Im getting an error saying `TypeError: int() argument must be a string, a bytes-like object or a real number, not 'KeyboardModifier` when I try to do anything

### Code for reproduction

```python
import matplotlib.pyplot as plt

plt.show()
```

### Actual outcome

Traceback (most recent call last):
  File "/home/abdullah/workspace/natural-selection-simulation/variations/low_diversity_quick_mut/main.py", line 128, in <module>
    produce_graph(data)
  File "/home/abdullah/workspace/natural-selection-simulation/variations/low_diversity_quick_mut/extras.py", line 23, in produce_graph
    plt.plot(data['frames'], val, label=category)
  File "/home/abdullah/.local/lib/python3.10/site-packages/matplotlib/pyplot.py", line 2767, in plot
    return gca().plot(
  File "/home/abdullah/.local/lib/python3.10/site-packages/matplotlib/pyplot.py", line 2272, in gca
    return gcf().gca(**kwargs)
  File "/home/abdullah/.local/lib/python3.10/site-packages/matplotlib/pyplot.py", line 865, in gcf
    return figure()
  File "/home/abdullah/.local/lib/python3.10/site-packages/matplotlib/pyplot.py", line 806, in figure
    manager = new_figure_manager(
  File "/home/abdullah/.local/lib/python3.10/site-packages/matplotlib/pyplot.py", line 324, in new_figure_manager
    _warn_if_gui_out_of_main_thread()
  File "/home/abdullah/.local/lib/python3.10/site-packages/matplotlib/pyplot.py", line 314, in _warn_if_gui_out_of_main_thread
    if (_get_required_interactive_framework(_get_backend_mod())
  File "/home/abdullah/.local/lib/python3.10/site-packages/matplotlib/pyplot.py", line 217, in _get_backend_mod
    switch_backend(dict.__getitem__(rcParams, "backend"))
  File "/home/abdullah/.local/lib/python3.10/site-packages/matplotlib/pyplot.py", line 262, in switch_backend
    switch_backend(candidate)
  File "/home/abdullah/.local/lib/python3.10/site-packages/matplotlib/pyplot.py", line 282, in switch_backend
    class backend_mod(matplotlib.backend_bases._Backend):
  File "/home/abdullah/.local/lib/python3.10/site-packages/matplotlib/pyplot.py", line 283, in backend_mod
    locals().update(vars(importlib.import_module(backend_name)))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/abdullah/.local/lib/python3.10/site-packages/matplotlib/backends/backend_qtagg.py", line 12, in <module>
    from .backend_qt import (
  File "/home/abdullah/.local/lib/python3.10/site-packages/matplotlib/backends/backend_qt.py", line 73, in <module>
    _MODIFIER_KEYS = [
  File "/home/abdullah/.local/lib/python3.10/site-packages/matplotlib/backends/backend_qt.py", line 74, in <listcomp>
    (_to_int(getattr(_enum("QtCore.Qt.KeyboardModifier"), mod)),
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'KeyboardModifier'

### Expected outcome

I expect the plot to show up with all my data. 

### Additional information

This did work in an earlier version in around June 2021. I just opened it up recently and it no longer works despite me not changing anything. Strangely, when I run the backend command, I get the exact same error. It seems like I can't do anything 

### Operating system

Manjaro

### Matplotlib Version

3.5.3

### Matplotlib Backend

I can't run this, I get the same error

### Python version

3.10.10

### Installation

pip

**Comment by jklymak** [comment]
You likely have an installation problem.  Rebuild your environment and please bring any further issues to https://discourse.matplotlib.org.  Thanks....
