### ISSUE TITLE
[Doc]: running matplotlib with readonly fs

### ISSUE THREAD

**Issue by brsolomon-deloitte** [matplotlib/matplotlib#25838]
### Problem

It is not documented how to properly run matplotlib on a readonly filesystem.

```
$ docker container run -it --entrypoint=bash --rm --read-only -p 8081:8081 my-app:0.1
python@fc73f94c8f64:/app$ python3
Python 3.10.11 (main, May  4 2023, 06:08:16) [GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/matplotlib/__init__.py", line 961, in <module>
    dict.update(rcParams, _rc_params_in_file(matplotlib_fname()))
  File "/usr/local/lib/python3.10/site-packages/matplotlib/__init__.py", line 609, in matplotlib_fname
    for fname in gen_candidates():
  File "/usr/local/lib/python3.10/site-packages/matplotlib/__init__.py", line 606, in gen_candidates
    yield os.path.join(get_configdir(), 'matplotlibrc')
  File "/usr/local/lib/python3.10/site-packages/matplotlib/__init__.py", line 305, in wrapper
    ret = func(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/matplotlib/__init__.py", line 552, in get_configdir
    return _get_config_or_cache_dir(_get_xdg_config_dir)
  File "/usr/local/lib/python3.10/site-packages/matplotlib/__init__.py", line 524, in _get_config_or_cache_dir
    tempfile.mkdtemp(prefix="matplotlib-")
  File "/usr/local/lib/python3.10/tempfile.py", line 357, in mkdtemp
    prefix, suffix, dir, output_type = _sanitize_params(prefix, suffix, dir)
  File "/usr/local/lib/python3.10/tempfile.py", line 126, in _sanitize_params
    dir = gettempdir()
  File "/usr/local/lib/python3.10/tempfile.py", line 299, in gettempdir
    return _os.fsdecode(_gettempdir())
  File "/usr/local/lib/python3.10/tempfile.py", line 292, in _gettempdir
    tempdir = _get_default_tempdir()
  File "/usr/local/lib/python3.10/tempfile.py", line 223, in _get_default_tempdir
    raise FileNotFoundError(_errno.ENOENT,
FileNotFoundError: [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/app']
```

This can be reproduced with a Dockerfile using `python:3.10.11-bullseye` as the base image, which simply installs `matplotlib`.

**Comment by tacaswell** [comment]
I do not think we support running on a fully read-only file, I agree with PR #25840 being a good immediate path forward.

I am not sure off the top of my head if it would be possible to run on a fully read-only fs.  We could in principle skip the font cache (which means start up is always slow) and I think that all of latex integration would be broken.

I assume the application here is a webserver that is writing images to `BytesIO` and serving them directly without saving the files to disk?  If this is important to Deloitte I am confident we would consider a PR adding a "no writing mode" to mpl.

**Comment by ksunden** [comment]
Perhaps 

```
docker container run -it --entrypoint=bash --rm --read-only --tmpfs /tmp -p 8081:8081 my-app:0.1
```

May work (adding a tmpfs for /tmp which gives a location to write to from the perspective of python/tempfile but tmpfs exists only in memory so not writing to disk)

**Comment by brsolomon-deloitte** [comment]
Thanks @ksunden , I had forgotten about `--tmpfs` :) That works for us, at least. (I also set `ENV MPLCONFIGDIR="/tmp/matplotlib"` to be explicit.)
