### ISSUE TITLE
[Bug]: matplotlib crashes if _tkinter doesn't have __file__

### ISSUE THREAD

**Issue by hrektts** [matplotlib/matplotlib#25944]
### Bug summary

I got an error similar to #23074.

### Code for reproduction

```bash
wget https://github.com/indygreg/python-build-standalone/releases/download/20230116/cpython-3.11.1%2B20230116-x86_64-unknown-linux-gnu-pgo-full.tar.zst
tar xf cpython-3.11.1+20230116-x86_64-unknown-linux-gnu-pgo-full.tar.zst
python/install/bin/python3 -m venv venv
venv/bin/pip install matplotlib
venv/bin/python -c "import matplotlib; matplotlib.use('TkAgg'); import matplotlib.pyplot as plt; plt.plot(list(range(10)), list(range(10)))"
```

### Actual outcome

```bash
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/developer/venv/lib/python3.11/site-packages/matplotlib/pyplot.py", line 2812, in plot
    return gca().plot(
           ^^^^^
  File "/home/developer/venv/lib/python3.11/site-packages/matplotlib/pyplot.py", line 2309, in gca
    return gcf().gca()
           ^^^^^
  File "/home/developer/venv/lib/python3.11/site-packages/matplotlib/pyplot.py", line 906, in gcf
    return figure()
           ^^^^^^^^
  File "/home/developer/venv/lib/python3.11/site-packages/matplotlib/_api/deprecation.py", line 454, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/developer/venv/lib/python3.11/site-packages/matplotlib/pyplot.py", line 840, in figure
    manager = new_figure_manager(
              ^^^^^^^^^^^^^^^^^^^
  File "/home/developer/venv/lib/python3.11/site-packages/matplotlib/pyplot.py", line 383, in new_figure_manager
    _warn_if_gui_out_of_main_thread()
  File "/home/developer/venv/lib/python3.11/site-packages/matplotlib/pyplot.py", line 361, in _warn_if_gui_out_of_main_thread
    if _get_required_interactive_framework(_get_backend_mod()):
                                           ^^^^^^^^^^^^^^^^^^
  File "/home/developer/venv/lib/python3.11/site-packages/matplotlib/pyplot.py", line 208, in _get_backend_mod
    switch_backend(rcParams._get("backend"))
  File "/home/developer/venv/lib/python3.11/site-packages/matplotlib/pyplot.py", line 271, in switch_backend
    backend_mod = importlib.import_module(
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/developer/python/install/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/developer/venv/lib/python3.11/site-packages/matplotlib/backends/backend_tkagg.py", line 1, in <module>
    from . import _backend_tk
  File "/home/developer/venv/lib/python3.11/site-packages/matplotlib/backends/_backend_tk.py", line 24, in <module>
    from . import _tkagg
ImportError: module '_tkinter' has no attribute '__file__'
```

### Expected outcome

The plot is displayed.

### Operating system

ubuntu 22.04

### Matplotlib Version

3.7.1

### Python version

cpython-3.11.1+20230116-x86_64-unknown-linux-gnu-pgo-full (from [python-build-standalone](https://github.com/indygreg/python-build-standalone))

### Installation

pip

**Comment by oscargus** [comment]
Does `import tkinter` work for you in a normal Python shell? `import _tkinter`?

**Comment by anntzer** [comment]
See https://github.com/matplotlib/matplotlib/issues/23074#issuecomment-1132368413 and https://github.com/matplotlib/matplotlib/issues/23074#issuecomment-1134052145: python-build-standalone is not compatible with tkagg.

 > If you want to support mpl + tkagg @indygreg I think this is something you should handle on your side. As I said above, we will definitely consider reasonable patches if needed.
