### ISSUE TITLE
Some build issue with `oldest-supported-numpy`

### ISSUE THREAD

**Issue by chenrui333** [matplotlib/matplotlib#26246]
Trying to build matplotlib from source, but ran into some build failure with `oldest-supported-numpy` (as it does not support python@3.11, any reason why that is there??)

Related error log

<details>
<summary>error build log</summary>

```
  Collecting numpy==1.23.2
    Downloading numpy-1.23.2.tar.gz (10.7 MB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.7/10.7 MB 60.2 MB/s eta 0:00:00
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'error'
    error: subprocess-exited-with-error

    × Getting requirements to build wheel did not run successfully.
    │ exit code: 1
    ╰─> [95 lines of output]
        <string>:71: RuntimeWarning: NumPy 1.23.2 may not yet support Python 3.11.
        Running from numpy source directory.
        <string>:86: DeprecationWarning:

          `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
          of the deprecation of `distutils` itself. It will be removed for
          Python >= 3.12. For older Python versions it will remain present.
          It is recommended to use `setuptools < 60.0` for those Python versions.
          For more details, see:
            https://numpy.org/devdocs/reference/distutils_status_migration.html


        running egg_info
        running build_src
        INFO: build_src
        creating numpy.egg-info
        writing numpy.egg-info/PKG-INFO
        writing dependency_links to numpy.egg-info/dependency_links.txt
        writing entry points to numpy.egg-info/entry_points.txt
        writing top-level names to numpy.egg-info/top_level.txt
        writing manifest file 'numpy.egg-info/SOURCES.txt'
        /opt/homebrew/Cellar/sip/6.7.9/libexec/lib/python3.11/site-packages/setuptools/command/egg_info.py:661: SetuptoolsDeprecationWarning: Custom 'build_py' does not implement 'get_data_files_without_manifest'.
        Please extend command classes from setuptools instead of distutils.
          warnings.warn(
        INFO: unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
        Traceback (most recent call last):
          File "/opt/homebrew/Cellar/python-matplotlib/3.7.1/libexec/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
            main()
          File "/opt/homebrew/Cellar/python-matplotlib/3.7.1/libexec/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
            json_out['return_val'] = hook(**hook_input['kwargs'])
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "/opt/homebrew/Cellar/python-matplotlib/3.7.1/libexec/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
            return hook(config_settings)
                   ^^^^^^^^^^^^^^^^^^^^^
          File "/opt/homebrew/Cellar/sip/6.7.9/libexec/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
            return self._get_build_requires(config_settings, requirements=['wheel'])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "/opt/homebrew/Cellar/sip/6.7.9/libexec/lib/python3.11/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
            self.run_setup()
          File "/opt/homebrew/Cellar/sip/6.7.9/libexec/lib/python3.11/site-packages/setuptools/build_meta.py", line 485, in run_setup
            self).run_setup(setup_script=setup_script)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "/opt/homebrew/Cellar/sip/6.7.9/libexec/lib/python3.11/site-packages/setuptools/build_meta.py", line 335, in run_setup
            exec(code, locals())
          File "<string>", line 493, in <module>
          File "<string>", line 485, in setup_package
          File "/opt/homebrew/Cellar/sip/6.7.9/libexec/lib/python3.11/site-packages/setuptools/__init__.py", line 108, in setup
            return distutils.core.setup(**attrs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "/opt/homebrew/Cellar/sip/6.7.9/libexec/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
            return run_commands(dist)
                   ^^^^^^^^^^^^^^^^^^
          File "/opt/homebrew/Cellar/sip/6.7.9/libexec/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
            dist.run_commands()
          File "/opt/homebrew/Cellar/sip/6.7.9/libexec/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
            self.run_command(cmd)
          File "/opt/homebrew/Cellar/sip/6.7.9/libexec/lib/python3.11/site-packages/setuptools/dist.py", line 1221, in run_command
            super().run_command(command)
          File "/opt/homebrew/Cellar/sip/6.7.9/libexec/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
            cmd_obj.run()
          File "/private/tmp/pip-install-80b9o9df/numpy_02ce4ac571d84f178ec1bc964ebf850a/numpy/distutils/command/egg_info.py", line 25, in run
            _egg_info.run(self)
          File "/opt/homebrew/Cellar/sip/6.7.9/libexec/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 318, in run
            self.find_sources()
          File "/opt/homebrew/Cellar/sip/6.7.9/libexec/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 326, in find_sources
            mm.run()
          File "/opt/homebrew/Cellar/sip/6.7.9/libexec/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 570, in run
            self.add_defaults()
          File "/opt/homebrew/Cellar/sip/6.7.9/libexec/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 608, in add_defaults
            sdist.add_defaults(self)
          File "/opt/homebrew/Cellar/sip/6.7.9/libexec/lib/python3.11/site-packages/setuptools/command/sdist.py", line 107, in add_defaults
            self._add_defaults_build_sub_commands()
          File "/opt/homebrew/Cellar/sip/6.7.9/libexec/lib/python3.11/site-packages/setuptools/command/sdist.py", line 127, in _add_defaults_build_sub_commands
            self.filelist.extend(chain.from_iterable(files))
          File "/opt/homebrew/Cellar/sip/6.7.9/libexec/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 513, in extend
            self.files.extend(filter(self._safe_path, paths))
          File "/opt/homebrew/Cellar/sip/6.7.9/libexec/lib/python3.11/site-packages/setuptools/command/sdist.py", line 126, in <genexpr>
            files = (c.get_source_files() for c in cmds if hasattr(c, "get_source_files"))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "/opt/homebrew/Cellar/sip/6.7.9/libexec/lib/python3.11/site-packages/setuptools/command/sdist.py", line 125, in <genexpr>
            cmds = (self.get_finalized_command(c) for c in missing_cmds)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "/opt/homebrew/Cellar/sip/6.7.9/libexec/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 305, in get_finalized_command
            cmd_obj.ensure_finalized()
          File "/opt/homebrew/Cellar/sip/6.7.9/libexec/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
            self.finalize_options()
          File "/private/tmp/pip-install-80b9o9df/numpy_02ce4ac571d84f178ec1bc964ebf850a/numpy/distutils/command/config_compiler.py", line 69, in finalize_options
            v = getattr(c, a)
                ^^^^^^^^^^^^^
          File "/private/tmp/pip-build-env-ea8ygs0c/overlay/lib/python3.11/site-packages/Cython/Distutils/old_build_ext.py", line 157, in __getattr__
            return _build_ext.build_ext.__getattr__(self, name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "/opt/homebrew/Cellar/sip/6.7.9/libexec/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
            raise AttributeError(attr)
        AttributeError: fcompiler. Did you mean: 'compiler'?
        [end of output]

    note: This error originates from a subprocess, and is likely not a problem with pip.
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.

  [notice] A new release of pip is available: 23.0.1 -> 23.1.2
  [notice] To update, run: python3.11 -m pip install --upgrade pip
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /opt/homebrew/Cellar/python-matplotlib/3.7.1/libexec/bin/python3.11 /opt/homebrew/Cellar/python-matplotlib/3.7.1/libexec/lib/python3.11/site-packages/pip/__pip-runner__.py install --ignore-installed --no-user --prefix /private/tmp/pip-build-env-9jtv2700/overlay --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple -- 'certifi>=2020.06.20' oldest-supported-numpy 'pybind11>=2.6' 'setuptools_scm>=7'
  cwd: [inherit]
  Installing build dependencies: finished with status 'error'
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.
```

</details>

also relates to https://github.com/Homebrew/homebrew-core/pull/135355

**Comment by QuLogic** [comment]
If NumPy is failing to build, then this should be reported to NumPy.
