### ISSUE TITLE
[Bug]: mathtext caching issue in multi-threaded environment with tight_layout=True

### ISSUE THREAD

**Issue by karpov-sv** [matplotlib/matplotlib#26289]
### Bug summary

Encountered the issue when plotting images with mathematical notation and `tight_layout=True` in Django - it occasionally crashes with the traceback suggesting some text metric cache corruption.  

The minimal working example below does not crash anymore if I remove the mathematical notation (`$\pm$` in the example), or use `tight_layout=False`

### Code for reproduction

```python
from matplotlib.figure import Figure

import io
import threading

def test_crash2():
    for i in range(100):

        fig = Figure(tight_layout=True)
        # fig = Figure()

        ax = fig.add_subplot(1, 1, 1)

        ax.text(0, 0, 'test $\pm$ 1.2') # This crashes
        # ax.text(0, 0, 'test 1.2') # This does not

        buf = io.BytesIO()
        fig.savefig(buf, format='png')

if __name__ == '__main__':

    for i in range(10):
        x = threading.Thread(target=test_crash2)
        x.start()
```

### Actual outcome

It produces the following traceback, essentially identical to what I saw in Django:
```
Traceback (most recent call last):
  File "/Users/karpov/miniconda3/envs/stdweb/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Users/karpov/miniconda3/envs/stdweb/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/karpov/sciwork/stdweb/stdweb/test_crash.py", line 21, in test_crash2
    fig.savefig(buf, format='png')
  File "/Users/karpov/miniconda3/envs/stdweb/lib/python3.10/site-packages/matplotlib/figure.py", line 3343, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/Users/karpov/miniconda3/envs/stdweb/lib/python3.10/site-packages/matplotlib/backend_bases.py", line 2342, in print_figure
    self.figure.draw(renderer)
  File "/Users/karpov/miniconda3/envs/stdweb/lib/python3.10/site-packages/matplotlib/artist.py", line 95, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/Users/karpov/miniconda3/envs/stdweb/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/Users/karpov/miniconda3/envs/stdweb/lib/python3.10/site-packages/matplotlib/figure.py", line 3134, in draw
    self.get_layout_engine().execute(self)
  File "/Users/karpov/miniconda3/envs/stdweb/lib/python3.10/site-packages/matplotlib/layout_engine.py", line 178, in execute
    kwargs = get_tight_layout_figure(
  File "/Users/karpov/miniconda3/envs/stdweb/lib/python3.10/site-packages/matplotlib/_tight_layout.py", line 266, in get_tight_layout_figure
    kwargs = _auto_adjust_subplotpars(fig, renderer,
  File "/Users/karpov/miniconda3/envs/stdweb/lib/python3.10/site-packages/matplotlib/_tight_layout.py", line 82, in _auto_adjust_subplotpars
    bb += [martist._get_tightbbox_for_layout_only(ax, renderer)]
  File "/Users/karpov/miniconda3/envs/stdweb/lib/python3.10/site-packages/matplotlib/artist.py", line 1417, in _get_tightbbox_for_layout_only
    return obj.get_tightbbox(*args, **kwargs)
  File "/Users/karpov/miniconda3/envs/stdweb/lib/python3.10/site-packages/matplotlib/axes/_base.py", line 4408, in get_tightbbox
    bbox = a.get_tightbbox(renderer)
  File "/Users/karpov/miniconda3/envs/stdweb/lib/python3.10/site-packages/matplotlib/artist.py", line 367, in get_tightbbox
    bbox = self.get_window_extent(renderer)
  File "/Users/karpov/miniconda3/envs/stdweb/lib/python3.10/site-packages/matplotlib/text.py", line 959, in get_window_extent
    bbox, info, descent = self._get_layout(self._renderer)
  File "/Users/karpov/miniconda3/envs/stdweb/lib/python3.10/site-packages/matplotlib/text.py", line 386, in _get_layout
    w, h, d = _get_text_metrics_with_cache(
  File "/Users/karpov/miniconda3/envs/stdweb/lib/python3.10/site-packages/matplotlib/text.py", line 97, in _get_text_metrics_with_cache
    return _get_text_metrics_with_cache_impl(
  File "/Users/karpov/miniconda3/envs/stdweb/lib/python3.10/site-packages/matplotlib/text.py", line 105, in _get_text_metrics_with_cache_impl
    return renderer_ref().get_text_width_height_descent(text, fontprop, ismath)
  File "/Users/karpov/miniconda3/envs/stdweb/lib/python3.10/site-packages/matplotlib/backends/backend_agg.py", line 230, in get_text_width_height_descent
    self.mathtext_parser.parse(s, self.dpi, prop)
  File "/Users/karpov/miniconda3/envs/stdweb/lib/python3.10/site-packages/matplotlib/mathtext.py", line 226, in parse
    return self._parse_cached(s, dpi, prop)
  File "/Users/karpov/miniconda3/envs/stdweb/lib/python3.10/site-packages/matplotlib/mathtext.py", line 247, in _parse_cached
    box = self._parser.parse(s, fontset, fontsize, dpi)
  File "/Users/karpov/miniconda3/envs/stdweb/lib/python3.10/site-packages/matplotlib/_mathtext.py", line 1992, in parse
    result = self._expression.parseString(s)
  File "/Users/karpov/miniconda3/envs/stdweb/lib/python3.10/site-packages/pyparsing/core.py", line 1131, in parse_string
    loc, tokens = self._parse(instring, 0)
  File "/Users/karpov/miniconda3/envs/stdweb/lib/python3.10/site-packages/pyparsing/core.py", line 921, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/Users/karpov/miniconda3/envs/stdweb/lib/python3.10/site-packages/pyparsing/core.py", line 817, in _parseNoCache
    loc, tokens = self.parseImpl(instring, pre_loc, doActions)
  File "/Users/karpov/miniconda3/envs/stdweb/lib/python3.10/site-packages/pyparsing/core.py", line 3864, in parseImpl
    loc, resultlist = self.exprs[0]._parse(
  File "/Users/karpov/miniconda3/envs/stdweb/lib/python3.10/site-packages/pyparsing/core.py", line 921, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/Users/karpov/miniconda3/envs/stdweb/lib/python3.10/site-packages/pyparsing/core.py", line 856, in _parseNoCache
    tokens = fn(instring, tokens_start, ret_tokens)
  File "/Users/karpov/miniconda3/envs/stdweb/lib/python3.10/site-packages/pyparsing/core.py", line 291, in wrapper
    ret = func(*args[limit:])
  File "/Users/karpov/miniconda3/envs/stdweb/lib/python3.10/site-packages/matplotlib/_mathtext.py", line 2028, in non_math
    symbols = [Char(c, self.get_state()) for c in s]
  File "/Users/karpov/miniconda3/envs/stdweb/lib/python3.10/site-packages/matplotlib/_mathtext.py", line 2028, in <listcomp>
    symbols = [Char(c, self.get_state()) for c in s]
  File "/Users/karpov/miniconda3/envs/stdweb/lib/python3.10/site-packages/matplotlib/_mathtext.py", line 2005, in get_state
    return self._state_stack[-1]
TypeError: 'NoneType' object is not subscriptable
```

### Expected outcome

No failures

### Operating system

Tested on OS/X and on latest Ubuntu

### Matplotlib Version

3.7.1 and 3.6.3

### Python version

3.10.11 and 3.11.2

### Installation

None

**Comment by ksunden** [comment]
This doesn't really have anything to do with the caching, but rather that mathtext parsing (and matplotlib more generally) is [_not_ threadsafe](https://matplotlib.org/stable/users/faq/howto_faq.html#work-with-threads). The (inner/private) mathtext parser is a singleton, and so it is multiple threads writing to a single state variable where they are all parsing simultaneously.

It's not clear to me what we _can_ reasonably do here, at least without a fair bit of overhead (and maintenance) of e.g. adding locks to the parsing code... (which is something we _explicitly_ do _not_ do for most parts of the library)


Technically, I _think_ the parser could be cached slightly finer grained, (e.g. on the outer MathtextParser instance (which is initialized by the Renderer, so that would be one per renderer instead of one per process...) But that has performance (and memory) concerns, so not fully ready to commit to that at least without testing and comparing thouroughly.

**Comment by anntzer** [comment]
Agreed that a finer grained caching may have performance implications (we don't want to parse the text twice, once when displaying it interactively and once when saving (which can be done with two different renderers)); I'd support just closing this on the basis of "we're explicitly not threadsafe".

**Comment by karpov-sv** [comment]
I understand that - but why does it work without `tight_layout=True` set?..

**Comment by jklymak** [comment]
Feel free to continue discussion, but I don't think there is anything actionable here.

**Comment by tacaswell** [comment]
We do have one threading lock in the library: https://github.com/matplotlib/matplotlib/blob/e8bfdcb3c153806ffd5391239c1640d5238bcbe2/lib/matplotlib/backends/backend_agg.py#L393-L404

which is protecting the `ft2font` objects but I suspect is also protecting the mathtext singleton.

When using a layout engine we go through https://github.com/matplotlib/matplotlib/blob/e8bfdcb3c153806ffd5391239c1640d5238bcbe2/lib/matplotlib/backend_bases.py#L2141-L2151 which escapes that lock, but when we actually save the file in https://github.com/matplotlib/matplotlib/blob/e8bfdcb3c153806ffd5391239c1640d5238bcbe2/lib/matplotlib/backend_bases.py#L2180-L2187 we are actually going through https://github.com/matplotlib/matplotlib/blob/e8bfdcb3c153806ffd5391239c1640d5238bcbe2/lib/matplotlib/backends/backend_agg.py#L453-L461 which does go through the code path that locks.

While we say we are not thread safe, I think that should apply to messing with the same Figure from multiple threads, working on different figures on different threads (as is very common when using us in a web server) is something that we have historically supported and should continue to support.


I suspect that we could put a class-level RLock on `Figure` and hold it during `draw` and `draw_without_rendering` (and maybe get rid of the Agg level lock).

**Comment by tacaswell** [comment]
although it looks like we have been escaping this lock from 3.2 (2019) so I am a bit surprised that this is the first time this issue has been reported.

I suspect without mathtext the errors are either silent and mostly harmless (we get a size wrong while computing the size of the texts) or silent and a bit scary (we render the wrong text!) so are much harder to notice than a traceback.
