### ISSUE TITLE
[Bug]: UnboundLocalError: local variable 'interval' referenced before assignment

### ISSUE THREAD

**Issue by tnakamot** [matplotlib/matplotlib#26363]
### Bug summary

The code below ends up with an exception.

### Code for reproduction

```python
from datetime import datetime, timedelta
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

fig, ax = plt.subplots()
t0 = datetime.now()
dt = timedelta(seconds=1)
ax.plot([t0, t0+dt, t0+dt*2], [1, 2, 3])

locator = mdates.AutoDateLocator()
locator.intervald[mdates.MICROSECONDLY] = []
ax.xaxis.set_major_locator(locator)
ax.xaxis.set_major_formatter(mdates.DateFormatter('%H:%M:%S'))

plt.show()
```

### Actual outcome

Below is the exception message with a stack trace.

> Traceback (most recent call last):
  File "/home/tnakamoto/.local/lib/python3.10/site-packages/matplotlib/backends/backend_qt.py", line 468, in _draw_idle
    self.draw()
  File "/home/tnakamoto/.local/lib/python3.10/site-packages/matplotlib/backends/backend_agg.py", line 400, in draw
    self.figure.draw(self.renderer)
  File "/home/tnakamoto/.local/lib/python3.10/site-packages/matplotlib/artist.py", line 95, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/home/tnakamoto/.local/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/home/tnakamoto/.local/lib/python3.10/site-packages/matplotlib/figure.py", line 3175, in draw
    mimage._draw_list_compositing_images(
  File "/home/tnakamoto/.local/lib/python3.10/site-packages/matplotlib/image.py", line 131, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/tnakamoto/.local/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/home/tnakamoto/.local/lib/python3.10/site-packages/matplotlib/axes/_base.py", line 3064, in draw
    mimage._draw_list_compositing_images(
  File "/home/tnakamoto/.local/lib/python3.10/site-packages/matplotlib/image.py", line 131, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/tnakamoto/.local/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/home/tnakamoto/.local/lib/python3.10/site-packages/matplotlib/axis.py", line 1376, in draw
    ticks_to_draw = self._update_ticks()
  File "/home/tnakamoto/.local/lib/python3.10/site-packages/matplotlib/axis.py", line 1262, in _update_ticks
    major_locs = self.get_majorticklocs()
  File "/home/tnakamoto/.local/lib/python3.10/site-packages/matplotlib/axis.py", line 1484, in get_majorticklocs
    return self.major.locator()
  File "/home/tnakamoto/.local/lib/python3.10/site-packages/matplotlib/dates.py", line 1378, in __call__
    locator = self.get_locator(dmin, dmax)
  File "/home/tnakamoto/.local/lib/python3.10/site-packages/matplotlib/dates.py", line 1460, in get_locator
    f"intervald dictionary. Defaulting to {interval}.")
UnboundLocalError: local variable 'interval' referenced before assignment

### Expected outcome

Matplotlib should not raise this exception, but show an appropriate warning instead.

### Operating system

Ubuntu 22.04 on WSL2

### Matplotlib Version

3.7.2

### Matplotlib Backend

QtAgg

### Python version

3.10.6

### Installation

pip

**Comment by QuLogic** [comment]
> ```python
> locator.intervald[mdates.MICROSECONDLY] = []
> ```

Hmm, it's not clear to me whether that is a valid input to `intervald`; the docs do not specifically spell out the requirements.

What is your expected behaviour when passing an empty list?

**Comment by tnakamot** [comment]
I followed [the documentation about AutoDateLocator](https://matplotlib.org/stable/api/dates_api.html#matplotlib.dates.AutoDateLocator). It clearly says that we cannot add or delete entries in ``interval``, but it does not prevent us from settings an empty list to each entry. Even if that is not valid, the exception should be raised when an empty list is given, not when matplotlib actually draws the plot.

The intent of settings an empty list to ``interval[MICROSECONDLY]`` is to prevent matplotlib from making ticks on a place where the fractional second is not zero. Otherwise, matplotlib could make a tick at 14:08:52.624, but I don't want that. I would like to have ticks at 14:08:52.000, 14:09:53.000, ....

**Comment by tacaswell** [comment]
To get what you want I think 

```python
locator.intervald[mdates.MICROSECONDLY] = [1_000_000]
```

is the fix (it says you can only put ticks every 1M microseconds (which is on the seconds).

I think I see an easy fix to skip a frequency all together (by accepting an empty list).

**Comment by tnakamot** [comment]
@tacaswell Thank you for the workaround. That works well in my case.

**Comment by tacaswell** [comment]
```diff
diff --git a/lib/matplotlib/dates.py b/lib/matplotlib/dates.py
index 381dd810a5..a9d6c4c2df 100644
--- a/lib/matplotlib/dates.py
+++ b/lib/matplotlib/dates.py
@@ -1443,6 +1443,12 @@ class AutoDateLocator(DateLocator):
                 byranges[i] = None
                 continue

+            # if there are no candidate intervals at this level, skip it
+            # and move on.
+            if len(self.intervald[freq]) == 0:
+                byranges[i] = None
+                continue
+
             # Find the first available interval that doesn't give too many
             # ticks
             for interval in self.intervald[freq]:
```

but in this case seems to fall back to the `Microsceond` locator with an internal of 1 which is a worst-case scenario here....

It is not yet clear to me what the right behavior here is.  On one hand, being able to drop out a level makes sense, but in this particular case it the algorithm did not like any of the other values so fell back to a _very_ bad default.

**Comment by tacaswell** [comment]
Tagging as 3.9 as I think there maybe some behavior change we want here.

**Comment by raghav24agarwal** [comment]
Hi @tacaswell , is there anyone working on this issue ?

**Comment by melissawm** [comment]
@raghav24agarwal unless there is a PR linked to the issue, you can feel free to work on it. If you want to check your ideas before spending time on a full solution, feel free to also comment here on the issue with a proposed way forward. Cheers!

**Comment by QuLogic** [comment]
I tried applying @tacaswell's patch, and ran the example, but this outputs:
> Locator attempting to generate 2200002 ticks ([19743141762.0, ..., 19745341763.0]), which exceeds Locator.MAXTICKS (1000).
and then gets relatively stuck.

**Comment by anntzer** [comment]
This seems to be a case of an over-constrained problem: it seems easy to make it impossible to satisfy all of minticks, maxticks, and intervald, and the approach of ignoring intervald first (and not having the possibility to backtrack in the intervald scan) in case of unsatisfiability will indeed result in possibly a million microsecond ticks (as indicated above).
I wonder if maxticks is really necessary or has been made at least somewhat redundant with `get_tick_space()`, and whether we could get rid of minticks, so that the algorithm becomes simply "try to draw as many ticks as possible while satisfying both intervald and, *if possible*, get_tick_space()"
