### ISSUE TITLE
[Bug]: timedelta64 with pcolormesh

### ISSUE THREAD

**Issue by jklymak** [matplotlib/matplotlib#26525]
### Bug summary

`timedelta64` doesn't work with pcolormesh, and many other methods.  

### Code for reproduction

```python
import matplotlib.pyplot as plt
import numpy as np

time = np.arange(0, 50, dtype='timedelta64[h]')
y = np.arange(10)
Z = np.random.randn(10, 50)

fig, ax = plt.subplots()
ax.pcolormesh(time, y, Z)
```

### Actual outcome

```
Traceback (most recent call last):
  File "/Users/jklymak/matplotlib/testit.py", line 9, in <module>
    ax.pcolormesh(time, y, Z)
  File "/Users/jklymak/matplotlib/lib/matplotlib/__init__.py", line 1465, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jklymak/matplotlib/lib/matplotlib/axes/_axes.py", line 6270, in pcolormesh
    X, Y, C, shading = self._pcolorargs('pcolormesh', *args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jklymak/matplotlib/lib/matplotlib/axes/_axes.py", line 5854, in _pcolorargs
    X = _interp_grid(X)
        ^^^^^^^^^^^^^^^
  File "/Users/jklymak/matplotlib/lib/matplotlib/axes/_axes.py", line 5833, in _interp_grid
    dX = np.diff(X, axis=1)/2.
         ~~~~~~~~~~~~~~~~~~^~~
  File "/Users/jklymak/mambaforge/envs/mpl-dev/lib/python3.11/site-packages/numpy/ma/core.py", line 4254, in __truediv__
    return true_divide(self, other)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jklymak/mambaforge/envs/mpl-dev/lib/python3.11/site-packages/numpy/ma/core.py", line 1171, in __call__
    m |= domain(da, db)
         ^^^^^^^^^^^^^^
  File "/Users/jklymak/mambaforge/envs/mpl-dev/lib/python3.11/site-packages/numpy/ma/core.py", line 858, in __call__
    return umath.absolute(a) * self.tolerance >= umath.absolute(b)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: The DType <class 'numpy.dtype[timedelta64]'> could not be promoted by <class 'numpy.dtype[float64]'>. This means that no common DType exists for the given inputs. For example they cannot be stored in a single array unless the dtype is `object`. The full list of DTypes is: (<class 'numpy.dtype[timedelta64]'>, <class 'numpy.dtype[float64]'>)
```

### Expected outcome

The expected outcome is debatable.  We have tried to have this go through units like `datetime64`.  However, I really think we should just convert to float.  Yeah, that will give giant numbers for timedelta64 of ns, but I think it's better than failing.

### Matplotlib Version

main

### Installation

None

**Comment by Captain-Arnab** [comment]
```
from datetime import datetime, timedelta
import matplotlib.pyplot as plt
import numpy as np

#time = np.arange(0, 50, dtype=np.timedelta64(1,"h"))
base = datetime.today()
time = [base - timedelta(hours=x) for x in range(0, 50)]
y = np.arange(10)
Z = np.random.randn(10, 50)

fig, ax = plt.subplots()
ax.pcolormesh(time, y, Z)
```
I have tried this code, it's working.
If it doesn't work then let me know.

**Comment by jklymak** [comment]
That does work.  What does not work is timedelta64, which is a very common format for in numerical simulations and other applications.

**Comment by ksunden** [comment]
Hmmm... odd... when I just create an array with dtype timedelta64[h], I can diff and divide that by 2 with no issues, not sure what is different about the usage internally...

It is a masked array internally, so a masked array with timedelta dtype differs from a normal array, and that seems like perhaps something that should be fixed upstream

Pure numpy examples:
```python
>>> masked_array([1,2,3], dtype="timedelta64[h]")
masked_array(data=[1, 2, 3],
             mask=False,
       fill_value=numpy.timedelta64('NaT','h'),
            dtype='timedelta64[h]')
>>> masked_array([1,2,3], dtype="timedelta64[h]") / 2
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:1                                                                                    │
│                                                                                                  │
│ /home/kyle/venvs/pyenv/versions/edge/lib/python3.11/site-packages/numpy/ma/core.py:4270 in       │
│ __truediv__                                                                                      │
│                                                                                                  │
│   4267 │   │   """                                                                               │
│   4268 │   │   if self._delegate_binop(other):                                                   │
│   4269 │   │   │   return NotImplemented                                                         │
│ ❱ 4270 │   │   return true_divide(self, other)                                                   │
│   4271 │                                                                                         │
│   4272 │   def __rtruediv__(self, other):                                                        │
│   4273 │   │   """                                                                               │
│                                                                                                  │
│ /home/kyle/venvs/pyenv/versions/edge/lib/python3.11/site-packages/numpy/ma/core.py:1171 in       │
│ __call__                                                                                         │
│                                                                                                  │
│   1168 │   │   # Apply the domain                                                                │
│   1169 │   │   domain = ufunc_domain.get(self.f, None)                                           │
│   1170 │   │   if domain is not None:                                                            │
│ ❱ 1171 │   │   │   m |= domain(da, db)                                                           │
│   1172 │   │   # Take care of the scalar case first                                              │
│   1173 │   │   if not m.ndim:                                                                    │
│   1174 │   │   │   if m:                                                                         │
│                                                                                                  │
│ /home/kyle/venvs/pyenv/versions/edge/lib/python3.11/site-packages/numpy/ma/core.py:858 in        │
│ __call__                                                                                         │
│                                                                                                  │
│    855 │   │   # don't call ma ufuncs from __array_wrap__ which would fail for scalars           │
│    856 │   │   a, b = np.asarray(a), np.asarray(b)                                               │
│    857 │   │   with np.errstate(invalid='ignore'):                                               │
│ ❱  858 │   │   │   return umath.absolute(a) * self.tolerance >= umath.absolute(b)                │
│    859                                                                                           │
│    860                                                                                           │
│    861 class _DomainGreater:                                                                     │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
UFuncTypeError: Cannot cast ufunc 'greater_equal' input 0 from dtype('<m8[h]') to dtype('<m8') with casting rule 'same_kind'


>>> array([1,2,3], dtype="timedelta64[h]") / 2
array([0, 1, 1], dtype='timedelta64[h]')
```

**Comment by ksunden** [comment]
for the record add, subtract, and multiply all work fine, It is just divide (and mod) operations.

Also trig/log/sqrt, but those ones do _not_ work on standard timedelta arrays, so not as concerned

But the underlying thing here is that comparisons are used to guard against infinities, for... some reason...

See discussion at numpy/numpy#22347, particularly https://github.com/numpy/numpy/issues/22347#issuecomment-1262036298

**Comment by jklymak** [comment]
I mean is the practical fix to multiply by 0.5?

**Comment by jklymak** [comment]
You can keep chasing this down the stack, but at the end of the day, X needs to be a float at this point as we have already called `_process_unit_info`.  

Note https://github.com/matplotlib/matplotlib/pull/19236 makes a new Converter interface for timedelta64 which would close this.  I think the question is if they PR needs to be perfect, or greatly simplified (eg just convert to float, using whatever timedelta64 units are supplied).
