### ISSUE TITLE
matplotlib.tests.test_mathtext.test_mathtext_{cm,stix,stixsans}_{37,53}.test are failing

### ISSUE THREAD

**Issue by jlec** [matplotlib/matplotlib#2667]
FAIL: matplotlib.tests.test_mathtext.test_mathtext_cm_53.test
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/var/tmp/portage/dev-python/matplotlib-9999/work/matplotlib-9999-python2_7/build/test/lib/matplotlib-1.4.x-py2.7-linux-x86_64.egg/matplotlib/testing/decorators.py", line 45, in failer
    result = f(*args, **kwargs)
  File "/var/tmp/portage/dev-python/matplotlib-9999/work/matplotlib-9999-python2_7/build/test/lib/matplotlib-1.4.x-py2.7-linux-x86_64.egg/matplotlib/testing/decorators.py", line 189, in do_test
    '(RMS %(rms).3f)'%err)
ImageComparisonFailure: images not close: /var/tmp/portage/dev-python/matplotlib-9999/temp/python2.7/result_images/test_mathtext/mathtext_cm_53_pdf.png vs. /var/tmp/portage/dev-python/matplotlib-9999/temp/python2.7/result_images/test_mathtext/mathtext_cm_53-expected_pdf.png (RMS 34.378)

**Comment by efiring** [comment]
This looks like something that has been addressed.  Closing.
