### ISSUE TITLE
[Bug]: Zoom not working matplotlib.backends.backend_wxagg.NavigationToolbar2WxAgg

### ISSUE THREAD

**Issue by EirikJaccheri** [matplotlib/matplotlib#26857]
### Bug summary

When running  the "Embedding in wx #2", code from the matplotlib documentation (https://matplotlib.org/stable/gallery/user_interfaces/embedding_in_wx2_sgskip.html), the zoom function in the toolbar does not make a square and throws error:

File "/usr/lib/python3/dist-packages/wx/core.py", line 1098, in _DC_DrawLineList
    return self._DrawLineList(lines, pens, [])
TypeError: 'numpy.float64' object cannot be interpreted as an integer

### Code for reproduction

```python
import wx
import wx.lib.mixins.inspection as WIT

import numpy as np

from matplotlib.backends.backend_wxagg import FigureCanvasWxAgg as FigureCanvas
from matplotlib.backends.backend_wxagg import \
    NavigationToolbar2WxAgg as NavigationToolbar
from matplotlib.figure import Figure


class CanvasFrame(wx.Frame):
    def __init__(self):
        super().__init__(None, -1, 'CanvasFrame', size=(550, 350))

        self.figure = Figure()
        self.axes = self.figure.add_subplot()
        t = np.arange(0.0, 3.0, 0.01)
        s = np.sin(2 * np.pi * t)

        self.axes.plot(t, s)
        self.canvas = FigureCanvas(self, -1, self.figure)

        self.sizer = wx.BoxSizer(wx.VERTICAL)
        self.sizer.Add(self.canvas, 1, wx.LEFT | wx.TOP | wx.EXPAND)
        self.SetSizer(self.sizer)
        self.Fit()

        self.add_toolbar()  # comment this out for no toolbar

    def add_toolbar(self):
        self.toolbar = NavigationToolbar(self.canvas)
        self.toolbar.Realize()
        # By adding toolbar in sizer, we are able to put it at the bottom
        # of the frame - so appearance is closer to GTK version.
        self.sizer.Add(self.toolbar, 0, wx.LEFT | wx.EXPAND)
        # update the axes menu on the toolbar
        self.toolbar.update()


# Alternatively you could use:
# class App(wx.App):
class App(WIT.InspectableApp):
    def OnInit(self):
        """Create the main window and insert the custom frame."""
        self.Init()
        frame = CanvasFrame()
        frame.Show(True)

        return True


if __name__ == "__main__":
    app = App()
    app.MainLoop()
```

### Actual outcome

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_wx.py", line 655, in _onPaint
    self.gui_repaint(drawDC=drawDC)
  File "/usr/lib/python3/dist-packages/matplotlib/_api/deprecation.py", line 386, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_wx.py", line 622, in gui_repaint
    drawDC.DrawLineList(
  File "/usr/lib/python3/dist-packages/wx/core.py", line 1098, in _DC_DrawLineList
    return self._DrawLineList(lines, pens, [])
TypeError: 'numpy.float64' object cannot be interpreted as an integer
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_wx.py", line 655, in _onPaint
    self.gui_repaint(drawDC=drawDC)
  File "/usr/lib/python3/dist-packages/matplotlib/_api/deprecation.py", line 386, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_wx.py", line 622, in gui_repaint
    drawDC.DrawLineList(
  File "/usr/lib/python3/dist-packages/wx/core.py", line 1098, in _DC_DrawLineList
    return self._DrawLineList(lines, pens, [])
TypeError: 'numpy.float64' object cannot be interpreted as an integer
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_wx.py", line 655, in _onPaint
    self.gui_repaint(drawDC=drawDC)
  File "/usr/lib/python3/dist-packages/matplotlib/_api/deprecation.py", line 386, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_wx.py", line 622, in gui_repaint
    drawDC.DrawLineList(
  File "/usr/lib/python3/dist-packages/wx/core.py", line 1098, in _DC_DrawLineList
    return self._DrawLineList(lines, pens, [])
TypeError: 'numpy.float64' object cannot be interpreted as an integer
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_wx.py", line 655, in _onPaint
    self.gui_repaint(drawDC=drawDC)
  File "/usr/lib/python3/dist-packages/matplotlib/_api/deprecation.py", line 386, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_wx.py", line 622, in gui_repaint
    drawDC.DrawLineList(
  File "/usr/lib/python3/dist-packages/wx/core.py", line 1098, in _DC_DrawLineList
    return self._DrawLineList(lines, pens, [])
TypeError: 'numpy.float64' object cannot be interpreted as an integer
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_wx.py", line 655, in _onPaint
    self.gui_repaint(drawDC=drawDC)
  File "/usr/lib/python3/dist-packages/matplotlib/_api/deprecation.py", line 386, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_wx.py", line 622, in gui_repaint
    drawDC.DrawLineList(
  File "/usr/lib/python3/dist-packages/wx/core.py", line 1098, in _DC_DrawLineList
    return self._DrawLineList(lines, pens, [])
TypeError: 'numpy.float64' object cannot be interpreted as an integer
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_wx.py", line 655, in _onPaint
    self.gui_repaint(drawDC=drawDC)
  File "/usr/lib/python3/dist-packages/matplotlib/_api/deprecation.py", line 386, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_wx.py", line 622, in gui_repaint
    drawDC.DrawLineList(
  File "/usr/lib/python3/dist-packages/wx/core.py", line 1098, in _DC_DrawLineList
    return self._DrawLineList(lines, pens, [])
TypeError: 'numpy.float64' object cannot be interpreted as an integer
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_wx.py", line 655, in _onPaint
    self.gui_repaint(drawDC=drawDC)
  File "/usr/lib/python3/dist-packages/matplotlib/_api/deprecation.py", line 386, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_wx.py", line 622, in gui_repaint
    drawDC.DrawLineList(
  File "/usr/lib/python3/dist-packages/wx/core.py", line 1098, in _DC_DrawLineList
    return self._DrawLineList(lines, pens, [])
TypeError: 'numpy.float64' object cannot be interpreted as an integer
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_wx.py", line 655, in _onPaint
    self.gui_repaint(drawDC=drawDC)
  File "/usr/lib/python3/dist-packages/matplotlib/_api/deprecation.py", line 386, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_wx.py", line 622, in gui_repaint
    drawDC.DrawLineList(
  File "/usr/lib/python3/dist-packages/wx/core.py", line 1098, in _DC_DrawLineList
    return self._DrawLineList(lines, pens, [])
TypeError: 'numpy.float64' object cannot be interpreted as an integer
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_wx.py", line 655, in _onPaint
    self.gui_repaint(drawDC=drawDC)
  File "/usr/lib/python3/dist-packages/matplotlib/_api/deprecation.py", line 386, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_wx.py", line 622, in gui_repaint
    drawDC.DrawLineList(
  File "/usr/lib/python3/dist-packages/wx/core.py", line 1098, in _DC_DrawLineList
    return self._DrawLineList(lines, pens, [])
TypeError: 'numpy.float64' object cannot be interpreted as an integer
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_wx.py", line 655, in _onPaint
    self.gui_repaint(drawDC=drawDC)
  File "/usr/lib/python3/dist-packages/matplotlib/_api/deprecation.py", line 386, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_wx.py", line 622, in gui_repaint
    drawDC.DrawLineList(
  File "/usr/lib/python3/dist-packages/wx/core.py", line 1098, in _DC_DrawLineList
    return self._DrawLineList(lines, pens, [])
TypeError: 'numpy.float64' object cannot be interpreted as an integer
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_wx.py", line 655, in _onPaint
    self.gui_repaint(drawDC=drawDC)
  File "/usr/lib/python3/dist-packages/matplotlib/_api/deprecation.py", line 386, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_wx.py", line 622, in gui_repaint
    drawDC.DrawLineList(
  File "/usr/lib/python3/dist-packages/wx/core.py", line 1098, in _DC_DrawLineList
    return self._DrawLineList(lines, pens, [])
TypeError: 'numpy.float64' object cannot be interpreted as an integer
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_wx.py", line 655, in _onPaint
    self.gui_repaint(drawDC=drawDC)
  File "/usr/lib/python3/dist-packages/matplotlib/_api/deprecation.py", line 386, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_wx.py", line 622, in gui_repaint
    drawDC.DrawLineList(
  File "/usr/lib/python3/dist-packages/wx/core.py", line 1098, in _DC_DrawLineList
    return self._DrawLineList(lines, pens, [])
TypeError: 'numpy.float64' object cannot be interpreted as an integer
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_wx.py", line 655, in _onPaint
    self.gui_repaint(drawDC=drawDC)
  File "/usr/lib/python3/dist-packages/matplotlib/_api/deprecation.py", line 386, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_wx.py", line 622, in gui_repaint
    drawDC.DrawLineList(
  File "/usr/lib/python3/dist-packages/wx/core.py", line 1098, in _DC_DrawLineList
    return self._DrawLineList(lines, pens, [])
TypeError: 'numpy.float64' object cannot be interpreted as an integer

### Expected outcome

Expected zoom to work as a normal matplotlib plot.

### Additional information

I assume the code worked in a earlier version since the script was taken directly from the matplotlib documentation.

I installed wxPython using synaptic: 

python3-wxgtk4.0 v

version: python3-wxgtk4.0

### Operating system

 Ubuntu 22.04.3 LTS, release 22.04

### Matplotlib Version

3.5.1

### Matplotlib Backend

TkAgg

### Python version

Python 3.10.12

### Jupyter version

4.0.5

### Installation

pip

**Comment by QuLogic** [comment]
This was fixed by #21990 in 3.5.2. Please update.
