### ISSUE TITLE
[Bug]: PGF Backend Does not Handle ‘#’ in Labels Properly

### ISSUE THREAD

**Issue by nhusung** [matplotlib/matplotlib#27048]
### Bug summary

When I try to use a ‘#‘ in labels, the PGF backend fails with the error message
```
matplotlib.backends.backend_pgf.LatexError: LaTeX process halted
! You can't use `macro parameter character #' in restricted horizontal mode.
```

### Code for reproduction

```python
import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
import platform

print(mpl.__version__)
print(platform.python_version())


y = [4.8, 5.5, 3.5, 4.6, 6.5, 6.6, 2.6, 3.0]

fig, ax = plt.subplots()

ax.stairs(y, linewidth=2.5)

ax.set(xlim=(0, 8), xticks=np.arange(1, 8),
       ylim=(0, 8), yticks=np.arange(1, 8))

plt.ylabel("# solved instances")
plt.savefig('test.pgf')
```

### Actual outcome

Full console output:

```
3.8.0
3.11.5
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/matplotlib/backends/backend_pgf.py", line 307, in _get_box_metrics
    answer = self._expect_prompt()
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/matplotlib/backends/backend_pgf.py", line 235, in _expect_prompt
    return self._expect("\n*")
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/matplotlib/backends/backend_pgf.py", line 231, in _expect
    raise LatexError("LaTeX process halted", "".join(chars))
matplotlib.backends.backend_pgf.LatexError: LaTeX process halted
! You can't use `macro parameter character #' in restricted horizontal mode.
<argument> ...i }\catcode `\%=\active \def %{\%}##
                                                   solved instances}
<*> ...ode`\%=\active\def%{\%}# solved instances}}
                                                  \typeout{\the\wd0,\the\ht0...
No pages of output.
Transcript written on texput.log.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/test.py", line 20, in <module>
    plt.savefig('test.pgf')
  File "/usr/lib/python3.11/site-packages/matplotlib/pyplot.py", line 1119, in savefig
    res = fig.savefig(*args, **kwargs)  # type: ignore[func-returns-value]
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/matplotlib/figure.py", line 3390, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/usr/lib/python3.11/site-packages/matplotlib/backends/backend_qtagg.py", line 75, in print_figure
    super().print_figure(*args, **kwargs)
  File "/usr/lib/python3.11/site-packages/matplotlib/backend_bases.py", line 2187, in print_figure
    result = print_method(
             ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/matplotlib/backend_bases.py", line 2043, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
                                                                 ^^^^^
  File "/usr/lib/python3.11/site-packages/matplotlib/backends/backend_pgf.py", line 797, in print_pgf
    self._print_pgf_to_fh(file, **kwargs)
  File "/usr/lib/python3.11/site-packages/matplotlib/backends/backend_pgf.py", line 782, in _print_pgf_to_fh
    self.figure.draw(renderer)
  File "/usr/lib/python3.11/site-packages/matplotlib/artist.py", line 95, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/matplotlib/figure.py", line 3154, in draw
    mimage._draw_list_compositing_images(
  File "/usr/lib/python3.11/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/lib/python3.11/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/matplotlib/axes/_base.py", line 3070, in draw
    mimage._draw_list_compositing_images(
  File "/usr/lib/python3.11/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/lib/python3.11/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/matplotlib/axis.py", line 1395, in draw
    self.label.draw(renderer)
  File "/usr/lib/python3.11/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/matplotlib/text.py", line 748, in draw
    bbox, info, descent = self._get_layout(renderer)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/matplotlib/text.py", line 381, in _get_layout
    w, h, d = _get_text_metrics_with_cache(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/matplotlib/text.py", line 69, in _get_text_metrics_with_cache
    return _get_text_metrics_with_cache_impl(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/matplotlib/text.py", line 77, in _get_text_metrics_with_cache_impl
    return renderer_ref().get_text_width_height_descent(text, fontprop, ismath)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/matplotlib/backends/backend_pgf.py", line 704, in get_text_width_height_descent
    .get_width_height_descent(s, prop))
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/matplotlib/backends/backend_pgf.py", line 292, in get_width_height_descent
    return self._get_box_metrics(_escape_and_apply_props(text, prop))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/matplotlib/backends/backend_pgf.py", line 311, in _get_box_metrics
    raise ValueError("Error measuring {}\nLaTeX Output:\n{}"
ValueError: Error measuring {\sffamily\fontsize{10.000000}{12.000000}\selectfont\catcode`\^=\active\def^{\ifmmode\sp\else\^{}\fi}\catcode`\%=\active\def%{\%}# solved instances}
LaTeX Output:
! You can't use `macro parameter character #' in restricted horizontal mode.
<argument> ...i }\catcode `\%=\active \def %{\%}##
                                                   solved instances}
<*> ...ode`\%=\active\def%{\%}# solved instances}}
                                                  \typeout{\the\wd0,\the\ht0...
No pages of output.
Transcript written on texput.log.
```

### Expected outcome

A PGF file for https://matplotlib.org/stable/plot_types/basic/stairs.html#sphx-glr-plot-types-basic-stairs-py but with the respective Y-label.

### Additional information

Using `plt.ylabel(r"\# solved instances")` works.

### Operating system

Arch Linux

### Matplotlib Version

3.8.0

### Matplotlib Backend

pgf

### Python version

3.11.5

### Jupyter version

6.5.4

### Installation

Linux package manager

**Comment by oscargus** [comment]
This is more of a LaTeX issue. There isn't much we can do about it (given that sometimes people would like to use the "LaTeX #"). So all labels must be valid from a LaTeX perspective when using PGF and/or `usetex=True`. (Just like you will not get '$a$' doing `plt.ylabel("$a$")` with the PGF backend.)

**Comment by jklymak** [comment]
For your report, do you need PGF versus say PDF?  If you make a pgf graphic, the assumption is that you are going to pass through latex to process the text, so you'd need to follow latex escaping requirements.  Conversely if you are locked to PGF for some reason, I'd let your labels in PNG look bad if those are just for a quick look.  

But overall, PDF should look much closer to the png and still be vector graphics.

**Comment by nhusung** [comment]
I’d like to use PGF because this way, the fonts are the same as in any other TikZ figure. But I agree, using the escaped variant in PNGs would be an option given that it is mainly for previewing purposes. I just found out that https://matplotlib.org/stable/users/explain/text/pgf.html states that the current behavior is the desired one. So I’m closing this now. Thanks for your help.

**Comment by ksunden** [comment]
I will also point to the note that gives a workaround which may be precisely what you are looking for:

> However, one can configure TeX to treat them as "normal" characters (known as "catcode 12" to TeX) via a custom preamble, such as:

```python
plt.rcParams["pgf.preamble"] = (
    r"\AtBeginDocument{\catcode`\&=12\catcode`\#=12}")
```

That seemed to work when I tested it.
