### ISSUE TITLE
[Bug]: gridspec __init__ doesn't provision for float.is_integer for nrows and ncols

### ISSUE THREAD

**Issue by wdeshazer** [matplotlib/matplotlib#27260]
### Bug summary

OMFIT has some plotting utilities that previously used subplot with arguments that were integer float. Two years ago, @anntzer in commit https://github.com/matplotlib/matplotlib/commit/eff7337 moved an integer check into _from_subplot_args but there was no provision for integer floats. 
- Is there a reason that integer float is not an acceptable argument?
- Wouldn't a test that catches integer floats and recasts them as straight ints be more user friendly than error-ing out? 

Below, I am attaching the quick and easy fix. However, it would be easy to refactor as a try except block that attempted to recast integer floats and only errored when there truly was no integer.

```python
if not isinstance(nrows, Integral) or nrows.is_integer() or nrows <= 0:
    raise ValueError(
        f"Number of rows must be a positive integer, not {nrows!r}")
if not isinstance(ncols, Integral)  or nrows.is_integer() or ncols <= 0:
    raise ValueError(
        f"Number of columns must be a positive integer, not {ncols!r}")
```

### Code for reproduction

```python
from matplotlib import pyplot
ax1 = pyplot.subplot(5.0, 4.0, 1.0)
```

### Actual outcome

```python
Error in "OMFIT command box #1" at line  1
    ax1 = pyplot.subplot(5.0, 4.0, 1.0)
ValueError: Number of rows must be a positive integer, not 5.0


Press <F6> to see full error report...

Traceback (most recent call last):
  File "/Users/deshazere/OMFIT-source/omfit/omfit_plot.py", line 2074, in subplot
    if args in fig._stored_axes:
AttributeError: 'Figure' object has no attribute '_stored_axes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/deshazere/OMFIT-source/omfit/omfit_classes/OMFITx.py", line 4624, in manage_user_errors
    tmp = command(**kw)
  File "/Users/deshazere/OMFIT-source/omfit/utils_tk.py", line 1180, in GlobLoc_tk
    return py.run(_relLoc=self.namespace, _OMFITscriptsDict=False, _OMFITconsoleDict=True, noGUI=None)
  File "/Users/deshazere/OMFIT-source/omfit/omfit_classes/omfit_python.py", line 1105, in run
    result = self.__run__(**kw)
  File "/Users/deshazere/OMFIT-source/omfit/omfit_classes/omfit_python.py", line 954, in __run__
    self, userDict=kw, inputDict=_relLoc, persistentDict=OMFITconsoleDict, runDict={}, prerun=prerun, postrun=postrun
  File "/Users/deshazere/OMFIT-source/omfit/omfit_classes/omfit_python.py", line 129, in f_locked
    return f(*args, **kw)
  File "/Users/deshazere/OMFIT-source/omfit/omfit_classes/omfit_python.py", line 376, in execGlobLoc
    exec(compile(execString, filename, "exec"), GlobLoc)
  File "/private/tmp/deshazere/OMFIT/OMFIT_2023-11-02_19_52_58_742465/project/OMFIT command box #1", line 1, in <module>
    ax1 = pyplot.subplot(5.0, 4.0, 1.0)
  File "/Users/deshazere/OMFIT-source/omfit/omfit_plot.py", line 2080, in subplot
    _orig_subplot(*args, **kw)
  File "/Users/deshazere/mambaforge/envs/omfit/lib/python3.7/site-packages/matplotlib/pyplot.py", line 1287, in subplot
    key = SubplotSpec._from_subplot_args(fig, args)
  File "/Users/deshazere/mambaforge/envs/omfit/lib/python3.7/site-packages/matplotlib/gridspec.py", line 597, in _from_subplot_args
    gs = GridSpec._check_gridspec_exists(figure, rows, cols)
  File "/Users/deshazere/mambaforge/envs/omfit/lib/python3.7/site-packages/matplotlib/gridspec.py", line 225, in _check_gridspec_exists
    return GridSpec(nrows, ncols, figure=figure)
  File "/Users/deshazere/mambaforge/envs/omfit/lib/python3.7/site-packages/matplotlib/gridspec.py", line 387, in __init__
    height_ratios=height_ratios)
  File "/Users/deshazere/mambaforge/envs/omfit/lib/python3.7/site-packages/matplotlib/gridspec.py", line 50, in __init__
    f"Number of rows must be a positive integer, not {nrows!r}")
ValueError: Number of rows must be a positive integer, not 5.0
```

### Expected outcome

![image](https://github.com/matplotlib/matplotlib/assets/15264812/b7543e1e-c323-4472-a520-a5550d313c48)

### Additional information

This worked in matplotlib v 3.3.4.

![image](https://github.com/matplotlib/matplotlib/assets/15264812/c4c88814-6f3f-447c-8c82-88e2706bb1a1)

### Operating system

OS/X and Ubuntu

### Matplotlib Version

3.5.3

### Matplotlib Backend

TkAgg

### Python version

Python 3.7.10

### Installation

conda

**Comment by timhoffm** [comment]
This is an intentional narrowing and clarification of the API. In fact, it has always been documented as `int`. We consider the previous acceptance of float an implementation detail.
Semantically, these are integers and interpreting floating points as integers is non-trivial and can lead to surprising results. Not all integers have exact floating point representations, so we need some sort of rounding, but then do we also accept larger deviations, e.g. 1.1, 1.9 or even 1.5 - and if so what kind of rounding do we use? These are all complications that we don't want to have in our codebase and document their behavior. `int` is the simple and clean interface contract with the user here.

**Comment by jklymak** [comment]
I'll +1 here - the only reason to accept floating-point integers is if the user has done some arithmetic to get `ncols` or `nrows` and floating point arithmetic should probably be cast to float.

OTOH, I will say that `np.round(2.0001)` returns a floating point, and I've been personally grumpy that I had to do `int(np.round(2.0001))`, though I'm not sure if I was grumpy at numpy or Matplotlib - I think usually numpy.

**Comment by wdeshazer** [comment]
Thank you. I understand and I will pass that on to my team.
