### ISSUE TITLE
[Bug]: Matplotlib is not recognizing 'seaborn' as a valid style

### ISSUE THREAD

**Issue by ramikheireddine** [matplotlib/matplotlib#27317]
### Bug summary

Matplotlib is not recognizing 'seaborn' as a valid style

### Code for reproduction

```python
spladder build -o output_directory -b bam_file -a /home/databench/Rami_BulkRNA/Drosophila_melanogaster.BDGP6.32.109_UCSC.gtf.g
```

### Actual outcome

Traceback (most recent call last):
  File "/home/lab_anjohnson/miniconda3/lib/python3.10/site-packages/matplotlib/style/core.py", line 137, in use
    style = _rc_params_in_file(style)
  File "/home/lab_anjohnson/miniconda3/lib/python3.10/site-packages/matplotlib/__init__.py", line 871, in _rc_params_in_file
    with _open_file_or_url(fname) as fd:
  File "/home/lab_anjohnson/miniconda3/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/lab_anjohnson/miniconda3/lib/python3.10/site-packages/matplotlib/__init__.py", line 848, in _open_file_or_url
    with open(fname, encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'seaborn'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lab_anjohnson/miniconda3/bin/spladder", line 33, in <module>
    sys.exit(load_entry_point('spladder==3.0.4', 'console_scripts', 'spladder')())
  File "/home/lab_anjohnson/miniconda3/bin/spladder", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/lab_anjohnson/miniconda3/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/home/lab_anjohnson/miniconda3/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/lab_anjohnson/miniconda3/lib/python3.10/site-packages/spladder/spladder.py", line 9, in <module>
    from .spladder_viz import spladder_viz
  File "/home/lab_anjohnson/miniconda3/lib/python3.10/site-packages/spladder/spladder_viz.py", line 8, in <module>
    plt.style.use('seaborn')
  File "/home/lab_anjohnson/miniconda3/lib/python3.10/site-packages/matplotlib/style/core.py", line 139, in use
    raise OSError(
OSError: 'seaborn' is not a valid package style, path of style file, URL of style file, or library style name (library styles are listed in `style.available`)

### Expected outcome

I expect to get output_directory

### Operating system

Linux

### Matplotlib Version

3.9.0.dev0

### Installation

None

**Comment by ksunden** [comment]
https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.6.0.html#seaborn-styles-renamed

These styles were renamed to include version numbers and the unversioned names were deprecated in mpl 3.6.0 (and the deprecation expired for mpl 3.8.0)

This was an intentional change to avoid confusion with the current seaborn style, which has diverged.

You should be able to use `'seaborn-v0_8'` still, and that may need to be reported to `spladder` instead:

https://github.com/ratschlab/spladder/blob/9ad616f583c8113d14e59d06b7ed344e18f3087e/spladder/spladder_viz.py#L8C12-L8C12|

However, if you intend to use more recent versions of the seaborn style, you should do so via seaborn's APIs.

**Comment by ramikheireddine** [comment]
I apologize for any confusion, I am a beginner in these matters. But I did import the full directory for seaborn-v0_8 on python but I am still getting the same error. Could it be a compatibility issue between python and matplotlib ?

**Comment by ksunden** [comment]
I'm not clear what you mean... the line from spladder that uses the old name is not expected to work on newer matplotlib, having undergone a deprecation cycle. That line should be updated to use the new name to retain compatibility with newer mpl.
