### ISSUE TITLE
[CI]: PR Greetings is failing due to node.js error

### ISSUE THREAD

**Issue by scottshambaugh** [matplotlib/matplotlib#27371]
### Summary

This looks like it might be something upstream? I'm not sure how this is set up.

https://github.com/actions/first-interaction

See: https://github.com/matplotlib/matplotlib/actions/runs/6993830106/job/19026915960?pr=27349
```
Run actions/first-interaction@v1
/usr/bin/docker run --name fc51c55824a099e244e0ebe6dcdba01986c88_c8dfcd --label 6fc51c --workdir /github/workspace --rm -e "INPUT_REPO-TOKEN" -e "INPUT_PR-MESSAGE" -e "INPUT_ISSUE-MESSAGE" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/matplotlib/matplotlib":"/github/workspace" 6fc51c:55824a099e244e0ebe6dcdba01986c88
internal/modules/cjs/loader.js:1032
  throw err;
  ^

Error: Cannot find module 'node:assert'
Require stack:
- /node_modules/undici/lib/handler/RetryHandler.js
- /node_modules/undici/index.js
- /node_modules/@actions/http-client/lib/index.js
- /node_modules/@actions/core/lib/oidc-utils.js
- /node_modules/@actions/core/lib/core.js
- /lib/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/node_modules/undici/lib/handler/RetryHandler.js:1:16)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:[14](https://github.com/matplotlib/matplotlib/actions/runs/6993830106/job/19026915960?pr=27349#step:3:15))
    at Module.require (internal/modules/cjs/loader.js:1089:[19](https://github.com/matplotlib/matplotlib/actions/runs/6993830106/job/19026915960?pr=27349#step:3:20)) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/node_modules/undici/lib/handler/RetryHandler.js',
    '/node_modules/undici/index.js',
    '/node_modules/@actions/http-client/lib/index.js',
    '/node_modules/@actions/core/lib/oidc-utils.js',
    '/node_modules/@actions/core/lib/core.js',
    '/lib/main.js'
  ]
}
```

**Comment by pat8901** [comment]
I had this happen to my recent PR as well #27370.

See: https://github.com/matplotlib/matplotlib/actions/runs/6992396184/job/19023973611?pr=27370.

**Comment by scottshambaugh** [comment]
Looks like this is an upstream issue happening to others: https://github.com/actions/first-interaction/issues/286

**Comment by scottshambaugh** [comment]
This has been fixed upstream
