### ISSUE TITLE
[Bug]: 3.8.3 doesn't interact well throwing module 'backend_interagg' has no attribute 'FigureCanvas'

### ISSUE THREAD

**Issue by wywanchongshan** [matplotlib/matplotlib#27835]
### Bug summary

**code simple**

```python
import matplotlib.pyplot as plt
import numpy as np
import matplotlib as mpl


if __name__ == '__main__':

  fig, ax = plt.subplots()  # Create a figure containing a single axes.
  ax.plot([1, 2, 3, 4], [1, 4, 2, 3])  # Plot some data on the axes.

```
**actual output**

```
Traceback (most recent call last):
  File "C:\Users\gener\AppData\Roaming\JetBrains\IntelliJIdea2021.3\plugins\python\helpers\pydev\pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Users\gener\AppData\Roaming\JetBrains\IntelliJIdea2021.3\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "E:/dev/code/self/com/ai/test/python_1.py", line 8, in <module>
    fig, ax = plt.subplots()  # Create a figure containing a single axes.
  File "C:\Users\gener\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\pyplot.py", line 1613, in subplots
    fig = figure(**fig_kw)
  File "C:\Users\gener\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\pyplot.py", line 934, in figure
    manager = new_figure_manager(
  File "C:\Users\gener\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\pyplot.py", line 464, in new_figure_manager
    _warn_if_gui_out_of_main_thread()
  File "C:\Users\gener\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\pyplot.py", line 441, in _warn_if_gui_out_of_main_thread
    canvas_class = cast(type[FigureCanvasBase], _get_backend_mod().FigureCanvas)
  File "C:\Users\gener\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\pyplot.py", line 280, in _get_backend_mod
    switch_backend(rcParams._get("backend"))  # type: ignore[attr-defined]
  File "C:\Users\gener\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\pyplot.py", line 343, in switch_backend
    canvas_class = module.FigureCanvas
AttributeError: module 'backend_interagg' has no attribute 'FigureCanvas'
python-BaseException
```

**Version information**
python: 3.9
matplotlib: 3.8.3

### Code for reproduction

```Python
import matplotlib.pyplot as plt
import numpy as np
import matplotlib as mpl


if __name__ == '__main__':

  fig, ax = plt.subplots()  # Create a figure containing a single axes.
  ax.plot([1, 2, 3, 4], [1, 4, 2, 3])  # Plot some data on the axes.
```

### Actual outcome

Traceback (most recent call last):
  File "C:\Users\gener\AppData\Roaming\JetBrains\IntelliJIdea2021.3\plugins\python\helpers\pydev\pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Users\gener\AppData\Roaming\JetBrains\IntelliJIdea2021.3\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "E:/dev/code/self/com/ai/test/python_1.py", line 8, in <module>
    fig, ax = plt.subplots()  # Create a figure containing a single axes.
  File "C:\Users\gener\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\pyplot.py", line 1613, in subplots
    fig = figure(**fig_kw)
  File "C:\Users\gener\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\pyplot.py", line 934, in figure
    manager = new_figure_manager(
  File "C:\Users\gener\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\pyplot.py", line 464, in new_figure_manager
    _warn_if_gui_out_of_main_thread()
  File "C:\Users\gener\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\pyplot.py", line 441, in _warn_if_gui_out_of_main_thread
    canvas_class = cast(type[FigureCanvasBase], _get_backend_mod().FigureCanvas)
  File "C:\Users\gener\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\pyplot.py", line 280, in _get_backend_mod
    switch_backend(rcParams._get("backend"))  # type: ignore[attr-defined]
  File "C:\Users\gener\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\pyplot.py", line 343, in switch_backend
    canvas_class = module.FigureCanvas
AttributeError: module 'backend_interagg' has no attribute 'FigureCanvas'
python-BaseException

### Expected outcome

no error reporting

### Additional information

**Version information**
python: 3.9
matplotlib: 3.8.3

### Operating system

win 11

### Matplotlib Version

3.8.3

### Matplotlib Backend

module://backend_interagg

### Python version

3.9

### Installation

pip

**Comment by ksunden** [comment]
Please update your IDE. That backend is not provided by us, that is provided by InteliJ/Pycharm

That attribute was made mandatory in Matplotlib 3.6, with deprecation expiring in 3.8.

xref #25227 #23911
