### ISSUE TITLE
[Bug]: AttributeError: module 'matplotlib.cbook' has no attribute '_Stack'. Did you mean: 'Stack'?

### ISSUE THREAD

**Issue by Indigo-Coder-github** [matplotlib/matplotlib#27995]
### Bug summary

I found an issue in libraray code, so when I fix it, it works.

### Code for reproduction

```Python
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

df = pd.read_csv('weatherHistory.csv')
sns.scatterplot(data=df, x="Temperature (C)", y="Humidity")
plt.show()
```

### Actual outcome

Traceback (most recent call last):
  File "e:\학과\4학년 1학기\데이터마이닝\과제\test.py", line 6, in <module>
    sns.scatterplot(data=df, x="Temperature (C)", y="Humidity")
  File "C:\Users\LG\AppData\Roaming\Python\Python310\site-packages\seaborn\relational.py", line 626, in scatterplot
    ax = plt.gca()
  File "C:\Users\LG\AppData\Roaming\Python\Python310\site-packages\matplotlib\pyplot.py", line 2540, in gca
    return gcf().gca()
  File "C:\Users\LG\AppData\Roaming\Python\Python310\site-packages\matplotlib\pyplot.py", line 1000, in gcf
    return figure()
  File "C:\Users\LG\AppData\Roaming\Python\Python310\site-packages\matplotlib\pyplot.py", line 934, in figure
    manager = new_figure_manager(
  File "C:\Users\LG\AppData\Roaming\Python\Python310\site-packages\matplotlib\pyplot.py", line 465, in new_figure_manager
    return _get_backend_mod().new_figure_manager(*args, **kwargs)
  File "C:\Users\LG\AppData\Roaming\Python\Python310\site-packages\matplotlib\backend_bases.py", line 3411, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "C:\Users\LG\AppData\Roaming\Python\Python310\site-packages\matplotlib\backend_bases.py", line 3416, in new_figure_manager_given_figure
    return cls.FigureCanvas.new_manager(figure, num)
  File "C:\Users\LG\AppData\Roaming\Python\Python310\site-packages\matplotlib\backend_bases.py", line 1785, in new_manager
    return cls.manager_class.create_with_canvas(cls, figure, num)
  File "C:\Users\LG\AppData\Roaming\Python\Python310\site-packages\matplotlib\backend_bases.py", line 2690, in create_with_canvas
    return cls(canvas_class(figure), num)
  File "C:\Users\LG\AppData\Roaming\Python\Python310\site-packages\matplotlib\backends\backend_qt.py", line 522, in __init__
    super().__init__(canvas, num)
  File "C:\Users\LG\AppData\Roaming\Python\Python310\site-packages\matplotlib\backend_bases.py", line 2664, in __init__
    self.toolbar = self._toolbar2_class(self.canvas)
  File "C:\Users\LG\AppData\Roaming\Python\Python310\site-packages\matplotlib\backends\backend_qt.py", line 669, in __init__
    NavigationToolbar2.__init__(self, canvas)
  File "C:\Users\LG\AppData\Roaming\Python\Python310\site-packages\matplotlib\backend_bases.py", line 2859, in __init__
    self._nav_stack = cbook._Stack()
  File "C:\Users\LG\AppData\Roaming\Python\Python310\site-packages\matplotlib\_api\__init__.py", line 217, in __getattr__
    raise AttributeError(
AttributeError: module 'matplotlib.cbook' has no attribute '_Stack'. Did you mean: 'Stack'?

### Expected outcome

![Figure_1](https://github.com/matplotlib/matplotlib/assets/49811400/c6509b65-13f0-4bb9-9b4c-a2dca32552e7)

### Additional information

And I fix
`self._nav_stack = cbook._Stack()`
into
`self._nav_stack = cbook.Stack()`, it works!
Does my version have problem? or is there some mistakes in library?

### Operating system

Windows, VS Code

### Matplotlib Version

3.8.3

### Matplotlib Backend

QtAgg

### Python version

3.10.0

### Installation

pip

**Comment by jklymak** [comment]
Please uninstall and reinstall.  Somehow you have crossed versions of Matplotlib

**Comment by Indigo-Coder-github** [comment]
Uninstall and reinstall Matplotlib is worked! Thanks!
