### ISSUE TITLE
matplotlib.tests.test_basic.test_override_builtins() fails with Python >=3.4

### ISSUE THREAD

**Issue by Arfrever** [matplotlib/matplotlib#2842]
`matplotlib.tests.test_basic.test_override_builtins()` fails with Python >=3.4 due to `__spec__`.
http://docs.python.org/3.4/reference/import.html#__spec__

I use Matplotlib 1.3.1.

```
======================================================================
FAIL: matplotlib.tests.test_basic.test_override_builtins
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/tmp/matplotlib-1.3.1-tests/usr/lib64/python3.4/site-packages/matplotlib/tests/test_basic.py", line 38, in test_override_builtins
    assert not overridden
nose.proxy.AssertionError:
-------------------- >> begin captured stdout << ---------------------
'__spec__' was overridden in globals().

--------------------- >> end captured stdout << ----------------------
```

**Comment by efiring** [comment]
Closed by #2981.
