### ISSUE TITLE
[Bug]: Update Matplotlib 3.5.1 Numpy dependency

### ISSUE THREAD

**Issue by hugotomasf** [matplotlib/matplotlib#28477]
### Bug summary

When installing matplotlib==3.5.1, matplotlib (pip install matplotlib==3.5.1) has the following requirement over numpy: numpy>=1.17. Version 2.0.0 gets installed (_numpy-2.0.0-cp310-cp310-win_amd64.whl_) but, some matplotlib code can't be run over this version of numpy.

### Code for reproduction

```Python
import matplotlib.pyplot as plt
import matplotlib.animation as animation

TEMP_THRESHOLD = 40
PRESSURE_THRESHOLD = 3

temperature_data = [30, 40, 50, 60]
pressure_data = [2, 3, 4, 5]

def animate(i):
    """
    Animation function that updates the plot.
    """
    plt.cla()
    plt.scatter(temperature_data, pressure_data, c=['red' if t > TEMP_THRESHOLD or p > PRESSURE_THRESHOLD else 'green' for t, p in zip(temperature_data, pressure_data)])
    plt.xlabel('Temperature (K)')
    plt.ylabel('Pressure (Bar)')
    plt.title('Sensor Data (Red: Abnormal, Green: Normal)')

def main():
    fig = plt.figure()
    ani = animation.FuncAnimation(fig, animate, interval=1000)
 
    # Display the plot
    plt.show()

if __name__ == '__main__':
    main()
```

### Actual outcome

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "path_to\import matplotlib.py", line 1, in <module>
    import matplotlib.pyplot as plt
  File "path_to\miniconda3\envs\matplotlibtest\lib\site-packages\matplotlib\__init__.py", line 109, in <module>
    from . import _api, _version, cbook, docstring, rcsetup
  File "path_to\miniconda3\envs\matplotlibtest\lib\site-packages\matplotlib\rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "path_to\miniconda3\envs\matplotlibtest\lib\site-packages\matplotlib\colors.py", line 56, in <module>
    from matplotlib import _api, cbook, scale
  File "path_to\miniconda3\envs\matplotlibtest\lib\site-packages\matplotlib\scale.py", line 23, in <module>
    from matplotlib.ticker import (
  File "path_to\miniconda3\envs\matplotlibtest\lib\site-packages\matplotlib\ticker.py", line 136, in <module>
    from matplotlib import transforms as mtransforms
  File "path_to\miniconda3\envs\matplotlibtest\lib\site-packages\matplotlib\transforms.py", line 46, in <module>
    from matplotlib._path import (
AttributeError: _ARRAY_API not found
Traceback (most recent call last):
  File "path_to\import matplotlib.py", line 1, in <module>
    import matplotlib.pyplot as plt
  File "path_to\miniconda3\envs\matplotlibtest\lib\site-packages\matplotlib\__init__.py", line 109, in <module>
    from . import _api, _version, cbook, docstring, rcsetup
  File "path_to\miniconda3\envs\matplotlibtest\lib\site-packages\matplotlib\rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "path_to\miniconda3\envs\matplotlibtest\lib\site-packages\matplotlib\colors.py", line 56, in <module>
    from matplotlib import _api, cbook, scale
  File "path_to\miniconda3\envs\matplotlibtest\lib\site-packages\matplotlib\scale.py", line 23, in <module>
    from matplotlib.ticker import (
  File "path_to\miniconda3\envs\matplotlibtest\lib\site-packages\matplotlib\ticker.py", line 136, in <module>
    from matplotlib import transforms as mtransforms
  File "path_to\miniconda3\envs\matplotlibtest\lib\site-packages\matplotlib\transforms.py", line 46, in <module>
    from matplotlib._path import (
ImportError: numpy.core.multiarray failed to import

### Expected outcome

![image](https://github.com/matplotlib/matplotlib/assets/79416297/9ee2dfca-1dad-4d27-b02b-53c14687bb3f)

This outcome is achieved by downgrading numpy to 1.26.4

### Additional information

This problem can be solved by downgrading numpy to 1.26.4.

### Operating system

Windows 11 Pro

### Matplotlib Version

3.5.1

### Matplotlib Backend

TkAgg

### Python version

Python 3.10.14

### Jupyter version

N/A

### Installation

pip

**Comment by tacaswell** [comment]
This is not strictly due to an API issue (Matplotlib has code that no longer runs with numpy2) but an ABI issue (the c-extensions are not compatible) so built binary artifacts in the wheel is not compatible.  Numpy is failing on import to give you a nice error rather than segfaulting later.

Unfortunately due to limitations of pip/pypi there is no way we can update the pinning of the wheels.  If you are going to pin Matplotlib back to an old version, then you will need to also pin back numpy.  Newer versions of Matplotlib (I think starting with 3.8) are built with numpy2 and should not have this problem.

If you really need to use both mpl 3.5.1 and numpy2 you can try installing Matplotlib from source (`pip install matplotlib==3.5.1 --no-binary=matplotlib` ) but I do not know if anyone has tested that combinations of versions (and we may _also_ have some API issues that have been subsequently fixed).
