### ISSUE TITLE
Error while saving as "pdf" file in redhat linux

### ISSUE THREAD

**Issue by Raamkrishnan** [matplotlib/matplotlib#28556]
Hi,

I have installed matplotlib in the redhat linux system and it seems to be working fine except for saving the file as pdf. I tried saving the file as "jpg". It works fine. Following are the error that I get from the terminal:
```
Traceback (most recent call last):
  File "postprocess.py", line 101, in <module>
    plt.savefig('dynamic.pdf')
  File "/usr/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 689, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/matplotlib/figure.py", line 2094, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/usr/lib64/python3.6/site-packages/matplotlib/backend_bases.py", line 2075, in print_figure
    **kwargs)
  File "/usr/lib64/python3.6/site-packages/matplotlib/backends/backend_pdf.py", line 2565, in print_pdf
    self.figure.draw(renderer)
  File "/usr/lib64/python3.6/site-packages/matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/matplotlib/figure.py", line 1649, in draw
    renderer, self, artists, self.suppressComposite)
  File "/usr/lib64/python3.6/site-packages/matplotlib/image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/lib64/python3.6/site-packages/matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/matplotlib/axes/_base.py", line 2628, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/usr/lib64/python3.6/site-packages/matplotlib/image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/lib64/python3.6/site-packages/matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/matplotlib/axis.py", line 1190, in draw
    tick.draw(renderer)
  File "/usr/lib64/python3.6/site-packages/matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/matplotlib/axis.py", line 304, in draw
    self.label1.draw(renderer)
  File "/usr/lib64/python3.6/site-packages/matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/matplotlib/text.py", line 754, in draw
    mtext=mtext)
  File "/usr/lib64/python3.6/site-packages/matplotlib/backends/backend_pdf.py", line 1916, in draw_tex
    pdfname = self.file.dviFontName(dvifont)
  File "/usr/lib64/python3.6/site-packages/matplotlib/backends/backend_pdf.py", line 675, in dviFontName
    tex_font_map = dviread.PsfontsMap(dviread.find_tex_file('pdftex.map'))
  File "/usr/lib64/python3.6/site-packages/matplotlib/dviread.py", line 822, in __new__
    with open(filename, 'rb') as file:
FileNotFoundError: [Errno 2] No such file or directory: ''
```

By the way, I have run the same script in mac and windows. The codes runs fine. Is there any package that I am missing here for the linux? 

Thank you.

Best,
Rama

**Comment by oscargus** [comment]
I'm guessing that you are using Matplotlib 3.5 or earlier since 3.6 and later are raising an error saying that `pdftex.map` is not found (if I read the source and changes correctly).

Hence, the solution, I assume, is to make sure that `pdflatex` is installed.  

You may also want to update Matplotlib, although that will require updating Python to, at least, 3.9.

**Comment by Raamkrishnan** [comment]
Thank you. I have Python 3.6.8 in my system. I will install ```pdflatex``` and try.
