### ISSUE TITLE
Request to support PostScript-flavoured (CFF) OpenType fonts in PDF backend

### ISSUE THREAD

**Issue by mojca** [matplotlib/matplotlib#2869]
I would like to request support for OpenType fonts. I have the main text written with Lucida and I'm unable to get the font on the graphs match the ones in the text.

I'm using the latest matplotlib with Python 3.3 on Mac OS X 10.7. When I try to use any give OpenType font

```
matplotlib.rcParams['font.family'] = 'Any Name Of OpenType Font'
```

this is what I get:

```
Traceback (most recent call last):
  File "test.py", line 26, in <module>
    plt.savefig('test.pdf')
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/matplotlib/pyplot.py", line 571, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/matplotlib/figure.py", line 1448, in savefig
    self.canvas.print_figure(*args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/matplotlib/backend_bases.py", line 2192, in print_figure
    **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/matplotlib/backends/backend_pdf.py", line 2476, in print_pdf
    file.close()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/matplotlib/backends/backend_pdf.py", line 528, in close
    self.writeFonts()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/matplotlib/backends/backend_pdf.py", line 631, in writeFonts
    fonts[Fx] = self.embedTTF(realpath, chars[1])
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/matplotlib/backends/backend_pdf.py", line 1106, in embedTTF
    return embedTTFType3(font, characters, descriptor)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/matplotlib/backends/backend_pdf.py", line 892, in embedTTFType3
    filename.encode(sys.getfilesystemencoding()), glyph_ids)
RuntimeError: TrueType font is missing table
```

The weird thing is that my colleagues get a different warning (complaining that font substitution isn't supported and then some garbled output).

The problem is that apparently backend_pdf.py is only taking
into account:
-  *.afm fonts
- something with dvi info (which came from TeX)
- everything else is treated as TTF, so it goes though ttconv which apparently isn't able to handle PostScript-flavoured fonts

The interactive display and PNG work just fine, but I would like to have vector graphics.

I then tried to fetch a TrueType version of Lucida from Java, but that one behaves weird enough that I'm unable to use it (I'll open a new issue for that). I also experienced something very very odd – fonts from those fonts are rendered on our high end laser printer as if they were high resolution bitmap images, somewhat fuzzy. Fonts from gnuplot graphics and the rest of text is crisp clear, while text from pyplot graphs is somewhat smoothed at the edges, it looks like rasterized or weirdly hinted font.

An alternative would be to render the text labels through TeX, but I don't know how to set it up for (OpenType) Lucida fonts. (I know how to set it up outside of matplotlib.)

A slightly related issue is #1366. It would be great if pyplot supported OpenType Math fonts indeed, like Latin Modern Math, XITS Math, TeX Gyre Math (basically Helvetica, Times, Palatino, Bookman), Lucida Bright Math, Cambria, ...

**Comment by petehuang** [comment]
Just tossing in an update: doesn't seem like there's been any movement, please comment if otherwise

**Comment by anntzer** [comment]
If you're still interested: the https://github.com/anntzer/mplcairo backend should support all reasonably common font formats.

**Comment by mojca** [comment]
Still interested

**Comment by oscargus** [comment]
There seems to be alternative bindings now: https://pypi.org/project/freetype-py/

**Comment by QuLogic** [comment]
`ttconv` was replaced in #20866, but without a specific (non-proprietary) font to test, I cannot confirm whether this is working or not, but I suspect it was fixed.

**Comment by lstngr** [comment]
I'm also interested in this! The situation seems to have improved since the ticket was opened (a PDF is generated), but the resulting file appears to be malformed?

In particular, many LaTeX OTF fonts (distributed by, e.g., TeXLive) seem to originate from a Postscript format and trigger this error:

```python
import matplotlib as mpl
import matplotlib.pyplot as plt

# A copy of TeX Gyre Heros can also be found here: https://www.gust.org.pl/projects/e-foundry/tex-gyre/heros
mpl.rcdefaults()
mpl.rcParams["pdf.fonttype"] = 42
mpl.rcParams["font.sans-serif"] = ["TeX Gyre Heros"] + mpl.rcParamsDefault["font.sans-serif"]

plt.subplots()
plt.savefig("/tmp/text.pdf")
```

Executing `pdffonts /tmp/text.pdf` yields:

```
Syntax Warning: Mismatch between font type and embedded font file
name                                 type              encoding         emb sub uni object ID
------------------------------------ ----------------- ---------------- --- --- --- ---------
CCVYUO+TeXGyreHeros-Regular          CID Type 0C (OT)  Identity-H       yes yes yes     15  0
```

If the default font, DejaVu Sans, is used, the output is:

```
name                                 type              encoding         emb sub uni object ID
------------------------------------ ----------------- ---------------- --- --- --- ---------
BMQQDV+DejaVuSans                    CID TrueType      Identity-H       yes yes yes     15  0
```

In the current Matplotlib version, this seems to be due to the following [backend location](https://github.com/matplotlib/matplotlib/blob/9da2022dccf1bae213c4a44985dab89d4bac9229/lib/matplotlib/backends/backend_pdf.py#L1312), which hardcodes the font type when Opentype output is requested. In this backend, CIDFontType2 supposedly indicates the font is in Truetype format.
The hardcoded behavior can be checked by decompressing the output PDF:

```
# pdftk /tmp/text.pdf output /tmp/text-uncompr.pdf uncompress
# grep -aC3 CID /tmp/text-uncompr.pdf
15 0 obj

<<
/Subtype /CIDFontType2
/CIDSystemInfo 
<<
/Supplement 0
/Registry (Adobe)
--
/BaseFont /CCVYUO+TeXGyreHeros-Regular
/FontDescriptor 13 0 R
/W 16 0 R
/CIDToGIDMap 17 0 R
>>
endobj

--
/Length 460
>>
stream
/CIDInit /ProcSet findresource begin
12 dict begin
begincmap
/CIDSystemInfo
<< /Registry (Adobe)
   /Ordering (UCS)
   /Supplement 0
```

I'm far from knowledgeable on this topic, so I hope my conclusions are not erroneous and that this helps!
