### ISSUE TITLE
feature request: support passing DataFrames to table.table

### ISSUE THREAD

**Issue by dawnwangcx** [matplotlib/matplotlib#28726]
### Bug summary

When trying to input a dataframe to a table, it will raise keyerror. Since cellText [0] will not give the first row of the dataframe and thus not returning the correct column length. So, I made a modification to recognize cellText as dataframe.
contact: chenxuw@alumni.cmu.edu

### Code for reproduction

```Python
df = pd.DataFrame() #any dataframe
table = table.table(ax,df,loc='center')
```

### Actual outcome

Traceback (most recent call last):
  File "C:\Users\053232\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\indexes\base.py", line 3653, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:/Users/Downloads/suspension_check.py", line 147, in <module>
    generate_image(suspended_etfs,'suspended_etfs')
  File "c:/Users/Downloads/suspension_check.py", line 106, in generate_image
    tbl = table.table(ax, df, loc='center')
  File "C:\Users\AppData\Local\Programs\Python\Python38\lib\site-packages\matplotlib\table.py", line 754, in table
    cols = len(cellText[0])
  File "C:\Users\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\frame.py", line 3761, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Users\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\indexes\base.py", line 3655, in get_loc
    raise KeyError(key) from err
KeyError: 0

### Expected outcome

 return a table contains a dataframe 

### Additional information

# Check we have some cellText
    if cellText is None:
        # assume just colours are needed
        rows = len(cellColours)
        cols = len(cellColours[0])
        cellText = [[''] * cols] * rows
    elif isinstance(cellText, pd.DataFrame):
        # 获取DataFrame的列名
        column_names = cellText.columns.values
        cellText = np.vstack([column_names, cellText.values])

### Matplotlib Version

3.7.5

### Installation

pip

**Comment by tacaswell** [comment]
I would not consider this a bug a the input is documented as a 2D list of strings (https://matplotlib.org/stable/api/table_api.html#matplotlib.table.table) .

That said, this may be a reasonable feature request as I don't think it would be too hard to detect if we were passed a `pd.DataFrame` and then convert it to a list-of-list-of-str at the top of `table.table`.

**Comment by timhoffm** [comment]
@dawnwangcx You are welcome to submit you proposal as a pull request.

**Comment by StefRe** [comment]
This is what [`pandas.plotting.table`](https://pandas.pydata.org/docs/reference/api/pandas.plotting.table.html) was made for. Is it necessary to reinvent the wheel at the possible expense of an additional dependency here?

**Comment by timhoffm** [comment]
I wasn't aware of this. Nevertheless, I think it's nice to support this natively in matplotlib:

- It saves the user from having to know about `pandas.plotting.table`
- It's really just a handful of lines to implement
- With the discussed pattern, we don't add a dependency.
