### ISSUE TITLE
[MNT]: Broken compatibility with numpy 2.1.*

### ISSUE THREAD

**Issue by Elimiriel** [matplotlib/matplotlib#28804]
### Summary

Numpy warned me about compatibility before but worked with the other module not matplotlib, but it has became error after manual update by me in 24.09.11, via pip. numpy: 2.1.1, matplotlib: 3.9.2, installed through anaconda but I updated them in manual and using VS Code. Sorry for lack of experience about using github even my account is a old one.

**Detailed error messages**

1. _from numpy:_

Traceback (most recent call last):
ImportError                               Traceback (most recent call last)
File c:\ProgramData\anaconda3\Lib\site-packages\numpy\core\_multiarray_umath.py:44, in __getattr__(attr_name)
     [39](file:///C:/ProgramData/anaconda3/Lib/site-packages/numpy/core/_multiarray_umath.py:39)     # Also print the message (with traceback).  This is because old versions
     [40](file:///C:/ProgramData/anaconda3/Lib/site-packages/numpy/core/_multiarray_umath.py:40)     # of NumPy unfortunately set up the import to replace (and hide) the
     [41](file:///C:/ProgramData/anaconda3/Lib/site-packages/numpy/core/_multiarray_umath.py:41)     # error.  The traceback shouldn't be needed, but e.g. pytest plugins
     [42](file:///C:/ProgramData/anaconda3/Lib/site-packages/numpy/core/_multiarray_umath.py:42)     # seem to swallow it and we should be failing anyway...
     [43](file:///C:/ProgramData/anaconda3/Lib/site-packages/numpy/core/_multiarray_umath.py:43)     sys.stderr.write(msg + tb_msg)
---> [44](file:///C:/ProgramData/anaconda3/Lib/site-packages/numpy/core/_multiarray_umath.py:44)     raise ImportError(msg)

2. _From matplotlib:_

ImportError                               Traceback (most recent call last)
ImportError: numpy.core.multiarray failed to import

The above exception was the direct cause of the following exception:

ImportError                               Traceback (most recent call last)
Cell In[3], [line 3](vscode-notebook-cell:?execution_count=3&line=3)
      [1](vscode-notebook-cell:?execution_count=3&line=1) import numpy as np;
      [2](vscode-notebook-cell:?execution_count=3&line=2) import torch;
----> [3](vscode-notebook-cell:?execution_count=3&line=3) import matplotlib.pyplot as plt;
      [4](vscode-notebook-cell:?execution_count=3&line=4) import scipy;
      [5](vscode-notebook-cell:?execution_count=3&line=5) import torch.nn as nn;

File c:\ProgramData\anaconda3\Lib\site-packages\matplotlib\__init__.py:159
    [155](file:///C:/ProgramData/anaconda3/Lib/site-packages/matplotlib/__init__.py:155) from packaging.version import parse as parse_version
    [157](file:///C:/ProgramData/anaconda3/Lib/site-packages/matplotlib/__init__.py:157) # cbook must import matplotlib only within function
    [158](file:///C:/ProgramData/anaconda3/Lib/site-packages/matplotlib/__init__.py:158) # definitions, so it is safe to import from it here.
--> [159](file:///C:/ProgramData/anaconda3/Lib/site-packages/matplotlib/__init__.py:159) from . import _api, _version, cbook, _docstring, rcsetup
    [160](file:///C:/ProgramData/anaconda3/Lib/site-packages/matplotlib/__init__.py:160) from matplotlib.cbook import sanitize_sequence
    [161](file:///C:/ProgramData/anaconda3/Lib/site-packages/matplotlib/__init__.py:161) from matplotlib._api import MatplotlibDeprecationWarning

File c:\ProgramData\anaconda3\Lib\site-packages\matplotlib\rcsetup.py:28
     [26](file:///C:/ProgramData/anaconda3/Lib/site-packages/matplotlib/rcsetup.py:26) from matplotlib.backends import BackendFilter, backend_registry
     [27](file:///C:/ProgramData/anaconda3/Lib/site-packages/matplotlib/rcsetup.py:27) from matplotlib.cbook import ls_mapper
---> [28](file:///C:/ProgramData/anaconda3/Lib/site-packages/matplotlib/rcsetup.py:28) from matplotlib.colors import Colormap, is_color_like
     [29](file:///C:/ProgramData/anaconda3/Lib/site-packages/matplotlib/rcsetup.py:29) from matplotlib._fontconfig_pattern import parse_fontconfig_pattern
     [30](file:///C:/ProgramData/anaconda3/Lib/site-packages/matplotlib/rcsetup.py:30) from matplotlib._enums import JoinStyle, CapStyle

File c:\ProgramData\anaconda3\Lib\site-packages\matplotlib\colors.py:57
     [55](file:///C:/ProgramData/anaconda3/Lib/site-packages/matplotlib/colors.py:55) import matplotlib as mpl
     [56](file:///C:/ProgramData/anaconda3/Lib/site-packages/matplotlib/colors.py:56) import numpy as np
---> [57](file:///C:/ProgramData/anaconda3/Lib/site-packages/matplotlib/colors.py:57) from matplotlib import _api, _cm, cbook, scale
     [58](file:///C:/ProgramData/anaconda3/Lib/site-packages/matplotlib/colors.py:58) from ._color_data import BASE_COLORS, TABLEAU_COLORS, CSS4_COLORS, XKCD_COLORS
     [61](file:///C:/ProgramData/anaconda3/Lib/site-packages/matplotlib/colors.py:61) class _ColorMapping(dict):

File c:\ProgramData\anaconda3\Lib\site-packages\matplotlib\scale.py:22
     [20](file:///C:/ProgramData/anaconda3/Lib/site-packages/matplotlib/scale.py:20) import matplotlib as mpl
     [21](file:///C:/ProgramData/anaconda3/Lib/site-packages/matplotlib/scale.py:21) from matplotlib import _api, _docstring
---> [22](file:///C:/ProgramData/anaconda3/Lib/site-packages/matplotlib/scale.py:22) from matplotlib.ticker import (
     [23](file:///C:/ProgramData/anaconda3/Lib/site-packages/matplotlib/scale.py:23)     NullFormatter, ScalarFormatter, LogFormatterSciNotation, LogitFormatter,
     [24](file:///C:/ProgramData/anaconda3/Lib/site-packages/matplotlib/scale.py:24)     NullLocator, LogLocator, AutoLocator, AutoMinorLocator,
     [25](file:///C:/ProgramData/anaconda3/Lib/site-packages/matplotlib/scale.py:25)     SymmetricalLogLocator, AsinhLocator, LogitLocator)
     [26](file:///C:/ProgramData/anaconda3/Lib/site-packages/matplotlib/scale.py:26) from matplotlib.transforms import Transform, IdentityTransform
     [29](file:///C:/ProgramData/anaconda3/Lib/site-packages/matplotlib/scale.py:29) class ScaleBase:

File c:\ProgramData\anaconda3\Lib\site-packages\matplotlib\ticker.py:144
    [142](file:///C:/ProgramData/anaconda3/Lib/site-packages/matplotlib/ticker.py:142) import matplotlib as mpl
    [143](file:///C:/ProgramData/anaconda3/Lib/site-packages/matplotlib/ticker.py:143) from matplotlib import _api, cbook
--> [144](file:///C:/ProgramData/anaconda3/Lib/site-packages/matplotlib/ticker.py:144) from matplotlib import transforms as mtransforms
    [146](file:///C:/ProgramData/anaconda3/Lib/site-packages/matplotlib/ticker.py:146) _log = logging.getLogger(__name__)
    [148](file:///C:/ProgramData/anaconda3/Lib/site-packages/matplotlib/ticker.py:148) __all__ = ('TickHelper', 'Formatter', 'FixedFormatter',
    [149](file:///C:/ProgramData/anaconda3/Lib/site-packages/matplotlib/ticker.py:149)            'NullFormatter', 'FuncFormatter', 'FormatStrFormatter',
    [150](file:///C:/ProgramData/anaconda3/Lib/site-packages/matplotlib/ticker.py:150)            'StrMethodFormatter', 'ScalarFormatter', 'LogFormatter',
   (...)
    [156](file:///C:/ProgramData/anaconda3/Lib/site-packages/matplotlib/ticker.py:156)            'MultipleLocator', 'MaxNLocator', 'AutoMinorLocator',
    [157](file:///C:/ProgramData/anaconda3/Lib/site-packages/matplotlib/ticker.py:157)            'SymmetricalLogLocator', 'AsinhLocator', 'LogitLocator')

File c:\ProgramData\anaconda3\Lib\site-packages\matplotlib\transforms.py:49
     [46](file:///C:/ProgramData/anaconda3/Lib/site-packages/matplotlib/transforms.py:46) from numpy.linalg import inv
     [48](file:///C:/ProgramData/anaconda3/Lib/site-packages/matplotlib/transforms.py:48) from matplotlib import _api
---> [49](file:///C:/ProgramData/anaconda3/Lib/site-packages/matplotlib/transforms.py:49) from matplotlib._path import (
     [50](file:///C:/ProgramData/anaconda3/Lib/site-packages/matplotlib/transforms.py:50)     affine_transform, count_bboxes_overlapping_bbox, update_path_extents)
     [51](file:///C:/ProgramData/anaconda3/Lib/site-packages/matplotlib/transforms.py:51) from .path import Path
     [53](file:///C:/ProgramData/anaconda3/Lib/site-packages/matplotlib/transforms.py:53) DEBUG = False

ImportError: initialization failed

3. _Extras-other modules included, last 6 lines are about matplotlib:_

  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\ProgramData\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "c:\ProgramData\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "c:\ProgramData\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 739, in start
    self.io_loop.start()
  File "c:\ProgramData\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "c:\ProgramData\anaconda3\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "c:\ProgramData\anaconda3\Lib\asyncio\base_events.py", line 1987, in _run_once
    handle._run()
  File "c:\ProgramData\anaconda3\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "c:\ProgramData\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 545, in dispatch_queue
    await self.process_one()
  File "c:\ProgramData\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in process_one
    await dispatch(*args)
  File "c:\ProgramData\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 437, in dispatch_shell
    await result
  File "c:\ProgramData\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 362, in execute_request
    await super().execute_request(stream, ident, parent)
  File "c:\ProgramData\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 778, in execute_request
    reply_content = await reply_content
  File "c:\ProgramData\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 449, in do_execute
    res = shell.run_cell(
  File "c:\ProgramData\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "c:\ProgramData\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "c:\ProgramData\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "c:\ProgramData\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "c:\ProgramData\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "c:\ProgramData\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "c:\ProgramData\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\elimi\AppData\Local\Temp\ipykernel_11220\1158092262.py", line 3, in <module>
    import matplotlib.pyplot as plt;
  File "c:\ProgramData\anaconda3\Lib\site-packages\matplotlib\__init__.py", line 159, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File "c:\ProgramData\anaconda3\Lib\site-packages\matplotlib\rcsetup.py", line 28, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "c:\ProgramData\anaconda3\Lib\site-packages\matplotlib\colors.py", line 57, in <module>
    from matplotlib import _api, _cm, cbook, scale
  File "c:\ProgramData\anaconda3\Lib\site-packages\matplotlib\scale.py", line 22, in <module>
    from matplotlib.ticker import (
  File "c:\ProgramData\anaconda3\Lib\site-packages\matplotlib\ticker.py", line 144, in <module>
    from matplotlib import transforms as mtransforms
  File "c:\ProgramData\anaconda3\Lib\site-packages\matplotlib\transforms.py", line 49, in <module>
    from matplotlib._path import (

### Proposed fix

Suggestion from numpy:

> A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

I'm a newbie in programming field, so sorry about the lack of my proposals. My incomplete code doesn't require matplotlib in debugging stage in now, but requires this module for checking results.

**Comment by ksunden** [comment]
I believe that this is purely downstream packaging within the anaconda (main) repos, which only within the last week has uploaded numpy 2.0, and the latest version of matplotlib is 2 days older. I _think_ that them updating their version of matplotlib to be built with the current version of numpy would fix it, but they were building with the version of numpy in anaconda at the time of the last release.

The version of matplotlib we uploaded to pypi as a wheel is built with Numpy 2 and therefore this is not a problem.

Additionally, conda forge should have Matplotlib built with numpy 2.0.

In general, mixing conda and pip often leads to problems like this, where the compilation version and runtime version of libraries are incompatible.

I do not believe there is any action we can take in this repository to address this problem, as it is purely about compile time environment, which we do not control for Anaconda.
