### ISSUE TITLE
[Bug]: plt.imshow raises KeyError: 'changed'  in a multiprocessing setup

### ISSUE THREAD

**Issue by Alex17Li** [matplotlib/matplotlib#29082]
### Bug summary

plt.imshow sometimes raises KeyError: 'changed' when called from many processes at once. Though typically the code runs fine, when trying to plot many images in parallel for a long time, there will be occasional caught exceptions and a even rarer uncaught exception (after 1000s of images it only sometimes appears).

### Code for reproduction

This may be hard to reproduce. For one thing you need a dataframe with thousands of saved images and for another it might not even fail. The images we use have size 256x512.

<details>
  <summary>
Reproducing is too hard for me to give you a truly minimal example, I think the problem is in the multiprocessing part more than the code since we are just plotting a few images on a plt.subplots object. I will share the full code though.
</summary>

```Python
from enum import Enum
from pathlib import Path
from typing import Dict, Iterable, List, Mapping, Optional, Union

import matplotlib
import matplotlib.pyplot as plt
import numpy as np

classlabels_viz_colors = [
    "green",
    "yellow",
    "blue",
    "red",
    "magenta",
    "cyan",
    "lightseagreen",
    "brown",
    "rebeccapurple",
    "olive",
    "wheat",
    "black",
    "white",  # Ignored labels mapped to white so that they do not change color when masked - we don't care about them either way, so a color change does not make sense
]

classlabels_viz_bounds = list(range(len(classlabels_viz_colors)))
IGNORE_LABEL_COLOR_INDEX = len(classlabels_viz_bounds) - 1
assert len(classlabels_viz_bounds) == len(classlabels_viz_colors)

classlabels_viz_cmap = matplotlib.colors.ListedColormap(classlabels_viz_colors)
classlabels_viz_norm = matplotlib.colors.BoundaryNorm(
    classlabels_viz_bounds, classlabels_viz_cmap.N
)

confidence_heatmap_viz_colors = [
    "white",
    "blue",
    "red",
    "orange",
    "yellow",
    "lightgreen",
    "lightseagreen",
]

HEATMAP_VIZ_BOUNDS_HIGH_INTERESTING = [
    -1,
    0,
    0.5,
    0.6,
    0.7,
    0.8,
    0.9,
    1,
]  # High confidence values are interesting
HEATMAP_VIZ_BOUNDS_LOW_INTERESTING = [
    0,
    0.05,
    0.1,
    0.15,
    0.2,
    0.25,
    0.3,
    1,
]  # Low confidence values are interesting


def plot_patch(ax: plt.Axes, label_ind: int, detections_info: Iterable[Dict]) -> None:
    color = (
        classlabels_viz_colors[label_ind]
        if label_ind >= 0
        else classlabels_viz_colors[IGNORE_LABEL_COLOR_INDEX]
    )
    for cur_detection_info in detections_info:
        min_row, min_col, max_row, max_col = (
            cur_detection_info["y_min"],
            cur_detection_info["x_min"],
            cur_detection_info["y_max"],
            cur_detection_info["x_max"],
        )
        shortest_side = min(max_col - min_col + 1, max_row - min_row + 1)
        ax.add_patch(
            matplotlib.patches.Rectangle(
                (min_col, min_row),
                (max_col - min_col + 1),
                (max_row - min_row + 1),
                linewidth=np.clip(
                    shortest_side // 6, 1, 3
                ),  # for small objects a large linewidth can obsure the image
                edgecolor=matplotlib.colors.to_rgba(color, 0.8),
                facecolor=matplotlib.colors.to_rgba(color, 0.0),
            )
        )


def create_mpl_viz_outputs(
    image: np.ndarray,
    output_path: Optional[Union[str, Path]],
    prediction_labels: np.ndarray,
    groundtruth_labels: Optional[np.ndarray] = None,
    confidences: Optional[np.ndarray] = None,
    depth_img: Optional[np.ndarray] = None,
    depth_clip_threshold: Optional[float] = None,
    depth_clip_lower_threshold: float = 0.0,
    labeled_object_bbox: Optional[Mapping[int, Iterable[Dict]]] = None,
    predicted_object_bbox: Optional[Mapping[int, Iterable[Dict]]] = None,
    label_mask: Optional[np.ndarray] = None,
    pred_mask: Optional[np.ndarray] = None,
    lr_consistency_mask: Optional[np.ndarray] = None,
    confidence_heatmap_viz_bounds: Optional[List[float]] = None,

    raw_left_image: Optional[np.ndarray] = None,
    raw_right_image: Optional[np.ndarray] = None,
) -> None:
    """
    Utility function to plot results based on order of input provided.

    Axes index can have different values based on input provided.

    For example: If image, prediction and groundtruth_label is provided, A three axes plot will be generated with
    image(ax1), ground_truth(ax2), prediction(ax3).

    Order of plot if all the inputs are provided will be in same order as arguments listed above.
    """
    if confidence_heatmap_viz_bounds is None:
        confidence_heatmap_viz_bounds = HEATMAP_VIZ_BOUNDS_HIGH_INTERESTING
        assert len(confidence_heatmap_viz_bounds) == len(confidence_heatmap_viz_colors) + 1
    confidence_heatmap_viz_cmap = matplotlib.colors.ListedColormap(confidence_heatmap_viz_colors)
    confidence_heatmap_viz_norm = matplotlib.colors.BoundaryNorm(
        confidence_heatmap_viz_bounds, confidence_heatmap_viz_cmap.N
    )
    ax_inds: Dict[str, int] = {}
    for name, value in [
        ("Rectified Image", image),
        ("Raw Left Image", raw_left_image),
        ("Raw Right Image", raw_right_image),
        ("Depth", depth_img),
        ("LR Consistency Mask", lr_consistency_mask),
        ("Groundtruth", groundtruth_labels),
        ("Prediction", prediction_labels),
        ("Confidences", confidences),
    ]:
        if value is not None:
            ax_inds[name] = len(ax_inds)
    axes: List[plt.Axes]
    fig, axes = plt.subplots(1, len(ax_inds), figsize=((8 * len(ax_inds), 6)))  # type: ignore
    for name, ind in ax_inds.items():
        axes[ind].set_title(name)

    # Reduce the alpha value for masked elements should be less visible
    if label_mask is not None:
        label_alpha = np.where(label_mask, 0.15, 1.0)
    else:
        label_alpha = None

    if pred_mask is not None:
        pred_alpha = np.where(pred_mask, 0.15, 1.0)
    else:
        pred_alpha = None

    if "Rectified Image" in ax_inds:
        # Grab only RGB channels from image, otherwise depth with distort the image when it is displayed
        axes[ax_inds["Rectified Image"]].imshow(image[:, :, 0:3])
        for label_ind, detection_info in predicted_object_bbox.items():
            plot_patch(axes[ax_inds["Rectified Image"]], int(label_ind), detection_info)
    if "Raw Left Image" in ax_inds:
        axes[ax_inds["Raw Left Image"]].imshow(raw_left_image)
    if "Raw Right Image" in ax_inds:
        axes[ax_inds["Raw Right Image"]].imshow(raw_right_image)
    if "LR Consistency Mask" in ax_inds:
        axes[ax_inds["LR Consistency Mask"]].imshow(lr_consistency_mask)
        for label_ind, detection_info in predicted_object_bbox.items():
            plot_patch(axes[ax_inds["LR Consistency Mask"]], int(label_ind), detection_info)

    if "Depth" in ax_inds:
        if depth_clip_threshold:
            depth_img = np.where(depth_img > depth_clip_threshold, depth_clip_threshold, depth_img)
            depth_img = np.where(
                depth_img < depth_clip_lower_threshold, depth_clip_lower_threshold, depth_img
            )
            title = f"Depth clamped between {round(depth_clip_lower_threshold) * 100} and {round(depth_clip_threshold*100)}m"
            axes[ax_inds["Depth"]].set_title(title)
        axes[ax_inds["Depth"]].imshow(depth_img, cmap="turbo")
        for label_ind, detection_info in predicted_object_bbox.items():
            plot_patch(axes[ax_inds["Depth"]], int(label_ind), detection_info)

    if "Groundtruth" in ax_inds:
        ax = axes[ax_inds["Groundtruth"]]
        groundtruth_labels = np.where(
            groundtruth_labels == 255, IGNORE_LABEL_COLOR_INDEX, groundtruth_labels
        )
        groundtruth_labels = np.where(
            groundtruth_labels == -1, IGNORE_LABEL_COLOR_INDEX, groundtruth_labels
        )
        assert (
            0 <= np.max(groundtruth_labels) < classlabels_viz_cmap.N
        )
        ax.imshow( # NOTE: The exception below is crashing at this line
            groundtruth_labels,
            cmap=classlabels_viz_cmap,
            norm=classlabels_viz_norm,
            interpolation="nearest",
            alpha=label_alpha,
        )
        for label_ind, detection_info in labeled_object_bbox.items():
            plot_patch(ax, int(label_ind), detection_info)

    if "Prediction" in ax_inds:
        ax = axes[ax_inds["Prediction"]]
        prediction_labels = np.where(
            prediction_labels == -1, IGNORE_LABEL_COLOR_INDEX, prediction_labels
        )
        assert (
            0 <= np.max(prediction_labels) < classlabels_viz_cmap.N
        )  # Failure to abhere will make some colors change unpredicatably
        ax.imshow(
            prediction_labels,
            cmap=classlabels_viz_cmap,
            norm=classlabels_viz_norm,
            interpolation="nearest",
            alpha=pred_alpha,
        )
        for label_ind, detection_info in predicted_object_bbox.items():
            plot_patch(ax, int(label_ind), detection_info)

    if "Confidences" in ax_inds:
        if len(confidences.shape) > 2:
            confidences = np.max(confidences, axis=2)
        axes[ax_inds["Confidences"]].imshow(
            confidences,
            confidence_heatmap_viz_cmap,
            confidence_heatmap_viz_norm,
            interpolation="nearest",
        )
        for label_ind, detection_info in predicted_object_bbox.items():
            plot_patch(axes[ax_inds["Confidences"]], int(label_ind), detection_info)

    if output_path is not None:
        fig.savefig(output_path, pad_inches=0, bbox_inches="tight", dpi=75)
        plt.close(fig)
    return fig

```

Outer loop:
```
pandarallel.initialize(nb_workers=self.num_workers)
# I am not giving you this huge df because the images + data cannot be shared. Plus it is massive.
self.master_annotations_df.apply(
                lambda row: self.evaluate_one_frame(row), axis=1
            )
... somewhere in self.evaluate_one_frame, we call create_mpl_viz_outputs()

```
</details>

### Actual outcome

Sometimes, everything runs fine. Especially if there are only a few ~100 images. With more images, we get some caught exceptions. With lots of images and bad luck, the code can crash. 

Caught exceptions

```
INFO: Pandarallel will run on 20 workers.
INFO: Pandarallel will use Memory file system to transfer data between the main process and workers.
Exception ignored in: <function WeakMethod.__new__.<locals>._cb at 0x74b7b8cbe440>
Traceback (most recent call last):
  File "/ci_cache/bazel_root_integration28/bb1c596d129cbbfac12269b41131c80b/external/python_x86_64-unknown-linux-gnu/lib/python3.10/weakref.py", line 61, in _cb
    callback(self)
  File "/ci_cache/bazel_root_integration28/bb1c596d129cbbfac12269b41131c80b/execroot/com_bluerivertech/bazel-out/k8-opt/bin/autonomy/jupiter/embedded_safety_metrics/create_summary.runfiles/pip_matplotlib/site-packages/matplotlib/cbook/__init__.py", line 239, in _remove_proxy
    del self.callbacks[signal][cid]
KeyError: 'changed'
Exception ignored in: <function WeakMethod.__new__.<locals>._cb at 0x74b7b8cbe8c0>
Traceback (most recent call last):
  File "/ci_cache/bazel_root_integration28/bb1c596d129cbbfac12269b41131c80b/external/python_x86_64-unknown-linux-gnu/lib/python3.10/weakref.py", line 61, in _cb
    callback(self)
  File "/ci_cache/bazel_root_integration28/bb1c596d129cbbfac12269b41131c80b/execroot/com_bluerivertech/bazel-out/k8-opt/bin/autonomy/jupiter/embedded_safety_metrics/create_summary.runfiles/pip_matplotlib/site-packages/matplotlib/cbook/__init__.py", line 239, in _remove_proxy
    del self.callbacks[signal][cid]
KeyError: 'changed'
(repeats many times)
```

Uncaught Exception

```
INFO: Pandarallel will run on 20 workers.
INFO: Pandarallel will use Memory file system to transfer data between the main process and workers.
multiprocessing.pool.RemoteTraceback: 

Traceback (most recent call last):
  File "/ci_cache/bazel_root_integration27/bb1c596d129cbbfac12269b41131c80b/external/python_x86_64-unknown-linux-gnu/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/ci_cache/bazel_root_integration27/bb1c596d129cbbfac12269b41131c80b/external/python_x86_64-unknown-linux-gnu/lib/python3.10/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/ci_cache/bazel_root_integration27/bb1c596d129cbbfac12269b41131c80b/execroot/com_bluerivertech/bazel-out/k8-opt/bin/autonomy/jupiter/embedded_safety_metrics/create_summary.runfiles/pip_pandarallel/site-packages/pandarallel/core.py", line 95, in __call__
    result = self.work_function(
  File "/ci_cache/bazel_root_integration27/bb1c596d129cbbfac12269b41131c80b/execroot/com_bluerivertech/bazel-out/k8-opt/bin/autonomy/jupiter/embedded_safety_metrics/create_summary.runfiles/pip_pandarallel/site-packages/pandarallel/data_types/dataframe.py", line 32, in work
    return data.apply(
  File "/ci_cache/bazel_root_integration27/bb1c596d129cbbfac12269b41131c80b/execroot/com_bluerivertech/bazel-out/k8-opt/bin/autonomy/jupiter/embedded_safety_metrics/create_summary.runfiles/pip_pandas/site-packages/pandas/core/frame.py", line 9568, in apply
    return op.apply().__finalize__(self, method="apply")
  File "/ci_cache/bazel_root_integration27/bb1c596d129cbbfac12269b41131c80b/execroot/com_bluerivertech/bazel-out/k8-opt/bin/autonomy/jupiter/embedded_safety_metrics/create_summary.runfiles/pip_pandas/site-packages/pandas/core/apply.py", line 764, in apply
    return self.apply_standard()
  File "/ci_cache/bazel_root_integration27/bb1c596d129cbbfac12269b41131c80b/execroot/com_bluerivertech/bazel-out/k8-opt/bin/autonomy/jupiter/embedded_safety_metrics/create_summary.runfiles/pip_pandas/site-packages/pandas/core/apply.py", line 891, in apply_standard
    results, res_index = self.apply_series_generator()
  File "/ci_cache/bazel_root_integration27/bb1c596d129cbbfac12269b41131c80b/execroot/com_bluerivertech/bazel-out/k8-opt/bin/autonomy/jupiter/embedded_safety_metrics/create_summary.runfiles/pip_pandas/site-packages/pandas/core/apply.py", line 907, in apply_series_generator
    results[i] = self.f(v)
  File "/__w/brt/brt/autonomy/jupiter/embedded_safety_metrics/metrics_report.py", line 1009, in <lambda>
    lambda row: self.evaluate_one_frame(row), axis=1
  File "/__w/brt/brt/autonomy/jupiter/embedded_safety_metrics/metrics_report.py", line 971, in evaluate_one_frame
    create_mpl_viz_outputs(
  File "/ci_cache/bazel_root_integration27/bb1c596d129cbbfac12269b41131c80b/execroot/com_bluerivertech/bazel-out/k8-opt/bin/autonomy/jupiter/embedded_safety_metrics/create_summary.runfiles/com_bluerivertech/autonomy/jupiter/cvml/europa/base/src/europa/dl/utils/colors.py", line 232, in create_mpl_viz_outputs
    ax.imshow(
  File "/ci_cache/bazel_root_integration27/bb1c596d129cbbfac12269b41131c80b/execroot/com_bluerivertech/bazel-out/k8-opt/bin/autonomy/jupiter/embedded_safety_metrics/create_summary.runfiles/pip_matplotlib/site-packages/matplotlib/_api/deprecation.py", line 459, in wrapper
    return func(*args, **kwargs)
  File "/ci_cache/bazel_root_integration27/bb1c596d129cbbfac12269b41131c80b/execroot/com_bluerivertech/bazel-out/k8-opt/bin/autonomy/jupiter/embedded_safety_metrics/create_summary.runfiles/pip_matplotlib/site-packages/matplotlib/__init__.py", line 1412, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/ci_cache/bazel_root_integration27/bb1c596d129cbbfac12269b41131c80b/execroot/com_bluerivertech/bazel-out/k8-opt/bin/autonomy/jupiter/embedded_safety_metrics/create_summary.runfiles/pip_matplotlib/site-packages/matplotlib/axes/_axes.py", line 5475, in imshow
    im = mimage.AxesImage(self, cmap, norm, interpolation,
  File "/ci_cache/bazel_root_integration27/bb1c596d129cbbfac12269b41131c80b/execroot/com_bluerivertech/bazel-out/k8-opt/bin/autonomy/jupiter/embedded_safety_metrics/create_summary.runfiles/pip_matplotlib/site-packages/matplotlib/image.py", line 929, in __init__
    super().__init__(
  File "/ci_cache/bazel_root_integration27/bb1c596d129cbbfac12269b41131c80b/execroot/com_bluerivertech/bazel-out/k8-opt/bin/autonomy/jupiter/embedded_safety_metrics/create_summary.runfiles/pip_matplotlib/site-packages/matplotlib/image.py", line 246, in __init__
    cm.ScalarMappable.__init__(self, norm, cmap)
  File "/ci_cache/bazel_root_integration27/bb1c596d129cbbfac12269b41131c80b/execroot/com_bluerivertech/bazel-out/k8-opt/bin/autonomy/jupiter/embedded_safety_metrics/create_summary.runfiles/pip_matplotlib/site-packages/matplotlib/cm.py", line 357, in __init__
    self.set_norm(norm)  # The Normalize instance of this ScalarMappable.
  File "/ci_cache/bazel_root_integration27/bb1c596d129cbbfac12269b41131c80b/execroot/com_bluerivertech/bazel-out/k8-opt/bin/autonomy/jupiter/embedded_safety_metrics/create_summary.runfiles/pip_matplotlib/site-packages/matplotlib/cm.py", line 589, in set_norm
    self.norm = norm
  File "/ci_cache/bazel_root_integration27/bb1c596d129cbbfac12269b41131c80b/execroot/com_bluerivertech/bazel-out/k8-opt/bin/autonomy/jupiter/embedded_safety_metrics/create_summary.runfiles/pip_matplotlib/site-packages/matplotlib/cm.py", line 570, in norm
    self._id_norm = self.norm.callbacks.connect('changed',
  File "/ci_cache/bazel_root_integration27/bb1c596d129cbbfac12269b41131c80b/execroot/com_bluerivertech/bazel-out/k8-opt/bin/autonomy/jupiter/embedded_safety_metrics/create_summary.runfiles/pip_matplotlib/site-packages/matplotlib/_api/deprecation.py", line 302, in wrapper
    return func(*args, **kwargs)
  File "/ci_cache/bazel_root_integration27/bb1c596d129cbbfac12269b41131c80b/execroot/com_bluerivertech/bazel-out/k8-opt/bin/autonomy/jupiter/embedded_safety_metrics/create_summary.runfiles/pip_matplotlib/site-packages/matplotlib/cbook/__init__.py", line 222, in connect
    if proxy in self._func_cid_map[signal]:
KeyError: 'changed'


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/ci_cache/bazel_root_integration27/bb1c596d129cbbfac12269b41131c80b/execroot/com_bluerivertech/bazel-out/k8-opt/bin/autonomy/jupiter/embedded_safety_metrics/create_summary.runfiles/com_bluerivertech/autonomy/jupiter/embedded_safety_metrics/create_summary.py", line 239, in <module>
    main(sys.argv)
  File "/ci_cache/bazel_root_integration27/bb1c596d129cbbfac12269b41131c80b/execroot/com_bluerivertech/bazel-out/k8-opt/bin/autonomy/jupiter/embedded_safety_metrics/create_summary.runfiles/com_bluerivertech/autonomy/jupiter/embedded_safety_metrics/create_summary.py", line 226, in main
    metrics_summary.evaluate()
  File "/__w/brt/brt/autonomy/jupiter/embedded_safety_metrics/metrics_report.py", line 1008, in evaluate
    results = self.master_annotations_df.parallel_apply(
  File "/ci_cache/bazel_root_integration27/bb1c596d129cbbfac12269b41131c80b/execroot/com_bluerivertech/bazel-out/k8-opt/bin/autonomy/jupiter/embedded_safety_metrics/create_summary.runfiles/pip_pandarallel/site-packages/pandarallel/core.py", line 333, in closure
    results_promise.get()
  File "/ci_cache/bazel_root_integration27/bb1c596d129cbbfac12269b41131c80b/external/python_x86_64-unknown-linux-gnu/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
KeyError: 'changed'
```

### Expected outcome

![image](https://github.com/user-attachments/assets/bc35a76d-86fd-43c5-9677-863601e0f170)

Each call produces an image like this, stitching many input images together. Multiple images are saved to disk

### Additional information

The crash I'm reporting was noticed in 3.5.2 at least, but I've seen it on a few machines that don't all have the exact same version. I updated to the most recent 3.9.2 just to check and at least am seeing the caught version of the exception, the other one probably still exists but it hasn't happened yet

### Operating system

Ubuntu

### Matplotlib Version

3.5.2

### Matplotlib Backend

agg

### Python version

3.10, (also seen on 3.8)

### Jupyter version

Seen in a python script

### Installation

pip

**Comment by timhoffm** [comment]
By its nature `pyplot` manages a lot of global state. It is not safe for concurrent use. It seems you only want to save figures to files. In that case, you can directly instantiate a `Figure` and don't need `pyplot` at all. Outline:

```
from matplotlib.figure import Figure

fig = Figure()
ax = fig.subplots()
ax.plot([1, 2])
fig.savefig("test.png")
```

See also [this example](https://matplotlib.org/devdocs/gallery/user_interfaces/web_application_server_sgskip.html) where this pattern is applied to create images in web server.

**Comment by Alex17Li** [comment]
Thanks a lot for looking into this and pointing that out! I didn't realize that plt.subplots was manipulating a global object, so I changed the line

```
axes = fig.subplots(1, len(ax_inds), figsize=((8 * len(ax_inds), 6))) # type: ignore
```

to

``
fig = Figure(figsize=(8 * len(ax_inds), 6))
axes = fig.subplots(1, len(ax_inds))
```

It still didn't work until I removed the plt.close(fig), after that it looks to be running smoothly
