### ISSUE TITLE
ImportError: No module named 'mpl_toolkits'

### ISSUE THREAD

**Issue by cgohlke** [matplotlib/matplotlib#3252]
`matplotlib.test()` fails with 13 of the following errors using matplotlib-1.4.0rc1 on Windows, any Python version:

```
======================================================================
ERROR: Failure: ImportError (No module named 'mpl_toolkits')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python34\lib\site-packages\nose\failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "X:\Python34\lib\site-packages\nose\loader.py", line 285, in generate
    for test in g():
  File "X:\Python34\lib\site-packages\matplotlib\testing\decorators.py", line 157, in test
    baseline_dir, result_dir = _image_directories(self._func)
  File "X:\Python34\lib\site-packages\matplotlib\testing\decorators.py", line 322, in _image_directories
    mod_file = find_dotted_module(func.__module__)[1]
  File "X:\Python34\lib\site-packages\matplotlib\testing\decorators.py", line 316, in find_dotted_module
    res = file, path, _ = imp.find_module(sub_mod, path)
  File "X:\Python34\lib\imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'mpl_toolkits'
```

Running the tests via `nosetests.exe mpl_toolkits` fails with:

```
======================================================================
FAIL: Failure: AssertionError ()
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python34\lib\site-packages\nose\failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "X:\Python34\lib\site-packages\nose\loader.py", line 285, in generate
    for test in g():
  File "X:\Python34\lib\site-packages\matplotlib\testing\decorators.py", line 157, in test
    baseline_dir, result_dir = _image_directories(self._func)
  File "X:\Python34\lib\site-packages\matplotlib\testing\decorators.py", line 308, in _image_directories
    assert mods.pop(0) == 'tests'
AssertionError
```

Adding an empty `__init__.py` file to `Lib\site-packages\mpl_toolkits\` fixes these errors.

Importing mpl_toolkits via `import mpl_toolkits` from the interpreter or in scripts works.

Using numpy-1.8.1, nose-1.3.3, and setuptools-3.8.1. Matplotlib is installed using bdist_wininst installers.

**Comment by johnyjchan** [comment]
I melt similar problem. http://stackoverflow.com/questions/7816799/getting-py2exe-to-work-with-zope-interface/11632115#11632115 may be help.  Same strategy to fix the problem.  Find the site package path and make sure there is mpl_toolkits file.  Finally, create an empty  __init__.py if not exists.

**Comment by hongyi-zhang** [comment]
Just to confirm that @johnyjchan 's method works for me.

Background: Running anaconda2 + matplotlib 2.0.2, cannot import mpl_toolkits
