### ISSUE TITLE
Cannot properly reload figure that was previously pickled

### ISSUE THREAD

**Issue by mdepitta** [matplotlib/matplotlib#3483]
Dear all,
I just figure out that matplotlib does not have apparently a simple way to save interactive plots as MATLAB "fig" figures. I sincerely hope the "experimental" pickling will be soon consolidated because it would be of great benefit for users imho.

Briefly, I followed the simple procedure outlined here in order to pickle and reload figures:
http://stackoverflow.com/questions/7290370/store-and-reload-matplotlib-pyplot-object

It seems that I am able to pickle the figure indeed, but not to reload it properly.
This is what I get:

```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/matplotlib/backends/backend_qt4.py", line 299, in resizeEvent
    self.draw()
  File "/usr/lib64/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 154, in draw
    FigureCanvasAgg.draw(self)
  File "/usr/lib64/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 451, in draw
    self.figure.draw(self.renderer)
  File "/usr/lib64/python2.7/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/matplotlib/figure.py", line 1031, in draw
    dsu = [row for row in dsu if not row[1].get_animated()]
  File "/usr/lib64/python2.7/site-packages/matplotlib/artist.py", line 612, in get_animated
    return self._animated
AttributeError: 'AxesSubplot' object has no attribute '_animated'
```

Any suggestion? Shall I bother about this?
I am using matplotlib 1.3.1 on Fedora 20 with QtAgg backend.

Thanks for your time,

Maurizio

**Comment by pelson** [comment]
Wow, I'm so behind on my notifications! Thanks for raising this @mdepitta. Can you provide a SSCCE (Short, Self Contained, Correct , Example) to allow us to reproduce? This will dramatically speed up the development of a fix for this issue.

Thanks!

**Comment by efiring** [comment]
Given the "won't fix" decision, I'm going to close this.
