### ISSUE TITLE
latex support fails when $MPLCONFIGDIR is specified on command line

### ISSUE THREAD

**Issue by hollandjg** [matplotlib/matplotlib#3823]
If MPLCONFIGDIR is specified as a command line parameter, tex.usetex = True leads to a failure with no latex error report generated.

In the current working directory, there is a directory named mpl_setup containing matplotlibrc (default from http://matplotlib.org/_static/matplotlibrc with tex.usetex = True

Using the example latex support file as test.py:

```python
"""
Demo of TeX rendering.

You can use TeX to render all of your matplotlib text if the rc
parameter text.usetex is set.  This works currently on the agg and ps
backends, and requires that you have tex and the other dependencies
described at http://matplotlib.sf.net/matplotlib.texmanager.html
properly installed on your system.  The first time you run a script
you will see a lot of output from tex and associated tools.  The next
time, the run may be silent, as a lot of the information is cached in
~/.tex.cache

"""
import numpy as np
import matplotlib.pyplot as plt


# Example data
t = np.arange(0.0, 1.0 + 0.01, 0.01)
s = np.cos(4 * np.pi * t) + 2

plt.rc('text', usetex=True)
plt.rc('font', family='serif')
plt.plot(t, s)

plt.xlabel(r'\textbf{time} (s)')
plt.ylabel(r'\textit{voltage} (mV)',fontsize=16)
plt.title(r"\TeX\ is Number "
          r"$\displaystyle\sum_{n=1}^\infty\frac{-e^{i\pi}}{2^n}$!",
          fontsize=16, color='gray')
# Make room for the ridiculously large title.
plt.subplots_adjust(top=0.8)

plt.savefig('tex_demo')
```

call:
```bash
$ MPLCONFIGDIR=mpl_setup python test.py
```

returns:
```
sh: mpl_setup/tex.cache/03e7a0bce05f84219ebbd9b25349b054.output: No such file or directory
Traceback (most recent call last):
  File "test.py", line 34, in <module>
    plt.savefig('tex_demo')
  File "/Users/jholland/.virtualenvs/rexcess_substructure_2.7.8/lib/python2.7/site-packages/matplotlib/pyplot.py", line 577, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/Users/jholland/.virtualenvs/rexcess_substructure_2.7.8/lib/python2.7/site-packages/matplotlib/figure.py", line 1470, in savefig
    self.canvas.print_figure(*args, **kwargs)
  File "/Users/jholland/.virtualenvs/rexcess_substructure_2.7.8/lib/python2.7/site-packages/matplotlib/backends/backend_qt5agg.py", line 161, in print_figure
    FigureCanvasAgg.print_figure(self, *args, **kwargs)
  File "/Users/jholland/.virtualenvs/rexcess_substructure_2.7.8/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 2194, in print_figure
    **kwargs)
  File "/Users/jholland/.virtualenvs/rexcess_substructure_2.7.8/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 521, in print_png
    FigureCanvasAgg.draw(self)
  File "/Users/jholland/.virtualenvs/rexcess_substructure_2.7.8/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 469, in draw
    self.figure.draw(self.renderer)
  File "/Users/jholland/.virtualenvs/rexcess_substructure_2.7.8/lib/python2.7/site-packages/matplotlib/artist.py", line 59, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/Users/jholland/.virtualenvs/rexcess_substructure_2.7.8/lib/python2.7/site-packages/matplotlib/figure.py", line 1079, in draw
    func(*args)
  File "/Users/jholland/.virtualenvs/rexcess_substructure_2.7.8/lib/python2.7/site-packages/matplotlib/artist.py", line 59, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/Users/jholland/.virtualenvs/rexcess_substructure_2.7.8/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 2092, in draw
    a.draw(renderer)
  File "/Users/jholland/.virtualenvs/rexcess_substructure_2.7.8/lib/python2.7/site-packages/matplotlib/artist.py", line 59, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/Users/jholland/.virtualenvs/rexcess_substructure_2.7.8/lib/python2.7/site-packages/matplotlib/axis.py", line 1116, in draw
    renderer)
  File "/Users/jholland/.virtualenvs/rexcess_substructure_2.7.8/lib/python2.7/site-packages/matplotlib/axis.py", line 1065, in _get_tick_bboxes
    extent = tick.label1.get_window_extent(renderer)
  File "/Users/jholland/.virtualenvs/rexcess_substructure_2.7.8/lib/python2.7/site-packages/matplotlib/text.py", line 741, in get_window_extent
    bbox, info, descent = self._get_layout(self._renderer)
  File "/Users/jholland/.virtualenvs/rexcess_substructure_2.7.8/lib/python2.7/site-packages/matplotlib/text.py", line 311, in _get_layout
    ismath=False)
  File "/Users/jholland/.virtualenvs/rexcess_substructure_2.7.8/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 223, in get_text_width_height_descent
    renderer=self)
  File "/Users/jholland/.virtualenvs/rexcess_substructure_2.7.8/lib/python2.7/site-packages/matplotlib/texmanager.py", line 670, in get_text_width_height_descent
    dvifile = self.make_dvi(tex, fontsize)
  File "/Users/jholland/.virtualenvs/rexcess_substructure_2.7.8/lib/python2.7/site-packages/matplotlib/texmanager.py", line 417, in make_dvi
    report))
RuntimeError: LaTeX was not able to process the following string:
'lp'
Here is the full report generated by LaTeX: 

No latex error report available.
```

The error arises from matplotlib/texmanager.py 396-401
```python
            command = self._get_shell_cmd(
                'cd "%s"' % self.texcache,
                'latex -interaction=nonstopmode %s > "%s"' %
                (os.path.split(texfile)[-1], outfile))
            mpl.verbose.report(command, 'debug')
            exit_status = os.system(command)
```
The command generated looks like:
```python
u'cd "mpl_setup/tex.cache" && latex -interaction=nonstopmode 420826448ee4e4cf20666ffd8c36d03c.tex > "mpl_setup/tex.cache/420826448ee4e4cf20666ffd8c36d03c.output"'
```

Due to the cd at the start of the line, the write operation to `mpl_setup/tex.cache` attempts to write to `mpl_setup/tex.cache/mpl_setup/tex.cache/420826448ee4e4cf20666ffd8c36d03c.output`

A stopgap solution is to change the command variable in texmanager to 
```python
'(cd "%s"' % self.texcache,
'latex -interaction=nonstopmode %s) > "%s"' %
(os.path.split(texfile)[-1], outfile))
```
so that the latex step occurs in a subshell, but it may be better to correct the outfile variable specified.

**Comment by efiring** [comment]
Closed by #3827

**Comment by FRidh** [comment]
I just ran in a similar issue as I was generating plots inside a Nix build. For a Nix build a chroot is created and `$HOME` is set to a directory where it cannot write. Because in this case it is ok to write a `$HOME` since what's written there won't be saved anyway, I set `$HOME` to `"."`. That isn't an absolute path, thereby giving the same error as reported here.

**Comment by tacaswell** [comment]
@FRidh Please make a new issue, I suspect this is going through a different code path.
