### ISSUE TITLE
interactive mode not working with backends gtk3agg, gtk3cairo

### ISSUE THREAD

**Issue by thraen** [matplotlib/matplotlib#3881]
``` python
import matplotlib
matplotlib.use('GTK3Cairo') 
from pylab import *
ion()
plot([1,2,3])
xlabel('hi mom')
show()
```

doesn't show anything, no error no plot. same for backends gtk3agg. 
Only when I close the python shell I get an error:

```
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib64/python3.3/site-packages/matplotlib/_pylab_helpers.py", line 86, in destroy_all
    manager.destroy()
  File "/usr/lib64/python3.3/site-packages/matplotlib/backends/backend_gtk3.py", line 427, in destroy
    self.canvas.destroy()
AttributeError: 'FigureManagerGTK3Agg' object has no attribute 'canvas'
```

**Comment by tacaswell** [comment]
@thraen Any update on this?  Does it behave better with 1.4.3 / the 1.5.0rcs?

**Comment by mdehoon** [comment]
With the current master, it is still broken. I am getting
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib-0_unknown-py2.7-macosx-10.9-intel.egg/matplotlib/pyplot.py", line 527, in figure
    **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib-0_unknown-py2.7-macosx-10.9-intel.egg/matplotlib/backends/backend_gtk3cairo.py", line 61, in new_figure_manager
    return new_figure_manager_given_figure(num, thisFig)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib-0_unknown-py2.7-macosx-10.9-intel.egg/matplotlib/backends/backend_gtk3cairo.py", line 69, in new_figure_manager_given_figure
    manager = FigureManagerGTK3Cairo(canvas, num)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib-0_unknown-py2.7-macosx-10.9-intel.egg/matplotlib/backends/backend_gtk3.py", line 451, in __init__
    self.canvas.draw_idle()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib-0_unknown-py2.7-macosx-10.9-intel.egg/matplotlib/backends/backend_gtk3.py", line 347, in draw_idle
    self._idle_draw_id = GLib.idle_add(idle_draw)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gi/types.py", line 44, in function
    return info.invoke(*args)
TypeError: Error invoking GLib.idle_add: Unexpected value for argument 'function'
```

**Comment by mdboom** [comment]
Has ion() ever worked with Gtk3?  For me at least, this works fine without it (Fedora 22 and Mac Yosemite).  It also works fine inside of IPython (which is the recommended mode for interactive use).

**Comment by mdboom** [comment]
Given this and the recent wx issue, I wonder if we should start displaying warnings if `ion` is turned on outside of IPython for certain backends.

**Comment by anntzer** [comment]
This is still broken now, no window being raised at all.  No error is displayed, so I guess the root issue may have changed in between...  See also https://github.com/matplotlib/matplotlib/issues/17769#issuecomment-736660205 for a similar issue on wx.

**Comment by QuLogic** [comment]
I don't think PyGObject sets up an input hook, and we don't for GTK, so I expect it does no event loop processing.

**Comment by Freed-Wu** [comment]
I run the code in python's REPL.

**Comment by mdehoon** [comment]
@QuLogic  The old PyGTK set the input hook via `gtk.set_interactive` but it looks like this functionality was lost in the transition to PyGObject.

**Comment by jklymak** [comment]
I'll close as very stale.  Any issues with modern gut toolkits should get a new reproducible example..
