### ISSUE TITLE
Qt Version Validation Failure 

### ISSUE THREAD

**Issue by Quartinus** [matplotlib/matplotlib#3940]
On OSX 10.10.1 with PyQt5 5.3.2 installed, I am getting the follwing error: 

``` python
from matplotlib.backends import qt_compat
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/matplotlib/backends/qt_compat.py", line 91, in <module>
    from PyQt4 import QtCore, QtGui
ImportError: No module named 'PyQt4'
```

I have traced the error to the qt_compat.py file, and on line 48 there is the line `if rcParams['backend'] == 'Qt5Agg':`

Running `rcParams['backend']` in isolation provides the following string `"MacOSX"` which would seem to be nothing like the correct string that it should be returning. I am able to get my code to work by editing the qt_compat.py file but it would seem that there is a validation failure with the `rcParams['backend']`. 

I am also able to get the code working by placing this kludge into my code: 

``` python
import matplotlib
matplotlib.rcParams['backend'] = "Qt5Agg"
```

If I manually change this backend parameter, I am able to get my later import statements to work properly.

**Comment by tacaswell** [comment]
Recent changes to `qt_compat` should make this work better.

**Comment by jni** [comment]
Hi all,

I'm not sure whether I'm running into the same issue, but currently a simple matplotlib import is crashing my Travis, complaining that there is no Qt:

```pytb
==================================== ERRORS ====================================
_________________________ ERROR collecting gala/viz.py _________________________
gala/viz.py:5: in <module>
[1m    from matplotlib import cm, pyplot as plt[0m
../../../miniconda/envs/gala/lib/python3.5/site-packages/matplotlib/pyplot.py:114: in <module>
[1m    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()[0m
../../../miniconda/envs/gala/lib/python3.5/site-packages/matplotlib/backends/__init__.py:32: in pylab_setup
[1m    globals(),locals(),[backend_name],0)[0m
../../../miniconda/envs/gala/lib/python3.5/site-packages/matplotlib/backends/backend_qt4agg.py:18: in <module>
[1m    from .backend_qt5agg import FigureCanvasQTAggBase as _FigureCanvasQTAggBase[0m
../../../miniconda/envs/gala/lib/python3.5/site-packages/matplotlib/backends/backend_qt5agg.py:16: in <module>
[1m    from .backend_qt5 import QtCore[0m
../../../miniconda/envs/gala/lib/python3.5/site-packages/matplotlib/backends/backend_qt5.py:31: in <module>
[1m    from .qt_compat import QtCore, QtGui, QtWidgets, _getSaveFileName, __version__[0m
../../../miniconda/envs/gala/lib/python3.5/site-packages/matplotlib/backends/qt_compat.py:137: in <module>
[1m    from PyQt4 import QtCore, QtGui[0m
[31m[1mE   ImportError: No module named 'PyQt4'[0m
```

Any ideas on why it's trying to load the Qt backend by default?

Thanks!

**Comment by DavidMStraub** [comment]
FYI, I just ran into a similar problem with Travis & matplotlib, which is apparently due to changes in anaconda (PyQt4 vs PyQt5). In my case it was solved by adding to .travis.yml:
`conda install --yes python=$TRAVIS_PYTHON_VERSION pyqt=4`

**Comment by jenshnielsen** [comment]
@DavidMStraub 

Matplotlib has had a working QT5 backend for a long time so I would definitely recommend to change the default backend to QT5 rather than relying on downgrading to qt4
See http://matplotlib.org/faq/usage_faq.html#what-is-a-backend for information on how to set backends

@jni 

The default backend is QT4, If you want a non interactive backend you will have to set it. Again http://matplotlib.org/faq/usage_faq.html#what-is-a-backend has information on how to do that.

**Comment by Kojoley** [comment]
@jni @DavidMStraub please follow #7124 and ContinuumIO/anaconda-issues/issues/1068

**Comment by naught101** [comment]
I was getting an error like this:

```{python}
scripts/offline_runs/run_model.py run STH_km233_lR2d Amplero
Traceback (most recent call last):
  File "scripts/offline_runs/run_model.py", line 25, in <module>
    from pals_utils.constants import MET_VARS
  File "/data/documents/uni/phd/projects/pals_utils/pals_utils/__init__.py", line 10, in <module>
    from . import plot
  File "/data/documents/uni/phd/projects/pals_utils/pals_utils/plot.py", line 9, in <module>
    import ggplot as gg
  File "/home/naught101/miniconda3/envs/science/lib/python3.5/site-packages/ggplot/__init__.py", line 19, in <module>
    from .geoms import geom_area, geom_blank, geom_boxplot, geom_line, geom_point, geom_jitter, geom_histogram, geom_density, geom_hline, geom_vline, geom_bar, geom_abline, geom_tile, geom_rect, geom_bin2d, geom_step, geom_text, geom_path, geom_ribbon, geom_now_its_art, geom_violin, geom_errorbar, geom_polygon
  File "/home/naught101/miniconda3/envs/science/lib/python3.5/site-packages/ggplot/geoms/__init__.py", line 1, in <module>
    from .geom_abline import geom_abline
  File "/home/naught101/miniconda3/envs/science/lib/python3.5/site-packages/ggplot/geoms/geom_abline.py", line 1, in <module>
    from .geom import geom
  File "/home/naught101/miniconda3/envs/science/lib/python3.5/site-packages/ggplot/geoms/geom.py", line 3, in <module>
    from ..ggplot import ggplot
  File "/home/naught101/miniconda3/envs/science/lib/python3.5/site-packages/ggplot/ggplot.py", line 4, in <module>
    import matplotlib.pyplot as plt
  File "/home/naught101/miniconda3/envs/science/lib/python3.5/site-packages/matplotlib/pyplot.py", line 114, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/home/naught101/miniconda3/envs/science/lib/python3.5/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/home/naught101/miniconda3/envs/science/lib/python3.5/site-packages/matplotlib/backends/backend_qt4agg.py", line 18, in <module>
    from .backend_qt5agg import FigureCanvasQTAggBase as _FigureCanvasQTAggBase
  File "/home/naught101/miniconda3/envs/science/lib/python3.5/site-packages/matplotlib/backends/backend_qt5agg.py", line 16, in <module>
    from .backend_qt5 import QtCore
  File "/home/naught101/miniconda3/envs/science/lib/python3.5/site-packages/matplotlib/backends/backend_qt5.py", line 31, in <module>
    from .qt_compat import QtCore, QtGui, QtWidgets, _getSaveFileName, __version__
  File "/home/naught101/miniconda3/envs/science/lib/python3.5/site-packages/matplotlib/backends/qt_compat.py", line 137, in <module>
    from PyQt4 import QtCore, QtGui
ImportError: No module named 'PyQt4'
```

I worked around it by changing all instances of `Qt4` to `qt5` in `vim /home/naught101/miniconda3/pkgs/matplotlib-1.5.3-np111py35_0/lib/python3.5/site-packages/matplotlib/mpl-data/matplotlibrc`
