### ISSUE TITLE
Can't set marker fillstyle

### ISSUE THREAD

**Issue by ibell** [matplotlib/matplotlib#4073]
On windows, I can't seem to set the marker using a MarkerStyle instance (should this be possible?).  If I am doing this wrong, how DO I set the fillstyle?

``` python
import matplotlib.pyplot as plt
from matplotlib.markers import MarkerStyle
plt.scatter([1,2,3], [1,4,9], marker = MarkerStyle('o', fillstyle = 'top'))
plt.show()
```
yields
```
Traceback (most recent call last):
  File "markers.py", line 4, in <module>
    plt.scatter([1,2,3], [1,4,9], marker = MarkerStyle('o', fillstyle = 'top'))
  File "C:\Users\ihb\AppData\Local\Continuum\Miniconda\lib\site-packages\matplotlib\pyplot.py", line 3200, in scatter
    linewidths=linewidths, verts=verts, **kwargs)
  File "C:\Users\ihb\AppData\Local\Continuum\Miniconda\lib\site-packages\matplotlib\axes\_axes.py", line 3632, in scatter
    marker_obj = mmarkers.MarkerStyle(marker)
  File "C:\Users\ihb\AppData\Local\Continuum\Miniconda\lib\site-packages\matplotlib\markers.py", line 169, in __init__
    self.set_marker(marker)
  File "C:\Users\ihb\AppData\Local\Continuum\Miniconda\lib\site-packages\matplotlib\markers.py", line 244, in set_marker
    Path(marker)
  File "C:\Users\ihb\AppData\Local\Continuum\Miniconda\lib\site-packages\matplotlib\path.py", line 137, in __init__
    vertices = np.asarray(vertices, np.float_)
  File "C:\Users\ihb\AppData\Local\Continuum\Miniconda\lib\site-packages\numpy\core\numeric.py", line 462, in asarray
    return array(a, dtype, copy=False, order=order)
TypeError: float() argument must be a string or a number
```

Me:
```
C:\Users\ihb>ipython
Python 2.7.8 |Continuum Analytics, Inc.| (default, Jul  2 2014, 15:12:11) [MSC v.1500 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 2.3.1 -- An enhanced Interactive Python.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import matplotlib

In [2]: matplotlib.__version__
Out[2]: '1.4.2'
```

**Comment by tacaswell** [comment]
I think this has come up before https://github.com/matplotlib/matplotlib/issues/3895 but not yet fixed. The issue seems to be that scatter does not check that marker input is makerstyle objects and then does a bunch of internal magic to extract the path that is then passed to the underlying `PathCollection`.

**Comment by ibell** [comment]
Thanks!
