### ISSUE TITLE
segfault creating polarplot with GridHelperCurveLinear

### ISSUE THREAD

**Issue by Maik1976** [matplotlib/matplotlib#4448]
I'm using `mpl_toolkits.axisartist.floating_axes.GridHelperCurveLinear`
for creating half-polar plots from 180 degree measurements for receive sensitivity.

Working with the measurement values itself is no problem if I let the values scaling start at zero.
If I use normalized values I can plot it also, but if I transform it into the dB scale I got a SEGFAULT in this lib.  This behavior is reproducible on different computers with different operatting systems.

Here is the code for creating the SEGFAULT:

```python
from __future__ import division
from __future__ import print_function
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.transforms import Affine2D
from matplotlib.projections import PolarAxes
from mpl_toolkits.axisartist import angle_helper
from mpl_toolkits.axisartist.grid_finder import MaxNLocator
from mpl_toolkits.axisartist.floating_axes import GridHelperCurveLinear, FloatingSubplot

def fractional_polar_axes(f, thlim=(0, 180), rlim=(0, 1), step=(30, 0.2),
                      thlabel='theta', rlabel='r', ticklabels=True, theta_offset=0):
    """Return polar axes that adhere to desired theta (in deg) and r limits. steps for theta
    and r are really just hints for the locators."""
    th0, th1 = thlim # deg
    r0, r1 = rlim
    thstep, rstep = step

    tr_rotate = Affine2D().translate(theta_offset, 0)
    # scale degrees to radians:
    tr_scale = Affine2D().scale(np.pi/180., 1.)
    #pa = axes(polar="true") # Create a polar axis
    pa = PolarAxes
    tr = tr_rotate + tr_scale + pa.PolarTransform()
    theta_grid_locator = angle_helper.LocatorDMS((th1-th0)//thstep)
    r_grid_locator = MaxNLocator((r1-r0)//rstep)
    theta_tick_formatter = angle_helper.FormatterDMS()

    grid_helper = GridHelperCurveLinear(tr,
                                    extremes=(th0, th1, r0, r1),
                                    grid_locator1=theta_grid_locator,
                                    grid_locator2=r_grid_locator,
                                    tick_formatter1=theta_tick_formatter,
                                    tick_formatter2=None)
    a = FloatingSubplot(f, 111, grid_helper=grid_helper)
    f.add_subplot(a)
    # adjust x axis (theta):
    a.axis["bottom"].set_visible(False)
    a.axis["top"].set_axis_direction("bottom") # tick direction
    a.axis["top"].toggle(ticklabels=ticklabels, label=bool(thlabel))
    a.axis["top"].major_ticklabels.set_axis_direction("top")
    a.axis["top"].label.set_axis_direction("top")

    # adjust y axis (r):
    a.axis["left"].set_axis_direction("bottom") # tick direction
    a.axis["right"].set_axis_direction("top") # tick direction
    a.axis["left"].toggle(ticklabels=ticklabels, label=bool(rlabel))

    # add labels:
    a.axis["top"].label.set_text(thlabel)
    a.axis["left"].label.set_text(rlabel)

    # create a parasite axes whose transData is theta, r:
    auxa = a.get_aux_axes(tr)
    # make aux_ax to have a clip path as in a?:
    auxa.patch = a.patch
    # this has a side effect that the patch is drawn twice, and possibly over some other
    # artists. So, we decrease the zorder a bit to prevent this:
    a.patch.zorder = -2
    # add sector lines for both dimensions:
    thticks = grid_helper.grid_info['lon_info'][0]
    rticks = grid_helper.grid_info['lat_info'][0]
    for th in thticks[1:-1]: # all but the first and last
        auxa.plot([th, th], [r0, r1], '--', c='grey', zorder=-1)
    for ri, r in enumerate(rticks):
        # plot first r line as axes border in solid black only if it isn't at r=0
        if ri == 0 and r != 0:
            ls, lw, color = 'solid', 2, 'black'
        else:
            ls, lw, color = 'dashed', 1, 'grey'
        # From http://stackoverflow.com/a/19828753/2020363
        auxa.add_artist(plt.Circle([0, 0], radius=r, ls=ls, lw=lw, color=color, fill=False,
                        transform=auxa.transData._b, zorder=-1))

    return auxa

if __name__ == '__main__':
    f1 = plt.figure(facecolor='white', figsize=(16/2.54, 12/2.54), dpi=600)
    a1 = fractional_polar_axes(f1, thlim=(-90, 90),step=(10, 0.2),theta_offset=90)
    # example spiral plot:
    thstep = 10
    th = np.arange(-90, 90+thstep, thstep) # deg
    rstep = 1/(len(th)-1)
    r = np.arange(0, 1+rstep, rstep)
    a1.plot(th, r, 'b')
    f1.show()

    f2 = plt.figure(facecolor='white', figsize=(16/2.54, 12/2.54), dpi=600)
    a2 = fractional_polar_axes(f2, thlim=(-90, 90),rlim=(0,30),step=(10, 8),theta_offset=90)
    # example spiral plot:
    r2 = 20 * np.log10(r) +30
    a2.plot(th, r2, 'b')
    f2.show()

    f3 = plt.figure(facecolor='white', figsize=(16/2.54, 12/2.54), dpi=600)
    a3 = fractional_polar_axes(f2, thlim=(-90, 90),rlim=(-30,0), step=(10, 8),theta_offset=90)
    # example spiral plot:
    r3 = 20 * np.log10(r)
    a3.plot(th, r2, 'b')
    f2.show()
```

**Comment by tacaswell** [comment]
I think we also had a report of this on the mailing list that did not get dealt with yet.

**Comment by Maik1976** [comment]
yes, I ask it there. Maybe the user-list was the wrong place.

**Comment by tacaswell** [comment]
attn @leejjoon

**Comment by QuLogic** [comment]
This produces this rather amazing backtrace (on 1.5.2):
```
#52285 0x00007fffe28179db in agg::rasterizer_cells_aa<agg::cell_aa>::line(int, int, int, int) () from /usr/lib64/python3.5/site-packages/matplotlib/backends/_backend_agg.cpython-35m-x86_64-linux-gnu.so
#52286 0x00007fffe28179db in agg::rasterizer_cells_aa<agg::cell_aa>::line(int, int, int, int) () from /usr/lib64/python3.5/site-packages/matplotlib/backends/_backend_agg.cpython-35m-x86_64-linux-gnu.so
#52287 0x00007fffe28179db in agg::rasterizer_cells_aa<agg::cell_aa>::line(int, int, int, int) () from /usr/lib64/python3.5/site-packages/matplotlib/backends/_backend_agg.cpython-35m-x86_64-linux-gnu.so
#52288 0x00007fffe28179db in agg::rasterizer_cells_aa<agg::cell_aa>::line(int, int, int, int) () from /usr/lib64/python3.5/site-packages/matplotlib/backends/_backend_agg.cpython-35m-x86_64-linux-gnu.so
#52289 0x00007fffe2813922 in RendererAgg::render_clippath(py::PathIterator&, agg::trans_affine const&) () from /usr/lib64/python3.5/site-packages/matplotlib/backends/_backend_agg.cpython-35m-x86_64-linux-gnu.so
#52290 0x00007fffe28315d3 in void RendererAgg::draw_path<py::PathIterator>(GCAgg&, py::PathIterator&, agg::trans_affine&, agg::rgba&) () from /usr/lib64/python3.5/site-packages/matplotlib/backends/_backend_agg.cpython-35m-x86_64-linux-gnu.so
#52291 0x00007fffe281d458 in PyRendererAgg_draw_path(PyRendererAgg*, _object*, _object*) () from /usr/lib64/python3.5/site-packages/matplotlib/backends/_backend_agg.cpython-35m-x86_64-linux-gnu.so
  <built-in method draw_path of matplotlib.backends._backend_agg.RendererAgg object at remote 0x7fffe233fe70>
  File "/usr/lib64/python3.5/site-packages/matplotlib/backends/backend_agg.py", line 166, in draw_path
    self._renderer.draw_path(gc, path, transform, rgbFace)
  File "/usr/lib64/python3.5/site-packages/matplotlib/lines.py", line 1241, in _draw_dashed
    renderer.draw_path(gc, path, trans)
  File "/usr/lib64/python3.5/site-packages/matplotlib/lines.py", line 1209, in _draw_lines
    self._lineFunc(renderer, gc, path, trans)
  File "/usr/lib64/python3.5/site-packages/matplotlib/lines.py", line 771, in draw
    drawFunc(renderer, gc, tpath, affine.frozen())
  File "/usr/lib64/python3.5/site-packages/matplotlib/artist.py", line 62, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/usr/lib64/python3.5/site-packages/matplotlib/axes/_base.py", line 2319, in draw
    a.draw(renderer)
  File "/usr/lib64/python3.5/site-packages/matplotlib/artist.py", line 62, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/usr/lib64/python3.5/site-packages/mpl_toolkits/axisartist/axislines.py", line 778, in draw
    super(Axes, self).draw(renderer, inframe)
  File "/usr/lib64/python3.5/site-packages/mpl_toolkits/axes_grid1/parasite_axes.py", line 295, in draw
    self._get_base_axes_attr("draw")(self, renderer)
  File "/usr/lib64/python3.5/site-packages/matplotlib/figure.py", line 1159, in draw
    func(*args)
  File "/usr/lib64/python3.5/site-packages/matplotlib/artist.py", line 62, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/usr/lib64/python3.5/site-packages/matplotlib/backends/backend_agg.py", line 474, in draw
    self.figure.draw(self.renderer)
  File "/usr/lib64/python3.5/site-packages/matplotlib/backends/backend_tkagg.py", line 354, in draw
    FigureCanvasAgg.draw(self)
  File "/usr/lib64/python3.5/site-packages/matplotlib/backends/backend_tkagg.py", line 373, in idle_draw
    self.draw()
  File "/usr/lib64/python3.5/tkinter/__init__.py", line 596, in callit
    func(*args)
  File "/usr/lib64/python3.5/tkinter/__init__.py", line 1550, in __call__
    return self.func(*args)
  <built-in method call of _tkinter.tkapp object at remote 0x7fffe23dbeb0>
  File "/usr/lib64/python3.5/tkinter/__init__.py", line 1025, in update
    self.tk.call('update')
  File "/usr/lib64/python3.5/site-packages/matplotlib/backends/backend_tkagg.py", line 609, in show
    self.window.update()
  File "/usr/lib64/python3.5/site-packages/matplotlib/backend_bases.py", line 162, in __call__
    manager.show()
  File "/usr/lib64/python3.5/site-packages/matplotlib/pyplot.py", line 244, in show
    return _show(*args, **kw)
  File "test4448.py", line 102, in <module>
    plt.show()
```
Yes, there are really 50000 stack frames; it seems to be an infinite loop in Agg somewhere.

**Comment by anntzer** [comment]
https://github.com/matplotlib/matplotlib/pull/11748 is supposed to have fixed this (in the soon-to-be-released mpl3.4); feel free to reopen if not.
