### ISSUE TITLE
plot failed.

### ISSUE THREAD

**Issue by infozyzhang** [matplotlib/matplotlib#4577]
Win 7 32bit. Python 3.4 32bit. Matplotlib 1.4.3

```python
x = [1, 2, 3, 4, 5, 6, 7, 8, 9]
y = [961270000, 961270000, 961270000, 961270000, 961270000, 961270000, 961270000, 961270000, 961270000]
plt.plot(x, y, 'ro')

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\matplotlib\backends\tkagg.py", line 17, in blit
    tk.call("PyAggImagePhoto", photoimage, id(aggimage), colormode, id(bbox_array))
_tkinter.TclError: invalid command name "PyAggImagePhoto"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\Lib\tkinter\__init__.py", line 1487, in __call__
    return self.func(*args)
  File "C:\Python34\lib\site-packages\matplotlib\backends\backend_tkagg.py", line 278, in resize
    self.show()
  File "C:\Python34\lib\site-packages\matplotlib\backends\backend_tkagg.py", line 350, in draw
    tkagg.blit(self._tkphoto, self.renderer._renderer, colormode=2)
  File "C:\Python34\lib\site-packages\matplotlib\backends\tkagg.py", line 24, in blit
    tk.call("PyAggImagePhoto", photoimage, id(aggimage), colormode, id(bbox_array))
_tkinter.TclError
[<matplotlib.lines.Line2D object at 0x050E4870>]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\matplotlib\backends\tkagg.py", line 17, in blit
    tk.call("PyAggImagePhoto", photoimage, id(aggimage), colormode, id(bbox_array))
_tkinter.TclError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\Lib\tkinter\__init__.py", line 1487, in __call__
    return self.func(*args)
  File "C:\Python34\Lib\tkinter\__init__.py", line 532, in callit
    func(*args)
  File "C:\Python34\lib\site-packages\matplotlib\backends\backend_tkagg.py", line 365, in idle_draw
    self.draw()
  File "C:\Python34\lib\site-packages\matplotlib\backends\backend_tkagg.py", line 350, in draw
    tkagg.blit(self._tkphoto, self.renderer._renderer, colormode=2)
  File "C:\Python34\lib\site-packages\matplotlib\backends\tkagg.py", line 24, in blit
    tk.call("PyAggImagePhoto", photoimage, id(aggimage), colormode, id(bbox_array))
_tkinter.TclError
```

**Comment by infozyzhang** [comment]
My _TKINTER.PYD linked to TCL86.dll and TK86.dll instead of TCL86T.dll and TK86T.dll.

**Comment by infozyzhang** [comment]
The issue is because activestate python is not compatible.

**Comment by tacaswell** [comment]
Closing for the same reason as #4576 If you have a funny python distribution  you will need to compile mpl from source.  See https://github.com/jbmohler/matplotlib-winbuild
