### ISSUE TITLE
axes.format_cursor_data is raising a (2.7) ValueError and (3.4) TypeError in Jupyter notebook with nbagg backend

### ISSUE THREAD

**Issue by ericdill** [matplotlib/matplotlib#4806]
This bug exists on current master (465aecfba695a1630b48977a25407152d1b2e4f0) and raises a different exception for python 2.7 and python 3.4.  Environment lists are at the end.

This is demonstrated with the following notebook: http://nbviewer.ipython.org/b4dc8c682619fd820081

If you execute the above notebook, zoom in on the region where the array of random numbers has been set to -np.inf and hover over the region where the array is -np.inf, the following exception is raised in the jupyter notebook terminal app:

Debugging this has proven challenging because I'm having trouble piping any information about the current state back to the notebook terminal app, so I'm not sure exactly what `item` this format string is barfing on. However, it seems to raise the same exception if I pass `format_cursor_data` a numpy array as the third argument.  Sorry for the weak debugging :cry: 

Python 3.4 stack trace
-----
```
[IPKernelApp] ERROR | Exception in comm_msg for 247c2ff5e60f46629925768fd21d7fe4
Traceback (most recent call last):
  File "/home/edill/miniconda/envs/nikea3/lib/python3.4/site-packages/IPython/kernel/comm/manager.py", line 136, in comm_msg
    comm.handle_msg(msg)
  File "/home/edill/miniconda/envs/nikea3/lib/python3.4/site-packages/IPython/kernel/comm/comm.py", line 164, in handle_msg
    self._msg_callback(msg)
  File "/home/edill/dev/python/matplotlib/lib/matplotlib/backends/backend_nbagg.py", line 293, in on_message
    self.manager.handle_json(message)
  File "/home/edill/dev/python/matplotlib/lib/matplotlib/backends/backend_webagg_core.py", line 466, in handle_json
    self.canvas.handle_event(content)
  File "/home/edill/dev/python/matplotlib/lib/matplotlib/backends/backend_webagg_core.py", line 309, in handle_event
    self.motion_notify_event(x, y, guiEvent=guiEvent)
  File "/home/edill/dev/python/matplotlib/lib/matplotlib/backend_bases.py", line 1943, in motion_notify_event
    self.callbacks.process(s, event)
  File "/home/edill/dev/python/matplotlib/lib/matplotlib/cbook.py", line 562, in process
    proxy(*args, **kwargs)
  File "/home/edill/dev/python/matplotlib/lib/matplotlib/cbook.py", line 429, in __call__
    return mtd(*args, **kwargs)
  File "/home/edill/dev/python/matplotlib/lib/matplotlib/backend_bases.py", line 2824, in mouse_move
    s += ' [%s]' % a.format_cursor_data(data)
  File "/home/edill/dev/python/matplotlib/lib/matplotlib/artist.py", line 962, in format_cursor_data
    return ', '.join('{:0.3g}'.format(item) for item in data)
  File "/home/edill/dev/python/matplotlib/lib/matplotlib/artist.py", line 962, in <genexpr>
    return ', '.join('{:0.3g}'.format(item) for item in data)
TypeError: non-empty format string passed to object.__format__
```

Python 2.7 stack trace
------
```
[IPKernelApp] ERROR | Exception in comm_msg for e7668fae506944f08235b9278a7cfc6a
Traceback (most recent call last):
  File "/home/edill/miniconda/envs/nikea2/lib/python2.7/site-packages/IPython/kernel/comm/manager.py", line 136, in comm_msg
    comm.handle_msg(msg)
  File "/home/edill/miniconda/envs/nikea2/lib/python2.7/site-packages/IPython/kernel/comm/comm.py", line 164, in handle_msg
    self._msg_callback(msg)
  File "/home/edill/dev/python/matplotlib/lib/matplotlib/backends/backend_nbagg.py", line 293, in on_message
    self.manager.handle_json(message)
  File "/home/edill/dev/python/matplotlib/lib/matplotlib/backends/backend_webagg_core.py", line 466, in handle_json
    self.canvas.handle_event(content)
  File "/home/edill/dev/python/matplotlib/lib/matplotlib/backends/backend_webagg_core.py", line 309, in handle_event
    self.motion_notify_event(x, y, guiEvent=guiEvent)
  File "/home/edill/dev/python/matplotlib/lib/matplotlib/backend_bases.py", line 1943, in motion_notify_event
    self.callbacks.process(s, event)
  File "/home/edill/dev/python/matplotlib/lib/matplotlib/cbook.py", line 562, in process
    proxy(*args, **kwargs)
  File "/home/edill/dev/python/matplotlib/lib/matplotlib/cbook.py", line 429, in __call__
    return mtd(*args, **kwargs)
  File "/home/edill/dev/python/matplotlib/lib/matplotlib/backend_bases.py", line 2824, in mouse_move
    s += ' [%s]' % a.format_cursor_data(data)
  File "/home/edill/dev/python/matplotlib/lib/matplotlib/artist.py", line 962, in format_cursor_data
    return ', '.join('{:0.3g}'.format(item) for item in data)
  File "/home/edill/dev/python/matplotlib/lib/matplotlib/artist.py", line 962, in <genexpr>
    return ', '.join('{:0.3g}'.format(item) for item in data)
ValueError: Unknown format code 'g' for object of type 'unicode'
```

Python 3.4 environment
=====
```
(nikea3)edill@edill-810g:~/dev/python/matplotlib (master *$% u=)$ conda list
# packages in environment at /home/edill/miniconda/envs/nikea3:
alabaster                 0.7.3                    py34_0  
args                      0.1.0                     <pip>
babel                     1.3                      py34_0  
binstar                   0.10.4                   py34_0  
bluesky                   0.0.0.post1               <pip>
boltons                   0.6.4                     <pip>
bubblegum                 0.0.0.dev0                <pip>
certifi                   14.05.14                 py34_0  
channelarchiver           0.0.4.post5     5_g365f325_np19py34  
cj-db                     0.5.0.dev0                <pip>
clint                     0.4.1                     <pip>
clyent                    0.3.4                    py34_0  
coverage                  3.7.1                    py34_0  
coveralls                 0.5                       <pip>
cppy                      1.0.2                     <pip>
csxtools (/home/edill/dev/python/csxtools) 0.0.0                     <pip>
curl                      7.38.0                        0  
cython                    0.22.1                   py34_0  
dataportal                0.1.0.post0               <pip>
decorator                 3.4.0                    py34_0  
docopt                    0.6.2                     <pip>
docutils                  0.12                     py34_0  
enum34                    1.0.4                     <pip>
fabio                     0.2.1                     <pip>
filestore                 v0.0.4.post5    5_g4f57684_np19py34  
flake8                    2.3.0                    py34_0  
fontconfig                2.11.1                        4  
freetype                  2.5.2                         2  
h5py                      2.5.0                np19py34_0  
hdf5                      1.8.14                        0  
history (/home/edill/dev/python/history) 0.1.0                     <pip>
humanize                  0.5.1                     <pip>
ipython                   3.2.1                    py34_0  
ipython-notebook          3.2.1                    py34_0  
jinja2                    2.7.3                    py34_1  
jpeg                      8d                            0  
jsonschema                2.4.0                    py34_0  
libnetcdf                 4.3.2                         1  
libpng                    1.6.17                        0  
libsodium                 0.4.5                         0  
libtiff                   4.0.2                         1  
libxml2                   2.9.0                         0  
llvmlite                  0.6.0                    py34_0  
lmfit                     0.8.1.post32    32_g5d103f6_np19py34  
markupsafe                0.23                     py34_0  
matplotlib                1.5.dev1                  <pip>
mccabe                    0.3                      py34_1  
metadatastore             0.1.0.post0               <pip>
mistune                   0.7                      py34_0  
mongoengine               0.8.7                    py34_0  
ncurses                   5.9                           6  
netcdf4                   1.1.8                np19py34_0  
networkx                  1.9.1                    py34_0  
nose                      1.3.6                    py34_0  
nosexcover                1.0.10                    <pip>
numba                     0.20.0               np19py34_0  
numpy                     1.9.2                    py34_0  
openssl                   1.0.1k                        1  
ophyd                     0.0.6                     <pip>
pandas                    0.16.1               np19py34_0  
pep257                    0.5.0                     <pip>
pep8                      1.6.2                    py34_0  
pillow                    2.7.0                    py34_1  
pims                      0.2.2                    py34_0  
pip                       7.1.0                    py34_0  
prettytable               0.7.2                     <pip>
ptyprocess                0.4                      py34_0  
pyfai (/home/edill/dev/python/pyFAI) 0.10.3                    <pip>
pyflakes                  0.8.1                    py34_0  
pygments                  2.0.2                    py34_0  
pymongo                   2.8                      py34_0  
pyparsing                 2.0.3                    py34_0  
pyqt                      4.11.3                   py34_1  
python                    3.4.3                         1  
python-dateutil           2.4.2                    py34_0  
pytz                      2015.4                   py34_0  
pyyaml                    3.11                     py34_0  
pyzmq                     14.7.0                   py34_0  
qt                        4.8.6                         3  
readline                  6.2.5                         1  
requests                  2.7.0                    py34_0  
scikit-image              0.11.3               np19py34_0  
scikit-xray               0.0.3.post0               <pip>
scipy                     0.15.1               np19py34_0  
setuptools                18.0.1                   py34_0  
simdb                     0.5.0.dev0                <pip>
sip                       4.16.5                   py34_0  
six                       1.9.0                    py34_0  
snowballstemmer           1.2.0                    py34_0  
sphinx                    1.3.1                    py34_0  
sphinx-rtd-theme          0.1.7                     <pip>
sphinx_rtd_theme          0.1.7                    py34_0  
sphinxcontrib-napoleon    0.2.8                    py34_0  
sqlite                    3.8.4.1                       1  
super-state-machine       1.0                       <pip>
system                    5.8                           2  
terminado                 0.5                      py34_0  
tifffile                  0.3.1                np19py34_0  
tk                        8.5.18                        0  
tornado                   4.2.1                    py34_0  
tzlocal                   1.1.2                    py34_0  
xray-vision               0.0.0.dev0                <pip>
xraylib                   master               np19py34_0  
xz                        5.0.5                         0  
yaml                      0.1.4                         0  
zeromq                    4.0.5                         0  
zlib                      1.2.8                         0  
```

Python 2.7 environment
======
```
(nikea2)edill@edill-810g:~/dev/python/matplotlib (master *$% u=)$ conda list
# packages in environment at /home/edill/miniconda/envs/nikea2:
args                      0.1.0                     <pip>
atom                      0.3.9                    py27_0  
backports.ssl-match-hostname 3.4.0.2                   <pip>
binstar                   0.11.0                   py27_0  
bubblegum                 0.0.0.dev0                <pip>
cairo                     1.12.18                       4  
certifi                   14.05.14                 py27_1  
channelarchiver           0.0.4.post5     5_g365f325_np19py27  
clint                     0.4.1                     <pip>
clyent                    0.3.4                    py27_0  
controlsui                0.0.0                     <pip>
coverage                  3.7.1                    py27_0  
coveralls                 0.5                       <pip>
curl                      7.38.0                        0  
cython                    0.22.1                   py27_0  
dataportal                0.1.0.post0               <pip>
decorator                 3.4.2                    py27_0  
distribute                0.7.3                     <pip>
docopt                    0.6.2                     <pip>
enaml                     0.9.8                    py27_0  
fabio                     0.2.1                np19py27_0  
file-archive              0.6                       <pip>
filestore                 v0.0.3               np19py27_0  
fontconfig                2.11.1                        4  
freetype                  2.5.2                         2  
gmp                       4.3.2                         0  
h5py                      2.5.0                np19py27_3  
hdf5                      1.8.14                        0  
humanize                  0.5.1                     <pip>
ipython                   3.2.0                    py27_0  
ipython-notebook          3.1.0                    py27_1  
ipython-qtconsole         3.2.0                    py27_0  
jedi                      0.9.0                     <pip>
jinja2                    2.7.3                    py27_1  
jpeg                      8d                            0  
jsonschema                2.4.0                    py27_0  
kiwisolver                0.1.3                    py27_0  
libffi                    3.0.13                        3  
libnetcdf                 4.3.2                         1  
libpng                    1.6.17                        0  
libsodium                 0.4.5                         0  
libtiff                   4.0.2                         1  
libxml2                   2.9.2                         0  
libxslt                   1.1.28                        0  
lmfit                     0.8.3.post70    70_g3bf4298_np19py27  
lxml                      3.4.4                    py27_0  
markupsafe                0.23                     py27_0  
matplotlib                1.5.dev1                  <pip>
metadatastore             0.1.0.post0               <pip>
mistune                   0.6                      py27_0  
mock                      1.0.1                     <pip>
mongoengine               0.8.7                    py27_1  
ncurses                   5.9                           6  
netcdf4                   1.1.8                np19py27_0  
networkx                  1.9.1                    py27_0  
nose                      1.3.7                    py27_0  
numpy                     1.9.2                    py27_0  
openssl                   1.0.1k                        1  
pandas                    0.16.2               np19py27_0  
pandoc                    1.12.3                        3  
pillow                    2.9.0                    py27_0  
pims                      0.2.2                    py27_0  
pip                       7.1.0                    py27_0  
pixman                    0.26.2                        0  
ply                       3.4                      py27_0  
prettytable               0.7.2                     <pip>
prompt-toolkit (/home/edill/dev/python/python-prompt-toolkit) 0.42                      <pip>
ptpython (/home/edill/dev/python/ptpython) 0.16                      <pip>
ptyprocess                0.4                      py27_0  
py2cairo                  1.10.0                   py27_2  
pyfai                     0.10.3               np19py27_0  
pygments                  2.0.2                    py27_0  
pymongo                   2.8                      py27_0  
pyparsing                 2.0.3                    py27_0  
pyqt                      4.11.3                   py27_1  
python                    2.7.10                        0  
python-dateutil           2.4.2                    py27_0  
pytz                      2015.4                   py27_0  
pyyaml                    3.11                     py27_1  
pyzmq                     14.7.0                   py27_0  
qt                        4.8.6                         3  
readline                  6.2.5                         1  
replay                    0.0.0.dev0                <pip>
requests                  2.7.0                    py27_0  
scikit-image              0.11.3               np19py27_0  
scikit-xray               0.0.3.post0               <pip>
scipy                     0.15.1               np19py27_0  
setuptools                18.0.1                   py27_0  
sip                       4.16.5                   py27_0  
six                       1.9.0                    py27_0  
sqlite                    3.8.4.1                       1  
ssl_match_hostname        3.4.0.2                  py27_0  
system                    5.8                           2  
tdparser                  1.1.6                     <pip>
terminado                 0.5                      py27_0  
tifffile                  0.3.1                np19py27_0  
tk                        8.5.18                        0  
tornado                   4.2                      py27_0  
tzlocal                   1.1.2                    py27_0  
vistrails                 v2.1.4.post1392      np19py27_0  
vtk                       5.10.1                   py27_1  
vttools                   0.0.x                     <pip>
wcwidth                   0.1.4                     <pip>
xlrd                      0.9.3                    py27_0  
xlwt                      1.0.0                    py27_0  
xray-vision               0.0.0.dev0                <pip>
xraylib                   3.1.0.post7     7_ge921a46_np19py27  
yaml                      0.1.6                         0  
zeromq                    4.0.5                         0  
zlib                      1.2.8                         0  
```

**Comment by ericdill** [comment]
Uh, right, so turns out that this bug is easy to reproduce in a script.  Here is the stack trace with the local state that is causing this exception:

```python
import matplotlib.pyplot as plt
# %matplotlib notebook
import numpy as np
fig, ax = plt.subplots()
arr = np.random.random((50,50))
arr[0, :] = -np.inf
arr[:, 0] = -np.inf
im = ax.imshow(arr, cmap='viridis')
im.format_cursor_data((0, 0, arr[0,0]))
plt.show()
```

Same as above, zoom in on the -np.inf region and mpl will barf the same exceptions as above.

Python 2
=====
```
Exception --> Unknown format code 'g' for object of type 'unicode'
`data` = [masked]
`item` = --
Traceback (most recent call last):
  File "/home/edill/dev/python/matplotlib/lib/matplotlib/backends/backend_qt5.py", line 280, in mouseMoveEvent
    FigureCanvasBase.motion_notify_event(self, x, y, guiEvent=event)
  File "/home/edill/dev/python/matplotlib/lib/matplotlib/backend_bases.py", line 1943, in motion_notify_event
    self.callbacks.process(s, event)
  File "/home/edill/dev/python/matplotlib/lib/matplotlib/cbook.py", line 562, in process
    proxy(*args, **kwargs)
  File "/home/edill/dev/python/matplotlib/lib/matplotlib/cbook.py", line 429, in __call__
    return mtd(*args, **kwargs)
  File "/home/edill/dev/python/matplotlib/lib/matplotlib/backend_bases.py", line 2824, in mouse_move
    s += ' [%s]' % a.format_cursor_data(data)
  File "/home/edill/dev/python/matplotlib/lib/matplotlib/artist.py", line 968, in format_cursor_data
    formatted = ', '.join('{:0.3g}'.format(item) for item in data)
  File "/home/edill/dev/python/matplotlib/lib/matplotlib/artist.py", line 968, in <genexpr>
    formatted = ', '.join('{:0.3g}'.format(item) for item in data)
ValueError: Unknown format code 'g' for object of type 'unicode'
```

Python 3.4
====
```
Exception --> non-empty format string passed to object.__format__
`data` = [masked]
`item` = --
Traceback (most recent call last):
  File "/home/edill/dev/python/matplotlib/lib/matplotlib/backends/backend_qt5.py", line 280, in mouseMoveEvent
    FigureCanvasBase.motion_notify_event(self, x, y, guiEvent=event)
  File "/home/edill/dev/python/matplotlib/lib/matplotlib/backend_bases.py", line 1943, in motion_notify_event
    self.callbacks.process(s, event)
  File "/home/edill/dev/python/matplotlib/lib/matplotlib/cbook.py", line 562, in process
    proxy(*args, **kwargs)
  File "/home/edill/dev/python/matplotlib/lib/matplotlib/cbook.py", line 429, in __call__
    return mtd(*args, **kwargs)
  File "/home/edill/dev/python/matplotlib/lib/matplotlib/backend_bases.py", line 2824, in mouse_move
    s += ' [%s]' % a.format_cursor_data(data)
  File "/home/edill/dev/python/matplotlib/lib/matplotlib/artist.py", line 968, in format_cursor_data
    formatted = ', '.join('{:0.3g}'.format(item) for item in data)
  File "/home/edill/dev/python/matplotlib/lib/matplotlib/artist.py", line 968, in <genexpr>
    formatted = ', '.join('{:0.3g}'.format(item) for item in data)
TypeError: non-empty format string passed to object.__format__
```

git diff on the changed code that I used to print out this line:
```diff
()edill@edill-810g:~/dev/python/matplotlib (master *$% u=)$ git diff
diff --git a/lib/matplotlib/artist.py b/lib/matplotlib/artist.py
index e6d428f..28cbe9a 100644
--- a/lib/matplotlib/artist.py
+++ b/lib/matplotlib/artist.py
@@ -959,7 +959,14 @@ class Artist(object):
             data[0]
         except (TypeError, IndexError):
             data = [data]
-        return ', '.join('{:0.3g}'.format(item) for item in data)
+        for item in data:
+            try:
+                ', '.join('{:0.3g}'.format(item))
+            except Exception as e:
+                print('\nException --> %s\n`data` = %s\n`item` = %s' % (e, data, item))
+            
+        formatted = ', '.join('{:0.3g}'.format(item) for item in data)
+        return formatted
 
 
 class ArtistInspector(object):
```

**Comment by ericdill** [comment]
I'm happy to put in a PR to fix this if I could have some guidance as to what should be fixed

**Comment by tacaswell** [comment]
attn @blink1073

**Comment by blink1073** [comment]
How about using this:

```python
        return ', '.join('{:0.3g}'.format(item) for item in data if
                         isinstance(item, (int, float)))
``

**Comment by tacaswell** [comment]
:+1:

**Comment by mdboom** [comment]
@blink1073: Will your suggested solution work for Numpy scalars?  I can't remember if that's required in this context, but there's many cases in matplotlib where it is.

**Comment by blink1073** [comment]
@mdboom, yup:

```python
In [2]: isinstance(np.float64(1.0), float)
Out[2]: True

In [3]: isinstance(np.inf, float)
Out[3]: True
```

**Comment by jenshnielsen** [comment]
Wouldn't it be better to use the Numbers.Real ABC https://docs.python.org/2/library/numbers.html#numbers.Real

I.e. 
```python
In [1]: isinstance(np.int32(1), int)
Out[1]: False

In [2]: isinstance(np.float128(1), float)
Out[2]: False

In [3]: isinstance(np.int32(1), numbers.Real)
Out[3]: True

In [4]: isinstance(np.float128(1), numbers.Real)
Out[4]: True
```

**Comment by blink1073** [comment]
Ah, good call @jenshnielsen.

**Comment by mdboom** [comment]
Except using an ABC is *really* slow.  I usually do `isinstance(1.0, (float, np.floating))`.

```
In [5]: %timeit isinstance(np.float128(1.0), numbers.Real)
1000000 loops, best of 3: 1.12 µs per loop

In [6]: %timeit isinstance(np.float128(1.0), (float, np.floating))
1000000 loops, best of 3: 632 ns per loop
```

**Comment by jenshnielsen** [comment]
Right I guess we are off doing:
```
isinstance(numpy.int64(1),(numpy.floating,numpy.integer,int,float))
```

**Comment by tacaswell** [comment]
@ericdill Your offer to implement this still good?
