### ISSUE TITLE
tick labels when autoscale is off

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#4996]
Consider

```
import numpy as np
from matplotlib import pyplot as plt

fig, ax = plt.subplots()
ax.set_autoscaley_on(False)
ax.semilogy(np.arange(.1, 3))
plt.show()
```

This prints the warning

```
/usr/lib/python3.4/site-packages/numpy/ma/core.py:3900: UserWarning: Warning: converting a masked element to nan.
  warnings.warn("Warning: converting a masked element to nan.")
```

and gives a plot with a completely missing y axis.

**Comment by efiring** [comment]
Odd bug.  If you perturb the plot slightly with zoom/pan and then use the Home button to go back to the original, the y axis scale appears.
On master it's a bit different: it comes up with a completely blank axes patch. Shaking with zoom/pan and then clicking Home again restores it to the same form as with version 1.4.3.

**Comment by tacaswell** [comment]
If you add `ax.set_ylim([.01, 10])` to this example it works fine.

I get a whole spam of exceptions in my console that look something like

```python
Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/tcaswell/.virtualenvs/dd_py3k/lib/python3.4/tkinter/__init__.py", line 1533, in __call__
    return self.func(*args)
  File "/home/tcaswell/other_source/matplotlib/lib/matplotlib/backends/backend_tkagg.py", line 390, in motion_notify_event
  File "/home/tcaswell/other_source/matplotlib/lib/matplotlib/backend_bases.py", line 1950, in motion_notify_event
    *guiEvent*
  File "/home/tcaswell/other_source/matplotlib/lib/matplotlib/backend_bases.py", line 1544, in __init__
    self.button = button
  File "/home/tcaswell/other_source/matplotlib/lib/matplotlib/backend_bases.py", line 1459, in __init__
    xdata, ydata = trans.transform_point((x, y))
  File "/home/tcaswell/other_source/matplotlib/lib/matplotlib/transforms.py", line 2361, in inverted
    inverted.__doc__ = Transform.inverted.__doc__
  File "/home/tcaswell/other_source/matplotlib/lib/matplotlib/transforms.py", line 2361, in inverted
    inverted.__doc__ = Transform.inverted.__doc__
  File "/home/tcaswell/other_source/matplotlib/lib/matplotlib/transforms.py", line 1757, in inverted
    self._invalid = 0
  File "/home/tcaswell/.virtualenvs/dd_py3k/lib/python3.4/site-packages/numpy/linalg/linalg.py", line 520, in inv
    ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)
  File "/home/tcaswell/.virtualenvs/dd_py3k/lib/python3.4/site-packages/numpy/linalg/linalg.py", line 90, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
numpy.linalg.linalg.LinAlgError: Singular matrix
```

which arise from trying to have 0 in the range of a log-scaled axes.  I think it is reasonable to expect that if users are going to turn off auto-scaling and use log-scales, then it is their responsibility to make sure the the axis limits are strictly greater than 0.

**Comment by anntzer** [comment]
I understand your point but I think matplotlib should at least fail "cleanly" by raising an exception (or a specific warning) in such a case (in fact, the fact that this was due to default limits being [0, 1] wasn't clear initially to me as I'd expect log(0)-related issues printing warnings about inf, not nan).

**Comment by efiring** [comment]
It's pretty obscure: explicitly telling mpl not to autoscale, and then complaining that it doesn't autoscale sensibly.  When I try it now I don't get a nice y-axis, but I don't get an error message, either.  Closing, but re-open if you have an idea about how to improve the situation.
