### ISSUE TITLE
curious issue on Windows trying to run test 

### ISSUE THREAD

**Issue by stonebig** [matplotlib/matplotlib#5174]
matplotlib 1.5rc2 / Python 3.4 64  bit / Windows 7 
````
>>> import matplotlib
>>> matplotlib.test()
Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    matplotlib.test()
  File "D:\WinPython\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64\lib\site-packages\matplotlib\__init__.py", line 1504, in test
    faulthandler.enable()
io.UnsupportedOperation: fileno
>>> 
````

**Comment by stonebig** [comment]
better look on qtconsole:
````
In [1]: >>> import matplotlib
   ...: >>> matplotlib.test()
   ...: 
Traceback (most recent call last):

  File "<ipython-input-1-021275aad5ad>", line 2, in <module>
    matplotlib.test()

  File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64\lib\site-packages\matplotlib\__init__.py", line 1504, in test
    faulthandler.enable()

  File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64\lib\site-packages\ipykernel\iostream.py", line 205, in fileno
    raise UnsupportedOperation("IOStream has no fileno.")

UnsupportedOperation: IOStream has no fileno.

````

**Comment by tacaswell** [comment]
attn @cgohlke 

Does running `python test.py` work?

**Comment by efiring** [comment]
Faulthandler is new to me; I see it was added in python 3.3.  Based on the traceback, it looks like the implementation of it on @stonebig's system is broken.
@stonebig, what happens if you try it without matplotlib:
```python
import faulthandler
faulthandler.enable()
```

**Comment by stonebig** [comment]
````
In [1]: import faulthandler
   ...: faulthandler.enable()
   ...: 
Traceback (most recent call last):

  File "<ipython-input-1-535243639b75>", line 2, in <module>
    faulthandler.enable()

  File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64\lib\site-packages\ipykernel\iostream.py", line 205, in fileno
    raise UnsupportedOperation("IOStream has no fileno.")

UnsupportedOperation: IOStream has no fileno
`````

**Comment by efiring** [comment]
It is not a matplotlib bug; therefore the question is whether to include a workaround.  Wrapping the `faulthandler.enable()` in another try/except, or wrapping the whole faulthandler block in a try with a bare except would do it.

**Comment by cgohlke** [comment]
I can not reproduce this issue.

**Comment by stonebig** [comment]
ok, closing, as cgohlkge can't reroduce.
