### ISSUE TITLE
    self._renderer = _RendererAgg(int(width), int(height), dpi, debug=False) ValueError: width and height must each be below 32768

### ISSUE THREAD

**Issue by neuronphysics** [matplotlib/matplotlib#5191]
I am trying to make a plot with 364 subplots with 26 rows and columns and in order that sub-plots would not overlap with each other I calculated the size might be needed by  
    K = len(xs)
    factor = 3.0           # size of one side of one panel
    lbdim = 1.1 * factor   # size of left/bottom margin
    trdim = 0.7 * factor   # size of top/right margin
    whspace = 0.01         # w/hspace size
    plotdim = factor * K + factor * (K - 1.) * whspace
    dim = lbdim + plotdim + trdim
    print('figure size:\t',dim)
    # Create a new figure if one wasn't provided.
    if fig is None:
        fig, axes = pl.subplots(K, K, figsize=(dim, dim))
.
.
.
pl.savefig(outname, bbox_inches="tight", bbox_extra_artists=[])

so the value that it returns for the figure size is:
figure size:	 84.15
I have chosen a large dpi 
matplotlib.rcParams["savefig.dpi"]= 2000
however I got this error message 

Traceback (most recent call last):
  File "Multi_Clusters_mass_conc_emcee.py", line 58, in <module>
    results=model.sample_posterior(nwalkers=800, nsamp=1200, burn=500, thin=100, plot_posterior=True, plot_chains=False, single_posterior=False, sampler_type='ensemble')
  File "/vol/multiclusters_model_fit.py", line 800, in sample_posterior
    outname=fname, verbose=True)
  File "/vol/corner.py", line 391, in corner
    pl.savefig(outname, bbox_inches="tight", bbox_extra_artists=[])
  File "/anaconda/lib/python2.7/site-packages/matplotlib/pyplot.py", line 577, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/anaconda/lib/python2.7/site-packages/matplotlib/figure.py", line 1476, in savefig
    self.canvas.print_figure(*args, **kwargs)
  File "/anaconda/lib/python2.7/site-packages/matplotlib/backends/backend_qt5agg.py", line 161, in print_figure
    FigureCanvasAgg.print_figure(self, *args, **kwargs)
  File "/anaconda/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 2158, in print_figure
    **kwargs)
  File "/anaconda/lib/python2.7/site-packages/matplotlib/backends/backend_pdf.py", line 2485, in print_pdf
    self.figure.draw(renderer)
  File "/anaconda/lib/python2.7/site-packages/matplotlib/artist.py", line 59, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/anaconda/lib/python2.7/site-packages/matplotlib/figure.py", line 1085, in draw
    func(*args)
  File "/vol/aibn84/data2/zahra/anaconda/lib/python2.7/site-packages/matplotlib/artist.py", line 59, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/anaconda/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 2110, in draw
    a.draw(renderer)
  File "/anaconda/lib/python2.7/site-packages/matplotlib/artist.py", line 58, in draw_wrapper
    before(artist, renderer)
  File "/anaconda/lib/python2.7/site-packages/matplotlib/artist.py", line 43, in before
    renderer.start_rasterizing()
  File "/anaconda/lib/python2.7/site-packages/matplotlib/backends/backend_mixed.py", line 101, in start_rasterizing
    self._width*self.dpi, self._height*self.dpi, self.dpi)
  File "/anaconda/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 94, in __init__
    self._renderer = _RendererAgg(int(width), int(height), dpi, debug=False)
ValueError: width and height must each be below 32768

When I just use plt.show() the generated image is very good but I am wondering what would be the work around this problem without I lose a high resolution image and I would not need to change the setup to get my plot?
Thanks.

**Comment by mdboom** [comment]
This is an inherent limitation of Agg, which never really contemplated using image buffers that large.

You could try generating an SVG or PDF and then converting that to PNG instead.
