### ISSUE TITLE
RuntimeError: No SFNT name table

### ISSUE THREAD

**Issue by aamirza93** [matplotlib/matplotlib#5232]
Hi, I'm on Ubuntu 14.04 LTS using Python 3.4 and matplotlib 1.4.3.

I'm new to all this , and I tried to make the simple lot in the tutorial (http://matplotlib.org/users/pyplot_tutorial.html), but I got these two errors:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/matplotlib/font_manager.py", line 1407, in <module>
    fontManager = pickle_load(_fmcache)
  File "/usr/local/lib/python3.4/dist-packages/matplotlib/font_manager.py", line 960, in pickle_load
    with open(filename, 'rb') as fh:
FileNotFoundError: [Errno 2] No such file or directory: '/home/aamir/.cache/matplotlib/fontList.py3k.cache'




During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "testplots.py", line 1, in <module>
    import matplotlib.pyplot as plt
  File "/usr/local/lib/python3.4/dist-packages/matplotlib/pyplot.py", line 27, in <module>
    import matplotlib.colorbar
  File "/usr/local/lib/python3.4/dist-packages/matplotlib/colorbar.py", line 34, in <module>
    import matplotlib.collections as collections
  File "/usr/local/lib/python3.4/dist-packages/matplotlib/collections.py", line 27, in <module>
    import matplotlib.backend_bases as backend_bases
  File "/usr/local/lib/python3.4/dist-packages/matplotlib/backend_bases.py", line 56, in <module>
    import matplotlib.textpath as textpath
  File "/usr/local/lib/python3.4/dist-packages/matplotlib/textpath.py", line 19, in <module>
    import matplotlib.font_manager as font_manager
  File "/usr/local/lib/python3.4/dist-packages/matplotlib/font_manager.py", line 1415, in <module>
    _rebuild()
  File "/usr/local/lib/python3.4/dist-packages/matplotlib/font_manager.py", line 1400, in _rebuild
    fontManager = FontManager()
  File "/usr/local/lib/python3.4/dist-packages/matplotlib/font_manager.py", line 1055, in __init__
    self.ttflist = createFontList(self.ttffiles)
  File "/usr/local/lib/python3.4/dist-packages/matplotlib/font_manager.py", line 589, in createFontList
    prop = ttfFontProperty(font)
  File "/usr/local/lib/python3.4/dist-packages/matplotlib/font_manager.py", line 395, in ttfFontProperty
    sfnt = font.get_sfnt()
RuntimeError: No SFNT name table
```
-----
If I use Python2, I can get rid of the first FileNotFoundError, but I'd strongly prefer to use Python 3. Anyway, I have no idea what these errors mean. A bit of searching around lead to me believe I might have some incompatible fonts, but removing all the fonts from my ~/.fonts folder (which is where I installed all my custom fonts) didn't solve the issue. 

Anyone have any idea on what's going on?

**Comment by mdboom** [comment]
matplotlib has found some non-standard-compliant font on your system.  The bug on our end is that we probably need to be robust against this and just move on to the next font.

In the meantime, if you want to see the offending font, you can turn on the Python debugger and print out the value of `font.fname` where it fails here.  Then move or remove the font file.

**Comment by mdboom** [comment]
See #5233 for fix.

**Comment by aamirza93** [comment]
Thank you! The fix got it working.
