### ISSUE TITLE
1.5.0~rc2: unittest failures/errors on (debian) mips

### ISSUE THREAD

**Issue by sandrotosi** [matplotlib/matplotlib#5255]
Hey, when rebuilding mpl on debian mips, we got these errors in the unittest suite (full log at https://buildd.debian.org/status/fetch.php?pkg=matplotlib&arch=mips&ver=1.5.0~rc2-1&stamp=1444478830, I'm reporting only the 2.7 issues, there might be others in the -dbg favour or in the 3.4&3.5 runs, you can look for them in the log):

```
======================================================================
ERROR: matplotlib.tests.test_backend_qt4.test_fig_close
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/testing/decorators.py", line 118, in wrapped_function
    func(*args, **kwargs)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/testing/decorators.py", line 53, in failer
    result = f(*args, **kwargs)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/testing/decorators.py", line 371, in backend_switcher
    result = func(*args, **kwargs)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/tests/test_backend_qt4.py", line 40, in test_fig_close
    fig = plt.figure()
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/pyplot.py", line 527, in figure
    **kwargs)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/backends/backend_qt4agg.py", line 46, in new_figure_manager
    return new_figure_manager_given_figure(num, thisFig)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/backends/backend_qt4agg.py", line 53, in new_figure_manager_given_figure
    canvas = FigureCanvasQTAgg(figure)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/backends/backend_qt4agg.py", line 71, in __init__
    FigureCanvasQT.__init__(self, figure)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/backends/backend_qt4.py", line 71, in __init__
    QtWidgets.QWidget.__init__(self)
TypeError: __init__() takes exactly 2 arguments (1 given)

======================================================================
ERROR: matplotlib.tests.test_backend_qt4.test_shift
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/testing/decorators.py", line 118, in wrapped_function
    func(*args, **kwargs)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/testing/decorators.py", line 53, in failer
    result = f(*args, **kwargs)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/tests/test_backend_qt4.py", line 78, in test_shift
    'A')
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/testing/decorators.py", line 371, in backend_switcher
    result = func(*args, **kwargs)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/tests/test_backend_qt4.py", line 59, in assert_correct_key
    qt_canvas = plt.figure().canvas
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/pyplot.py", line 527, in figure
    **kwargs)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/backends/backend_qt4agg.py", line 46, in new_figure_manager
    return new_figure_manager_given_figure(num, thisFig)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/backends/backend_qt4agg.py", line 53, in new_figure_manager_given_figure
    canvas = FigureCanvasQTAgg(figure)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/backends/backend_qt4agg.py", line 71, in __init__
    FigureCanvasQT.__init__(self, figure)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/backends/backend_qt4.py", line 71, in __init__
    QtWidgets.QWidget.__init__(self)
TypeError: __init__() takes exactly 2 arguments (1 given)

======================================================================
ERROR: matplotlib.tests.test_backend_qt4.test_lower
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/testing/decorators.py", line 118, in wrapped_function
    func(*args, **kwargs)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/testing/decorators.py", line 53, in failer
    result = f(*args, **kwargs)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/tests/test_backend_qt4.py", line 86, in test_lower
    'a')
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/testing/decorators.py", line 371, in backend_switcher
    result = func(*args, **kwargs)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/tests/test_backend_qt4.py", line 59, in assert_correct_key
    qt_canvas = plt.figure().canvas
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/pyplot.py", line 527, in figure
    **kwargs)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/backends/backend_qt4agg.py", line 46, in new_figure_manager
    return new_figure_manager_given_figure(num, thisFig)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/backends/backend_qt4agg.py", line 53, in new_figure_manager_given_figure
    canvas = FigureCanvasQTAgg(figure)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/backends/backend_qt4agg.py", line 71, in __init__
    FigureCanvasQT.__init__(self, figure)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/backends/backend_qt4.py", line 71, in __init__
    QtWidgets.QWidget.__init__(self)
TypeError: __init__() takes exactly 2 arguments (1 given)

======================================================================
ERROR: matplotlib.tests.test_backend_qt4.test_control
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/testing/decorators.py", line 118, in wrapped_function
    func(*args, **kwargs)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/testing/decorators.py", line 53, in failer
    result = f(*args, **kwargs)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/tests/test_backend_qt4.py", line 94, in test_control
    'ctrl+a')
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/testing/decorators.py", line 371, in backend_switcher
    result = func(*args, **kwargs)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/tests/test_backend_qt4.py", line 59, in assert_correct_key
    qt_canvas = plt.figure().canvas
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/pyplot.py", line 527, in figure
    **kwargs)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/backends/backend_qt4agg.py", line 46, in new_figure_manager
    return new_figure_manager_given_figure(num, thisFig)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/backends/backend_qt4agg.py", line 53, in new_figure_manager_given_figure
    canvas = FigureCanvasQTAgg(figure)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/backends/backend_qt4agg.py", line 71, in __init__
    FigureCanvasQT.__init__(self, figure)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/backends/backend_qt4.py", line 71, in __init__
    QtWidgets.QWidget.__init__(self)
TypeError: __init__() takes exactly 2 arguments (1 given)

======================================================================
ERROR: matplotlib.tests.test_backend_qt4.test_unicode_upper
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/testing/decorators.py", line 118, in wrapped_function
    func(*args, **kwargs)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/testing/decorators.py", line 53, in failer
    result = f(*args, **kwargs)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/tests/test_backend_qt4.py", line 102, in test_unicode_upper
    unichr(193))
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/testing/decorators.py", line 371, in backend_switcher
    result = func(*args, **kwargs)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/tests/test_backend_qt4.py", line 59, in assert_correct_key
    qt_canvas = plt.figure().canvas
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/pyplot.py", line 527, in figure
    **kwargs)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/backends/backend_qt4agg.py", line 46, in new_figure_manager
    return new_figure_manager_given_figure(num, thisFig)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/backends/backend_qt4agg.py", line 53, in new_figure_manager_given_figure
    canvas = FigureCanvasQTAgg(figure)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/backends/backend_qt4agg.py", line 71, in __init__
    FigureCanvasQT.__init__(self, figure)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/backends/backend_qt4.py", line 71, in __init__
    QtWidgets.QWidget.__init__(self)
TypeError: __init__() takes exactly 2 arguments (1 given)

======================================================================
ERROR: matplotlib.tests.test_backend_qt4.test_unicode_lower
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/testing/decorators.py", line 118, in wrapped_function
    func(*args, **kwargs)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/testing/decorators.py", line 53, in failer
    result = f(*args, **kwargs)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/tests/test_backend_qt4.py", line 110, in test_unicode_lower
    unichr(225))
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/testing/decorators.py", line 371, in backend_switcher
    result = func(*args, **kwargs)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/tests/test_backend_qt4.py", line 59, in assert_correct_key
    qt_canvas = plt.figure().canvas
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/pyplot.py", line 527, in figure
    **kwargs)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/backends/backend_qt4agg.py", line 46, in new_figure_manager
    return new_figure_manager_given_figure(num, thisFig)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/backends/backend_qt4agg.py", line 53, in new_figure_manager_given_figure
    canvas = FigureCanvasQTAgg(figure)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/backends/backend_qt4agg.py", line 71, in __init__
    FigureCanvasQT.__init__(self, figure)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/backends/backend_qt4.py", line 71, in __init__
    QtWidgets.QWidget.__init__(self)
TypeError: __init__() takes exactly 2 arguments (1 given)

======================================================================
ERROR: matplotlib.tests.test_backend_qt4.test_alt_control
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/testing/decorators.py", line 118, in wrapped_function
    func(*args, **kwargs)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/testing/decorators.py", line 53, in failer
    result = f(*args, **kwargs)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/tests/test_backend_qt4.py", line 118, in test_alt_control
    'alt+control')
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/testing/decorators.py", line 371, in backend_switcher
    result = func(*args, **kwargs)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/tests/test_backend_qt4.py", line 59, in assert_correct_key
    qt_canvas = plt.figure().canvas
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/pyplot.py", line 527, in figure
    **kwargs)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/backends/backend_qt4agg.py", line 46, in new_figure_manager
    return new_figure_manager_given_figure(num, thisFig)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/backends/backend_qt4agg.py", line 53, in new_figure_manager_given_figure
    canvas = FigureCanvasQTAgg(figure)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/backends/backend_qt4agg.py", line 71, in __init__
    FigureCanvasQT.__init__(self, figure)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/backends/backend_qt4.py", line 71, in __init__
    QtWidgets.QWidget.__init__(self)
TypeError: __init__() takes exactly 2 arguments (1 given)

======================================================================
ERROR: matplotlib.tests.test_backend_qt4.test_control_alt
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/testing/decorators.py", line 118, in wrapped_function
    func(*args, **kwargs)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/testing/decorators.py", line 53, in failer
    result = f(*args, **kwargs)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/tests/test_backend_qt4.py", line 126, in test_control_alt
    'ctrl+alt')
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/testing/decorators.py", line 371, in backend_switcher
    result = func(*args, **kwargs)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/tests/test_backend_qt4.py", line 59, in assert_correct_key
    qt_canvas = plt.figure().canvas
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/pyplot.py", line 527, in figure
    **kwargs)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/backends/backend_qt4agg.py", line 46, in new_figure_manager
    return new_figure_manager_given_figure(num, thisFig)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/backends/backend_qt4agg.py", line 53, in new_figure_manager_given_figure
    canvas = FigureCanvasQTAgg(figure)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/backends/backend_qt4agg.py", line 71, in __init__
    FigureCanvasQT.__init__(self, figure)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/backends/backend_qt4.py", line 71, in __init__
    QtWidgets.QWidget.__init__(self)
TypeError: __init__() takes exactly 2 arguments (1 given)

======================================================================
ERROR: matplotlib.tests.test_backend_qt4.test_modifier_order
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/testing/decorators.py", line 118, in wrapped_function
    func(*args, **kwargs)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/testing/decorators.py", line 53, in failer
    result = f(*args, **kwargs)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/tests/test_backend_qt4.py", line 134, in test_modifier_order
    'ctrl+alt+super+' + unichr(225))
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/testing/decorators.py", line 371, in backend_switcher
    result = func(*args, **kwargs)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/tests/test_backend_qt4.py", line 59, in assert_correct_key
    qt_canvas = plt.figure().canvas
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/pyplot.py", line 527, in figure
    **kwargs)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/backends/backend_qt4agg.py", line 46, in new_figure_manager
    return new_figure_manager_given_figure(num, thisFig)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/backends/backend_qt4agg.py", line 53, in new_figure_manager_given_figure
    canvas = FigureCanvasQTAgg(figure)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/backends/backend_qt4agg.py", line 71, in __init__
    FigureCanvasQT.__init__(self, figure)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/backends/backend_qt4.py", line 71, in __init__
    QtWidgets.QWidget.__init__(self)
TypeError: __init__() takes exactly 2 arguments (1 given)

======================================================================
ERROR: matplotlib.tests.test_backend_qt4.test_backspace
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/testing/decorators.py", line 118, in wrapped_function
    func(*args, **kwargs)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/testing/decorators.py", line 53, in failer
    result = f(*args, **kwargs)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/tests/test_backend_qt4.py", line 142, in test_backspace
    'backspace')
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/testing/decorators.py", line 371, in backend_switcher
    result = func(*args, **kwargs)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/tests/test_backend_qt4.py", line 59, in assert_correct_key
    qt_canvas = plt.figure().canvas
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/pyplot.py", line 527, in figure
    **kwargs)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/backends/backend_qt4agg.py", line 46, in new_figure_manager
    return new_figure_manager_given_figure(num, thisFig)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/backends/backend_qt4agg.py", line 53, in new_figure_manager_given_figure
    canvas = FigureCanvasQTAgg(figure)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/backends/backend_qt4agg.py", line 71, in __init__
    FigureCanvasQT.__init__(self, figure)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/backends/backend_qt4.py", line 71, in __init__
    QtWidgets.QWidget.__init__(self)
TypeError: __init__() takes exactly 2 arguments (1 given)

======================================================================
ERROR: matplotlib.tests.test_backend_qt4.test_backspace_mod
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/testing/decorators.py", line 118, in wrapped_function
    func(*args, **kwargs)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/testing/decorators.py", line 53, in failer
    result = f(*args, **kwargs)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/tests/test_backend_qt4.py", line 150, in test_backspace_mod
    'ctrl+backspace')
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/testing/decorators.py", line 371, in backend_switcher
    result = func(*args, **kwargs)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/tests/test_backend_qt4.py", line 59, in assert_correct_key
    qt_canvas = plt.figure().canvas
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/pyplot.py", line 527, in figure
    **kwargs)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/backends/backend_qt4agg.py", line 46, in new_figure_manager
    return new_figure_manager_given_figure(num, thisFig)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/backends/backend_qt4agg.py", line 53, in new_figure_manager_given_figure
    canvas = FigureCanvasQTAgg(figure)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/backends/backend_qt4agg.py", line 71, in __init__
    FigureCanvasQT.__init__(self, figure)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/backends/backend_qt4.py", line 71, in __init__
    QtWidgets.QWidget.__init__(self)
TypeError: __init__() takes exactly 2 arguments (1 given)

======================================================================
ERROR: matplotlib.tests.test_backend_qt4.test_non_unicode_key
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/testing/decorators.py", line 118, in wrapped_function
    func(*args, **kwargs)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/testing/decorators.py", line 53, in failer
    result = f(*args, **kwargs)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/tests/test_backend_qt4.py", line 158, in test_non_unicode_key
    None)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/testing/decorators.py", line 371, in backend_switcher
    result = func(*args, **kwargs)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/tests/test_backend_qt4.py", line 59, in assert_correct_key
    qt_canvas = plt.figure().canvas
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/pyplot.py", line 527, in figure
    **kwargs)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/backends/backend_qt4agg.py", line 46, in new_figure_manager
    return new_figure_manager_given_figure(num, thisFig)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/backends/backend_qt4agg.py", line 53, in new_figure_manager_given_figure
    canvas = FigureCanvasQTAgg(figure)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/backends/backend_qt4agg.py", line 71, in __init__
    FigureCanvasQT.__init__(self, figure)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/backends/backend_qt4.py", line 71, in __init__
    QtWidgets.QWidget.__init__(self)
TypeError: __init__() takes exactly 2 arguments (1 given)

======================================================================
FAIL: matplotlib.tests.test_png.test_pngsuite.test
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/testing/decorators.py", line 53, in failer
    result = f(*args, **kwargs)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/testing/decorators.py", line 220, in do_test
    '(RMS %(rms).3f)'%err)
ImageComparisonFailure: images not close: /«PKGBUILDDIR»/result_images/test_png/pngsuite.png vs. /«PKGBUILDDIR»/result_images/test_png/pngsuite-expected.png (RMS 23.887)

======================================================================
FAIL: matplotlib.tests.test_png.test_imread_png_uint16
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/matplotlib/tests/test_png.py", line 45, in test_imread_png_uint16
    assert np.sum(img.flatten()) == 134184960
AssertionError

----------------------------------------------------------------------
Ran 5112 tests in 80416.746s

FAILED (KNOWNFAIL=11, SKIP=9, errors=12, failures=2)
```

**Comment by anntzer** [comment]
Closing as 1.5.0 is quite old now (and e.g. I recognize the Qt issues that have been fixed a while ago).  Feel free to reopen with more recent failures.
