### ISSUE TITLE
error in set_linestyle

### ISSUE THREAD

**Issue by Fedefyco** [matplotlib/matplotlib#5312]
Hi to everyone,

I'm running:

Anaconda 2.3.0 64-bit/Python 2.7.10/matplotlib 1.4.3 on a VM Ubuntu 14.04. I have a 3d matrix to plot, and since it comes from a tutorial on coursera, I have few doubts about it is correct. Now what I'm doing is running pyplot.pcolor(X,Y,U)
```
plt.pcolor(X,Y,U)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fedro/anaconda/lib/python2.7/site-packages/matplotlib/pyplot.py", line 3018, in pcolor
    ret = ax.pcolor(*args, **kwargs)
  File "/home/fedro/anaconda/lib/python2.7/site-packages/matplotlib/axes/_axes.py", line 4958, in pcolor
    collection = mcoll.PolyCollection(verts, **kwargs)
  File "/home/fedro/anaconda/lib/python2.7/site-packages/matplotlib/collections.py", line 822, in __init__
    Collection.__init__(self, **kwargs)
  File "/home/fedro/anaconda/lib/python2.7/site-packages/matplotlib/collections.py", line 109, in __init__
    self.set_linestyle(linestyles)
  File "/home/fedro/anaconda/lib/python2.7/site-packages/matplotlib/collections.py", line 527, in set_linestyle
    raise ValueError('Do not know how to convert %s to dashes' % ls)
ValueError: Do not know how to convert - to dashes
```
and I got this issue. Any suggestion about how to solve it?

**Comment by efiring** [comment]
Something is odd here, and I don't think this is a bug in mpl.  The line numbers in your traceback don't match the line numbers in version 1.4.3.

**Comment by Fedefyco** [comment]
Solved. Don't know exactly what happened. I first tried to conda remove and reinstall numpy and matplotlib: It didn't work. Then I conda removed matplotlib and numpy provided by anaconda, I installed them with pip and now it works.

**Comment by tacaswell** [comment]
Closing this as the issue seems to be a crossed installation.

One of the holes in the isolation that conda provides is that things installed via `--user` will still be found.
