### ISSUE TITLE
Hangs on OS X 10.11.1: No such file or directory: '~/.matplotlib/fontList.json'

### ISSUE THREAD

**Issue by an0** [matplotlib/matplotlib#5406]
```python
Traceback (most recent call last):
  File "xxx/lib/python3.5/site-packages/matplotlib-1.5.0+237.ga7b76bc-py3.5-macosx-10.11-x86_64.egg/matplotlib/font_manager.py", line 1441, in <module>
    fontManager = json_load(_fmcache)
  File "xxx/lib/python3.5/site-packages/matplotlib-1.5.0+237.ga7b76bc-py3.5-macosx-10.11-x86_64.egg/matplotlib/font_manager.py", line 991, in json_load
    with open(filename, 'r') as fh:
FileNotFoundError: [Errno 2] No such file or directory: '~/.matplotlib/fontList.json'
```

**Comment by tacaswell** [comment]
I am really confused on how that is getting out, it is wrapped in an un-conditional `try...except` https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/font_manager.py#L1440

What do you mean 'hangs'?  Rebuilding the font cache may take a long time the first time it runs.

Is this the complete trace-back?  What did you run to generate this?

**Comment by an0** [comment]
@tacaswell you are right. It just takes unexpected(to me) long time to finish, during which I thought it hangs.

**Comment by tacaswell** [comment]
No worries.  It will be faster the next time!

**Comment by an0** [comment]
👍
