### ISSUE TITLE
Segfault in matplotlib.tests.test_image:test_get_window_extent_for_AxisImage on python3.5

### ISSUE THREAD

**Issue by jenshnielsen** [matplotlib/matplotlib#5429]
On master here: https://travis-ci.org/matplotlib/matplotlib/jobs/89776539

Unfortunately this is not caught because we use the nose multiprocessing plugin just skips the test

**Comment by jenshnielsen** [comment]
It seems to be due to the test calling 
`fig.canvas.draw()` within a nose test.

**Comment by mdboom** [comment]
Traceback makes me think it's related to #5361

**Comment by mdboom** [comment]
```
#0  agg::pixfmt_alpha_blend_rgba<fixed_blender_rgba_plain<agg::rgba8T<agg::linear>, agg::order_rgba>, agg::row_accessor<unsigned char> >::blend_solid_hspan (this=this@entry=0x177a4d8, 
    x=x@entry=0, y=y@entry=991, len=<optimized out>, len@entry=4294967291, c=..., covers=0x1802000 <error: Cannot access memory at address 0x1802000>)
    at extern/agg24-svn/include/agg_pixfmt_rgba.h:1859
#1  0x00007fffe4e44d75 in agg::pixfmt_alpha_blend_rgba<fixed_blender_rgba_plain<agg::rgba8T<agg::linear>, agg::order_rgba>, agg::row_accessor<unsigned char> >::blend_solid_hspan (
    covers=<optimized out>, c=..., len=<optimized out>, y=991, x=0, this=0x177a4d8) at extern/agg24-svn/include/agg_pixfmt_rgba.h:1854
#2  RendererAgg::draw_text_image<numpy::array_view<unsigned char, 2> > (this=0x177a390, gc=..., image=..., x=<optimized out>, y=1006, angle=<optimized out>) at src/_backend_agg.h:792
#3  0x00007fffe4e3382e in PyRendererAgg_draw_text_image (self=0x7fffe7de9390, args=<optimized out>, kwds=<optimized out>) at src/_backend_agg_wrapper.cpp:240
#4  0x0000000000599cf9 in PyCFunction_Call (func=func@entry=0x7fffe7d59438, args=args@entry=0x7fffe7dc3e60, kwds=kwds@entry=0x0) at Objects/methodobject.c:109
```
