### ISSUE TITLE
RuntimeError: could not open display

### ISSUE THREAD

**Issue by datomnurdin** [matplotlib/matplotlib#5482]
I'm using python 2.7.10 and EI Capitan to test my script. I got this error message when using this library to generate plot.

```
(process:27893): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
Traceback (most recent call last):
  File "analyze_tweets.py", line 10, in <module>
    import matplotlib.pyplot as plt
  File "/usr/lib64/python2.7/site-packages/matplotlib/pyplot.py", line 97, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/usr/lib64/python2.7/site-packages/matplotlib/backends/__init__.py", line 25, in pylab_setup
    globals(),locals(),[backend_name])
  File "/usr/lib64/python2.7/site-packages/matplotlib/backends/backend_gtkagg.py", line 10, in <module>
    from matplotlib.backends.backend_gtk import gtk, FigureManagerGTK, FigureCanvasGTK,\
  File "/usr/lib64/python2.7/site-packages/matplotlib/backends/backend_gtk.py", line 13, in <module>
    import gtk; gdk = gtk.gdk
  File "/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py", line 64, in <module>
    _init()
  File "/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py", line 52, in _init
    _gtk.init_check()
RuntimeError: could not open display
```

My code

```
fig, ax = plt.subplots()
ax.tick_params(axis='x', labelsize=15)
ax.tick_params(axis='y', labelsize=10)
ax.set_xlabel('Languages', fontsize=15)
ax.set_ylabel('Number of tweets' , fontsize=15)
ax.set_title('Top 5 languages', fontsize=15, fontweight='bold')
tweets_by_lang[:5].plot(ax=ax, kind='bar', color='red')
```

Please advice. Thank you.

**Comment by efiring** [comment]
This question would be better posed to the matplotlib-users list https://mail.python.org/mailman/listinfo/matplotlib-users so I'm going to close this.  Your question relates to your particular installation.  As a quick note, though, you are using the gtkagg backend, which is an unusual choice for a Mac.  I think the error it is returning is because it can't find an X-server.  You would at least need Xquartz.
