### ISSUE TITLE
Trouble importing image_comparison decorator in v1.5

### ISSUE THREAD

**Issue by phobson** [matplotlib/matplotlib#5487]
Seems like the 1.5 no longer allows users to import testing decorators (e.g., `image_comparison`)

Consider the following similar conda environments:

```
conda create --name=_mpl14 python=3.4 matplotlib=1.5 nose --yes --quiet
conda create --name=_mpl15 python=3.5 matplotlib=1.5 nose --yes --quiet
paul@umpqua ~ $ source activate _mpl14
(_mpl14)paul@umpqua ~ $ python -c "from matplotlib.testing.decorators import image_comparison" # fine

paul@umpqua ~ $ source activate _mpl15
(_mpl15)paul@umpqua ~ $ python -c "from matplotlib.testing.decorators import image_comparison" # fails
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/paul/miniconda3/envs/_mpl15/lib/python3.5/site-packages/matplotlib/testing/decorators.py", line 19, in <module>
    import matplotlib.tests
ImportError: No module named 'matplotlib.tests'
```

Looks like both matplotlib.__init__ and matplotlib.tests.__init__ got modified a bit since version 1.4.

Is this expected? If not, I can take a stab at `git bisect`-ing the issue.

**Comment by WeatherGod** [comment]
I bet you that the problem is stemming from the bit of repackaging that was
done for v1.5, but I have no clue why there would be a difference between
py3.4 and py3.5... I do know that conda packages are now significantly
smaller because the test data has been stripped out, but I didn't think
that the test module was stripped out...

**Comment by phobson** [comment]
@WeatherGod Sorry -- there was a copy/paste error in the original message, which has since been corrected. 

Both versions use python 3.5, the difference needs to be mpl1.4 vs mpl1.5 to demonstrate the issue.

**Comment by jenshnielsen** [comment]
I think @WeatherGod is right this is a result of stripping the test data out. I cannot reproduce it with the pypi package which contains the test images but I can reproduce it with the conda package which does not

**Comment by phobson** [comment]
shoot -- this is going to be tricky (for me) to track down then. 

Seems like the best path forward is to track down Continuum's recipe, and use it to build locally until I can get it to work again. Hopefully I have a PR soon -- within a week maybe -- provided it's something y'all want tracked down.

**Comment by mdboom** [comment]
Breaking the image comparison decorators was unintentional.  However, you can install all the test data by installing `matplotlib-tests` in conda.  That *hopefully* should fix the issue for you.  In the meantime, I'll see if I can make the testing decorators not depend on the test data (which they shouldn't -- I suspect this is accidental).

**Comment by phobson** [comment]
@mdboom is that package in a private channel? I can't find it from the CLI or anaconda.org:
https://anaconda.org/search?q=matplotlib-tests

**Comment by mdboom** [comment]
I'm a little surprised it hasn't shown up in the main channel (but I can confirm that).  I'm investigating...

**Comment by phobson** [comment]
thanks so much, @mdboom

**Comment by twiecki** [comment]
Will we have to wait for matplotlib 1.6 or 2.0 for this to get fixed?

**Comment by WeatherGod** [comment]
Good question. @mdboom, was this backported to v1.5.x?

**Comment by jenshnielsen** [comment]
Yes the relevant pr is #5492 which was against 1.5.x

**Comment by jenshnielsen** [comment]
It's also only an issue with conda. So if conda did provide the matplotlib-tests package that would be a work around

**Comment by tacaswell** [comment]
This was fixed directly on 1.5.x https://github.com/matplotlib/matplotlib/pull/5492

The only question is if we do a 1.5.1 before 2.0

**Comment by twiecki** [comment]
I couldn't find a matplotlib-tests package in conda.

**Comment by jenshnielsen** [comment]
No they don't provide it at the moment as stated above. But if they did provide it it would be a work around that does not require a new release

**Comment by mdboom** [comment]
The matplotlib-tests package should be available in conda soon -- there was a glitch with it that is now resolved.

**Comment by twiecki** [comment]
Is matplotlib-tests available? Still can't find it.

**Comment by phobson** [comment]
@twiecki this works for me on Travis' Linux and Windows: https://anaconda.org/msarahan/matplotlib-tests

**Comment by twiecki** [comment]
I just confirmed that it seems to exist now.
