### ISSUE TITLE
Something fishy in png reading

### ISSUE THREAD

**Issue by mdboom** [matplotlib/matplotlib#5495]
We're seeing spurious test failures like:

```
======================================================================
ERROR: matplotlib.tests.test_cycles.test_marker_cycle.test
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/matplotlib/matplotlib/venv/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/matplotlib/matplotlib/venv/lib/python2.7/site-packages/matplotlib-1.5.0+34.g43afdd8-py2.7-linux-x86_64.egg/matplotlib/testing/decorators.py", line 53, in failer
    result = f(*args, **kwargs)
  File "/home/travis/build/matplotlib/matplotlib/venv/lib/python2.7/site-packages/matplotlib-1.5.0+34.g43afdd8-py2.7-linux-x86_64.egg/matplotlib/testing/decorators.py", line 210, in do_test
    self._tol, in_decorator=True)
  File "/home/travis/build/matplotlib/matplotlib/venv/lib/python2.7/site-packages/matplotlib-1.5.0+34.g43afdd8-py2.7-linux-x86_64.egg/matplotlib/testing/compare.py", line 314, in compare_images
    actualImage = _png.read_png_int(actual)
RuntimeError: Error setting jump
```

and 

```
======================================================================
ERROR: matplotlib.tests.test_cycles.test_marker_cycle.test
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/matplotlib/matplotlib/venv/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/matplotlib/matplotlib/venv/lib/python3.4/site-packages/matplotlib-1.5.0+34.g43afdd8-py3.4-linux-x86_64.egg/matplotlib/testing/decorators.py", line 53, in failer
    result = f(*args, **kwargs)
  File "/home/travis/build/matplotlib/matplotlib/venv/lib/python3.4/site-packages/matplotlib-1.5.0+34.g43afdd8-py3.4-linux-x86_64.egg/matplotlib/testing/decorators.py", line 210, in do_test
    self._tol, in_decorator=True)
  File "/home/travis/build/matplotlib/matplotlib/venv/lib/python3.4/site-packages/matplotlib-1.5.0+34.g43afdd8-py3.4-linux-x86_64.egg/matplotlib/testing/compare.py", line 314, in compare_images
    actualImage = _png.read_png_int(actual)
SystemError: error return without exception set
```

While there were recent changes to PNG *writing*, there haven't been recent changes to PNG *reading*, so I'm not sure what's up.  But probably shouldn't let this slide...

**Comment by tacaswell** [comment]
Digging into this a bit, there is one `goto exit` in `_read_png` which does not explicitly set an exception before hitting the goto (https://github.com/matplotlib/matplotlib/blob/master/src/_png.cpp#L368) This was last touched in
ba4016014cb4fb4927e36ce8ea429fed47dcb787 .  I have no guess as to why this is showing up intermittently now though.  Maybe travis has changed their infrastructure and we are hitting a weird race/edge case on opening files?

**Comment by mdboom** [comment]
> Digging into this a bit, there is one goto exit in _read_png which does not explicitly set an exception before hitting the goto (https://github.com/matplotlib/matplotlib/blob/master/src/_png.cpp#L368)

I think this is fine actually.  The exception is set inside `mpl_PyFile_OpenFile` (indirectly in `PyDict_GetItemString`).

I feel this is somehow related to file handling, just not sure what yet.

**Comment by productivememberofsociety666** [comment]
For the record, #5515 didn't fix it: https://travis-ci.org/matplotlib/matplotlib/jobs/94019696

**Comment by WeatherGod** [comment]
It is important to note that what I haven't seen lately is that we are now
seeing useful exception messages when something goes wrong with reading
images. We are seeing a wider variety of errors now when before it was a
single, generic error message. I suspect the issue might be with whatever
the underlying filesystem is on any particular docker instance.

**Comment by jenshnielsen** [comment]
I suspect that most of these issues are related to the nose multiprocessing. If someone sees any of this happen with the 3.5 job, which no longer runs multiprocessing to get correct coverage, please put a reference in here since that would disconfirm my theory

**Comment by tacaswell** [comment]
I am getting these failures locally as well now.

**Comment by mdboom** [comment]
That's promising, I guess.  For whatever reason, I've never seen them locally...

**Comment by tacaswell** [comment]
Also getting these locally

```python
======================================================================
FAIL: matplotlib.tests.test_backend_ps.test_savefig_to_stringio_with_usetex_eps
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tcaswell/source/other_source/nose/build/lib/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/tcaswell/source/my_source/matplotlib/lib/matplotlib/testing/decorators.py", line 138, in wrapped_function
    func(*args, **kwargs)
  File "/home/tcaswell/source/my_source/matplotlib/lib/matplotlib/testing/decorators.py", line 54, in failer
    result = f(*args, **kwargs)
  File "/home/tcaswell/source/my_source/matplotlib/lib/matplotlib/tests/test_backend_ps.py", line 96, in test_savefig_to_stringio_with_usetex_eps
    _test_savefig_to_stringio(format='eps')
  File "/home/tcaswell/source/my_source/matplotlib/lib/matplotlib/tests/test_backend_ps.py", line 54, in _test_savefig_to_stringio
    assert values[0] == values[1]
AssertionError

```
