### ISSUE TITLE
DLL load failed: cannot find specified procedure when importing matplotlib.pyplot

### ISSUE THREAD

**Issue by mmagnuski** [matplotlib/matplotlib#5507]
I'm on python3.4, most packages installed through conda.
Recently I get the following error when doing `import matplotlib.pyplot as plt`:

``` python
ImportError                               Traceback (most recent call last)
<ipython-input-41-eff513f636fd> in <module>()
----> 1 import matplotlib.pyplot as plt

C:\Users\Mikuś\Miniconda3\lib\site-packages\matplotlib\pyplot.py in <module>()
    107 
    108 from matplotlib.backends import pylab_setup
--> 109 _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
    110 
    111 

C:\Users\Mikuś\Miniconda3\lib\site-packages\matplotlib\backends\__init__.py in pylab_setup()
     30     # imports. 0 means only perform absolute imports.
     31     backend_mod = __import__(backend_name,
---> 32                              globals(),locals(),[backend_name],0)
     33 
     34     # Things we pull in from all backends

C:\Users\Mikuś\Miniconda3\lib\site-packages\matplotlib\backends\backend_qt4agg.py in <module>()
     15 from matplotlib.figure import Figure
     16 
---> 17 from .backend_qt5agg import NavigationToolbar2QTAgg
     18 from .backend_qt5agg import FigureCanvasQTAggBase
     19 

C:\Users\Mikuś\Miniconda3\lib\site-packages\matplotlib\backends\backend_qt5agg.py in <module>()
     16 
     17 from .backend_agg import FigureCanvasAgg
---> 18 from .backend_qt5 import QtCore
     19 from .backend_qt5 import QtGui
     20 from .backend_qt5 import FigureManagerQT

C:\Users\Mikuś\Miniconda3\lib\site-packages\matplotlib\backends\backend_qt5.py in <module>()
     29     figureoptions = None
     30 
---> 31 from .qt_compat import QtCore, QtGui, QtWidgets, _getSaveFileName, __version__
     32 from matplotlib.backends.qt_editor.formsubplottool import UiSubplotTool
     33 

C:\Users\Mikuś\Miniconda3\lib\site-packages\matplotlib\backends\qt_compat.py in <module>()
     89     if QT_API in [QT_API_PYQT, QT_API_PYQTv2]:  # PyQt4 API
     90 
---> 91         from PyQt4 import QtCore, QtGui
     92 
     93         try:

ImportError: DLL load failed: Nie można odnaleźć określonej procedury.
```

The last part is in polish and says "cannot find specified procedure".
I understand this is probably not your fault (is this a conda issue?), but would be thankful for any advice.

**Comment by jenshnielsen** [comment]
It's trying to load pyqt which should normally be installed as a dependency of matplotlib in conda. Can you check if `pyqt` and `qt` are installed i.e. listed in `conda list` and if not install them. If they are installed perhaps try reinstalling them

**Comment by mmagnuski** [comment]
Ok, I will try. BTW - unfortunately `conda list` gives me `UnicodeDecodeError`, but that is a completely differrent issue.

**Comment by mmagnuski** [comment]
My `pyqt` and `qt` versions:
```
pyqt                      4.11.4                   py34_3
qt                        4.8.7                    vc10_4  [vc10]
```

I tried using `conda uninstall` and then `conda install` but that only unlinks and then links specified packages.
So I tried a couple of `conda clean` commands after uninstall and then installed `pyqt` again. Unfortunatelly I am still getting the same error. :(

**Comment by jenshnielsen** [comment]
Just to be sure does it also happen if you do 

```
from PyQt4 import QtCore, QtGui
```
from a python shell?

**Comment by mmagnuski** [comment]
The same error pops up:
```python
from PyQt4 import QtCore, QtGui
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: DLL load failed: Nie można odnaleźć określonej procedury.
```

**Comment by tacaswell** [comment]
do

```
conda create -n mpl_clean matplotlib python=3.4
```

and try from inside that env?

**Comment by mmagnuski** [comment]
Thanks,
that just linked the packages in the new env as I had everything locally, but it worked! :grinning:
Should I reinstall miniconda then? What is the best way to make it work outside that environment?

**Comment by WeatherGod** [comment]
Sometimes, nuking from orbit is the only way to be sure... ;-)

**Comment by mmagnuski** [comment]
Ouch, 
conda install failed and now conda is not recognized:
```
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
An unexpected error has occurred, please consider sending the            |  28%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Users\Mikuś\Miniconda3\Scripts\conda-script.py", line 4, in <module>
  File "C:\Users\Mikuś\Miniconda3\lib\site-packages\conda\cli\main.py", line 195, in main
  File "C:\Users\Mikuś\Miniconda3\lib\site-packages\conda\cli\main.py", line 202, in args_func
  File "C:\Users\Mikuś\Miniconda3\lib\site-packages\conda\cli\main_install.py", line 45, in execute
  File "C:\Users\Mikuś\Miniconda3\lib\site-packages\conda\cli\install.py", line 423, in install
  File "C:\Users\Mikuś\Miniconda3\lib\site-packages\conda\plan.py", line 537, in execute_actions
  File "C:\Users\Mikuś\Miniconda3\lib\site-packages\conda\instructions.py", line 148, in execute_instructions
  File "C:\Users\Mikuś\Miniconda3\lib\site-packages\conda\instructions.py", line 91, in LINK_CMD
  File "C:\Users\Mikuś\Miniconda3\lib\site-packages\conda\instructions.py", line 87, in link
  File "C:\Users\Mikuś\Miniconda3\lib\site-packages\conda\install.py", line 613, in link
  File "C:\Users\Mikuś\Miniconda3\lib\os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [WinError 5] Odmowa dostępu: 'C:\\Users\\Mikuś\\Miniconda3\\Scripts'

D:\DATA
λ conda install matplotlib pandas seaborn
'conda' is not recognized as an internal or external command,
operable program or batch file.
```
Another nuke...

**Comment by WeatherGod** [comment]
I wonder if the Unicode characters in the filepath on a Windows system is
causing the issue? Perhaps try creating an ASCII user account and see if
that works? This might be more likely a python/conda issue.

**Comment by mmagnuski** [comment]
I'm using python 3 so I thought non-ascii characters in username should not be a problem. I have a separate issue for that on conda issues.
I recently installed Anaconda (previously I was using Miniconda) and I no longer have PermissionError, but the DLL error is still present when importing matplotlib.
I think I'm out of nukes :disappointed: 
Now all I am left with is massive radiation causing mutations in the DLLs... :grin:

**Comment by cbcoutinho** [comment]
I am having a similar issue with importing `matplotlib.pyplot` on windows using anaconda and python3. The main ticket tracking this issue is ContinuumIO/anaconda-issues#1672.

Essentially, there is a dll error when importing `matplotlib.pyplot`, `matplotlib` itself loads fine. Executing the following line:

```bash
python -c 'import matplotlib.pyplot'
```

results in the following traceback:

```python
python : Traceback (most recent call last):
At line:1 char:1
+ python -c 'import matplotlib.pyplot' 2> error.txt
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Traceback (most recent call last)::String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
  File "<string>", line 1, in <module>
  File "C:\Users\ccoutinho\AppData\Local\Continuum\Anaconda3\lib\site-packages\matplotlib\pyplot.py", line 29, in <modu
le>
    import matplotlib.colorbar
  File "C:\Users\ccoutinho\AppData\Local\Continuum\Anaconda3\lib\site-packages\matplotlib\colorbar.py", line 36, in <mo
dule>
    import matplotlib.contour as contour
  File "C:\Users\ccoutinho\AppData\Local\Continuum\Anaconda3\lib\site-packages\matplotlib\contour.py", line 21, in <mod
ule>
    import matplotlib.font_manager as font_manager
  File "C:\Users\ccoutinho\AppData\Local\Continuum\Anaconda3\lib\site-packages\matplotlib\font_manager.py", line 58, in
 <module>
    from matplotlib import afm, cbook, ft2font, rcParams, get_cachedir
ImportError: DLL load failed: The specified procedure could not be found.
```

I've been able to isolate the issue to importing the `ft2font` module:

```bash
$ python -c 'from matplotlib import ft2font'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: DLL load failed: The specified procedure could not be found.
```

I've tried fresh installs of anaconda without any luck, and the anaconda developers are at a loss as to how the problem could be solved on their end. We would really like some advice from you guys, if possible.

**Comment by cbcoutinho** [comment]
I tried creating a clean mpl environment (just pyhont=3 and matplotlib) as @tacaswell suggested, but that didn't work:

```bash
(mpl_clean) C:\Users\ccoutinho>python -c "import matplotlib.pyplot"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Development\anaconda3\envs\mpl_clean\lib\site-packages\matplotlib\pyplot.py", line 29, in <module>
    import matplotlib.colorbar
  File "C:\Development\anaconda3\envs\mpl_clean\lib\site-packages\matplotlib\colorbar.py", line 36, in <module>
    import matplotlib.contour as contour
  File "C:\Development\anaconda3\envs\mpl_clean\lib\site-packages\matplotlib\contour.py", line 21, in <module>
    import matplotlib.font_manager as font_manager
  File "C:\Development\anaconda3\envs\mpl_clean\lib\site-packages\matplotlib\font_manager.py", line 58, in <module>
    from matplotlib import afm, cbook, ft2font, rcParams, get_cachedir
ImportError: DLL load failed: The specified procedure could not be found.
```

**Comment by efiring** [comment]
Did you try uninstalling matplotlib and then installing the version from conda-forge?
```
conda install -c conda-forge matplotlib
```

**Comment by tacaswell** [comment]
This looks like ABI issues with freetype?

**Comment by cbcoutinho** [comment]
A workaround for this issue was suggested in ContinuumIO/anaconda-issues#1672, which is able to sufficiently solve the problem. I'm not sure if it could help @mmagnuski and this issue, but for me it's good enough.

**Comment by QuLogic** [comment]
I'm going to close this then.
