### ISSUE TITLE
Testfailures on windows

### ISSUE THREAD

**Issue by JanSchulz** [matplotlib/matplotlib#5610]
Currently the unittests produce a few test failures on windows:

https://ci.appveyor.com/project/mdboom/matplotlib/build/1.0.56/job/yxkw1tmjqv0hynkw

```
python tests.py || cmd /c "exit /b 0"
c:\projects\matplotlib\lib\matplotlib\__init__.py:1510: UserWarning: matplotlib is not built with the correct FreeType version to run tests.  Set local_freetype=True in setup.cfg and rebuild. Expect many image comparison failures below.
  "matplotlib is not built with the correct FreeType version to run "
....EKC:\Python34_64\envs\test-environment\lib\subprocess.py:754: ResourceWarning: unclosed file <_io.BufferedReader name=9>
  _cleanup()
C:\Python34_64\envs\test-environment\lib\subprocess.py:754: ResourceWarning: unclosed file <_io.BufferedWriter name=7>
  _cleanup()
C:\Python34_64\envs\test-environment\lib\subprocess.py:754: ResourceWarning: unclosed file <_io.BufferedReader name=8>
  _cleanup()
EKKKKK...KK.KK......KK...KK.KK.KK.KK.....KK.KK.KK.KK...KK..........................KK.KK.KK.KK...KK.KK.KK.KK.KK.KK.KK.KK.KK...KK..KK.KK.KK.KK.KK.KK.....KK.KK.KK..KK.KK.KK.KK.KK.KK.KK.KK.KK......KK........KK.KK.KK.KK.....KK...KK.KK.KK.KK.KK.KK..KK.KK.KK...KK...........KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.....KK...KK..KK.KK.KK.KK.............KK.KK.KK.KK.KK.KK.KK.KK.KK....KK........................................................KK....'gs' is not recognized as an internal or external command,
operable program or batch file.
'gs' is not recognized as an internal or external command,
operable program or batch file.
'latex' is not recognized as an internal or external command,
operable program or batch file.
'latex' is not recognized as an internal or external command,
operable program or batch file.
SSSSSSKKK.................KKKKKKKKKKKKKKK.KK....K..KK.KK.KK.KK........................SS..KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK..............c:\projects\matplotlib\lib\matplotlib\collections.py:364: UserWarning: Collection picker None could not be converted to float
  % self._picker)
....KK....................................KK..c:\projects\matplotlib\lib\matplotlib\colorbar.py:539: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 5 but corresponding boolean dimension is 4
  colors = np.asarray(colors)[igood]
c:\projects\matplotlib\lib\matplotlib\colorbar.py:539: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 5 but corresponding boolean dimension is 3
  colors = np.asarray(colors)[igood]
...........................................................................................K.KK.KK.........E..K...KK.KK.KK.KK.KKKK.KKKK.KKKK.K.....K............KK.KK..KK.KK.KK.KK..KK.KK.KK...KK.KKC:\Python34_64\envs\test-environment\lib\site-packages\numpy\lib\nanfunctions.py:227: RuntimeWarning: All-NaN axis encountered
  warnings.warn("All-NaN axis encountered", RuntimeWarning)
...................................................................................................................................................................................................................................................................................................................KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................K...KK..KK.KK.KK.KK.KK.....KK.KK......KK.KK.KK.KKK............................. 
Bad key "timezone" on line 1 in
c:\projects\matplotlib\lib\matplotlib\tests\test_utf32_be_rcparams.rc.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
........................................................................................KK...KK.KK.KK.KK.KK.KK.KK.KK.KK.....KK.KK.KK..KK.KK.KK...........KK.c:\projects\matplotlib\lib\matplotlib\figure.py:1100: UserWarning: sharex argument to add_subplots() was an integer. Did you intend to use add_subplot() (without 's')?
  "sharex argument to add_subplots() was an integer. "
.c:\projects\matplotlib\lib\matplotlib\figure.py:1100: UserWarning: sharex argument to add_subplots() was an integer. Did you intend to use add_subplot() (without 's')?
  "sharex argument to add_subplots() was an integer. "
......KK.....KK..KK.KK.KK..........................KK.KK.KK.KK.KK.KK.KK.KK.KK.KK................KK....................................................c:\projects\matplotlib\lib\matplotlib\cbook.py:136: MatplotlibDeprecationWarning: The set_color_cycle attribute was deprecated in version 1.5. Use set_prop_cycle instead.
  warnings.warn(message, mplDeprecation, stacklevel=1)
........S.....c:\projects\matplotlib\lib\matplotlib\tests\test_labeled_data_unpacking.py:399: RuntimeWarning: Second argument is ambiguous: could be a color spec but is in data. Using as data.
Either rename the entry in data or use three arguments to plot.
  assert_equal(funcy(None, "x", "y1", data=data),
.S...KK.KK.KK.KK.KK.KK.KK.KK.KK...KK.KK.KK.KK.KK.....KK.. 
======================================================================
ERROR: matplotlib.tests.test_animation.test_save_animation_smoketest('imagemagick', 'gif')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python34_64\envs\test-environment\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "c:\projects\matplotlib\lib\matplotlib\testing\decorators.py", line 138, in wrapped_function
    func(*args, **kwargs)
  File "c:\projects\matplotlib\lib\matplotlib\tests\test_animation.py", line 57, in check_save_animation
    anim.save(F.name, fps=30, writer=writer, bitrate=500)
  File "c:\projects\matplotlib\lib\matplotlib\animation.py", line 787, in save
    writer.grab_frame(**savefig_kwargs)
  File "c:\projects\matplotlib\lib\matplotlib\animation.py", line 230, in grab_frame
    dpi=self.dpi, **savefig_kwargs)
  File "c:\projects\matplotlib\lib\matplotlib\figure.py", line 1672, in savefig
    self.canvas.print_figure(*args, **kwargs)
  File "c:\projects\matplotlib\lib\matplotlib\backend_bases.py", line 2230, in print_figure
    **kwargs)
  File "c:\projects\matplotlib\lib\matplotlib\backends\backend_agg.py", line 512, in print_raw
    fileobj.write(renderer._renderer.buffer_rgba())
BrokenPipeError: [Errno 32] Broken pipe
 
======================================================================
ERROR: matplotlib.tests.test_animation.test_save_animation_smoketest('imagemagick_file', 'gif')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python34_64\envs\test-environment\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "c:\projects\matplotlib\lib\matplotlib\testing\decorators.py", line 138, in wrapped_function
    func(*args, **kwargs)
  File "c:\projects\matplotlib\lib\matplotlib\tests\test_animation.py", line 57, in check_save_animation
    anim.save(F.name, fps=30, writer=writer, bitrate=500)
  File "c:\projects\matplotlib\lib\matplotlib\animation.py", line 787, in save
    writer.grab_frame(**savefig_kwargs)
  File "C:\Python34_64\envs\test-environment\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "c:\projects\matplotlib\lib\matplotlib\animation.py", line 196, in saving
    self.finish()
  File "c:\projects\matplotlib\lib\matplotlib\animation.py", line 387, in finish
    + ' Try running with --verbose-debug')
RuntimeError: Error creating movie, return code: 4 Try running with --verbose-debug
 
======================================================================
ERROR: matplotlib.tests.test_font_manager.test_json_serialization
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python34_64\envs\test-environment\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "c:\projects\matplotlib\lib\matplotlib\tests\test_font_manager.py", line 33, in test_json_serialization
    json_dump(fontManager, temp.name)
  File "c:\projects\matplotlib\lib\matplotlib\font_manager.py", line 984, in json_dump
    with open(filename, 'w') as fh:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\tmpuay3njay'
 
----------------------------------------------------------------------
Ran 5772 tests in 398.349s
 ```

IMO experience, Windows' "Permission denied" errors can happen when a file is accessed to fast after another. The rest could be that it's missing a app?

**Comment by jenshnielsen** [comment]
As I said before I think the imagemagick issues is fixed by #5460 Can you try merging that into your branch?

**Comment by JanSchulz** [comment]
Just FYI, here is a testrun from py27 with the same errors.

```
ython tests.py || cmd /c "exit /b 0"
c:\projects\matplotlib\lib\matplotlib\__init__.py:1510: UserWarning: matplotlib is not built with the correct FreeType version to run tests.  Set local_freetype=True in setup.cfg and rebuild. Expect many image comparison failures below.
  "matplotlib is not built with the correct FreeType version to run "
....EEKKKKKK...KK.KK......KK...KK.KK.KK.KK.....KK.KK.KK.KK...KK..........................KK.KK.KK.KK...KK.KK.KK.KK.KK.KK.KK.KK.KK...KK..KK.KK.KK.KK.KK.KK.....KK.KK.KK..KK.KK.KK.KK.KK.KK.KK.KK.KK......KK........KK.KK.KK.KK.....KK...KK.KK.KK.KK.KK.KK..KK.KK.KK...KK...........KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.....KK...KK..KK.KK.KK.KK.............KK.KK.KK.KK.KK.KK.KK.KK.KK....KK........................................................KK....'gs' is not recognized as an internal or external command,
operable program or batch file.
'gs' is not recognized as an internal or external command,
operable program or batch file.
'latex' is not recognized as an internal or external command,
operable program or batch file.
'latex' is not recognized as an internal or external command,
operable program or batch file.
SSSSSSKKK.................KKKKKKKKKKKKKKK.KK....K..KK.KK.KK.KK........................SS..KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK..............c:\projects\matplotlib\lib\matplotlib\collections.py:364: UserWarning: Collection picker None could not be converted to float
  % self._picker)
....KK....................................KK..c:\projects\matplotlib\lib\matplotlib\colorbar.py:539: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 5 but corresponding boolean dimension is 4
  colors = np.asarray(colors)[igood]
c:\projects\matplotlib\lib\matplotlib\colorbar.py:539: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 5 but corresponding boolean dimension is 3
  colors = np.asarray(colors)[igood]
...........................................................................................K.KK.KK.........E..K...KK.KK.KK.KK.KKKK.KKKK.KKKK.K.....K............KK.KK..KK.KK.KK.KK..KK.KK.KK...KK.KKC:\Python27_64\envs\test-environment\lib\site-packages\numpy\lib\nanfunctions.py:227: RuntimeWarning: All-NaN axis encountered
  warnings.warn("All-NaN axis encountered", RuntimeWarning)
...................................................................................................................................................................................................................................................................................................................KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................K...KK..KK.KK.KK.KK.KK.....KK.KK......KK.KK.KK.KKK............................. 
Bad key "timezone" on line 1 in
c:\projects\matplotlib\lib\matplotlib\tests\test_utf32_be_rcparams.rc.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
........................................................................................KK...KK.KK.KK.KK.KK.KK.KK.KK.KK.....KK.KK.KK..KK.KK.KK...........KK.c:\projects\matplotlib\lib\matplotlib\figure.py:1100: UserWarning: sharex argument to add_subplots() was an integer. Did you intend to use add_subplot() (without 's')?
  "sharex argument to add_subplots() was an integer. "
.......KK.....KK..KK.KK.KK..........................KK.KK.KK.KK.KK.KK.KK.KK.KK.KK................KK....................................................c:\projects\matplotlib\lib\matplotlib\cbook.py:136: MatplotlibDeprecationWarning: The set_color_cycle attribute was deprecated in version 1.5. Use set_prop_cycle instead.
  warnings.warn(message, mplDeprecation, stacklevel=1)
........S.....c:\projects\matplotlib\lib\matplotlib\tests\test_labeled_data_unpacking.py:399: RuntimeWarning: Second argument is ambiguous: could be a color spec but is in data. Using as data.
Either rename the entry in data or use three arguments to plot.
  assert_equal(funcy(None, "x", "y1", data=data),
.S...KK.KK.KK.KK.KK.KK.KK.KK.KK...KK.KK.KK.KK.KK.....KK.. 
======================================================================
ERROR: matplotlib.tests.test_animation.test_save_animation_smoketest('imagemagick_file', u'gif')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27_64\envs\test-environment\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "c:\projects\matplotlib\lib\matplotlib\testing\decorators.py", line 138, in wrapped_function
    func(*args, **kwargs)
  File "c:\projects\matplotlib\lib\matplotlib\tests\test_animation.py", line 57, in check_save_animation
    anim.save(F.name, fps=30, writer=writer, bitrate=500)
  File "c:\projects\matplotlib\lib\matplotlib\animation.py", line 787, in save
    writer.grab_frame(**savefig_kwargs)
  File "C:\Python27_64\envs\test-environment\lib\contextlib.py", line 24, in __exit__
    self.gen.next()
  File "c:\projects\matplotlib\lib\matplotlib\animation.py", line 196, in saving
    self.finish()
  File "c:\projects\matplotlib\lib\matplotlib\animation.py", line 387, in finish
    + ' Try running with --verbose-debug')
RuntimeError: Error creating movie, return code: 4 Try running with --verbose-debug
 
======================================================================
ERROR: matplotlib.tests.test_animation.test_save_animation_smoketest('imagemagick', u'gif')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27_64\envs\test-environment\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "c:\projects\matplotlib\lib\matplotlib\testing\decorators.py", line 138, in wrapped_function
    func(*args, **kwargs)
  File "c:\projects\matplotlib\lib\matplotlib\tests\test_animation.py", line 57, in check_save_animation
    anim.save(F.name, fps=30, writer=writer, bitrate=500)
  File "c:\projects\matplotlib\lib\matplotlib\animation.py", line 787, in save
    writer.grab_frame(**savefig_kwargs)
  File "c:\projects\matplotlib\lib\matplotlib\animation.py", line 230, in grab_frame
    dpi=self.dpi, **savefig_kwargs)
  File "c:\projects\matplotlib\lib\matplotlib\figure.py", line 1672, in savefig
    self.canvas.print_figure(*args, **kwargs)
  File "c:\projects\matplotlib\lib\matplotlib\backend_bases.py", line 2230, in print_figure
    **kwargs)
  File "c:\projects\matplotlib\lib\matplotlib\backends\backend_agg.py", line 512, in print_raw
    fileobj.write(renderer._renderer.buffer_rgba())
IOError: [Errno 32] Broken pipe
 
======================================================================
ERROR: matplotlib.tests.test_font_manager.test_json_serialization
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27_64\envs\test-environment\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "c:\projects\matplotlib\lib\matplotlib\tests\test_font_manager.py", line 33, in test_json_serialization
    json_dump(fontManager, temp.name)
  File "c:\projects\matplotlib\lib\matplotlib\font_manager.py", line 984, in json_dump
    with open(filename, 'w') as fh:
IOError: [Errno 13] Permission denied: 'c:\\users\\appveyor\\appdata\\local\\temp\\1\\tmpalnlyd'
 
----------------------------------------------------------------------
Ran 5772 tests in 444.299s
 ```

**Comment by JanSchulz** [comment]
And here is the problem with the tempfile: http://stackoverflow.com/questions/23212435/permission-denied-to-write-to-my-temporary-file

**Comment by JanSchulz** [comment]
I added a woraround for the NamedTempfile problem: https://github.com/JanSchulz/matplotlib/commit/1179df765bfb999e91d3087bdc92c2b7216e21e5

**Comment by JanSchulz** [comment]
@jenshnielsen I merged the PR... Lets see what happens in #5604...

**Comment by cgohlke** [comment]
The test_json_serialization error was previously reported at https://github.com/matplotlib/matplotlib/pull/5278

**Comment by JanSchulz** [comment]
And it worked: no failures anymore:

```
python tests.py || cmd /c "exit /b 0"
c:\projects\matplotlib\lib\matplotlib\__init__.py:1510: UserWarning: matplotlib is not built with the correct FreeType version to run tests.  Set local_freetype=True in setup.cfg and rebuild. Expect many image comparison failures below.
  "matplotlib is not built with the correct FreeType version to run "
....KKKKKKKK...KK.KK.....KK...KK.KK.KK.KK.....KK.KK.KK.KK...KK..........................KK.KK.KK.KK...KK.KK.KK.KK.KK.KK.KK.KK.KK...KK..KK.KK.KK.KK.KK.KK.....KK.KK.KK..KK.KK.KK.KK.KK.KK.KK.KK.KK......KK........KK.KK.KK.KK.....KK...KK.KK.KK.KK.KK.KK..KK.KK.KK...KK...........KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.....KK...KK..KK.KK.KK.KK.............KK.KK.KK.KK.KK.KK.KK.KK.KK....KK........................................................KK....'gs' is not recognized as an internal or external command,
operable program or batch file.
'gs' is not recognized as an internal or external command,
operable program or batch file.
'latex' is not recognized as an internal or external command,
operable program or batch file.
'latex' is not recognized as an internal or external command,
operable program or batch file.
SSSSSSKKK.................KKKKKKKKKKKKKKK.KK....K..KK.KK.KK.KK........................SS..KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK..............c:\projects\matplotlib\lib\matplotlib\collections.py:360: UserWarning: Collection picker None could not be converted to float
  % self._picker)
....KK....................................KK..c:\projects\matplotlib\lib\matplotlib\colorbar.py:539: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 5 but corresponding boolean dimension is 4
  colors = np.asarray(colors)[igood]
c:\projects\matplotlib\lib\matplotlib\colorbar.py:539: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 5 but corresponding boolean dimension is 3
  colors = np.asarray(colors)[igood]
...........................................................................................K.KK.KK............K...KK.KK.KK.KK.KKKK.KKKK.KKKK.K.....K............KK.KK..KK.KK.KK.KK..KK.KK.KK...KK.KKC:\Python34_64\envs\test-environment\lib\site-packages\numpy\lib\nanfunctions.py:227: RuntimeWarning: All-NaN axis encountered
  warnings.warn("All-NaN axis encountered", RuntimeWarning)
...................................................................................................................................................................................................................................................................................................................KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK.KK............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................K...KK..KK.KK.KK.KK.KK.....KK.KK......KK.KK.KK.KKK............................. 
Bad key "timezone" on line 1 in
c:\projects\matplotlib\lib\matplotlib\tests\test_utf32_be_rcparams.rc.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
........................................................................................KK...KK.KK.KK.KK.KK.KK.KK.KK.KK.....KK.KK.KK..KK.KK.KK...........KK.c:\projects\matplotlib\lib\matplotlib\figure.py:1100: UserWarning: sharex argument to add_subplots() was an integer. Did you intend to use add_subplot() (without 's')?
  "sharex argument to add_subplots() was an integer. "
.c:\projects\matplotlib\lib\matplotlib\figure.py:1100: UserWarning: sharex argument to add_subplots() was an integer. Did you intend to use add_subplot() (without 's')?
  "sharex argument to add_subplots() was an integer. "
......KK.....KK..KK.KK.KK..........................KK.KK.KK.KK.KK.KK.KK.KK.KK.KK................KK....................................................c:\projects\matplotlib\lib\matplotlib\cbook.py:136: MatplotlibDeprecationWarning: The set_color_cycle attribute was deprecated in version 1.5. Use set_prop_cycle instead.
  warnings.warn(message, mplDeprecation, stacklevel=1)
........S.....c:\projects\matplotlib\lib\matplotlib\tests\test_labeled_data_unpacking.py:399: RuntimeWarning: Second argument is ambiguous: could be a color spec but is in data. Using as data.
Either rename the entry in data or use three arguments to plot.
  assert_equal(funcy(None, "x", "y1", data=data),
.S...KK.KK.KK.KK.KK.KK.KK.KK.KK...KK.KK.KK.KK.KK.....KK.. 
----------------------------------------------------------------------
Ran 5771 tests in 1359.446s
 
OK (KNOWNFAIL=1215, SKIP=10)
```
