### ISSUE TITLE
Test matplotlib.tests.test_backend_svg.test_determinism fails on OSX in virtual envs.

### ISSUE THREAD

**Issue by jenshnielsen** [matplotlib/matplotlib#5729]
Looks like it is trying to use the OSX backend which fails inside the virtual environment
```
======================================================================
ERROR: matplotlib.tests.test_backend_svg.test_determinism
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jhn/Envs/mplmasterpy35/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/jhn/Envs/mplmasterpy35/lib/python3.5/site-packages/matplotlib/testing/decorators.py", line 138, in wrapped_function
    func(*args, **kwargs)
  File "/Users/jhn/Envs/mplmasterpy35/lib/python3.5/site-packages/matplotlib/tests/test_backend_svg.py", line 154, in test_determinism
    'from matplotlib.tests.test_backend_svg '
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 584, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/jhn/Envs/mplmasterpy35/bin/python', '-R', '-c', 'from matplotlib.tests.test_backend_svg import _test_determinism;_test_determinism("determinism.svg")']' returned non-zero exit status 1
```

**Comment by mdboom** [comment]
I would guess that an explicit call to `matplotlib.use('svg')` in `_test_determinism` (which is run only in a subprocess and thus the backend change should succeed) would work.
