### ISSUE TITLE
UnicodeDecodeError matplotlib notebook backend

### ISSUE THREAD

**Issue by jakirkham** [matplotlib/matplotlib#5802]
Seeing this traceback in Jupyter console log when plotting in a Jupyter notebook using Firefox 43.0.2, matplotlib 1.5.0, python 2.7.11, ipython 4.0.1, ipykernel 4.1.1, notebook 4.0.6, etc.. Happens if I accidentally type something like `cmd+t` on Mac while a graph is selected.

```
Traceback (most recent call last):
  File "/opt/conda/lib/python2.7/site-packages/ipykernel/comm/manager.py", line 137, in comm_msg
    comm.handle_msg(msg)
  File "/opt/conda/lib/python2.7/site-packages/ipykernel/comm/comm.py", line 164, in handle_msg
    self._msg_callback(msg)
  File "/opt/conda/lib/python2.7/site-packages/matplotlib/backends/backend_nbagg.py", line 335, in on_message
    self.manager.handle_json(message)
  File "/opt/conda/lib/python2.7/site-packages/matplotlib/backends/backend_webagg_core.py", line 468, in handle_json
    self.canvas.handle_event(content)
  File "/opt/conda/lib/python2.7/site-packages/matplotlib/backends/backend_webagg_core.py", line 318, in handle_event
    key = _handle_key(event['key'])
  File "/opt/conda/lib/python2.7/site-packages/matplotlib/backends/backend_webagg_core.py", line 136, in _handle_key
    key = key[:key.index('k')] + value
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe0 in position 0: ordinal not in range(128)
```

**Comment by tacaswell** [comment]
Does this happen with python3?

**Comment by jakirkham** [comment]
Fair question, haven't tested that.

**Comment by jakirkham** [comment]
Seems to be a problem that occurs when using the Python 2 kernel. If the Python 3 kernel is used, the problem doesn't occur.

**Comment by tacaswell** [comment]
Given that this is a python2 only issue this is a low priority.

The fix is to improve the the unicode handling in 'backend_webagg_core.py:_handle_key'.

**Comment by tacaswell** [comment]
This issue also should not cause much trouble, there will just be key-events which fall on the floor (so you can not register an action to happen on 'cmd-t') and spam your log, but no functionality is lost.

**Comment by jakirkham** [comment]
FWIW it seems this happens when the Command key is pressed on Mac.

**Comment by jakirkham** [comment]
Also figured I'd add this [SO answer]( http://stackoverflow.com/a/3922353 ). Not sure if it helps in this context or not. The gist is that the Command key is handled differently by different browsers. On Firefox on Mac, it appears the associated event code is `224`.

**Comment by timhoffm** [comment]
Closing as we don't support Python 2 anymore.
