### ISSUE TITLE
1.5.1rc1: Could not import extension matplotlib.sphinxext.plot_directive (exception: No module named _path)

### ISSUE THREAD

**Issue by sandrotosi** [matplotlib/matplotlib#5807]
Hello,
I got this error when running the test suite on debian unstable

```
ERROR: test suite for <class 'matplotlib.sphinxext.tests.test_tinypages.TestTinyPages'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/suite.py", line 210, in run
    self.setUp()
  File "/usr/lib/python3/dist-packages/nose/suite.py", line 293, in setUp
    self.setupContext(ancestor)
  File "/usr/lib/python3/dist-packages/nose/suite.py", line 316, in setupContext
    try_run(context, names)
  File "/usr/lib/python3/dist-packages/nose/util.py", line 471, in try_run
    return func()
  File "/build/matplotlib-1.5.1~rc1/build/lib.linux-x86_64-3.4/matplotlib/sphinxext/tests/test_tinypages.py", line 58, in setup_class
    out, err))
RuntimeError: sphinx-build failed with stdout:
b'Running Sphinx v1.3.3\nmaking output directory...\n'
stderr:
b'\nExtension error:\nCould not import extension matplotlib.sphinxext.plot_directive (exception: No module named _path)\n'
```

this log is for python3.4 but it happens also on 2.7 and 3.5

_path is available at

```
/build/matplotlib-1.5.1~rc1/build/lib.linux-x86_64-3.4/matplotlib/_path.cpython-34m.so
```

and PYTHONPATH is set to `PYTHONPATH=build/lib.linux-x86_64-3.4` (we built it from within /build/matplotlib-1.5.1~rc1/)

**Comment by tacaswell** [comment]
I can not reproduce this locally

```
python setup.py build
...
22:53 $ env | grep PYTHON
PYTHONPATH=/home/redacted/matplotlib/build/lib.linux-x86_64-3.5/

22:53 $ python tests.py matplotlib.sphinxext
.
----------------------------------------------------------------------
Ran 1 test in 2.470s

OK

```

on an up-to-date arch box (which I agree is a different system).

I have a vague memory of an issue like this before.  Did we re-break it or was this an issues with 1.5.0 as well?

Would setting the fully path to `PYTHONPATH` help?  In the documentation test it uses `Popen` to invoke sphinx build.  Maybe the pwd that `sphinx-build` sees is not where the tests are being executed from?  The [`Popen`](https://docs.python.org/3.5/library/subprocess.html#subprocess.Popen) docs say what happens if `cwd` is not `None`, but not the default behavior.  On the other hand, I tried using a relative path and it did work for me locally so maybe not...

```
23:06 $ export PYTHONPATH=build/lib.linux-x86_64-3.5/
✔ ~/source/matplotlib [tst_fix_nonetwork|⚑ 2] 
23:06 $ python tests.py matplotlib.sphinxext
.
----------------------------------------------------------------------
Ran 1 test in 2.504s

OK

```

**Comment by sandrotosi** [comment]
so I was pretty sure that setting the full path in PYTHONPATH was not necessary, but I tried anyway and  it still fails; setting --verbosity=3 i got:

```
======================================================================
ERROR: test suite for <class 'matplotlib.sphinxext.tests.test_tinypages.TestTinyPages'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/suite.py", line 210, in run
    self.setUp()
  File "/usr/lib/python3/dist-packages/nose/suite.py", line 293, in setUp
    self.setupContext(ancestor)
  File "/usr/lib/python3/dist-packages/nose/suite.py", line 316, in setupContext
    try_run(context, names)
  File "/usr/lib/python3/dist-packages/nose/util.py", line 471, in try_run
    return func()
  File "/home/morph/deb/build-area/matplotlib-1.5.1~rc1/build/lib.linux-x86_64-3.5/matplotlib/sphinxext/tests/test_tinypages.py", line 58, in setup_class
    out, err))
RuntimeError: sphinx-build failed with stdout:
b'Running Sphinx v1.3.1\nmaking output directory...\n'
stderr:
b'\nExtension error:\nCould not import extension matplotlib.sphinxext.plot_directive (exception: No module named _path)\n'
```

that's likely due to:

```
            cmd = ['sphinx-build', '-W', '-b', 'html',
                   '-d', cls.doctree_dir,
                   TINY_PAGES,
                   cls.html_dir]
```

so the system sphinx-build is called: is it possible you have installed a recent version of mpl and so it doesnt fail on your system?

**Comment by tacaswell** [comment]
I removed the system package and verified that mpl failed to import before setting `PYTHONPATH`.

**Comment by tacaswell** [comment]
@sandrotosi I think this is a configuration issue on the debian build side.

**Comment by anntzer** [comment]
3b10e574e1 switched to using python -msphinx, which should have solved any remaining configuration issue.  Please reopen if still present as of master.

**Comment by Soumi7** [comment]
I am facing this error:
```
PYTHONPATH=..: sphinx-build -b html -d _build/doctrees -W --keep-going src _build/html
Running Sphinx v3.0.3

Extension error:
Could not import extension matplotlib.sphinxext.plot_directive (exception: No module named 'matplotlib')
Makefile:49: recipe for target 'html' failed
make: *** [html] Error 2
```

**Comment by tacaswell** [comment]
@Soumi7 Do you have Matplotlib installed in the environment you are running sphinx in?

**Comment by Soumi7** [comment]
Yes I do.
```
>>>matplotlib.__version__
>>>'3.2.1'
```

**Comment by tacaswell** [comment]
please do `which python` and `which sphinx-build`.  The issues is likely that you do not have sphinx installed in the venv / conda env in which you are trying that import.

Can you switch to `python -m sphinx` instead of `sphinx-build`.
