### ISSUE TITLE
AttributeError (no attribute 'callbacks') when setting attributes on pickle-loaded PatchCollection

### ISSUE THREAD

**Issue by jasoncpatton** [matplotlib/matplotlib#6048]
Using matplotlib version 1.5.1 installed from pip on Linux (Fedora 22 and CentOS 7).

Trying to set certain attributes (e.g. cmap, clim) on a PatchCollection loaded from a pickle leads to an `AttributeError: 'CallbackRegistry' object has no attribute 'callbacks'`:

``` python
Traceback (most recent call last):
  File "mpl_pickle_pc_test.py", line 48, in <module>
    pc_loaded.set_cmap(cmap)
  File "<venv>/lib/python2.7/site-packages/matplotlib/cm.py", line 308, in set_cmap
    self.changed()
  File "<venv>/lib/python2.7/site-packages/matplotlib/cm.py", line 359, in changed
    self.callbacksSM.process('changed', self)
  File "<venv>/lib/python2.7/site-packages/matplotlib/cbook.py", line 560, in process
    if s in self.callbacks:
AttributeError: 'CallbackRegistry' object has no attribute 'callbacks'
```

I've created a gist to reproduce this behavior: https://gist.github.com/jasoncpatton/c19d19b638ff10ece5d2

Oddly, if you catch the AttributeError and ignore it (set `use_try = True` in the gist), the attribute is actually set on the PatchCollection. However, using any methods that take the PatchCollection as a parameter (e.g. `fig.colorbar()`) will also break your code.

This behavior does not occur in version 1.4.3.

**Comment by tacaswell** [comment]
Can you test with either the master or 2.x branch?

**Comment by jasoncpatton** [comment]
_Assuming I did it right_ (installed into my venv using `pip install -e <git_cloned_dir>`, tried on master and v2.x, reported __version__ = ['1.5.1.post1337+g2b4e698', '1.5.1.post282+g918e80e'], respectively), I'm still getting the same errors.

**Comment by Fmajor** [comment]
I met the same problem
Using 
OS X EI Capitan 10.11.3
matplotlib.__version__='1.5.0'
pickle.__version__='$Revision: 72223 $'

when i try to drag and pan the fig object load from pickle.load(fileObject), i get the errors

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 1952, in motion_notify_event
    self.callbacks.process(s, event)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/cbook.py", line 562, in process
    proxy(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/cbook.py", line 429, in __call__
    return mtd(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 3012, in drag_pan
    a.drag_pan(self._button_pressed, event.key, event.x, event.y)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 3538, in drag_pan
    self.set_xlim(*result.intervalx)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 2776, in set_xlim
    self.callbacks.process('xlim_changed', self)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/cbook.py", line 559, in process
    if s in self.callbacks:
AttributeError: 'CallbackRegistry' object has no attribute 'callbacks'

although i have this error, i can reset the x_lim successfully by right-click-drag, but not the y_lim

**Comment by JeziL** [comment]
Meet the same error, too.

When I try to save a figure object loaded from pickle (or cPickle), the error occurs:
```
Traceback (most recent call last):
  File "test.py", line 40, in <module>
    plt.gcf().savefig('fig.png')
  File "/Library/Python/2.7/site-packages/matplotlib/figure.py", line 1565, in savefig
    self.canvas.print_figure(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/matplotlib/backend_bases.py", line 2151, in print_figure
    self.figure.dpi = dpi
  File "/Library/Python/2.7/site-packages/matplotlib/figure.py", line 411, in _set_dpi
    self.callbacks.process('dpi_changed', self)
  File "/Library/Python/2.7/site-packages/matplotlib/cbook.py", line 560, in process
    if s in self.callbacks:
AttributeError: 'CallbackRegistry' object has no attribute 'callbacks'
```
Unlike jasoncpatton's and Fmajor's situation, if you just ignore the AttributeError, the figure won't be saved.

Using:
- OS X EI Capitan 10.11.4
- matplotlib 1.5.1
- pickle revision 72223 (cPickle 1.71)

**Comment by Delosari** [comment]
In case the contribution may help: I am experiencing the same issue while loading the pickle on a wxpython frame. This issue also does not allow you to zoom in. 

You get the same error when you use the pan tool. However, you will still get some functionality when you use it. (This will also display the zoom previously selected)
