### ISSUE TITLE
anaconda package missing nose dependency

### ISSUE THREAD

**Issue by megies** [matplotlib/matplotlib#6097]
The packages on anaconda cloud are missing a dependency on nose, so it is not installed automatically and then this leads to package management raising exceptions when trying to use matplotlib.

Hope this is the right place to report this packaging issue.. otherwise please lat me know where to report.

example `conda info` output:
```
matplotlib 1.5.1 np110py35_0
----------------------------
file name   : matplotlib-1.5.1-np110py35_0.tar.bz2
name        : matplotlib
version     : 1.5.1
build number: 0
build string: np110py35_0
channel     : defaults
size        : 8.4 MB
date        : 2016-01-11
license     : PSF-based (http://matplotlib.sourceforge.net/users/license.html)
license_family: PSF
md5         : 255686571cea2826664d14ce3e8c4c56
installed environments:
dependencies:
    cycler
    freetype 2.5.*
    libpng 1.6.*
    numpy 1.10*
    pyparsing
    pyqt
    python 3.5*
    python-dateutil
    pytz
```

**Comment by jenshnielsen** [comment]
The conda packages are afaik maintained by the anaconda team and not directly by us.
However, matplotlib should only depend on nose for testing and we have deliberately removed the explicit pip dependency because users complained about it being unnecessary installed. Which error are you talking about and how  do you trigger it?

**Comment by megies** [comment]
Oh.. actually looking at the full traceback the missing nose wasn't triggered from matplotlib itself but from our own package (obspy) by using `load_entry_point` from `pkg_resources` module (my bad to not notice right away).

So while it is to some extent an external problem, it might still be worthwile to think about some solution for this. (although for us it'll go away as we have `nose` in our own dependencies for the most recent stable versions -- but potentially other people might still get hurt by this if other packages use `pkg_resources` in their code)

```
Traceback (most recent call last):
  File "/home/megies/anaconda/envs/0.10/lib/python2.7/site-packages/obspy/core/util/base.py", line 476, in make_format_plugin_table
    "obspy.plugin.%s.%s" % (group, name), method)
  File "/home/megies/anaconda/envs/0.10/lib/python2.7/site-packages/setuptools-20.1.1-py2.7.egg/pkg_resources/__init__.py", line 547, in load_entry_point
  File "/home/megies/anaconda/envs/0.10/lib/python2.7/site-packages/setuptools-20.1.1-py2.7.egg/pkg_resources/__init__.py", line 2720, in load_entry_point
  File "/home/megies/anaconda/envs/0.10/lib/python2.7/site-packages/setuptools-20.1.1-py2.7.egg/pkg_resources/__init__.py", line 2379, in load
  File "/home/megies/anaconda/envs/0.10/lib/python2.7/site-packages/setuptools-20.1.1-py2.7.egg/pkg_resources/__init__.py", line 2396, in require
  File "/home/megies/anaconda/envs/0.10/lib/python2.7/site-packages/setuptools-20.1.1-py2.7.egg/pkg_resources/__init__.py", line 828, in resolve
pkg_resources.DistributionNotFound: The 'nose>=0.11.1' distribution was not found and is required by matplotlib
```

**Comment by jenshnielsen** [comment]
Which version of matplotlib are you seeing this on. We do not have any dependency on any version of nose in version 1.5.1. If you try to run the tests it will just fail informing you to install nose 
1.4.x and older used to depend on nose via `install_requires` (1.5.0 has nose as test_requires but we dropped that due to several issues)

**Comment by efiring** [comment]
Closing; I gather there is no action we need to take.
