### ISSUE TITLE
appveyor is failing on build

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#6115]
It looks like build issues related to numpy for python < 3.5.  

attn @JanSchulz 

Looking at the history it does not look like there was a merge to master between it working and not working.

https://ci.appveyor.com/project/mdboom/matplotlib/history

worked: https://ci.appveyor.com/project/mdboom/matplotlib/build/1.0.963
failed: https://ci.appveyor.com/project/mdboom/matplotlib/build/1.0.964

Looking at diffs between the logs it looks like there is a change of py ~~3.4.3 -> 3.4.4~~ 3.4.4 -> 3.4.3

---
## pass env

```
conda list
# packages in environment at C:\conda\envs\test-environment:
#
backports-abc             0.4                       <pip>
backports_abc             0.4                      py34_0    defaults
cycler                    0.10.0                   py34_0    conda-forge
freetype                  2.5.5                    vc10_0  [vc10]  defaults
funcsigs                  0.4                      py34_0    defaults
jpeg                      8d                       vc10_0  [vc10]  defaults
libpng                    1.6.17                   vc10_1  [vc10]  defaults
libtiff                   4.0.6                    vc10_1  [vc10]  defaults
mkl                       11.3.1                        0    defaults
mock                      1.3.0                    py34_0    defaults
msinttypes                r26                           0    conda-forge
msvc_runtime              1.0.1                    vc10_0  [vc10]  defaults
nose                      1.3.7                    py34_0    defaults
numpy                     1.10.4                   py34_0    defaults
pbr
                    1.3.0                    py34_0    defaults
pip                       8.0.3                    py34_0    defaults
pyparsing                 2.0.3                    py34_0    defaults
pyqt                      4.11.4                   py34_5    defaults
python                    3.4.4                         2    defaults
python-dateutil           2.4.2                    py34_0    defaults
pytz                      2015.7                   py34_0    defaults
qt                        4.8.7                    vc10_6  [vc10]  defaults
setuptools                20.1.1                   py34_0    defaults
sip                       4.16.9                   py34_2    defaults
six                       1.10.0                   py34_0    defaults
tk                        8.5.18                   vc10_0  [vc10]  defaults
tornado                   4.3                      py34_0    defaults
wheel                     0.29.0                   py34_0    defaults
zlib
  1.2.8                    vc10_2  [vc10]  defaults
%CMD_IN_ENV% python setup.py develop
```
## fail env

```
conda list
# packages in environment at C:\conda\envs\test-environment:
#
backports-abc             0.4                       <pip>
backports_abc             0.4                      py34_0    defaults
cycler                    0.10.0                   py34_0    conda-forge
freetype                  2.5.5                    vc10_0  [vc10]  defaults
funcsigs                  0.4                      py34_0    defaults
libpng                    1.6.17                   vc10_1  [vc10]  defaults
mkl                       11.3.1                        0    defaults
mock                      1.3.0                    py34_0    defaults
msinttypes                r26                           0    conda-forge
nose                      1.3.7                    py34_0    defaults
numpy                     1.10.4                   py34_0    defaults
pbr                       1.3.0                    py34_0    defaults
pip                       8.0.3                    py34_0    defaults
pyparsing                 2.0.3                    py34_0    defaults
pyqt
  4.10.4                   py34_1    defaults
python                    3.4.3                         0    defaults
python-dateutil           2.4.2                    py34_0    defaults
pytz                      2015.7                   py34_0    defaults
setuptools                20.1.1                   py34_0    defaults
six                       1.10.0                   py34_0    defaults
tk                        8.5.18                   vc10_0  [vc10]  defaults
tornado                   4.3                      py34_0    defaults
wheel                     0.29.0                   py34_0    defaults
zlib                      1.2.8                    vc10_2  [vc10]  defaults
%CMD_IN_ENV% python setup.py develop
Configuring Windows SDK "v7.1" for Python 3 on a 64 bit architecture
```

---

```
[snip]
running build_ext
building 'matplotlib.ft2font' extension
Traceback (most recent call last):
  File "setup.py", line 308, in <module>
    **extra_args
  File "C:\conda\envs\_build\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\conda\envs\_build\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\conda\envs\_build\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "c:\conda\envs\_build\lib\site-packages\setuptools-20.1.1-py3.4.egg\setuptools\command\install.py", line 67, in run
  File "c:\conda\envs\_build\lib\site-packages\setuptools-20.1.1-py3.4.egg\setuptools\command\install.py", line 109, in do_egg_install
  File "C:\conda\envs\_build\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\conda\envs\_build\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "c:\conda\envs\_build\lib\site-packages\setuptools-20.1.1-py3.4.egg\setuptools\command\bdist_egg.py", line 161, in run
  File "c:\conda\envs\_build\lib\site-packages\setuptools-20.1.1-py3.4.egg\setuptools\command\bdist_egg.py", line 147, in call_command
  File "C:\conda\envs\_build\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\conda\envs\_build\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "c:\conda\envs\_build\lib\site-packages\setuptools-20.1.1-py3.4.egg\setuptools\command\install_lib.py", line 10, in run
  File "C:\conda\envs\_build\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "C:\conda\envs\_build\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\conda\envs\_build\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 149, in run
    return BuildExtCommand.run(self)
  File "c:\conda\envs\_build\lib\site-packages\setuptools-20.1.1-py3.4.egg\setuptools\command\build_ext.py", line 49, in run
  File "C:\conda\envs\_build\lib\distutils\command\build_ext.py", line 339, in run
    self.build_extensions()
  File "C:\conda\envs\_build\lib\distutils\command\build_ext.py", line 448, in build_extensions
    self.build_extension(ext)
  File "c:\conda\envs\_build\lib\site-packages\setuptools-20.1.1-py3.4.egg\setuptools\command\build_ext.py", line 174, in build_extension
  File "C:\conda\envs\_build\lib\distutils\command\build_ext.py", line 500, in build_extension
    include_dirs=ext.include_dirs,
  File "C:\conda\conda-bld\work\setupext.py", line 850, in __get__
    result = obj._hooks[self._name]() + result
  File "C:\conda\conda-bld\work\setupext.py", line 870, in include_dirs_hook
    import numpy
  File "C:\conda\envs\_build\lib\site-packages\numpy\__init__.py", line 180, in <module>
    from . import add_newdocs
  File "C:\conda\envs\_build\lib\site-packages\numpy\add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "C:\conda\envs\_build\lib\site-packages\numpy\lib\__init__.py", line 8, in <module>
    from .type_check import *
  File "C:\conda\envs\_build\lib\site-packages\numpy\lib\type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "C:\conda\envs\_build\lib\site-packages\numpy\core\__init__.py", line 14, in <module>
    from . import multiarray
ImportError: DLL load failed: The specified module could not be found.

C:\conda\conda-bld\work>if errorlevel 1 exit 1 
Command failed: C:\windows\system32\cmd.exe /c call bld.bat
Command exited with code 1
```

**Comment by tacaswell** [comment]
Sorry, I flipped the fail/pass env in my initial post.  If you are reading this in GH I have fixed it, if you are reading the emails they are flipped.

**Comment by tacaswell** [comment]
I have a suspicion that this might a bug due to the new conda dependency solver as the command

```shell
conda create -y -q -n test-environment python=%PYTHON_VERSION% pip setuptools numpy python-dateutil freetype msinttypes tk pyparsing pytz tornado libpng zlib pyqt cycler nose mock
```

results in different environments

**Comment by JanSchulz** [comment]
I've no clue why this error happen but you guess your suspicion might be correct. It looks like #6116 fix it, thanks!

**Comment by JanSchulz** [comment]
It seems one of the differences between the linked logs is conda 3.19.3-py27_0 (works) vs 4.0.0-py27_0 . What I don't understand is why this worked before?

There seems to be two different errors: on py2.7 it fails with a missing libpng and on 3.4 with some problems on numpy imports.

CC: @mcg1969 for some advise?

**Comment by mcg1969** [comment]
I can take a look later today, but we have identified and fixed one issue in 4.0.0 that will be pushed out ASAP.

**Comment by mcg1969** [comment]
Can you give me some specifics here on what you expect `conda` to do here? Please keep in mind: the previous conda solver was broken in numerous ways; it's not sufficient to simply say "the behavior has changed", because that was the goal :-) But if you think that conda is not producing the proper package solution here, let's figure that out. It may indeed be a new or remaining issue in the solver, and it might also be that it's now interpreting the metadata properly, and that metadata needs adjusting. (We've already seen that in one instance.)

**Comment by JanSchulz** [comment]
@mcg1969 It's more of a "if this is now ok, we are ok" thing :-) IMO there are two things: 

* why didn't the 2.7 builds fail earlier with the missing libpng?
* why does it seem that we now need a explicit dependency on `msvc_runtime`

-> PR in #6116

**Comment by mcg1969** [comment]
This seems to be related to the `msvc_runtime` issue: https://github.com/ContinuumIO/anaconda-issues/issues/443#issuecomment-193270154

I think that's something that's going to be fixed very soon, possibly with a metadata-only fix.

**Comment by mcg1969** [comment]
We did find a couple of issues related to features (which `msvc_runtime` controls) that might have affected this issue. It might be worth revisiting this now that conda 4.0.2 is out.

**Comment by anntzer** [comment]
Clearly seems resolved now.
