### ISSUE TITLE
Can´t make matplotlib run in my computer

### ISSUE THREAD

**Issue by jenninascimentoschulze** [matplotlib/matplotlib#6163]
Hi,

I am using the python3.5

when I try to call matplotlib this message occures

jennifers-mbp:~ jennifercatherinenascimentoschulze$ python /Users/jennifercatherinenascimentoschulze/Documents/2016.01/Praktikum_Frank/Scripts/sendtoreinerscript.py
Traceback (most recent call last):
  File "/Users/jennifercatherinenascimentoschulze/Documents/2016.01/Praktikum_Frank/Scripts/sendtoreinerscript.py", line 15, in <module>
    import matplotlib.pyplot as plt
  File "/Users/jennifercatherinenascimentoschulze/anaconda/lib/python3.5/site-packages/matplotlib/__init__.py", line 1131, in <module>
    rcParams = rc_params()
  File "/Users/jennifercatherinenascimentoschulze/anaconda/lib/python3.5/site-packages/matplotlib/__init__.py", line 975, in rc_params
    return rc_params_from_file(fname, fail_on_error)
  File "/Users/jennifercatherinenascimentoschulze/anaconda/lib/python3.5/site-packages/matplotlib/__init__.py", line 1100, in rc_params_from_file
    config_from_file = _rc_params_in_file(fname, fail_on_error)
  File "/Users/jennifercatherinenascimentoschulze/anaconda/lib/python3.5/site-packages/matplotlib/__init__.py", line 1018, in _rc_params_in_file
    with _open_file_or_url(fname) as fd:
  File "/Users/jennifercatherinenascimentoschulze/anaconda/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/Users/jennifercatherinenascimentoschulze/anaconda/lib/python3.5/site-packages/matplotlib/__init__.py", line 1000, in _open_file_or_url
    encoding = locale.getdefaultlocale()[1]
  File "/Users/jennifercatherinenascimentoschulze/anaconda/lib/python3.5/locale.py", line 559, in getdefaultlocale
    return _parse_localename(localename)
  File "/Users/jennifercatherinenascimentoschulze/anaconda/lib/python3.5/locale.py", line 487, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: UTF-8

I am new in using this programe, and I have no clue of what to do! If someone could help this would be great, thank you!

**Comment by mdboom** [comment]
Apple misconfigures the `LANG` environment variable to something that is not ISO standard and Python doesn't like it.

Issue #5931 works around the problem, and will make it into the next release of matplotlib.  You can also, in the meantime, set LANG to something parseable like `en_US.UTF-8`, e.g. by adding to your `.profile`:

```
export LANG=en_US.UTF-8
```
