### ISSUE TITLE
Issue saving figure as eps when using gouraud shaded triangulation

### ISSUE THREAD

**Issue by peynmurray** [matplotlib/matplotlib#6226]
I'm running python 3.4 on Debian 8.3, and am using the Qt5Agg backend. When I call savefig() or use the toolbar widget to save a figure that has a gouraud shaded triangulation, I get the following stacktrace:

```python
Traceback (most recent call last):
  File "/home/tps/PyCharmProjects/test/test_PlotWindow.py", line 323, in saveFigRButtonClicked
    savefig(fname)
  File "/usr/local/lib/python3.4/dist-packages/matplotlib/pyplot.py", line 688, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/matplotlib/figure.py", line 1565, in savefig
    self.canvas.print_figure(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/matplotlib/backends/backend_qt5agg.py", line 196, in print_figure
    FigureCanvasAgg.print_figure(self, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/matplotlib/backend_bases.py", line 2232, in print_figure
    **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/matplotlib/backends/backend_ps.py", line 995, in print_eps
    return self._print_ps(outfile, 'eps', *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/matplotlib/backends/backend_ps.py", line 1023, in _print_ps
    **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/matplotlib/backends/backend_ps.py", line 1113, in _print_figure
    self.figure.draw(renderer)
  File "/usr/local/lib/python3.4/dist-packages/matplotlib/artist.py", line 61, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/matplotlib/figure.py", line 1159, in draw
    func(*args)
  File "/usr/local/lib/python3.4/dist-packages/matplotlib/artist.py", line 61, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/matplotlib/axes/_base.py", line 2324, in draw
    a.draw(renderer)
  File "/usr/local/lib/python3.4/dist-packages/matplotlib/artist.py", line 61, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/matplotlib/collections.py", line 1694, in draw
    renderer.draw_gouraud_triangles(gc, verts, colors, transform.frozen())
  File "/usr/local/lib/python3.4/dist-packages/matplotlib/backends/backend_ps.py", line 867, in draw_gouraud_triangles
    stream = quote_ps_string(streamarr.tostring())
  File "/usr/local/lib/python3.4/dist-packages/matplotlib/backends/backend_ps.py", line 170, in quote_ps_string
    s=s.replace("\\", "\\\\")
TypeError: expected bytes, bytearray or buffer compatible object
```

**Comment by tacaswell** [comment]
Can you provide a minimal example which produces this?

**Comment by peynmurray** [comment]
Sorry for the slow response, see below. Use either the toolbar to save the figure as a .eps file, or uncomment the savefig() line.


from numpy import *
from matplotlib.pyplot import *
from matplotlib.tri import triangulation
from numpy.random import uniform

npts = 1000

x = uniform(-100, 100, npts)
y = uniform(-100, 100, npts)
z = sin(x)*cos(y)

triang = triangulation.Triangulation(x, y)
im = tripcolor(triang, z, shading="gouraud")

#savefig("test.eps")

show()
