### ISSUE TITLE
Cant get emoji working in Pie chart legend with google app engine. Need help.

### ISSUE THREAD

**Issue by VishvajitP** [matplotlib/matplotlib#6438]
- Python-2.7
- Google app engine

**Comment by tacaswell** [comment]
Almost certainly a font issue.  You need to use a font which emoji that is available on GAE.

With out more information there is not much we can do to help you.

**Comment by tacaswell** [comment]
I would also suggest sending this question (with a minimal example) to the mailing list (matplotlib-users@python.org you will need to sign up for the list to post un-moderated) which will get wider attention and is better suited for usage questions (rather than bugs or feature requests).

**Comment by VishvajitP** [comment]
I have added the fonts `Symbola` and `Roboto-Regular` which do support the emoji. I am trying to draw a table with reportlab along with a pie chart using matplotlib in the same pdf file.And evidently I can see the black and white coloured in my remaining part of the page [https://kaviraj.me/generating-pdf-containing-emoji-python/](reportlab-emoji) but not in the pie chart.

**Comment by WeatherGod** [comment]
After adding the fonts, you will need to clear matplotlib's font-cache so
that it can find the new fonts at the next run.

**Comment by VishvajitP** [comment]
@WeatherGod Yes agree. But in case of gae clearing the cache is not required 

[https://cloud.google.com/appengine/docs/python/tools/using-libraries-python-27#matplotlib](url)

**Comment by VishvajitP** [comment]
I get this error when tried 

`plt.savefig(ram, facecolor="#FFFFFF", transparent=True, format="png")`



'NoneType' object has no attribute 'endswith' (/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py:1528)
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 310, in post
    self.run_from_request()
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 305, in run_from_request
    run(self.request.body)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 147, in run
    return func(*args, **kwds)
  File "/base/data/home/apps/s~devel-walnut-backend-2014/dev-8.392875017263096787/utils/report.py", line 665, in create_data
    top_merchant_count)
  File "/base/data/home/apps/s~devel-walnut-backend-2014/dev-8.392875017263096787/utils/report_utils.py", line 517, in draw_pdf_header
    category_img = draw_pie_chart(top_categories, total_amount_category)
  File "/base/data/home/apps/s~devel-walnut-backend-2014/dev-8.392875017263096787/utils/report_utils.py", line 340, in draw_pie_chart
    transparent=True, format="png")
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/matplotlib-1.2.0/matplotlib/pyplot.py", line 472, in savefig
    return fig.savefig(*args, **kwargs)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/matplotlib-1.2.0/matplotlib/figure.py", line 1363, in savefig
    self.canvas.print_figure(*args, **kwargs)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/matplotlib-1.2.0/matplotlib/backend_bases.py", line 2093, in print_figure
    **kwargs)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/matplotlib-1.2.0/matplotlib/backends/backend_agg.py", line 491, in print_png
    FigureCanvasAgg.draw(self)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/matplotlib-1.2.0/matplotlib/backends/backend_agg.py", line 439, in draw
    self.figure.draw(self.renderer)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/matplotlib-1.2.0/matplotlib/artist.py", line 54, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/matplotlib-1.2.0/matplotlib/figure.py", line 999, in draw
    func(*args)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/matplotlib-1.2.0/matplotlib/artist.py", line 54, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/matplotlib-1.2.0/matplotlib/axes.py", line 2086, in draw
    a.draw(renderer)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/matplotlib-1.2.0/matplotlib/artist.py", line 54, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/matplotlib-1.2.0/matplotlib/text.py", line 531, in draw
    bbox, info = self._get_layout(renderer)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/matplotlib-1.2.0/matplotlib/text.py", line 304, in _get_layout
    ismath=False)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/matplotlib-1.2.0/matplotlib/backends/backend_agg.py", line 199, in get_text_width_height_descent
    renderer=self)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/matplotlib-1.2.0/matplotlib/texmanager.py", line 604, in get_text_width_height_descent
    dvifile = self.make_dvi(tex, fontsize)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/matplotlib-1.2.0/matplotlib/texmanager.py", line 346, in make_dvi
    basefile = self.get_basefile(tex, fontsize)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/matplotlib-1.2.0/matplotlib/texmanager.py", line 183, in get_basefile
    return os.path.join(self.texcache, md5(bytes).hexdigest())
  File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/posixpath.py", line 77, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'

**Comment by tacaswell** [comment]
On GAE we do not have access to a writable file system so we can not create any caches.

I strongly suggest that you move this discussion to the mailing list.
