### ISSUE TITLE
axhline and axvline linestyle as on-off seq doesn't work if set directly in function call

### ISSUE THREAD

**Issue by grg2rsr** [matplotlib/matplotlib#6449]
the following does not work:
```
import matplotlib.pyplot as plt
ls = (0,(2,2))
plt.plot()
line = plt.axvline(1,linestyle=ls)
```

however:
```
line.set_linestyle(ls)
```
produces the expected result. both `axhline` and `axvline` are affected, `axhspan` and `axvspan` not.

matplotlib '1.5.1' installed through Anaconda on Ubuntu 15.10. 

Traceback:
```
Traceback (most recent call last):
  File "/home/georg/python/linestyle_bug.py", line 13, in <module>
    line = plt.axhline(0,1,linestyle=ls)
  File "/home/georg/anaconda2/lib/python2.7/site-packages/matplotlib/pyplot.py", line 2574, in axhline
    ret = ax.axhline(y=y, xmin=xmin, xmax=xmax, **kwargs)
  File "/home/georg/anaconda2/lib/python2.7/site-packages/matplotlib/axes/_axes.py", line 749, in axhline
    l = mlines.Line2D([xmin, xmax], [y, y], transform=trans, **kwargs)
  File "/home/georg/anaconda2/lib/python2.7/site-packages/matplotlib/lines.py", line 332, in __init__
    self.set_linestyle(linestyle)
  File "/home/georg/anaconda2/lib/python2.7/site-packages/matplotlib/lines.py", line 1029, in set_linestyle
    self.set_dashes(ls[1])
  File "/home/georg/anaconda2/lib/python2.7/site-packages/matplotlib/lines.py", line 1165, in set_dashes
    if self._dashSeq != seq:
AttributeError: 'Line2D' object has no attribute '_dashSeq'
```

**Comment by tacaswell** [comment]
Thank you for reporting this.  I can not reproduce this on v1.5.x and think this is a variation on https://github.com/matplotlib/matplotlib/issues/5850 which is fixed by https://github.com/matplotlib/matplotlib/pull/5852

Please ping to have this re-opened if you can reproduce this on any of the active dev branches.
