### ISSUE TITLE
import matplotlib.pyplot as plt throws an erro

### ISSUE THREAD

**Issue by ksrinidhipatil** [matplotlib/matplotlib#6742]
Using windows 10 
python 2.7 
used pip install matplotlib 
import matplotlib works well but when "import matplotlib.pyplot as plt" the following course of errors occur

Using Eclipse IDE and even the python interpreter throws same error 
please help

Thank you  

import matplotlib.pyplot as plt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\matplotlib\pyplot.py", line 114, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "C:\Python27\lib\site-packages\matplotlib\backends\__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "C:\Python27\lib\site-packages\matplotlib\backends\backend_tkagg.py", line 6, in <module>
    from matplotlib.externals.six.moves import tkinter as Tk
  File "C:\Python27\lib\site-packages\matplotlib\externals\six.py", line 199, in load_module
    mod = mod._resolve()
  File "C:\Python27\lib\site-packages\matplotlib\externals\six.py", line 113, in _resolve
    return _import_module(self.mod)
  File "C:\Python27\lib\site-packages\matplotlib\externals\six.py", line 80, in _import_module
    __import__(name)
  File "C:\Python27\lib\lib-tk\Tkinter.py", line 38, in <module>
    import FixTk
  File "C:\Python27\lib\lib-tk\FixTk.py", line 65, in <module>
    import _tkinter
ImportError: DLL load failed: %1 is not a valid Win32 application.

**Comment by jenshnielsen** [comment]
It looks like there is something broken with the TK installation which should be part of your python installation and which matplotlib uses for the TK backend. 

What happens if you do?
```
import Tkinter
```

Alternatively you can switch to a different backend (QT4/5) if you have PyQT4/5 installed.

```
import matplotlib
matplotlib.use('QT4Agg')
import matplotlib.pyplot as plt
```

**Comment by ksrinidhipatil** [comment]
now it doesn't throw any error!!
I had pyQT4 installed
it works well now..
Thank You @jenshnielsen

**Comment by jenshnielsen** [comment]
Closing then. Feel free to reopen if there is anything else we can do
