### ISSUE TITLE
Undefined Symbol Error On Ubuntu

### ISSUE THREAD

**Issue by JonnoFTW** [matplotlib/matplotlib#6797]
I'm using the latest source version version of matplotlib (I get the same error using version 2.0.0b3 from pypi). I'm running python 2.7.12 on 64 bit compiled with ucs4 and shared libraries using pyenv.

I get the following error when I try to import `matplotlib.pyplot`:

```
Python 2.7.12 (default, Jul 19 2016, 15:29:32) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib.pyplot as plt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/CSEM/mack0242/.pyenv/versions/2.7.12/lib/python2.7/site-packages/matplotlib-2.0.0b3+1804.ge3fd1b1-py2.7-linux-x86_64.egg/matplotlib/pyplot.py", line 29, in <module>
    import matplotlib.colorbar
  File "/home/CSEM/mack0242/.pyenv/versions/2.7.12/lib/python2.7/site-packages/matplotlib-2.0.0b3+1804.ge3fd1b1-py2.7-linux-x86_64.egg/matplotlib/colorbar.py", line 32, in <module>
    import matplotlib.artist as martist
  File "/home/CSEM/mack0242/.pyenv/versions/2.7.12/lib/python2.7/site-packages/matplotlib-2.0.0b3+1804.ge3fd1b1-py2.7-linux-x86_64.egg/matplotlib/artist.py", line 15, in <module>
    from .transforms import (Bbox, IdentityTransform, TransformedBbox,
  File "/home/CSEM/mack0242/.pyenv/versions/2.7.12/lib/python2.7/site-packages/matplotlib-2.0.0b3+1804.ge3fd1b1-py2.7-linux-x86_64.egg/matplotlib/transforms.py", line 38, in <module>
    from matplotlib._path import (affine_transform, count_bboxes_overlapping_bbox,
ImportError: /home/CSEM/mack0242/.pyenv/versions/2.7.12/lib/python2.7/site-packages/matplotlib-2.0.0b3+1804.ge3fd1b1-py2.7-linux-x86_64.egg/matplotlib/_path.so: undefined symbol: _ZTVN10__cxxabiv120__si_class_type_infoE
```
Am I somehow missing a library or using the wrong library? Running `ldd` on `_path.so` gives the following output:

```
$ ldd /home/CSEM/mack0242/.pyenv/versions/2.7.12/lib/python2.7/site-packages/matplotlib-2.0.0b3+1804.ge3fd1b1-py2.7-linux-x86_64.egg/matplotlib/_path.so
	linux-vdso.so.1 =>  (0x00007fff4c9f3000)
	libpython2.7.so.1.0 => /home/CSEM/mack0242/.pyenv/versions/2.7.12/lib/libpython2.7.so.1.0 (0x00007f8f77bf1000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f8f779db000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f8f777bd000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f8f773f8000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f8f771f4000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f8f76ff1000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f8f76ceb000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f8f78242000)

```

**Comment by QuLogic** [comment]
How did you install? From wheels? That error's a C++ library incompatibility (though oddly I don't see it listed in `ldd` output.)

**Comment by JonnoFTW** [comment]
I installed from source and pip. Both give the same error even after I did
`pip uninstall matplotlib`

**Comment by WeatherGod** [comment]
What are your LD_* environment variables? Particularly, do you happen to
have LD_PRELOAD?

**Comment by JonnoFTW** [comment]
I have nothing set in LD* environment variables.

**Comment by tacaswell** [comment]
I suggest running `git clean -xfd` in your checkout and then rebuilding.  This smells like you built it, something updated at the system level, and now your binaries are out of sync but the build system is not noticing.

**Comment by JonnoFTW** [comment]
I tried that just now and got the same error. Could it be something wrong with my build system?

**Comment by tacaswell** [comment]
Did you also compile python your self?

**Comment by JonnoFTW** [comment]
Yes, I did, via pyenv. I did

`PYTHON_CONFIGURE_OPTS="--enable-unicode=ucs4 --enable-shared" pyenv install  -f -k 2.7.12`

Which runs the following: https://github.com/yyuu/pyenv/blob/master/plugins/python-build/share/python-build/2.7.12
```
#require_gcc
install_package "openssl-1.0.2g" "https://www.openssl.org/source/openssl-1.0.2g.tar.gz#b784b1b3907ce39abf4098702dade6365522a253ad1552e267a9a0e89594aa33" mac_openssl --if has_broken_mac_openssl
install_package "readline-6.3" "http://ftpmirror.gnu.org/readline/readline-6.3.tar.gz#56ba6071b9462f980c5a72ab0023893b65ba6debb4eeb475d7a563dc65cafd43" standard --if has_broken_mac_readline
install_package "Python-2.7.12" "https://www.python.org/ftp/python/2.7.12/Python-2.7.12.tar.xz#d7837121dd5652a05fef807c361909d255d173280c4e1a4ded94d73d80a1f978" ldflags_dirs standard verify_py27 ensurepip
```

**Comment by tacaswell** [comment]
You should probably take this up on the `pyenv` issue tracker / mailing list.

Can you reproduce this using system python or miniconda?

**Comment by JonnoFTW** [comment]
It worked fine using using miniconda (using the conda provided binaries), though I had some issues with interactive mode.

I could not replicate this issue on a clean VM of the latest Debian.

**Comment by tacaswell** [comment]
Closing as this is an issue with pyenv not mpl and is difficult to replicate.
