### ISSUE TITLE
Axes.hist with no data in range raises UnboundLocalError

### ISSUE THREAD

**Issue by duncanmmacleod** [matplotlib/matplotlib#6805]
Using matplotlib 1.5.1 on OSX installed via macports, trying to generate a histogram of a non-empty dataset that sits completely outside the given `range` produces an `UnboundLocalError`:

``` python
>>> from matplotlib import pyplot
>>> fig = pyplot.figure()
>>> ax = fig.gca()
>>> ax.hist([0, 0, 0], histtype='stepfilled', log=True, range=[1, 3])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/__init__.py", line 1813, in inner
    return func(ax, *args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/axes/_axes.py", line 6209, in hist
    ymin = max(ymin*0.9, minimum) if not input_empty else minimum
UnboundLocalError: local variable 'ymin' referenced before assignment
```

The offending block can't handle all bins having a count of 0, so `ymin` doesn't get set. This is still a bug with matplotlib 2.0.0b3, and on the HEAD of master.

The following patch fixes the problem for me, so I can turn this into a PR if recommended:

``` diff
diff --git a/lib/matplotlib/axes/_axes.py b/lib/matplotlib/axes/_axes.py
index f3733fe..65e17f5 100644
--- a/lib/matplotlib/axes/_axes.py
+++ b/lib/matplotlib/axes/_axes.py
@@ -6320,25 +6320,34 @@ class Axes(_AxesBase):

             # adopted from adjust_x/ylim part of the bar method
             if orientation == 'horizontal':
-                xmin0 = max(_saved_bounds[0]*0.9, minimum)
                 xmax = self.dataLim.intervalx[1]
-                for m in n:
-                    if np.sum(m) > 0:  # make sure there are counts
-                        xmin = np.amin(m[m != 0])
-                        # filter out the 0 height bins
-                xmin = max(xmin*0.9, minimum) if not input_empty else minimum
-                xmin = min(xmin0, xmin)
+                # no data or all bins have 0 counts
+                if input_empty or np.sum(m) == 0:
+                    xmin = minimum
+                # some data
+                else:
+                    xmin0 = max(_saved_bounds[0]*0.9, minimum)
+                    for m in n:
+                        if np.sum(m) > 0:  # make sure there are counts
+                            xmin = np.amin(m[m != 0])
+                            # filter out the 0 height bins
+                    xmin = max(xmin*0.9, minimum)
+                    xmin = min(xmin0, xmin)
                 self.dataLim.intervalx = (xmin, xmax)
             elif orientation == 'vertical':
-                ymin0 = max(_saved_bounds[1]*0.9, minimum)
                 ymax = self.dataLim.intervaly[1]
-
-                for m in n:
-                    if np.sum(m) > 0:  # make sure there are counts
-                        ymin = np.amin(m[m != 0])
-                        # filter out the 0 height bins
-                ymin = max(ymin*0.9, minimum) if not input_empty else minimum
-                ymin = min(ymin0, ymin)
+                # no data or all bins have 0 counts
+                if input_empty or np.sum(m) == 0:
+                    ymin = minimum
+                # some data
+                else:
+                    ymin0 = max(_saved_bounds[1]*0.9, minimum)
+                    for m in n:
+                        if np.sum(m) > 0:  # make sure there are counts
+                            ymin = np.amin(m[m != 0])
+                            # filter out the 0 height bins
+                    ymin = max(ymin*0.9, minimum)
+                    ymin = min(ymin0, ymin)
                 self.dataLim.intervaly = (ymin, ymax)

         if label is None:
```

**Comment by WeatherGod** [comment]
Yes, can you please submit a PR? They are also easier to review that way.

**Comment by anntzer** [comment]
As far as I can see this is no longer an issue in 2.0 (due to changes in how axes autolimits are computed), so closing. Feel free to request a reopen if necessary.
