### ISSUE TITLE
nonsensical error message for invalid input to plt.bar

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#6820]
mpl2.0b3, py3.5.2

```
In [1]: plt.bar(range(3), 1)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<elided>
ValueError: incompatible sizes: argument 'height' must be length 3 or scalar
```

Well, it is a scalar...

**Comment by QuLogic** [comment]
Python 2 or 3?

**Comment by anntzer** [comment]
py3, but it's the same for both.

**Comment by Kojoley** [comment]
I have got the same with master and py2
```
>python -c "import matplotlib.pylab as plt; plt.bar(range(3), 1)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\working\repositories\matplotlib\lib\matplotlib\pyplot.py", line 2554, in bar
    **kwargs)
  File "c:\working\repositories\matplotlib\lib\matplotlib\__init__.py", line 1916, in inner
    return func(ax, *args, **kwargs)
  File "c:\working\repositories\matplotlib\lib\matplotlib\axes\_axes.py", line 2041, in bar
    "must be length %d or scalar" % nbars)
ValueError: incompatible sizes: argument 'height' must be length 3 or scalar
```

**Comment by Kojoley** [comment]
The doc says that height is [sequence of scalars](https://github.com/matplotlib/matplotlib/blob/5443e8112842ce689d2edb738fedaf7344d41e04/lib/matplotlib/axes/_axes.py#L1844-L1845) 

So exception message lies, function expects sequence of 1 or `len(bottom)` elements
```python
            nbars = len(bottom)
            if len(left) == 1:
                left *= nbars
            if len(height) == 1:
                height *= nbars
...
        if len(height) != nbars:
            raise ValueError("incompatible sizes: argument 'height' "
                              "must be length %d or scalar" % nbars)
```
_from [here](https://github.com/matplotlib/matplotlib/blob/5443e8112842ce689d2edb738fedaf7344d41e04/lib/matplotlib/axes/_axes.py#L2006-L2010)_
