### ISSUE TITLE
SVG backend closes BytesIO on print if were `usetex=True` and `cleanup` decorator used

### ISSUE THREAD

**Issue by Kojoley** [matplotlib/matplotlib#6926]
``` python
import matplotlib
matplotlib.use('svg')

from matplotlib.testing.decorators import cleanup


def make_svg(filename, usetex):
    from matplotlib import rc
    from matplotlib.figure import Figure
    from matplotlib.backends.backend_svg import FigureCanvasSVG
    rc('text', usetex=usetex)

    fig = Figure()
    ax = fig.add_subplot(111)

    FigureCanvasSVG(fig).print_svg(filename)


@cleanup
def make_svg_with_cleanup(filename, usetex):
    make_svg(filename, usetex)


def do_test(cleanup, usetex):
    import io
    stream = io.BytesIO()
    if cleanup:
        make_svg_with_cleanup(stream, usetex)
    else:
        make_svg(stream, usetex)
    assert not stream.closed
    return stream.getvalue()


do_test(cleanup=False, usetex=True)
do_test(cleanup=True, usetex=True)
do_test(cleanup=False, usetex=False)
do_test(cleanup=True, usetex=False)
```

Bunch of `seek(0)` calls on `BytesIO` objects in different tests can be related to this bug.

**Comment by QuLogic** [comment]
I don't understand; it seems to be gc'd?
```pytb
cleanup=True, usetex=False
  File "issue6926.py", line 51, in <module>
    do_test(cleanup=True, usetex=False)
  File "issue6926.py", line 41, in do_test
    make_svg_with_cleanup(stream, usetex)
  File ".../lib/matplotlib/testing/decorators.py", line 154, in wrapped_callable
    original_settings)
  File ".../lib/matplotlib/testing/decorators.py", line 74, in _do_cleanup
    plt.close('all')
  File ".../lib/matplotlib/pyplot.py", line 647, in close
    _pylab_helpers.Gcf.destroy_all()
  File ".../lib/matplotlib/_pylab_helpers.py", line 96, in destroy_all
    gc.collect(1)
  File "issue6926.py", line 35, in close
    traceback.print_stack()
```

**Comment by Kojoley** [comment]
I have got this:
```
Traceback (most recent call last):
  File "test_bytesio.py", line 36, in <module>
    do_test(cleanup=True, usetex=True)
  File "test_bytesio.py", line 31, in do_test
    assert not stream.closed
AssertionError
```

**Comment by QuLogic** [comment]
Sorry, I added a wrapper to catch the closing:

```python
class BIO(io.BytesIO):
    def __init__(self, cleanup, usetex, *args, **kwargs):
        super(BIO, self).__init__(*args, **kwargs)
        self.cleanup = cleanup
        self.usetex = usetex

    def close(self, *args, **kwargs):
        super(BIO, self).close(*args, **kwargs)
        print('cleanup=%s, usetex=%s' % (self.cleanup, self.usetex))
        traceback.print_stack()
```
which prints the traceback above.

**Comment by Kojoley** [comment]
Oh. Ok. `cleanup=True, usetex=False` is not the case I am talking about. The bug appears in the `cleanup=True, usetex=True` case.

**Comment by Kojoley** [comment]
Sorry. I have changed the order of tests and put wrong case in the title...
