### ISSUE TITLE
cycler 0.10 is required due to change_key() usage

### ISSUE THREAD

**Issue by rathann** [matplotlib/matplotlib#6999]
To help us understand and resolve your issue please check that you have provided
the information below.

- [ ] Matplotlib version, Python version and Platform (Windows, OSX, Linux ...)

  2.0.0b3, python-2.7.12, Linux (Fedora rawhide)

- [ ] How did you install Matplotlib and Python (pip, anaconda, from source ...)

  from source (I'm building an RPM package)

- [ ] If possible please supply a [Short, Self Contained, Correct, Example](http://sscce.org/)
      that demonstrates the issue i.e a small piece of code which reproduces the issue
      and can be run with out any other (or as few as possible) external dependencies.

  Commit https://github.com/matplotlib/matplotlib/commit/bfe5e3fb84f69045e99ca4337ba1270bf0f8f5b5 erroneously bumps the cycler requirement to 0.9, when in fact the commit that introduced change_key method ended up only in master and 0.10 branches of cycler (https://github.com/matplotlib/cycler/commit/1898aa21d055d22f16293a26954ec9b84c2500e4).
Please bump the cycler requirement to 0.10.

**Comment by rathann** [comment]
By the way, the exact error message with cycler 0.9.0 is:
```
$ cd /builddir/BUILD/matplotlib-2.0.0b3/doc/
$ MPLCONFIGDIR=/builddir/build/BUILD/matplotlib-2.0.0b3/doc/.. MATPLOTLIBDATA=/builddir/build/BUILD/matplotlib-2.0.0b3/doc/../lib/matplotlib/mpl-data PYTHONPATH=/builddir/build/BUILD/matplotlib-2.0.0b3/build/lib.linux-x86_64-2.7 python2 make.py html
Traceback (most recent call last):
  File "make.py", line 10, in <module>
    import matplotlib
  File "/builddir/build/BUILD/matplotlib-2.0.0b3/build/lib.linux-x86_64-2.7/matplotlib/__init__.py", line 1165, in <module>
    rcParams = rc_params()
  File "/builddir/build/BUILD/matplotlib-2.0.0b3/build/lib.linux-x86_64-2.7/matplotlib/__init__.py", line 1008, in rc_params
    return rc_params_from_file(fname, fail_on_error)
  File "/builddir/build/BUILD/matplotlib-2.0.0b3/build/lib.linux-x86_64-2.7/matplotlib/__init__.py", line 1141, in rc_params_from_file
    if key not in _all_deprecated])
  File "/builddir/build/BUILD/matplotlib-2.0.0b3/build/lib.linux-x86_64-2.7/matplotlib/__init__.py", line 892, in __init__
    self[k] = v
  File "/builddir/build/BUILD/matplotlib-2.0.0b3/build/lib.linux-x86_64-2.7/matplotlib/__init__.py", line 909, in __setitem__
    cval = self.validate[key](val)
  File "/builddir/build/BUILD/matplotlib-2.0.0b3/build/lib.linux-x86_64-2.7/matplotlib/rcsetup.py", line 844, in validate_cycler
    cycler_inst.change_key(prop, norm_prop)
AttributeError: 'Cycler' object has no attribute 'change_key'
$ 
```

**Comment by tacaswell** [comment]
It is marked as such in https://github.com/matplotlib/matplotlib/blob/v2.x/setupext.py#L1359 and https://github.com/matplotlib/matplotlib/blob/v2.x/INSTALL#L214

**Comment by rathann** [comment]
Right, sorry, it's there. I missed the fact that setup.py succeeded despite cycler 0.9 being installed.

**Comment by tacaswell** [comment]
If you do not have `setuptools` installed we fallback to `dist_utils` which ignores `install_requires`.
