### ISSUE TITLE
1.5.3, debian unstable: test failures/errors/hands when using --processors=2

### ISSUE THREAD

**Issue by sandrotosi** [matplotlib/matplotlib#7085]
Hello,
when preparing to upload 1.5.3, i tried to run the unittests with --processors=2 to try and speedup the building the debian package (we run the test 4 times, 2.7/2.7-dbg/3.5/3.5-dbg and it takes its sweet time), but there are several errors (often with just printing `ERROR` on a new line, with no reference to the failed test) and ultimately it just stopped at:

```
matplotlib.tests.test_rcparams.test_validators(<function _listify_validator.<locals>.f at 0x7fdb6083bd08>, 'r,g,b', ['r', 'g', 'b']) ... ok
matplotlib.tests.test_rcparams.test_validators(<function _listify_validator.<locals>.f at 0x7fdb6083bd08>, ['r', 'g', 'b'], ['r', 'g', 'b']) ... ok
matplotlib.tests.test_rcparams.test_validators(<function _listify_validator.<locals>.f at 0x7fdb6083bd08>, 'r, ,', ['r']) ... ok
matplotlib.tests.test_rcparams.test_validators(<function _listify_validator.<locals>.f at 0x7fdb6083bd08>, ['', 'g', 'blue'], ['g', 'blue']) ... ok
matplotlib.tests.test_rcparams.test_validators(<function _listify_validator.<locals>.f at 0x7fdb6083bd08>, [array([1, 0, 0]), array([0, 1, 0])], array([[1, 0, 0], ... ok
matplotlib.tests.test_rcparams.test_validators(<function _listify_validator.<locals>.f at 0x7fdb6083bd08>, array([[1, 0, 0], ... ok
matplotlib.tests.test_rcparams.test_validators(<function _listify_validator.<locals>.f at 0x7fdb6083bd08>, 'fish', <class 'ValueError'>) ... ok
/usr/lib/python3/dist-packages/dateutil/rrule.py:833: DeprecationWarning: fractions.gcd() is deprecated. Use math.gcd() instead.
  i_gcd = gcd(self._interval, base)
/usr/lib/python3/dist-packages/dateutil/rrule.py:719: DeprecationWarning: fractions.gcd() is deprecated. Use math.gcd() instead.
  for j in range(rep_rate // gcd(interval, rep_rate)):
/usr/lib/python3/dist-packages/dateutil/rrule.py:833: DeprecationWarning: fractions.gcd() is deprecated. Use math.gcd() instead.
  i_gcd = gcd(self._interval, base)
/usr/lib/python3/dist-packages/dateutil/rrule.py:719: DeprecationWarning: fractions.gcd() is deprecated. Use math.gcd() instead.
  for j in range(rep_rate // gcd(interval, rep_rate)):
/usr/lib/python3/dist-packages/dateutil/rrule.py:833: DeprecationWarning: fractions.gcd() is deprecated. Use math.gcd() instead.
  i_gcd = gcd(self._interval, base)
/usr/lib/python3/dist-packages/dateutil/rrule.py:719: DeprecationWarning: fractions.gcd() is deprecated. Use math.gcd() instead.
  for j in range(rep_rate // gcd(interval, rep_rate)):
/usr/lib/python3/dist-packages/dateutil/rrule.py:833: DeprecationWarning: fractions.gcd() is deprecated. Use math.gcd() instead.
  i_gcd = gcd(self._interval, base)
/build/matplotlib-1.5.3/build/lib.linux-x86_64-3.5/matplotlib/_pylab_helpers.py:96: ResourceWarning: unclosed file <_io.FileIO name=9 mode='rb' closefd=True>
  gc.collect(1)
/build/matplotlib-1.5.3/build/lib.linux-x86_64-3.5/matplotlib/_pylab_helpers.py:96: ResourceWarning: unclosed file <_io.FileIO name=12 mode='rb' closefd=True>
  gc.collect(1)
/usr/lib/python3.5/subprocess.py:504: ResourceWarning: unclosed file <_io.BufferedReader name=10>
  for inst in _active[:]:
/usr/lib/python3.5/subprocess.py:504: ResourceWarning: unclosed file <_io.BufferedReader name=8>
  for inst in _active[:]:

Bad key "timezone" on line 1 in
/build/matplotlib-1.5.3/build/lib.linux-x86_64-3.5/matplotlib/tests/test_utf32_be_rcparams.rc.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fdb57190950>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 108, in remove
    def remove(wr, selfref=ref(self)):
  File "/usr/lib/python3/dist-packages/nose/plugins/multiprocess.py", line 276, in signalhandler
    raise TimedOutException()
nose.plugins.multiprocess.TimedOutException: 'Timed Out'
/build/matplotlib-1.5.3/build/lib.linux-x86_64-3.5/matplotlib/_pylab_helpers.py:96: ResourceWarning: unclosed file <_io.FileIO name=15 mode='rb' closefd=True>
  gc.collect(1)
/build/matplotlib-1.5.3/build/lib.linux-x86_64-3.5/matplotlib/_pylab_helpers.py:96: ResourceWarning: unclosed file <_io.FileIO name=18 mode='rb' closefd=True>
  gc.collect(1)
/build/matplotlib-1.5.3/build/lib.linux-x86_64-3.5/matplotlib/testing/decorators.py:73: ResourceWarning: unclosed file <_io.BufferedReader name=7>
  gc.collect()
/build/matplotlib-1.5.3/build/lib.linux-x86_64-3.5/matplotlib/testing/decorators.py:73: ResourceWarning: unclosed file <_io.BufferedReader name=9>
  gc.collect()
/usr/lib/python3/dist-packages/nose/plugins/multiprocess.py:821: ResourceWarning: unclosed file <_io.BufferedReader name=7>
  sys.exc_info()[2])
/usr/lib/python3/dist-packages/nose/plugins/multiprocess.py:821: ResourceWarning: unclosed file <_io.BufferedReader name=9>
  sys.exc_info()[2])
/build/matplotlib-1.5.3/build/lib.linux-x86_64-3.5/matplotlib/_pylab_helpers.py:96: ResourceWarning: unclosed file <_io.FileIO name=8 mode='rb' closefd=True>
  gc.collect(1)
/build/matplotlib-1.5.3/build/lib.linux-x86_64-3.5/matplotlib/_pylab_helpers.py:96: ResourceWarning: unclosed file <_io.FileIO name=11 mode='rb' closefd=True>
  gc.collect(1)
/usr/lib/python3/dist-packages/dateutil/rrule.py:833: DeprecationWarning: fractions.gcd() is deprecated. Use math.gcd() instead.
  i_gcd = gcd(self._interval, base)
/usr/lib/python3/dist-packages/dateutil/rrule.py:719: DeprecationWarning: fractions.gcd() is deprecated. Use math.gcd() instead.
  for j in range(rep_rate // gcd(interval, rep_rate)):
/usr/lib/python3/dist-packages/dateutil/rrule.py:751: DeprecationWarning: fractions.gcd() is deprecated. Use math.gcd() instead.
  for j in range(0, rep_rate // gcd(interval, rep_rate)):
/build/matplotlib-1.5.3/build/lib.linux-x86_64-3.5/matplotlib/tests/test_streamplot.py:44: MaskedArrayFutureWarning: setting an item on a masked array which has a shared mask will not copy the mask and also change the original mask array in the future.
Check the NumPy 1.11 release notes for more information.
  U[:20, :20] = np.nan
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/plugins/multiprocess.py", line 717, in __runner
    resultQueue.put((ix, test_addr, test.tasks, batch(result)))
  File "<string>", line 2, in put
  File "/usr/lib/python3.5/multiprocessing/managers.py", line 717, in _callmethod
    kind, result = conn.recv()
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
  File "/usr/lib/python3/dist-packages/nose/plugins/multiprocess.py", line 276, in signalhandler
    raise TimedOutException()
nose.plugins.multiprocess.TimedOutException: 'Timed Out'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/nose/plugins/multiprocess.py", line 652, in runner
    keyboardCaught, shouldStop, loaderClass, resultClass, config)
  File "/usr/lib/python3/dist-packages/nose/plugins/multiprocess.py", line 722, in __runner
    if len(currentaddr.value):
TypeError: object of type 'NoneType' has no len()
```

is it known that --processors is not working? in that case, maybe you can force to have processors=1 inside the test code

do you have any tips to speedup tests execution?

thanks!!

**Comment by Kojoley** [comment]
We are running tests on travis with `--processors=2` so it should not be a problem.
Probably you have faced https://bugs.python.org/issue19542

**Comment by tacaswell** [comment]
You also need ` --process-timeout=300`

**Comment by tacaswell** [comment]
Closing as this is a configuration issue and for mpl 1.5.3
