### ISSUE TITLE
Unknown exception in resize

### ISSUE THREAD

**Issue by rocapp** [matplotlib/matplotlib#7260]
- [Matplotlib 1.5.1, Python 2.7.11 64 bit, Windows 10]
- [Installed Matplotlib from http://www.lfd.uci.edu/~gohlke/pythonlibs/#matplotlib using pip]

I apologize, I can't provide a simple example because this is something that only happens in a very specific implementation. Pieces of matplotlib I'm using:

```
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib.patches import Rectangle
import matplotlib.gridspec as gridspec
```
I am using a 2-row gridspec, and I call ax.imshow() on both.

I can provide more information if it is needed.

The error I see is below, which happens on a call to both plt.show() and plt.savefig(), which causes the image to never be drawn.

> Exception in Tkinter callback
> Traceback (most recent call last):
>   File "C:\Python27_64bit\lib\lib-tk\Tkinter.py", line 1536, in __call__
>     return self.func(*args)
>   File "C:\Python27_64bit\lib\site-packages\matplotlib\backends\backend_tkagg.py", line 283, in resize
>     self.show()
>   File "C:\Python27_64bit\lib\site-packages\matplotlib\backends\backend_tkagg.py", line 354, in draw
>     FigureCanvasAgg.draw(self)
>   File "C:\Python27_64bit\lib\site-packages\matplotlib\backends\backend_agg.py", line 474, in draw
>     self.figure.draw(self.renderer)
>   File "C:\Python27_64bit\lib\site-packages\matplotlib\artist.py", line 61, in draw_wrapper
>     draw(artist, renderer, *args, **kwargs)
>   File "C:\Python27_64bit\lib\site-packages\matplotlib\figure.py", line 1159, in draw
>     func(*args)
>   File "C:\Python27_64bit\lib\site-packages\matplotlib\artist.py", line 61, in draw_wrapper
>     draw(artist, renderer, *args, **kwargs)
>   File "C:\Python27_64bit\lib\site-packages\matplotlib\axes\_base.py", line 2324, in draw
>     a.draw(renderer)
>   File "C:\Python27_64bit\lib\site-packages\matplotlib\artist.py", line 61, in draw_wrapper
>     draw(artist, renderer, *args, **kwargs)
>   File "C:\Python27_64bit\lib\site-packages\matplotlib\image.py", line 383, in draw
>     self._draw_unsampled_image(renderer, gc)
>   File "C:\Python27_64bit\lib\site-packages\matplotlib\image.py", line 352, in _draw_unsampled_image
>     im.resize(numcols, numrows)  # just to create im.bufOut that
> RuntimeError: Unknown exception in resize

**Comment by rocapp** [comment]
Never mind... whatever the issue is, it was fixed in Matplotlib 1.5.3. :)
