### ISSUE TITLE
Latex greek letters in axis labels

### ISSUE THREAD

**Issue by DanyPPage** [matplotlib/matplotlib#7274]
Here is a simple example were the use of greek letters with Latex fails:

```python
import matplotlib.pyplot as plt
X = [[1.,1.], [2.,2.], [3.,3.]]
Y = [[1.,1.], [2.,2.], [3.,3.]]
fig = plt.figure()
ax = fig.add_subplot(111)
ax.scatter(X, Y)
ax.set_xlabel('$\rho$')
plt.show()
```

Notice that some letters, as \phi, work, and others don't.

I'm using Python2.7 on a Mac with Yosemite, and python and all packages were
installed using Macport and my Matplotlib is
py27-matplotlib @1.5.2_0+cairo (active)

**Comment by QuLogic** [comment]
You are not using a raw string here: `'$\rho$'`. The `\r` is interpreted by Python as a carriage return. Using a raw string `r'$\rho$'` or escaped backslash `'$\\rho$'` will work.

**Comment by DanyPPage** [comment]
Thanx Elliott :)

Dany

**Comment by ehsansadeghi1** [comment]
I tried this code:
`import matplotlib.pyplot as plt
X = [[1.,1.], [2.,2.], [3.,3.]]
Y = [[1.,1.], [2.,2.], [3.,3.]]
fig = plt.figure()
ax = fig.add_subplot(111)
ax.scatter(X, Y)
ax.set_xlabel(r'$\rho$')
plt.show()`
 and keep getting error: 
`/usr/local/anaconda3/lib/python3.6/site-packages/matplotlib/font_manager.py:1328: UserWarning: findfont: Font family ['sans-serif'] not found. Falling back to DejaVu Sans
  (prop.get_family(), self.defaultFamily[fontext]))
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_qt5.py", line 519, in _draw_idle
    self.draw()
  File "/usr/local/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 433, in draw
    self.figure.draw(self.renderer)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/matplotlib/figure.py", line 1475, in draw
    renderer, self, artists, self.suppressComposite)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/matplotlib/image.py", line 141, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 2607, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/matplotlib/image.py", line 141, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/matplotlib/axis.py", line 1192, in draw
    renderer)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/matplotlib/axis.py", line 1130, in _get_tick_bboxes
    extent = tick.label1.get_window_extent(renderer)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/matplotlib/text.py", line 922, in get_window_extent
    bbox, info, descent = self._get_layout(self._renderer)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/matplotlib/text.py", line 309, in _get_layout
    ismath=ismath)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 232, in get_text_width_height_descent
    s, fontsize, renderer=self)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/matplotlib/texmanager.py", line 503, in get_text_width_height_descent
    page = next(iter(dvi))
  File "/usr/local/anaconda3/lib/python3.6/site-packages/matplotlib/dviread.py", line 254, in __iter__
    have_page = self._read()
  File "/usr/local/anaconda3/lib/python3.6/site-packages/matplotlib/dviread.py", line 315, in _read
    self._dtable[byte](self, byte)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/matplotlib/dviread.py", line 171, in wrapper
    return method(self, *[f(self, byte-min) for f in get_args])
  File "/usr/local/anaconda3/lib/python3.6/site-packages/matplotlib/dviread.py", line 460, in _fnt_def
    self._fnt_def_real(k, c, s, d, a, l)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/matplotlib/dviread.py", line 465, in _fnt_def_real
    tfm = _tfmfile(fontname)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/matplotlib/dviread.py", line 1057, in _fontfile
    filename = find_tex_file(texname + suffix)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/matplotlib/dviread.py", line 1045, in find_tex_file
    stderr=subprocess.PIPE)
  File "/usr/local/anaconda3/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/local/anaconda3/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'kpsewhich': 'kpsewhich'`

**Comment by jklymak** [comment]
Make sure you run the above with a vanilla matplotlibrc.  I suspect you have `tex.usetex=True`, and you don't have TeX installed in a way that python can find it.  (check `print(rcParams['tex.usetex'])` to check)
