### ISSUE TITLE
plt.table() without any kwargs throws exception

### ISSUE THREAD

**Issue by dstansby** [matplotlib/matplotlib#7519]
Installed from source using pip on OSX.
Version 2.0.0b4+2948.g6a56f69

I encountered this when trying to fix #5350. Just using plt.table() errors, which I wouldn't expect given all the arguments are optional...

Minimal snippet:
```
import matplotlib.pyplot as plt
plt.table()
```

And output:
```
python test.py 
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    plt.table()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/pyplot.py", line 3484, in table
    ret = gca().table(**kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/axes/_axes.py", line 5884, in table
    return mtable.table(self, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/table.py", line 587, in table
    rows = len(cellColours)
TypeError: object of type 'NoneType' has no len()
```

**Comment by tacaswell** [comment]
The exact work to do here is to:

 - [ ] add check and user-friendly exception to `matplotlib.table.table` to check if both `cellColours` and `cellText` are `None`
