### ISSUE TITLE
tripcolor documentation rendering error .

### ISSUE THREAD

**Issue by stilley2** [matplotlib/matplotlib#7803]
The documentation at https://github.com/matplotlib/matplotlib/blob/38be7aeaaac3691560aeadafe46722dda427ef47/lib/matplotlib/tri/tripcolor.py#L41 does not render properly (see tripcolor documentation here http://matplotlib.org/api/axes_api.html).
A couple of the '*' are being used for formatting while a couple are printed literally. I'll try to make a PR when I get some more time.

**Comment by tacaswell** [comment]
http://matplotlib.org/api/axes_api.html#matplotlib.axes.Axes.tripcolor is a direct link to the offending entry.

exact work:

 - fix the rst markup in the docstring

@stilley2 do you mind if someone takes care of this before you do?

**Comment by stilley2** [comment]
Not at all

**Comment by rishikksh20** [comment]
Am I eligible to take this ?

**Comment by dstansby** [comment]
The 2nd example figure also has a title that runs off the left hand edge, perhaps that could be fixed at the same time too. (http://matplotlib.org/mpl_examples/pylab_examples/tripcolor_demo_01.png)

**Comment by jenshnielsen** [comment]
@rishikksh20 
@stilley2 confirmed above that he is happy for someone else to work on it so your contribution fixing this would be very welcome

**Comment by rishikksh20** [comment]
Getting following error while building matplotlib doc :
 ```
Warning, treated as error:
/home/rishikesh/Dev/Open_Source/matplotlib/doc/examples/mplot3d/pathpatch3d_demo.rst:8: WARNING: Exception occurred in plotting pathpatch3d_demo
 from /home/rishikesh/Dev/Open_Source/matplotlib/doc/mpl_examples/mplot3d/pathpatch3d_demo.py:
Traceback (most recent call last):
  File "/home/rishikesh/Dev/Open_Source/matplotlib/lib/matplotlib/sphinxext/plot_directive.py", line 525, in run_code
    six.exec_(code, ns)
  File "<string>", line 61, in <module>
  File "<string>", line 32, in text3d
  File "/home/rishikesh/Dev/Open_Source/matplotlib/lib/matplotlib/textpath.py", line 450, in __init__
    usetex=usetex)
  File "/home/rishikesh/Dev/Open_Source/matplotlib/lib/matplotlib/textpath.py", line 530, in text_get_vertices_codes
    verts, codes = text_to_path.get_text_path(prop, s, usetex=True)
  File "/home/rishikesh/Dev/Open_Source/matplotlib/lib/matplotlib/textpath.py", line 152, in get_text_path
    glyph_info, glyph_map, rects = self.get_glyphs_tex(prop, s)
  File "/home/rishikesh/Dev/Open_Source/matplotlib/lib/matplotlib/textpath.py", line 305, in get_glyphs_tex
    dviread.find_tex_file('pdftex.map'))
  File "/home/rishikesh/Dev/Open_Source/matplotlib/lib/matplotlib/dviread.py", line 985, in find_tex_file
    stderr=subprocess.PIPE)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'kpsewhich'

Building HTML failed.

```
