### ISSUE TITLE
very small errors in test suite, py3.6 and 3.5

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#7851]
```
19:13 $ inkscape --version
Inkscape 0.92.0 r
```

```
======================================================================
FAIL: matplotlib.tests.test_axes.test_alpha.test(1, '/home/tcaswell/source/p/matplotlib/result_images/test_axes/test_alpha.svg', '/home/tcaswell/source/p/matplotlib/result_images/test_axes/test_alpha-expected.svg')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tcaswell/.virtualenvs/dd36/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/tcaswell/source/p/matplotlib/lib/matplotlib/testing/decorators.py", line 58, in failer
    result = f(*args, **kwargs)
  File "/home/tcaswell/source/p/matplotlib/lib/matplotlib/testing/decorators.py", line 259, in do_test
    '(RMS %(rms).3f)'%err)
matplotlib.testing.exceptions.ImageComparisonFailure: images not close: /home/tcaswell/source/p/matplotlib/result_images/test_axes/test_alpha_svg.png vs. /home/tcaswell/source/p/matplotlib/result_images/test_axes/test_alpha-expected_svg.png (RMS 0.004)

======================================================================
FAIL: matplotlib.tests.test_axes.test_pcolormesh.test(1, '/home/tcaswell/source/p/matplotlib/result_images/test_axes/pcolormesh.svg', '/home/tcaswell/source/p/matplotlib/result_images/test_axes/pcolormesh-expected.svg')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tcaswell/.virtualenvs/dd36/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/tcaswell/source/p/matplotlib/lib/matplotlib/testing/decorators.py", line 58, in failer
    result = f(*args, **kwargs)
  File "/home/tcaswell/source/p/matplotlib/lib/matplotlib/testing/decorators.py", line 259, in do_test
    '(RMS %(rms).3f)'%err)
matplotlib.testing.exceptions.ImageComparisonFailure: images not close: /home/tcaswell/source/p/matplotlib/result_images/test_axes/pcolormesh_svg.png vs. /home/tcaswell/source/p/matplotlib/result_images/test_axes/pcolormesh-expected_svg.png (RMS 0.001)

----------------------------------------------------------------------
Ran 6161 tests in 307.138s

```

**Comment by tacaswell** [comment]
![pcolormesh-expected_svg](https://cloud.githubusercontent.com/assets/199813/22003956/8db33342-dc25-11e6-813b-971ced2897bd.png)
![pcolormesh_svg](https://cloud.githubusercontent.com/assets/199813/22003957/8db35804-dc25-11e6-929a-9b3cba506274.png)
![pcolormesh_svg-failed-diff](https://cloud.githubusercontent.com/assets/199813/22003986/bd2ac5cc-dc25-11e6-8a8e-dffda1bf8076.png)
---
![test_alpha-expected_svg](https://cloud.githubusercontent.com/assets/199813/22003977/b35e8e0c-dc25-11e6-9c6b-d5a058529c5d.png)
![test_alpha_svg](https://cloud.githubusercontent.com/assets/199813/22003978/b3609d96-dc25-11e6-9d16-d42ab507dabc.png)
![test_alpha_svg-failed-diff](https://cloud.githubusercontent.com/assets/199813/22003979/b361be42-dc25-11e6-95c2-35605a4188ef.png)

**Comment by efiring** [comment]
It looks to me like a little tolerance is in order!

**Comment by tacaswell** [comment]
Looks like there is some rounding differences in how paths are output (scroll to the bottom of the diff)

Fun fact: "You can't comment at this time — your comment is too long (maximum is 65536 characters)."

A very truncated diff:

```diff
--- pcolormesh-expected.svg	2017-01-16 19:49:41.588202094 -0500
+++ pcolormesh.svg	2017-01-16 19:49:42.821506602 -0500
@@ -22847,108 +22847,108 @@
     <g id="ytick_19">
      <g id="line2d_73">
       <g>
-       <use style="stroke:#000000;stroke-width:0.500000;" x="387.105882353" xlink:href="#m0b6d9ceefb" y="388.8"/>
+       <use style="stroke:#000000;stroke-width:0.5;" x="387.105882" xlink:href="#mbe547fa9e8" y="388.8"/>
       </g>
      </g>
      <g id="line2d_74">
       <g>
-       <use style="stroke:#000000;stroke-width:0.500000;" x="518.4" xlink:href="#m1f00aa164d" y="388.8"/>
+       <use style="stroke:#000000;stroke-width:0.5;" x="518.4" xlink:href="#m0ddd930dee" y="388.8"/>
       </g>
      </g>
     </g>
     <g id="ytick_20">
      <g id="line2d_75">
       <g>
-       <use style="stroke:#000000;stroke-width:0.500000;" x="387.105882353" xlink:href="#m0b6d9ceefb" y="345.6"/>
+       <use style="stroke:#000000;stroke-width:0.5;" x="387.105882" xlink:href="#mbe547fa9e8" y="345.6"/>
       </g>
      </g>
      <g id="line2d_76">
       <g>
-       <use style="stroke:#000000;stroke-width:0.500000;" x="518.4" xlink:href="#m1f00aa164d" y="345.6"/>
+       <use style="stroke:#000000;stroke-width:0.5;" x="518.4" xlink:href="#m0ddd930dee" y="345.6"/>
       </g>
      </g>
     </g>
     <g id="ytick_21">
      <g id="line2d_77">
       <g>
-       <use style="stroke:#000000;stroke-width:0.500000;" x="387.105882353" xlink:href="#m0b6d9ceefb" y="302.4"/>
+       <use style="stroke:#000000;stroke-width:0.5;" x="387.105882" xlink:href="#mbe547fa9e8" y="302.4"/>
       </g>
      </g>
      <g id="line2d_78">
       <g>
-       <use style="stroke:#000000;stroke-width:0.500000;" x="518.4" xlink:href="#m1f00aa164d" y="302.4"/>
+       <use style="stroke:#000000;stroke-width:0.5;" x="518.4" xlink:href="#m0ddd930dee" y="302.4"/>
       </g>
      </g>
     </g>
     <g id="ytick_22">
      <g id="line2d_79">
       <g>
-       <use style="stroke:#000000;stroke-width:0.500000;" x="387.105882353" xlink:href="#m0b6d9ceefb" y="259.2"/>
+       <use style="stroke:#000000;stroke-width:0.5;" x="387.105882" xlink:href="#mbe547fa9e8" y="259.2"/>
       </g>
      </g>
      <g id="line2d_80">
       <g>
-       <use style="stroke:#000000;stroke-width:0.500000;" x="518.4" xlink:href="#m1f00aa164d" y="259.2"/>
+       <use style="stroke:#000000;stroke-width:0.5;" x="518.4" xlink:href="#m0ddd930dee" y="259.2"/>
       </g>
      </g>
     </g>
     <g id="ytick_23">
      <g id="line2d_81">
       <g>
-       <use style="stroke:#000000;stroke-width:0.500000;" x="387.105882353" xlink:href="#m0b6d9ceefb" y="216.0"/>
+       <use style="stroke:#000000;stroke-width:0.5;" x="387.105882" xlink:href="#mbe547fa9e8" y="216"/>
       </g>
      </g>
      <g id="line2d_82">
       <g>
-       <use style="stroke:#000000;stroke-width:0.500000;" x="518.4" xlink:href="#m1f00aa164d" y="216.0"/>
+       <use style="stroke:#000000;stroke-width:0.5;" x="518.4" xlink:href="#m0ddd930dee" y="216"/>
       </g>
      </g>
     </g>
     <g id="ytick_24">
      <g id="line2d_83">
       <g>
-       <use style="stroke:#000000;stroke-width:0.500000;" x="387.105882353" xlink:href="#m0b6d9ceefb" y="172.8"/>
+       <use style="stroke:#000000;stroke-width:0.5;" x="387.105882" xlink:href="#mbe547fa9e8" y="172.8"/>
       </g>
      </g>
      <g id="line2d_84">
       <g>
-       <use style="stroke:#000000;stroke-width:0.500000;" x="518.4" xlink:href="#m1f00aa164d" y="172.8"/>
+       <use style="stroke:#000000;stroke-width:0.5;" x="518.4" xlink:href="#m0ddd930dee" y="172.8"/>
       </g>
      </g>
     </g>
     <g id="ytick_25">
      <g id="line2d_85">
       <g>
-       <use style="stroke:#000000;stroke-width:0.500000;" x="387.105882353" xlink:href="#m0b6d9ceefb" y="129.6"/>
+       <use style="stroke:#000000;stroke-width:0.5;" x="387.105882" xlink:href="#mbe547fa9e8" y="129.6"/>
       </g>
      </g>
      <g id="line2d_86">
       <g>
-       <use style="stroke:#000000;stroke-width:0.500000;" x="518.4" xlink:href="#m1f00aa164d" y="129.6"/>
+       <use style="stroke:#000000;stroke-width:0.5;" x="518.4" xlink:href="#m0ddd930dee" y="129.6"/>
       </g>
      </g>
     </g>
     <g id="ytick_26">
      <g id="line2d_87">
       <g>
-       <use style="stroke:#000000;stroke-width:0.500000;" x="387.105882353" xlink:href="#m0b6d9ceefb" y="86.4"/>
+       <use style="stroke:#000000;stroke-width:0.5;" x="387.105882" xlink:href="#mbe547fa9e8" y="86.4"/>
       </g>
      </g>
      <g id="line2d_88">
       <g>
-       <use style="stroke:#000000;stroke-width:0.500000;" x="518.4" xlink:href="#m1f00aa164d" y="86.4"/>
+       <use style="stroke:#000000;stroke-width:0.5;" x="518.4" xlink:href="#m0ddd930dee" y="86.4"/>
       </g>
      </g>
     </g>
     <g id="ytick_27">
      <g id="line2d_89">
       <g>
-       <use style="stroke:#000000;stroke-width:0.500000;" x="387.105882353" xlink:href="#m0b6d9ceefb" y="43.2"/>
+       <use style="stroke:#000000;stroke-width:0.5;" x="387.105882" xlink:href="#mbe547fa9e8" y="43.2"/>
       </g>
      </g>
      <g id="line2d_90">
       <g>
-       <use style="stroke:#000000;stroke-width:0.500000;" x="518.4" xlink:href="#m1f00aa164d" y="43.2"/>
+       <use style="stroke:#000000;stroke-width:0.5;" x="518.4" xlink:href="#m0ddd930dee" y="43.2"/>
       </g>
      </g>
     </g>
@@ -22956,14 +22956,14 @@
   </g>
  </g>
  <defs>
-  <clipPath id="p47f2670ee0">
-   <rect height="345.6" width="131.294117647" x="72.0" y="43.2"/>
+  <clipPath id="p2e7b46362b">
+   <rect height="345.6" width="131.294118" x="72" y="43.2"/>
   </clipPath>
-  <clipPath id="pe468aefb88">
-   <rect height="345.6" width="131.294117647" x="229.552941176" y="43.2"/>
+  <clipPath id="pe83024229e">
+   <rect height="345.6" width="131.294118" x="229.552941" y="43.2"/>
   </clipPath>
-  <clipPath id="pe34fef1660">
-   <rect height="345.6" width="131.294117647" x="387.105882353" y="43.2"/>
+  <clipPath id="p9c2d882e61">
+   <rect height="345.6" width="131.294118" x="387.105882" y="43.2"/>
   </clipPath>
  </defs>
 </svg>

```

**Comment by efiring** [comment]
This is odd, because formatting is being done with `short_float_fmt` which is just 

```    return '{0:f}'.format(x).rstrip('0').rstrip('.')``` 
I don't understand how this could be leaving the zeros on the stroke-width value.
```
-       <use style="stroke:#000000;stroke-width:0.500000;" x="387.105882353" xlink:href="#m0b6d9ceefb" y="345.6"/>
+       <use style="stroke:#000000;stroke-width:0.5;" x="387.105882" xlink:href="#mbe547fa9e8" y="345.6"/>
```

**Comment by tacaswell** [comment]
we may not have re-generated the svgs after that change?

**Comment by efiring** [comment]
#5651 was the PR with that change, back in Dec. 2015.  Only two svg files were updated.

**Comment by jkseppan** [comment]
It's not *only* dropping zeros from the end, it's also 387.105882353 vs 387.105882

**Comment by tacaswell** [comment]
@QuLogic reported on gitter that the changes are 1 pixel by 1 bit (or around that magnitude).
