### ISSUE TITLE
pyplot import error when current directory contains a file named sip.py

### ISSUE THREAD

**Issue by florian-wagner** [matplotlib/matplotlib#7867]
### Bug report

**Bug summary**

When the current working directory containes a file named "sip.py" (I am working on spectral induced polarization), `import matplotlib.pyplot` gives a qt-related import error. This has been reproduced with 1.5.1, 1.5.3, 2.0rc with debian packages and within a conda environment.

**Code for reproduction**

``` bash
>>> python3 -c "import matplotlib; print(matplotlib.__version__); import matplotlib.pyplot"
2.0.0rc2
>>> touch sip.py
>>> python3 -c "import matplotlib; print(matplotlib.__version__); import matplotlib.pyplot"
2.0.0rc2
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/usr/lib/python3/dist-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_qt4agg.py", line 18, in <module>
    from .backend_qt5agg import FigureCanvasQTAggBase as _FigureCanvasQTAggBase
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_qt5agg.py", line 16, in <module>
    from .backend_qt5 import QtCore
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_qt5.py", line 26, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "/usr/lib/python3/dist-packages/matplotlib/backends/qt_editor/figureoptions.py", line 20, in <module>
    import matplotlib.backends.qt_editor.formlayout as formlayout
  File "/usr/lib/python3/dist-packages/matplotlib/backends/qt_editor/formlayout.py", line 56, in <module>
    from matplotlib.backends.qt_compat import QtGui, QtWidgets, QtCore
  File "/usr/lib/python3/dist-packages/matplotlib/backends/qt_compat.py", line 137, in <module>
    from PyQt4 import QtCore, QtGui
SystemError: initialization of QtCore failed without raising an exception
```

**Comment by jenshnielsen** [comment]
This is not really a bug in Matplotlib but a consequence of how the import system in python works.

The Matplotlib QT backend uses PyQT4/5 which internally uses sip https://pypi.python.org/pypi/SIP when you import any python module python will first look for a file with the same name in your local directory. 

I.e. If you try using numpy from a directory containing a numpy.py file it will fail too

**Comment by florian-wagner** [comment]
Makes sense. Just took me a while since there is no mentioning of sip in the error message. So one really has to be careful with naming if the list of dependencies grows. Anyhow, thanks a lot. Closing this.

**Comment by WeatherGod** [comment]
one way to avoid getting into this trap yourself is to develop your
codebase as a module, that way, you can say "from . import sip", which will
never pick up the sip package installed in site-packages.
