### ISSUE TITLE
Matplotlib 2.0 cannot find PyQt5 (Windows)

### ISSUE THREAD

**Issue by jat255** [matplotlib/matplotlib#7958]
### Bug report

**Bug summary**

- With Matplotlib 2.0 and PyQt5 (5.7.1), I cannot use the PyQt5 backend for interactive plotting

**Code for reproduction**

```python
import matplotlib
matplotlib.use("Qt5Agg")
import matplotlib.pyplot as plt
```

**Actual outcome**

```
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\matplotlib\backends\qt_compat.py", line 172, in <module>
    from PySide import QtCore, QtGui, __version__, __version_info__
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python36\lib\site-packages\matplotlib\pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "C:\Python36\lib\site-packages\matplotlib\backends\__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "C:\Python36\lib\site-packages\matplotlib\backends\backend_qt5agg.py", line 16, in <module>
    from .backend_qt5 import QtCore
  File "C:\Python36\lib\site-packages\matplotlib\backends\backend_qt5.py", line 26, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "C:\Python36\lib\site-packages\matplotlib\backends\qt_editor\figureoptions.py", line 20, in <module>
    import matplotlib.backends.qt_editor.formlayout as formlayout
  File "C:\Python36\lib\site-packages\matplotlib\backends\qt_editor\formlayout.py", line 56, in <module>
    from matplotlib.backends.qt_compat import QtGui, QtWidgets, QtCore
  File "C:\Python36\lib\site-packages\matplotlib\backends\qt_compat.py", line 175, in <module>
    "Matplotlib qt-based backends require an external PyQt4, PyQt5,\n"
ImportError: Matplotlib qt-based backends require an external PyQt4, PyQt5,
or PySide package to be installed, but it was not found.
```

**Expected outcome**

- This should not produce an error, ideally.

**Matplotlib version**

```
$ ipython                                                                                                    
Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)]
```

```
$ pip show matplotlib
Name: matplotlib
Version: 2.0.0
Summary: Python plotting package
Home-page: http://matplotlib.org
Author: John D. Hunter, Michael Droettboom
Author-email: matplotlib-users@python.org
License: BSD
Location: c:\python36\lib\site-packages
Requires: python-dateutil, six, pyparsing, numpy, cycler, pytz
```

```
$ pip show pyqt5
Name: PyQt5
Version: 5.7.1
Summary: Python bindings for the Qt cross platform UI and application toolkit
Home-page: https://www.riverbankcomputing.com/software/pyqt/
Author: Riverbank Computing Limited
Author-email: info@riverbankcomputing.com
License: GPL v3
Location: c:\python36\lib\site-packages
Requires: sip
```

- How did you install Matplotlib and Python (pip, anaconda, from source ...)

Both `matplotlib` and `PyQt5` installed from pypi sources using `pip`

**Comment by tacaswell** [comment]
Can you `import PyQt5` in ipython?

**Comment by jat255** [comment]
Sorry, I should have mentioned. Yes, importing `PyQt5` is not a problem.

**Comment by tacaswell** [comment]
how about `import sip`?

**Comment by jat255** [comment]
That does not work: `ModuleNotFoundError: No module named 'sip'`

But I do have `sip` installed.

Anyway, I uninstalled sip and reinstalled it (clearing pip's cache), and all seems well now. I'm not sure what went wrong....

**Comment by tacaswell** [comment]
Some packaging questions are best left un-answered :wink:

**Comment by 372046933** [comment]
On arch linux, this can be solved by `pacman -S --needed python-sip`

**Comment by tacaswell** [comment]
We are going to be broken in a very major way be the latest verison of pyqt....

**Comment by RouquinBlanc** [comment]
Hum... 

I was hitting the same error on mac with pyqt5, but reinstalling it made an update to sip-4.19.8 and now it works properly...

**Comment by tacaswell** [comment]
The issue is that riverbank decided to make `sip` a 'private' package of pyqt.  We try to `import sip` _first_ to see if we are using pyqt or pyside.  As this now fails, we conclude pyqt is not installed and try pyside instead.

Getting a 2.2.3 out the door ASAP is on my radar (specifically due to this issue).

**Comment by evadeflow** [comment]
I'm having the exact same issue, and traced it back to the `import sip` check mentioned by @tacaswell. I definitely do have PyQt5 installed (from PyPI, using `pip install pyqt5`).  I guess when Riverbank made `sip` a private package, its name changed to `PyQt5-sip`:

```
$ pip freeze | grep -i sip
PyQt5-sip==4.19.12
```

While trying to work around this, I discovered that the latest PyQt5 package (5.11.2) is _broken_:

```
$ python3 -m venv pyqt5
$ source pyqt5/bin/activate
(pyqt5) $ pip install PyQt5
Collecting PyQt5
  Using cached https://files.pythonhosted.org/packages/3a/c7/4a9bec78c864051051b41b4cc76672ecc232e6dc7dbb91a5f8ff6f20ff64/PyQt5-5.11.2-5.11.1-cp35.cp36.cp37.cp38-abi3-manylinux1_x86_64.whl
Collecting PyQt5_sip<4.20,>=4.19.11 (from PyQt5)
  Using cached https://files.pythonhosted.org/packages/1f/73/a097e063ea84f9c0d5641bd45fd0147d7e88ad0e92c86638fa7ada14f436/PyQt5_sip-4.19.12-cp35-cp35m-manylinux1_x86_64.whl
Installing collected packages: PyQt5-sip, PyQt5
Successfully installed PyQt5-5.11.2 PyQt5-sip-4.19.12
You are using pip version 8.1.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(pyqt5) $ python
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from PyQt5 import QtCore, QtGui, QtWidgets
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /home/dwolfe/projects/ai_knowledge_model/pyqt5/lib/python3.5/site-packages/PyQt5/QtCore.so: undefined symbol: PySlice_AdjustIndices
>>>
```
I guess I'll file a bug with Riverbank...

In the meantime, my solution was to:

```
$ pip uninstall pyqt5
$ pip install pyqt5==5.10.1
```

(Whatever bug is present in 5.11.2 is missing in 5.10.1.)

**Comment by itsayushthada** [comment]
Install **PySide** package if you are using Python < 3.4 else go for the **PySide2** package.

After this, you can just use **%matplotlib qt**
