### ISSUE TITLE
necked_tensile_specimen.png contains non-free color calibration profile

### ISSUE THREAD

**Issue by sandrotosi** [matplotlib/matplotlib#8034]
Hello,
as reported in http://bugs.debian.org/854280, lib/matplotlib/mpl-data/sample_data/necked_tensile_specimen.png calibration code is copyrighted by Apple but no license is specified, so the "all rights reserved" means it's a non-free package, possible even totally non-distributable (ie it shouldnt be in the upstream tarball/repo at all):

```
$ exiftool lib/matplotlib/mpl-data/sample_data/necked_tensile_specimen.png
ExifTool Version Number         : 10.40
File Name                       : necked_tensile_specimen.png
Directory                       : lib/matplotlib/mpl-data/sample_data
File Size                       : 93 kB
File Modification Date/Time     : 2017:01:17 22:48:59-05:00
File Access Date/Time           : 2017:01:17 22:48:59-05:00
File Inode Change Date/Time     : 2017:01:17 22:48:59-05:00
File Permissions                : rw-r--r--
File Type                       : PNG
File Type Extension             : png
MIME Type                       : image/png
Image Width                     : 634
Image Height                    : 945
Bit Depth                       : 8
Color Type                      : RGB with Alpha
Compression                     : Deflate/Inflate
Filter                          : Adaptive
Interlace                       : Noninterlaced
Profile Name                    : ICC Profile
Profile CMM Type                : appl
Profile Version                 : 2.2.0
Profile Class                   : Display Device Profile
Color Space Data                : RGB
Profile Connection Space        : XYZ
Profile Date Time               : 2009:02:25 11:26:11
Profile File Signature          : acsp
Primary Platform                : Apple Computer Inc.
CMM Flags                       : Not Embedded, Independent
Device Manufacturer             : appl
Device Model                    : 
Device Attributes               : Reflective, Glossy, Positive, Color
Rendering Intent                : Perceptual
Connection Space Illuminant     : 0.9642 1 0.82491
Profile Creator                 : appl
Profile ID                      : 0
Profile Description             : Generic RGB Profile
Profile Description ML (sk-SK)  : Všeobecný RGB profil
Profile Description ML (hr-HR)  : Generički RGB profil
Profile Description ML (ca-ES)  : Perfil RGB genèric
Profile Description ML (pt-BR)  : Perfil RGB Genérico
Profile Description ML (uk-UA)  : Загальний профайл RGB
Profile Description ML (fr-FU)  : Profil générique RVB
Profile Description ML (zh-TW)  : 通用 RGB 色彩描述
Profile Description ML (it-IT)  : Profilo RGB generico
Profile Description ML (nb-NO)  : Generisk RGB-profil
Profile Description ML (ko-KR)  : 일반 RGB 프로파일
Profile Description ML (cs-CZ)  : Obecný RGB profil
Profile Description ML (he-IL)  : פרופיל RGB כללי
Profile Description ML (de-DE)  : Allgemeines RGB-Profil
Profile Description ML (hu-HU)  : Általános RGB profil
Profile Description ML (sv-SE)  : Generisk RGB-profil
Profile Description ML (zh-CN)  : 普通 RGB 描述文件
Profile Description ML (ja-JP)  : 一般 RGB プロファイル
Profile Description ML (ro-RO)  : Profil RGB generic
Profile Description ML (el-GR)  : Γενικό προφίλ RGB
Profile Description ML (pt-PO)  : Perfil RGB genérico
Profile Description ML (nl-NL)  : Algemeen RGB-profiel
Profile Description ML (es-ES)  : Perfil RGB genérico
Profile Description ML (th-TH)  : โปรไฟล์ RGB ทั่วไป
Profile Description ML (tr-TR)  : Genel RGB Profili
Profile Description ML (fi-FI)  : Yleinen RGB-profiili
Profile Description ML (pl-PL)  : Uniwersalny profil RGB
Profile Description ML (ru-RU)  : Общий профиль RGB
Profile Description ML (ar-EG)  : ملف تعريف RGB العام
Profile Description ML          : Generic RGB Profile
Profile Description ML (da-DK)  : Generel RGB-beskrivelse
Profile Copyright               : Copyright 2007 Apple Inc., all rights reserved.
Media White Point               : 0.95047 1 1.0891
Red Matrix Column               : 0.4543 0.24191 0.01489
Green Matrix Column             : 0.35335 0.67363 0.09064
Blue Matrix Column              : 0.15665 0.08446 0.71957
Red Tone Reproduction Curve     : (Binary data 14 bytes, use -b option to extract)
Chromatic Adaptation            : 1.04788 0.02292 -0.0502 0.02957 0.99049 -0.01706 -0.00923 0.01508 0.75165
Blue Tone Reproduction Curve    : (Binary data 14 bytes, use -b option to extract)
Green Tone Reproduction Curve   : (Binary data 14 bytes, use -b option to extract)
Pixels Per Unit X               : 2835
Pixels Per Unit Y               : 2835
Pixel Units                     : meters
XMP Toolkit                     : XMP Core 5.1.2
Photometric Interpretation      : RGB
Orientation                     : Horizontal (normal)
Image Size                      : 634x945
Megapixels                      : 0.599
```

what would be the impact (in this case for Debian, in the immediate) if we just remove that file from what we distribute in debian? something will break? how badly it would break?

thanks for considering!

**Comment by tacaswell** [comment]
attn @breedlun

Can in via https://github.com/matplotlib/matplotlib/pull/2995 I have a suspicion that the meta-data is just wrong.

**Comment by breedlun** [comment]
Hmmm...  @tacaswell could be right that the meta-data is wrong.  I created that png file using paraview which is an open source visualization package, but I dunno if that means the color profile was necessarily open source.  

There is nothing special about that image, though.  We could replace it with just about any high rez image and still get the same point across.

**Comment by sandrotosi** [comment]
please note that this is an important bug for debian (it's what we call a Release Critical bug, which is possibly held back the release of the new debian stable distribution), i am open to any resolution of this, and i'm willing to help/test as needed

**Comment by QuLogic** [comment]
You can just leave it out; it's only used in `examples/images_contours_and_fields/interpolation_none_vs_nearest.py` (which is currently deleted on `master`, although the description may return somewhere.)

**Comment by sandrotosi** [comment]
thanks @QuLogic i will remove it from the tarball (and binary packages) distributed by debian, it'd be great to remove it entirely from matplotlib future releases (either 2.0.x and future 2.x) -- thanks!

**Comment by sandrotosi** [comment]
sadly it was not "just remove it" as it generated:

```
generating thumbnails... [100%] build/plot_directive/mpl_examples/pylab_examples/agg_buffer_to_array_01.png

Warning, treated as error:
/home/morph/deb/build-area/matplotlib-2.0.0+dfsg1/doc/examples/images_contours_and_fields/interpolation_none_vs_nearest.rst:8: WARNING: Exception occurred in plotting interpolation_none_vs_nea
rest
 from /home/morph/deb/build-area/matplotlib-2.0.0+dfsg1/doc/mpl_examples/images_contours_and_fields/interpolation_none_vs_nearest.py:
Traceback (most recent call last):
  File "/home/morph/deb/build-area/matplotlib-2.0.0+dfsg1/build/lib.linux-x86_64-2.7/matplotlib/sphinxext/plot_directive.py", line 520, in run_code
    six.exec_(code, ns)
  File "/usr/lib/python2.7/dist-packages/six.py", line 699, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "<string>", line 19, in <module>
  File "/home/morph/deb/build-area/matplotlib-2.0.0+dfsg1/build/lib.linux-x86_64-2.7/matplotlib/cbook.py", line 833, in get_sample_data
    return open(path, mode)
IOError: [Errno 2] No such file or directory: u'/home/morph/deb/build-area/matplotlib-2.0.0+dfsg1/lib/matplotlib/mpl-data/sample_data/necked_tensile_specimen.png'

Building HTML failed.
```

**Comment by QuLogic** [comment]
You need to remove the example that uses it as well.

**Comment by sandrotosi** [comment]
thanks all!
