### ISSUE TITLE
save animation to mp4 fail 

### ISSUE THREAD

**Issue by angelleng** [matplotlib/matplotlib#8053]
To help us understand and resolve your issue, please fill out the form to the best of your ability. You can feel free to delete the sections that do not apply.

### Bug report

**Bug summary**

- A short 1-2 sentences that succinctly describes the bug
I was trying to save an matplotlib.animation.ArtistAnimation object to mp4. but it failed and returned error: `ValueError: I/O operation on closed file` 

**Code for reproduction**

- A minimum code snippet required to reproduce the bug, also minimizing the number of dependencies required

```python
# Paste your code here
ims = [] 
for i in range(5): 
       im1, = plt.plot(x[:,0], x[:,1], 'b.')
        im2, = plt.plot(fakenp[:,0], fakenp[:,1], 'rx')
        ims.append([im1, im2])
ani = animation.ArtistAnimation(fig, ims, interval=100, blit=True,
    repeat_delay=1000) 
ani.save('sample.mp4', writer='ffmpeg')
```

**Actual outcome**

- The output produced by the above code, which may be a screenshot, console output, etc.

```
# If applicable, paste the console output here
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jingleng/envs/my_root/lib/python2.7/site-packages/matplotlib/animation.py", line 1013, in save
    writer.grab_frame(**savefig_kwargs)
  File "/home/jingleng/envs/my_root/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/jingleng/envs/my_root/lib/python2.7/site-packages/matplotlib/animation.py", line 256, in saving
    self.finish()
  File "/home/jingleng/envs/my_root/lib/python2.7/site-packages/matplotlib/animation.py", line 276, in finish
    self.cleanup()
  File "/home/jingleng/envs/my_root/lib/python2.7/site-packages/matplotlib/animation.py", line 311, in cleanup
    out, err = self._proc.communicate()
  File "/home/jingleng/envs/my_root/lib/python2.7/site-packages/subprocess32.py", line 927, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/home/jingleng/envs/my_root/lib/python2.7/site-packages/subprocess32.py", line 1713, in _communicate
    orig_timeout)
  File "/home/jingleng/envs/my_root/lib/python2.7/site-packages/subprocess32.py", line 1769, in _communicate_with_poll
    register_and_append(self.stdout, select_POLLIN_POLLPRI)
  File "/home/jingleng/envs/my_root/lib/python2.7/site-packages/subprocess32.py", line 1748, in register_and_append
    poller.register(file_obj.fileno(), eventmask)
ValueError: I/O operation on closed file
```

**Expected outcome**

it saves the animation to video file 'sample.mp4'. 

**Matplotlib version**

- using matplotlib 2.0.0, Python 2.7.13 :: Anaconda 2.1.0 (64-bit), on OSX. 
- installed both python and matplotlib through anaconda.

**Comment by WeatherGod** [comment]
just as a sanity check... is ffmpeg installed on your system?

**Comment by angelleng** [comment]
yes. 
```
$ which ffmpeg
/usr/local/bin/ffmpeg
```

**Comment by tacaswell** [comment]
I can not reproduce this

```python

import matplotlib.pyplot as plt
import matplotlib.animation as animation
import numpy as np

# Paste your code here
fig, ax = plt.subplots()
ims = []
N = 500
x = np.random.rand(N, 50, 2)
fakenp = np.random.rand(N, 50, 2)
for i in range(N):
    im1, = plt.plot(x[i, :, 0], x[i, :, 1], 'b.')
    im2, = plt.plot(fakenp[i, :, 0], fakenp[i, :, 1], 'rx')
    ims.append([im1, im2])
ani = animation.ArtistAnimation(fig, ims, interval=100, blit=True,
                                repeat_delay=1000)
ani.save('sample.mp4', writer='ffmpeg')
```

This might be a mac-specific bug?

**Comment by dopplershift** [comment]
Works for me on OSX with python 2.7 and matplotlib 2.0 (everything installed from conda-forge, including ffmpeg).

Can you run the script with the additional command line argument `--verbose-debug`?

**Comment by angelleng** [comment]
Guys turned out I was using outdated ffmpeg (1.2.1). Also I put the platform wrong. I was working on a linux server (RHEL) and got confused when entering the bug report. 

Sorry about the confusion!

**Comment by WeatherGod** [comment]
glad you got it sorted out!
