### ISSUE TITLE
"RuntimeError: could not create GdkCursor object" when import gtk

### ISSUE THREAD

**Issue by premier424** [matplotlib/matplotlib#8132]
I run some python code with matplotlib but meet the error "could not create Gdk Cursor object" when import the ```FigureCanvasGTK``` from ```matplotlib``` python version is 2.7.6 and matplotlib version is 1.5.0 installed using pip: 
```
/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_gtk.py:61: GtkWarning:     IA__gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
cursors.MOVE          : gdk.Cursor(gdk.FLEUR),
2017-02-22 19:06:16 DEBUG [PythonGadget.h:106] Error loading python modules in Gadget ImageViewPython
Traceback (most recent call last):
File "/usr/local/bin/..//share/gadgetron/python/image_viewer.py", line 8, in 
from matplotlib.backends.backend_gtk import FigureCanvasGTK as FigureCanvas
File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_gtk.py", line 61, in 
cursors.MOVE          : gdk.Cursor(gdk.FLEUR)
RuntimeError: could not create GdkCursor object
```
I searched this issue online and try to change backend in ```matplotlibrc``` from GtkAgg to Agg but still doesn't work and report the same error. In ```image_viewer.py``` there are some codes above the error 
```
occurred in case: 
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.figure import Figure
from matplotlib.backends.backend_gtk import FigureCanvasGTK as FigureCanvas
from matplotlib.backends.backend_gtkagg import NavigationToolbar2GTKAgg as NavigationToolbar
```

Please give me some hint where I should checked and where to debug this problem. Thanks.

**Comment by anntzer** [comment]
The GTK backend has been removed a while ago.
