### ISSUE TITLE
Segfault during savefig for imshow of 10k x 10k matrix

### ISSUE THREAD

**Issue by willfurnass** [matplotlib/matplotlib#8350]
### Bug report

**Bug summary**

`savefig` causes a segfault when trying to save a figure containing an `imshow` plot that was generated from a 10k * 10k matrix

**Code for reproduction**

```python
import matplotlib
matplotlib.use('AGG')
import matplotlib.pyplot as plt
import numpy as np

Y = np.random.rand(10255, 10255)
fig, ax = plt.subplots()
ax.imshow(Y)
ax.set_agg_filter(None)
fig.savefig('test.png')
```

**Actual outcome**

Output generated by `gdb -batch -ex "run" -ex "bt" -args python imshow_test.py`:

```
Program received signal SIGSEGV, Segmentation fault.
agg::span_image_filter_rgba_nn<agg::image_accessor_wrap<agg::pixfmt_alpha_blend_rgba<agg::blender_rgba_plain<agg::rgba64, agg::order_rgba>, agg::row_accessor<unsigned char> >, agg::wrap_mode_reflect, agg::wrap_mode_reflect>, agg::span_interpolator_linear<agg::trans_affine, 8u> >::generate (this=<optimized out>, len=370, y=2621732, x=3548, span=0x1175ff0) at extern/agg24-svn/include/agg_span_image_filter_rgba.h:68
68      extern/agg24-svn/include/agg_span_image_filter_rgba.h: No such file or directory.
#0  agg::span_image_filter_rgba_nn<agg::image_accessor_wrap<agg::pixfmt_alpha_blend_rgba<agg::blender_rgba_plain<agg::rgba64, agg::order_rgba>, agg::row_accessor<unsigned char> >, agg::wrap_mode_reflect, agg::wrap_mode_reflect>, agg::span_interpolator_linear<agg::trans_affine, 8u> >::generate (this=<optimized out>, len=370, y=2621732, x=3548, span=0x1175ff0) at extern/agg24-svn/include/agg_span_image_filter_rgba.h:68
#1  agg::span_converter<agg::span_image_filter_rgba_nn<agg::image_accessor_wrap<agg::pixfmt_alpha_blend_rgba<agg::blender_rgba_plain<agg::rgba64, agg::order_rgba>, agg::row_accessor<unsigned char> >, agg::wrap_mode_reflect, agg::wrap_mode_reflect>, agg::span_interpolator_linear<agg::trans_affine, 8u> >, span_conv_alpha<agg::rgba64> >::generate (len=370, y=0, x=0, span=<optimized out>, this=0x7fffffffb240) at extern/agg24-svn/include/agg_span_converter.h:45
#2  agg::render_scanline_aa<agg::scanline_u8, agg::renderer_base<agg::pixfmt_alpha_blend_rgba<agg::blender_rgba_plain<agg::rgba64, agg::order_rgba>, agg::row_accessor<unsigned char> > >, agg::span_allocator<agg::rgba64>, agg::span_converter<agg::span_image_filter_rgba_nn<agg::image_accessor_wrap<agg::pixfmt_alpha_blend_rgba<agg::blender_rgba_plain<agg::rgba64, agg::order_rgba>, agg::row_accessor<unsigned char> >, agg::wrap_mode_reflect, agg::wrap_mode_reflect>, agg::span_interpolator_linear<agg::trans_affine, 8u> >, span_conv_alpha<agg::rgba64> > > (sl=..., ren=..., alloc=..., span_gen=...) at extern/agg24-svn/include/agg_renderer_scanline.h:168
#3  0x00007fffeb4a0441 in agg::renderer_scanline_aa<agg::renderer_base<agg::pixfmt_alpha_blend_rgba<agg::blender_rgba_plain<agg::rgba64, agg::order_rgba>, agg::row_accessor<unsigned char> > >, agg::span_allocator<agg::rgba64>, agg::span_converter<agg::span_image_filter_rgba_nn<agg::image_accessor_wrap<agg::pixfmt_alpha_blend_rgba<agg::blender_rgba_plain<agg::rgba64, agg::order_rgba>, agg::row_accessor<unsigned char> >, agg::wrap_mode_reflect, agg::wrap_mode_reflect>, agg::span_interpolator_linear<agg::trans_affine, 8u> >, span_conv_alpha<agg::rgba64> > >::render<agg::scanline_u8> (sl=..., this=<optimized out>) at extern/agg24-svn/include/agg_renderer_scanline.h:227
#4  agg::render_scanlines<resample(const T*, int, int, T*, int, int, resample_params_t&) [with T = agg::rgba64]::rasterizer_t, agg::scanline_u8, resample(const T*, int, int, T*, int, int, resample_params_t&) [with T = agg::rgba64]::nn_renderer_t> (ren=..., sl=..., ras=...) at extern/agg24-svn/include/agg_renderer_scanline.h:446
#5  resample<agg::rgba64> (input=<optimized out>, in_width=<optimized out>, in_height=10255, output=<optimized out>, out_width=370, out_height=370, params=...) at src/_image_resample.h:969
#6  0x00007fffeb486bbf in image_resample (self=<optimized out>, args=<optimized out>, kwargs=<optimized out>) at src/_image_wrapper.cpp:263
#7  0x00007ffff79a6621 in PyCFunction_Call (func=<built-in method resample of module object at remote 0x7fffeb6b3e58>, args=(<numpy.ndarray at remote 0x7fffb561ea30>, <numpy.ndarray at remote 0x7fffb561eb20>, <CompositeGenericTransform(output_dims=2, _invalid=1, _a=<CompositeGenericTransform(output_dims=2, _invalid=1, _a=<CompositeGenericTransform(output_dims=2, _invalid=1, _a=<Affine2D(_invalid=0, _inverted=None, _mtx=<numpy.ndarray at remote 0x7fffb561e760>, _shorthand_name='', _parents=<WeakValueDictionary(_pending_removals=[], _iterating=set(), _remove=<function at remote 0x7fffb5610730>, data={140736236495872: <KeyedRef at remote 0x7fffb560b780>}) at remote 0x7fffb56222b0>) at remote 0x7fffb5622278>, input_dims=2, _shorthand_name='', _parents=<WeakValueDictionary(_pending_removals=[], _iterating=set(), _remove=<function at remote 0x7fffb56108c8>, data={140736236496264: <KeyedRef at remote 0x7fffb560b830>}) at remote 0x7fffb5622438>, _b=<CompositeGenericTransform(output_dims=2, _invalid=1, _a=<Affine2D(_invalid=0, _inverted=None, _mtx=<numpy.ndarray at remote 0x7fffb561e800>, _shorthand_name='', _parents=<WeakValueDictionary(_...(truncated), kwds=<optimized out>) at Objects/methodobject.c:98
...
```

**Expected outcome**

- Program writes a PNG file to disk then exits without segfaulting.

**Matplotlib version**

matplotlib 2.0.0, pyqt 5.6.0, py35_2 and python 3.5.2 in a conda environment on Arch Linux

**Comment by phobson** [comment]
Thanks for the detailed and reproduible report. I get analogous behavior in Windows 10.

**Comment by tacaswell** [comment]
This appear to be fixed on current master, closing.

If you can still reproduce this please ping to have re-opened.

Thank you for reporting @willfurnass
