### ISSUE TITLE
plt.pcolormesh shape mismatch when shading='gouraud'

### ISSUE THREAD

**Issue by egranstedt** [matplotlib/matplotlib#8422]
### Bug report

**Bug summary**

When running `plt.pcolormesh(X, Y, C, shading='flat')`, if `C.shape == (nrows, ncols)`, then if `X` and `Y` are 2-D arrays, their shapes must be either `(nrows, ncols)` or `(nrows+1, ncols+1)`.  If `shading='gouraud'`, however, the latter results in an error.  The code snippet below uses 1-D arrays for `X` and `Y`, but the same error occurs when they are the equivalent 2-D arrays.

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt
x = np.arange(-4, 5)
y = np.arange(-6, 7)
xe = np.linspace(-4.5, 4.5, 10)
ye = np.linspace(-6.5, 6.5, 14)
c = np.exp(-0.5*0.125*(x.reshape(1, -1)**2 + y.reshape(-1, 1)**2))
plt.pcolormesh(xe, ye, c, shading='flat')  # works
plt.pcolormesh(x, y, c, shading='gouraud')  # works
plt.pcolormesh(xe, ye, c, shading='gouraud')  # doesn't work
```

**Actual outcome**

```
Traceback (most recent call last):

  File "<ipython-input-67-154f761638cd>", line 1, in <module>
    plt.pcolormesh(xe, ye, c, shading='gouraud')

  File "/home/egranstedt/anaconda3/lib/python3.6/site-packages/matplotlib/pyplot.py", line 3245, in pcolormesh
    ret = ax.pcolormesh(*args, **kwargs)

  File "/home/egranstedt/anaconda3/lib/python3.6/site-packages/matplotlib/__init__.py", line 1892, in inner
    return func(ax, *args, **kwargs)

  File "/home/egranstedt/anaconda3/lib/python3.6/site-packages/matplotlib/axes/_axes.py", line 5569, in pcolormesh
    X, Y, C = self._pcolorargs('pcolormesh', *args, allmatch=allmatch)

  File "/home/egranstedt/anaconda3/lib/python3.6/site-packages/matplotlib/axes/_axes.py", line 5187, in _pcolorargs
    C.shape, Nx, Ny, funcname))

TypeError: Dimensions of C (13, 9) are incompatible with X (10) and/or Y (14); see help(pcolormesh)
```

**Expected outcome**

I expected `pcolormesh` would accept the same arrays for `X` and `Y  irrespective of the setting of the `shading` keyword argument.

**Matplotlib version**

- The error occurs with Matplotlib version 2.0.0 in the python 3.6 interpreter on Linux (installed via anaconda), but also seems to exist in older versions of Matplotlib (e.g., 1.5.1)

**Comment by tacaswell** [comment]
Exact work:

 - [ ] sort out if we can handle the N+1 case for gourand shading
 - [ ] if so, fix the bug, if not document the limitation

**Comment by AtharvaKhare** [comment]
Dimensions of `c` are wrong. Try this:
```
import numpy as np
import matplotlib.pyplot as plt
xe = np.linspace(-4.5, 4.5, 10)
ye = np.linspace(-6.5, 6.5, 14)
c = np.exp(-0.5*0.125*(x.reshape(1, -1)**2 + y.reshape(-1, 1)**2))
plt.pcolormesh(xe, ye, c, shading='gouraud') 
```
Should I add additional documentation for shading?

**Comment by dopplershift** [comment]
The actual problem here is that if you don't use the Gouraud shading, pcolormesh is capable of automatically adjusting dimensions so that the original example works. The question is what it will take for Gouraud shading to work when given the slightly mis-shaped data.

**Comment by QuLogic** [comment]
@jklymak since you just finished working on the 'flat' case, I wonder if you have any thought here (and on the linked PR)?

**Comment by jklymak** [comment]
I think interpolating the grid midpoints  is "fine" to make gouraud work, maybe with a warning.  The linked PR died because the author insisted on a kwarg controlling whether that would happen or not, which I didn't agree with.

**Comment by jklymak** [comment]
This is still an issue.

**Comment by lucaznch** [comment]
@jklymak I'd like to work on this good first issue if possible. My approach is to add support for the N+1 case in gouraud shading by emitting a warning and reshaping X and Y using interpolation.

**Comment by timhoffm** [comment]
Is the original request meaningful? Different types of "assigning colors to grids" have different intrinsic relations between grid points structue and color structure:
- *colors specified on the grid points*: shapes are identical
  To fill the area one has to specify the interpolation behavior between the points; i.e. *shading* "nearest" or "gouraud"
- *colors specified on the quadrilaterals*: One needs one more grid point than colors per direction - *shading* "flat"
  We have one quirk here that we accept same-shape and drop the last color (with a warning). IMHO this is logically wrong and potentially dangerous. We only have this for backward-compatibility reasons.

By it's nature guraud shading requires colors on the grid points. Can't we just stick with this requirement and be done?

Yes one could interpolate another grid centering in between and assign the colors to this, Say I have an integer grid; one quadilateral is spanned by (0,0), (0,1), (1, 1), (1, 0); it's interpolated grid point is at (0.5, 0.5). this would get color C[0, 0]. We can use gouraud shading on the interpolated grid with C. This means, that the edge quadrilaterals are not filled. i.e. here for x<0.5, y<0.5. Is that what we want or do you plan to extrapolate? 

I'm not very convinced this is needed but see that it could be nice to switch from "flat" to a smoother visualiztion. If we want to do this I'd strongly advocate to introduce a new shading variant like "centered-gouraud" and not let "gourauld" automatically decide based on input size. Automatic decision would disguise errors or slopy data specifications.

**Comment by lucaznch** [comment]
My understanding from the discussion in this issue is that two main approaches were considered:
1. keep the error to enforce correctness (and possibly provide a helper function to reshape the grid)
2. handle the (nrows+1, ncols+1) case.

I definitly understand the first. But my thinking in going with the second approach was mainly to provide a fallback instead of raising an error, for the situation where users provide the (nrows+1, ncols+1) grid togteher with (nrows, ncols) colors for gouraud. This seems like a possible common pattern, especially when switching from flat shading.

As was mentioned earlier in the discussion:
> I can't imagine a case where a user is going to complain that they got a plot instead of an error telling them to futz with their dimensions.

The implementation I am working on emits a warning and then converts the grid to match the shape of C using midpoint interpolation, so that colors correspond to grid points. This conversion changes the grid domain, however this would not happen silently since the warning would inform the user that the grid was reshaped.

Below is an image showing an actual interpolation for gourad, having the flat shading for reference, for a simple 3x3 grid and a 2x2 C.

<img width="915" height="339" alt="Image" src="https://github.com/user-attachments/assets/d1e3db21-4215-4b3d-bbce-7ca748cbef54" />

**Comment by timhoffm** [comment]
> The implementation I am working on emits a warning and then converts the grid to match the shape of C using midpoint interpolation, so that colors correspond to grid points.

This is a reasonable functionality.

> This conversion changes the grid domain, however this would not happen silently since the warning would inform the user that the grid was reshaped.

The problem with the warning is that it will always be there, even if the user does this intentionally and knows about the grid effect.

Giving two separate shading values allows the user to communicate intent, and us acting accordingly. If we have the one more grid point than color case
- `shading="gouraud"` should error out with
  > ValueError: shading="gouraud" requires an equal number of colors and grid points since the colors are defind on the grid points. If you have colors on the quadrilateral centers you may want to use shading="centered-gouraud"
- `shading="centered-gouraud"` silently work.
