### ISSUE TITLE
TclError bad cursor spec thrown while using pyplot.plot

### ISSUE THREAD

**Issue by quinnkjones** [matplotlib/matplotlib#8438]
### Bug report

Attempting to call matplotlib.pyplot.plot even on very simple vectors and without deviating from the default cursor, marker options etc.  Throws the following exception in ipython: TclError: bad cursor spec "#A5BFCA" 

**Reproduce error with:**

```
import matplotlib.pyplot as plt
import numpy as np

x = np.arange(0,10)
y = np.arange(4,14) 

plt.plot(x,y)
```

**Actual outcome**

```
/usr/lib/python2.7/dist-packages/matplotlib/pyplot.pyc in plot(*args, **kwargs)
   3145 @_autogen_docstring(Axes.plot)
   3146 def plot(*args, **kwargs):
-> 3147     ax = gca()
   3148     # allow callers to override the hold state by passing hold=True|False
   3149     washold = ax.ishold()

/usr/lib/python2.7/dist-packages/matplotlib/pyplot.pyc in gca(**kwargs)
    926     matplotlib.figure.Figure.gca : The figure's gca method.
    927     """
--> 928     return gcf().gca(**kwargs)
    929 
    930 # More ways of creating axes:

/usr/lib/python2.7/dist-packages/matplotlib/pyplot.pyc in gcf()
    576         return figManager.canvas.figure
    577     else:
--> 578         return figure()
    579 
    580 

/usr/lib/python2.7/dist-packages/matplotlib/pyplot.pyc in figure(num, figsize, dpi, facecolor, edgecolor, frameon, FigureClass, **kwargs)
    525                                         frameon=frameon,
    526                                         FigureClass=FigureClass,
--> 527                                         **kwargs)
    528 
    529         if figLabel:

/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_tkagg.pyc in new_figure_manager(num, *args, **kwargs)
     82     FigureClass = kwargs.pop('FigureClass', Figure)
     83     figure = FigureClass(*args, **kwargs)
---> 84     return new_figure_manager_given_figure(num, figure)
     85 
     86 

/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_tkagg.pyc in new_figure_manager_given_figure(num, figure)
     90     """
     91     _focus = windowing.FocusManager()
---> 92     window = Tk.Tk()
     93     window.withdraw()
     94 

/usr/lib/python2.7/lib-tk/Tkinter.pyc in __init__(self, screenName, baseName, className, useTk, sync, use)
   1816                 baseName = baseName + ext
   1817         interactive = 0
-> 1818         self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
   1819         if useTk:
   1820             self._loadtk()

TclError: bad cursor spec "#A5BFCA"
```

**Matplotlib version**

- Matplotlib version: 1.5.1
- python 2.7.12
- ipython 5.2.2 
- Ubuntu Linux 16.04 with xfce and i3wm
- python, ipython, matplotlib, and numpy were all installed via apt

**Comment by matthew-brett** [comment]
Would you mind trying the latest matplotlib to see if you get the same behavior?

```
curl -LO https://bootstrap.pypa.io/get-pip.py
python get-pip.py --user
~/.local/bin/pip install matplotlib
```

**Comment by matthew-brett** [comment]
Sorry - note edit adding ``--user`` install - you want:

```
~/.local/bin/pip install --user matplotlib
```

**Comment by quinnkjones** [comment]
No problem,
I installed it via pip and confirmed that matplotlib.__version__ was 2.0.0 and I still got the same behavior

**Comment by jenshnielsen** [comment]
What happens of you just try to create a TK instance without matplotlib?

```
Python 2.7.13 (default, Dec 18 2016, 07:03:39)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tkinter as Tk
>>> Tk.Tk()
<Tkinter.Tk instance at 0x10171bf38>
>>>
```

**Comment by quinnkjones** [comment]
I cannot import tkinter as the module is not there. that said `import _tkinter`  does work.

**Comment by quinnkjones** [comment]
to be clear 
`import tkinter`
gives 
`ImportError: No module named tkinter`

**Comment by jenshnielsen** [comment]
sorry the module is Tkinter in python 2 (on osx it's case insensitive anyway)

**Comment by quinnkjones** [comment]
It does give the same exception back
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1818, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: bad cursor spec "#A5BFCA"
```

**Comment by jenshnielsen** [comment]
Ok then it looks like there is something wrong with your python or tk/tcl tkinter installation. 

As a workaround you can use matplotlib with a different backend. Such as:
```
import matplotlib
matplotlib.use('Qt5Agg')
```
before importing matplotlib.pyplot to use the QT5Agg backend. 

To fix the tk error I guess you should try reinstalling python and or python-tk from apt?

**Comment by jenshnielsen** [comment]
It might also be useful to look at the output of 

```
>>> import _tkinter
>>> _tkinter.__file__
```
and if that points to a file installed by apt?

**Comment by quinnkjones** [comment]
/usr/lib/python2.7/lib-dynload/_tkinter.so

since it isn't in site-packages or dist-packages looks like apt is in charge no?

**Comment by jenshnielsen** [comment]
Yes I would guess so. I guess it's possible that tcl/tk just doesn't play well with xfce or i3wm

**Comment by anntzer** [comment]
Closed as this is arguably a Tk problem.
