### ISSUE TITLE
plt.hist: Unable to plot multiple distributions when x is a datetime

### ISSUE THREAD

**Issue by crawles** [matplotlib/matplotlib#8459]
To help us understand and resolve your issue, please fill out the form to the best of your ability. You can feel free to delete the sections that do not apply.

### Bug report

**Bug summary**

When one tries to plot two distributions, with x as a datetime, you get an error.

**Code for reproduction**

```python
from matplotlib import pyplot as plt
import pandas as pd
import numpy as np

rng = pd.date_range('1/1/2011', periods=10, freq='H')

x = rng
w1 = np.arange(0,1,.1)
w2 = np.arange(0,1,.1)[::-1]
plt.hist([x,x],weights=[w1,w2])

plt.show()
```

**Actual outcome**

- The output produced by the above code, which may be a screenshot, console output, etc.

```
ValueError: weights should have the same shape as x
```

**Expected outcome**

It two plot two different distributions on the same histogram

**Matplotlib version**
1.5.1, 2.7.12 Anaconda install, Mac OSX

**Comment by dstansby** [comment]
Hmm, I get a different error:

```
>>> plt.hist([x,x],weights=[w1,w2])
Traceback (most recent call last):
  File "/Users/dstansby/miniconda3/lib/python3.6/site-packages/pandas/tseries/converter.py", line 213, in convert
    values = tools.to_datetime(values)
  File "/Users/dstansby/miniconda3/lib/python3.6/site-packages/pandas/util/decorators.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/Users/dstansby/miniconda3/lib/python3.6/site-packages/pandas/tseries/tools.py", line 428, in to_datetime
    return _convert_listlike(arg, box, format)
  File "/Users/dstansby/miniconda3/lib/python3.6/site-packages/pandas/tseries/tools.py", line 401, in _convert_listlike
    require_iso8601=require_iso8601
  File "pandas/tslib.pyx", line 2374, in pandas.tslib.array_to_datetime (pandas/tslib.c:46691)
  File "pandas/tslib.pyx", line 2602, in pandas.tslib.array_to_datetime (pandas/tslib.c:46395)
  File "pandas/tslib.pyx", line 2535, in pandas.tslib.array_to_datetime (pandas/tslib.c:45342)
TypeError: <class 'pandas.tseries.index.DatetimeIndex'> is not convertible to datetime

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dstansby/matplotlib/lib/matplotlib/pyplot.py", line 3013, in hist
    stacked=stacked, data=data, **kwargs)
  File "/Users/dstansby/matplotlib/lib/matplotlib/__init__.py", line 1803, in inner
    return func(ax, *args, **kwargs)
  File "/Users/dstansby/matplotlib/lib/matplotlib/axes/_axes.py", line 6138, in hist
    x = self.convert_xunits(x)
  File "/Users/dstansby/matplotlib/lib/matplotlib/artist.py", line 199, in convert_xunits
    return ax.xaxis.convert_units(x)
  File "/Users/dstansby/matplotlib/lib/matplotlib/axis.py", line 1471, in convert_units
    ret = self.converter.convert(x, self.units, self)
  File "/Users/dstansby/miniconda3/lib/python3.6/site-packages/pandas/tseries/converter.py", line 219, in convert
    values = _dt_to_float_ordinal(values)
  File "/Users/dstansby/miniconda3/lib/python3.6/site-packages/pandas/tseries/converter.py", line 178, in _dt_to_float_ordinal
    base = dates.date2num(dt)
  File "/Users/dstansby/matplotlib/lib/matplotlib/dates.py", line 362, in date2num
    return _to_ordinalf_np_vectorized(d)
  File "/Users/dstansby/miniconda3/lib/python3.6/site-packages/numpy/lib/function_base.py", line 2576, in __call__
    return self._vectorize_call(func=func, args=vargs)
  File "/Users/dstansby/miniconda3/lib/python3.6/site-packages/numpy/lib/function_base.py", line 2646, in _vectorize_call
    ufunc, otypes = self._get_ufunc_and_otypes(func=func, args=args)
  File "/Users/dstansby/miniconda3/lib/python3.6/site-packages/numpy/lib/function_base.py", line 2606, in _get_ufunc_and_otypes
    outputs = func(*inputs)
  File "/Users/dstansby/matplotlib/lib/matplotlib/dates.py", line 220, in _to_ordinalf
    base = float(dt.toordinal())
AttributeError: 'DatetimeIndex' object has no attribute 'toordinal'
```

(ps. I updated the original report to include `import numpy as np` in the example)

**Comment by Tuan333** [comment]
I also just ran into this problem as well. Had a closer look, the problem is that at line 1472 of `axis.py`, we called 
```
ret = self.converter.convert(x, self.units, self)
```
where `self.converter` is a `pandas.tseries.DatetimeConverter`. The function `DatetimeConverter.convert()` expects an**_element to be converted_**  and not a list. In our case, `x` is: 
```
x = [DatetimeIndex(['2011-01-01 00:00:00', '2011-01-01 01:00:00',
               '2011-01-01 02:00:00', '2011-01-01 03:00:00',
               '2011-01-01 04:00:00', '2011-01-01 05:00:00',
               '2011-01-01 06:00:00', '2011-01-01 07:00:00',
               '2011-01-01 08:00:00', '2011-01-01 09:00:00'],
              dtype='datetime64[ns]', freq='H'),
         DatetimeIndex(['2011-01-01 00:00:00', '2011-01-01 01:00:00',
               '2011-01-01 02:00:00', '2011-01-01 03:00:00',
               '2011-01-01 04:00:00', '2011-01-01 05:00:00',
               '2011-01-01 06:00:00', '2011-01-01 07:00:00',
               '2011-01-01 08:00:00', '2011-01-01 09:00:00'],
              dtype='datetime64[ns]', freq='H')]
```
I made a temporary hack (since no testing just as yet): replace line 1472 of `axis.py`, by
```
try:
    ret = [self.converter.convert(arr, self.units, self) for arr in x]
except Exception:
    ret = self.converter.convert(x, self.units, self) 
```

**Comment by Tuan333** [comment]
I also just ran into this problem as well. Converting `datetimeindex` into `datetime` in pandas appears to be unhappy with list. I suggest a workaround somewhere along the line of replacing line 1472 of axis.py by:
```
        try:
            ret = self.converter.convert(x, self.units, self)
        except Exception as error:
            #if converter is really not happy with list, convert element individually
            ret = [self.converter.convert(arr, self.units, self) for arr in list(x)]
```

**Comment by Tuan333** [comment]
I also ran into this problem and had some digging into `pandas` and the `axis.py` file in `matplotlib`. It looks like `pandas`'s converting from `DatetimeIndex` into `Datetime` fine. The problem lies in line 1472 of `axis.py`. Given setting as above, we are passing a list of two `DatetimeIndex`, each of which is an array of datetime64 data, hence `x` in this line is a list of array. However, the converting function (called by line 1472 in `axis.py`) `DatetimeIndex.convert(values, unit, axis)` only takes in either 1 dimensional array of elements to be converted or individual elements themselves. Passing in a two dimensional list causes the problem. I suggest a workaround to this problem by replacing line 1472 in `axis.py` by something along the line:
```
        try:
            ret = self.converter.convert(x, self.units, self)
        except Exception as error:
            #if convert cannot work with multi-demensional list, convert each sub-list
            ret = [self.converter.convert(arr, self.units, self) for arr in list(x)]
```

**Comment by tacaswell** [comment]
I'm inclined to push this to the pandas side to get the converter to handle multi-dimensional data, but @Tuan333 's suggestion is reasonable as well.

Reached out to panda's gitter to see who we should talk to on their side.

**Comment by TomAugspurger** [comment]
Agreed this is a pandas issue.

https://github.com/pandas-dev/pandas/pull/16026 should fix it hopefully:

![screen shot 2017-04-16 at 9 29 28 pm](https://cloud.githubusercontent.com/assets/1312546/25077138/a69cf51a-22ec-11e7-8484-ccfb3119d34d.png)

**Comment by dstansby** [comment]
This now works fine with pandas 0.20 👍
