### ISSUE TITLE
Erros with plt.clabel()

### ISSUE THREAD

**Issue by ZenKa24** [matplotlib/matplotlib#8833]
# **When plotting a map I got this erros with plt.clabel:**
/usr/lib/pymodules/python2.7/mpl_toolkits/__init__.py:2: UserWarning: Module dap was already imported from None, but /usr/lib/python2.7/dist-packages is being added to sys.path
  __import__('pkg_resources').declare_namespace(__name__)
499 499
/usr/local/lib/python2.7/dist-packages/matplotlib-1.3.1-py2.7-linux-x86_64.egg/matplotlib/collections.py:608: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if self._edgecolors_original != 'face':
Traceback (most recent call last):
  File "curvi_2dvar_viet_max.py", line 101, in <module>
    plt.clabel(cs,fmt='%3.1f',inline=4,fontsize=10,colors='k')
  File "/usr/local/lib/python2.7/dist-packages/matplotlib-1.3.1-py2.7-linux-x86_64.egg/matplotlib/pyplot.py", line 2614, in clabel
    ret = ax.clabel(CS, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib-1.3.1-py2.7-linux-x86_64.egg/matplotlib/axes.py", line 7987, in clabel
    return CS.clabel(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib-1.3.1-py2.7-linux-x86_64.egg/matplotlib/contour.py", line 220, in clabel
    self.labels(inline, inline_spacing)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib-1.3.1-py2.7-linux-x86_64.egg/matplotlib/contour.py", line 668, in labels
    inline_spacing)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib-1.3.1-py2.7-linux-x86_64.egg/matplotlib/contour.py", line 483, in calc_label_rot_and_inline
    nlc.append(np.r_[lc[:I[0] + 1], xy1])
TypeError: slice indices must be integers or None or have an __index__ method

# **So I can not plot label on contour. Please correct it to me!

# **Here is my code:**

```python
from netCDF4 import Dataset, num2date
#from netCDF4 import MFDataset
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.basemap import Basemap
from pyproj import Proj as proj
import scipy as sp
import pylab as pl
from scipy import ndimage
#import multiprocessing

#nproc=multiprocessing.cpu_count()-1 #number of parallel threads

#nc = Dataset('/disk1/ROMS_VIETNAM/run2d/ocean_his.nc')
nc = Dataset('ocean_his.nc')
# grd = nc
#grd = Dataset('/disk1/ROMS_VIETNAM/Apps/east_sea_curv/east_sea_curv_v0.1_grd.nc')
grd = Dataset('east_sea_grd-smooth.nc')
ocean_time=nc.variables['ocean_time'][:]
#h=nc.variables['h'][:,:]
#x=grd.variables['x_rho'][:,:]
#y=grd.variables['y_rho'][:,:]
lon=grd.variables['lon_rho'][:,:]
lat=grd.variables['lat_rho'][:,:]
mask_rho = nc.variables['mask_rho'][:,:]

#name = 'current_'
name = 'surge_'
variable = 'zeta'


#Get stuff needed for vertical interpolation:
H = nc.variables['h'][:,:]
tt2 = len(ocean_time)
tt1 = 0
dt = 1

#p=proj('+proj=stere +lat_0=90 +lon_0=24 +lat_ts=60 +units=m +R=6.371e+06 +no_defs')

#lonx, laty = p(x,y,inverse=True)

yy, xx = H.shape

timee = nc.variables['ocean_time']
time2 = num2date(timee[:],timee.units)

print xx, yy

xslide = 1
yslide = 1

data = nc.variables[variable][:,:,:]
ubar = nc.variables['ubar']
vbar = nc.variables['vbar']


if True:
    #print 't: '+str(t)+', '+time2[t].strftime("%d-%m-%Y %H:%M")
    #datat = np.ma.masked_where(mask_rho==0,np.where(data[t,:,:].mask,0,data[t,:,:]))
    datat = np.ma.masked_where(mask_rho==0,data[:,:,:].max(axis=0))
    mask= (mask_rho==0)[1::,1::]
    #ubart = np.ma.masked_where(mask,ubar[t,1:,:])
    #vbart = np.ma.masked_where(mask,vbar[t,:,1:])

    #Uxi, Veta = ubart, vbart
    #U_east, V_north = rotate_wind(Uxi, Veta, -northdir)

    plt.close('all')


    fig = plt.figure(figsize=(12,10))
    m = Basemap(projection='stere',lon_0=105,lat_0=20,lat_ts=20,
                llcrnrlat=7,urcrnrlat=11,
                llcrnrlon=105,urcrnrlon=109,
                rsphere=6.371e+06,resolution='i')

    #U_grid,V_grid=m.rotate_vector(U_east,V_north,lon[1::,1::],lat[1::,1::])
    

#         m.etopo()
    m.drawcoastlines(linewidth=0.5)
    m.drawcountries()
    m.fillcontinents(color='0.6')
    # draw parallels.
    parallels = np.arange(0.,90,0.5)
    m.drawparallels(parallels,labels=[1,0,0,0],fontsize=10)
    # draw meridians
    meridians = np.arange(0.,360.,0.5)
    m.drawmeridians(meridians,labels=[0,0,0,1],fontsize=10)
    x2, y2 = m(lon,lat)
    #cs = m.contourf(x2,y2,var3d,clevs,cmap=plt.cm.cool,extend='max')
    #cs = m.pcolormesh(x2,y2,datat,cmap=plt.cm.Spectral_r,vmin=-0.5,vmax=2)

    #levels = np.arange(-1, 2.5, 0.5)
    #cf = m.contourf(x2,y2,datat,levels,origin='lower',linewidths=2,extent=(-3,3,-2,2))
    cf = m.contourf(x2,y2,datat, levels = np.arange(0., 2., 0.2), extend='both')
    #cf = m.contourf(x2,y2,datat, 10)
    cs = plt.contour(x2,y2,datat,levels = np.arange(0., 2., 0.2), colors='k' )
    #cs = plt.contour(x2,y2,datat,10, colors='k' )
    #levels = np.arange(-0.5, 2.5, 0.25)
    plt.clabel(cs,fmt='%3.1f',inline=4,fontsize=10,colors='k')
    #cf = m.contour(x2,y2,datat, 10)
    

#plot vector current   
    #n=15
    #mask = ndimage.binary_dilation(mask)
    #U_grid[mask] = sp.nan
    #V_grid[mask] = sp.nan
    #speed = sp.sqrt(U_grid**2 + V_grid**2)
    #speed[mask] = sp.nan
    #cf = m.contourf(x2[1::,1::],y2[1::,1::],speed,levels = np.arange(0,1.5, 0.1), extend='both')
    #q = m.quiver(x2[1::n,1::n],y2[1::n,1::n],U_grid[::n,::n]/speed[::n,::n],V_grid[::n,::n]/speed[::n,::n])
    
    

    #cbar = m.colorbar(cs,location='right',pad="10%")
    cbar = m.colorbar(cf,location='right',pad="10%")
    #cbar = m.colorbar(cf,location='right', extend='both')
    #cbar.set_label('[m/s]')
    cbar.set_label('[m]')
    fig.suptitle('Maximum Storm Surge', fontsize=18, fontweight='bold')
    plt.savefig('SaiGon.png',dpi=100,facecolor='white')


# print 'If multiproc, will be using '+str(nproc)+' of '+str(multiprocessing.cpu_count())+' processors...'  
# pool = multiprocessing.Pool(processes=nproc)
# pool.map(do_plotting,range(tt1,tt2,dt))
# map(do_plotting,range(tt1,tt2,dt))

plt.show()
print 'done'
```

**Matplotlib version**

  * Operating System:
  * Matplotlib Version: 1.3.1
  * Python Version: 2.7
  * Jupyter Version (if applicable):
  * Other Libraries:

**Comment by dstansby** [comment]
It looks like you're using an old version of Matplotlib; the most recent version is `2.0.2`. Please could you install Matplotlib 2.0.2 and let us know if there is still a problem?

**Comment by ZenKa24** [comment]
@dstansby :+1: I upgraded Matplotlib 2.0.2 successfull and fixed error. Thanks for you helping! :)
