### ISSUE TITLE
building conda-package on appveyor is broken

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#8849]
```
where python
C:\Miniconda-x64\python.exe
C:\Python27\python.exe
%CMD_IN_ENV% conda config --get channels
Configuring Windows SDK "v7.0" for Python 2 on a 64 bit architecture
Setting SDK environment relative to C:\Program Files\Microsoft SDKs\Windows\v7.0.
Targeting Windows Server 2008 x64 RELEASE
Executing: conda config --get channels
--add channels 'conda-forge'   # lowest priority
--add channels 'defaults'   # highest priority
%CMD_IN_ENV% conda build -q .\ci\conda_recipe
Configuring Windows SDK "v7.0" for Python 2 on a 64 bit architecture
Setting SDK environment relative to C:\Program Files\Microsoft SDKs\Windows\v7.0.
Targeting Windows Server 2008 x64 RELEASE
Executing: conda build -q .\ci\conda_recipe
Leaving build/test directories:
  Work:	 ..\..\Miniconda-x64\conda-bld\work 
  Test:	 ..\..\Miniconda-x64\conda-bld\test_tmp 
Leaving build/test environments:
  Test:	source activate  ..\..\Miniconda-x64\conda-bld\_test_env 
  Build:	source activate  ..\..\Miniconda-x64\conda-bld\_h_env 
Traceback (most recent call last):
  File "C:\Miniconda-x64\Scripts\conda-build-script.py", line 5, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "C:\Miniconda-x64\lib\site-packages\conda_build\cli\main_build.py", line 340, in main
    execute(sys.argv[1:])
  File "C:\Miniconda-x64\lib\site-packages\conda_build\cli\main_build.py", line 331, in execute
    noverify=args.no_verify)
  File "C:\Miniconda-x64\lib\site-packages\conda_build\api.py", line 183, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "C:\Miniconda-x64\lib\site-packages\conda_build\build.py", line 1615, in build_tree
    built_packages=built_packages,
  File "C:\Miniconda-x64\lib\site-packages\conda_build\build.py", line 928, in build
    channel_urls=tuple(m.config.channel_urls))
  File "C:\Miniconda-x64\lib\site-packages\conda_build\environ.py", line 701, in get_install_actions
    raise DependencyNeedsBuildingError(exc, subdir=subdir)
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform win-64: ['python', 'numpy']
Command exited with code 1
python tools/visualize_tests.py --no-browser
Traceback (most recent call last):
  File "tools/visualize_tests.py", line 137, in <module>
    run(show_browser=not args.no_browser)
  File "tools/visualize_tests.py", line 54, in run
    for name in os.listdir(image_dir)
WindowsError: [Error 3] The system cannot find the path specified: 'result_images/*.*'
Command exited with code 1

```

**Comment by jjhelmus** [comment]
I believe this is caused by conda/conda-build#2168.  In conda-build 3.x the `CONDA_PY=27` environmental variable is causing conda build to search for Python=27 rather than Python 2.7.  If this is true I expect a bug fix for conda-build will be out soon as this will effect a number of projects.

**Comment by msarahan** [comment]
Yes, @jjhelmus is correct, and I'll get a bug fix out soon.

**Comment by msarahan** [comment]
Fixed by https://github.com/conda/conda-build/pull/2176

**Comment by tacaswell** [comment]
Appveyor is running 2.7 again.
