### ISSUE TITLE
No backend in Docker?

### ISSUE THREAD

**Issue by olalonde** [matplotlib/matplotlib#8929]
I am using matplotlib to save a graph in a Docker container:

```python
    plt.savefig(graph_path)
```

I am however getting the following error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/tkinter/__init__.py", line 36, in <module>
    import _tkinter
ImportError: No module named '_tkinter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./benchmark/benchmark", line 12, in <module>
    import matplotlib.pyplot as plt
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/backends/backend_tkagg.py", line 6, in <module>
    from six.moves import tkinter as Tk
  File "/usr/local/lib/python3.5/dist-packages/six.py", line 92, in __get__
    result = self._resolve()
  File "/usr/local/lib/python3.5/dist-packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/usr/local/lib/python3.5/dist-packages/six.py", line 82, in _import_module
    __import__(name)
  File "/usr/lib/python3.5/tkinter/__init__.py", line 38, in <module>
    raise ImportError(str(msg) + ', please install the python3-tk package')
ImportError: No module named '_tkinter', please install the python3-tk package
make: *** [benchmark] Error 1
```

I would like to avoid installing a large GUI package since all I need is to save the plot to a file. Is there any way to achieve this?

**Comment by efiring** [comment]
Start your script with
```python
import matplotlib
matplotlib.use('agg')
```
or use a matplotlibrc file with
```
backend : agg
```
so that when you import pyplot it will not pull in a GUI.
I'm closing this, since I think the suggestions above will solve your problem, and this type of question is better suited to the mailing list, matplotlib-users@python.org.

**Comment by olalonde** [comment]
Thanks. Adding this to my Dockerfile solved the issue:

```Dockerfile
# matplotlib config (used by benchmark)
RUN mkdir -p /root/.config/matplotlib
RUN echo "backend : Agg" > /root/.config/matplotlib/matplotlibrc
```

**Comment by jtlz2** [comment]
NB The `matplotlib.use('agg')` line did not work, but the matplotlibrc route did. Thanks!

**Comment by tacaswell** [comment]
@jtlz2 You must run `matplotlib.use` before `matplotlib.pyplot` is imported anywhere.

**Comment by awa5114** [comment]
What if we actually want to use `TkAgg` or some other GUI backend along with Docker? I have been scouring the internet for several days and asking questions on multiple forums with no response as of yet. Could anyone please help?
