### ISSUE TITLE
Tensorflow installation

### ISSUE THREAD

**Issue by grvjn06** [matplotlib/matplotlib#9098]
### Bug report

Using TensorFlow backend.
Traceback (most recent call last):

  File "<ipython-input-1-c74e2bd4ca71>", line 1, in <module>
    import keras

  File "/Applications/anaconda/lib/python3.6/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils

  File "/Applications/anaconda/lib/python3.6/site-packages/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils

  File "/Applications/anaconda/lib/python3.6/site-packages/keras/utils/conv_utils.py", line 3, in <module>
    from .. import backend as K

  File "/Applications/anaconda/lib/python3.6/site-packages/keras/backend/__init__.py", line 83, in <module>
    from .tensorflow_backend import *

  File "/Applications/anaconda/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 1, in <module>
    import tensorflow as tf

ModuleNotFoundError: No module named 'tensorflow'
**Bug summary**

**Code for reproduction**

```python
# Paste your code here
#
#
```
import keras
**Actual outcome**

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

**Matplotlib version**

  * Operating System:
  * Matplotlib Version: 
  * Python Version:Python 3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 13:14:59) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
  * Jupyter Version (if applicable):
  * Other Libraries:

**Comment by grvjn06** [comment]
error in importing keras with theano #3794
Solved using this

**Comment by dstansby** [comment]
This is the issue tracker for Matplotlib; it looks like the issue tracker for keras is here: https://github.com/fchollet/keras/issues
