### ISSUE TITLE
matplotlib gets installed (according to pip), but pip cannot find it, nor can I import it

### ISSUE THREAD

**Issue by ptadas** [matplotlib/matplotlib#9119]
When installing matplotlib on linux (Amazon EC2 instance) python 3.4 I don't get any errors, but also don't see and cannot import matplotlib

```
(venv)[ec2-user@ip-xx ~]$ pip install matplotlib
Collecting matplotlib
  Downloading matplotlib-2.0.2-cp34-cp34m-manylinux1_x86_64.whl (14.6MB)
    100% |████████████████████████████████| 14.6MB 90kB/s 
Requirement already satisfied: cycler>=0.10 in /home/ec2-user/venv/lib/python3.4/site-packages (from matplotlib)
Requirement already satisfied: six>=1.10 in /home/ec2-user/venv/lib/python3.4/site-packages (from matplotlib)
Requirement already satisfied: pytz in /home/ec2-user/venv/lib/python3.4/site-packages (from matplotlib)
Requirement already satisfied: pyparsing!=2.0.0,!=2.0.4,!=2.1.2,!=2.1.6,>=1.5.6 in /home/ec2-user/venv/lib/python3.4/site-packages (from matplotlib)
Requirement already satisfied: python-dateutil in /home/ec2-user/venv/lib/python3.4/site-packages (from matplotlib)
Requirement already satisfied: numpy>=1.7.1 in /home/ec2-user/venv/lib64/python3.4/site-packages (from matplotlib)
Installing collected packages: matplotlib
Successfully installed matplotlib-2.0.2
(venv)[ec2-user@ip-xx ~]$ pip show matplotlib
(venv)[ec2-user@ip-xx ~]$ 
```

now if I try to import matplotlib I i get ImportError:

```
IPython 4.2.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import matplotlib.pyplot as plt
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-eff513f636fd> in <module>()
----> 1 import matplotlib.pyplot as plt

ImportError: No module named 'matplotlib'

```

**Comment by matthew-brett** [comment]
One explanation could be that your `pip` command is thinking of a different Python to your `ipython` command.  What do you get for:

```
head -1 $(which pip)
head -1 $(which ipython)
```
?

**Comment by ptadas** [comment]
it seems to be the same one:

```
[ec2-user@ip-xx ~]$ source venv/bin/activate
(venv)[ec2-user@ip-xx ~]$ head -1 $(which pip)
#!/home/ec2-user/venv/bin/python34
(venv)[ec2-user@ip-xx ~]$ head -1 $(which ipython)
#!/home/ec2-user/venv/bin/python34
(venv)[ec2-user@ip-xx ~]$ 
```

**Comment by matthew-brett** [comment]
What do you get for `python -c "import matplotlib"`?

**Comment by ptadas** [comment]
```
[ec2-user@ip-10-0-1-185 ~]$ source venv/bin/activate
(venv)[ec2-user@ip-10-0-1-185 ~]$ python -c "import matplotlib"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'matplotlib'
(venv)[ec2-user@ip-10-0-1-185 ~]$ 
```

**Comment by matthew-brett** [comment]
How odd.  How about reinstalling matplotlib?:

```
source venv/bin/activate
pip install --ignore-installed matplotlib
python -c "import matplotlib"
```

**Comment by ptadas** [comment]
unfortunately, it did not help as well. I think I will just try to setup a new Amazon Instance, maybe some of the packages on the current one are corrupted.
Thanks for your help though.

```
(venv)[ec2-user@ip-10-0-1-185 ~]$ pip install --ignore-installed matplotlib
Collecting matplotlib
  Using cached matplotlib-2.0.2-cp34-cp34m-manylinux1_x86_64.whl
Collecting six>=1.10 (from matplotlib)
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting pyparsing!=2.0.0,!=2.0.4,!=2.1.2,!=2.1.6,>=1.5.6 (from matplotlib)
  Downloading pyparsing-2.2.0-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 4.6MB/s 
Collecting pytz (from matplotlib)
  Downloading pytz-2017.2-py2.py3-none-any.whl (484kB)
    100% |████████████████████████████████| 491kB 2.4MB/s 
Collecting cycler>=0.10 (from matplotlib)
  Downloading cycler-0.10.0-py2.py3-none-any.whl
Collecting numpy>=1.7.1 (from matplotlib)
  Downloading numpy-1.13.1-cp34-cp34m-manylinux1_x86_64.whl (16.9MB)
    100% |████████████████████████████████| 16.9MB 78kB/s 
Collecting python-dateutil (from matplotlib)
  Downloading python_dateutil-2.6.1-py2.py3-none-any.whl (194kB)
    100% |████████████████████████████████| 194kB 6.2MB/s 
Installing collected packages: six, pyparsing, pytz, cycler, numpy, python-dateutil, matplotlib
Successfully installed cycler-0.10.0 matplotlib-2.0.2 numpy-1.13.1 pyparsing-2.2.0 python-dateutil-2.6.1 pytz-2017.2 six-1.10.0
(venv)[ec2-user@ip-10-0-1-185 ~]$ pip show matplotlib
(venv)[ec2-user@ip-10-0-1-185 ~]$ python -c "import matplotlib"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'matplotlib'
(venv)[ec2-user@ip-10-0-1-185 ~]$ 
```

**Comment by matthew-brett** [comment]
Sorry not to solve it.  I don't know what the problem is, and can't immediately think of anything else to suggest...

**Comment by tacaswell** [comment]
Can you find the files installed by pip and is it in `sys.path`?  Is `sys.executable` what you expect as well?

Sometimes `hash -r` in bash will fix things.  If bash has a path to `pip`, `python`, or `ipython` cached, `which` and what actually gets run may not always match.

**Comment by ptadas** [comment]
installed python 3.5 and all seems to work now. thanks for your help.

**Comment by WeatherGod** [comment]
Glad you got it sorted out!

**Comment by domino14** [comment]
I am seeing this exact same issue, on Python 3.6. There's no newer version of Python to update to. Anyone know what could be causing this?

**Comment by jklymak** [comment]
@domino14 stackoverflow.com is a better forum for setup issues like this.  The bigger community there has a larger breadth of experience setting a larger breadth of systems.  If there is a packaging issue, bring it up with the packager.  If there is an actual matplotlib bug please do bring it up here.   Thanks!

**Comment by ugluks** [comment]
FWI and for whoever comes by here with the same problem, I figured out that my issue was mis-matching versions of python/pip (3.9) vs ipython (3.10)
```
% which python3
/Library/Frameworks/Python.framework/Versions/3.9/bin/python3
% which ipython
/usr/local/bin/ipython
```
