### ISSUE TITLE
Accidental weird error: ValueError: RGBA values should be within 0-1 range

### ISSUE THREAD

**Issue by secsilm** [matplotlib/matplotlib#9190]
### Bug report

**Bug summary**

I use matplotlib and cartopy to plot a map with animation. But the result is unstable. While Sometimes it's fine, sometimes it's broken.

**Code for reproduction**

```python
#-*-coding:utf-8-*-
from matplotlib.patches import Circle
import matplotlib.pyplot as plt
import xlrd
from matplotlib.animation import FuncAnimation
import matplotlib.ticker as mticker
import cartopy.crs as ccrs
from cartopy.mpl.gridliner import LONGITUDE_FORMATTER, LATITUDE_FORMATTER
import time

fig=plt.figure()
ax = plt.axes(projection=ccrs.PlateCarree())
ax.coastlines()
gl = ax.gridlines(crs=ccrs.PlateCarree(), draw_labels=True,
                  linewidth=2, color='gray', alpha=15, linestyle='--')
gl.xlabels_top = False
gl.ylabels_left = False
gl.xlines = False
gl.xlocator = mticker.FixedLocator([-180, -45, 0, 45, 180])
gl.xformatter = LONGITUDE_FORMATTER
gl.yformatter = LATITUDE_FORMATTER
gl.xlabel_style = {'size': 15, 'color': 'gray'}
gl.xlabel_style = {'color': 'red', 'weight': 'bold'}

start = time.time()
lats  = []
lons  = []
data=xlrd.open_workbook("D:\ChromeDownload\sd.xlsx")
table=data.sheets()[0]
ncols=table.ncols
nrows=table.nrows
for i in range(nrows):
    cir1=Circle(xy=(float(table.col(0)[i].value),float(table.col(1)[i].value)),radius=2,alpha=0.5,transform=ccrs.PlateCarree())
    lons.append(cir1)
    ax.add_artist(lons[i])


def update(framedata):
    if time.time() - start < 8:
        for i in range(nrows):
            lons[i].radius+=1
            if lons[i].radius==15:
                lons[i].radius=2
        return lons
    else:
        for i in range(nrows):
            lons[i].radius = 0
        return lons


animation = FuncAnimation(fig, update, interval=50)
plt.show()
```

This  is the file using in code: `sd.xlsx` .

[sd.xlsx](https://github.com/matplotlib/matplotlib/files/1305140/sd.xlsx)

**Actual outcome**

```
Traceback (most recent call last):
  File "C:\Users\secsi\Anaconda3\lib\site-packages\matplotlib\backends\backend_qt5agg.py", line 197, in __draw_idle_agg
    FigureCanvasAgg.draw(self)
  File "C:\Users\secsi\Anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py", line 464, in draw
    self.figure.draw(self.renderer)
  File "C:\Users\secsi\Anaconda3\lib\site-packages\matplotlib\artist.py", line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "C:\Users\secsi\Anaconda3\lib\site-packages\matplotlib\figure.py", line 1143, in draw
    renderer, self, dsu, self.suppressComposite)
  File "C:\Users\secsi\Anaconda3\lib\site-packages\matplotlib\image.py", line 139, in _draw_list_compositing_images
    a.draw(renderer)
  File "C:\Users\secsi\Anaconda3\lib\site-packages\matplotlib\artist.py", line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "C:\Users\secsi\Anaconda3\lib\site-packages\cartopy\mpl\geoaxes.py", line 356, in draw
    gl._draw_gridliner(background_patch=self.background_patch)
  File "C:\Users\secsi\Anaconda3\lib\site-packages\cartopy\mpl\gridliner.py", line 344, in _draw_gridliner
    y_lc = mcollections.LineCollection(lines, **collection_kwargs)
  File "C:\Users\secsi\Anaconda3\lib\site-packages\matplotlib\collections.py", line 1208, in __init__
    **kwargs)
  File "C:\Users\secsi\Anaconda3\lib\site-packages\matplotlib\collections.py", line 162, in __init__
    self.update(kwargs)
  File "C:\Users\secsi\Anaconda3\lib\site-packages\matplotlib\artist.py", line 885, in update
    for k, v in props.items()]
  File "C:\Users\secsi\Anaconda3\lib\site-packages\matplotlib\artist.py", line 885, in <listcomp>
    for k, v in props.items()]
  File "C:\Users\secsi\Anaconda3\lib\site-packages\matplotlib\artist.py", line 879, in _update_property
    return func(v)
  File "C:\Users\secsi\Anaconda3\lib\site-packages\matplotlib\collections.py", line 749, in set_alpha
    self._set_edgecolor(self._original_edgecolor)
  File "C:\Users\secsi\Anaconda3\lib\site-packages\matplotlib\collections.py", line 712, in _set_edgecolor
    self._edgecolors = mcolors.to_rgba_array(c, self._alpha)
  File "C:\Users\secsi\Anaconda3\lib\site-packages\matplotlib\colors.py", line 232, in to_rgba_array
    raise ValueError("RGBA values should be within 0-1 range")
ValueError: RGBA values should be within 0-1 range
```

**Expected outcome**

![Expected outcome](https://user-images.githubusercontent.com/8894643/30464033-b678f330-9a01-11e7-821b-96ecb1f4d5f1.gif)

**Matplotlib version**

  * Operating System: `Windows 10`
  * Matplotlib Version: `2.0.0`
  * Python Version: `Python 3.5.2 :: Anaconda custom (64-bit)`
  * Cartopy Version: `0.15.1`

**Comment by dopplershift** [comment]
I can't get the issue to occur here with matplotlib 2.0.2 on OS X. The problem appears to be coming from drawing CartoPy's gridlines, which aren't changing during the animation. Weird.

**Comment by secsilm** [comment]
Really weird! I'll try to open a new issue in cartopy.

**Comment by anntzer** [comment]
xref https://github.com/SciTools/cartopy/issues/932.
Closing the issue on this side, but feel free to request a reopen if it turns out it's a matplotlib bug.
