### ISSUE TITLE
ValueError: ordinal must be >= 1 by plotting the index and its SMA

### ISSUE THREAD

**Issue by thomas2004ch** [matplotlib/matplotlib#9210]
### Bug report

**Bug summary**
I don't think it's a bug.

1.
As I run the code I get the error messages shown below.

2.
If I comment the figure(1) or figure(2), I can see the plotting. 

**Code for reproduction**

```python
# Paste your code here
#
#
import pandas_datareader.data as web
import datetime
import matplotlib as mpl
mpl.use('agg')
import matplotlib.pyplot as pyplot
import talib
import numpy as np
import pandas as pd

start = datetime.datetime(2002, 1, 1)

def computeSMA(data):
    head = data[-100:].dropna()
    ## Transform column to row
    x = head.as_matrix().T[0]
    ## Get rid off the NaN
    y = x[~np.isnan(x)] 
    ## Compute SMA
    z=talib.SMA(y, timeperiod=5)
    my_sma = z[~np.isnan(z)]
    
    return my_sma
    
## S&P 500
sp500 = web.DataReader("SP500", "fred", start)
sp_sma = computeSMA(sp500)
print(len(sp500[-len(sp_sma):]))
print(len(sp_sma))

## Plot
pyplot.figure(1)
sp500[-len(sp_sma):].dropna().plot()

pyplot.figure(2)
pd.Series(sp_sma).plot(use_index=False)
```

**Actual outcome**

```
# If applicable, paste the console output here
#
#
runfile('Z:/Eigene_Dateien/Temp/Python/TestPlot.py', wdir='Z:/Eigene_Dateien/Temp/Python')
C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\__init__.py:1405: UserWarning: 
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
93
93
Traceback (most recent call last):

  File "<ipython-input-1-82edc36ab359>", line 1, in <module>
    runfile('Z:/Eigene_Dateien/Temp/Python/TestPlot.py', wdir='Z:/Eigene_Dateien/Temp/Python')

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 710, in runfile
    execfile(filename, namespace)

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "Z:/Eigene_Dateien/Temp/Python/TestPlot.py", line 41, in <module>
    pd.Series(sp_sma).plot(use_index=False)

  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\tools\plotting.py", line 3566, in __call__
    **kwds)

  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\tools\plotting.py", line 2645, in plot_series
    **kwds)

  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\tools\plotting.py", line 2441, in _plot
    plot_obj.generate()

  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\tools\plotting.py", line 1034, in generate
    self._post_plot_logic_common(ax, self.data)

  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\tools\plotting.py", line 1162, in _post_plot_logic_common
    fontsize=self.fontsize)

  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\tools\plotting.py", line 1210, in _apply_axis_properties
    labels = axis.get_majorticklabels() + axis.get_minorticklabels()

  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\axis.py", line 1191, in get_majorticklabels
    ticks = self.get_major_ticks()

  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\axis.py", line 1320, in get_major_ticks
    numticks = len(self.get_major_locator()())

  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\dates.py", line 986, in __call__
    self.refresh()

  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\dates.py", line 1006, in refresh
    dmin, dmax = self.viewlim_to_dt()

  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\dates.py", line 763, in viewlim_to_dt
    return num2date(vmin, self.tz), num2date(vmax, self.tz)

  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\dates.py", line 401, in num2date
    return _from_ordinalf(x, tz)

  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\dates.py", line 254, in _from_ordinalf
    dt = datetime.datetime.fromordinal(ix).replace(tzinfo=UTC)

ValueError: ordinal must be >= 1

<matplotlib.figure.Figure at 0xc175d68>
Traceback (most recent call last):

  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\formatters.py", line 307, in __call__
    return printer(obj)

  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\pylabtools.py", line 240, in <lambda>
    png_formatter.for_type(Figure, lambda fig: print_figure(fig, 'png', **kwargs))

  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\pylabtools.py", line 124, in print_figure
    fig.canvas.print_figure(bytes_io, **kw)

  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\backend_bases.py", line 2200, in print_figure
    **kwargs)

  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py", line 545, in print_png
    FigureCanvasAgg.draw(self)

  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py", line 464, in draw
    self.figure.draw(self.renderer)

  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\artist.py", line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)

  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\figure.py", line 1144, in draw
    renderer, self, dsu, self.suppressComposite)

  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\image.py", line 139, in _draw_list_compositing_images
    a.draw(renderer)

  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\artist.py", line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)

  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\axes\_base.py", line 2426, in draw
    mimage._draw_list_compositing_images(renderer, self, dsu)

  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\image.py", line 139, in _draw_list_compositing_images
    a.draw(renderer)

  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\artist.py", line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)

  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\axis.py", line 1136, in draw
    ticks_to_draw = self._update_ticks(renderer)

  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\axis.py", line 969, in _update_ticks
    tick_tups = [t for t in self.iter_ticks()]

  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\axis.py", line 969, in <listcomp>
    tick_tups = [t for t in self.iter_ticks()]

  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\axis.py", line 912, in iter_ticks
    majorLocs = self.major.locator()

  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\dates.py", line 986, in __call__
    self.refresh()

  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\dates.py", line 1006, in refresh
    dmin, dmax = self.viewlim_to_dt()

  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\dates.py", line 763, in viewlim_to_dt
    return num2date(vmin, self.tz), num2date(vmax, self.tz)

  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\dates.py", line 401, in num2date
    return _from_ordinalf(x, tz)

  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\dates.py", line 254, in _from_ordinalf
    dt = datetime.datetime.fromordinal(ix).replace(tzinfo=UTC)

ValueError: ordinal must be >= 1

<matplotlib.figure.Figure at 0xc18ce48>
```

**Expected outcome**

**Matplotlib version**

  * Operating System: Windows 7
  * Matplotlib Version:  2.0.2
  * Python Version: 3.6.1
  * Jupyter Version (if applicable): I don't use the Jupyter but Spyder 3.2.3
  * Other Libraries: 

I install the Anaconda 3-4.4. The matplotlib  is included.

**Comment by dstansby** [comment]
I suspect that `sp_sma` does not contain `datetime` data, but the already plotted `sp500` does. What is the result of `print(sp_sma)` and `print(sp500)`?

**Comment by thomas2004ch** [comment]
@dstansby 
You are right. The sp_sma doesn't contains datetime data. 

The print(sp_sma) is:
[93 rows x 1 columns]
[ 2396.948  2397.932  2396.254  2396.842  2397.592  2389.072  2383.328
  2381.494  2379.834  2379.384  2388.856  2398.726  2405.544  2409.322
  2411.998  2417.132  2421.932  2425.988  2429.272  2433.54   2434.286
  2432.826  2431.484  2433.688  2434.644  2434.378  2434.654  2439.468
  2438.804  2438.342  2438.75   2439.78   2436.902  2433.372  2434.388
  2431.428  2428.45   2426.438  2429.07   2422.882  2423.978  2424.782
  2424.086  2426.228  2433.844  2440.662  2447.004  2454.02   2460.136
  2465.26   2467.914  2470.068  2473.372  2474.172  2474.566  2474.478
  2474.556  2474.4    2474.348  2473.696  2474.642  2476.764  2476.478
  2475.768  2468.978  2461.876  2458.862  2456.8    2455.618  2453.978
  2450.824  2443.33   2440.91   2436.096  2437.888  2441.388  2444.562
  2443.32   2446.03   2452.566  2459.266  2461.988  2465.836  2467.338
  2465.294  2467.606  2475.332  2481.898  2488.002  2495.762  2498.914
  2500.948  2502.922]

The print(sp500) is:
DATE               
2017-05-15  2402.32
2017-05-16  2400.67
2017-05-17  2357.03
2017-05-18  2365.72
2017-05-19  2381.73
2017-05-22  2394.02
...
...
2017-09-14  2495.62
2017-09-15  2500.23
2017-09-18  2503.87
2017-09-19  2506.65
2017-09-20  2508.24

One can see the sp_sma and the sp500 are different type. I can either plot the sp_sma or the sp500, but not the both, even I plot them in separated figure.

**Comment by dstansby** [comment]
Great, glad this is fixed for you! I'm going to leave this open, since I think the error message should be clearer (I've spent a while in the past trying to work out what it means with exactly the same problem).

**Comment by dstansby** [comment]
Have opened a new issue here #9211.
