### ISSUE TITLE
backend toolbar error with wxPython 4.0.0b2

### ISSUE THREAD

**Issue by vinvega** [matplotlib/matplotlib#9250]
### Bug report

**Bug summary**

The tool bar (matplotlib.backends.backend_wx.NavigationToolbar2Wx) was broken with the latest release of wxPython 4.0.0b2, where it previously worked in wxPython 4.0.0b1

from the wxPython 4.0.0b2 change log:
•Fix parameter names in Toolbar.AddTool methods to be consistent. (#475)

keyword shortHelpString changed to shortHelp
keyword longHelpString changed to longHelp

**Code for reproduction**

```python
import matplotlib as mpl
from matplotlib.backends.backend_wx import NavigationToolbar2Wx as Toolbar
from matplotlib.backends.backend_wxagg import FigureCanvasWxAgg as Canvas
import wx

class plotClass(wx.Frame):
    def __init__(self, parent, id=wx.ID_ANY, title="", pos=wx.DefaultPosition,
                 size=wx.DefaultSize, style=wx.DEFAULT_FRAME_STYLE, log=None,dpi=None):

        wx.Frame.__init__(self, parent, id, title, pos, size, style)
        self.figure = mpl.figure.Figure(dpi=dpi, figsize=(2, 2))
        self.canvas = Canvas(self, -1, self.figure)
        self.toolbar = Toolbar(self.canvas)

def main():
    app = wx.App()
    frame = plotClass(None)
    app.MainLoop()

if __name__ == "__main__" :
    main()

```

**Actual outcome**

```
"C:\Program Files\Anaconda2\python.exe" "C:/local_files/abaqus common plugins/GIT/cppaba/plugins/CPP_AbaqusPlugins/trunk/inwork/simple_panel/gui/test3.py"
Traceback (most recent call last):
  File "C:/local_files/abaqus common plugins/GIT/cppaba/plugins/CPP_AbaqusPlugins/trunk/inwork/simple_panel/gui/test3.py", line 21, in <module>
    main()
  File "C:/local_files/abaqus common plugins/GIT/cppaba/plugins/CPP_AbaqusPlugins/trunk/inwork/simple_panel/gui/test3.py", line 17, in main
    frame = plotClass(None)
  File "C:/local_files/abaqus common plugins/GIT/cppaba/plugins/CPP_AbaqusPlugins/trunk/inwork/simple_panel/gui/test3.py", line 13, in __init__
    self.toolbar = Toolbar(self.canvas)
  File "C:\Program Files\Anaconda2\lib\site-packages\matplotlib\backends\backend_wx.py", line 1582, in __init__
    NavigationToolbar2.__init__(self, canvas)
  File "C:\Program Files\Anaconda2\lib\site-packages\matplotlib\backend_bases.py", line 2760, in __init__
    self._init_toolbar()
  File "C:\Program Files\Anaconda2\lib\site-packages\matplotlib\backends\backend_wx.py", line 1609, in _init_toolbar
    tooltip_text)
  File "C:\Program Files\Anaconda2\lib\site-packages\matplotlib\backends\wx_compat.py", line 153, in _AddTool
    kind=kind)
TypeError: ToolBar.AddTool(): arguments did not match any overloaded call:
  overload 1: argument 1 has unexpected type 'int'
  overload 2: 'shortHelpString' is not a valid keyword argument
  overload 3: 'shortHelpString' is not a valid keyword argument
```

**Expected outcome**

**Matplotlib version**

  * Operating System: windows 7 enterprise
  * Matplotlib Version: 2.0.2
  * Python Version: Python 2.7.12 (Anaconda 4.2.0 (64-bit))
  * Jupyter Version (if applicable):
  * Other Libraries: 

installed from pip

**Comment by anntzer** [comment]
Fixed by https://github.com/matplotlib/matplotlib/pull/9187 (which should be released "soon").

**Comment by Borda** [comment]
May I ask when it will be released, this issue is crucial form me while there no longer available lower versions? So, I would be interested why in pip there is no lower version of wxPython than 4.x ?

**Comment by anntzer** [comment]
2.1 has been released.
Can you describe your issue more precisely?

**Comment by Borda** [comment]
ok, upgrade to matplotlib==2.1.0 seems to help. Thanks :)
