### ISSUE TITLE
Cartopy Border Plotting Fails on 2.1 Only

### ISSUE THREAD

**Issue by jrleeman** [matplotlib/matplotlib#9443]
### Bug report

**Bug summary**

Plotting country borders with cartopy causes the following error on mpl 2.1, but runs fine on mpl 2.0.

**Code for reproduction**

```python
import cartopy.crs as ccrs
import cartopy.feature as feat
import matplotlib.pyplot as plt

# Set up the map projection and set up a cartopy feature for state borders
proj = ccrs.LambertConformal(central_longitude=-95, central_latitude=35,
                             standard_parallels=[35])
state_boundaries = feat.NaturalEarthFeature(category='cultural',
                                            name='admin_1_states_provinces_lines',
                                            scale='110m', facecolor='none')

fig = plt.figure(figsize=(20, 10))
ax = fig.add_subplot(1, 1, 1, projection=proj)
# Add some various map elements to the plot to make it recognizable
ax.add_feature(feat.LAND, zorder=-1)
ax.add_feature(feat.OCEAN, zorder=-1)
ax.add_feature(feat.LAKES, zorder=-1)
ax.coastlines(resolution='110m', zorder=2, color='black')
ax.add_feature(state_boundaries, edgecolor='black')

# Comment out this line and it runs fine!
ax.add_feature(feat.BORDERS, linewidth='2', edgecolor='black')

# Set plot bounds
ax.set_extent((-118, -73, 23, 50))

plt.show()
```

**Actual outcome**

```python
Traceback (most recent call last):
  File "/Users/johnleeman/miniconda3/envs/metpydev/lib/python3.6/site-packages/matplotlib/backends/backend_macosx.py", line 105, in _draw
    self.figure.draw(renderer)
  File "/Users/johnleeman/miniconda3/envs/metpydev/lib/python3.6/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/Users/johnleeman/miniconda3/envs/metpydev/lib/python3.6/site-packages/matplotlib/figure.py", line 1295, in draw
    renderer, self, artists, self.suppressComposite)
  File "/Users/johnleeman/miniconda3/envs/metpydev/lib/python3.6/site-packages/matplotlib/image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "/Users/johnleeman/miniconda3/envs/metpydev/lib/python3.6/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/Users/johnleeman/miniconda3/envs/metpydev/lib/python3.6/site-packages/cartopy/mpl/geoaxes.py", line 372, in draw
    inframe=inframe)
  File "/Users/johnleeman/miniconda3/envs/metpydev/lib/python3.6/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/Users/johnleeman/miniconda3/envs/metpydev/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 2399, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/Users/johnleeman/miniconda3/envs/metpydev/lib/python3.6/site-packages/matplotlib/image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "/Users/johnleeman/miniconda3/envs/metpydev/lib/python3.6/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/Users/johnleeman/miniconda3/envs/metpydev/lib/python3.6/site-packages/cartopy/mpl/feature_artist.py", line 179, in draw
    return c.draw(renderer)
  File "/Users/johnleeman/miniconda3/envs/metpydev/lib/python3.6/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/Users/johnleeman/miniconda3/envs/metpydev/lib/python3.6/site-packages/matplotlib/collections.py", line 845, in draw
    Collection.draw(self, renderer)
```

**Matplotlib version**
  * Operating system: osx
  * Matplotlib version: 2.0 vs 2.1
  * Matplotlib backend MacOSX
  * Python version: 3.6

* Installed via conda w/ conda forge

**Comment by cgohlke** [comment]
Using the TkAgg backend, I get this:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "X:\Python36\lib\tkinter\__init__.py", line 1699, in __call__
    return self.func(*args)
  File "X:\Python36\lib\tkinter\__init__.py", line 745, in callit
    func(*args)
  File "X:\Python36\lib\site-packages\matplotlib\backends\backend_tkagg.py", line 323, in idle_draw
    self.draw()
  File "X:\Python36\lib\site-packages\matplotlib\backends\backend_tkagg.py", line 304, in draw
    FigureCanvasAgg.draw(self)
  File "X:\Python36\lib\site-packages\matplotlib\backends\backend_agg.py", line 430, in draw
    self.figure.draw(self.renderer)
  File "X:\Python36\lib\site-packages\matplotlib\artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "X:\Python36\lib\site-packages\matplotlib\figure.py", line 1295, in draw
    renderer, self, artists, self.suppressComposite)
  File "X:\Python36\lib\site-packages\matplotlib\image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "X:\Python36\lib\site-packages\matplotlib\artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "X:\Python36\lib\site-packages\cartopy\mpl\geoaxes.py", line 372, in draw
    inframe=inframe)
  File "X:\Python36\lib\site-packages\matplotlib\artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "X:\Python36\lib\site-packages\matplotlib\axes\_base.py", line 2399, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "X:\Python36\lib\site-packages\matplotlib\image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "X:\Python36\lib\site-packages\matplotlib\artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "X:\Python36\lib\site-packages\cartopy\mpl\feature_artist.py", line 178, in draw
    return c.draw(renderer)
  File "X:\Python36\lib\site-packages\matplotlib\artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "X:\Python36\lib\site-packages\matplotlib\collections.py", line 845, in draw
    Collection.draw(self, renderer)
  File "X:\Python36\lib\site-packages\matplotlib\artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "X:\Python36\lib\site-packages\matplotlib\collections.py", line 321, in draw
    self._offset_position)
  File "X:\Python36\lib\site-packages\matplotlib\backends\backend_agg.py", line 120, in draw_path_collection
    return self._renderer.draw_path_collection(*kl, **kw)
TypeError: Cannot cast array data from dtype('<U1') to dtype('float64') according to the rule 'safe'
Exception in Tkinter callback
Traceback (most recent call last):
  File "X:\Python36\lib\tkinter\__init__.py", line 1699, in __call__
    return self.func(*args)
  File "X:\Python36\lib\site-packages\matplotlib\backends\backend_tkagg.py", line 233, in resize
    self.show()
  File "X:\Python36\lib\site-packages\matplotlib\backends\backend_tkagg.py", line 304, in draw
    FigureCanvasAgg.draw(self)
  File "X:\Python36\lib\site-packages\matplotlib\backends\backend_agg.py", line 430, in draw
    self.figure.draw(self.renderer)
  File "X:\Python36\lib\site-packages\matplotlib\artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "X:\Python36\lib\site-packages\matplotlib\figure.py", line 1295, in draw
    renderer, self, artists, self.suppressComposite)
  File "X:\Python36\lib\site-packages\matplotlib\image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "X:\Python36\lib\site-packages\matplotlib\artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "X:\Python36\lib\site-packages\cartopy\mpl\geoaxes.py", line 372, in draw
    inframe=inframe)
  File "X:\Python36\lib\site-packages\matplotlib\artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "X:\Python36\lib\site-packages\matplotlib\axes\_base.py", line 2399, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "X:\Python36\lib\site-packages\matplotlib\image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "X:\Python36\lib\site-packages\matplotlib\artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "X:\Python36\lib\site-packages\cartopy\mpl\feature_artist.py", line 178, in draw
    return c.draw(renderer)
  File "X:\Python36\lib\site-packages\matplotlib\artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "X:\Python36\lib\site-packages\matplotlib\collections.py", line 845, in draw
    Collection.draw(self, renderer)
  File "X:\Python36\lib\site-packages\matplotlib\artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "X:\Python36\lib\site-packages\matplotlib\collections.py", line 321, in draw
    self._offset_position)
  File "X:\Python36\lib\site-packages\matplotlib\backends\backend_agg.py", line 120, in draw_path_collection
    return self._renderer.draw_path_collection(*kl, **kw)
TypeError: Cannot cast array data from dtype('<U1') to dtype('float64') according to the rule 'safe'
```

**Comment by jrleeman** [comment]
A result of becoming more strict with line width arguments. Should be passed as integer, not string. This works:

```python
import cartopy.crs as ccrs
import cartopy.feature as feat
import matplotlib.pyplot as plt

# Set up the map projection and set up a cartopy feature for state borders
proj = ccrs.LambertConformal(central_longitude=-95, central_latitude=35,
                             standard_parallels=[35])
state_boundaries = feat.NaturalEarthFeature(category='cultural',
                                            name='admin_1_states_provinces_lines',
                                            scale='110m', facecolor='none')

fig = plt.figure(figsize=(20, 10))
ax = fig.add_subplot(1, 1, 1, projection=proj)
# Add some various map elements to the plot to make it recognizable
ax.add_feature(feat.LAND, zorder=-1)
ax.add_feature(feat.OCEAN, zorder=-1)
ax.add_feature(feat.LAKES, zorder=-1)
ax.coastlines(resolution='110m', zorder=2, color='black')
ax.add_feature(state_boundaries, edgecolor='black')

# Comment out this line and it runs fine!
ax.add_feature(feat.BORDERS, linewidth=2, edgecolor='black')

# Set plot bounds
ax.set_extent((-118, -73, 23, 50))

plt.show()
```

**Comment by WeatherGod** [comment]
so.... why weren't we raising an error?
