### ISSUE TITLE
semilogx() raises incorrect ValueError with AGG backend

### ISSUE THREAD

**Issue by danieldwright** [matplotlib/matplotlib#9800]
### Bug report

**Bug summary**

An incorrect exception is raised when trying to plot positive data using `semilogx()`:
```ValueError: Data has no positive values, and therefore can not be log-scaled.```
If I use the 'Qt5Agg' backend (Linux, Python 3.6.2 via pyenv) the `semilogx()` command succeeds.

This most likely has the same root cause as #5541.

**Code for reproduction**

```python
from __future__ import print_function
import matplotlib
matplotlib.use('AGG')
import matplotlib.pyplot as plt

if __name__ == '__main__':
    x = [1e3, 1e4]
    y = [1, 2]
    print(matplotlib.__version__)
    fig = plt.figure()
    ax = fig.add_subplot(1,1,1)
    # This fails.
    plt.semilogx(x, y)
    # Workaround: Calling plot and then setting the scale to log works.
    # plt.plot(x, y)
    # ax.set_xscale('log')
    plt.savefig("logx.png")
```

**Actual outcome**

Console output:
```
Traceback (most recent call last):
  File "foo.py", line 11, in <module>
    plt.semilogx(x, y)
  File "/home/danielw/.pyenv/versions/3.6.2/lib/python3.6/site-packages/matplotlib/pyplot.py", line 3388, in semilogx
    ret = ax.semilogx(*args, **kwargs)
  File "/home/danielw/.pyenv/versions/3.6.2/lib/python3.6/site-packages/matplotlib/axes/_axes.py", line 1624, in semilogx
    self.set_xscale('log', **d)
  File "/home/danielw/.pyenv/versions/3.6.2/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 2982, in set_xscale
    ax.xaxis._set_scale(value, **kwargs)
  File "/home/danielw/.pyenv/versions/3.6.2/lib/python3.6/site-packages/matplotlib/axis.py", line 692, in _set_scale
    self._scale.set_default_locators_and_formatters(self)
  File "/home/danielw/.pyenv/versions/3.6.2/lib/python3.6/site-packages/matplotlib/scale.py", line 249, in set_default_locators_and_formatters
    axis.set_major_locator(LogLocator(self.base))
  File "/home/danielw/.pyenv/versions/3.6.2/lib/python3.6/site-packages/matplotlib/axis.py", line 1542, in set_major_locator
    self.stale = True
  File "/home/danielw/.pyenv/versions/3.6.2/lib/python3.6/site-packages/matplotlib/artist.py", line 241, in stale
    self.stale_callback(self, val)
  File "/home/danielw/.pyenv/versions/3.6.2/lib/python3.6/site-packages/matplotlib/artist.py", line 68, in _stale_axes_callback
    self.axes.stale = val
  File "/home/danielw/.pyenv/versions/3.6.2/lib/python3.6/site-packages/matplotlib/artist.py", line 241, in stale
    self.stale_callback(self, val)
  File "/home/danielw/.pyenv/versions/3.6.2/lib/python3.6/site-packages/matplotlib/figure.py", line 56, in _stale_figure_callback
    self.figure.stale = val
  File "/home/danielw/.pyenv/versions/3.6.2/lib/python3.6/site-packages/matplotlib/artist.py", line 241, in stale
    self.stale_callback(self, val)
  File "/home/danielw/.pyenv/versions/3.6.2/lib/python3.6/site-packages/matplotlib/pyplot.py", line 588, in _auto_draw_if_interactive
    fig.canvas.draw_idle()
  File "/home/danielw/.pyenv/versions/3.6.2/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 2052, in draw_idle
    self.draw(*args, **kwargs)
  File "/home/danielw/.pyenv/versions/3.6.2/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 430, in draw
    self.figure.draw(self.renderer)
  File "/home/danielw/.pyenv/versions/3.6.2/lib/python3.6/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/danielw/.pyenv/versions/3.6.2/lib/python3.6/site-packages/matplotlib/figure.py", line 1294, in draw
    renderer, self, artists, self.suppressComposite)
  File "/home/danielw/.pyenv/versions/3.6.2/lib/python3.6/site-packages/matplotlib/image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/danielw/.pyenv/versions/3.6.2/lib/python3.6/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/danielw/.pyenv/versions/3.6.2/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 2401, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/home/danielw/.pyenv/versions/3.6.2/lib/python3.6/site-packages/matplotlib/image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/danielw/.pyenv/versions/3.6.2/lib/python3.6/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/danielw/.pyenv/versions/3.6.2/lib/python3.6/site-packages/matplotlib/axis.py", line 1113, in draw
    ticks_to_draw = self._update_ticks(renderer)
  File "/home/danielw/.pyenv/versions/3.6.2/lib/python3.6/site-packages/matplotlib/axis.py", line 954, in _update_ticks
    tick_tups = list(self.iter_ticks())
  File "/home/danielw/.pyenv/versions/3.6.2/lib/python3.6/site-packages/matplotlib/axis.py", line 897, in iter_ticks
    majorLocs = self.major.locator()
  File "/home/danielw/.pyenv/versions/3.6.2/lib/python3.6/site-packages/matplotlib/ticker.py", line 2101, in __call__
    return self.tick_values(vmin, vmax)
  File "/home/danielw/.pyenv/versions/3.6.2/lib/python3.6/site-packages/matplotlib/ticker.py", line 2127, in tick_values
    "Data has no positive values, and therefore can not be "
ValueError: Data has no positive values, and therefore can not be log-scaled.
```

**Expected outcome**
Plot with logarithmic x-axis scale.

**Matplotlib version**
 (also reproduced on Win64 with Python2.7, matplotlib 2.1)
  * Operating system: Linux 64-bit
  * Matplotlib version: '2.1.0rc1'
  * Matplotlib backend (`print(matplotlib.get_backend())`): AGG
  * Python version: 3.6.2 (in pyenv)
  * Jupyter version (if applicable): - 
  * Other libraries: numpy 1.13.3

Matplotlib installed via pip on both Linux (pyenv) and Windows (standard Python installer).

**Comment by dstansby** [comment]
This is working for me fine on the latest master branch and `2.1` - can you update to full `2.1` (not `2.1.0rc1`) and try again @danieldwright ?

**Comment by danieldwright** [comment]
Hi @dstansby, I still see the same behaviour on Linux64 with Python 3.6.2 (from pyenv) with matplotlib 2.1.0 (via pyenv's pip). But indeed, I can't provoke the behaviour with the above minimal script on Windows & Python 2.7 with matplotlib 2.1.0 - there I only triggered it with my original code before reducing it to the script above.

**Comment by dstansby** [comment]
That's odd, I can't seem to reproduce on `2.1` from pypi. What is the result of running this on the system where you have the bug
```python
import matplotlib
print(matplotlib.__version__)
```
?

**Comment by danieldwright** [comment]
I still see the problem. I just installed a new Python 3.6.3 installation in pyenv and installed matplotlib from pypi. Here's the output of pip list:
```cycler (0.10.0)
matplotlib (2.1.0)
numpy (1.13.3)
pip (9.0.1)
pyparsing (2.2.0)
python-dateutil (2.6.1)
pytz (2017.3)
setuptools (28.8.0)
six (1.11.0)
```
If I run the script above (I just updated it to print the matplotlib version) as:
```
python -sE logx.py
```
Version "2.1.0" is printed before raising the exception as above.

If I additionally install `PyQt5` from pypi and replace the backend (`matplotlib.use('Qt5Agg')`) the plot is saved as expected.

It's still an issue with 2.0.{0,1,2}, but works with 1.5.3 installed from pypi via
```
pip install matplotlib==1.5.3
```
I didn't try again on Windows - yesterday I could not reproduce the problem there with matplotlib 2.1.0.

**Comment by i3v** [comment]
I just ran into something similar after switching to backend to `Agg` in an existing script. There was `plt.ion()` a few lines below, but I've not mentioned it. And... it worked! At first....
The only strange thing was that I've started to see `Backend agg is non-interactive backend. Turning interactive mode off.` messages. But who cares if on the whole it's working OK :-) .

Later, at some point, I ran into this issue. The stack trace is quite similar (see below). I was puzzled with "how does it manage to get through [this](https://github.com/matplotlib/matplotlib/blob/0aad6fd3c405a9def9487a124943a683fd90fb8b/lib/matplotlib/pyplot.py#L591) `matplotlib.is_interactive()` check?".

I've managed to reduce my code to this:
```
import matplotlib
matplotlib.use('Agg')
from matplotlib import pyplot as plt

# The following line doesn't make sense in normal life. I only use it to reproduce the error.
plt.ion()

fig = plt.figure('title')
ax = fig.add_subplot(111)
ax.set_yscale("log", nonposy='clip')  # error here

# Core below is "just for completeness".
# It is not executed when the bug happens.
x = [1e3, 1e4]
y = [1, 2]
plt.plot(x, y)
```
1. Normal `run` fails.
2. Normal `debug run` fails.
3. If I add a breakpoint at `ax.set_yscale(...)` line and stop there and continue - no error happens. `Backend agg is non-interactive backend. Turning interactive mode off` happens immediately when it stops on a breakpoint. As soon as it happens, the issue with log scale is gone, because `matplotlib.is_interactive()` would return `False` and those code would never be reached. This "unstable" behavior could be quite misleading.

I'm unable to reproduce the issue with the code from @danieldwright 's message. And I'm not sure how could it pass through [that](https://github.com/matplotlib/matplotlib/blob/0aad6fd3c405a9def9487a124943a683fd90fb8b/lib/matplotlib/pyplot.py#L591) `matplotlib.is_interactive()` check... 

Maybe it is worth to add some check "whether it is actually possible to set interactive to ON" in `plt.ion()` itself?

I'm not sure what exactly triggers that automatic-interactive-mode-switch-off (and why it's happening asynchronously), probably some IPython black magic. 


My stack trace:
```
C:\Users\ivarfolomeev\Anaconda3\envs\logticks_bug\python.exe W:/tests/Python/bugReports/pyplot_logticks/test_ticks3.py
Traceback (most recent call last):
  File "W:/tests/Python/bugReports/pyplot_logticks/test_ticks3.py", line 12, in <module>
    ax1.set_yscale("log", nonposy='clip')  # error here
  File "C:\Users\ivarfolomeev\Anaconda3\envs\logticks_bug\lib\site-packages\matplotlib\axes\_base.py", line 3346, in set_yscale
    ax.yaxis._set_scale(value, **kwargs)
  File "C:\Users\ivarfolomeev\Anaconda3\envs\logticks_bug\lib\site-packages\matplotlib\axis.py", line 712, in _set_scale
    self._scale.set_default_locators_and_formatters(self)
  File "C:\Users\ivarfolomeev\Anaconda3\envs\logticks_bug\lib\site-packages\matplotlib\scale.py", line 264, in set_default_locators_and_formatters
    axis.set_major_locator(LogLocator(self.base))
  File "C:\Users\ivarfolomeev\Anaconda3\envs\logticks_bug\lib\site-packages\matplotlib\axis.py", line 1562, in set_major_locator
    self.stale = True
  File "C:\Users\ivarfolomeev\Anaconda3\envs\logticks_bug\lib\site-packages\matplotlib\artist.py", line 241, in stale
    self.stale_callback(self, val)
  File "C:\Users\ivarfolomeev\Anaconda3\envs\logticks_bug\lib\site-packages\matplotlib\artist.py", line 68, in _stale_axes_callback
    self.axes.stale = val
  File "C:\Users\ivarfolomeev\Anaconda3\envs\logticks_bug\lib\site-packages\matplotlib\artist.py", line 241, in stale
    self.stale_callback(self, val)
  File "C:\Users\ivarfolomeev\Anaconda3\envs\logticks_bug\lib\site-packages\matplotlib\figure.py", line 56, in _stale_figure_callback
    self.figure.stale = val
  File "C:\Users\ivarfolomeev\Anaconda3\envs\logticks_bug\lib\site-packages\matplotlib\artist.py", line 241, in stale
    self.stale_callback(self, val)
  File "C:\Users\ivarfolomeev\Anaconda3\envs\logticks_bug\lib\site-packages\matplotlib\pyplot.py", line 583, in _auto_draw_if_interactive
    fig.canvas.draw_idle()
  File "C:\Users\ivarfolomeev\Anaconda3\envs\logticks_bug\lib\site-packages\matplotlib\backend_bases.py", line 2061, in draw_idle
    self.draw(*args, **kwargs)
  File "C:\Users\ivarfolomeev\Anaconda3\envs\logticks_bug\lib\site-packages\matplotlib\backends\backend_agg.py", line 430, in draw
    self.figure.draw(self.renderer)
  File "C:\Users\ivarfolomeev\Anaconda3\envs\logticks_bug\lib\site-packages\matplotlib\artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\Users\ivarfolomeev\Anaconda3\envs\logticks_bug\lib\site-packages\matplotlib\figure.py", line 1299, in draw
    renderer, self, artists, self.suppressComposite)
  File "C:\Users\ivarfolomeev\Anaconda3\envs\logticks_bug\lib\site-packages\matplotlib\image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "C:\Users\ivarfolomeev\Anaconda3\envs\logticks_bug\lib\site-packages\matplotlib\artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\Users\ivarfolomeev\Anaconda3\envs\logticks_bug\lib\site-packages\matplotlib\axes\_base.py", line 2437, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "C:\Users\ivarfolomeev\Anaconda3\envs\logticks_bug\lib\site-packages\matplotlib\image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "C:\Users\ivarfolomeev\Anaconda3\envs\logticks_bug\lib\site-packages\matplotlib\artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\Users\ivarfolomeev\Anaconda3\envs\logticks_bug\lib\site-packages\matplotlib\axis.py", line 1133, in draw
    ticks_to_draw = self._update_ticks(renderer)
  File "C:\Users\ivarfolomeev\Anaconda3\envs\logticks_bug\lib\site-packages\matplotlib\axis.py", line 974, in _update_ticks
    tick_tups = list(self.iter_ticks())
  File "C:\Users\ivarfolomeev\Anaconda3\envs\logticks_bug\lib\site-packages\matplotlib\axis.py", line 917, in iter_ticks
    majorLocs = self.major.locator()
  File "C:\Users\ivarfolomeev\Anaconda3\envs\logticks_bug\lib\site-packages\matplotlib\ticker.py", line 2097, in __call__
    return self.tick_values(vmin, vmax)
  File "C:\Users\ivarfolomeev\Anaconda3\envs\logticks_bug\lib\site-packages\matplotlib\ticker.py", line 2123, in tick_values
    "Data has no positive values, and therefore can not be "
ValueError: Data has no positive values, and therefore can not be log-scaled.
```

I've only tested this on Windows 10, python 3.6.4, matplotlib 2.1.0 and matplotlib 2.1.2.

**Comment by dstansby** [comment]
Since this is quite old and I can't reproduce it, I'm going to close. Feel free to comment if it's still an issue and I can reopen!

**Comment by Recognition2** [comment]
I've got an MVP:
```python
def mvp(interactive: bool):
    ts = [11, 111, 1111]
    vs = [10, 100, 1000]
    print(mpl.get_backend())
    if interactive:
        plt.ion()
    print(mpl.get_backend())
    plt.loglog(ts, vs)
    plt.show()
```
This function will crash if called with `True` and succeed if called with `False` inside PyCharm.
PyCharm venv is python 3.7.3 with numpy and matplotlib, created today.
In both cases the backend used is `module://backend_interagg`.
The output of calling this function is:
```
module://backend_interagg
module://backend_interagg
Traceback (most recent call last):
  File "/path/to/my/pycharm/project/FakeSim/main.py", line 151, in <module>
    mvp()
  File "/path/to/my/pycharm/project/FakeSim/main.py", line 107, in mvp
    plt.loglog(ts, vs)
  File "/path/to/my/pycharm/project/FakeSim/venv/lib/python3.7/site-packages/matplotlib/pyplot.py", line 2697, in loglog
    return gca().loglog(*args, **kwargs)
  File "/path/to/my/pycharm/project/FakeSim/venv/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 1798, in loglog
    self.set_xscale('log', **dx)
  File "/path/to/my/pycharm/project/FakeSim/venv/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 3322, in set_xscale
    ax.xaxis._set_scale(value, **kwargs)
  File "/path/to/my/pycharm/project/FakeSim/venv/lib/python3.7/site-packages/matplotlib/axis.py", line 800, in _set_scale
    self._scale.set_default_locators_and_formatters(self)
  File "/path/to/my/pycharm/project/FakeSim/venv/lib/python3.7/site-packages/matplotlib/scale.py", line 406, in set_default_locators_and_formatters
    axis.set_major_locator(LogLocator(self.base))
  File "/path/to/my/pycharm/project/FakeSim/venv/lib/python3.7/site-packages/matplotlib/axis.py", line 1652, in set_major_locator
    self.stale = True
  File "/path/to/my/pycharm/project/FakeSim/venv/lib/python3.7/site-packages/matplotlib/artist.py", line 230, in stale
    self.stale_callback(self, val)
  File "/path/to/my/pycharm/project/FakeSim/venv/lib/python3.7/site-packages/matplotlib/artist.py", line 51, in _stale_axes_callback
    self.axes.stale = val
  File "/path/to/my/pycharm/project/FakeSim/venv/lib/python3.7/site-packages/matplotlib/artist.py", line 230, in stale
    self.stale_callback(self, val)
  File "/path/to/my/pycharm/project/FakeSim/venv/lib/python3.7/site-packages/matplotlib/figure.py", line 51, in _stale_figure_callback
    self.figure.stale = val
  File "/path/to/my/pycharm/project/FakeSim/venv/lib/python3.7/site-packages/matplotlib/artist.py", line 230, in stale
    self.stale_callback(self, val)
  File "/path/to/my/pycharm/project/FakeSim/venv/lib/python3.7/site-packages/matplotlib/pyplot.py", line 583, in _auto_draw_if_interactive
    fig.canvas.draw_idle()
  File "/path/to/my/pycharm/project/FakeSim/venv/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 1907, in draw_idle
    self.draw(*args, **kwargs)
  File "/home/gregory/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/191.7479.30/helpers/pycharm_matplotlib_backend/backend_interagg.py", line 83, in draw
    FigureCanvasAgg.draw(self)
  File "/path/to/my/pycharm/project/FakeSim/venv/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 388, in draw
    self.figure.draw(self.renderer)
  File "/path/to/my/pycharm/project/FakeSim/venv/lib/python3.7/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/path/to/my/pycharm/project/FakeSim/venv/lib/python3.7/site-packages/matplotlib/figure.py", line 1709, in draw
    renderer, self, artists, self.suppressComposite)
  File "/path/to/my/pycharm/project/FakeSim/venv/lib/python3.7/site-packages/matplotlib/image.py", line 135, in _draw_list_compositing_images
    a.draw(renderer)
  File "/path/to/my/pycharm/project/FakeSim/venv/lib/python3.7/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/path/to/my/pycharm/project/FakeSim/venv/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 2645, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/path/to/my/pycharm/project/FakeSim/venv/lib/python3.7/site-packages/matplotlib/image.py", line 135, in _draw_list_compositing_images
    a.draw(renderer)
  File "/path/to/my/pycharm/project/FakeSim/venv/lib/python3.7/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/path/to/my/pycharm/project/FakeSim/venv/lib/python3.7/site-packages/matplotlib/axis.py", line 1204, in draw
    ticks_to_draw = self._update_ticks()
  File "/path/to/my/pycharm/project/FakeSim/venv/lib/python3.7/site-packages/matplotlib/axis.py", line 1080, in _update_ticks
    major_locs = self.get_majorticklocs()
  File "/path/to/my/pycharm/project/FakeSim/venv/lib/python3.7/site-packages/matplotlib/axis.py", line 1325, in get_majorticklocs
    return self.major.locator()
  File "/path/to/my/pycharm/project/FakeSim/venv/lib/python3.7/site-packages/matplotlib/ticker.py", line 2271, in __call__
    return self.tick_values(vmin, vmax)
  File "/path/to/my/pycharm/project/FakeSim/venv/lib/python3.7/site-packages/matplotlib/ticker.py", line 2297, in tick_values
    "Data has no positive values, and therefore can not be "
ValueError: Data has no positive values, and therefore can not be log-scaled.

Process finished with exit code 1
```

Expected outcome
Plot with logarithmic x-axis scale.

Matplotlib version
(also reproduced on Win64 with Python2.7, matplotlib 2.1)

    Operating system: Linux 64-bit
    Matplotlib version: '3.1.0'
    Matplotlib backend (print(matplotlib.get_backend())): Qt5Agg
    Python version: 3.7.3 (in pyenv)
    Jupyter version (if applicable): -
    Other libraries: numpy 1.16.4

**Comment by timhoffm** [comment]
This is not reproducible with the regular matplotlib backends. I assume this is an issue with pycharms own backend `backend_interagg`.

**Comment by tacaswell** [comment]
This is the intersection of several things:

 1. When an artist is changed in a way that makes the figure "stale" (that is a re-render is needed because the image has changed), it notifies it's parent recursively to the root.
 2. in interactive mode and not in IPython when the figure is marked as stale, it calls `draw_idle` on it's canvas.  This is so `ax.set_xlim(1, 2)` will work in the plain python prompt.  In that situation with the GUI backends, `draw_idle` eventually gets put on the GUI event loop and processed the next time that the input hook runs.  In IPython we install a hook that is run right before the user gets control back that checks if any figures known to pyplot are stale and then re-draws them.
 3. if a backend does not provide a `draw_idle` implemenation, we fallback to `draw` (maybe we should fallback to no-op?)
 4. the default limits before you plot anything are a bit negative, when `loglog` sets the scale it does so before it clips the limits.  Setting the scale marks the figure as stale, which in interactive mode with a backend that does not provide `draw_idle` attempts to draw the figure when it is in an inconsistent state (details about how we get to that state are a bit fuzzy, may have something wrong in this point, but I think the gist of it is correct).

**Comment by tacaswell** [comment]
attn @ktisha  @ Elizaveta239 (guessed you two because your names are on https://youtrack.jetbrains.com/issues?q=tag:%20%7Bscientific%20view%7D )

**Comment by Elizaveta239** [comment]
@tacaswell Thank you for letting us know! Created an issue in PyCharm tracker: https://youtrack.jetbrains.com/issue/PY-36698

**Comment by RylanSchaeffer** [comment]
Are there any updates on this? I'm hitting this error, frustratingly.

**Comment by jklymak** [comment]
@RylanSchaeffer please open anew issue with a reproducible self-contained minimal example.  Thanks
