### ISSUE TITLE
ValueError: ordinal must be >= 1

### ISSUE THREAD

**Issue by Moonpiiie** [matplotlib/matplotlib#9866]
import numpy as np
import scipy.stats as stats
import scipy.special as sp
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

file= 'data.xlsx'
x1 = pd.ExcelFile(file)
df1 = x1.parse('data')
plt.plot(df1['Time'],df1['PM2.5'])
plt.xlabel('Time')
plt.ylabel('PM2.5')
#plt.title()

pm=df1['PM2.5']
print(pm)
sns.distplot(pm)

runfile('C:/Users/xuehy/.spyder-py3/GEOL425.py', wdir='C:/Users/xuehy/.spyder-py3')
0       35.088570
1       34.517440
2       48.119690
3       42.489400
4       35.012850
5       49.380100
6       46.798300
7       43.837250
8       49.149050
9      152.004000
10      62.966450
11      74.801050
12      58.464600
13     101.668850
14      57.379650
15      54.862150
16      36.678270
17      38.448735
18      87.923565
19     111.452350
20      69.969350
21      87.508700
22      57.379200
23      63.828800
24      42.421650
25      66.872400
26      40.604200
27      22.188650
28      41.418753
29      33.769161
   
76       6.260794
77      94.557863
78      56.330748
79      30.524994
80      48.725127
81      45.991082
82      48.475571
83      11.976084
84      31.723201
85      15.354869
86      14.658562
87      17.662843
88      29.416903
89      19.487214
90      32.878614
91       9.829354
92      31.298012
93      37.042098
94      25.012096
95      24.478525
96      25.858073
97      27.166411
98      40.971386
99      29.743064
100     47.941417
101     58.532223
102     25.615453
103     36.277873
104     60.217282
105     41.612912
Name: PM2.5, Length: 106, dtype: float64
Traceback (most recent call last):

  File "C:\Users\xuehy\Anaconda3\lib\site-packages\IPython\core\formatters.py", line 332, in __call__
    return printer(obj)

  File "C:\Users\xuehy\Anaconda3\lib\site-packages\IPython\core\pylabtools.py", line 237, in <lambda>
    png_formatter.for_type(Figure, lambda fig: print_figure(fig, 'png', **kwargs))

  File "C:\Users\xuehy\Anaconda3\lib\site-packages\IPython\core\pylabtools.py", line 121, in print_figure
    fig.canvas.print_figure(bytes_io, **kw)

  File "C:\Users\xuehy\Anaconda3\lib\site-packages\matplotlib\backend_bases.py", line 2208, in print_figure
    **kwargs)

  File "C:\Users\xuehy\Anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py", line 507, in print_png
    FigureCanvasAgg.draw(self)

  File "C:\Users\xuehy\Anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py", line 430, in draw
    self.figure.draw(self.renderer)

  File "C:\Users\xuehy\Anaconda3\lib\site-packages\matplotlib\artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)

  File "C:\Users\xuehy\Anaconda3\lib\site-packages\matplotlib\figure.py", line 1295, in draw
    renderer, self, artists, self.suppressComposite)

  File "C:\Users\xuehy\Anaconda3\lib\site-packages\matplotlib\image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)

  File "C:\Users\xuehy\Anaconda3\lib\site-packages\matplotlib\artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)

  File "C:\Users\xuehy\Anaconda3\lib\site-packages\matplotlib\axes\_base.py", line 2399, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)

  File "C:\Users\xuehy\Anaconda3\lib\site-packages\matplotlib\image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)

  File "C:\Users\xuehy\Anaconda3\lib\site-packages\matplotlib\artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)

  File "C:\Users\xuehy\Anaconda3\lib\site-packages\matplotlib\axis.py", line 1133, in draw
    ticks_to_draw = self._update_ticks(renderer)

  File "C:\Users\xuehy\Anaconda3\lib\site-packages\matplotlib\axis.py", line 974, in _update_ticks
    tick_tups = list(self.iter_ticks())

  File "C:\Users\xuehy\Anaconda3\lib\site-packages\matplotlib\axis.py", line 917, in iter_ticks
    majorLocs = self.major.locator()

  File "C:\Users\xuehy\Anaconda3\lib\site-packages\matplotlib\dates.py", line 1054, in __call__
    self.refresh()

  File "C:\Users\xuehy\Anaconda3\lib\site-packages\matplotlib\dates.py", line 1074, in refresh
    dmin, dmax = self.viewlim_to_dt()

  File "C:\Users\xuehy\Anaconda3\lib\site-packages\matplotlib\dates.py", line 832, in viewlim_to_dt
    return num2date(vmin, self.tz), num2date(vmax, self.tz)

  File "C:\Users\xuehy\Anaconda3\lib\site-packages\matplotlib\dates.py", line 441, in num2date
    return _from_ordinalf(x, tz)

  File "C:\Users\xuehy\Anaconda3\lib\site-packages\matplotlib\dates.py", line 256, in _from_ordinalf
    dt = datetime.datetime.fromordinal(ix).replace(tzinfo=UTC)

ValueError: ordinal must be >= 1

<matplotlib.figure.Figure at 0x2175f02efd0>

**Comment by efiring** [comment]
If you think you have found a matplotlib bug, please provide a simple, self-contained example, using matplotlib alone--without pandas or seaborn.
My guess based on what you have here is that you are using a date that is out of the range handled by the pandas converter, so it is feeding matplotlib a negative number, which is then being caught by the python standard library datetime module.  See  http://pandas.pydata.org/pandas-docs/stable/timeseries.html#timestamp-limitations.  If you are working with geological data, for example, you can't use pandas in any way that involves dates and times.

**Comment by Moonpiiie** [comment]
I solved this problem by simply adding "plt.subplot(1,2,1)"

**Comment by efiring** [comment]
Good, I'm glad you found a simple solution.  In the future, questions like this might be better directed to the matplotlib-users@python.org mailing list.
