### ISSUE TITLE
drag/pan error when mouse click is not 1 or 3

### ISSUE THREAD

**Issue by raphaelvalentin** [matplotlib/matplotlib#9972]
Dear,
in a situation with qt backend, when I add the 'pan' action into a created context menu, I get an error with the pan function. Below, my error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/cbook/__init__.py", line 389, in process
    proxy(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/cbook/__init__.py", line 227, in __call__
    return mtd(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backend_bases.py", line 3056, in drag_pan
    a.drag_pan(self._button_pressed, event.key, event.x, event.y)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/axes/_base.py", line 3836, in drag_pan
    self.set_xlim(*result.intervalx)
UnboundLocalError: local variable 'result' referenced before assignment
```

The error may be related to the function 'drag_pan' in files 'axes._base.py'. From what I could understand, the mouse button other than 1 and 3 seems not taken into account as shown as below; maybe, such situation could be caught by adding an else statement. Matplotlib version == 2.1.0.

```
 if button == 1:
    dx, dy = format_deltas(key, dx, dy)
    result = p.bbox.translated(-dx, -dy) \
        .transformed(p.trans_inverse)
elif button == 3:
    try:
        dx = -dx / float(self.bbox.width)
        dy = -dy / float(self.bbox.height)
        dx, dy = format_deltas(key, dx, dy)
        if self.get_aspect() != 'auto':
            dx = 0.5 * (dx + dy)
            dy = dx

        alpha = np.power(10.0, (dx, dy))
        start = np.array([p.x, p.y])
        oldpoints = p.lim.transformed(p.trans)
        newpoints = start + alpha * (oldpoints - start)
        result = mtransforms.Bbox(newpoints) \
            .transformed(p.trans_inverse)
    except OverflowError:
        warnings.warn('Overflow while panning')
        return

self.set_xlim(*result.intervalx)
self.set_ylim(*result.intervaly)
```

Thank you for your support,

**Comment by dstansby** [comment]
Can you post the code that causes the error?

**Comment by anntzer** [comment]
drag_pan (and the other _pan functions) is quite clearly an implementation detail of interactive panning and should be made private...  But an example would still be nice.

**Comment by QuLogic** [comment]
Two months without response; closing.
