### ISSUE TITLE
Cannot update to MPL v2.1.1 on Anaconda

### ISSUE THREAD

**Issue by rayosborn** [matplotlib/matplotlib#9980]
### Bug report

**Bug summary**

Although I was able to update to Matplotlib v2.1.1 using `conda update matplotlib`, *i.e.*, on the default channel, I could not import `matplotlib.pyplot` because the installed version of `libpng` is not high enough. Attempting to update `libpng` to v1.6.34 (the highest available on condo-forge) causes conda to downgrade Matplotlib to v2.1.0.

**Code for reproduction**

```python
Python 3.6.1 |Anaconda custom (x86_64)| (default, May 11 2017, 13:04:09) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib.pyplot as plt
```

**Actual outcome**

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rosborn/anaconda/lib/python3.6/site-packages/matplotlib/pyplot.py", line 32, in <module>
    import matplotlib.colorbar
  File "/Users/rosborn/anaconda/lib/python3.6/site-packages/matplotlib/colorbar.py", line 36, in <module>
    import matplotlib.contour as contour
  File "/Users/rosborn/anaconda/lib/python3.6/site-packages/matplotlib/contour.py", line 21, in <module>
    import matplotlib.font_manager as font_manager
  File "/Users/rosborn/anaconda/lib/python3.6/site-packages/matplotlib/font_manager.py", line 58, in <module>
    from matplotlib import afm, cbook, ft2font, rcParams, get_cachedir
ImportError: dlopen(/Users/rosborn/anaconda/lib/python3.6/site-packages/matplotlib/ft2font.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libpng16.16.dylib
  Referenced from: /Users/rosborn/anaconda/lib/libfreetype.6.dylib
  Reason: Incompatible library version: libfreetype.6.dylib requires version 45.0.0 or later, but libpng16.16.dylib provides version 44.0.0
```
Here is the result of trying to update `libpng`.
```
$ conda update -c conda-forge libpng
Fetching package metadata .................
Solving package specifications: .

Package plan for installation in environment /Users/rosborn/anaconda:

The following packages will be UPDATED:

    libpng:     1.6.27-0                 --> 1.6.34-0     conda-forge

The following packages will be DOWNGRADED:

    freetype:   2.7-2        conda-forge --> 2.7-1        conda-forge
    matplotlib: 2.1.1-py36_0 conda-forge --> 2.1.0-py36_0 conda-forge
```

**Matplotlib version**
  * Operating system: Mac OS X 10.12.6
  * Matplotlib version: 2.1.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): MacOSX and PyQt5
  * Python version: 3.6.1

**Comment by QuLogic** [comment]
This is something you should report on the [matplotlib feedstock](https://github.com/conda-forge/matplotlib-feedstock/).

**Comment by rayosborn** [comment]
Are you sure that anyone monitors [matplotlib feedstock](https://github.com/conda-forge/matplotlib-feedstock/)? There doesn't seem to have been any activity since September, and this is a potentially serious issue for people using my software.
